pgxpool docs
cockroachdb/docs pull request #10030
Opened 2021-03-22 17:17 UTC by ericharmeling

Fixes https://github.com/cockroachdb/docs/issues/9879.

2021-03-22 17:17 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/10030)
<!-- Reviewable:end -->

2021-03-22 17:24 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4e0aceb518166f3ba986eea11b8647d16a0b40bb/

Edited pages:
- [v21.1/build-a-go-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4e0aceb518166f3ba986eea11b8647d16a0b40bb/v21.1/build-a-go-app-with-cockroachdb.html)
- [v21.1/build-a-java-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4e0aceb518166f3ba986eea11b8647d16a0b40bb/v21.1/build-a-java-app-with-cockroachdb.html)
- [v21.1/connection-pooling.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4e0aceb518166f3ba986eea11b8647d16a0b40bb/v21.1/connection-pooling.html)

2021-03-25 17:17 UTC, vy-ton requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10030)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[v21.1/connection-pooling.md, line 87 at r1](https://reviewable.io/reviews/cockroachdb/docs/10030#-MWeN0_gDS-vP2G69KqS:-MWeN0_gDS-vP2G69KqT:b-yl5atk) ([raw file](https://github.com/cockroachdb/docs/blob/4e0aceb518166f3ba986eea11b8647d16a0b40bb/v21.1/connection-pooling.md#L87)):*
> ```Markdown
> Using the connection pool formula above:
> 
> **connections = (10 [processor cores] * 3)**
> ```

Formula above is `* 4`, so the pool should be `40`?

Same issue with the Hikari example


<!-- Sent from Reviewable.io -->

2021-03-25 17:19 UTC, vy-ton approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10030)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[v21.1/build-a-go-app-with-cockroachdb.md, line 74 at r1](https://reviewable.io/reviews/cockroachdb/docs/10030#-MWeOJzgCukHEJAmBbzb:-MWeOJzgCukHEJAmBbzc:b-irgavt) ([raw file](https://github.com/cockroachdb/docs/blob/4e0aceb518166f3ba986eea11b8647d16a0b40bb/v21.1/build-a-go-app-with-cockroachdb.md#L74)):*
> ```Markdown
> 
> {{site.data.alerts.callout_success}}
> For guidance on connection pooling, with an example using the pgx connection pooling library ([pgxpool](https://pkg.go.dev/github.com/jackc/pgx/v4/pgxpool)), see [Connection Pooling](connection-pooling.html).
> ```

We should add `pgxpool` to the `Third-party tools` overview page as fully supported.


<!-- Sent from Reviewable.io -->

2021-03-29 15:38 UTC, ericharmeling reviewed
TFTR @vy-ton

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10030#-:-MWycUYA0TvEn-Z4-lzr:bmejyvy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ianjevans and @vy-ton)

___
*[v21.1/build-a-go-app-with-cockroachdb.md, line 74 at r1](https://reviewable.io/reviews/cockroachdb/docs/10030#-MWeOJzgCukHEJAmBbzb:-MWyWXk46rX8P_4udBb9:bylv224) ([raw file](https://github.com/cockroachdb/docs/blob/4e0aceb518166f3ba986eea11b8647d16a0b40bb/v21.1/build-a-go-app-with-cockroachdb.md#L74)):*
<details><summary><i>Previously, vy-ton (Vy Ton) wrote…</i></summary><blockquote>

We should add `pgxpool` to the `Third-party tools` overview page as fully supported.
</blockquote></details>

Because `pgxpool` is part of the `pgx` (it's a subdirectory of the `pgx` package directory: https://github.com/jackc/pgx/tree/master/pgxpool and listed as a feature of `pgx`: https://github.com/jackc/pgx#features), I'm concerned that explicitly adding `pgxpool` support to the tooling page implies that all other driver connection pooling capabilities are not supported (e.g., https://www.psycopg.org/docs/pool.html and https://node-postgres.com/features/pooling), which is not the case. 

IMO, claiming full support for `pgx` should be sufficient. It might be better to call out which core capabilities of a driver that we *do not* support, rather than which ones we do support. 
___
*[v21.1/connection-pooling.md, line 87 at r1](https://reviewable.io/reviews/cockroachdb/docs/10030#-MWeN0_gDS-vP2G69KqS:-MWyWZ4j3k9nr-dGmezC:bmvxft6) ([raw file](https://github.com/cockroachdb/docs/blob/4e0aceb518166f3ba986eea11b8647d16a0b40bb/v21.1/connection-pooling.md#L87)):*
<details><summary><i>Previously, vy-ton (Vy Ton) wrote…</i></summary><blockquote>

Formula above is `* 4`, so the pool should be `40`?

Same issue with the Hikari example
</blockquote></details>

Hmm... you are right. Fixed both.

@ianjevans Please confirm. I just copied the Hikari example for the pgxpool example. I assume the formula above the examples is the correct one? 


<!-- Sent from Reviewable.io -->

2021-03-29 15:44 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c846904c831d4e574946169ccc9cec8c8c765232/

Edited pages:
- [v20.2/build-a-go-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c846904c831d4e574946169ccc9cec8c8c765232/v20.2/build-a-go-app-with-cockroachdb.html)
- [v20.2/build-a-java-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c846904c831d4e574946169ccc9cec8c8c765232/v20.2/build-a-java-app-with-cockroachdb.html)
- [v20.2/connection-pooling.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c846904c831d4e574946169ccc9cec8c8c765232/v20.2/connection-pooling.html)
- [v21.1/build-a-go-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c846904c831d4e574946169ccc9cec8c8c765232/v21.1/build-a-go-app-with-cockroachdb.html)
- [v21.1/build-a-java-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c846904c831d4e574946169ccc9cec8c8c765232/v21.1/build-a-java-app-with-cockroachdb.html)
- [v21.1/connection-pooling.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c846904c831d4e574946169ccc9cec8c8c765232/v21.1/connection-pooling.html)

2021-03-29 20:37 UTC, ianjevans approved these changes

2021-03-29 20:51 UTC, merged