ALTER TYPE ... DROP VALUE
cockroachdb/docs pull request #10172
Opened 2021-03-24 20:12 UTC by ericharmeling

Fixes https://github.com/cockroachdb/docs/issues/10138.
Fixes https://github.com/cockroachdb/docs/issues/10060.
Fixes https://github.com/cockroachdb/docs/issues/10137.

2021-03-24 20:12 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/10172)
<!-- Reviewable:end -->

2021-03-24 20:18 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/caf9786eba0575432c9ddd5f930c300272a59a2c/

Edited pages:
- [v21.1/alter-type.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/caf9786eba0575432c9ddd5f930c300272a59a2c/v21.1/alter-type.html)
- [v21.1/cancel-job.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/caf9786eba0575432c9ddd5f930c300272a59a2c/v21.1/cancel-job.html)
- [v21.1/online-schema-changes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/caf9786eba0575432c9ddd5f930c300272a59a2c/v21.1/online-schema-changes.html)

2021-03-26 15:37 UTC, arulajmani requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10172)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[v21.1/alter-type.md, line 39 at r1](https://reviewable.io/reviews/cockroachdb/docs/10172#-MWj9e2N9rXwBO0E22kX:-MWj9e2OCOWjg5laU6DP:bj50jtd) ([raw file](https://github.com/cockroachdb/docs/blob/caf9786eba0575432c9ddd5f930c300272a59a2c/v21.1/alter-type.md#L39)):*
> ```Markdown
> 
> - You can only reference a user-defined type from the database that contains the type.
> - You can only [cancel](cancel-job.html) `ALTER TYPE`[schema change jobs](online-schema-changes.html) that drop values. All other `ALTER TYPE` schema change jobs are non-cancellable.
> ```

I wouldn't call this a limitation, it is by design -- all other jobs are expected to finish very quickly, but drop value jobs can take an arbitrarily long time. To that effect, these jobs are cancellable. 

One known limitation of `ALTER TYPE .. DROP VALUE` is that if the value is used in a table expression, such as a computed column or default expressions or view expressions, those expressions may stop working after the drop. Worth documenting I think. 
___
*[v21.1/cancel-job.md, line 20 at r1](https://reviewable.io/reviews/cockroachdb/docs/10172#-MWjA4OFEBuveImnAmlz:-MWjA4OFEBuveImnAmm-:bt3r3v6) ([raw file](https://github.com/cockroachdb/docs/blob/caf9786eba0575432c9ddd5f930c300272a59a2c/v21.1/cancel-job.md#L20)):*
> ```Markdown
> 
> - When an enterprise [`RESTORE`](restore.html) is canceled, partially restored data is properly cleaned up. This can have a minor, temporary impact on cluster performance.
> - You can only cancel [`ALTER TYPE`](alter-type.html) [schema change jobs](online-schema-changes.html) that drop values. All other `ALTER TYPE` schema change jobs are non-cancellable.
> ```

See my comment about limitations above. 


<!-- Sent from Reviewable.io -->

2021-03-29 17:34 UTC, ericharmeling reviewed
TFTR @arulajmani !

I think I addressed your comments. If everything looks good, I'll pass it over to writer review.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10172#-:-MWz1ydFAKO3N0PbVl6I:b-syy0gh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[v21.1/alter-type.md, line 39 at r1](https://reviewable.io/reviews/cockroachdb/docs/10172#-MWj9e2N9rXwBO0E22kX:-MWz-Im13KzNa2kmF4m4:brbe21g) ([raw file](https://github.com/cockroachdb/docs/blob/caf9786eba0575432c9ddd5f930c300272a59a2c/v21.1/alter-type.md#L39)):*
> I wouldn't call this a limitation, it is by design -- all other jobs are expected to finish very quickly, but drop value jobs can take an arbitrarily long time. To that effect, these jobs are cancellable.

Right on. If the text is correct, then I'll just make it a note at the top of the page. 

> One known limitation of ALTER TYPE .. DROP VALUE is that if the value is used in a table expression, such as a computed column or default expressions or view expressions, those expressions may stop working after the drop. Worth documenting I think.


I had a note in the `DROP VALUE` parameter description for this, but I agree that it is more of a limitation. I added it to the limitations and trimmed the parameter description a bit.
___
*[v21.1/cancel-job.md, line 20 at r1](https://reviewable.io/reviews/cockroachdb/docs/10172#-MWjA4OFEBuveImnAmlz:-MWz-SnF7bDiRtUu7W2P:b-gqza0s) ([raw file](https://github.com/cockroachdb/docs/blob/caf9786eba0575432c9ddd5f930c300272a59a2c/v21.1/cancel-job.md#L20)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

See my comment about limitations above. 
</blockquote></details>

Removed this from the list of limitations.


<!-- Sent from Reviewable.io -->

2021-03-29 17:38 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/09d2f2824f7d35cf4696a1917c75ed31f4edad87/

Edited pages:
- [v21.1/alter-type.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/09d2f2824f7d35cf4696a1917c75ed31f4edad87/v21.1/alter-type.html)
- [v21.1/cancel-job.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/09d2f2824f7d35cf4696a1917c75ed31f4edad87/v21.1/cancel-job.html)
- [v21.1/online-schema-changes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/09d2f2824f7d35cf4696a1917c75ed31f4edad87/v21.1/online-schema-changes.html)

2021-03-29 20:34 UTC, ianjevans approved these changes

2021-03-29 20:50 UTC, merged