Document simulating a multi-region cluster locally
cockroachdb/docs pull request #10185
Opened 2021-03-25 19:14 UTC by rmloveland

Fixes #10007.

Summary of changes:

- Add a new page 'Simulate a multi-region cluster on localhost', with
  instructions for using `cockroach demo --global ...` This will be part
  of the infrastructure for creating/updating multi-region demos in our
  docs that highlight the new features coming for v21.1.

2021-03-25 19:14 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/10185)
<!-- Reviewable:end -->

2021-03-25 19:19 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/dcb31dc1347492f2a8da4d4d7ce33bd761ab061f/

Edited pages:
- [v21.1/cockroach-demo.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/dcb31dc1347492f2a8da4d4d7ce33bd761ab061f/v21.1/cockroach-demo.html)
- [v21.1/frequently-asked-questions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/dcb31dc1347492f2a8da4d4d7ce33bd761ab061f/v21.1/frequently-asked-questions.html)
- [v21.1/simulate-a-multi-region-cluster-on-localhost.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/dcb31dc1347492f2a8da4d4d7ce33bd761ab061f/v21.1/simulate-a-multi-region-cluster-on-localhost.html)

2021-04-06 15:07 UTC, awoods187 approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10185)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rmloveland)

___
*[v21.1/simulate-a-multi-region-cluster-on-localhost.md, line 3 at r1](https://reviewable.io/reviews/cockroachdb/docs/10185#-MXbhNEk8sICTkO5B4Gv:-MXbhNEk8sICTkO5B4Gw:b-l83w8i) ([raw file](https://github.com/cockroachdb/docs/blob/dcb31dc1347492f2a8da4d4d7ce33bd761ab061f/v21.1/simulate-a-multi-region-cluster-on-localhost.md#L3)):*
> ```Markdown
> ---
> title: Simulate a Multi-Region Cluster on localhost (insecure)
> summary: Run an insecure simulated multi-region CockroachDB cluster locally using 'cockroach demo'.
> ```

i dont think insecure/secure matters as a dimension here. I'd use secure
___
*[v21.1/simulate-a-multi-region-cluster-on-localhost.md, line 17 at r1](https://reviewable.io/reviews/cockroachdb/docs/10185#-MXbhm_5AbDamngDAj2j:-MXbhm_5AbDamngDAj2k:blezq15) ([raw file](https://github.com/cockroachdb/docs/blob/dcb31dc1347492f2a8da4d4d7ce33bd761ab061f/v21.1/simulate-a-multi-region-cluster-on-localhost.md#L17)):*
> ```Markdown
> ## Step 1. Start the cluster
> 
> Use the [`cockroach demo`](cockroach-demo.html) command shown below to start the cluster. This particular combination of flags results in an in-memory cluster of 9 nodes, with 3 nodes in each region. It sets the appropriate [node localities](cockroach-start.html#locality) and also simulates the network latency that would occur between nodes in these localities. For more information about each flag, see the [`cockroach demo`](cockroach-demo.html#flags) documentation, especially for [`--global`](cockroach-demo.html#global-flag).
> ```

do people understand "in-memory" I usually say this creates "ephemeral simulated nodes on my laptop"
___
*[v21.1/simulate-a-multi-region-cluster-on-localhost.md, line 21 at r1](https://reviewable.io/reviews/cockroachdb/docs/10185#-MXbhfGA2_IjXmMyK9Hd:-MXbhfGA2_IjXmMyK9He:b-bd5y6u) ([raw file](https://github.com/cockroachdb/docs/blob/dcb31dc1347492f2a8da4d4d7ce33bd761ab061f/v21.1/simulate-a-multi-region-cluster-on-localhost.md#L21)):*
> ```Markdown
> {% include copy-clipboard.html %}
> ~~~ shell
> $ cockroach demo --global --nodes 9 --empty --insecure
> ```

see above you don't need to pass --insecure
___
*[v21.1/simulate-a-multi-region-cluster-on-localhost.md, line 93 at r1](https://reviewable.io/reviews/cockroachdb/docs/10185#-MXbi2D0BfFon2sG9QEB:-MXbi2D0BfFon2sG9QEC:boemx62) ([raw file](https://github.com/cockroachdb/docs/blob/dcb31dc1347492f2a8da4d4d7ce33bd761ab061f/v21.1/simulate-a-multi-region-cluster-on-localhost.md#L93)):*
> ```Markdown
> The [DB Console](ui-overview.html) gives you insight into the overall health of your cluster, as well as the performance of any [client workloads](cockroach-workload.html).
> 
> To verify that the 9 nodes you specified are up and running as expected, go to the [**Cluster Overview**](ui-cluster-overview-page.html) at <a href="http://localhost:8080/#/overview/list" data-proofer-ignore>http://localhost:8080/#/overview/list</a>.
> ```

you can cmd click for the dbconsole and it works to log you in with secure clusters


<!-- Sent from Reviewable.io -->

2021-04-08 16:43 UTC, ajstorm requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10185)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rmloveland)

___
*[v21.1/cockroach-demo.md, line 115 at r1](https://reviewable.io/reviews/cockroachdb/docs/10185#-MXlzTqw93g1-6bXvkoA:-MXlzTqx7o_ab1vp6i2S:b-2tngx4) ([raw file](https://github.com/cockroachdb/docs/blob/dcb31dc1347492f2a8da4d4d7ce33bd761ab061f/v21.1/cockroach-demo.md#L115)):*
> ```Markdown
> `--format` | How to display table rows printed to the standard output. Possible values: `tsv`, `csv`, `table`, `raw`, `records`, `sql`, `html`.<br><br>**Default:** `table` for sessions that [output on a terminal](cockroach-sql.html#session-and-output-types); `tsv` otherwise<br /><br />This flag corresponds to the `display_format` [client-side option](#client-side-options) for use in interactive sessions.
> `--geo-partitioned-replicas` | Start a 9-node demo cluster with the [Geo-Partitioned Replicas](topology-geo-partitioned-replicas.html) topology pattern applied to the [`movr`](movr.html) database.
> `--global` | <a name="global-flag"></a> Simulate a [multi-region cluster](simulate-a-multi-region-cluster-on-localhost.html) which sets the [node localities](cockroach-start.html#locality) in different regions, and also simulates the network latency that would occur between them given the specified localities.  In order for this to operate as expected, with 3 nodes in each of 3 regions, you must also pass the `--nodes 9` argument.
> ```

Nit: I'm wondering if we should use something other than "node localities" here.  Would "--locality flag on node startup" work better for searching and precision.

Nit: "in different regions" -> "in three different regions"

Based on the conversation this week, we should also note that --global is experimental for the time being.
___
*[v21.1/simulate-a-multi-region-cluster-on-localhost.md, line 12 at r1](https://reviewable.io/reviews/cockroachdb/docs/10185#-MXmJPiG1HO5MJ02KY6k:-MXmJPiG1HO5MJ02KY6l:b-flxz7i) ([raw file](https://github.com/cockroachdb/docs/blob/dcb31dc1347492f2a8da4d4d7ce33bd761ab061f/v21.1/simulate-a-multi-region-cluster-on-localhost.md#L12)):*
> ```Markdown
> 
> - Make sure you have already [installed CockroachDB](install-cockroachdb.html).
> - Note that simulating multiple geographically distributed nodes on a single host is useful for testing, but not for production. It is especially not representative of the [performance you should expect](frequently-asked-questions.html#single-row-perf) of a production deployment.
> ```

This statement struck me as a bit strange, just because we're using demo.  Can we add something here which talks about how demo in general should never be used in production (for a number of reasons, not least of which is the fact that it doesn't persist state).
___
*[v21.1/simulate-a-multi-region-cluster-on-localhost.md, line 64 at r1](https://reviewable.io/reviews/cockroachdb/docs/10185#-MXmK3JsC9iwpXzh1Bcv:-MXmK3Jt8_c5IUOE20St:be12ndb) ([raw file](https://github.com/cockroachdb/docs/blob/dcb31dc1347492f2a8da4d4d7ce33bd761ab061f/v21.1/simulate-a-multi-region-cluster-on-localhost.md#L64)):*
> ```Markdown
> {% include copy-clipboard.html %}
> ~~~ sql
> > CREATE DATABASE bank;
> ```

Are we missing a `USE bank;` here?
___
*[v21.1/simulate-a-multi-region-cluster-on-localhost.md, line 69 at r1](https://reviewable.io/reviews/cockroachdb/docs/10185#-MXmLNy3BI36YPVZCeOl:-MXmLNy414PDFm3VR2TU:b9gzmm) ([raw file](https://github.com/cockroachdb/docs/blob/dcb31dc1347492f2a8da4d4d7ce33bd761ab061f/v21.1/simulate-a-multi-region-cluster-on-localhost.md#L69)):*
> ```Markdown
> {% include copy-clipboard.html %}
> ~~~ sql
> > CREATE TABLE bank.accounts (id INT PRIMARY KEY, balance DECIMAL);
> ```

Does it make sense to add at least some commands here which leverage multi-region syntax?  Maybe create the database in a number of regions and create a GLOBAL table?
___
*[v21.1/simulate-a-multi-region-cluster-on-localhost.md, line 115 at r1](https://reviewable.io/reviews/cockroachdb/docs/10185#-MXmMOtV0xiZEBa-7TOE:-MXmMOtV0xiZEBa-7TOF:bxiig6l) ([raw file](https://github.com/cockroachdb/docs/blob/dcb31dc1347492f2a8da4d4d7ce33bd761ab061f/v21.1/simulate-a-multi-region-cluster-on-localhost.md#L115)):*
> ```Markdown
> {% include copy-clipboard.html %}
> ~~~ sql
> \q
> ```

Nit: Does it make more sense to change this to `quit`?  


<!-- Sent from Reviewable.io -->

2021-04-12 20:06 UTC, rmloveland reviewed
Thanks for the reviews Andy and Adam!  I have made updates based on your feedback

please let me know what you think

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10185#-:-MY6dO-O8t59_Z_OxTek:b-kng1t5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @awoods187)

___
*[v21.1/cockroach-demo.md, line 115 at r1](https://reviewable.io/reviews/cockroachdb/docs/10185#-MXlzTqw93g1-6bXvkoA:-MY6e4JH8ONs4q7lJgf1:b-7m3b93) ([raw file](https://github.com/cockroachdb/docs/blob/dcb31dc1347492f2a8da4d4d7ce33bd761ab061f/v21.1/cockroach-demo.md#L115)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: I'm wondering if we should use something other than "node localities" here.  Would "--locality flag on node startup" work better for searching and precision.

Nit: "in different regions" -> "in three different regions"

Based on the conversation this week, we should also note that --global is experimental for the time being.
</blockquote></details>

Good points all.  Have updated to use the new language, as well as mention it's experimental - PTAL
___
*[v21.1/simulate-a-multi-region-cluster-on-localhost.md, line 3 at r1](https://reviewable.io/reviews/cockroachdb/docs/10185#-MXbhNEk8sICTkO5B4Gv:-MY6ZcML1jICwulEGNqZ:bmd7g64) ([raw file](https://github.com/cockroachdb/docs/blob/dcb31dc1347492f2a8da4d4d7ce33bd761ab061f/v21.1/simulate-a-multi-region-cluster-on-localhost.md#L3)):*
<details><summary><i>Previously, awoods187 (Andy Woods) wrote…</i></summary><blockquote>

i dont think insecure/secure matters as a dimension here. I'd use secure
</blockquote></details>

Agreed - removed the unnecessary mention of "insecure" from this
___
*[v21.1/simulate-a-multi-region-cluster-on-localhost.md, line 12 at r1](https://reviewable.io/reviews/cockroachdb/docs/10185#-MXmJPiG1HO5MJ02KY6k:-MY6ZhYv24FTI5sCIugv:bhn6rrc) ([raw file](https://github.com/cockroachdb/docs/blob/dcb31dc1347492f2a8da4d4d7ce33bd761ab061f/v21.1/simulate-a-multi-region-cluster-on-localhost.md#L12)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

This statement struck me as a bit strange, just because we're using demo.  Can we add something here which talks about how demo in general should never be used in production (for a number of reasons, not least of which is the fact that it doesn't persist state).
</blockquote></details>

Tweaked the language here a bit to note that demo is not ok in prod

Also updated the `cockroach demo` docs to say "this is not suitable for production", which was apparently not written down explicitly there.
___
*[v21.1/simulate-a-multi-region-cluster-on-localhost.md, line 17 at r1](https://reviewable.io/reviews/cockroachdb/docs/10185#-MXbhm_5AbDamngDAj2j:-MY6b6kw5X43bjISujYB:b58xmdy) ([raw file](https://github.com/cockroachdb/docs/blob/dcb31dc1347492f2a8da4d4d7ce33bd761ab061f/v21.1/simulate-a-multi-region-cluster-on-localhost.md#L17)):*
<details><summary><i>Previously, awoods187 (Andy Woods) wrote…</i></summary><blockquote>

do people understand "in-memory" I usually say this creates "ephemeral simulated nodes on my laptop"
</blockquote></details>

changed to say "demo cluster", and we'll rely on the `cockroach demo` docs to provide such details
___
*[v21.1/simulate-a-multi-region-cluster-on-localhost.md, line 21 at r1](https://reviewable.io/reviews/cockroachdb/docs/10185#-MXbhfGA2_IjXmMyK9Hd:-MY6bCKo3EvQakIG92Gi:b-f213k6) ([raw file](https://github.com/cockroachdb/docs/blob/dcb31dc1347492f2a8da4d4d7ce33bd761ab061f/v21.1/simulate-a-multi-region-cluster-on-localhost.md#L21)):*
<details><summary><i>Previously, awoods187 (Andy Woods) wrote…</i></summary><blockquote>

see above you don't need to pass --insecure
</blockquote></details>

Unfortunately I needed this so I could point movr at the cluster and get it to work in #10235  
___
*[v21.1/simulate-a-multi-region-cluster-on-localhost.md, line 64 at r1](https://reviewable.io/reviews/cockroachdb/docs/10185#-MXmK3JsC9iwpXzh1Bcv:-MY6bZQ12q-GAXMvF99N:b2mc9ya) ([raw file](https://github.com/cockroachdb/docs/blob/dcb31dc1347492f2a8da4d4d7ce33bd761ab061f/v21.1/simulate-a-multi-region-cluster-on-localhost.md#L64)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Are we missing a `USE bank;` here?
</blockquote></details>

Yes! Thanks, added
___
*[v21.1/simulate-a-multi-region-cluster-on-localhost.md, line 69 at r1](https://reviewable.io/reviews/cockroachdb/docs/10185#-MXmLNy3BI36YPVZCeOl:-MY6baQ9CM0mswdL-PGg:b-7vppyp) ([raw file](https://github.com/cockroachdb/docs/blob/dcb31dc1347492f2a8da4d4d7ce33bd761ab061f/v21.1/simulate-a-multi-region-cluster-on-localhost.md#L69)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Does it make sense to add at least some commands here which leverage multi-region syntax?  Maybe create the database in a number of regions and create a GLOBAL table?
</blockquote></details>

This is happening in #10235 .  When these are both in I will link to that doc from this one as a "next step" type thing

Don't wanna do it here because there is too much explanatory overhead for the localities / etc. which we will do in the actual tutorial(s)

This page will be a base prerequisite for all the multi-region tutorial type things going forward (until multi-region Cloud is there Someday Real Soon Now (tm) )
___
*[v21.1/simulate-a-multi-region-cluster-on-localhost.md, line 93 at r1](https://reviewable.io/reviews/cockroachdb/docs/10185#-MXbi2D0BfFon2sG9QEB:-MY6cAmr7bIaXnru9_fO:bbfse64) ([raw file](https://github.com/cockroachdb/docs/blob/dcb31dc1347492f2a8da4d4d7ce33bd761ab061f/v21.1/simulate-a-multi-region-cluster-on-localhost.md#L93)):*
<details><summary><i>Previously, awoods187 (Andy Woods) wrote…</i></summary><blockquote>

you can cmd click for the dbconsole and it works to log you in with secure clusters
</blockquote></details>

Interesting!  I went with insecure for the reasons described above (pointing external Dockerized movr workloads at this in #10235) 
___
*[v21.1/simulate-a-multi-region-cluster-on-localhost.md, line 115 at r1](https://reviewable.io/reviews/cockroachdb/docs/10185#-MXmMOtV0xiZEBa-7TOE:-MY6cJOp4fha2miA3tjd:b-bk5ipd) ([raw file](https://github.com/cockroachdb/docs/blob/dcb31dc1347492f2a8da4d4d7ce33bd761ab061f/v21.1/simulate-a-multi-region-cluster-on-localhost.md#L115)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Does it make more sense to change this to `quit`?  
</blockquote></details>

Works for me!


<!-- Sent from Reviewable.io -->

2021-04-13 01:43 UTC, awoods187 approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10185)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)



<!-- Sent from Reviewable.io -->

2021-04-13 12:25 UTC, ajstorm approved these changes
I like the changes.  <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10185#-:-MYABLgz6AT86MEsRb_K:b6f83hp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[v21.1/cockroach-demo.md, line 115 at r1](https://reviewable.io/reviews/cockroachdb/docs/10185#-MXlzTqw93g1-6bXvkoA:-MYAArMuCNmzZZn5Bi_S:b-ee3n42) ([raw file](https://github.com/cockroachdb/docs/blob/dcb31dc1347492f2a8da4d4d7ce33bd761ab061f/v21.1/cockroach-demo.md#L115)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Good points all.  Have updated to use the new language, as well as mention it's experimental - PTAL
</blockquote></details>

Looks good. We're still debating whether "experimental" is the right term to use, but we can come back to that later.


<!-- Sent from Reviewable.io -->

2021-04-13 15:03 UTC, rmloveland reviewed
SWEET - thanks Adam!  And thanks Andy!

Passing on to docs team reviewer

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10185#-:-MYAk_da1fTtBZQjJpjv:buzk0qy)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm)

___
*[v21.1/cockroach-demo.md, line 115 at r1](https://reviewable.io/reviews/cockroachdb/docs/10185#-MXlzTqw93g1-6bXvkoA:-MYAkXvU9KGt7-cfmxMy:bupbap9) ([raw file](https://github.com/cockroachdb/docs/blob/dcb31dc1347492f2a8da4d4d7ce33bd761ab061f/v21.1/cockroach-demo.md#L115)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Looks good. We're still debating whether "experimental" is the right term to use, but we can come back to that later.
</blockquote></details>

OK! Yeah, easy to change it


<!-- Sent from Reviewable.io -->

2021-04-14 19:01 UTC, lnhsingh reviewed
A couple small edits. Once addressed, LGTM!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10185#-:-MYGkbPj4qOJB8Eh6JVG:b-5paz5t)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm and @rmloveland)

___
*[v21.1/cockroach-demo.md, line 14 at r2](https://reviewable.io/reviews/cockroachdb/docs/10185#-MYGifb5CR4k542ZLKYh:-MYGifb5CR4k542ZLKYi:b-nsu54n) ([raw file](https://github.com/cockroachdb/docs/blob/c77be73f5139644e99ea74db35c1b51ab7a3b9e5/v21.1/cockroach-demo.md#L14)):*
> ```Markdown
> 
> {{site.data.alerts.callout_danger}}
> `cockroach demo` is designed for testing purposes only. It is not suitable for production deployments.  To see a list of recommendations for production deployments, see the [Production Checklist](recommended-production-settings.html).
> ```

nit: extra space after period
___
*[v21.1/cockroach-demo.md, line 119 at r2](https://reviewable.io/reviews/cockroachdb/docs/10185#-MYGijxG6sLhicKefVKt:-MYGijxH0WrA5W5BykUY:b-rhuq1w) ([raw file](https://github.com/cockroachdb/docs/blob/c77be73f5139644e99ea74db35c1b51ab7a3b9e5/v21.1/cockroach-demo.md#L119)):*
> ```Markdown
> `--format` | How to display table rows printed to the standard output. Possible values: `tsv`, `csv`, `table`, `raw`, `records`, `sql`, `html`.<br><br>**Default:** `table` for sessions that [output on a terminal](cockroach-sql.html#session-and-output-types); `tsv` otherwise<br /><br />This flag corresponds to the `display_format` [client-side option](#client-side-options) for use in interactive sessions.
> `--geo-partitioned-replicas` | Start a 9-node demo cluster with the [Geo-Partitioned Replicas](topology-geo-partitioned-replicas.html) topology pattern applied to the [`movr`](movr.html) database.
> `--global` | <a name="global-flag"></a> This experimental flag is used to simulate a [multi-region cluster](simulate-a-multi-region-cluster-on-localhost.html) which sets the [`--locality` flag on node startup](cockroach-start.html#locality) to three different regions. It also simulates the network latency that would occur between them given the specified localities.  In order for this to operate as expected, with 3 nodes in each of 3 regions, you must also pass the `--nodes 9` argument.
> ```

nit: extra space
___
*[v21.1/simulate-a-multi-region-cluster-on-localhost.md, line 2 at r2](https://reviewable.io/reviews/cockroachdb/docs/10185#-MYGimVZBPaNf-BMEsfs:-MYGimVZBPaNf-BMEsft:b-4mt5m2) ([raw file](https://github.com/cockroachdb/docs/blob/c77be73f5139644e99ea74db35c1b51ab7a3b9e5/v21.1/simulate-a-multi-region-cluster-on-localhost.md#L2)):*
> ```Markdown
> ---
> title: Simulate a Multi-Region Cluster on localhost (insecure)
> ```

nit: capitalize Insecure
___
*[v21.1/simulate-a-multi-region-cluster-on-localhost.md, line 3 at r2](https://reviewable.io/reviews/cockroachdb/docs/10185#-MYGis7SDtRI-gveD-LP:-MYGis7SDtRI-gveD-LQ:bw1iemu) ([raw file](https://github.com/cockroachdb/docs/blob/c77be73f5139644e99ea74db35c1b51ab7a3b9e5/v21.1/simulate-a-multi-region-cluster-on-localhost.md#L3)):*
> ```Markdown
> ---
> title: Simulate a Multi-Region Cluster on localhost (insecure)
> summary: Run a simulated multi-region CockroachDB cluster locally using 'cockroach demo'.
> ```

Does `cockroach demo` need to have backticks here instead of single quotes? I'm not sure if it matters for the summary or not (if not, I might remove the single quotes)?
___
*[v21.1/simulate-a-multi-region-cluster-on-localhost.md, line 12 at r2](https://reviewable.io/reviews/cockroachdb/docs/10185#-MYGjIXR7w58EbU3LhED:-MYGjIXR7w58EbU3LhEE:b-jsv131) ([raw file](https://github.com/cockroachdb/docs/blob/c77be73f5139644e99ea74db35c1b51ab7a3b9e5/v21.1/simulate-a-multi-region-cluster-on-localhost.md#L12)):*
> ```Markdown
> 
> - Make sure you have already [installed CockroachDB](install-cockroachdb.html).
> - Note that [`cockroach demo`](cockroach-demo.html) is not suitable for production deployments.  Additionally, simulating multiple geographically distributed nodes on a single host is not representative of the [performance you should expect](frequently-asked-questions.html#single-row-perf) of a production deployment.
> ```

This bullet point and it's sub-bullet don't seem to belong in "Before you begin". I would suggest moving this into a callout and move it to the intro/overview section above this section.
___
*[v21.1/simulate-a-multi-region-cluster-on-localhost.md, line 24 at r2](https://reviewable.io/reviews/cockroachdb/docs/10185#-MYGkMFDA5GmvEVgbK95:-MYGkMFDA5GmvEVgbK96:b-hl6ntr) ([raw file](https://github.com/cockroachdb/docs/blob/c77be73f5139644e99ea74db35c1b51ab7a3b9e5/v21.1/simulate-a-multi-region-cluster-on-localhost.md#L24)):*
> ```Markdown
> ~~~
> 
> When the cluster starts, you'll see a message like the one shown below, followed by a SQL prompt.
> ```

I would suggest moving the code block to be right after this sentence since you say "...see a message like the one shown below...", but up to you. If you do move it, there is a risk that the next "note the URLs" section gets overlooked.
___
*[v21.1/simulate-a-multi-region-cluster-on-localhost.md, line 26 at r2](https://reviewable.io/reviews/cockroachdb/docs/10185#-MYGjeiOBJaDP3rkTAVf:-MYGjeiOBJaDP3rkTAVg:bn4zi2w) ([raw file](https://github.com/cockroachdb/docs/blob/c77be73f5139644e99ea74db35c1b51ab7a3b9e5/v21.1/simulate-a-multi-region-cluster-on-localhost.md#L26)):*
> ```Markdown
> When the cluster starts, you'll see a message like the one shown below, followed by a SQL prompt.
> 
> Note the URLs for:
> ```

This isn't rendering as a bulleted list. I think you need an empty line between the colon and the list.


<!-- Sent from Reviewable.io -->

2021-04-15 15:42 UTC, rmloveland reviewed
Thanks Lauren!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10185#-:-MYL9xcbAhLgg5ECD2BB:b-jia9os)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm and @lnhsingh)

___
*[v21.1/cockroach-demo.md, line 14 at r2](https://reviewable.io/reviews/cockroachdb/docs/10185#-MYGifb5CR4k542ZLKYh:-MYL8DSRASTLzPmhZU8n:bt2vr0y) ([raw file](https://github.com/cockroachdb/docs/blob/c77be73f5139644e99ea74db35c1b51ab7a3b9e5/v21.1/cockroach-demo.md#L14)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

nit: extra space after period
</blockquote></details>

Fixed!
___
*[v21.1/cockroach-demo.md, line 119 at r2](https://reviewable.io/reviews/cockroachdb/docs/10185#-MYGijxG6sLhicKefVKt:-MYL8EPhAuCJqaxo2HAt:b-wlneke) ([raw file](https://github.com/cockroachdb/docs/blob/c77be73f5139644e99ea74db35c1b51ab7a3b9e5/v21.1/cockroach-demo.md#L119)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

nit: extra space
</blockquote></details>

Fixed! SPACE TYRANT
___
*[v21.1/simulate-a-multi-region-cluster-on-localhost.md, line 2 at r2](https://reviewable.io/reviews/cockroachdb/docs/10185#-MYGimVZBPaNf-BMEsfs:-MYL8OZY8KeviXpEeatX:b-886gsx) ([raw file](https://github.com/cockroachdb/docs/blob/c77be73f5139644e99ea74db35c1b51ab7a3b9e5/v21.1/simulate-a-multi-region-cluster-on-localhost.md#L2)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

nit: capitalize Insecure
</blockquote></details>

Fixed
___
*[v21.1/simulate-a-multi-region-cluster-on-localhost.md, line 3 at r2](https://reviewable.io/reviews/cockroachdb/docs/10185#-MYGis7SDtRI-gveD-LP:-MYL8PZtEVa2lstudhUQ:b-5tw4by) ([raw file](https://github.com/cockroachdb/docs/blob/c77be73f5139644e99ea74db35c1b51ab7a3b9e5/v21.1/simulate-a-multi-region-cluster-on-localhost.md#L3)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Does `cockroach demo` need to have backticks here instead of single quotes? I'm not sure if it matters for the summary or not (if not, I might remove the single quotes)?
</blockquote></details>

I have removed the single quotes.  If memory serves, markdown things do not render because it is YAML
___
*[v21.1/simulate-a-multi-region-cluster-on-localhost.md, line 12 at r2](https://reviewable.io/reviews/cockroachdb/docs/10185#-MYGjIXR7w58EbU3LhED:-MYL8wUyAGLgb6pG6N0Y:bb6un1j) ([raw file](https://github.com/cockroachdb/docs/blob/c77be73f5139644e99ea74db35c1b51ab7a3b9e5/v21.1/simulate-a-multi-region-cluster-on-localhost.md#L12)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

This bullet point and it's sub-bullet don't seem to belong in "Before you begin". I would suggest moving this into a callout and move it to the intro/overview section above this section.
</blockquote></details>

Done
___
*[v21.1/simulate-a-multi-region-cluster-on-localhost.md, line 24 at r2](https://reviewable.io/reviews/cockroachdb/docs/10185#-MYGkMFDA5GmvEVgbK95:-MYL9PU5Eej1PZWDUZvi:be49rx0) ([raw file](https://github.com/cockroachdb/docs/blob/c77be73f5139644e99ea74db35c1b51ab7a3b9e5/v21.1/simulate-a-multi-region-cluster-on-localhost.md#L24)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

I would suggest moving the code block to be right after this sentence since you say "...see a message like the one shown below...", but up to you. If you do move it, there is a risk that the next "note the URLs" section gets overlooked.
</blockquote></details>

I sorta (?) split the difference by smushing the paras together so the code block doesn't seem so "far away".  I do want the reader to see the bit about the URLs before getting tossed into all the node startup noise
___
*[v21.1/simulate-a-multi-region-cluster-on-localhost.md, line 26 at r2](https://reviewable.io/reviews/cockroachdb/docs/10185#-MYGjeiOBJaDP3rkTAVf:-MYL9fHl-5F1txJ6Vmq6:bt2vr0y) ([raw file](https://github.com/cockroachdb/docs/blob/c77be73f5139644e99ea74db35c1b51ab7a3b9e5/v21.1/simulate-a-multi-region-cluster-on-localhost.md#L26)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

This isn't rendering as a bulleted list. I think you need an empty line between the colon and the list.
</blockquote></details>

Fixed!


<!-- Sent from Reviewable.io -->

2021-04-15 15:49 UTC, merged