Update multi-region low latency demo for v21.1
cockroachdb/docs pull request #10235
Opened 2021-04-05 16:30 UTC by rmloveland

Fixes #10001.

Summary of changes:

- Port 'Low Latency Reads and Writes in a Multi-Region Cluster' to use
  new multi-region SQL statements, etc.

- Along the way we shorten it considerably, since:

  - It now depends on a separate page showing you how to spin up a local
    simulated multi-region cluster

  - It focuses on latency and does not get into low-level concerns like
    checking replica placement from SQL

2021-04-05 16:31 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/10235)
<!-- Reviewable:end -->

2021-04-05 18:57 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/36529c844734ab84260c4275255e22ad2f95e41d/

Edited pages:
- [v21.1/architecture/reads-and-writes-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/36529c844734ab84260c4275255e22ad2f95e41d/v21.1/architecture/reads-and-writes-overview.html)
- [v21.1/demo-low-latency-multi-region-deployment.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/36529c844734ab84260c4275255e22ad2f95e41d/v21.1/demo-low-latency-multi-region-deployment.html)
- [v21.1/ui-network-latency-page.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/36529c844734ab84260c4275255e22ad2f95e41d/v21.1/ui-network-latency-page.html)

2021-04-07 14:59 UTC, awoods187 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10235)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @rmloveland)

___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 12 at r1](https://reviewable.io/reviews/cockroachdb/docs/10235#-MXgouYK3xrwdL0RbSRi:-MXgouYK3xrwdL0RbSRj:bj6f8ll) ([raw file](https://github.com/cockroachdb/docs/blob/36529c844734ab84260c4275255e22ad2f95e41d/v21.1/demo-low-latency-multi-region-deployment.md#L12)):*
> ```Markdown
> <span class="version-tag">New in v21.1:</span> CockroachDB has improved multi-region capabilities that make it easier to run global applications. For an overview of these capabilities, see the [Multi-region Overview](multiregion-overview.html).
> 
> In multi-region clusters, the distribution of data becomes a performance consideration. This makes it important to think about the latency requirements of each table and then use the right combination of [survival goals](multiregion-overview.html#survival-goals) and [table localities](multiregion-overview.html#table-locality) to locate data for optimal performance.
> ```

I usually think of it as you have survival goals and then you do the best you can via latency rather than you go for latency and then decide survival goals. 
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 22 at r1](https://reviewable.io/reviews/cockroachdb/docs/10235#-MXgp6gP-EYyWH5fEqoP:-MXgp6gP-EYyWH5fEqoQ:b-8cmsws) ([raw file](https://github.com/cockroachdb/docs/blob/36529c844734ab84260c4275255e22ad2f95e41d/v21.1/demo-low-latency-multi-region-deployment.md#L22)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> This page describes the process of simulating a 9-node, multi-region cluster on a single machine. A demo cluster in this configuration is already in an overloaded state. This means that the absolute performance numbers described below are not reflective of [the performance you can expect of single-point reads and writes against CockroachDB in a production setting](frequently-asked-questions.html#single-row-perf).
> ```

What do you mean overloaded state? Why would 9 node movr cluster be overloaded?


<!-- Sent from Reviewable.io -->

2021-04-09 18:05 UTC, arulajmani requested changes
I have a few questions about how the primary key looks these tables after they are switched to Regional By Row tables. I think it's quite confusing if they started out as (city, ID) and now we have a region column with the same (city, ID) primary key. 

I'm not sure about the scope of this demo, and maybe my concerns are for a more thorough "switch old schema to multi-region abstractions" demo, but just some thoughts that came to mind while perusing through this. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10235#-:-MXrmyQK7TB_ChyuwdZx:b-y1ec6r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187 and @rmloveland)

___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 22 at r1](https://reviewable.io/reviews/cockroachdb/docs/10235#-MXgp6gP-EYyWH5fEqoP:-MXrhqJGBy3kDDRnGpht:b9hcrss) ([raw file](https://github.com/cockroachdb/docs/blob/36529c844734ab84260c4275255e22ad2f95e41d/v21.1/demo-low-latency-multi-region-deployment.md#L22)):*
<details><summary><i>Previously, awoods187 (Andy Woods) wrote…</i></summary><blockquote>

What do you mean overloaded state? Why would 9 node movr cluster be overloaded?
</blockquote></details>

Is the intention here is to say "demo multi-region" has fake latencies? I agree with Andy, I'm not sure what overloaded means in this context. 
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 57 at r1](https://reviewable.io/reviews/cockroachdb/docs/10235#-MXriDQZ6KVoh1qj3s4B:-MXriDQZ6KVoh1qj3s4C:b-pvkunl) ([raw file](https://github.com/cockroachdb/docs/blob/36529c844734ab84260c4275255e22ad2f95e41d/v21.1/demo-low-latency-multi-region-deployment.md#L57)):*
> ```Markdown
> {% include {{ page.version.version }}/misc/movr-schema.md %}
> 
> All of the tables except `promo_codes` have a multi-column primary key of `city` and `id`, in that order. This means that the rows in these tables are ordered by their geography. These tables are read from and written to very frequently. To keep read and write latency low, you'll use the [Regional table locality pattern](multiregion-overview.html#regional-by-row-tables) for these tables.
> ```

nit: s/multi-column/composite/g?
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 156 at r1](https://reviewable.io/reviews/cockroachdb/docs/10235#-MXrjEgoBKrPwS8RqXuA:-MXrjEgoBKrPwS8RqXuB:b-gc1im3) ([raw file](https://github.com/cockroachdb/docs/blob/36529c844734ab84260c4275255e22ad2f95e41d/v21.1/demo-low-latency-multi-region-deployment.md#L156)):*
> ```Markdown
>     {% include copy-clipboard.html %}
>     ~~~ sql
>     CREATE DATABASE IF NOT EXISTS movr;
> ```

Just to confirm, things will work as expected even if the database exists and contains tables?
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 354 at r1](https://reviewable.io/reviews/cockroachdb/docs/10235#-MXrkvqj7G0Rrw8SEJk-:-MXrkvqj7G0Rrw8SEJk0:b-9tcrn4) ([raw file](https://github.com/cockroachdb/docs/blob/36529c844734ab84260c4275255e22ad2f95e41d/v21.1/demo-low-latency-multi-region-deployment.md#L354)):*
> ```Markdown
> ) STORED;
> ALTER TABLE rides ALTER COLUMN REGION SET NOT NULL;
> ALTER TABLE rides SET LOCALITY REGIONAL BY ROW AS "region";
> ```

What's the primary key of this table before we start using REGIONAL BY ROW tables? Is it (city, id)? If so, the schema after switching to a RBR is slightly confusing to me. 


<!-- Sent from Reviewable.io -->

2021-04-12 21:16 UTC, rmloveland reviewed
Thanks for the reviews Andy and Arul!

Andy I think all of your feedback was addressed below - PTAL

Arul, I tried to answer your question about the rides PK below - I think the rides table is only `id`? More detail in discussion below

Re: the scope of this demo, AIUI it is basically "turn on multi-region features and watch the latency charts go down".   It is intended to be a super-quick "kick the tires on multi-region without having to do too much work" type thing

Re: schema design, this is not currently intended to be a document describing how to design multi-region schemas - I just filed an issue to update our current schema design docs around multi-region considerations but I will not get to that in the time remaining for v21.1: https://github.com/cockroachdb/docs/issues/10299

My understanding is that the current Movr schema is not necessarily ideal for the new MR features, but I think we are hoping to do some work here for the 21.2 cycle (Andy captured this in https://github.com/cockroachdb/cockroach/issues/62025)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10235#-:-MY6oFD45kh7j0n1_aSQ:b-t6zm7z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @awoods187)

___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 12 at r1](https://reviewable.io/reviews/cockroachdb/docs/10235#-MXgouYK3xrwdL0RbSRi:-MY6mVgX3cXeCUGdjMvR:b-ggudbb) ([raw file](https://github.com/cockroachdb/docs/blob/36529c844734ab84260c4275255e22ad2f95e41d/v21.1/demo-low-latency-multi-region-deployment.md#L12)):*
<details><summary><i>Previously, awoods187 (Andy Woods) wrote…</i></summary><blockquote>

I usually think of it as you have survival goals and then you do the best you can via latency rather than you go for latency and then decide survival goals. 
</blockquote></details>

Makes sense - I have updated this section to mention the survival first, followed by the localities
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 22 at r1](https://reviewable.io/reviews/cockroachdb/docs/10235#-MXgp6gP-EYyWH5fEqoP:-MY6m_TMB_4mrwLdv2YE:brjlp51) ([raw file](https://github.com/cockroachdb/docs/blob/36529c844734ab84260c4275255e22ad2f95e41d/v21.1/demo-low-latency-multi-region-deployment.md#L22)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Is the intention here is to say "demo multi-region" has fake latencies? I agree with Andy, I'm not sure what overloaded means in this context. 
</blockquote></details>

Ah thanks - I removed the sentence about it being overloaded, it's not necessary

What I meant was that later on it's pretty clear that throwing even a modest load at this little demo cluster overloads it - it gives very poor performance in the 1-2s range in the SQL service latency chart. It was part of emphasizing "these are not real performance numbers,  only directional" But I see where yall are coming from, having it in the front of the document, it's unclear what it means.  Removed!
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 57 at r1](https://reviewable.io/reviews/cockroachdb/docs/10235#-MXriDQZ6KVoh1qj3s4B:-MY6npXh4JpwNiG3Y0Fr:blwv4on) ([raw file](https://github.com/cockroachdb/docs/blob/36529c844734ab84260c4275255e22ad2f95e41d/v21.1/demo-low-latency-multi-region-deployment.md#L57)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: s/multi-column/composite/g?
</blockquote></details>

yes! updated, thanks
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 156 at r1](https://reviewable.io/reviews/cockroachdb/docs/10235#-MXrjEgoBKrPwS8RqXuA:-MY6ns_vBLBinAtPJdsP:b-4c4r9n) ([raw file](https://github.com/cockroachdb/docs/blob/36529c844734ab84260c4275255e22ad2f95e41d/v21.1/demo-low-latency-multi-region-deployment.md#L156)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Just to confirm, things will work as expected even if the database exists and contains tables?
</blockquote></details>

I'm not sure.  I think I added that out of habit because I was running this multiple times

Removed the IF NOT EXISTS since it's not necessary
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 354 at r1](https://reviewable.io/reviews/cockroachdb/docs/10235#-MXrkvqj7G0Rrw8SEJk-:-MY6qC5wApMQrOHn4RK4:b-snjlvq) ([raw file](https://github.com/cockroachdb/docs/blob/36529c844734ab84260c4275255e22ad2f95e41d/v21.1/demo-low-latency-multi-region-deployment.md#L354)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

What's the primary key of this table before we start using REGIONAL BY ROW tables? Is it (city, id)? If so, the schema after switching to a RBR is slightly confusing to me. 
</blockquote></details>

I think it's only `id`?  Just loaded the data set again (Step 3, list item 2) and ran the following queries

```
show columns FROM rides;
   column_name  |   data_type   | is_nullable | column_default | generation_expression |  indices  | is_hidden
----------------+---------------+-------------+----------------+-----------------------+-----------+------------
  id            | UUID          |    false    | NULL           |                       | {primary} |   false
  city          | VARCHAR       |    false    | NULL           |                       | {}        |   false
  rider_id      | UUID          |    true     | NULL           |                       | {}        |   false
  vehicle_id    | UUID          |    true     | NULL           |                       | {}        |   false
  start_address | VARCHAR       |    true     | NULL           |                       | {}        |   false
  end_address   | VARCHAR       |    true     | NULL           |                       | {}        |   false
  start_time    | TIMESTAMP     |    true     | NULL           |                       | {}        |   false
  end_time      | TIMESTAMP     |    true     | NULL           |                       | {}        |   false
  revenue       | DECIMAL(10,2) |    true     | NULL           |                       | {}        |   false
```

however the `SHOW CREATE TABLE` shows an additional line `FAMILY "primary" (id, city, rider_id, ...)` with a lot of columns, which I'm not sure of the meaning of

```
show CREATE TABLE rides;
  table_name |                                                 create_statement
-------------+-------------------------------------------------------------------------------------------------------------------
  rides      | CREATE TABLE public.rides (
             |     id UUID NOT NULL,
             |     city VARCHAR NOT NULL,
             |     rider_id UUID NULL,
             |     vehicle_id UUID NULL,
             |     start_address VARCHAR NULL,
             |     end_address VARCHAR NULL,
             |     start_time TIMESTAMP NULL,
             |     end_time TIMESTAMP NULL,
             |     revenue DECIMAL(10,2) NULL,
             |     CONSTRAINT "primary" PRIMARY KEY (id ASC),
             |     CONSTRAINT fk_rider_id_ref_users FOREIGN KEY (rider_id) REFERENCES public.users(id),
             |     CONSTRAINT fk_vehicle_id_ref_vehicles FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id),
             |     FAMILY "primary" (id, city, rider_id, vehicle_id, start_address, end_address, start_time, end_time, revenue)
             | )
```


<!-- Sent from Reviewable.io -->

2021-04-13 14:30 UTC, arulajmani reviewed
Thanks for going down this primary key rabbit hole with me! This thing looks good to me, but I'll let Andy sign off. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10235#-:-MYAceUCBh1lRQktCvg-:bul7y65)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @awoods187, and @rmloveland)

___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 354 at r1](https://reviewable.io/reviews/cockroachdb/docs/10235#-MXrkvqj7G0Rrw8SEJk-:-MYAbFtf4ZWswUJh4DZd:b-maypqh) ([raw file](https://github.com/cockroachdb/docs/blob/36529c844734ab84260c4275255e22ad2f95e41d/v21.1/demo-low-latency-multi-region-deployment.md#L354)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

I think it's only `id`?  Just loaded the data set again (Step 3, list item 2) and ran the following queries

```
show columns FROM rides;
   column_name  |   data_type   | is_nullable | column_default | generation_expression |  indices  | is_hidden
----------------+---------------+-------------+----------------+-----------------------+-----------+------------
  id            | UUID          |    false    | NULL           |                       | {primary} |   false
  city          | VARCHAR       |    false    | NULL           |                       | {}        |   false
  rider_id      | UUID          |    true     | NULL           |                       | {}        |   false
  vehicle_id    | UUID          |    true     | NULL           |                       | {}        |   false
  start_address | VARCHAR       |    true     | NULL           |                       | {}        |   false
  end_address   | VARCHAR       |    true     | NULL           |                       | {}        |   false
  start_time    | TIMESTAMP     |    true     | NULL           |                       | {}        |   false
  end_time      | TIMESTAMP     |    true     | NULL           |                       | {}        |   false
  revenue       | DECIMAL(10,2) |    true     | NULL           |                       | {}        |   false
```

however the `SHOW CREATE TABLE` shows an additional line `FAMILY "primary" (id, city, rider_id, ...)` with a lot of columns, which I'm not sure of the meaning of

```
show CREATE TABLE rides;
  table_name |                                                 create_statement
-------------+-------------------------------------------------------------------------------------------------------------------
  rides      | CREATE TABLE public.rides (
             |     id UUID NOT NULL,
             |     city VARCHAR NOT NULL,
             |     rider_id UUID NULL,
             |     vehicle_id UUID NULL,
             |     start_address VARCHAR NULL,
             |     end_address VARCHAR NULL,
             |     start_time TIMESTAMP NULL,
             |     end_time TIMESTAMP NULL,
             |     revenue DECIMAL(10,2) NULL,
             |     CONSTRAINT "primary" PRIMARY KEY (id ASC),
             |     CONSTRAINT fk_rider_id_ref_users FOREIGN KEY (rider_id) REFERENCES public.users(id),
             |     CONSTRAINT fk_vehicle_id_ref_vehicles FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id),
             |     FAMILY "primary" (id, city, rider_id, vehicle_id, start_address, end_address, start_time, end_time, revenue)
             | )
```
</blockquote></details>

Perfect -- I wanted to double check because when I ran `SHOW CREATE TABLE rides` on cockroach demo it showed (city, id) as the primary key to me, but looks like its sane in this data set and for the purpose of this demo! 

The column families should be fine, they're separate to primary keys even though it's named primary there. Don't quote me on the details here, but we probably name the family "primary" if it's the only one. 


<!-- Sent from Reviewable.io -->

2021-04-13 14:38 UTC, awoods187 approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10235)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @rmloveland)



<!-- Sent from Reviewable.io -->

2021-04-13 14:48 UTC, rmloveland reviewed
Thanks Arul!

I will pass this on for docs team review.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10235#-:-MYAgOG_Chh5xeVC1xms:b3qh137)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 354 at r1](https://reviewable.io/reviews/cockroachdb/docs/10235#-MXrkvqj7G0Rrw8SEJk-:-MYAg0O82nl5XsqwmMuP:bjk7awi) ([raw file](https://github.com/cockroachdb/docs/blob/36529c844734ab84260c4275255e22ad2f95e41d/v21.1/demo-low-latency-multi-region-deployment.md#L354)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Perfect -- I wanted to double check because when I ran `SHOW CREATE TABLE rides` on cockroach demo it showed (city, id) as the primary key to me, but looks like its sane in this data set and for the purpose of this demo! 

The column families should be fine, they're separate to primary keys even though it's named primary there. Don't quote me on the details here, but we probably name the family "primary" if it's the only one. 
</blockquote></details>

Thanks for checking this.  I guess there is divergence in schemas between `cockroach demo movr` and the "official" (?) movr app

Glad to hear it looks sane!  

I wasn't sure what to do if it wasn't, maybe make a PR to the movr app - glad not to have to do that right now :-) 


<!-- Sent from Reviewable.io -->

2021-04-14 20:01 UTC, lnhsingh reviewed
Added some nits / suggestions on making the steps flow a little better, but you can take/leave them. Overall, the content itself looks great!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10235#-:-MYGyGOJ1KpxsUT75o2b:b-pfxo1l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @rmloveland)

___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 16 at r2](https://reviewable.io/reviews/cockroachdb/docs/10235#-MYGsKDM9bJEE-XO1Aiq:-MYGsKDM9bJEE-XO1Air:bk5b8vb) ([raw file](https://github.com/cockroachdb/docs/blob/58159527358426949720c20449dd11ab09ff765b/v21.1/demo-low-latency-multi-region-deployment.md#L16)):*
> ```Markdown
> In this tutorial, you will:
> 
> 1. Simulate a multi-region CockroachDB cluster on your local machine.
> ```

formatting nit: make the ordered list start with all `1.`
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 17 at r2](https://reviewable.io/reviews/cockroachdb/docs/10235#-MYGs8XC-DmAKj9rcJNk:-MYGs8XC-DmAKj9rcJNl:bmkgoii) ([raw file](https://github.com/cockroachdb/docs/blob/58159527358426949720c20449dd11ab09ff765b/v21.1/demo-low-latency-multi-region-deployment.md#L17)):*
> ```Markdown
> 
> 1. Simulate a multi-region CockroachDB cluster on your local machine.
> 2. Run a workload on the cluster: our fictional vehicle-sharing application called [MovR](movr.html).
> ```

suggestion: "Run a workload on the cluster using our fictional vehicle-sharing application..."
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 21 at r2](https://reviewable.io/reviews/cockroachdb/docs/10235#-MYGsZpI64uPkYaJGUGx:-MYGsZpI64uPkYaJGUGy:b-48z07l) ([raw file](https://github.com/cockroachdb/docs/blob/58159527358426949720c20449dd11ab09ff765b/v21.1/demo-low-latency-multi-region-deployment.md#L21)):*
> ```Markdown
> 4. Configure the cluster for good multi-region performance by issuing SQL statements that choose the right [survival goals](multiregion-overview.html#survival-goals) and [table localities](multiregion-overview.html#table-locality).
> 
> {{site.data.alerts.callout_info}}
> ```

It seems like this callout + the next callout are pretty similar and could be combined into one. For example:

```
This page describes the process of simulating a 9-node, multi-region cluster on a single machine using a demo cluster; it does not show best practices for a production deployment. This means that the absolute performance numbers described below are not reflective of the performance you can expect of single-point reads and writes against CockroachDB in a production setting. For more information about production deployments of multi-region applications, see Orchestrate CockroachDB Across Multiple Kubernetes Clusters and the Production Checklist.

Instead, these instructions are designed with the following goals:

1. foo
1. bar
```

If you did combine them into one note, it also seems like a lot of info for a callout. Maybe it could be it's own section called `Considerations`?
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 25 at r2](https://reviewable.io/reviews/cockroachdb/docs/10235#-MYGsXTn5JJ6GSZiiyvQ:-MYGsXTn5JJ6GSZiiyvR:b3y38ml) ([raw file](https://github.com/cockroachdb/docs/blob/58159527358426949720c20449dd11ab09ff765b/v21.1/demo-low-latency-multi-region-deployment.md#L25)):*
> ```Markdown
> 
> Instead, these instructions are designed with the following goals:  
> 1. To show the _relative_ magnitude of the performance improvements to expect when you configure a multi-region cluster correctly.  
> ```

same nit re: ordered lists
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 30 at r2](https://reviewable.io/reviews/cockroachdb/docs/10235#-MYGsltr6h2fyP_L5-k_:-MYGsltr6h2fyP_L5-ka:b-n3yc5p) ([raw file](https://github.com/cockroachdb/docs/blob/58159527358426949720c20449dd11ab09ff765b/v21.1/demo-low-latency-multi-region-deployment.md#L30)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> This page describes a demo cluster; it does not show best practices for a production deployment. For more information about production deployments of multi-region applications, see [Orchestrate CockroachDB Across Multiple Kubernetes Clusters](orchestrate-cockroachdb-with-kubernetes-multi-cluster.html) and the [Production Checklist](recommended-production-settings.html)
> ```

nit: add period at end of callout
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 69 at r2](https://reviewable.io/reviews/cockroachdb/docs/10235#-MYGu6-48PW1llixYBpA:-MYGu6-48PW1llixYBpB:bb1ah2k) ([raw file](https://github.com/cockroachdb/docs/blob/58159527358426949720c20449dd11ab09ff765b/v21.1/demo-low-latency-multi-region-deployment.md#L69)):*
> ```Markdown
> ## Step 2. Determine which nodes are in which regions
> 
> To see which nodes are in which regions, check the [Network Latency Page](ui-network-latency-page.html) in the DB Console. The simulated latencies should be working as expected, as shown in the screenshot below. Round trip times between `us-west1` and `europe-west1` should be in the 150 ms range.
> ```

It's a little confusing to me that the screenshot this paragraph refers to is after more descriptions / code blocks. I think it would be more helpful for it to display right after this first paragraph.

Edit: But now after reading more, it seems like the screenshot is actually more helpful for viewing the node IDs. In this case, the sentence about simulated latencies doesn't really make sense in this section about "determining which nodes are in which regions." Does it make sense to move the info about simulated latencies up into Step 1? Something like:

```
To check that the simulated latencies are working as expected, check the Network Latency Page in the DB Console. Round trip times between us-west1 and europe-west1 should be in the 150 ms range.
```

If you move that info up, you could probably get rid of the first two sentences in Step 2 and start Step 2 with "To determine which nodes are in which regions, you will need to refer to two things: ..."
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 150 at r2](https://reviewable.io/reviews/cockroachdb/docs/10235#-MYGvuUyBewFNIoCt3MW:-MYGvuUyBewFNIoCt3MX:b-7g48o3) ([raw file](https://github.com/cockroachdb/docs/blob/58159527358426949720c20449dd11ab09ff765b/v21.1/demo-low-latency-multi-region-deployment.md#L150)):*
> ```Markdown
> ## Step 3. Load and run MovR
> 
> Follow the steps below to spin up 3 instances of MovR. Each instance is pointed at a node in a different region. This will simulate load from that region.
> ```

nit: is "spin up" a colloquialism that we want to avoid? Replace with "start"?
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 152 at r2](https://reviewable.io/reviews/cockroachdb/docs/10235#-MYGw3Qv6kb_ShE9ohGO:-MYGw3Qv6kb_ShE9ohGP:bgrtelu) ([raw file](https://github.com/cockroachdb/docs/blob/58159527358426949720c20449dd11ab09ff765b/v21.1/demo-low-latency-multi-region-deployment.md#L152)):*
> ```Markdown
> Follow the steps below to spin up 3 instances of MovR. Each instance is pointed at a node in a different region. This will simulate load from that region.
> 
> 1. In the SQL shell, create the `movr` database:
> ```

same nit re: numbered lists
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 274 at r2](https://reviewable.io/reviews/cockroachdb/docs/10235#-MYGwSDI3C-x_YdVJQAJ:-MYGwSDI3C-x_YdVJQAK:b-3fiht5) ([raw file](https://github.com/cockroachdb/docs/blob/58159527358426949720c20449dd11ab09ff765b/v21.1/demo-low-latency-multi-region-deployment.md#L274)):*
> ```Markdown
> Within a single region, round-trip latency is under 6 ms (milliseconds).
> 
> Across regions, round-trip latency is significantly higher. 
> ```

nit: I think this can be on the same line as the sentence before it (i.e., I don't think it should be its own "paragraph")
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 288 at r2](https://reviewable.io/reviews/cockroachdb/docs [...]

2021-04-15 16:33 UTC, rmloveland reviewed
Thanks Lauren!!!1!

I think I fixed the things you mentioned - great suggestions for improvement, thank you!

(Note to self: stop writing "under the hood" :-} )

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10235#-:-MYLF7kfEbiaBcJb7aQ-:b-20xgs3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @lnhsingh)

___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 16 at r2](https://reviewable.io/reviews/cockroachdb/docs/10235#-MYGsKDM9bJEE-XO1Aiq:-MYLFJwJC8YUZBiOS2MS:boyv45w) ([raw file](https://github.com/cockroachdb/docs/blob/58159527358426949720c20449dd11ab09ff765b/v21.1/demo-low-latency-multi-region-deployment.md#L16)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

formatting nit: make the ordered list start with all `1.`
</blockquote></details>

Done (here and elsewhere in this doc)
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 17 at r2](https://reviewable.io/reviews/cockroachdb/docs/10235#-MYGs8XC-DmAKj9rcJNk:-MYLFQER0fnUm_J5LMwl:b-896fja) ([raw file](https://github.com/cockroachdb/docs/blob/58159527358426949720c20449dd11ab09ff765b/v21.1/demo-low-latency-multi-region-deployment.md#L17)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

suggestion: "Run a workload on the cluster using our fictional vehicle-sharing application..."
</blockquote></details>

Done!
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 21 at r2](https://reviewable.io/reviews/cockroachdb/docs/10235#-MYGsZpI64uPkYaJGUGx:-MYLGiFv8FOvNmEMUQMA:bnfzl8s) ([raw file](https://github.com/cockroachdb/docs/blob/58159527358426949720c20449dd11ab09ff765b/v21.1/demo-low-latency-multi-region-deployment.md#L21)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

It seems like this callout + the next callout are pretty similar and could be combined into one. For example:

```
This page describes the process of simulating a 9-node, multi-region cluster on a single machine using a demo cluster; it does not show best practices for a production deployment. This means that the absolute performance numbers described below are not reflective of the performance you can expect of single-point reads and writes against CockroachDB in a production setting. For more information about production deployments of multi-region applications, see Orchestrate CockroachDB Across Multiple Kubernetes Clusters and the Production Checklist.

Instead, these instructions are designed with the following goals:

1. foo
1. bar
```

If you did combine them into one note, it also seems like a lot of info for a callout. Maybe it could be it's own section called `Considerations`?
</blockquote></details>

Ya it's a bit awkward, but felt it needed to be said somewhere to avoid any misunderstandings. Moved to a new section called 'Considerations' - thanks!
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 25 at r2](https://reviewable.io/reviews/cockroachdb/docs/10235#-MYGsXTn5JJ6GSZiiyvQ:-MYLGuru4RT2piw-uCcd:bj9s9x1) ([raw file](https://github.com/cockroachdb/docs/blob/58159527358426949720c20449dd11ab09ff765b/v21.1/demo-low-latency-multi-region-deployment.md#L25)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

same nit re: ordered lists
</blockquote></details>

~HOW DARE YOU LAUREN~

Fixed.
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 30 at r2](https://reviewable.io/reviews/cockroachdb/docs/10235#-MYGsltr6h2fyP_L5-k_:-MYLH-3WEf1den7VmVYv:b-pyg9fj) ([raw file](https://github.com/cockroachdb/docs/blob/58159527358426949720c20449dd11ab09ff765b/v21.1/demo-low-latency-multi-region-deployment.md#L30)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

nit: add period at end of callout
</blockquote></details>

Fixed in its new home
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 69 at r2](https://reviewable.io/reviews/cockroachdb/docs/10235#-MYGu6-48PW1llixYBpA:-MYLJIgKALE7Eh8yzufe:b-4uhgjq) ([raw file](https://github.com/cockroachdb/docs/blob/58159527358426949720c20449dd11ab09ff765b/v21.1/demo-low-latency-multi-region-deployment.md#L69)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

It's a little confusing to me that the screenshot this paragraph refers to is after more descriptions / code blocks. I think it would be more helpful for it to display right after this first paragraph.

Edit: But now after reading more, it seems like the screenshot is actually more helpful for viewing the node IDs. In this case, the sentence about simulated latencies doesn't really make sense in this section about "determining which nodes are in which regions." Does it make sense to move the info about simulated latencies up into Step 1? Something like:

```
To check that the simulated latencies are working as expected, check the Network Latency Page in the DB Console. Round trip times between us-west1 and europe-west1 should be in the 150 ms range.
```

If you move that info up, you could probably get rid of the first two sentences in Step 2 and start Step 2 with "To determine which nodes are in which regions, you will need to refer to two things: ..."
</blockquote></details>

I did it!  Thanks, this is better
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 150 at r2](https://reviewable.io/reviews/cockroachdb/docs/10235#-MYGvuUyBewFNIoCt3MW:-MYLHE4PDOUQjMcBh7HI:b6brq9) ([raw file](https://github.com/cockroachdb/docs/blob/58159527358426949720c20449dd11ab09ff765b/v21.1/demo-low-latency-multi-region-deployment.md#L150)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

nit: is "spin up" a colloquialism that we want to avoid? Replace with "start"?
</blockquote></details>

Ah good point.  Fixed to say "start"
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 152 at r2](https://reviewable.io/reviews/cockroachdb/docs/10235#-MYGw3Qv6kb_ShE9ohGO:-MYLHN_q2img5W33L719:b-886gsx) ([raw file](https://github.com/cockroachdb/docs/blob/58159527358426949720c20449dd11ab09ff765b/v21.1/demo-low-latency-multi-region-deployment.md#L152)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

same nit re: numbered lists
</blockquote></details>

Fixed
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 274 at r2](https://reviewable.io/reviews/cockroachdb/docs/10235#-MYGwSDI3C-x_YdVJQAJ:-MYLHRDAA61hiIHSu1ma:b-uunnvn) ([raw file](https://github.com/cockroachdb/docs/blob/58159527358426949720c20449dd11ab09ff765b/v21.1/demo-low-latency-multi-region-deployment.md#L274)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

nit: I think this can be on the same line as the sentence before it (i.e., I don't think it should be its own "paragraph")
</blockquote></details>

Sounds good - moved it up!
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 288 at r2](https://reviewable.io/reviews/cockroachdb/docs/10235#-MYGwtRxEVFFW9n9Xg7d:-MYLHTg5EGqMbXpP1tZH:bbuc70v) ([raw file](https://github.com/cockroachdb/docs/blob/58159527358426949720c20449dd11ab09ff765b/v21.1/demo-low-latency-multi-region-deployment.md#L288)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Do you need "under the hood"? I feel like that makes me ask more questions about what that means and it might be unnecessary
</blockquote></details>

Gosh I guess not.  Busy revealing the location and approximate year of my birth with these colloquialisms everywhere
___
*[v21.1/demo-low-latency-multi-region-deployment.md, line 294 at r2](https://reviewable.io/reviews/cockroachdb/docs/10235#-MYGxMHz4dVXh1KXrBR_:-MYLIAr-4YloKrHB5jXU:bq6odoe) ([raw file](https://github.com/cockroachd [...]

2021-04-15 16:37 UTC, merged