draft logging updates
cockroachdb/docs pull request #10273
Opened 2021-04-06 23:46 UTC by taroface

WIP

2021-04-06 23:46 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/10273)
<!-- Reviewable:end -->

2021-04-07 00:00 UTC, taroface commented
@knz This PR still has some outstanding elements (see list above), but I wonder if you'd like to begin reviewing what is here. If you would prefer to wait, I can update you when all of the above are resolved.

2021-04-12 18:09 UTC, knz reviewed
This was a very pleasant read — I really like the use cases and the organization you've come up with.
Only few comments remaining.

> Reviewed 37 of 37 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10273#-:-MY6GJTYEtF27GdLifPl:bxu6ths)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface and @thtruo)

___
*[_includes/v21.1/misc/logging-flags.md, line 3 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY5qZ2i44dE4LTLr97r:-MY5qZ2i44dE4LTLr97s:b9ec7dz) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/_includes/v21.1/misc/logging-flags.md#L3)):*
> ```
> All of the below settings are defined in the YAML payload.
> ```

"All the below settings can now be defined in the YAML payload instead."
___
*[v21.1/cockroach-gen.md, line 118 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY5t-_m62SCSYM_JBda:-MY5t-_n-FcceF43-h2U:buybwrl) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/cockroach-gen.md#L118)):*
> ```Markdown
> ### Logging
> 
> By default, the `gen` command logs messages to `stderr`. This includes events with `WARNING` [severity](logging.html#logging-levels) and higher.
> ```

Here and throughout: What about an include?

"By default, this command logs messages to...;

if you need to troubleshoot..."
___
*[v21.1/configure-logs.md, line 9 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY5ubxmEsuoJBWVifno:-MY5ubxmEsuoJBWVifnp:b3dz4m3) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/configure-logs.md#L9)):*
> ```Markdown
> This page describes how to configure CockroachDB logs with the [`--log` flag](cockroach-start.html#logging) and a [YAML payload](#yaml-payload). Most logging behaviors are configurable, including:
> 
> - The [logging sinks](#configure-logging-sinks) that output logs to different locations, including over the network
> ```

nit: period at the end of each bullet point?
___
*[v21.1/configure-logs.md, line 68 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY69dG_C1O1m0fwcWYu:-MY69dG_C1O1m0fwcWYv:b-se6376) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/configure-logs.md#L68)):*
> ```Markdown
> ## Configure logging sinks
> 
> A logging *sink* outputs log messages from specified [logging channels](#logging-overview.html#logging-channels).
> ```

"A logging sink represents one logical funnel through which the events from one or more logging channel are emitted externally to the `cockroach` process. Logging sinks are the unit of configurability for mapping events from inside to outside of CockroachDB."
___
*[v21.1/configure-logs.md, line 70 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6A6arBV5XXaOjv6B9:-MY6A6arBV5XXaOjv6BA:b-38wy07) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/configure-logs.md#L70)):*
> ```Markdown
> A logging *sink* outputs log messages from specified [logging channels](#logging-overview.html#logging-channels).
> 
> CockroachDB can write logs to [files](#output-to-files), a [Fluentd](https://www.fluentd.org/)-compatible [server](#output-to-network), and the [standard error stream (`stderr`)](#output-to-stderr). Each output is configured under `sinks`:
> ```

here and below: it would be useful to convey the idea that the list of sink types will likely grow over time. Currently the phrasing suggests that there are only 3 types and that choice is closed forever.
___
*[v21.1/configure-logs.md, line 79 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6A2M3-x4vnhexN5Vf:-MY6A2M3-x4vnhexN5Vg:bx4hyz1) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/configure-logs.md#L79)):*
> ```Markdown
>       ...
>   fluent-servers:
>   	{server name}:
> ```

nit: stray tab character
___
*[v21.1/configure-logs.md, line 89 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6AHfJ4xUSw2sWIaWN:-MY6AHfJ4xUSw2sWIaWO:bo4peb) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/configure-logs.md#L89)):*
> ```Markdown
> <a name="common-sink-parameters">
> 
> All three sink types use the following common parameters.
> ```

"All possible sink types .." (this will remain true even if we add more sink types)
___
*[v21.1/configure-logs.md, line 115 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6AODK9W58qEgaLj9K:-MY6AODK9W58qEgaLj9L:blguvit) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/configure-logs.md#L115)):*
> ```Markdown
> sinks:
>   file-groups:
>   	default:
> ```

nit: stray tab character, here and below.
___
*[v21.1/configure-logs.md, line 123 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6AR8U1XMjTJu6Yf7L:-MY6AR8U1XMjTJu6Yf7M:bf4ao5o) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/configure-logs.md#L123)):*
> ```Markdown
> 
> {{site.data.alerts.callout_success}}
> A file group name is arbitrary and is used to name the log file. The `default` file group is an exception. For details, see [Log file naming](#log-file-naming).
> ```

name the log _files_
___
*[v21.1/configure-logs.md, line 159 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6AaHWAnPGazi_nDPz:-MY6AaHWAnPGazi_nDQ-:b-2p7tkf) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/configure-logs.md#L159)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> Channels in a file group named `default` are output to a `cockroach.log` file.
> ```

"The files generated for a group named `default` are named after the pattern`cockroach.XXXX.log`"

(no need to mention the "channel" concept in this explanation)
___
*[v21.1/configure-logs.md, line 208 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6Arib6rqQ3UGgWjL-:-MY6Arib6rqQ3UGgWjL0:b-kvama9) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/configure-logs.md#L208)):*
> ```Markdown
> ## Configure logging defaults
> 
> When setting up a logging configuration, it's simplest to define shared parameters in `file-defaults` and `fluent-defaults` and override specific values as needed in [`file-groups`](#output-to-files), [`fluent-servers`](#output-to-network), and [`stderr`](#output-to-stderr). For a complete example, see the [default configuration](#default-logging-configuration).
> ```

nit: here and below; do we conventionally use contractions? if not, "it's" -> "it is"
___
*[v21.1/configure-logs.md, line 221 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6B0SN6PMdMFUBTPY9:-MY6B0SN6PMdMFUBTPYA:b2tiexk) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/configure-logs.md#L221)):*
> ```Markdown
> 
> ~~~
> /cockroachdb/cockroach/cockroach-data/logs
> ```

What is this example coming from? I don't see the path `cockroachdb/cockroach` being mentioned elsewhere.
___
*[v21.1/configure-logs.md, line 225 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6BBkR75GmANeM0d9-:-MY6BBkR75GmANeM0d90:bkzmsju) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/configure-logs.md#L225)):*
> ```
> in its own directory
> ```

"in the directory pointed to by its logging configuration".

(it's possible, albeit not recommended, to point multiple crdb processes to the same directory)
___
*[v21.1/configure-logs.md, line 248 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6BQQZ-LSvalRC4ysH:-MY6BQQZ-LSvalRC4ysI:bwfwcli) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/configure-logs.md#L248)):*
> ```Markdown
>     dev:
> [...]

2021-04-15 19:06 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10273)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface and @thtruo)

___
*[v21.1/logging-use-cases.md, line 84 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6F2JyALee_CNMMbuP:-MYLvJZq4FwOR20F9-QU:b7j1wl3) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/logging-use-cases.md#L84)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This is not a structured event and thus we would prefer not to document it.

Arguably we probably do need a structured event here for this use case, but it's not implemented yet.

I would appreciate an issue on the crdb repo filed for this.
</blockquote></details>

Filed: https://github.com/cockroachdb/cockroach/issues/63750
___
*[v21.1/logging-use-cases.md, line 95 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6F7JM9Aslwb4TP6vG:-MYLvOna76CFdcBw04Zv:b-ykw8ft) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/logging-use-cases.md#L95)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This is not a structured event and thus we would prefer not to document it.

Arguably we probably do need a structured event here for this use case, but it's not implemented yet.

Also worth a (separate) issue.
</blockquote></details>

Filed : https://github.com/cockroachdb/cockroach/issues/63639


<!-- Sent from Reviewable.io -->

2021-04-16 01:11 UTC, taroface reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10273#-:-MYMYMtnDUAPkLdr81_B:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @taroface, and @thtruo)

___
*[_includes/v21.1/misc/logging-flags.md, line 3 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY5qZ2i44dE4LTLr97r:-MYMYjvE7Kg9j__t5sRq:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/_includes/v21.1/misc/logging-flags.md#L3)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

> ```
> All of the below settings are defined in the YAML payload.
> ```

"All the below settings can now be defined in the YAML payload instead."
</blockquote></details>

Done.
___
*[v21.1/cockroach-gen.md, line 118 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY5t-_m62SCSYM_JBda:-MYMZmDeEbqljLhKveZ2:b-6djle) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/cockroach-gen.md#L118)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Here and throughout: What about an include?

"By default, this command logs messages to...;

if you need to troubleshoot..."

</blockquote></details>

Yes, good idea! Done. I left `workload` and `demo` alone, since they have different defaults.
___
*[v21.1/configure-logs.md, line 9 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY5ubxmEsuoJBWVifno:-MYM_OelBAdp7jfBh2pt:b-zhhfod) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/configure-logs.md#L9)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: period at the end of each bullet point?
</blockquote></details>

I think so, since each of these list items completes a sentence. Thanks!
___
*[v21.1/configure-logs.md, line 68 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY69dG_C1O1m0fwcWYu:-MYMkmbhCiIwohtvai1a:b-70snmc) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/configure-logs.md#L68)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

"A logging sink represents one logical funnel through which the events from one or more logging channel are emitted externally to the `cockroach` process. Logging sinks are the unit of configurability for mapping events from inside to outside of CockroachDB."
</blockquote></details>

How's this wording? I want to capture the basic gist while retaining accuracy.

"Logging *sinks* route events from specified [logging channels](#logging-overview.html#logging-channels) to destinations outside CockroachDB."
___
*[v21.1/configure-logs.md, line 70 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6A6arBV5XXaOjv6B9:-MYMmOkE3CIOSy-qXSNA:b-oj5t5v) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/configure-logs.md#L70)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

here and below: it would be useful to convey the idea that the list of sink types will likely grow over time. Currently the phrasing suggests that there are only 3 types and that choice is closed forever.
</blockquote></details>

I wasn't aware - made some tweaks that should convey this.
___
*[v21.1/configure-logs.md, line 89 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6AHfJ4xUSw2sWIaWN:-MYMm_3T0lJc3kDDUlUd:b-duzdi5) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/configure-logs.md#L89)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

"All possible sink types .." (this will remain true even if we add more sink types)
</blockquote></details>

Done. Using "supported" as the adjective.
___
*[v21.1/configure-logs.md, line 115 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6AODK9W58qEgaLj9K:-MYMmwer3YeU24f2bSca:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/configure-logs.md#L115)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: stray tab character, here and below.
</blockquote></details>

Done.
___
*[v21.1/configure-logs.md, line 123 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6AR8U1XMjTJu6Yf7L:-MYMn3Of9pT46x_GtkI-:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/configure-logs.md#L123)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

name the log _files_
</blockquote></details>

Done.
___
*[v21.1/configure-logs.md, line 159 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6AaHWAnPGazi_nDPz:-MYMncbM0Ddw88hP5v5M:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/configure-logs.md#L159)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

"The files generated for a group named `default` are named after the pattern`cockroach.XXXX.log`"

(no need to mention the "channel" concept in this explanation)
</blockquote></details>

Done.
___
*[v21.1/configure-logs.md, line 208 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6Arib6rqQ3UGgWjL-:-MYMo7GR5nAoqzOmLDaU:by215hy) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/configure-logs.md#L208)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: here and below; do we conventionally use contractions? if not, "it's" -> "it is"
</blockquote></details>

According to our style guide, contractions can be used to simplify language. We don't use them when we are describing a clear directive or prohibition: https://github.com/cockroachdb/docs/wiki/Style-Guide#style-and-tone
___
*[v21.1/configure-logs.md, line 221 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6B0SN6PMdMFUBTPY9:-MYMoOY23aHoolyk6KLL:b-6hbxqg) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/configure-logs.md#L221)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

What is this example coming from? I don't see the path `cockroachdb/cockroach` being mentioned elsewhere.
</blockquote></details>

Ah, my mistake! This was my local path. Amended to `/cockroach-data/logs`.
___
*[v21.1/configure-logs.md, line 225 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6BBkR75GmANeM0d9-:-MYMoiXs5JVIJqOHSMTl:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/configure-logs.md#L225)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

> ```
> in its own directory
> ```

"in the directory pointed to by its logging configuration".

(it's possible, albeit not recommended, to point multiple crdb processes to the same directory)
</blockquote></details>

Done.
___
*[v21.1/configure-logs.md, line 262 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6BX1p2r3ybQV8F1RW:-MYMpeoZ25Yf3EN-dQBb:b9shyyp) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/configure-logs.md#L262)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

there are multiple JSON formats; how do you plan to explain that?
</blockquote></details>

Added links to both `json` and `json-compact`.
___
*[v21.1/configure-logs.md, line 306 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6BoeJ4PHoMGVZujPZ:-MYMpnWR56yDOQuq6JWf:b-4ttnuj) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/configure-logs.md#L306)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

"receive" -> "emit"

(the sink receives them from the channe [...]

2021-04-19 09:04 UTC, knz reviewed
> Reviewed 14 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10273)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface and @thtruo)

___
*[v21.1/configure-logs.md, line 221 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6B0SN6PMdMFUBTPY9:-MYdLe702YuqLkCBTxi8:b-qn6ndx) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/configure-logs.md#L221)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Ah, my mistake! This was my local path. Amended to `/cockroach-data/logs`.
</blockquote></details>

I think the leading `/` is still incorrect, the default would be `cockroach-data/logs` or `./cockroach-data/logs`
___
*[v21.1/logging-overview.md, line 18 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6DVVD9rci46UELIYk:-MYdLqYrE2cN0ONIuyHX:b72ydzu) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/logging-overview.md#L18)):*
> ```
> For details on event types and their fields
> ```

For details on *structured* event types ...
___
*[v21.1/logging-use-cases.md, line 84 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6F2JyALee_CNMMbuP:-MYdM5VuBR63DztUu50N:b-dfbtcl) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/logging-use-cases.md#L84)):*
> Is there a chance the structured events you describe in the two issues you filed will be ready for 21.1?

Not for 21.1.0, probably for 21.1.1 or 21.1.2.

> All I can think of is something like "If you are experiencing cluster issues and need help understanding these logs, please contact Support." 

What about this:

1) rename the section header from "Example" to "Content of log messages on this channel"

2) explain:

"At the time of this writing, the events logged through this channel are unstructured. This means that Cockroach Labs does not yet place any guarantee on the specific format of the log entries and they can change between releases, including patch revisions. We assume that the entries are meant to be consumed by human operators."

You could add a mention that we are working on it


<!-- Sent from Reviewable.io -->

2021-04-21 15:02 UTC, thtruo reviewed
Nice @taroface! I read through the major new docs describing our logging system and configuration options which look good. It seems there are multiple comments you're addressing at the moment based off Raphael's feedback. I'm happy to review once a new iteration is posted.

2021-05-05 17:55 UTC, taroface reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10273)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @taroface)

___
*[v21.1/configure-logs.md, line 221 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6B0SN6PMdMFUBTPY9:-MYvu3b5Ef4DuTtTY0dy:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/configure-logs.md#L221)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think the leading `/` is still incorrect, the default would be `cockroach-data/logs` or `./cockroach-data/logs`
</blockquote></details>

Done.
___
*[v21.1/logging-overview.md, line 18 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6DVVD9rci46UELIYk:-MYvu9Vj3eY29dHCcXJK:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/logging-overview.md#L18)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

> ```
> For details on event types and their fields
> ```

For details on *structured* event types ...
</blockquote></details>

Done.
___
*[v21.1/logging-use-cases.md, line 84 at r2](https://reviewable.io/reviews/cockroachdb/docs/10273#-MY6F2JyALee_CNMMbuP:-MZxenDOEjbu59FrhckA:b-k6o5rj) ([raw file](https://github.com/cockroachdb/docs/blob/e8888f70315daf36ead91551917b6f379f6588f7/v21.1/logging-use-cases.md#L84)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

> Is there a chance the structured events you describe in the two issues you filed will be ready for 21.1?

Not for 21.1.0, probably for 21.1.1 or 21.1.2.

> All I can think of is something like "If you are experiencing cluster issues and need help understanding these logs, please contact Support." 

What about this:

1) rename the section header from "Example" to "Content of log messages on this channel"

2) explain:

"At the time of this writing, the events logged through this channel are unstructured. This means that Cockroach Labs does not yet place any guarantee on the specific format of the log entries and they can change between releases, including patch revisions. We assume that the entries are meant to be consumed by human operators."

You could add a mention that we are working on it
</blockquote></details>

Done. Added a short callout to convey this.


<!-- Sent from Reviewable.io -->

2021-05-06 12:39 UTC, knz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>
(I think you forgot to add the new callout file to the commit.)

> Reviewed 18 of 18 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10273#-:-M_0g2rWC9taEwSs7Z9_:b-er6d8j)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mikeCRL and @thtruo)



<!-- Sent from Reviewable.io -->

2021-05-11 20:49 UTC, mikeCRL requested changes
Great work, here! Left some comments/suggestions.

2021-05-11 22:16 UTC, thtruo reviewed
Thanks @taroface - barring final touches mentioned in the latest round of comments, this latest iteration generally looks good to me! 

The overall structure is sound, content is easy to parse, and included essential callouts around specific configuration UX (e.g. using shell redirection syntax to pass in yaml files directly)

This LGTM

2021-05-11 22:33 UTC, taroface reviewed
TFTR Mike!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10273#-:-M_SYy-o1FpNZySjuPRx:b-qgtwkg)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz and @mikeCRL)

___
*[_includes/sidebar-data-v21.1.json, line 2748 at r7](https://reviewable.io/reviews/cockroachdb/docs/10273#-MXd_Dnn_wZpy9ZPSbeM-r7-2748:-M_SYw3dEjzD174wyecx:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/e45c6ddfcba8400fd43ea83f20a5befb182915a4/_includes/sidebar-data-v21.1.json#L2748)):*
<details><summary><i>Previously, mikeCRL (Mike Lewis) wrote…</i></summary><blockquote>

Consider renaming to log-sinks.html to match our other pages.

(Same with logformats.html as I mentioned elsewhere.)
</blockquote></details>

Done.
___
*[_includes/v21.1/misc/logging-flags.md, line 4 at r7](https://reviewable.io/reviews/cockroachdb/docs/10273#-MXd_Dnn_wZpy9ZPSbeN-r7-4:-M_SSx595EDx5HLfLSJI:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/e45c6ddfcba8400fd43ea83f20a5befb182915a4/_includes/v21.1/misc/logging-flags.md#L4)):*
<details><summary><i>Previously, mikeCRL (Mike Lewis) wrote…</i></summary><blockquote>

Consider adding a phrase to this and the other deprecated `--log*` flag descriptions like "This is now handled by the log [configuration](configure-logs.html) YAML specified with `--log`." Or if not applicable, some other detail about its current state/effect/lack thereof.
</blockquote></details>

Done.
___
*[v21.1/common-errors.md, line 33 at r7](https://reviewable.io/reviews/cockroachdb/docs/10273#-MXd_Dnn_wZpy9ZPSbec-r7-33:-M_ST1xy2hvsMQ_l7S1l:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/e45c6ddfcba8400fd43ea83f20a5befb182915a4/v21.1/common-errors.md#L33)):*
<details><summary><i>Previously, mikeCRL (Mike Lewis) wrote…</i></summary><blockquote>

```suggestion
If you're not sure what the IP address/hostname and port values might have been, you can look in the node's [logs](logging-overview.html). If necessary, you can also terminate the `cockroach` process and then restart the node:
```
</blockquote></details>

Done.
___
*[v21.1/configure-logs.md, line 17 at r7](https://reviewable.io/reviews/cockroachdb/docs/10273#-MXd_Dnn_wZpy9ZPSbed-r7-17:-M_STg7A4-GT7VreiwnI:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/e45c6ddfcba8400fd43ea83f20a5befb182915a4/v21.1/configure-logs.md#L17)):*
<details><summary><i>Previously, mikeCRL (Mike Lewis) wrote…</i></summary><blockquote>

I'm not sure what it means here to be backward compatible with an earlier version if we're talking about recording new logs, and the new feature requires v21.1. Maybe this could be clarified.
</blockquote></details>

Done.
___
*[v21.1/configure-logs.md, line 63 at r7](https://reviewable.io/reviews/cockroachdb/docs/10273#-MXd_Dnn_wZpy9ZPSbed-r7-63:-M_STo-h8ASwaACGXQH0:b-r8jkq1) ([raw file](https://github.com/cockroachdb/docs/blob/e45c6ddfcba8400fd43ea83f20a5befb182915a4/v21.1/configure-logs.md#L63)):*
<details><summary><i>Previously, mikeCRL (Mike Lewis) wrote…</i></summary><blockquote>

```suggestion
You can view your current settings by running `cockroach debug check-log-config`, which returns the YAML definitions and a URL for visualizing the current logging configuration.
```
</blockquote></details>

I'm going to keep the original wording for this one, as I think it is more accurate (if somewhat a mouthful).
___
*[v21.1/eventlog.md, line 7 at r7](https://reviewable.io/reviews/cockroachdb/docs/10273#-MXd_g0nL85AKCEEio1E-r7-7:-M_SUBns20qzgNyQMZ5T:boqn98t) ([raw file](https://github.com/cockroachdb/docs/blob/e45c6ddfcba8400fd43ea83f20a5befb182915a4/v21.1/eventlog.md#L7)):*
<details><summary><i>Previously, mikeCRL (Mike Lewis) wrote…</i></summary><blockquote>

Let me know if you'd like me to go back and review the include. I skimmed.

FYI in this one I noticed 22 cases where we lack a description, in case you want to ensure there is a `cockroach` repo issue for improving this.
</blockquote></details>

Will make a note of this.
___
*[v21.1/logging.md, line 7 at r7](https://reviewable.io/reviews/cockroachdb/docs/10273#-MXd_g0nL85AKCEEio1G-r7-7:-M_SUCooEmjHfIEuc_xg:boqn98t) ([raw file](https://github.com/cockroachdb/docs/blob/e45c6ddfcba8400fd43ea83f20a5befb182915a4/v21.1/logging.md#L7)):*
<details><summary><i>Previously, mikeCRL (Mike Lewis) wrote…</i></summary><blockquote>

We could link SENSITIVE_ACCESS (in this remote_include) back to `experimental-audit.md` if appropriate. There may be other opportunities to go back to the generated docs and add links back to the new docs, as a follow-up task, post-release.
</blockquote></details>

Will make a note of this.
___
*[v21.1/logsinks.md, line 2 at r7](https://reviewable.io/reviews/cockroachdb/docs/10273#-MXd_g0nL85AKCEEio1H-r7-2:-M_SYKjk0SYCeZCXvkw6:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/e45c6ddfcba8400fd43ea83f20a5befb182915a4/v21.1/logsinks.md#L2)):*
<details><summary><i>Previously, mikeCRL (Mike Lewis) wrote…</i></summary><blockquote>

Log Sinks seems more common. Consider renaming?

Regardless, I believe the file name for the page should have a hyphen per our convention.
</blockquote></details>

Done.
___
*[v21.1/query-behavior-troubleshooting.md, line 148 at r7](https://reviewable.io/reviews/cockroachdb/docs/10273#-MXd_Dnn_wZpy9ZPSbem-r7-148:-M_SYRuA06wZgEurUyEI:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/e45c6ddfcba8400fd43ea83f20a5befb182915a4/v21.1/query-behavior-troubleshooting.md#L148)):*
<details><summary><i>Previously, mikeCRL (Mike Lewis) wrote…</i></summary><blockquote>

```suggestion
If you are testing CockroachDB locally and want to log queries executed just by a specific node, you can either pass a CLI flag at node startup or execute a SQL function on a running node.
```
</blockquote></details>

Done.
___
*[v21.1/query-behavior-troubleshooting.md, line 150 at r7](https://reviewable.io/reviews/cockroachdb/docs/10273#-MXd_Dnn_wZpy9ZPSbem-r7-150:-M_SYTnH2PDUsf59VmdO:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/e45c6ddfcba8400fd43ea83f20a5befb182915a4/v21.1/query-behavior-troubleshooting.md#L150)):*
<details><summary><i>Previously, mikeCRL (Mike Lewis) wrote…</i></summary><blockquote>

I don't think of it as passing a flag _to the command_ but more about passing data/information to the application/script _using_ a flag 'on/with' the command. This is not authoritative so take with a grain of salt.

```suggestion
Using the CLI to start a new node, use the `--vmodule` flag with the [`cockroach start`](cockroach-start.html) command. For example, to start a single node locally and log all client-generated SQL queries it executes, you'd run:
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-12 17:36 UTC, merged