COPY FROM support for CSV, DELIMITER, NULL
cockroachdb/docs pull request #10316
Opened 2021-04-13 18:40 UTC by ericharmeling

Fixes https://github.com/cockroachdb/docs/issues/10061.
Fixes https://github.com/cockroachdb/docs/issues/10062.

2021-04-13 18:40 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/10316)
<!-- Reviewable:end -->

2021-04-13 23:04 UTC, rafiss requested changes
lgtm but one typo!

2021-04-13 23:04 UTC, rafiss commented on v21.1/copy-from.md
> +`CSV` | <span class="version-tag">New in v21.1:</span> Copy data from CSV format. If `CVS` is specified, no other format can be specified.<br>If no format is specified, CockroachDB copies in plaintex
typo on the third "CSV"

2021-04-14 14:20 UTC, ericharmeling commented on v21.1/copy-from.md
> +`CSV` | <span class="version-tag">New in v21.1:</span> Copy data from CSV format. If `CVS` is specified, no other format can be specified.<br>If no format is specified, CockroachDB copies in plaintex
Good catch. Fixed.

2021-04-14 14:20 UTC, ericharmeling commented
TFTR @rafiss !

2021-04-14 15:48 UTC, ianjevans approved these changes

2021-04-14 15:57 UTC, merged