Abbey cdc
cockroachdb/docs pull request #10310
Opened 2021-04-13 13:31 UTC by amruss

Added callouts to the fact that changefeeds will be disabled on Regional By Row tables in 21.1. Let me know if there are additional places I should add callouts to.

@gemma-shay who should I ask to review on the multi region side?

2021-04-13 13:31 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/10310)
<!-- Reviewable:end -->

2021-04-13 19:39 UTC, gemma-shay requested changes
LGTM besides 2 small changes! Not sure about multi-region reviewer, want me to ask the docs team?

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10310#-:-MYBjFJqETeHG_EJeufJ:b-99e2bx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @amruss and @stevendanna)

___
*[_includes/v21.1/known-limitations/cdc.md, line 1 at r1](https://reviewable.io/reviews/cockroachdb/docs/10310#-MYBiVa80jlIkwXVED9B:-MYBiVa80jlIkwXVED9C:b9c5z3d) ([raw file](https://github.com/cockroachdb/docs/blob/05077dd5a096cd7791a03177320f7bd064a659ff/_includes/v21.1/known-limitations/cdc.md#L1)):*
> ```Markdown
> - Changefeeds do not work on _regional by row_ tables. Any running changefeed job will fail when setting a table's locality to [`REGIONAL BY ROW`](set-locality.html).
> ```

nit: might rephrase "when setting a table's locality" to "when a table's locality is set..."

BTW, Italics are working fine here. I think it's just an issue in callouts.
___
*[v21.1/set-locality.md, line 67 at r1](https://reviewable.io/reviews/cockroachdb/docs/10310#-MYBg7nq906emk4SClWt:-MYBg7nr1Gk6orQ_or1l:b-pkmupz) ([raw file](https://github.com/cockroachdb/docs/blob/05077dd5a096cd7791a03177320f7bd064a659ff/v21.1/set-locality.md#L67)):*
> ```Markdown
> ### Set the table locality to `REGIONAL BY ROW`
> 
> {{site.data.alerts.callout_info}} Changefeeds are not currently supported on _regional by row_ tables and any ongoing changefeed job will fail when setting locality to `REGIONAL BY ROW` {{site.data.alerts.end}}
> ```

The italics here aren't rendering. I'm not sure if it's a docs UX issue with callouts or just in the Netlify preview, but maybe try using `<em>regional by row</em>` instead.


<!-- Sent from Reviewable.io -->

2021-04-14 07:32 UTC, stevendanna reviewed
Overall this looks correct to me.  

I wonder, however, if we might want to avoid any possible doubt about which changefeeds will be cancelled.

Perhaps, instead of 

> Any running changefeed job will fail when setting a table's locality to [`REGIONAL BY ROW`](set-locality.html).

something like:

> When a table's locality is set to `REGIONAL BY ROW`, changefeed jobs targeting that that table will fail.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10310#-:-MYEGWks7vYvnD0tBSLQ:bosogop)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @amruss)



<!-- Sent from Reviewable.io -->

2021-04-14 07:33 UTC, stevendanna reviewed
> When a table's locality is set to REGIONAL BY ROW, changefeed jobs targeting that that table will fail.

should be: When a table's locality is set to REGIONAL BY ROW, changefeed jobs targeting that table will fail.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10310#-:-MYEI2tBAXXMB5vqxeX3:b-lrzyta)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @amruss)



<!-- Sent from Reviewable.io -->

2021-04-19 13:16 UTC, amruss commented
Thanks @stevendanna and @gemma-shay, updated the wording re: your comments. Gemma, would you mind finding out who the multi-region docs writer is?

2021-04-19 20:27 UTC, rmloveland approved these changes

2021-04-19 20:27 UTC, rmloveland commented on v21.1/set-locality.md
> +{{site.data.alerts.callout_info}} Changefeeds are not currently supported on <em>regional by row</em> tables. When a table's locality is set to `REGIONAL BY ROW`, changefeed jobs targeting that that
Hi Abbey!  This content LGTM except there is a rendering issue in this callout which I think will be solved by editing the format slightly to the below (also I snuck in a link to CDC stuff, hope that's OK):

```
{{site.data.alerts.callout_info}}
[Changefeeds](stream-data-out-of-cockroachdb-using-changefeeds.md) are not currently supported on regional by row tables. When a table's locality is set to `REGIONAL BY ROW`, any changefeed jobs targeting that that table will fail.
{{site.data.alerts.end}}
```

Alternatively, I can fix this in a follow-up PR if you need to move on to something else, I know this part is not your day job :-)

2021-04-19 21:45 UTC, amruss commented
thanks @rmloveland ! I updated re: your suggestion

2021-04-26 22:58 UTC, amruss commented
@gemma-shay does this look good? I updated re: your suggestions

2021-04-27 16:42 UTC, gemma-shay approved these changes

2021-04-27 22:28 UTC, merged