Migrate from CC Free to CC Dedicated
cockroachdb/docs pull request #10411
Opened 2021-04-22 23:13 UTC by lnhsingh

Add instructions on how to migrate from a CC Free cluster to a paid CC cluster.

Closes [CC-3834](https://cockroachlabs.atlassian.net/browse/CC-3834).

2021-04-22 23:14 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/10411)
<!-- Reviewable:end -->

2021-04-28 19:21 UTC, lnhsingh commented
@mwang1026 / @kannanlakshmi - going to have Rich review this doc to get it moving, but would still appreciate your feedback on it! If you don't have time, please lmk if there's someone else who can review (I wasn't sure if another PM or eng maybe would be appropriate for reviewing instead)

2021-04-29 14:26 UTC, kannanlakshmi reviewed
Hi! I am not really the best person to review this as its bulk-IO work. Michael would be best suited here and I see that he is already cc-ed. 

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10411#-:-MZT0NA0AFG8x95CPLsP:b-7b55wz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mwang1026 and @rmloveland)



<!-- Sent from Reviewable.io -->

2021-04-29 19:41 UTC, rmloveland approved these changes
LGTM and I wrote some things to annoy you but you can ignore them :-)

2021-04-29 19:41 UTC, rmloveland commented on _includes/sidebar-data-v21.1.json
> +              {
hmm snuck in?

2021-04-29 19:41 UTC, rmloveland commented on cockroachcloud/free-faqs.md
> +For an example on how to use this output to migrate to a paid CockroachCloud cluster, see [Migrate from a CockroachCloud Free (beta) to CockroachCloud Cluster](migrate-from-free-to-dedicated.html).
your call but if you delete the "beta" from this you never have to update it again

2021-04-29 19:41 UTC, rmloveland commented on cockroachcloud/migrate-from-free-to-dedicated.md
> +After you've exported your Cockroach Free (beta) cluster data to your local machine, you now need to upload the files to a storage location where the paid CockroachCloud cluster can access them. **We
Rhetorical question: are (beta) we (beta) worried (beta) that (beta) users (beta) might (beta) forget (beta) this (beta) service (beta) is (beta) still (beta) in (beta) beta?

2021-04-29 19:41 UTC, rmloveland commented on cockroachcloud/migrate-from-free-to-dedicated.md
> +After you've exported your Cockroach Free (beta) cluster data to your local machine, you now need to upload the files to a storage location where the paid CockroachCloud cluster can access them. **We
:-)

2021-04-29 19:41 UTC, rmloveland commented on cockroachcloud/migrate-from-free-to-dedicated.md
> +Once all of the tables you want to migrate have been imported into the CockroachCloud cluster, add the foreign key relationships. To do this, use [`ALTER TABLE ... ADD CONSTRAINT`](../{{site.versions
Could link to foreign key docs

2021-04-29 19:41 UTC, rmloveland commented on _includes/sidebar-data-v21.1.json
> +              {
guess this was missing from the TOC?

2021-04-29 20:18 UTC, lnhsingh reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10411#-:-MZUH8f51ZUISP0q7IIC:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mwang1026 and @rmloveland)

___
*[_includes/sidebar-data-v21.1.json, line 2629 at r1](https://reviewable.io/reviews/cockroachdb/docs/10411#-MYvrAR7WS7BkmawGaOv-r1-2629:-MZUGOLO1xgpLjXlNJta:b-cf11w3) ([raw file](https://github.com/cockroachdb/docs/blob/aef33545731e0f5ea9a0a88c7e961f284274aa0d/_includes/sidebar-data-v21.1.json#L2629)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

guess this was missing from the TOC?
</blockquote></details>

I noticed it and pulled it in instead of opening a second PR :grimacing: 
___
*[cockroachcloud/free-faqs.md, line 104 at r1](https://reviewable.io/reviews/cockroachdb/docs/10411#-MYvrAR7WS7BkmawGaOw-r1-104:-MZUGVae3zHAME8eFgY4:b-cq7iwe) ([raw file](https://github.com/cockroachdb/docs/blob/aef33545731e0f5ea9a0a88c7e961f284274aa0d/cockroachcloud/free-faqs.md#L104)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

your call but if you delete the "beta" from this you never have to update it again
</blockquote></details>

That is true but we are officially referring to it as CockroachCloud Free (beta) (TM). I will just have to CTRL+SHIFT+F and change all of them eventually... what's one more
___
*[cockroachcloud/migrate-from-free-to-dedicated.md, line 70 at r1](https://reviewable.io/reviews/cockroachdb/docs/10411#-MYvrAR7WS7BkmawGaOx-r1-70:-MZUGj6516vrvURFng0c:b2nhswy) ([raw file](https://github.com/cockroachdb/docs/blob/aef33545731e0f5ea9a0a88c7e961f284274aa0d/cockroachcloud/migrate-from-free-to-dedicated.md#L70)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

:-) 
</blockquote></details>

Yes
___
*[cockroachcloud/migrate-from-free-to-dedicated.md, line 176 at r1](https://reviewable.io/reviews/cockroachdb/docs/10411#-MYvrAR7WS7BkmawGaOx-r1-176:-MZUH85P4aIpnjhEdX3T:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/aef33545731e0f5ea9a0a88c7e961f284274aa0d/cockroachcloud/migrate-from-free-to-dedicated.md#L176)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Could link to foreign key docs
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-29 20:42 UTC, mwang1026 requested changes
Overall looks good. A few nits.

Curious why we went the route of IMPORT vs. CREATE TABLE and then IMPORT INTO? I know it's a few more steps so maybe that's it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10411#-:-MZUMLvhDBb8tsPlgfP4:bn0yutl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kannanlakshmi, @lnhsingh, and @rmloveland)

___
*[cockroachcloud/migrate-from-free-to-dedicated.md, line 70 at r1](https://reviewable.io/reviews/cockroachdb/docs/10411#-MYvrAR7WS7BkmawGaOx-r1-70:-MZULSboBpOeI0jJaDVU:b-zci2n6) ([raw file](https://github.com/cockroachdb/docs/blob/aef33545731e0f5ea9a0a88c7e961f284274aa0d/cockroachcloud/migrate-from-free-to-dedicated.md#L70)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

Userfile also should work on Cockroach Cloud, but only after I think 20.2.7 or so where we fixed a bug. Soooo.... ya maybe we revisit once everyone's on latest minor version.
___
*[cockroachcloud/migrate-from-free-to-dedicated.md, line 10 at r2](https://reviewable.io/reviews/cockroachdb/docs/10411#-MZUJv821LNrgvEUv9C8:-MZUJv821LNrgvEUv9C9:b-ub0qqf) ([raw file](https://github.com/cockroachdb/docs/blob/7007410d1d9b424eb82fc5cf7d3a6964f6ac8206/cockroachcloud/migrate-from-free-to-dedicated.md#L10)):*
> ```
> like the ability to enable backups or to import data.
> ```

So this is coming after we upgrade to 21.1. Will we change docs then?

Also, I'd suggest something like `upload data with the IMPORT command` vs `import data`. a LOT of github issues where people talk about "importing data" but they're really just running a bunch of bulk inserts.
___
*[cockroachcloud/migrate-from-free-to-dedicated.md, line 49 at r2](https://reviewable.io/reviews/cockroachdb/docs/10411#-MZULGZB0P70F-RRl4GD:-MZULGZB0P70F-RRl4GE:b-xf5be1) ([raw file](https://github.com/cockroachdb/docs/blob/7007410d1d9b424eb82fc5cf7d3a6964f6ac8206/cockroachcloud/migrate-from-free-to-dedicated.md#L49)):*
> ```
> distrcit
> ```

TYPO TYPO


<!-- Sent from Reviewable.io -->

2021-04-29 21:05 UTC, lnhsingh reviewed
I went with IMPORT since it's fewer steps. It could be a follow up mini project to add steps on how to do it with CREATE + IMPORT INTO - I'll add an issue

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10411#-:-MZURVgX7Qy1jIFEIkeR:b-thmta3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kannanlakshmi, @mwang1026, and @rmloveland)

___
*[cockroachcloud/migrate-from-free-to-dedicated.md, line 70 at r1](https://reviewable.io/reviews/cockroachdb/docs/10411#-MYvrAR7WS7BkmawGaOx-r1-70:-MZUQuf15VWv57I5J5R4:b-fkx62t) ([raw file](https://github.com/cockroachdb/docs/blob/aef33545731e0f5ea9a0a88c7e961f284274aa0d/cockroachcloud/migrate-from-free-to-dedicated.md#L70)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

Userfile also should work on Cockroach Cloud, but only after I think 20.2.7 or so where we fixed a bug. Soooo.... ya maybe we revisit once everyone's on latest minor version.
</blockquote></details>

I'll add it now - I think it's a low risk callout since new CC clusters are now running 20.2.8 I think.
___
*[cockroachcloud/migrate-from-free-to-dedicated.md, line 10 at r2](https://reviewable.io/reviews/cockroachdb/docs/10411#-MZUJv821LNrgvEUv9C8:-MZUQWkb0KfD1YCBMPAl:b-xjbpfl) ([raw file](https://github.com/cockroachdb/docs/blob/7007410d1d9b424eb82fc5cf7d3a6964f6ac8206/cockroachcloud/migrate-from-free-to-dedicated.md#L10)):*
> Will we change docs then?

Yep, that's the plan.
___
*[cockroachcloud/migrate-from-free-to-dedicated.md, line 49 at r2](https://reviewable.io/reviews/cockroachdb/docs/10411#-MZULGZB0P70F-RRl4GD:-MZUQgDo-4Bo_L9eJJP2:bl1hl02) ([raw file](https://github.com/cockroachdb/docs/blob/7007410d1d9b424eb82fc5cf7d3a6964f6ac8206/cockroachcloud/migrate-from-free-to-dedicated.md#L49)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

> ```
> distrcit
> ```

TYPO TYPO
</blockquote></details>

Whoops - Done.


<!-- Sent from Reviewable.io -->

2021-04-29 21:49 UTC, jseldess commented on cockroachcloud/migrate-from-free-to-dedicated.md
> +This page has instructions for migrating data from a CockroachCloud Free (beta) cluster to a paid CockroachCloud cluster CSV using [`IMPORT`](../{{site.versions["stable"]}}/import.html). You may want
@lnhsingh, `cluster CSV using...` seems off.

2021-04-29 21:51 UTC, jseldess commented on cockroachcloud/migrate-from-free-to-dedicated.md
> +By running the above example command above, the following data is exported to the local `warehouse.csv` file:
Need to remove one instance of `above`.

2021-04-29 21:53 UTC, jseldess commented on cockroachcloud/migrate-from-free-to-dedicated.md
> +    You can use the [`SHOW CREATE TABLE`](../{{site.versions["stable"]}}/show-create.html#show-the-create-table-statement-for-a-table) in the CockroachCloud Free (beta) cluster to view the `CREATE` s
`the SHOW CREATE TABLE in the...` > `the SHOW CREATE TABLE statement in the...`

2021-04-30 16:10 UTC, lnhsingh reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10411#-:-MZYY0e_1j2-eHclxrY-:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess, @kannanlakshmi, @mwang1026, and @rmloveland)

___
*[cockroachcloud/migrate-from-free-to-dedicated.md, line 7 at r3](https://reviewable.io/reviews/cockroachdb/docs/10411#-MYvrAR7WS7BkmawGaOx-r3-7:-MZYXjru5h612NBjE8Di:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f362bf82ecd892be515a7dbc237ee1103c6ad96b/cockroachcloud/migrate-from-free-to-dedicated.md#L7)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

@lnhsingh, `cluster CSV using...` seems off. 
</blockquote></details>

Done.
___
*[cockroachcloud/migrate-from-free-to-dedicated.md, line 36 at r3](https://reviewable.io/reviews/cockroachdb/docs/10411#-MYvrAR7WS7BkmawGaOx-r3-36:-MZYXqBc4TCDW6eo0PlW:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f362bf82ecd892be515a7dbc237ee1103c6ad96b/cockroachcloud/migrate-from-free-to-dedicated.md#L36)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Need to remove one instance of `above`.
</blockquote></details>

Done.
___
*[cockroachcloud/migrate-from-free-to-dedicated.md, line 90 at r3](https://reviewable.io/reviews/cockroachdb/docs/10411#-MYvrAR7WS7BkmawGaOx-r3-90:-MZYXzmR3QjjPbCezwtX:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f362bf82ecd892be515a7dbc237ee1103c6ad96b/cockroachcloud/migrate-from-free-to-dedicated.md#L90)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

`the SHOW CREATE TABLE in the...` > `the SHOW CREATE TABLE statement in the...`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-30 16:44 UTC, merged