Add Auto TLS page and links to it from secure cluster configuration pages
cockroachdb/docs pull request #10539
Opened 2021-05-11 17:26 UTC by mikeCRL

2021-05-12 20:37 UTC, aaron-crl reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10539)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mikeCRL)

___
*[v21.1/auto-tls.md, line 41 at r5](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XHfn570ox1pg3DO0g:-M_XHfn570ox1pg3DO0h:b-wov7u6) ([raw file](https://github.com/cockroachdb/docs/blob/0e6b91894cf74bc76e99b2a8f89dfc57caeb0825/v21.1/auto-tls.md#L41)):*
> ```Markdown
>   ```
> 
> 2. For each node, run `cockroach connect`, specifying the initial number of nodes and the address and ports that each will use.
> ```

Might be worth noting that this process will not terminate until all nodes have initialized.


<!-- Sent from Reviewable.io -->

2021-05-12 21:20 UTC, mikeCRL reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10539)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl)

___
*[v21.1/auto-tls.md, line 41 at r5](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XHfn570ox1pg3DO0g:-M_XOf-j6aQoTfhIc834:b-mmg8wc) ([raw file](https://github.com/cockroachdb/docs/blob/0e6b91894cf74bc76e99b2a8f89dfc57caeb0825/v21.1/auto-tls.md#L41)):*
<details><summary><i>Previously, aaron-crl wrote…</i></summary><blockquote>

Might be worth noting that this process will not terminate until all nodes have initialized.
</blockquote></details>

I added this. I assumed that this is another way of saying that the process will run until `cockroach init` is run successfully but please correct me if wrong. New commit diff here https://github.com/cockroachdb/docs/pull/10539/commits/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16 . 


<!-- Sent from Reviewable.io -->

2021-05-12 21:24 UTC, aaron-crl reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10539)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @mikeCRL, and @taroface)

___
*[v21.1/auto-tls.md, line 16 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XRzyHBD9pCjC4Ibhr:-M_XRzyHBD9pCjC4Ibhs:b-krlktk) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/v21.1/auto-tls.md#L16)):*
> ```Markdown
> This feature is an alpha release in CockroachDB v21.1 with core functionality that may not yet meet your requirements. Planned enhancements in future versions include:
> 
> - Auto TLS cert generation when adding nodes to an existing cluster, though cert generation for new nodes is already possible using `cockroach cert` on clusters that initially used Auto TLS.
> ```

nit: I believe our manual `cockroach cert` instructions place the generated ca in a 'safe directory' per: https://www.cockroachlabs.com/docs/v20.2/secure-a-cluster

Auto TLS does not do this as the nodes maintain their own certificates and the ca lives in the `certs/` directory. We should expect a minor tweak to that pathing if a user attempts to follow the add steps verbatim.


<!-- Sent from Reviewable.io -->

2021-05-12 21:32 UTC, aaron-crl reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10539)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mikeCRL and @taroface)

___
*[v21.1/auto-tls.md, line 41 at r5](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XHfn570ox1pg3DO0g:-M_XTI2L5m5FPXl2xHzE:b-4rh7xn) ([raw file](https://github.com/cockroachdb/docs/blob/0e6b91894cf74bc76e99b2a8f89dfc57caeb0825/v21.1/auto-tls.md#L41)):*
<details><summary><i>Previously, mikeCRL (Mike Lewis) wrote…</i></summary><blockquote>

I added this. I assumed that this is another way of saying that the process will run until `cockroach init` is run successfully but please correct me if wrong. New commit diff here https://github.com/cockroachdb/docs/pull/10539/commits/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16 . 
</blockquote></details>

Yes though just the TLS init not the `cockroach init` in this case. See minor nit below.
___
*[v21.1/auto-tls.md, line 48 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XU8x0-QaZRrrc0jNn:-M_XU8x0-QaZRrrc0jNo:b-imptw7) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/v21.1/auto-tls.md#L48)):*
> ```Markdown
>   ```
> 
> This process will not terminate until the cluster and all its nodes have initialized.
> ```

_minor_ nit for clarity: s/initialized/provisioned their TLS certificates/.


<!-- Sent from Reviewable.io -->

2021-05-12 23:09 UTC, taroface requested changes
I have a mix of comments on 1) formatting/style and 2) clarifying how this feature works. It could be my lack of expertise on cert authentication, but I think some of the specifics (exactly which files are distributed using Auto TLS) could be clearer in places. Let me know if you have questions about my questions; I could probably have been more concise with them.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10539#-:-M_XpBqk11oH7TAWlBfY:bh0r345)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mikeCRL)

___
*[_includes/v21.1/prod-deployment/secure-generate-certificates.md, line 1 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XUiE44Y-MtqC1fjal:-M_XUiE44Y-MtqC1fjam:bmkadna) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/_includes/v21.1/prod-deployment/secure-generate-certificates.md#L1)):*
> ```Markdown
> You can use `cockroach cert` commands, [`openssl` commands](create-security-certificates-openssl.html), or [Auto TLS cert generation](auto-tls.html) (alpha) to generate security certificates. This section features the `cockroach cert` commands.
> ```

Suggesting linking `cockroach cert` to the corresponding page
___
*[v21.1/auto-tls.md, line 2 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XUtws60cEcyh96vsJ:-M_XUtws60cEcyh96vsK:bf99vt1) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/v21.1/auto-tls.md#L2)):*
> ```Markdown
> ---
> title: Use Auto TLS (alpha) to generate security certificates
> ```

Suggestion: I wonder if "security" can be cut from the title. Is it redundant?
___
*[v21.1/auto-tls.md, line 4 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XV4W94iKUnetoyCXf:-M_XV4W94iKUnetoyCXg:bsnay6x) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/v21.1/auto-tls.md#L4)):*
> ```Markdown
> title: Use Auto TLS (alpha) to generate security certificates
> summary: Let CockroachDB handle TLS cert creation for encrypted inter-node and client-node communication.
> toc: true
> ```

I don't see this in the sidebar nav on preview. Are we intentionally keeping it hidden since it's alpha?
___
*[v21.1/auto-tls.md, line 7 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XVFFeCpPrO5Rn1pyR:-M_XVFFeCpPrO5Rn1pyS:b11lvwo) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/v21.1/auto-tls.md#L7)):*
> ```Markdown
> ---
> 
> To secure your CockroachDB cluster's inter-node and client-node communication, you need to provide a Certificate Authority (CA) certificate that has been used to sign keys and certificates (SSLs) for:
> ```

Based on usage in authentication.html and K8s docs, we've been keeping Certificate Authority lowercase. (I also see it's lowercase later on in this doc.)

Also, is this paragraph describing the "normal" method of authentication that Auto TLS is simplifying? It could be taken as a requirement of Auto TLS.

Finally, since I'm not familiar with this feature, double-checking that "has been used" means that the CA cert must have already authenticated the below items? My naive tendency here is to read this as a "certificate that can be used to sign..." - is there a way to be clearer on the significance of "has been used"? Not sure if I'm making myself clear...
___
*[v21.1/auto-tls.md, line 11 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XVWf-2oB_EaNP5GuP:-M_XVWf-2oB_EaNP5GuQ:bv80sju) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/v21.1/auto-tls.md#L11)):*
> ```Markdown
> - Nodes
> - Clients
> - Optionally: the DB Console and Cluster API
> ```

Link "DB Console" to https://www.cockroachlabs.com/docs/v21.1/authentication.html#using-a-public-ca-certificate-to-access-the-db-console-for-a-secure-cluster

(and "Cluster API" to corresponding doc, when it's ready?)
___
*[v21.1/auto-tls.md, line 14 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XW637DxyzcO5SMk5l:-M_XW637DxyzcO5SMk5m:bmn09q) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/v21.1/auto-tls.md#L14)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> This feature is an alpha release in CockroachDB v21.1 with core functionality that may not yet meet your requirements. Planned enhancements in future versions include:
> ```

Per our convention, I'd suggest prepending this with `<span class="version-tag">New in v21.1:</span>` and cutting "in CockroachDB v21.1"
___
*[v21.1/auto-tls.md, line 16 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XWMlcC14m_aOYyvmb:-M_XWMlcC14m_aOYyvmc:b-d85nls) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/v21.1/auto-tls.md#L16)):*
> ```Markdown
> This feature is an alpha release in CockroachDB v21.1 with core functionality that may not yet meet your requirements. Planned enhancements in future versions include:
> 
> - Auto TLS cert generation when adding nodes to an existing cluster, though cert generation for new nodes is already possible using `cockroach cert` on clusters that initially used Auto TLS.
> ```

Link `cockroach cert` here to the corresponding page.
___
*[v21.1/auto-tls.md, line 20 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XavVMEZNk85J51rf_:-M_XavVMEZNk85J51rfa:br6e5tb) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/v21.1/auto-tls.md#L20)):*
> ```Markdown
> - Identification of misconfigurations leading to helpful error messages.
> - Other CLI instructions and feedback.
> {{site.data.alerts.end}}
> ```

I think this callout should be moved below the next paragraph ("With Auto TLS, ...") so that the feature has been formally introduced by the time this callout is read.
___
*[v21.1/auto-tls.md, line 22 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XX_GUEVZQQIXWR93d:-M_XX_GUEVZQQIXWR93e:bwimlss) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/v21.1/auto-tls.md#L22)):*
> ```Markdown
> {{site.data.alerts.end}}
> 
> With Auto TLS, your cluster creates the CA (certificate authority) required for secure communication with other nodes and clients and then securely distributes it among the nodes. The cluster also creates the certificates that nodes require to connect to other nodes.
> ```

Nit: "securely distributes it" -> "securely distributes the CA" <- I think? But it sounds from the doc like Auto TLS is also distributing the certs and keys? I'm unclear on this.

"certificates that nodes require to" (could read like "certificates that are required to connect") -> "certificates that nodes require in order to" or "certificates used by nodes to" or "certificates required for node-node connection" ...
___
*[v21.1/auto-tls.md, line 24 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XgLYTD8np35r1T0vs:-M_XgLYTD8np35r1T0vt:b6qjao4) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/v21.1/auto-tls.md#L24)):*
> ```Markdown
> With Auto TLS, your cluster creates the CA (certificate authority) required for secure communication with other nodes and clients and then securely distributes it among the nodes. The cluster also creates the certificates that nodes require to connect to other nodes.
> 
> To receive all certificates, each node must be started with the same secure token that you provide. This simplifies the default cluster creation process. Rather than requiring an operator to generate and distribute cert files, each node only requires this single token string that you will include as part of a one-time `cockroach connect` command.
> ```

Suggest this rephrasing for clarity - please use or discard at your preference:

```
To receive all certificates, each Cockroach node must be provided with a token string before it is started. Th [...]

2021-05-17 04:07 UTC, mikeCRL reviewed
TFTR @taroface and @aaron-crl! Many changes, for your follow-up review, please. Thanks in advance.

Note that when I went to add a link here from authentication.md, I realized that some changes (around TLS 1.3 support) that I made to v20.2 docs are not in v21.1, so I've now fixed that as part of this PR.

@aaron-crl some follow-ups:

1. Is the bit about the Cluster API true? (Or should I confirm with Bilal or Raphael on this?)
2. FYI the reason I am now instructing not to include `-join` as a flag on the first node's `connect` command is because I got non-stop errors when specifying it, until I killed the process.
3. I noticed that `cockroach start` (when run after `cockroach connect`, per this process) is creating the `certs` subdirectory if it doesn't exist. Does it create whatever folder name is specified in --certs-dir? (I did set --certs-dir=certs.) I.e. can this feature use (if not also create) something _other than_ `certs`? And does it create “certs” by default if you leave out --certs-dir? I’m happy to further test this, but haven’t had time yet to test this specifically, and I’m interested in what you may know offhand.
4. How's the current degree of information about the certs/keys that are created? I assume additional detail would be helpful. I logged the following cert/key files in testing: https://docs.google.com/spreadsheets/d/1x9MZ5YkZMaShP0JswssoBpvo995XQVzQ5Dv6eXHnhf0/ ; please let me know if there's any additional clarity we might add to this doc now, or whether you think a follow-up iteration to this effect might be worthwhile. Happy to further discuss, regardless.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10539#-:-M_sQ0hS4xdxzIarjPdV:b3nehp6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl and @taroface)

___
*[_includes/v21.1/prod-deployment/secure-generate-certificates.md, line 1 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XUiE44Y-MtqC1fjal:-M_sFzqj2lcstAr3xb_H:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/_includes/v21.1/prod-deployment/secure-generate-certificates.md#L1)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Suggesting linking `cockroach cert` to the corresponding page
</blockquote></details>

Done.
___
*[v21.1/auto-tls.md, line 41 at r5](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XHfn570ox1pg3DO0g:-M_sF8iz4WHa7W7Nyz2z:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/0e6b91894cf74bc76e99b2a8f89dfc57caeb0825/v21.1/auto-tls.md#L41)):*
<details><summary><i>Previously, aaron-crl wrote…</i></summary><blockquote>

Yes though just the TLS init not the `cockroach init` in this case. See minor nit below.
</blockquote></details>

Done.
___
*[v21.1/auto-tls.md, line 2 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XUtws60cEcyh96vsJ:-M_cvUaV-73wAoOuHmI8:bcymjsb) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/v21.1/auto-tls.md#L2)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Suggestion: I wonder if "security" can be cut from the title. Is it redundant?
</blockquote></details>

It is rather redundant, but I wanted to remain consistent with the pages "Create security certificates using a custom CA" and "Create security certificates using OpenSSL"
___
*[v21.1/auto-tls.md, line 4 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XV4W94iKUnetoyCXf:-M_sHYfZDabPmNSzCvN0:brnu77n) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/v21.1/auto-tls.md#L4)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

I don't see this in the sidebar nav on preview. Are we intentionally keeping it hidden since it's alpha?
</blockquote></details>

I left this out because we don't have a place in the left nav for the parallel cert-gen. pages.

Though they are linked from pages including "Authentication" which is in the left nav under Deploy > Security.  
https://www.cockroachlabs.com/docs/v20.2/authentication#using-digital-certificates-with-cockroachdb

If this is OK for now, I'm adding a note to our 1:1 doc to have an initial discussion about the left nav, but happy to take on specific improvements.
___
*[v21.1/auto-tls.md, line 7 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XVFFeCpPrO5Rn1pyR:-M_czZ9o5bi4MVOBtH9c:ba01cp2) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/v21.1/auto-tls.md#L7)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Based on usage in authentication.html and K8s docs, we've been keeping Certificate Authority lowercase. (I also see it's lowercase later on in this doc.)

Also, is this paragraph describing the "normal" method of authentication that Auto TLS is simplifying? It could be taken as a requirement of Auto TLS.

Finally, since I'm not familiar with this feature, double-checking that "has been used" means that the CA cert must have already authenticated the below items? My naive tendency here is to read this as a "certificate that can be used to sign..." - is there a way to be clearer on the significance of "has been used"? Not sure if I'm making myself clear...
</blockquote></details>

This was text replicated from our other 'use X to generate security certificates' pages, which I now see is a bit unclear. Your comment makes complete sense and I've updated this. (I've made a note to review the other pages for clarification, as well.)
___
*[v21.1/auto-tls.md, line 11 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XVWf-2oB_EaNP5GuP:-M_d-7xmD7sYPdM6ZIQB:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/v21.1/auto-tls.md#L11)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Link "DB Console" to https://www.cockroachlabs.com/docs/v21.1/authentication.html#using-a-public-ca-certificate-to-access-the-db-console-for-a-secure-cluster

(and "Cluster API" to corresponding doc, when it's ready?)
</blockquote></details>

Done.
___
*[v21.1/auto-tls.md, line 14 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XW637DxyzcO5SMk5l:-M_s6jVk14xnbjmkeD7I:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/v21.1/auto-tls.md#L14)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Per our convention, I'd suggest prepending this with `<span class="version-tag">New in v21.1:</span>` and cutting "in CockroachDB v21.1"
</blockquote></details>

Done.
___
*[v21.1/auto-tls.md, line 16 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XRzyHBD9pCjC4Ibhr:-M_d0LRI8Gvq5YQ4oJIp:b-he4qei) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/v21.1/auto-tls.md#L16)):*
<details><summary><i>Previously, aaron-crl wrote…</i></summary><blockquote>

nit: I believe our manual `cockroach cert` instructions place the generated ca in a 'safe directory' per: https://www.cockroachlabs.com/docs/v20.2/secure-a-cluster

Auto TLS does not do this as the nodes maintain their own certificates and the ca lives in the `certs/` directory. We should expect a minor tweak to that pathing if a user attempts to follow the add steps verbatim.
</blockquote></details>

Made an edit to point this out. Please review the new text.
___
*[v21.1/auto-tls.md, line 16 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XWMlcC14m_aOYyvmb:-M_s7FgU3nOVVNq_tCkd:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/v21.1/auto-tls.md#L16)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Link `cockroach cert` here to the corresponding page.
</blockquote> [...]

2021-05-17 14:25 UTC, aaron-crl reviewed
> Is the bit about the Cluster API true? (Or should I confirm with Bilal or Raphael on this?)

I'm not sure which cert the Cluster API uses, will have to defer to @itsbilal or @knz sorry.

> FYI the reason I am now instructing not to include -join as a flag on the first node's connect command is because I got non-stop errors when specifying it, until I killed the process.

That sounds like a bug. Would you mind capturing those errors and filing a ticket?

> I noticed that cockroach start (when run after cockroach connect, per this process) is creating the certs subdirectory if it doesn't exist. Does it create whatever folder name is specified in --certs-dir? (I did set --certs-dir=certs.) I.e. can this feature use (if not also create) something other than certs? And does it create “certs” by default if you leave out --certs-dir? I’m happy to further test this, but haven’t had time yet to test this specifically, and I’m interested in what you may know offhand.

The `connect` command only generates and writes certs and their directory structure (after communicating with other nodes). The intention is to eventually fold it directly into `start` with an ergonomic flag.

It does create a default certs directory `~/.cockroach-certs` if none is specified.

> How's the current degree of information about the certs/keys that are created? I assume additional detail would be helpful. I logged the following cert/key files in testing: https://docs.google.com/spreadsheets/d/1x9MZ5YkZMaShP0JswssoBpvo995XQVzQ5Dv6eXHnhf0/ ; please let me know if there's any additional clarity we might add to this doc now, or whether you think a follow-up iteration to this effect might be worthwhile. Happy to further discuss, regardless.

Thank you for this list, it is accurate and exposes a flaw in the design/implementation. The service certs should share a common CA by default across the cluster. My inclination is to default them to use the cluster CA when autogenerating unless the user specifically provides an override path. Related bug: https://github.com/cockroachdb/cockroach/issues/61614

Will highlight the other as another bug. Thank you for surfacing it! Created issue here: https://github.com/cockroachdb/cockroach/issues/65330

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10539#-:-M_uZzfcCNG1ohU_NXuJ:b-mvxzww)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @taroface)



<!-- Sent from Reviewable.io -->

2021-05-17 14:32 UTC, taroface approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> with 2 very small comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10539#-:-M_ujYXm2aRuIJYign5t:b-2aysk4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @mikeCRL)

___
*[v21.1/auto-tls.md, line 4 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XV4W94iKUnetoyCXf:-M_uiOxN8SzyW7RaLunZ:brxp9sq) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/v21.1/auto-tls.md#L4)):*
<details><summary><i>Previously, mikeCRL (Mike Lewis) wrote…</i></summary><blockquote>

I left this out because we don't have a place in the left nav for the parallel cert-gen. pages.

Though they are linked from pages including "Authentication" which is in the left nav under Deploy > Security.  
https://www.cockroachlabs.com/docs/v20.2/authentication#using-digital-certificates-with-cockroachdb

If this is OK for now, I'm adding a note to our 1:1 doc to have an initial discussion about the left nav, but happy to take on specific improvements.
</blockquote></details>

Sounds good.
___
*[v21.1/auto-tls.md, line 7 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XVFFeCpPrO5Rn1pyR:-M_uiWJL7l5_rG1vjvK2:b-7dbx6d) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/v21.1/auto-tls.md#L7)):*
<details><summary><i>Previously, mikeCRL (Mike Lewis) wrote…</i></summary><blockquote>

This was text replicated from our other 'use X to generate security certificates' pages, which I now see is a bit unclear. Your comment makes complete sense and I've updated this. (I've made a note to review the other pages for clarification, as well.)
</blockquote></details>

Super clear now, thanks!
___
*[v21.1/auto-tls.md, line 59 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XcFvB9qgnye71dTr2:-M_uiz82-wUj_lB_lpr1:b-syxv0a) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/v21.1/auto-tls.md#L59)):*
> ```
> node’s
> ```

Super-small nit! Above still looks like a smart apostrophe, which I think should be a straight one.
___
*[v21.1/auto-tls.md, line 66 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XfSKNCJ0xuu_Ql5Po:-M_uj8oO63mVUKE-VI_z:b-rn5c4s) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/v21.1/auto-tls.md#L66)):*
<details><summary><i>Previously, mikeCRL (Mike Lewis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I can't tell what has changed, so just double-checking: Did you mean to keep the "distribute" term here?


<!-- Sent from Reviewable.io -->

2021-05-17 16:39 UTC, mikeCRL reviewed
Thank you both. Updates made. @taroface per my other comment on [updates around] sharing client certs, can I ask you to please take one more look?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10539#-:-M_vBUMW1u4ky-Tra7cG:bov00ux)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @taroface)

___
*[v21.1/auto-tls.md, line 59 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XcFvB9qgnye71dTr2:-M_v9_MY4EPNmVtHTQ65:b-dx9cnx) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/v21.1/auto-tls.md#L59)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> node’s
> ```

Super-small nit! Above still looks like a smart apostrophe, which I think should be a straight one.
</blockquote></details>

Missed this - thanks!
___
*[v21.1/auto-tls.md, line 66 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XfSKNCJ0xuu_Ql5Po:-M_v9gAK6fn6Hky-bjuR:bh049jn) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/v21.1/auto-tls.md#L66)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

I can't tell what has changed, so just double-checking: Did you mean to keep the "distribute" term here?
</blockquote></details>

Ah, I should have mentioned: I'd clarified some earlier text and then thought this was clearer as-is, given the new context. On revisiting now, however, I've decided to get even more explicit and detailed in the process we're describing, and I realized that part of what we're describing (logging in to the SQL shell to create the additional admin users) should happen after the cluster is initialized, so I've rewritten this a bit. Please let me know what you think?

Page intro:

- Now says you'll still need to create and "manually distribute" client certs.

Step 2: Create a client certificate for the root user

- Now says "manually"
- Detailed note about what you'll do in a later step

New Step 4: Create additional users to administer the cluster

- Now explicit around creating the additional users and certs, and what certs to share.


<!-- Sent from Reviewable.io -->

2021-05-17 17:32 UTC, taroface reviewed
Some slight corrections, but overall the clarity is :100: for me now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10539#-:-M_vNcgK4LiEhgfu2MT2:bdeepiu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mikeCRL)

___
*[v21.1/auto-tls.md, line 66 at r6](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_XfSKNCJ0xuu_Ql5Po:-M_vM4cG14agzd5fBDBu:b13hxb7) ([raw file](https://github.com/cockroachdb/docs/blob/f9ac3230cbb97dca10d5ac0bf90c98f1f565eb16/v21.1/auto-tls.md#L66)):*
<details><summary><i>Previously, mikeCRL (Mike Lewis) wrote…</i></summary><blockquote>

Ah, I should have mentioned: I'd clarified some earlier text and then thought this was clearer as-is, given the new context. On revisiting now, however, I've decided to get even more explicit and detailed in the process we're describing, and I realized that part of what we're describing (logging in to the SQL shell to create the additional admin users) should happen after the cluster is initialized, so I've rewritten this a bit. Please let me know what you think?

Page intro:

- Now says you'll still need to create and "manually distribute" client certs.

Step 2: Create a client certificate for the root user

- Now says "manually"
- Detailed note about what you'll do in a later step

New Step 4: Create additional users to administer the cluster

- Now explicit around creating the additional users and certs, and what certs to share.
</blockquote></details>

Makes sense to me now, thanks!
___
*[v21.1/auto-tls.md, line 27 at r10](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_vJ_VE0qMqXPEC6i-p:-M_vJ_VE0qMqXPEC6i-q:bn7deve) ([raw file](https://github.com/cockroachdb/docs/blob/7947cbfe7e29cc4f41ef2e926cc0633be9c0aa85/v21.1/auto-tls.md#L27)):*
> ```
> user)and
> ```

Missing space here.
___
*[v21.1/auto-tls.md, line 80 at r10](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_vN70eDpvLA0A31nwc:-M_vN70eDpvLA0A31nwd:boxcmmc) ([raw file](https://github.com/cockroachdb/docs/blob/7947cbfe7e29cc4f41ef2e926cc0633be9c0aa85/v21.1/auto-tls.md#L80)):*
> ```
> report.
> ```

Change period to colon
___
*[v21.1/auto-tls.md, line 105 at r10](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_vMI7X2rejkF8O0D2u:-M_vMI7X2rejkF8O0D2v:bf6crcl) ([raw file](https://github.com/cockroachdb/docs/blob/7947cbfe7e29cc4f41ef2e926cc0633be9c0aa85/v21.1/auto-tls.md#L105)):*
> ```Markdown
> ## Step 2: Create a client certificate for the root user
> 
> On any node's machine, manually [create the certificate and key pair](cockroach-cert.html#create-the-certificate-and-key-pair-for-a-client) for the root user.
> ```

Same comment as below.
___
*[v21.1/auto-tls.md, line 108 at r10](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_vMC8KD-Adwdy1bhSS:-M_vMC8KD-Adwdy1bhST:b2bomef) ([raw file](https://github.com/cockroachdb/docs/blob/7947cbfe7e29cc4f41ef2e926cc0633be9c0aa85/v21.1/auto-tls.md#L108)):*
> ```Markdown
> 
> {{site.data.alerts.callout_danger}}
> Do not share the root cert. In a later step, you can use the root user to create additional administrative users, specifying their privileges. You can then create and securely share their certs, as appropriate, using the [principle of least privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege).
> ```

In step 4 you have "`root` user" - not sure what our convention is here, but should be consistent.
___
*[v21.1/auto-tls.md, line 126 at r10](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_vJoQc9kESOf9cssBn:-M_vJoQc9kESOf9cssBo:bk9or6d) ([raw file](https://github.com/cockroachdb/docs/blob/7947cbfe7e29cc4f41ef2e926cc0633be9c0aa85/v21.1/auto-tls.md#L126)):*
> ```
> admin role to confer all priviliges
> ```

Add backticks and fix typo:

`admin` role to confer all privileges


<!-- Sent from Reviewable.io -->

2021-05-17 17:40 UTC, mikeCRL reviewed
Thanks @taroface !!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10539#-:-M_vPaDe98024h4jg-EC:bg8qwej)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @taroface)

___
*[v21.1/auto-tls.md, line 27 at r10](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_vJ_VE0qMqXPEC6i-p:-M_vO1h46UG6MBGV8jjC:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/7947cbfe7e29cc4f41ef2e926cc0633be9c0aa85/v21.1/auto-tls.md#L27)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> user)and
> ```

Missing space here.
</blockquote></details>

Done.
___
*[v21.1/auto-tls.md, line 80 at r10](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_vN70eDpvLA0A31nwc:-M_vOF5_6quxnirdLBOM:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/7947cbfe7e29cc4f41ef2e926cc0633be9c0aa85/v21.1/auto-tls.md#L80)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> report.
> ```

Change period to colon
</blockquote></details>

Done.
___
*[v21.1/auto-tls.md, line 105 at r10](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_vMI7X2rejkF8O0D2u:-M_vOuaR5NIRaeL3syHY:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/7947cbfe7e29cc4f41ef2e926cc0633be9c0aa85/v21.1/auto-tls.md#L105)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Same comment as below.
</blockquote></details>

Done.
___
*[v21.1/auto-tls.md, line 108 at r10](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_vMC8KD-Adwdy1bhSS:-M_vOmC9AEp5C0AoHFis:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/7947cbfe7e29cc4f41ef2e926cc0633be9c0aa85/v21.1/auto-tls.md#L108)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

In step 4 you have "`root` user" - not sure what our convention is here, but should be consistent.
</blockquote></details>

Done.
___
*[v21.1/auto-tls.md, line 126 at r10](https://reviewable.io/reviews/cockroachdb/docs/10539#-M_vJoQc9kESOf9cssBn:-M_vPZ_u6or9YG_QmAhD:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/7947cbfe7e29cc4f41ef2e926cc0633be9c0aa85/v21.1/auto-tls.md#L126)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> admin role to confer all priviliges
> ```

Add backticks and fix typo:

`admin` role to confer all privileges
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-17 17:51 UTC, merged