Added key collision warning w IMPORT INTO to common errors and sql docs
cockroachdb/docs pull request #10561
Opened 2021-05-13 17:38 UTC by kathancox

Added more detail in the considerations section of `IMPORT INTO` that it's insert only. Also added the key collision warning to the common errors doc.

Closes #10028

2021-05-13 17:38 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/10561)
<!-- Reviewable:end -->

2021-05-13 19:40 UTC, mwang1026 reviewed
Minor note but otherwise LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10561#-:-M_bEZRF1gK7PEVvgpT8:bqp436l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kathancox)

___
*[v20.2/common-errors.md, line 189 at r1](https://reviewable.io/reviews/cockroachdb/docs/10561#-M_bEPCi0Y0Uo7xr_8-N:-M_bEPCi0Y0Uo7xr_8-O:bj42kkh) ([raw file](https://github.com/cockroachdb/docs/blob/cf6b9e6eb19be1643d1b2dc27859b5a6b5072eca/v20.2/common-errors.md#L189)):*
> ```Markdown
> ## checking for key collisions: ingested key collides with an existing one
> 
> When importing into an existing table with [`IMPORT INTO`](import-into.html), this error occurs because the rows in the import file conflict with an existing primary key. The import will fail as a result. `IMPORT INTO` is an insert-only statement, so you cannot use it to update existing rows. To update rows in an existing table, use the [`UPDATE`](update.html) statement.
> ```

cc'ed you in Slack but conflict I think is not limited to just primary key -- it's any index with a uniqueness constraint (of which PK is one). Depending on what folks say there this might need a slight tweak.


<!-- Sent from Reviewable.io -->

2021-05-16 18:46 UTC, jseldess requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10561)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kathancox and @mwang1026)

___
*[v20.2/common-errors.md, line 189 at r1](https://reviewable.io/reviews/cockroachdb/docs/10561#-M_bEPCi0Y0Uo7xr_8-N:-M_qUQaP0cqfMs_kEUgY:bn9wql5) ([raw file](https://github.com/cockroachdb/docs/blob/cf6b9e6eb19be1643d1b2dc27859b5a6b5072eca/v20.2/common-errors.md#L189)):*
I think I might stay singular here and simplify the uniqueness phrasing:

> because a row in the import file conflicts with an existing primary key or uniqueness constraint. 
___
*[v20.2/common-errors.md, line 23 at r2](https://reviewable.io/reviews/cockroachdb/docs/10561#-M_qTxxY1D4gOWMiMns5:-M_qTxxY1D4gOWMiMns6:b40oirc) ([raw file](https://github.com/cockroachdb/docs/blob/eedcff09e01f4eafe39d74fcc39d389edfb9f817/v20.2/common-errors.md#L23)):*
> ```Markdown
> | [Incremental backups](take-full-and-incremental-backups.html#incremental-backups) | [`pq: failed to verify protection id...`](#pq-failed-to-verify-protection-id)                                                                                                         
> | Ambiguous results                      | [`result is ambiguous`](#result-is-ambiguous)
> | [Import key collision](import-into.html#considerations) | [`checking for key collisions: ingested key collides with an existing one`](#checking-for-key-collisions-ingested-key-collides-with-an-existing-one)                                                                                                                                                                             
> ```

Let's remove the link from `Import key collision`. It's best to jump users down to the relevant section and from there link to the import docs.
___
*[v20.2/import-into.md, line 14 at r2](https://reviewable.io/reviews/cockroachdb/docs/10561#-M_qUKtvBPsx04CgwYjD:-M_qUKtw0lnTTL5KsJrS:b-6mxjmm) ([raw file](https://github.com/cockroachdb/docs/blob/eedcff09e01f4eafe39d74fcc39d389edfb9f817/v20.2/import-into.md#L14)):*
> ```Markdown
> - `IMPORT INTO` cannot be used within a [transaction](transactions.html) or during a [rolling upgrade](upgrade-cockroach-version.html).
> - `IMPORT INTO` invalidates all [foreign keys](foreign-key.html) on the target table. To validate the foreign key(s), use the [`VALIDATE CONSTRAINT`](validate-constraint.html) statement.
> - `IMPORT INTO` is an insert-only statement, it cannot be used to update existing rows—see [`UPDATE`](update.html). Imported rows cannot conflict with primary keys in the existing table, or any other constraints on uniqueness of data.
> ```

I'd replace the first command with either a semicolon or period. 


<!-- Sent from Reviewable.io -->

2021-05-18 13:48 UTC, jseldess approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

Thanks, @kathancox!

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10561#-:-M_zivOQ9oM3_DjGCV8h:b-hm87nk)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kathancox and @mwang1026)



<!-- Sent from Reviewable.io -->

2021-05-18 14:48 UTC, merged