Add guidance for connection pools in microservice architectures
cockroachdb/docs pull request #10765
Opened 2021-06-10 18:24 UTC by rafiss

This helps address _some_ questions about pool sizing in deployments
where a large cluster is shared by many applications.

I don't want to try to address every possible use case, so I also added
a recommendation to perform experimentation.

2021-06-10 18:24 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/10765)
<!-- Reviewable:end -->

2021-06-11 17:51 UTC, ianjevans requested changes
Looks good, just some small edit nits.

2021-06-11 17:51 UTC, ianjevans commented on v20.2/connection-pooling.md
> +In addition to setting a maximum connection pool size, set the maximum number of idle connection if possible. Cockroach Labs recommends setting the maximum number of idle connections pool to the maxi
```suggestion
In addition to setting a maximum connection pool size, set the maximum number of idle connections if possible. Cockroach Labs recommends setting the maximum number of idle connections to the maximum pool size. While this uses more memory, it allows many connections when concurrency is high without having to create a new connection for every new operation.
```

2021-06-11 17:51 UTC, ianjevans commented on v20.2/connection-pooling.md
> +If you have a large number of services connecting to the same cluster, then make sure the number of concurrent active connections across all the services does not exceed this recommendation by a larg
```suggestion
If you have a large number of services connecting to the same cluster, make sure the number of concurrent active connections across all the services does not exceed this recommendation by a large amount. If each service has its own connection pool, then you should make sure the sum of all the pool sizes is close to our maximum connections recommendation. Each workload and application is different, so you should conduct testing to determine the best-performing pool sizes for each service in your architecture.
```

2021-06-11 17:51 UTC, ianjevans commented on v21.1/connection-pooling.md
> +If you have a large number of services connecting to the same cluster, then make sure the number of concurrent active connections across all the services does not exceed this recommendation by a larg
```suggestion
If you have a large number of services connecting to the same cluster, make sure the number of concurrent active connections across all the services does not exceed this recommendation by a large amount. If each service has its own connection pool, then you should make sure the sum of all the pool sizes is close to our maximum connections recommendation. Each workload and application is different, so you should conduct testing to determine the best-performing pool sizes for each service in your architecture.
```

2021-06-11 17:51 UTC, ianjevans commented on v21.1/connection-pooling.md
> +In addition to setting a maximum connection pool size, set the maximum number of idle connection if possible. Cockroach Labs recommends setting the maximum number of idle connections pool to the maxi
```suggestion
In addition to setting a maximum connection pool size, set the maximum number of idle connections if possible. Cockroach Labs recommends setting the maximum number of idle connections to the maximum pool size. While this uses more memory, it allows many connections when concurrency is high without having to create a new connection for every new operation.
```

2021-06-15 04:22 UTC, rafiss commented
thanks! this is ready for another review

2021-06-16 18:44 UTC, ianjevans approved these changes

2021-06-16 21:38 UTC, merged