Added guidance for scaling applications to multiple regions
cockroachdb/docs pull request #10796
Opened 2021-06-16 21:49 UTC by ericharmeling

Fixes https://github.com/cockroachdb/docs/issues/10455.

This PR introduces a new page with guidance on scaling from single-region to multi-region. 

The page includes some general guidance on representing `crdb_region` columns in an ORM, for DML statements, with an example for SQLAlchemy. We can add other examples (notably, in Hibernate) after publishing this page.

2021-06-16 21:49 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/10796)
<!-- Reviewable:end -->

2021-06-21 15:15 UTC, awoods187 requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[v21.1/multiregion-scale-application.md, line 15 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mcj69DqDH6kGOLP0676:-Mcj69DqDH6kGOLP0677:b-a0vcrz) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L15)):*
> ```Markdown
> To scale to multiple regions:
> 
> [1.](#scale-deployments) Scale both the deployment of your database and the deployment of your application to multiple regions.
> ```

Im surprised to see this as one step. I think a more common pattern is to scale the app to multiple regions and then scale the db. Scaling the db also has some nuances to the order in which you do things (like adding the primary region before adding nodes with localities in other regions)
___
*[v21.1/multiregion-scale-application.md, line 17 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mcj5uqp29Nyth9JYDb0:-Mcj5uqp29Nyth9JYDb1:bs4kl9s) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L17)):*
> ```Markdown
> [1.](#scale-deployments) Scale both the deployment of your database and the deployment of your application to multiple regions.
> 
> [2.](#transform-a-single-region-schema-into-a-multi-region-schema) Migrate the database schema from a single-region schema to a multi-region schema, using a schema migration tool.
> ```

I like including the migration tool but it isn't strictly necessary. Should we allude to that more explicitly?
___
*[v21.1/multiregion-scale-application.md, line 23 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mcj6fpeEeQWLdiFvIVq:-Mcj6fpeEeQWLdiFvIVr:boziql3) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L23)):*
> ```Markdown
> ## Scale deployments
> 
> ### Scale database deployments
> ```

the first step is to alter your database and add the primary region = the current single region you operate within. This will keep your read/write traffic the same once you add the other regions. if you didn't do this step first, crdb would try to spread replicas and leaseholders for diversity and availability, potentially negatively impact your existing traffic. However, you if add the primary region first, then add the other regions, no leaseholder or replicas will move holding perf steady. Then, you can upgrade tables to RBR or Global.
___
*[v21.1/multiregion-scale-application.md, line 25 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mcj7YtcAvW4iH6n9riK:-Mcj6SER1wd2dOXDkheB:b8m58an) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L25)):*
> ```Markdown
> ### Scale database deployments
> 
> In order to use CockroachDB's [multi-region capabilities](multiregion-overview.html), your CockroachDB cluster must have nodes deployed in multiple regions, with different [regional localities](multiregion-overview.html#cluster-regions).
> ```

should this be node localities? or regional node localities? 
___
*[v21.1/multiregion-scale-application.md, line 33 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mcj6Yn14yULBv4WckJJ:-Mcj6Yn14yULBv4WckJK:bb2tp10) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L33)):*
> ```Markdown
> - For manual deployments, see [`cockroach start`](cockroach-start.html) and [Manual Deployment](manual-deployment.html).
> 
> ### Scale application deployments
> ```

i think this should be listed first since the user would likely do it first
___
*[v21.1/multiregion-scale-application.md, line 68 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mcj7L5Y0ValW7Tw-b39:-Mcj7L5Y0ValW7Tw-b3A:buq9jrx) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L68)):*
> ```Markdown
> - [Execute SQL statements from a file](cockroach-sql.html#execute-sql-statements-from-a-file) and [Change and Remove Objects in a Database Schema](schema-design-update.html).
> 
> ## Upgrade read/write operations
> ```

we've been calling these table localities 
___
*[v21.1/multiregion-scale-application.md, line 72 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mcj7sJkBMBDw4a493My:-Mcj7sJkBMBDw4a493Mz:b-m2bvr0) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L72)):*
> ```Markdown
> For most multi-region configurations, including the default configuration (`LOCALITY REGIONAL BY TABLE IN PRIMARY REGION` and `SURVIVE ZONE FAILURE`), you do not need to update any client-side read/write operations after migrating your database schema for multi-region features. CockroachDB automatically optimizes queries against multi-region databases, based on the locality of the node executing the query, and on the multi-region configuration of the database.
> 
> However, there are some scenarios in which you might need to update the read/write operations in your application's persistence layer. For example:
> ```

I think its strange to jump over the cool auto-homing and list a bunch of examples of when you wouldn't do that without selling it/showing an example of it for inserts and selects


<!-- Sent from Reviewable.io -->

2021-06-22 14:44 UTC, ericharmeling reviewed
TFTR @awoods187 !

I have some follow-up questions, for clarification. See below. (Apologies if I'm being a bit dense :laughing:.)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10796#-:-McnpxFqBDt31sytCYL7:b-9o1rd2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @awoods187, and @rmloveland)

___
*[v21.1/multiregion-scale-application.md, line 15 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mcj69DqDH6kGOLP0676:-Mcnmf25D13ObHX_FjBC:bur7e5w) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L15)):*
> Im surprised to see this as one step.

Fair enough! I've split up the app and db deployment steps.

>  I think a more common pattern is to scale the app to multiple regions and then scale the db.

This doesn't make much sense to me. You configure which node to connect to when you deploy the application. If you scale your application first, and then you scale your database, you need to re-configure the application (and possibly even re-deploy it, depending on the orchestration tool) to connect to the closest db node after you have already deployed and configured the application once. 

> Scaling the db also has some nuances to the order in which you do things (like adding the primary region before adding nodes with localities in other regions)

So I think we might be talking about different things when we say "scaling the db" here. But maybe I'm misunderstanding what you're saying?

When I say "scale the database deployment", I just mean "add nodes to the cluster" (no multi-region syntax/schema changes included yet). After you add nodes with regional localities, then you can transform the schema for multi-region (i.e., use the multi-region syntax to add the database regions, etc.). I've made these two entirely separate steps, as one of the steps ("Scale database deployments") is about navigating orchestration tools/CockroachCloud to get a cluster deployed in multiple regions, and the other step ("Transform a single-region schema into a multi-region schema") is about executing schema changes in SQL.
___
*[v21.1/multiregion-scale-application.md, line 17 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mcj5uqp29Nyth9JYDb0:-McnmLa7-DlG5rHNrJMT:b57sdmd) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L17)):*
<details><summary><i>Previously, awoods187 (Andy Woods) wrote…</i></summary><blockquote>

I like including the migration tool but it isn't strictly necessary. Should we allude to that more explicitly?
</blockquote></details>

I'll just remove it from here. The dedicated section ("Transform a single-region schema into a multi-region schema") mentions the migration tool.
___
*[v21.1/multiregion-scale-application.md, line 23 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mcj6fpeEeQWLdiFvIVq:-McnxO243C9E3lTvtBx_:b-6gxvxl) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L23)):*
<details><summary><i>Previously, awoods187 (Andy Woods) wrote…</i></summary><blockquote>

the first step is to alter your database and add the primary region = the current single region you operate within. This will keep your read/write traffic the same once you add the other regions. if you didn't do this step first, crdb would try to spread replicas and leaseholders for diversity and availability, potentially negatively impact your existing traffic. However, you if add the primary region first, then add the other regions, no leaseholder or replicas will move holding perf steady. Then, you can upgrade tables to RBR or Global.
</blockquote></details>

So I thought we might be talking about different things when we say "scale database deployments" (see my comment above), but now I'm not so sure.

I understand the workflow to be:

1. Scale database deployment (i.e., add nodes to the cluster with regional localities)
2. Scale application deployment (e.g., deploy Docker images in new regions, with configurations to connect to the closest db node)
3. Execute multi-region DDL statements (i.e., `ALTER DATABASE ... ADD PRIMARY REGION`, `ALTER DATABASE ... ADD REGION`, etc)
4. Update application, if necessary

It seems to me that you are suggesting the following workflow (but I could totally be misinterpreting what you are saying):

1. Scale the application (e.g., deploy Docker images in new regions, with configurations to connect to the *same*, single-region db node)
2. Execute a single `ALTER DATABASE ... ADD PRIMARY REGION` statement on a single-region CDB cluster
3. Scale the database deployment (i.e., add nodes to the cluster with regional localities)
4. Execute the rest of the multi-region DDL statements (`ALTER DATABASE ... ADD REGION`, etc.)
5. Update each application configuration to connect to the closest db node (e.g., update Docker images with new connection strings, and then re-deploy the images)
6. Update application, if necessary.

Is that correct?
___
*[v21.1/multiregion-scale-application.md, line 24 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mco9XuZ0sBUY-II38Ic:-Mco9XuZ0sBUY-II38Id:b-jhwu1p) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L24)):*
> the first step is to alter your database and add the primary region = the current single region you operate within. This will keep your read/write traffic the same once you add the other regions. 

A couple questions:

 - By "first step", do you mean before you have added any new nodes to your cluster (in new regions)?
- By "add other regions", do you mean "add other database regions" or "add other cluster regions" (i.e., "add new nodes to the cluster with other regional localities")? IIUC, the order of adding database regions is enforced in CRDB multi-region syntax. That is, you must add the primary database region before other database regions can be added.
___
*[v21.1/multiregion-scale-application.md, line 25 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mcj7YtcAvW4iH6n9riK:-McnxUNJ5g4IwJXsTQGK:b-4zj5er) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L25)):*
<details><summary><i>Previously, awoods187 (Andy Woods) wrote…</i></summary><blockquote>

should this be node localities? or regional node localities? 
</blockquote></details>

Updated to read "regional node localities".
___
*[v21.1/multiregion-scale-application.md, line 33 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mcj6Yn14yULBv4WckJJ:-Mcnx-O99Av-EzXeK8eZ:b-upj58l) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L33)):*
<details><summary><i>Previously, awoods187 (Andy Woods) wrote…</i></summary><blockquote>

i think this should be listed first since the user would likely do it first
</blockquote></details>

See my comments above.
___
*[v21.1/multiregion-scale-application.md, line 68 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mcj7L5Y0ValW7Tw-b39:-McnzJ7p-lMuLr5k1qVE:b-wpo9c6) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L68)):*
<details><summary><i>Previously, awoods187 (Andy Woods) wrote…</i></summary><blockquote>

we've been calling these table localities 
</blockquote></details>

Sorry - I'm not sure I know what you are referring to here.

I am trying to use the terminology used here: https://www.cockroachlabs.com/docs/stable/choosing-a-multi-region-configuration.html

But maybe I am missing something?
___
*[v21.1/multiregion-scale-application.md, line 72 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mcj7sJkBMBDw4a493My:-Mcnzc [...]

2021-06-22 18:12 UTC, rmloveland reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @awoods187, and @ericharmeling)

___
*[v21.1/multiregion-scale-application.md, line 24 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mco9XuZ0sBUY-II38Ic:-McopA21BoJFccTjjGmW:b9gor8v) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L24)):*
Not Andy (obv) but added my understanding below re:

> By "first step", do you mean before you have added any new nodes to your cluster (in new regions)?

I think the answer is "yes": if you (1) add a bunch of new nodes at time T without changing your multi-region config (really, constraints), the cluster will do a bunch of work rebalancing among those nodes based on CRDB's "default" set of constraints C in place at time T, and then when you (2) add a primary region at a later time T+1, yielding a new "narrower" set of constraints C', the cluster AGAIN has to do a bunch of work rebalancing etc. to meet the new constraint set C' which is now in place at time T+1.   The fact that the constraints started out "wide" and got "narrow" results in a lot of data movement etc.

By contrast, if you add a primary region first thing at time T when you have one node, the initial set of constraints is already "narrowed" significantly, so any new constraints you add at time T+1, ..., etc when you add a bunch of new nodes will be validated against the already existing "narrower" constraints and the data will go where you want it more quickly without so much rebalancing (since you avoided the wide constraint -> narrow constraint change described above)

Basically it's like a constraint propagation system that will be faster if you narrow the set of constraints as soon as possible during cluster setup and before adding more nodes, so it has a narrower range of things to consider (thus resulting in less churn / data movement / network traffic / etc)

At least this is my understanding of it
___
*[v21.1/multiregion-scale-application.md, line 68 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mcj7L5Y0ValW7Tw-b39:-McoshVyECWMiatlp10z:b-8o2606) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L68)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

Sorry - I'm not sure I know what you are referring to here.

I am trying to use the terminology used here: https://www.cockroachlabs.com/docs/stable/choosing-a-multi-region-configuration.html

But maybe I am missing something?
</blockquote></details>

the phrase we have been using for the `SET LOCALITY FOO ...` stuff is table localities

e.g. I might call this section "set table localities"

and in the paragraph below I might say something like "for most ... configurations ..., you do not need to update the default table localities"

a reason for this obliqueness is in keeping with the declarative nature of SQL and also the multi-region stuff in general: it's not like a statement in Python or or ALGOL or whatever where I say "set x=5", it's more like operating a constraint propagation system: "make this table regional in us-west-1", and then the r/w perf characteristics of the table's performance fall out of what CRDB does under the hood based on the constraints we have given it, depending on where the client is accessing the table from.  

So we are not really "upgrading" or "updating read/write operations" since what we are really doing is at arm's length: changing the "locality" constraint of the table and then CRDB does "Magic(tm)" to make it so that reads / writes from specific regions have certain characteristics.

Basically it's more fuzzy/declarative and less like a "regular" programming thing

I hope that makes sense - the core of actionable info is in the first 3 sentences above, the rest is my possibly unhelpful faux explication 


<!-- Sent from Reviewable.io -->

2021-06-23 15:15 UTC, awoods187 requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @awoods187, @ericharmeling, and @rmloveland)

___
*[v21.1/multiregion-scale-application.md, line 15 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mcj69DqDH6kGOLP0676:-MctQ9eZ-LP3aOsPy-PY:b-drlyk6) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L15)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> Im surprised to see this as one step.

Fair enough! I've split up the app and db deployment steps.

>  I think a more common pattern is to scale the app to multiple regions and then scale the db.

This doesn't make much sense to me. You configure which node to connect to when you deploy the application. If you scale your application first, and then you scale your database, you need to re-configure the application (and possibly even re-deploy it, depending on the orchestration tool) to connect to the closest db node after you have already deployed and configured the application once. 

> Scaling the db also has some nuances to the order in which you do things (like adding the primary region before adding nodes with localities in other regions)

So I think we might be talking about different things when we say "scaling the db" here. But maybe I'm misunderstanding what you're saying?

When I say "scale the database deployment", I just mean "add nodes to the cluster" (no multi-region syntax/schema changes included yet). After you add nodes with regional localities, then you can transform the schema for multi-region (i.e., use the multi-region syntax to add the database regions, etc.). I've made these two entirely separate steps, as one of the steps ("Scale database deployments") is about navigating orchestration tools/CockroachCloud to get a cluster deployed in multiple regions, and the other step ("Transform a single-region schema into a multi-region schema") is about executing schema changes in SQL.
</blockquote></details>

Well, it is a question of timing. You can actually get a lot of value out of deploying your app to multiple regions without deploying your db. You might do that for a few months before you go ahead and deploy your db (since it is so easy to do). With our new abstractions, it's also easy for the DB to deployed to multiple regions so you could choose to do it at the same time. However, as we will discuss below, you need to be careful how you do this. See this blog post for more details on app vs. db deployment https://www.cockroachlabs.com/blog/follower-reads/
___
*[v21.1/multiregion-scale-application.md, line 23 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mcj6fpeEeQWLdiFvIVq:-MctQdktC_4j5Stn3u5p:ba28pos) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L23)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

So I thought we might be talking about different things when we say "scale database deployments" (see my comment above), but now I'm not so sure.

I understand the workflow to be:

1. Scale database deployment (i.e., add nodes to the cluster with regional localities)
2. Scale application deployment (e.g., deploy Docker images in new regions, with configurations to connect to the closest db node)
3. Execute multi-region DDL statements (i.e., `ALTER DATABASE ... ADD PRIMARY REGION`, `ALTER DATABASE ... ADD REGION`, etc)
4. Update application, if necessary

It seems to me that you are suggesting the following workflow (but I could totally be misinterpreting what you are saying):

1. Scale the application (e.g., deploy Docker images in new regions, with configurations to connect to the *same*, single-region db node)
2. Execute a single `ALTER DATABASE ... ADD PRIMARY REGION` statement on a single-region CDB cluster
3. Scale the database deployment (i.e., add nodes to the cluster with regional localities)
4. Execute the rest of the multi-region DDL statements (`ALTER DATABASE ... ADD REGION`, etc.)
5. Update each application configuration to connect to the closest db node (e.g., update Docker images with new connection strings, and then re-deploy the images)
6. Update application, if necessary.

Is that correct?
</blockquote></details>

Yes, that is what I'm describing. Particualrly, you can also wait between 1 and 2 until your app needs it. If we want to do it all together, which I think does make sense, you could also do it this way:

Execute a single ALTER DATABASE ... ADD PRIMARY REGION statement on a single-region CDB cluster
Scale the database deployment (i.e., add nodes to the cluster with regional localities)
Execute the rest of the multi-region DDL statements (ALTER DATABASE ... ADD REGION, etc.)
Scale the application (e.g., deploy Docker images in new regions) and Update each application configuration to connect to the closest db node (e.g., update Docker images with new connection strings, and then re-deploy the images)
Update application, if necessary.

It may also be worth discussing how load balancing works. You could potentially deploy the app in multiple regions and have it talk to one load balancer that talks to one db node. Then you could do the load balancer in multiple regions talking to the db in multiple regions.
___
*[v21.1/multiregion-scale-application.md, line 24 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mco9XuZ0sBUY-II38Ic:-MctPnc44AhAwIS9mUMf:b-a6kf81) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L24)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Not Andy (obv) but added my understanding below re:

> By "first step", do you mean before you have added any new nodes to your cluster (in new regions)?

I think the answer is "yes": if you (1) add a bunch of new nodes at time T without changing your multi-region config (really, constraints), the cluster will do a bunch of work rebalancing among those nodes based on CRDB's "default" set of constraints C in place at time T, and then when you (2) add a primary region at a later time T+1, yielding a new "narrower" set of constraints C', the cluster AGAIN has to do a bunch of work rebalancing etc. to meet the new constraint set C' which is now in place at time T+1.   The fact that the constraints started out "wide" and got "narrow" results in a lot of data movement etc.

By contrast, if you add a primary region first thing at time T when you have one node, the initial set of constraints is already "narrowed" significantly, so any new constraints you add at time T+1, ..., etc when you add a bunch of new nodes will be validated against the already existing "narrower" constraints and the data will go where you want it more quickly without so much rebalancing (since you avoided the wide constraint -> narrow constraint change described above)

Basically it's like a constraint propagation system that will be faster if you narrow the set of constraints as soon as possible during cluster setup and before adding more nodes, so it has a narrower range of things to consider (thus resulting in less churn / data movement / network traffic / etc)

At least this is my understanding of it
</blockquote></details>

Good explanation Rich! That's exactly what I meant. 
___
*[v21.1/multiregion-scale-application.md, line 68 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mcj7L5Y0ValW7Tw-b39:-MctQ0gu39AxU-12Lvh-:b-ff6jdg) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L68)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

the phrase we have been using for the ` [...]

2021-06-23 16:48 UTC, ericharmeling commented
@awoods187 @rmloveland

Thank you both for the detailed responses! I'll work in your feedback as soon as I can.

2021-06-30 15:16 UTC, ericharmeling reviewed
TFTR @awoods187, @rmloveland 

I've updated the PR, and left some additional comments, after going over your feedback. PTAL at the changes and my new comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10796#-:-MdO9W-6D-ePGaEU_llz:b-sf7ej1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @awoods187, and @rmloveland)

___
*[v21.1/multiregion-scale-application.md, line 15 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mcj69DqDH6kGOLP0676:-MdMxQR94De8HUjzDDLQ:b6qk19m) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L15)):*
> You can actually get a lot of value out of deploying your app to multiple regions without deploying your db. 

Great point. I've added a note about the latency benefits of deploying the app in multiple regions, even if you stay with a single-region db. I also added a link to the relevant section of the blog post.
___
*[v21.1/multiregion-scale-application.md, line 23 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mcj6fpeEeQWLdiFvIVq:-MdJ3XKr37Y8B60PyqSq:byk6oev) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L23)):*
> If we want to do it all together, which I think does make sense, you could also do it this way: 
> Execute a single ALTER DATABASE ... ADD PRIMARY REGION statement on a single-region CDB cluster
> Scale the database deployment (i.e., add nodes to the cluster with regional localities)
> Execute the rest of the multi-region DDL statements (ALTER DATABASE ... ADD REGION, etc.)
> Scale the application (e.g., deploy Docker images in new regions) and Update each application configuration to connect to the closest db node (e.g., update Docker images with new connection strings, and then re-deploy the images)
> Update application, if necessary.

Okay - I think it will be easier to parse if we place the steps in two separate sections, with the order that you suggested here. We can then add a note to suggest a more flexible application deployment approach, and point to the blog post (as I mentioned in the comment thread above this one).
___
*[v21.1/multiregion-scale-application.md, line 24 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mco9XuZ0sBUY-II38Ic:-MdMlpRW6Oq7ZbbSbbJ1:b2ohd73) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L24)):*
<details><summary><i>Previously, awoods187 (Andy Woods) wrote…</i></summary><blockquote>

Good explanation Rich! That's exactly what I meant. 
</blockquote></details>

Thank you, Rich! Makes total sense. I've tried to summarize these performance implications in as clear and simple terms as I can.

I do have some thoughts on this though (or really, I just want to point some stuff out).

1. AFAICT, we don't currently explicitly document the performance implications of executing all multi-region DDL statements after adding new nodes (please correct me if I'm wrong!). I'm happy to make this page the first place where we do - but we should probably also update some of the existing reference docs (https://www.cockroachlabs.com/docs/v21.1/set-primary-region.html and https://www.cockroachlabs.com/docs/v21.1/multiregion-overview.html, in particular) to include a bit about the performance costs of adding nodes before setting the database(s)'s primary region.
2. The [multi-region tutorial](https://www.cockroachlabs.com/docs/stable/demo-low-latency-multi-region-deployment.html) does not demonstrate a proper "scaling" workflow. (And neither does the [scaling implementation in the python movr workload](https://github.com/cockroachdb/movr/blob/master/movr.py#L258)). The cluster in that tutorial starts as multi-region, so all the DDL is run back-to-back. I understand that scaling performance isn't really the purpose of the tutorial (it's more about comparing the performance with and without multi-region features), but I wonder if we want to create a tutorial, akin to the current multi-region tutorial, about scaling nodes *and* transforming the schema to use multi-region.
3. To set the database primary region when the cluster is single-region, you need to have set regional node localities for the nodes in the single-region cluster from the very beginning. UUIC, there is no way to add/change the locality of a node after it has been started, without shutting the node down and starting it up again (this something I brought up to Rich a while back). IDK if there is a technical reason for this, but IMO it greatly limits the ability of a single-region cluster to scale. A naive approach to resolving this would be to just make `--locality` a required flag. Something for engineering to consider.
___
*[v21.1/multiregion-scale-application.md, line 68 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mcj7L5Y0ValW7Tw-b39:-MdMx7CuDkz_dq-uGezS:b-52bdhp) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L68)):*
>e.g. I might call this section "set table localities"

Maybe I'm misunderstanding what y'all are referring to, but this section isn't about setting localities. It's about changing your application code so that it works with the new multi-region database schema. It's not about changing the database schema; it's about changing the persistence layer functions in the code itself (i.e., the DML SQL statements) *after* the database schema has already been changed.

The lead-in sentence here acknowledges that you likely won't need to change anything if you have the default table localities.

> For most multi-region configurations, including the default configuration (`LOCALITY REGIONAL BY TABLE IN PRIMARY REGION` and `SURVIVE ZONE FAILURE`), you do not need to update any client-side read/write operations after migrating your database schema for multi-region features. CockroachDB automatically optimizes queries against multi-region databases, based on the locality of the node executing the query, and on the multi-region configuration of the database.

Perhaps the language I am using here is confusing. I've updated the language to be a little more explicit than just "client read/write operations". I also changed the "multi-region configuration" terminology to just focus on table localities.


<!-- Sent from Reviewable.io -->

2021-07-01 15:16 UTC, rmloveland reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @awoods187, and @ericharmeling)

___
*[v21.1/multiregion-scale-application.md, line 24 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mco9XuZ0sBUY-II38Ic:-MdXcx3J90sVgAJPBk03:b7rpxl5) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L24)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

Thank you, Rich! Makes total sense. I've tried to summarize these performance implications in as clear and simple terms as I can.

I do have some thoughts on this though (or really, I just want to point some stuff out).

1. AFAICT, we don't currently explicitly document the performance implications of executing all multi-region DDL statements after adding new nodes (please correct me if I'm wrong!). I'm happy to make this page the first place where we do - but we should probably also update some of the existing reference docs (https://www.cockroachlabs.com/docs/v21.1/set-primary-region.html and https://www.cockroachlabs.com/docs/v21.1/multiregion-overview.html, in particular) to include a bit about the performance costs of adding nodes before setting the database(s)'s primary region.
2. The [multi-region tutorial](https://www.cockroachlabs.com/docs/stable/demo-low-latency-multi-region-deployment.html) does not demonstrate a proper "scaling" workflow. (And neither does the [scaling implementation in the python movr workload](https://github.com/cockroachdb/movr/blob/master/movr.py#L258)). The cluster in that tutorial starts as multi-region, so all the DDL is run back-to-back. I understand that scaling performance isn't really the purpose of the tutorial (it's more about comparing the performance with and without multi-region features), but I wonder if we want to create a tutorial, akin to the current multi-region tutorial, about scaling nodes *and* transforming the schema to use multi-region.
3. To set the database primary region when the cluster is single-region, you need to have set regional node localities for the nodes in the single-region cluster from the very beginning. UUIC, there is no way to add/change the locality of a node after it has been started, without shutting the node down and starting it up again (this something I brought up to Rich a while back). IDK if there is a technical reason for this, but IMO it greatly limits the ability of a single-region cluster to scale. A naive approach to resolving this would be to just make `--locality` a required flag. Something for engineering to consider.
</blockquote></details>

Thanks for this valuable feedback Eric!

Re point 1 I filed #10867 

Re point 2, filed #10868 
  
___
*[v21.1/multiregion-scale-application.md, line 68 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mcj7L5Y0ValW7Tw-b39:-Mcovu3C6KIL4jiDhuY2:b2exyam) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L68)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

the phrase we have been using for the `SET LOCALITY FOO ...` stuff is table localities

e.g. I might call this section "set table localities"

and in the paragraph below I might say something like "for most ... configurations ..., you do not need to update the default table localities"

a reason for this obliqueness is in keeping with the declarative nature of SQL and also the multi-region stuff in general: it's not like a statement in Python or or ALGOL or whatever where I say "set x=5", it's more like operating a constraint propagation system: "make this table regional in us-west-1", and then the r/w perf characteristics of the table's performance fall out of what CRDB does under the hood based on the constraints we have given it, depending on where the client is accessing the table from.  

So we are not really "upgrading" or "updating read/write operations" since what we are really doing is at arm's length: changing the "locality" constraint of the table and then CRDB does "Magic(tm)" to make it so that reads / writes from specific regions have certain characteristics.

Basically it's more fuzzy/declarative and less like a "regular" programming thing

I hope that makes sense - the core of actionable info is in the first 3 sentences above, the rest is my possibly unhelpful faux explication 
</blockquote></details>

PS if you have feedback on how we could improve the page you linked above 


<!-- Sent from Reviewable.io -->

2021-07-14 01:32 UTC, awoods187 reviewed
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @awoods187, and @ericharmeling)

___
*[v21.1/multiregion-scale-application.md, line 23 at r1](https://reviewable.io/reviews/cockroachdb/docs/10796#-Mcj6fpeEeQWLdiFvIVq:-MeXcZGZ-It2HZ5i4gKH:bb73djm) ([raw file](https://github.com/cockroachdb/docs/blob/764f31374ebf1fd24550072d60b83bafbdf6d3d0/v21.1/multiregion-scale-application.md#L23)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> If we want to do it all together, which I think does make sense, you could also do it this way: 
> Execute a single ALTER DATABASE ... ADD PRIMARY REGION statement on a single-region CDB cluster
> Scale the database deployment (i.e., add nodes to the cluster with regional localities)
> Execute the rest of the multi-region DDL statements (ALTER DATABASE ... ADD REGION, etc.)
> Scale the application (e.g., deploy Docker images in new regions) and Update each application configuration to connect to the closest db node (e.g., update Docker images with new connection strings, and then re-deploy the images)
> Update application, if necessary.

Okay - I think it will be easier to parse if we place the steps in two separate sections, with the order that you suggested here. We can then add a note to suggest a more flexible application deployment approach, and point to the blog post (as I mentioned in the comment thread above this one).
</blockquote></details>

SGTM


<!-- Sent from Reviewable.io -->

2021-07-19 14:48 UTC, ericharmeling commented
@awoods187 @rmloveland 

Everything looking good from your points of view?

@ajstorm 

When you get a chance, it would be nice to have an engineering review on this PR as well. :)

2021-07-20 18:12 UTC, rmloveland approved these changes
lgtm yo

2021-07-26 12:32 UTC, ericharmeling commented
@ajstorm Friendly ping on review :)

2021-07-26 13:00 UTC, ajstorm requested changes
Sorry for the delay.  Looks good overall.  Just a few comments (mostly focused on manually creating the enum).

> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10796#-:-MfXtknpBQFNUyH22UaN:bjgtsrz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187 and @ericharmeling)

___
*[v21.1/multiregion-scale-application.md, line 3 at r3](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfXnyp61BJZQuSGaUNo:-MfXnyp61BJZQuSGaUNp:b-l1ubxl) ([raw file](https://github.com/cockroachdb/docs/blob/f0e8a60339a47b2aac68282019c9ffdc1d8f7400/v21.1/multiregion-scale-application.md#L3)):*
> ```Markdown
> ---
> title: Scale to Multiple Regions
> summary: Learn how to scale a single-region application to a multi-region application.
> ```

Nit: This one is very much up to you, but this sentence might read a bit better if we ended it with "...application to multiple regions." so that it matches the title.
___
*[v21.1/multiregion-scale-application.md, line 7 at r3](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfXoH97CAOmA5PiaZbA:-MfXoH97CAOmA5PiaZbB:b-rmrlqo) ([raw file](https://github.com/cockroachdb/docs/blob/f0e8a60339a47b2aac68282019c9ffdc1d8f7400/v21.1/multiregion-scale-application.md#L7)):*
> ```Markdown
> ---
> 
> This page provides guidance for scaling a single-region application to a multi-region application.
> ```

Nit: if we're going to change things above, we should also change them here.
___
*[v21.1/multiregion-scale-application.md, line 15 at r3](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfXoROf310m746jpfEA:-MfXoROf310m746jpfEB:b5jhk5t) ([raw file](https://github.com/cockroachdb/docs/blob/f0e8a60339a47b2aac68282019c9ffdc1d8f7400/v21.1/multiregion-scale-application.md#L15)):*
> ```Markdown
> Scaling an application from a single region to multiple regions consists of:
> 
> - [Scaling the database](#scale-the-database), which includes transforming the database schema into a multi-region schema and adding new nodes to a CockroachDB cluster.
> ```

Nit: We might want to be more explicit here.  "...which includes adding new nodes to a CockroachDB cluster in different regions (if not present already), adding regions to the database, and optionally transforming the database schema to leverage multi-region table localities."
___
*[v21.1/multiregion-scale-application.md, line 17 at r3](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfXpaa82Ay1C0CXhpqJ:-MfXpaa82Ay1C0CXhpqK:bu1aiz4) ([raw file](https://github.com/cockroachdb/docs/blob/f0e8a60339a47b2aac68282019c9ffdc1d8f7400/v21.1/multiregion-scale-application.md#L17)):*
> ```Markdown
> - [Scaling the database](#scale-the-database), which includes transforming the database schema into a multi-region schema and adding new nodes to a CockroachDB cluster.
> 
> - [Scaling the application](#scale-the-application), which includes deploying the application in new regions and, if necessary, updating the application code to work with the multi-region database schema.
> ```

Nit: I'd think we'd want to add "optionally" right before "updating the application code".  In most cases, no application code changes should be required.
___
*[v21.1/multiregion-scale-application.md, line 23 at r3](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfXprLn9zef_Ky7FqpS:-MfXprLn9zef_Ky7FqpT:b-lxd6x8) ([raw file](https://github.com/cockroachdb/docs/blob/f0e8a60339a47b2aac68282019c9ffdc1d8f7400/v21.1/multiregion-scale-application.md#L23)):*
> ```Markdown
> To scale a database from a single region to multiple regions:
> 
> 1. Use an [`ALTER DATABASE ... SET PRIMARY REGION`](set-primary-region.html) statement to set the database's [primary region](multiregion-overview.html#database-regions) to the single region in which the cluster is deployed. This region must have been specified as a [regional locality](cockroach-start.html#locality) at cluster startup.
> ```

Why "single region" here?  I'd think that we could change this to "one of the regions in which the cluster is deployed".  Then, the comment below about "setting the primary database region before", can call out the benefits to doing this before adding new regions.

After reading the discussion below, I agree about it's importance, but we might want to provide a bit more context up here, or change the wording slightly.  I could see this occurring in a few steps:

1) Prep the database (by adding the primary region)
2) Scale the cluster
3) Scale the database
4) Scale the application
___
*[v21.1/multiregion-scale-application.md, line 25 at r3](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfXq5sk43cwq6-U0tlt:-MfXq5sk43cwq6-U0tlu:b439kua) ([raw file](https://github.com/cockroachdb/docs/blob/f0e8a60339a47b2aac68282019c9ffdc1d8f7400/v21.1/multiregion-scale-application.md#L25)):*
> ```Markdown
> 1. Use an [`ALTER DATABASE ... SET PRIMARY REGION`](set-primary-region.html) statement to set the database's [primary region](multiregion-overview.html#database-regions) to the single region in which the cluster is deployed. This region must have been specified as a [regional locality](cockroach-start.html#locality) at cluster startup.
> 
>     Setting the primary database region before adding new regional nodes to the cluster prevents CockroachDB from [rebalancing row replications](architecture/replication-layer.html#leaseholder-rebalancing) across all regions each time a node is added in a new region.
> ```

Nit: I'd drop "database" in "primary database region".
___
*[v21.1/multiregion-scale-application.md, line 44 at r3](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfXrftl9oYXtmmy3gk3:-MfXrftl9oYXtmmy3gk4:b30k0ve) ([raw file](https://github.com/cockroachdb/docs/blob/f0e8a60339a47b2aac68282019c9ffdc1d8f7400/v21.1/multiregion-scale-application.md#L44)):*
> ```Markdown
> 
>     {{site.data.alerts.callout_info}}
>     You must specify a [regional locality](cockroach-start.html#locality) for each node at startup. These regional localities are represented as [cluster regions](multiregion-overview.html#cluster-regions) in the cluster.
> ```

Nit: "You" is only relevant here for orchestrated and manual deployments, right?  CC will set these localities automatically.
___
*[v21.1/multiregion-scale-application.md, line 49 at r3](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfXrxxUCaqsX7kzzHWs:-MfXrxxUCaqsX7kzzHWt:b-4vs3mh) ([raw file](https://github.com/cockroachdb/docs/blob/f0e8a60339a47b2aac68282019c9ffdc1d8f7400/v21.1/multiregion-scale-application.md#L49)):*
> ```Markdown
> 1. Use an [`ALTER DATABASE ... ADD REGIONS`](add-region.html) statement to add the new regions to your database. Only cluster regions (i.e., regional localities specified at cluster startup) can be added as [database regions](multiregion-overview.html#database-regions).
> 
> 1. Use [`ALTER DATABASE ... SURVIVE ... FAILURE`](survive-failure.html) statements to set your database's [survival goals](multiregion-overview.html#survival-goals).
> ```

Nit: optionally...
___
*[v21.1/multiregion-scale-application.md, line 51 at r3](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfXs0R361NvppjzuPtD:-MfXs0R361NvppjzuPtE:b9zasfb) ([raw file](https://github.com/cockroachdb/docs/blob/f0e8a60339a47b2aac68282019c9ffdc1d8f7400/v21.1/multiregion-scale-application.md#L51)):*
> ```Markdown
> 1. Use [`ALTER DATABASE ... SURVIVE ... FAILURE`](survive-failure.html) statements to set your database's [survival goals](multiregion-overview.html#survival-goals).
> 
> 1. Use [`ALTER TABLE ... SET LOCALITY`](set-locality.html) statements to set [table localities](multiregion-overview.html#table-locality) for each table.
> ```

Nit: optionally
___
*[v21.1/multiregion-scale-application.md, line 86 at r3](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfXsWaN4wuf4PhzqgsR:-MfXsWaN4wuf4PhzqgsS:brf2dy8) ([raw file](https://github.com/cockroachdb/docs/blob/f0e8a60339a47b2aac68282019c9ffdc1d8f7400/v21.1/multiregion-scale-application.md#L86)):*
 [...]

2021-07-26 19:16 UTC, ericharmeling reviewed
@ajstorm 

No worries re: the delay. Thanks for reviewing this and giving really great feedback!

I updated the page after going through your review. Please see my comments below re: the enum. (spoiler: I rewrote that whole section.)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10796#-:-MfY1DKY7DxExoGXrmVo:b-r3juhn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @awoods187)

___
*[v21.1/multiregion-scale-application.md, line 3 at r3](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfXnyp61BJZQuSGaUNo:-MfY042R6bNIUwvPw_2P:btvpuu7) ([raw file](https://github.com/cockroachdb/docs/blob/f0e8a60339a47b2aac68282019c9ffdc1d8f7400/v21.1/multiregion-scale-application.md#L3)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: This one is very much up to you, but this sentence might read a bit better if we ended it with "...application to multiple regions." so that it matches the title.
</blockquote></details>

Good shout. Done.
___
*[v21.1/multiregion-scale-application.md, line 7 at r3](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfXoH97CAOmA5PiaZbA:-MfY0Oxw2udC65ltVz7V:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f0e8a60339a47b2aac68282019c9ffdc1d8f7400/v21.1/multiregion-scale-application.md#L7)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: if we're going to change things above, we should also change them here.
</blockquote></details>

Done.
___
*[v21.1/multiregion-scale-application.md, line 15 at r3](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfXoROf310m746jpfEA:-MfY0Thf1pZ7BYIHCD7G:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f0e8a60339a47b2aac68282019c9ffdc1d8f7400/v21.1/multiregion-scale-application.md#L15)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: We might want to be more explicit here.  "...which includes adding new nodes to a CockroachDB cluster in different regions (if not present already), adding regions to the database, and optionally transforming the database schema to leverage multi-region table localities."
</blockquote></details>

Done.
___
*[v21.1/multiregion-scale-application.md, line 17 at r3](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfXpaa82Ay1C0CXhpqJ:-MfY0gC550mrEkTQU9RG:b-9oozx2) ([raw file](https://github.com/cockroachdb/docs/blob/f0e8a60339a47b2aac68282019c9ffdc1d8f7400/v21.1/multiregion-scale-application.md#L17)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: I'd think we'd want to add "optionally" right before "updating the application code".  In most cases, no application code changes should be required.
</blockquote></details>

I think this is covered by the "if necessary" parenthetical. Later on, there is a sentence that calls out that the application won't usually need updating. Also, I've added "Optional" to that dedicated "Update the application code" section header below.
___
*[v21.1/multiregion-scale-application.md, line 23 at r3](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfXprLn9zef_Ky7FqpS:-MfY34kTEN8xlkBmJ_a0:bs65bif) ([raw file](https://github.com/cockroachdb/docs/blob/f0e8a60339a47b2aac68282019c9ffdc1d8f7400/v21.1/multiregion-scale-application.md#L23)):*
> Why "single region" here? I'd think that we could change this to "one of the regions in which the cluster is deployed". 

The assumption is that the cluster is single-region at this point (these are the steps to scale to multiple regions, from a single region). Your suggestion still holds though and would cover more cases (single region to multiple regions, multiple regions to more regions). Updated.

>Prep the database (by adding the primary region)
Scale the cluster
Scale the database
Scale the application

Thanks for the suggestion! Incorporated this into some section-restructuring changes.
___
*[v21.1/multiregion-scale-application.md, line 25 at r3](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfXq5sk43cwq6-U0tlt:-MfY1BnSDEwgk7AvKO73:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f0e8a60339a47b2aac68282019c9ffdc1d8f7400/v21.1/multiregion-scale-application.md#L25)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: I'd drop "database" in "primary database region".
</blockquote></details>

Done.
___
*[v21.1/multiregion-scale-application.md, line 44 at r3](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfXrftl9oYXtmmy3gk3:-MfY1U6SDGMH3zdp6NQr:b-ageg3o) ([raw file](https://github.com/cockroachdb/docs/blob/f0e8a60339a47b2aac68282019c9ffdc1d8f7400/v21.1/multiregion-scale-application.md#L44)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: "You" is only relevant here for orchestrated and manual deployments, right?  CC will set these localities automatically.
</blockquote></details>

Added "For orchestrated and manual deployments," to the beginning of that note.
___
*[v21.1/multiregion-scale-application.md, line 49 at r3](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfXrxxUCaqsX7kzzHWs:-MfY22fa0NvUlwv0MIX4:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f0e8a60339a47b2aac68282019c9ffdc1d8f7400/v21.1/multiregion-scale-application.md#L49)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: optionally...
</blockquote></details>

Done.
___
*[v21.1/multiregion-scale-application.md, line 51 at r3](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfXs0R361NvppjzuPtD:-MfY23UnD1JNhROju7PY:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f0e8a60339a47b2aac68282019c9ffdc1d8f7400/v21.1/multiregion-scale-application.md#L51)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: optionally
</blockquote></details>

Done.
___
*[v21.1/multiregion-scale-application.md, line 86 at r3](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfXsWaN4wuf4PhzqgsR:-MfY9HpW-w8aI4JYT0R8:bkm6vy5) ([raw file](https://github.com/cockroachdb/docs/blob/f0e8a60339a47b2aac68282019c9ffdc1d8f7400/v21.1/multiregion-scale-application.md#L86)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

You can't create this type manually.  The database will do it for you automatically as new regions are added.  If you create it manually, bad stuff is going to happen.
</blockquote></details>

This section is about creating a representation of the existing `crdb_region` type in the ORM, and not about creating the type and persisting it to the database. The guidance here is really only relevant if you need to reference `crdb_region` in a DML statement, and your ORM has no way of dynamically updating the mappings to the database schema, which I thought was the case but it turned out not to be. :)

I had to rewrite this after reading your feedback and doing a little more testing. It should be clearer now.
___
*[v21.1/multiregion-scale-application.md, line 87 at r3](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfXslnc9Ow_GlMFIhdt:-MfY6qIpAc10MqeKIfp3:bt2okd3) ([raw file](https://github.com/cockroachdb/docs/blob/f0e8a60339a47b2aac68282019c9ffdc1d8f7400/v21.1/multiregion-scale-application.md#L87)):*
>This column will be persisted. 

IIUC, SQLAlchemy does not persist ORM mappings to the database unless you are hooked up to a schema migration tool that automatically executes DDL statements on behalf of the application. SQLAlchemy [does not have schema manipulation capabilities](https://docs.sqlalchemy.org/en/14/core/metadata.html#altering-database-objects-through-migrations) (e.g., you can't add a column to an existing table with SQLAlchemy alone). This limitation certainly influenced [my own multi-region scaling efforts](https://github.com/cockroachdb/movr/blob/master/movr.py#L258).

For other ORMs, this might n [...]

2021-07-26 20:00 UTC, ajstorm approved these changes
Thanks for addressing the comments.  <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10796#-:-MfZOg9C8a0bloiIYrkI:bvyk976)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @awoods187 and @ericharmeling)

___
*[v21.1/multiregion-scale-application.md, line 17 at r3](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfXpaa82Ay1C0CXhpqJ:-MfZMh7QCLoYP0L-fo9L:b-8n327p) ([raw file](https://github.com/cockroachdb/docs/blob/f0e8a60339a47b2aac68282019c9ffdc1d8f7400/v21.1/multiregion-scale-application.md#L17)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

I think this is covered by the "if necessary" parenthetical. Later on, there is a sentence that calls out that the application won't usually need updating. Also, I've added "Optional" to that dedicated "Update the application code" section header below.
</blockquote></details>

Yes, good point.
___
*[v21.1/multiregion-scale-application.md, line 23 at r3](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfXprLn9zef_Ky7FqpS:-MfZNUur-bepeNDp0yAl:b9bkkpe) ([raw file](https://github.com/cockroachdb/docs/blob/f0e8a60339a47b2aac68282019c9ffdc1d8f7400/v21.1/multiregion-scale-application.md#L23)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> Why "single region" here? I'd think that we could change this to "one of the regions in which the cluster is deployed". 

The assumption is that the cluster is single-region at this point (these are the steps to scale to multiple regions, from a single region). Your suggestion still holds though and would cover more cases (single region to multiple regions, multiple regions to more regions). Updated.

>Prep the database (by adding the primary region)
Scale the cluster
Scale the database
Scale the application

Thanks for the suggestion! Incorporated this into some section-restructuring changes.
</blockquote></details>

Looks great.
___
*[v21.1/multiregion-scale-application.md, line 86 at r3](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfXsWaN4wuf4PhzqgsR:-MfZO0eI317l5bQZuyQs:b-19z96f) ([raw file](https://github.com/cockroachdb/docs/blob/f0e8a60339a47b2aac68282019c9ffdc1d8f7400/v21.1/multiregion-scale-application.md#L86)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

This section is about creating a representation of the existing `crdb_region` type in the ORM, and not about creating the type and persisting it to the database. The guidance here is really only relevant if you need to reference `crdb_region` in a DML statement, and your ORM has no way of dynamically updating the mappings to the database schema, which I thought was the case but it turned out not to be. :)

I had to rewrite this after reading your feedback and doing a little more testing. It should be clearer now.
</blockquote></details>

This look much better.  Thanks!
___
*[v21.1/multiregion-scale-application.md, line 100 at r3](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfXtBDsEqb4lWF9ahyB:-MfZOS9LBTlnH8mk6LnD:blbulw7) ([raw file](https://github.com/cockroachdb/docs/blob/f0e8a60339a47b2aac68282019c9ffdc1d8f7400/v21.1/multiregion-scale-application.md#L100)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

Again, this is meant just to reflect the column in the database.
</blockquote></details>

Looks better now.
___
*[v21.1/multiregion-scale-application.md, line 117 at r3](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfXtOIp0t80njAncsx0:-MfZOXDB-J-FhVjp1rSN:b-dbab0j) ([raw file](https://github.com/cockroachdb/docs/blob/f0e8a60339a47b2aac68282019c9ffdc1d8f7400/v21.1/multiregion-scale-application.md#L117)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

>You should be able to reference this column automatically

I think that is the intention of this guidance. We aren't creating the column, we are just referencing it from the ORM.

If by "reference this column automatically" you are saying that you should be able to use the ORM libraries to update the local representation of the database columns dynamically, then you are describing the ideal situation (i.e., a dynamic sync from database to ORM). 

TBH, in my own local environment, I couldn't get this to work with SQLAlchemy (using [`reflect(extend_existing=True, autoload_replace=True)`](https://docs.sqlalchemy.org/en/14/core/metadata.html#sqlalchemy.schema.MetaData.reflect)) at first. Other ORMs surely have this kind of capability as well (even if they don't support an ORM to database sync, like SQLAlchemy).

However! I wasn't considering what effect the hidden column was having on the sync, and I didn't see https://github.com/cockroachdb/cockroach/pull/63052 (which has yet to be documented). After running `ALTER TABLE ... ALTER COLUMN ... SET VISIBLE`, the sync worked! 

So... I've updated the guidance here to include running this statement, and not creating a new column/type on the app side at all, but instead just loading the schema onto the mapping.
</blockquote></details>

All good.  Thanks for taking a second look.
___
*[v21.1/multiregion-scale-application.md, line 21 at r4](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfZMwfQ2zKj3q5ToZsj:-MfZMwfQ2zKj3q5ToZsk:bwx03xq) ([raw file](https://github.com/cockroachdb/docs/blob/8d6e4d466de5b50763625e987f77868d660883a5/v21.1/multiregion-scale-application.md#L21)):*
> ```Markdown
> ## Scale the database
> 
> ### Step 1. Prep the database schema
> ```

Nit: I'd remove schema here.  We're not really modifying the database's schema at this point.  Well, to be fair, it depends on what you consider a schema to be, but I'd think we'd be find removing schema.


<!-- Sent from Reviewable.io -->

2021-07-27 13:21 UTC, ericharmeling reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10796)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @awoods187)

___
*[v21.1/multiregion-scale-application.md, line 21 at r4](https://reviewable.io/reviews/cockroachdb/docs/10796#-MfZMwfQ2zKj3q5ToZsj:-Mfc6xQp6uyO6Cn-ikWD:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/8d6e4d466de5b50763625e987f77868d660883a5/v21.1/multiregion-scale-application.md#L21)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: I'd remove schema here.  We're not really modifying the database's schema at this point.  Well, to be fair, it depends on what you consider a schema to be, but I'd think we'd be find removing schema.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-27 14:18 UTC, merged