Misc 21.1.1 CLI updates
cockroachdb/docs pull request #10805
Opened 2021-06-21 19:26 UTC by ericharmeling

Fixes https://github.com/cockroachdb/docs/issues/10661.
Fixes https://github.com/cockroachdb/docs/issues/10660.
Fixes https://github.com/cockroachdb/docs/issues/10659.
Fixes https://github.com/cockroachdb/docs/issues/10658.
Fixes https://github.com/cockroachdb/docs/issues/9142.
Fixes https://github.com/cockroachdb/docs/issues/9143.
Fixes https://github.com/cockroachdb/docs/issues/9131.

2021-06-21 19:27 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/10805)
<!-- Reviewable:end -->

2021-06-22 08:55 UTC, knz approved these changes
> Reviewed 26 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10805)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)



<!-- Sent from Reviewable.io -->

2021-06-22 11:16 UTC, ericharmeling commented
TFTR @knz !

2021-06-29 20:42 UTC, mikeCRL requested changes
Just one question that pertains to all the instances of `<br><br>`.

2021-06-29 20:42 UTC, mikeCRL commented on _includes/v21.1/sql/connection-parameters.md
> +`--port`<br><br>`-p` | The server port to connect to. Note: The port number can also be specified via `--host`. <br><br>**Env Variable:** `COCKROACH_PORT`<br>**Default:** `26257`
Why the extra line break? I think it looks good as-is on the live site. The meaning (that they're alternates/synonyms) is clear to me.

2021-06-30 15:23 UTC, ericharmeling reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10805)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mikeCRL)

___
*[_includes/v21.1/sql/connection-parameters.md, line 4 at r1](https://reviewable.io/reviews/cockroachdb/docs/10805#-Mck1_9_9OEQBHP_fClo-r1-4:-MdSUpWj6c-8LKOVoj8h:brb3inw) ([raw file](https://github.com/cockroachdb/docs/blob/037f3662a7543264a35f91a2ad76ab7f0bcf099c/_includes/v21.1/sql/connection-parameters.md#L4)):*
<details><summary><i>Previously, mikeCRL (Mike Lewis) wrote…</i></summary><blockquote>

Why the extra line break? I think it looks good as-is on the live site. The meaning (that they're alternates/synonyms) is clear to me.
</blockquote></details>

I noticed that a single line break makes the options difficult to parse if one of the options runs on to the next line (the formatting makes it look like there is an additional option). Having double spaces accommodates this case, but it looks a bit odd if just one or two of the columns with multiple options have the double line break. So I tried to update all of these to be consistent.

This could for sure be a style discussion for reference tables with multiple items with the same description.


<!-- Sent from Reviewable.io -->

2021-06-30 17:53 UTC, merged