REASSIGN OWNED
cockroachdb/docs pull request #11014
Opened 2021-08-05 19:48 UTC by ericharmeling

Fixes https://github.com/cockroachdb/docs/issues/10862.

2021-08-05 19:48 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/11014)
<!-- Reviewable:end -->

2021-08-05 19:53 UTC, ericharmeling commented
@fabiog1901 FYI

2021-08-05 22:02 UTC, RichardJCai requested changes
Mostly looks good to me, there's a missing privilege check on this that I'll make a PR shortly to fix.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11014#-:-MgNKh5X0xI8QtJk1Krs:b7qah3v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[v21.1/reassign-owned.md, line 15 at r1](https://reviewable.io/reviews/cockroachdb/docs/11014#-MgNK4Pi68Lcid-69dNm:-MgNK4Pi68Lcid-69dNn:bwo0vfi) ([raw file](https://github.com/cockroachdb/docs/blob/f6479e7efc7134e0a3b70393f86f1eab25e48009/v21.1/reassign-owned.md#L15)):*
> ```Markdown
> ## Required privileges
> 
> - To change the owner of objects in a database owned by a specific role or user, the user executing the command must be a member of the [`admin` role](authorization.html#admin-role).
> ```

The user executing the command doesn't have to be a member of the admin role but must be a member of the `old` and `new` role.

See: 
https://www.postgresql.org/docs/current/sql-reassign-owned.html

Right now we actually don't have any privilege checks which is a bug I'm gonna make a PR right now to fix it.
___
*[v21.1/reassign-owned.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/11014#-MgNKLGV88gYqSoq6yig:-MgNKLGV88gYqSoq6yih:b-zfhrsi) ([raw file](https://github.com/cockroachdb/docs/blob/f6479e7efc7134e0a3b70393f86f1eab25e48009/v21.1/reassign-owned.md#L16)):*
> ```Markdown
> 
> - To change the owner of objects in a database owned by a specific role or user, the user executing the command must be a member of the [`admin` role](authorization.html#admin-role).
> - The target role (i.e., the desired role of the objects) must have the `CREATE` [privilege](authorization.html#assign-privileges) on the current database.
> ```

Does not need create either
___
*[v21.1/reassign-owned.md, line 87 at r1](https://reviewable.io/reviews/cockroachdb/docs/11014#-MgNKZ3A-NfFIy8gbb8Y:-MgNKZ3A-NfFIy8gbb8Z:bqadjli) ([raw file](https://github.com/cockroachdb/docs/blob/f6479e7efc7134e0a3b70393f86f1eab25e48009/v21.1/reassign-owned.md#L87)):*
> ```Markdown
> {% include copy-clipboard.html %}
> ~~~ sql
> > REASSIGN OWNED BY cockroachlabs TO movrlabs;
> ```

You'd actually have to GRANT movrlabs to cockroachlabs first  for this to succeed but the privilege check is bugged right now.


<!-- Sent from Reviewable.io -->

2021-08-05 22:39 UTC, RichardJCai requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11014)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[v21.1/reassign-owned.md, line 15 at r1](https://reviewable.io/reviews/cockroachdb/docs/11014#-MgNK4Pi68Lcid-69dNm:-MgNSZH50OSxdynluyy3:byjc6c0) ([raw file](https://github.com/cockroachdb/docs/blob/f6479e7efc7134e0a3b70393f86f1eab25e48009/v21.1/reassign-owned.md#L15)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

The user executing the command doesn't have to be a member of the admin role but must be a member of the `old` and `new` role.

See: 
https://www.postgresql.org/docs/current/sql-reassign-owned.html

Right now we actually don't have any privilege checks which is a bug I'm gonna make a PR right now to fix it.
</blockquote></details>

Actually sorry, since this is for 21.1 and we wouldn't be backporting my fix, just change it to 
the user executing it must be either a member of the admin role or must be a member of the new role and have CREATE. It'll be changed in the next version


<!-- Sent from Reviewable.io -->

2021-08-06 16:21 UTC, ericharmeling reviewed
TFTR @richardjcai 

I followed the privileges suggestion in your last comment, but held off on all other suggestions. PTAL. 

We can always update if the 21.2 fix gets backported in a later minor release.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11014#-:-MgRFIfx10aIwK6ufOs8:b3ipmuv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[v21.1/reassign-owned.md, line 15 at r1](https://reviewable.io/reviews/cockroachdb/docs/11014#-MgNK4Pi68Lcid-69dNm:-MgRFm3OBqfU6F9Abcnv:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f6479e7efc7134e0a3b70393f86f1eab25e48009/v21.1/reassign-owned.md#L15)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Actually sorry, since this is for 21.1 and we wouldn't be backporting my fix, just change it to 
the user executing it must be either a member of the admin role or must be a member of the new role and have CREATE. It'll be changed in the next version
</blockquote></details>

Done.
___
*[v21.1/reassign-owned.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/11014#-MgNKLGV88gYqSoq6yig:-MgRF_3_6uAYk_pm-n47:bft11ai) ([raw file](https://github.com/cockroachdb/docs/blob/f6479e7efc7134e0a3b70393f86f1eab25e48009/v21.1/reassign-owned.md#L16)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Does not need create either
</blockquote></details>

I get the following in 21.1.6:

~~~
demo@127.0.0.1:26257/movr> REASSIGN OWNED BY cockroachlabs TO movrlabs;
ERROR: user movrlabs does not have CREATE privilege on database movr
~~~

But maybe this is part of the bug you are talking about?


<!-- Sent from Reviewable.io -->

2021-08-11 18:33 UTC, RichardJCai commented
> Previously, RichardJCai (Richard Cai) wrote…
> I get the following in 21.1.6:
> 
> ```
> demo@127.0.0.1:26257/movr> REASSIGN OWNED BY cockroachlabs TO movrlabs;
> ERROR: user movrlabs does not have CREATE privilege on database movr
> ```
> 
> But maybe this is part of the bug you are talking about?

Yeah I realized the privilege check is "incorrect" filed a separate issue about it. This LGTM for now

2021-08-11 18:34 UTC, RichardJCai approved these changes
Thanks for documenting this!

2021-08-17 15:15 UTC, ianjevans approved these changes
Just some include_cached nits, looks good.

2021-08-17 15:15 UTC, ianjevans commented on v21.1/reassign-owned.md
> +{% include copy-clipboard.html %}
```suggestion
{% include_cached copy-clipboard.html %}
```

2021-08-17 15:15 UTC, ianjevans commented on v21.1/reassign-owned.md
> +{% include copy-clipboard.html %}
```suggestion
{% include_cached copy-clipboard.html %}
```

2021-08-17 15:15 UTC, ianjevans commented on v21.1/reassign-owned.md
> +{% include copy-clipboard.html %}
```suggestion
{% include_cached copy-clipboard.html %}
```

2021-08-17 15:15 UTC, ianjevans commented on v21.1/reassign-owned.md
> +{% include copy-clipboard.html %}
```suggestion
{% include_cached copy-clipboard.html %}
```

2021-08-17 15:15 UTC, ianjevans commented on v21.1/reassign-owned.md
> +{% include copy-clipboard.html %}
```suggestion
{% include_cached copy-clipboard.html %}
```

2021-08-17 15:15 UTC, ianjevans commented on v21.1/reassign-owned.md
> +{% include copy-clipboard.html %}
```suggestion
{% include_cached copy-clipboard.html %}
```

2021-08-17 15:15 UTC, ianjevans commented on v21.1/reassign-owned.md
> +{% include copy-clipboard.html %}
```suggestion
{% include_cached copy-clipboard.html %}
```

2021-08-17 15:15 UTC, ianjevans commented on v21.1/reassign-owned.md
> +{% include copy-clipboard.html %}
```suggestion
{% include_cached copy-clipboard.html %}
```

2021-08-17 18:36 UTC, ericharmeling commented
TFTR!

These `include_cached`s keep getting me 😆

2021-08-17 18:47 UTC, merged