sql: clarify that role options are not inherited
cockroachdb/docs pull request #11675
Opened 2021-09-14 22:27 UTC by rafiss

This also includes a rewording to use the term "role option" instead of
"parameter" to describe these properties.

2021-09-14 22:27 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/11675)
<!-- Reviewable:end -->

2021-09-14 22:28 UTC, rafiss commented
I made this update in response to some confusion on https://github.com/cockroachlabs/support/issues/1217 (internal link)

I can update the pages for other versions if this looks good.

2021-09-15 15:29 UTC, ericharmeling requested changes
Thanks for handling this!

I have a few comments/suggestions. After you resolve those, it should be okay to copy the changes to 20.2, 21.1 docs.

Also, this PR should fix this issue: https://github.com/cockroachdb/docs/issues/8686

Also, there should be a follow-up PR that more specifically documents "role options" as a concept (and perhaps provides a list of available options). This is actually mentioned here: https://github.com/cockroachdb/docs/issues/10015#issue-835063060. Definitely a separate thing though IMO.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11675#-:-MjdpzFj9ymr_QdP_bEX:b-cjh7uc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[v21.2/alter-role.md, line 25 at r1](https://reviewable.io/reviews/cockroachdb/docs/11675#-MjdoylW9D6S2IZu8lYZ:-MjdoylW9D6S2IZu8lY_:b-bl8ymb) ([raw file](https://github.com/cockroachdb/docs/blob/6e5415a8777fc3afb37e5ff66cf5fa23ba91c456/v21.2/alter-role.md#L25)):*
> ```
> ## Role options
> ```

I think we should keep this as `## Parameters`, since that is the convention in our syntax docs when referring to statement syntax keywords (even though most of these parameters are, in fact, role options).
___
*[v21.2/alter-role.md, line 33 at r1](https://reviewable.io/reviews/cockroachdb/docs/11675#-MjdpfmeBS8RTFZOS1nE:-MjdpfmeBS8RTFZOS1nF:b-os5ffl) ([raw file](https://github.com/cockroachdb/docs/blob/6e5415a8777fc3afb37e5ff66cf5fa23ba91c456/v21.2/alter-role.md#L33)):*
> ```
> Role option
> ```

Same here. I think this header should remain `Parameters`.
___
*[v21.2/create-role.md, line 7 at r1](https://reviewable.io/reviews/cockroachdb/docs/11675#-Mje3Rkj8A80rKpwtHCp:-Mje3Rkj8A80rKpwtHCq:briqjpa) ([raw file](https://github.com/cockroachdb/docs/blob/6e5415a8777fc3afb37e5ff66cf5fa23ba91c456/v21.2/create-role.md#L7)):*
> ```
> privileges
> ```

`[privileges](authorization.html#privileges)`

(Just an ask, beyond the changes in the PR :smile_cat: )
___
*[v21.2/create-role.md, line 39 at r1](https://reviewable.io/reviews/cockroachdb/docs/11675#-MjdqnVy2TWd8eeHU_Qd:-MjdqnVy2TWd8eeHU_Qe:b-w8n8da) ([raw file](https://github.com/cockroachdb/docs/blob/6e5415a8777fc3afb37e5ff66cf5fa23ba91c456/v21.2/create-role.md#L39)):*
> ```
> ## Role options
> | Role option | Description |
> --------------|--------------
> ```

See my comments above. The same would apply here.

Also, changing the `## Role options` section header here breaks a few references to this page, which is causing errors in the build.


<!-- Sent from Reviewable.io -->

2021-09-15 17:15 UTC, rafiss reviewed
ah nice, i linked #8636  

i made another update -- some of the sentences were using the term "privilege" to refer to a "role option." that sounds easy to confuse with SQL privileges, so i reworded them.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11675#-:-MjeRqgVAxd3nHEs9pkc:bibklca)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[v21.2/alter-role.md, line 25 at r1](https://reviewable.io/reviews/cockroachdb/docs/11675#-MjdoylW9D6S2IZu8lYZ:-MjeRw_BCThofT9zOCbM:b1hq9hp) ([raw file](https://github.com/cockroachdb/docs/blob/6e5415a8777fc3afb37e5ff66cf5fa23ba91c456/v21.2/alter-role.md#L25)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> ## Role options
> ```

I think we should keep this as `## Parameters`, since that is the convention in our syntax docs when referring to statement syntax keywords (even though most of these parameters are, in fact, role options).
</blockquote></details>

done, but i kept "role option" in the non-header text. let me know if i should make those say "parameter" also
___
*[v21.2/alter-role.md, line 33 at r1](https://reviewable.io/reviews/cockroachdb/docs/11675#-MjdpfmeBS8RTFZOS1nE:-MjeRxMg-2mimVWoN4VM:bb7f2mf) ([raw file](https://github.com/cockroachdb/docs/blob/6e5415a8777fc3afb37e5ff66cf5fa23ba91c456/v21.2/alter-role.md#L33)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> Role option
> ```

Same here. I think this header should remain `Parameters`.
</blockquote></details>

done
___
*[v21.2/create-role.md, line 7 at r1](https://reviewable.io/reviews/cockroachdb/docs/11675#-Mje3Rkj8A80rKpwtHCp:-MjeSGSiA7pjSzpcHWWi:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/6e5415a8777fc3afb37e5ff66cf5fa23ba91c456/v21.2/create-role.md#L7)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> privileges
> ```

`[privileges](authorization.html#privileges)`

(Just an ask, beyond the changes in the PR :smile_cat: )
</blockquote></details>

Done.
___
*[v21.2/create-role.md, line 39 at r1](https://reviewable.io/reviews/cockroachdb/docs/11675#-MjdqnVy2TWd8eeHU_Qd:-MjeSHRu4iWGmpOJREjN:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/6e5415a8777fc3afb37e5ff66cf5fa23ba91c456/v21.2/create-role.md#L39)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> ## Role options
> | Role option | Description |
> --------------|--------------
> ```

See my comments above. The same would apply here.

Also, changing the `## Role options` section header here breaks a few references to this page, which is causing errors in the build.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-15 20:00 UTC, ericharmeling approved these changes
LGTM. Thanks!

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11675#-:-Mjf1q1fApK-hd5laPIZ:b-tx3rjn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @rafiss)

___
*[v21.2/alter-role.md, line 25 at r1](https://reviewable.io/reviews/cockroachdb/docs/11675#-MjdoylW9D6S2IZu8lYZ:-Mjf1nIq71QH2n-2Zqyx:bncd7sb) ([raw file](https://github.com/cockroachdb/docs/blob/6e5415a8777fc3afb37e5ff66cf5fa23ba91c456/v21.2/alter-role.md#L25)):*
> done, but i kept "role option" in the non-header text. 

Perfect. Thanks!


<!-- Sent from Reviewable.io -->

2021-09-15 22:14 UTC, rafiss commented
OK, coped to all the versions!

@ericharmeling could you give it one more review? there actually were some useful details in the v20.2 docs that were NOT in the v21.1 or v21.2 docs, so I coped them over

2021-09-16 14:54 UTC, ericharmeling commented
> there actually were some useful details in the v20.2 docs that were NOT in the v21.1 or v21.2 docs, so I copied them over

Yeah... it actually looks like a lot of changes were made to v20.2 here: https://github.com/cockroachdb/docs/pull/9913/files#diff-904332eaa2cdbe1ee643c7067bcc16b9274cbcd407feec85e6442ca2bfe6040fR14

But it doesn't look like these changes were copied over to 21.1 ahead of 21.1 itself being duplicated for the 21.2 release... 😞 :.  TBH not too much has happened since then (https://github.com/cockroachdb/docs/commits/master/v21.1/create-role.md v https://github.com/cockroachdb/docs/commits/master/v20.2/create-role.md), so this could be an easy fix, but I'll leave it for the security writer to handle. I'll make an issue.

LGTM though Rafi, thanks for the help here!

2021-09-16 15:12 UTC, merged