Gorm refactor
cockroachdb/docs pull request #11704
Opened 2021-09-16 21:15 UTC by ericharmeling

Fixes https://github.com/cockroachdb/docs/issues/4207
Fixes https://github.com/cockroachdb/docs/issues/8683
Fixes https://github.com/cockroachdb/docs/issues/8228

This PR updates the existing GORM tutorial to match the refactored sample app now located at https://github.com/cockroachlabs/example-app-go-gorm. It also includes a sample tutorial for the new Hello World app located at https://github.com/cockroachlabs/hello-world-go-gorm.

I'll propagate all changes to v20.2, v21.1 docsets after these changes are approved.

Related to https://github.com/cockroachdb/docs/pull/11063.

2021-09-16 21:15 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/11704)
<!-- Reviewable:end -->

2021-09-17 16:48 UTC, ianjevans requested changes
The `git clone` steps need the trailing slash removed, as it will error-out. Otherwise looks good.

2021-09-17 16:48 UTC, ianjevans commented on v20.2/build-a-go-app-with-cockroachdb-gorm.md
> +$ git clone https://github.com/cockroachlabs/example-app-go-gorm/
```suggestion
$ git clone https://github.com/cockroachlabs/example-app-go-gorm
```

2021-09-17 16:48 UTC, ianjevans commented on v20.2/hello-world-go-gorm.md
> +$ git clone https://github.com/cockroachlabs/hello-world-go-gorm/
```suggestion
$ git clone https://github.com/cockroachlabs/hello-world-go-gorm
```

2021-09-17 16:48 UTC, ianjevans commented on v21.1/build-a-go-app-with-cockroachdb-gorm.md
> +$ git clone https://github.com/cockroachlabs/example-app-go-gorm/
```suggestion
$ git clone https://github.com/cockroachlabs/example-app-go-gorm
```

2021-09-17 16:48 UTC, ianjevans commented on v21.1/hello-world-go-gorm.md
> +$ git clone https://github.com/cockroachlabs/hello-world-go-gorm/
```suggestion
$ git clone https://github.com/cockroachlabs/hello-world-go-gorm
```

2021-09-17 16:48 UTC, ianjevans commented on v21.2/build-a-go-app-with-cockroachdb-gorm.md
> +$ git clone https://github.com/cockroachlabs/example-app-go-gorm/
```suggestion
$ git clone https://github.com/cockroachlabs/example-app-go-gorm
```

2021-09-17 16:48 UTC, ianjevans commented on v21.2/hello-world-go-gorm.md
> +$ git clone https://github.com/cockroachlabs/hello-world-go-gorm/
```suggestion
$ git clone https://github.com/cockroachlabs/hello-world-go-gorm
```

2021-09-20 14:05 UTC, ericharmeling reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11704#-:-Mk2We6w9R7Lg7u0u2j-:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ianjevans)

___
*[v20.2/build-a-go-app-with-cockroachdb-gorm.md, line 32 at r1](https://reviewable.io/reviews/cockroachdb/docs/11704#-MjkSeHHc1r5PEqlQmT0-r1-32:-Mk2WfMY37vReXEQN7Bm:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/d513572d8b643c8fac6b45f2cb14028b8a734afd/v20.2/build-a-go-app-with-cockroachdb-gorm.md#L32)):*
<details><summary><i>Previously, ianjevans (Ian Evans) wrote…</i></summary><blockquote>

```suggestion
$ git clone https://github.com/cockroachlabs/example-app-go-gorm
```
</blockquote></details>

Done.
___
*[v20.2/hello-world-go-gorm.md, line 26 at r1](https://reviewable.io/reviews/cockroachdb/docs/11704#-MjkSeHHc1r5PEqlQmT2-r1-26:-Mk2Wg5a7K8a5knnExDp:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/d513572d8b643c8fac6b45f2cb14028b8a734afd/v20.2/hello-world-go-gorm.md#L26)):*
<details><summary><i>Previously, ianjevans (Ian Evans) wrote…</i></summary><blockquote>

```suggestion
$ git clone https://github.com/cockroachlabs/hello-world-go-gorm
```
</blockquote></details>

Done.
___
*[v21.1/build-a-go-app-with-cockroachdb-gorm.md, line 32 at r1](https://reviewable.io/reviews/cockroachdb/docs/11704#-MjkSeHHc1r5PEqlQmT4-r1-32:-Mk2WgYc37reEnOAy4-4:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/d513572d8b643c8fac6b45f2cb14028b8a734afd/v21.1/build-a-go-app-with-cockroachdb-gorm.md#L32)):*
<details><summary><i>Previously, ianjevans (Ian Evans) wrote…</i></summary><blockquote>

```suggestion
$ git clone https://github.com/cockroachlabs/example-app-go-gorm
```
</blockquote></details>

Done.
___
*[v21.1/hello-world-go-gorm.md, line 26 at r1](https://reviewable.io/reviews/cockroachdb/docs/11704#-MjkSeHHc1r5PEqlQmT6-r1-26:-Mk2WgwwC3PLcOGAqb0A:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/d513572d8b643c8fac6b45f2cb14028b8a734afd/v21.1/hello-world-go-gorm.md#L26)):*
<details><summary><i>Previously, ianjevans (Ian Evans) wrote…</i></summary><blockquote>

```suggestion
$ git clone https://github.com/cockroachlabs/hello-world-go-gorm
```
</blockquote></details>

Done.
___
*[v21.2/build-a-go-app-with-cockroachdb-gorm.md, line 32 at r1](https://reviewable.io/reviews/cockroachdb/docs/11704#-MjkSeHHc1r5PEqlQmT8-r1-32:-Mk2WhES6Do_3F03-J_1:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/d513572d8b643c8fac6b45f2cb14028b8a734afd/v21.2/build-a-go-app-with-cockroachdb-gorm.md#L32)):*
<details><summary><i>Previously, ianjevans (Ian Evans) wrote…</i></summary><blockquote>

```suggestion
$ git clone https://github.com/cockroachlabs/example-app-go-gorm
```
</blockquote></details>

Done.
___
*[v21.2/hello-world-go-gorm.md, line 26 at r1](https://reviewable.io/reviews/cockroachdb/docs/11704#-MjkSeHHc1r5PEqlQmTA-r1-26:-Mk2WhsS5JMqKJWddvdh:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/d513572d8b643c8fac6b45f2cb14028b8a734afd/v21.2/hello-world-go-gorm.md#L26)):*
<details><summary><i>Previously, ianjevans (Ian Evans) wrote…</i></summary><blockquote>

```suggestion
$ git clone https://github.com/cockroachlabs/hello-world-go-gorm
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-20 14:11 UTC, merged