Explain which log files are available via DB Console.
cockroachdb/docs pull request #11870
Opened 2021-10-04 15:23 UTC by knz

Note: we will fix the known limitations in [v21.2.1](https://github.com/cockroachdb/cockroach/pull/71075), but for now it needs to be documented.

2021-10-04 15:23 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/11870)
<!-- Reviewable:end -->

2021-10-04 21:27 UTC, taroface requested changes
Thank you @knz - some small comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11870#-:-MlCByiXD_8tPxzDSyKj:b-2pitwr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @taroface)

___
*[v20.1/sql-audit-logging.md, line 192 at r1](https://reviewable.io/reviews/cockroachdb/docs/11870#-MlC9V2d9AO6ZhTWsRdg:-MlC9V2eAAp3oF1wGtQ9:b326am) ([raw file](https://github.com/cockroachdb/docs/blob/582cdeb72125700c479a1099d4cd337a9237c6ba/v20.1/sql-audit-logging.md#L192)):*
> ```Markdown
> 
> SQL audit logs can only be accessed in the DB Console if they are
> stored in the same directory as the main CockroachDB log files.
> ```

Suggest adding a line: "For more information, see [`EXPERIMENTAL_AUDIT`](experimental-audit.html#audit-log-file-storage-location)."
___
*[v20.2/sql-audit-logging.md, line 194 at r1](https://reviewable.io/reviews/cockroachdb/docs/11870#-MlCBdxP1I1-f3bht0j9:-MlCBdxP1I1-f3bht0jA:b-89a4l7) ([raw file](https://github.com/cockroachdb/docs/blob/582cdeb72125700c479a1099d4cd337a9237c6ba/v20.2/sql-audit-logging.md#L194)):*
> ```Markdown
> 
> SQL audit logs can only be accessed in the DB Console if they are
> stored in the same directory as the main CockroachDB log files.
> ```

Ditto
___
*[v21.1/configure-logs.md, line 173 at r1](https://reviewable.io/reviews/cockroachdb/docs/11870#-MlCBmFT5OhTRBLwE59c:-MlCBmFT5OhTRBLwE59d:b-3m29b1) ([raw file](https://github.com/cockroachdb/docs/blob/582cdeb72125700c479a1099d4cd337a9237c6ba/v21.1/configure-logs.md#L173)):*
> ```Markdown
> {{site.data.alerts.end}}
> 
> #### Access in DB Console
> ```

Nice! Thanks for this.
___
*[v21.1/configure-logs.md, line 182 at r1](https://reviewable.io/reviews/cockroachdb/docs/11870#-MlCBpp03wSR02MmMMlX:-MlCBpp03wSR02MmMMlY:b-mcnxmn) ([raw file](https://github.com/cockroachdb/docs/blob/582cdeb72125700c479a1099d4cd337a9237c6ba/v21.1/configure-logs.md#L182)):*
> ```Markdown
> 
> Log files can only be accessed in the DB Console if they are stored
> in the same directory as the file sink for the DEV channel.
> ```

Nit: DEV -> `DEV`
___
*[v21.1/sql-audit-logging.md, line 199 at r1](https://reviewable.io/reviews/cockroachdb/docs/11870#-MlCBfgv1YzZMDy4h8VL:-MlCBfgw0cJ2c7ceINtN:b-89a4l7) ([raw file](https://github.com/cockroachdb/docs/blob/582cdeb72125700c479a1099d4cd337a9237c6ba/v21.1/sql-audit-logging.md#L199)):*
> ```Markdown
> 
> SQL audit logs can only be accessed in the DB Console if they are
> stored in the same directory as the main CockroachDB log files.
> ```

Ditto
___
*[v21.2/configure-logs.md, line 186 at r1](https://reviewable.io/reviews/cockroachdb/docs/11870#-MlCBvsN59APgtJCkKVF:-MlCBvsN59APgtJCkKVG:b-89a4l7) ([raw file](https://github.com/cockroachdb/docs/blob/582cdeb72125700c479a1099d4cd337a9237c6ba/v21.2/configure-logs.md#L186)):*
> ```Markdown
> 
> Log files can only be accessed in the DB Console if they are stored
> in the same directory as the file sink for the DEV channel.
> ```

Ditto


<!-- Sent from Reviewable.io -->

2021-10-05 21:56 UTC, taroface approved these changes
LGTM! But with one last nit

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11870#-:-MlHSESEATNA28fx0Htq:b-cov3o)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @taroface)

___
*[v20.1/sql-audit-logging.md, line 192 at r1](https://reviewable.io/reviews/cockroachdb/docs/11870#-MlC9V2d9AO6ZhTWsRdg:-MlHS9bz5VCbv6NiIPph:bsr8fn7) ([raw file](https://github.com/cockroachdb/docs/blob/582cdeb72125700c479a1099d4cd337a9237c6ba/v20.1/sql-audit-logging.md#L192)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

One nit, sorry: Can you please add code backticks to `EXPERIMENTAL_AUDIT`?


<!-- Sent from Reviewable.io -->

2021-10-05 22:15 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11870)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @taroface)

___
*[v20.1/sql-audit-logging.md, line 192 at r1](https://reviewable.io/reviews/cockroachdb/docs/11870#-MlC9V2d9AO6ZhTWsRdg:-MlHWUzVAOg0X-zJ-Pgj:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/582cdeb72125700c479a1099d4cd337a9237c6ba/v20.1/sql-audit-logging.md#L192)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

One nit, sorry: Can you please add code backticks to `EXPERIMENTAL_AUDIT`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-05 22:30 UTC, merged