SHOW DEFAULT PRIVILEGES/ALTER DEFAULT PRIVILEGES
cockroachdb/docs pull request #11942
Opened 2021-10-12 18:31 UTC by ericharmeling

Fixes https://github.com/cockroachdb/docs/issues/11420.
Fixes https://github.com/cockroachdb/docs/issues/11419.
Fixes https://github.com/cockroachdb/docs/issues/11442.
Fixes https://github.com/cockroachdb/docs/issues/11421.
Fixes https://github.com/cockroachdb/docs/issues/11449.
Fixes https://github.com/cockroachdb/docs/issues/11378.
Fixes https://github.com/cockroachdb/docs/issues/11397.
Fixes https://github.com/cockroachdb/docs/issues/11403.

2021-11-01 17:08 UTC, ericharmeling commented
@RichardJCai ping on review

2021-11-01 19:13 UTC, RichardJCai approved these changes
LGTM nice!

2021-11-01 19:17 UTC, ericharmeling commented
@RichardJCai TFTR!

2021-11-03 19:49 UTC, stbof commented on v21.2/alter-default-privileges.md
> +Note that, because `max` has no default privileges, the user can now be dropped:
```suggestion
Because `max` has no default privileges, the user can now be dropped:
```

2021-11-03 19:50 UTC, stbof commented on v21.2/authorization.md
> +Note that the creator of an object is also the object's [owner](authorization.html#object-ownership). Any roles that are members of the owner role have `ALL` privileges on the object, independent of
```suggestion
The creator of an object is also the object's [owner](authorization.html#object-ownership). Any roles that are members of the owner role have `ALL` privileges on the object, independent of the default privileges. Altering the default privileges of objects created by a role does not affect that role's privileges as the object's owner. The default privileges granted to other users/roles are always in addition to the ownership (i.e., `ALL`) privileges given to the creator of the object.
```

2021-11-03 19:50 UTC, stbof requested changes
See comment and suggestions.

2021-11-09 16:44 UTC, ericharmeling reviewed
TFTRs!

2021-11-09 17:20 UTC, merged