Local testing best practices
cockroachdb/docs pull request #12111
Opened 2021-10-28 17:40 UTC by ericharmeling

Fixes https://github.com/cockroachdb/docs/issues/10991.

This doc is just the first iteration of an app-testing docs page for developer users. This first iteration can just focus on local unit testing. We can further break this page up into sections for unit testing, integration testing, and automation (see https://github.com/cockroachdb/docs/issues/12077 and https://github.com/cockroachdb/docs/issues/10800).

I initially started working on this to resolve https://github.com/cockroachdb/docs/issues/10991, as it relates to https://cockroachlabs.atlassian.net/browse/CRDB-2459. We don't have full TestContainer support yet (AFAIK), so I just added some extra tips that may/may not be relevant to people reading this page (happy to remove those).

Some open questions:

- Do we really want to recommend unit-testing applications against a local, single-node, insecure cluster? What about free tier/serverless? (see https://github.com/cockroachdb/docs/issues/10991#issuecomment-954015843)
- Are there any more best practices that we can add here? (e.g., cluster settings to temporarily set? third-party unit testing tools to recommend?)

2021-11-03 15:47 UTC, vy-ton approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12111)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @rafiss)

___
*[v21.2/local-testing.md, line 43 at r1](https://reviewable.io/reviews/cockroachdb/docs/12111#-MnaTjB2C0Dp5MOfJHfK:-MnaTjB2C0Dp5MOfJHfL:b-e8k35u) ([raw file](https://github.com/cockroachdb/docs/blob/602df1bf86ad59b55522ee98c5d37c64b8ec7dfd/v21.2/local-testing.md#L43)):*
> ```Markdown
> ## Use a local file server for bulk operations
> 
> To test bulk operations like [`IMPORT`](import.html), [`BACKUP`](backup.html), or [`RESTORE`](restore.html), we recommend using a local file server.
> ```

@livlobo Does this match Bulk IO recommended best practice


<!-- Sent from Reviewable.io -->

2021-11-10 19:44 UTC, kernfeld-cockroach commented
It wouldn't be crazy to recommend Serverless as a testing tool, but that's no longer really "local testing" so I would probably scope it to a different doc page.

2021-11-15 17:40 UTC, ericharmeling commented
@rafiss Ping on quick review

2021-11-15 17:41 UTC, ericharmeling commented
Anyone else we might want to add to this? Would like to merge by EOW.

2021-11-15 20:07 UTC, rafiss requested changes
lgtm with one nit! i agree with the point that for devs running unit tests against their app, they probably would not want to go across a network boundary and use serverless in the average case -- so this will be valuable info to document

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12111#-:-Mo_CSKVDrVQaBe_szi6:b-ykw7ev)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @kernfeld-cockroach, and @livlobo)

___
*[v21.2/local-testing.md, line 32 at r1](https://reviewable.io/reviews/cockroachdb/docs/12111#-Mo_AqDv17w7qtKLUhmH:-Mo_AqDv17w7qtKLUhmI:b-6v947n) ([raw file](https://github.com/cockroachdb/docs/blob/602df1bf86ad59b55522ee98c5d37c64b8ec7dfd/v21.2/local-testing.md#L32)):*
> ```Markdown
> {% include_cached copy-clipboard.html %}
> ~~~ shell
> cockroach start-single-node --insecure --store=type=mem,size=0.25 --advertise-addr=localhost --log="{file-defaults: {dir: /path/to/logs}, sinks: {stderr: {filter: NONE}}}"
> ```

i think it'd be worth clarifying that this `--log` recommendation is because `start-single-node` WITH `--store=type=mem` causes all the logs to be shown in stdout (directly on the console)


<!-- Sent from Reviewable.io -->

2021-11-17 19:22 UTC, ericharmeling reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12111#-:-MojLPHHAH_O26bh07jH:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @kernfeld-cockroach, @livlobo, and @rafiss)

___
*[v21.2/local-testing.md, line 32 at r1](https://reviewable.io/reviews/cockroachdb/docs/12111#-Mo_AqDv17w7qtKLUhmH:-MojL8s88zPfxtN11x4D:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/602df1bf86ad59b55522ee98c5d37c64b8ec7dfd/v21.2/local-testing.md#L32)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think it'd be worth clarifying that this `--log` recommendation is because `start-single-node` WITH `--store=type=mem` causes all the logs to be shown in stdout (directly on the console)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-17 19:28 UTC, stbof commented on v21.2/local-testing.md
> +By default, `cockroach start-single-node` logs cluster activity to a file with the [default logging configuration](configure-logs.html#default-logging-configuration). When the `--store=type=mem` flag
```suggestion
By default, `cockroach start-single-node` logs cluster activity to a file with the [default logging configuration](configure-logs.html#default-logging-configuration). To print cluster activity directly to the console instead, specify  the `--store=type=mem` flag.
```

2021-11-17 19:28 UTC, stbof commented on v21.2/local-testing.md
> +This particular command includes two options:
```suggestion
This command has two options:
```

2021-11-17 19:29 UTC, stbof commented on v21.2/local-testing.md
> +This particular command includes two options:
Or "this flag has two suboptions".

2021-11-17 19:30 UTC, stbof commented on v21.2/local-testing.md
> +
Why would you choose to do that?

2021-11-17 19:42 UTC, stbof requested changes
See suggestions and question.

2021-11-17 22:17 UTC, livlobo reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12111)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @kernfeld-cockroach, @rafiss, and @stevendanna)

___
*[v21.2/local-testing.md, line 43 at r1](https://reviewable.io/reviews/cockroachdb/docs/12111#-MnaTjB2C0Dp5MOfJHfK:-Mojxugz76QqgwwbDO6z:b-9yk4jz) ([raw file](https://github.com/cockroachdb/docs/blob/602df1bf86ad59b55522ee98c5d37c64b8ec7dfd/v21.2/local-testing.md#L43)):*
<details><summary><i>Previously, vy-ton (Vy Ton) wrote…</i></summary><blockquote>

@livlobo Does this match Bulk IO recommended best practice
</blockquote></details>

@vy-ton - I'm not sure, what the recommendation should be for "testing' purposes. For regular use, we recommend using cloud storage for bulk operations. 
@stevendanna - do you have a recommendation?


<!-- Sent from Reviewable.io -->

2021-11-18 19:20 UTC, rafiss approved these changes
looks good from my end, but i personally am not sure about the Bulk IO recommendations so i'll defer to someone else

2021-12-15 17:04 UTC, ericharmeling commented
I think I got to everyone's direct feedback on this PR. 

I'm going to go ahead and merge it, if there's no objections. We can iterate after it's published, if necessary.

2021-12-15 18:01 UTC, merged