Follow up to incorporate feedback from Vy and Ian for #11968.
cockroachdb/docs pull request #12211
Opened 2021-11-09 17:44 UTC by stbof

Also fixes SQL feature support table for #12148.

2021-11-09 17:44 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/12211)
<!-- Reviewable:end -->

2021-11-09 22:05 UTC, ianjevans approved these changes

2021-11-11 17:25 UTC, vy-ton requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12211)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @stbof)

___
*[v21.2/expression-indexes.md, line 123 at r2](https://reviewable.io/reviews/cockroachdb/docs/12211#-MoEy0nJ31tOU2ZDFue-:-MoEy0nJ31tOU2ZDFue0:bsgym3n) ([raw file](https://github.com/cockroachdb/docs/blob/bf7ff4213485045343a0eda50221b169b8586536/v21.2/expression-indexes.md#L123)):*
> ```Markdown
>           └── • scan
>                 estimated row count: 3 (100% of the table; stats collected 5 minutes ago)
>                 table: users@timestamp_idx
> ```

Might be a copy/paste error, but the `timestamp_idx` wouldn't exist at this point in the example
___
*[v21.2/expression-indexes.md, line 138 at r2](https://reviewable.io/reviews/cockroachdb/docs/12211#-MoExgqoBO8L04HjVXxI:-MoExgqoBO8L04HjVXxJ:bj41n2t) ([raw file](https://github.com/cockroachdb/docs/blob/bf7ff4213485045343a0eda50221b169b8586536/v21.2/expression-indexes.md#L138)):*
> ```Markdown
> {% include_cached copy-clipboard.html %}
> ~~~sql
> > EXPLAIN SELECT jsonb_pretty(user_profile) FROM users@timestamp_idx WHERE parse_timestamp(user_profile->>'birthdate') = '2011-11-07';
> ```

The `EXPLAIN` output here should be without the index hint

The example flow is:
* Show `EXPLAIN` for query with full scan
* Create index
* `EXPLAIN` should show that the optimizer uses the new index **without the @timestamp_idx** index hint


<!-- Sent from Reviewable.io -->

2021-11-11 17:47 UTC, stbof commented
___
*[v21.2/expression-indexes.md, line 138 at r2](https://reviewable.io/reviews/cockroachdb/docs/12211#-MoExgqoBO8L04HjVXxI:-MoF5xBhEdO1ZcT-bgsp:bv0ilvi) ([raw file](https://github.com/cockroachdb/docs/blob/bf7ff4213485045343a0eda50221b169b8586536/v21.2/expression-indexes.md#L138)):*
<details><summary><i>Previously, vy-ton (Vy Ton) wrote…</i></summary><blockquote>

The `EXPLAIN` output here should be without the index hint

The example flow is:
* Show `EXPLAIN` for query with full scan
* Create index
* `EXPLAIN` should show that the optimizer uses the new index **without the @timestamp_idx** index hint
</blockquote></details>

If I run w/out the index hint it does a full scan:

EXPLAIN SELECT jsonb_pretty(user_profile) FROM users WHERE parse_timestamp(user_profile->>'birthdate') = '2011-11-07';
                                        info
-------------------------------------------------------------------------------------
  distribution: full
  vectorized: true

  • render
  │ estimated row count: 1
  │
  └── • filter
      │ estimated row count: 1
      │ filter: parse_timestamp(user_profile->>'birthdate') = '2011-11-07 00:00:00'
      │
      └── • scan
            estimated row count: 3 (100% of the table; stats collected 3 days ago)
            table: users@primary
            spans: FULL SCAN
(14 rows)

@mgartner Is that expected?


<!-- Sent from Reviewable.io -->

2021-11-13 03:43 UTC, jseldess commented on v21.2/sql-feature-support.md
> + Expression Indexes | ✓ | Common Extension | [Expression indexes](expression-indexes.html)
Indexes is capitalized here and in the next row but not in the other rows.

2021-11-15 01:49 UTC, vy-ton approved these changes

2021-11-15 16:47 UTC, merged