Refactored SQL Observability DB/Cloud console pages to be shared.
cockroachdb/docs pull request #12263
Opened 2021-11-12 01:35 UTC by ianjevans

This PR pulls the Sessions, Statements, and Transactions page content into a common include with Liquid conditionals to handle different links and UI elements.

2021-11-12 01:35 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/12263)
<!-- Reviewable:end -->

2021-11-12 16:45 UTC, stbof commented
The Statement Details page for Cloud isn't correct. It doesn't have any of the tabs shown here: https://deploy-preview-12263--cockroachdb-docs.netlify.app/docs/cockroachcloud/statements-page.html#activate-diagnostics-collection-and-download-bundles

2021-11-12 17:31 UTC, ianjevans commented
This is what I see after, but you have to have had statistics collected for any of the additional details to show up.

<img width="847" alt="Screen Shot 2021-11-12 at 9 29 50 AM" src="https://user-images.githubusercontent.com/5760366/141509468-6fa73303-8cc3-42ed-b3b2-4e0446151c36.png">

2021-11-12 17:32 UTC, ianjevans commented
But the Diagnostics tab is disabled for now on Serverless clusters, so I'll enclose it with a conditional.

2021-11-12 18:11 UTC, stbof commented on _includes/common/ui/statements-page.md
> +{% if page.cloud != true %}
Line 116 has to be conditionalized out of cloud.

2021-11-12 18:40 UTC, stbof commented on _includes/common/ui/statements-page.md
> +Diagnostics | Activate and download [diagnostics](#diagnostics) for this fingerprint. To activate, click the **Activate** button. The column displays the status of diagnostics collection (`WAITING`,
```suggestion
Diagnostics | Activate and download [diagnostics](#diagnostics) for this fingerprint. To activate, click the **Activate** button. The column displays the status of diagnostics collection (`WAITING`, `READY`, OR `ERROR`). When the status is `READY`, click **Download bundle** to download the most recent diagnostics bundle. <br><br>Statements are periodically cleared from the Statements page based on the start time. To access the full history of diagnostics for the fingerprint, see the [Diagnostics](#diagnostics) section of the Statement Details page. <br><br>**Diagnostics** is not enabled for {{ site.data.products.serverless }} clusters.
```

2021-11-12 20:05 UTC, stbof commented on _includes/common/ui/sessions-page.md
> +- To view [details of a session](#session-details), click the **Session Duration**.
```suggestion
- To view [details of a session](#session-details), click **Session Duration**.
```
```suggestion
- To view [details of a session](#session-details), click the **Session Duration**.
```

2021-11-12 20:07 UTC, stbof commented on _includes/common/ui/sessions-page.md
> +- **Transaction** will display the following information for an open transaction.
```suggestion
- **Transaction** displays the following information for an open transaction.
```
```suggestion
- **Transaction** will display the following information for an open transaction.
```

2021-11-12 20:07 UTC, stbof commented on _includes/common/ui/sessions-page.md
> +- **Statement** will display the following information for an active statement.
```suggestion
- **Statement** displays the following information for an active statement.
```
```suggestion
- **Statement** will display the following information for an active statement.
```

2021-11-12 20:07 UTC, stbof commented on _includes/common/ui/sessions-page.md
> +	- The SQL statement is shown.
```suggestion
	- The SQL statement.
```
```suggestion
	- The SQL statement is shown.
```

2021-11-12 20:07 UTC, stbof commented on _includes/common/ui/sessions-page.md
> +	- **Execution Start Time** shows the timestamp at which the statement was run.
```suggestion
	- **Execution Start Time** the timestamp at which the statement was run.
```
```suggestion
	- **Execution Start Time** shows the timestamp at which the statement was run.
```

2021-11-12 20:08 UTC, stbof commented on _includes/common/ui/sessions-page.md
> +	- **Distributed Execution?** shows whether the statement uses [Distributed SQL (DistSQL)]({{ link_prefix }}architecture/sql-layer.html#distsql) optimization.
```suggestion
	- **Distributed Execution?** whether the statement uses [Distributed SQL (DistSQL)]({{ link_prefix }}architecture/sql-layer.html#distsql) optimization.
```
```suggestion
	- **Distributed Execution?** shows whether the statement uses [Distributed SQL (DistSQL)]({{ link_prefix }}architecture/sql-layer.html#distsql) optimization.
```

2021-11-12 20:22 UTC, stbof commented on _includes/common/ui/transactions-page.md
> +- Transactions from the SQL shell are displayed under the `$ cockroach sql` app.
You can also fitler by Query fingerprint runs longer than a time period. See the description in the Statement page.

2021-11-12 20:23 UTC, stbof commented on _includes/common/ui/transactions-page.md
> +
I suggest moving this up to the Search section.

2021-11-12 20:25 UTC, stbof commented on _includes/common/ui/transactions-page.md
> +In contrast with the [**Statements** page]({{ page_prefix }}statements-page.html), which displays [SQL statement fingerprints]({{ page_prefix }}statements-page.html#sql-statement-fingerprints), the *
```suggestion
In contrast to the [**Statements** page]({{ page_prefix }}statements-page.html), which displays [SQL statement fingerprints]({{ page_prefix }}statements-page.html#sql-statement-fingerprints), the **Transactions** page displays SQL statement fingerprints grouped by [transaction]({{ link_prefix }}transactions.html).
```

2021-11-12 20:26 UTC, stbof commented on _includes/common/ui/transactions-page.md
> +Use this page to identify transactions that you may want to [troubleshoot]({{ link_prefix }}query-behavior-troubleshooting.html), such as transactions that are experiencing high latencies, multiple [
```suggestion
Use the Transactions page to identify transactions that you may want to [troubleshoot]({{ link_prefix }}query-behavior-troubleshooting.html), such as transactions that are experiencing high latencies, multiple [retries]({{ link_prefix }}transactions.html#transaction-retries), or execution failures.
```

2021-11-12 20:27 UTC, stbof requested changes
See suggestions.

2021-11-15 18:25 UTC, stbof commented on _includes/common/ui/statements-page.md
> +{% endif %}
I think you should remove or update this screenshot.  It has the old columns and Serverless doesn't support Diagnostics.

<img width="1360" alt="Screen Shot 2021-11-15 at 10 23 51 AM" src="https://user-images.githubusercontent.com/20482960/141834494-39959a13-30ad-43eb-9a07-639ee211c12d.png">

This are the current columns:
<img width="1930" alt="Screen Shot 2021-11-15 at 10 22 49 AM" src="https://user-images.githubusercontent.com/20482960/141834306-3c18b15b-91ee-4ffb-bc03-e26234e4dfef.png">

FWIW, I removed the screenshot from DB Console docs.

2021-11-15 18:26 UTC, stbof commented on _includes/common/ui/statements-page.md
> +
```suggestion
```

2021-11-15 18:26 UTC, stbof commented on _includes/common/ui/statements-page.md
> +
nit: extra line.

2021-11-15 18:31 UTC, stbof commented on _includes/common/ui/sessions-page.md
> +<img src="{{ 'images/v21.2/ui-sessions-page.png' | relative_url }}" alt="DB Console Database Tables View" style="border:1px solid #eee;max-width:100%" />
If we have Alt text it should be accurate. Right now it is the same in all screenshots.

2021-11-15 18:43 UTC, stbof approved these changes
Please remove the obsolete screenshot. Otherwise LGTM.

2021-11-15 21:23 UTC, merged