Correct serverless benchmarking data
cockroachdb/docs pull request #12486
Opened 2021-12-01 17:31 UTC by gemma-shay

New data: https://docs.google.com/spreadsheets/d/1dQw-uxmEwS1ldbzlgUBhf1s8NnQ4G6ZdY4J3QBML8OE/edit#gid=809516641

Updated the graph and results with corrected data.

2021-12-01 17:32 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/12486)
<!-- Reviewable:end -->

2021-12-06 18:51 UTC, ianjevans requested changes

2021-12-06 18:51 UTC, ianjevans commented on cockroachcloud/serverless-benchmarking.md
> +When not throttled to100 RU/s, the same cluster we benchmarked above used 86,984,376 RUs over 10 minutes, performing 54,460 operations per second and using an average of 2.66 RUs per operation. This
```suggestion
If the previously benchmarked cluster was not throttled to 100 RU/s, it used 86,984,376 RUs over 10 minutes, performing 54,460 operations per second and using an average of 2.66 RUs per operation. This results in a burst performance rate of 144,974 RU/s.
```

2021-12-07 15:56 UTC, gemma-shay commented on cockroachcloud/serverless-benchmarking.md
> +When not throttled to100 RU/s, the same cluster we benchmarked above used 86,984,376 RUs over 10 minutes, performing 54,460 operations per second and using an average of 2.66 RUs per operation. This
Done

2021-12-08 16:55 UTC, ianjevans approved these changes

2021-12-08 16:56 UTC, merged