v21.2.3 Release Notes
cockroachdb/docs pull request #12539
Opened 2021-12-09 20:10 UTC by lnhsingh

Closes https://cockroachlabs.atlassian.net/browse/DOC-1890

2021-12-09 20:10 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/12539)
<!-- Reviewable:end -->

2021-12-13 18:08 UTC, stbof commented on _config_base.yml
> +    build_time: 2021/12/13 11:00:26 (go1.16.6)
If these are being published tomorrow all dates need to change to 12/14.

2021-12-13 18:08 UTC, stbof commented on releases/v21.2.3.md
> +## December 13, 2021
```suggestion
## December 14, 2021
```

2021-12-13 18:12 UTC, stbof commented on releases/v21.2.3.md
> +### DB Console changes
I wonder if this heading should be DB Console and Cloud Console. (For the 2nd bullet).

2021-12-13 18:13 UTC, stbof commented on releases/v21.2.3.md
> +- Fixed a very unlikely bug where a crash during [startup](../v21.2/cockroach-start.html) may cause all subsequent starts to fail. [#73124][#73124]
I don't think we should include `very unlikely`.  It's not really helpful.

2021-12-13 18:14 UTC, stbof requested changes
See comments.

2021-12-13 18:22 UTC, stbof commented on releases/v21.2.3.md
> +summary: Additions and changes in CockroachDB version v21.2.3 since version v21.2.2
I wonder if we need `version` since it already has v21.2.3, etc.

2021-12-13 18:51 UTC, lnhsingh reviewed
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12539#-:-Mqp7d_Y5KTQDFyTEwx_:b-9qdoz3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stbof)

___
*[_config_base.yml, line 87 at r1](https://reviewable.io/reviews/cockroachdb/docs/12539#-MqVoQnKtxHNBXdg4nV5-r1-87:-Mqp7Pq07l7My0Q2sOwp:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/fa0dbfcb63902d1cc8d9db31c10e69ab98604bca/_config_base.yml#L87)):*
<details><summary><i>Previously, stbof (Stephanie Bodoff) wrote…</i></summary><blockquote>

If these are being published tomorrow all dates need to change to 12/14.
</blockquote></details>

Done.
___
*[releases/v21.2.3.md, line 4 at r1](https://reviewable.io/reviews/cockroachdb/docs/12539#-MqVoQnKtxHNBXdg4nV8-r1-4:-Mqp7B3VDp7ZIThQqMJM:bss4a2b) ([raw file](https://github.com/cockroachdb/docs/blob/fa0dbfcb63902d1cc8d9db31c10e69ab98604bca/releases/v21.2.3.md#L4)):*
<details><summary><i>Previously, stbof (Stephanie Bodoff) wrote…</i></summary><blockquote>

I wonder if we need `version` since it already has `v21.2.3`, where `v` stands for version, doesn't it?
</blockquote></details>

Removed.
___
*[releases/v21.2.3.md, line 7 at r1](https://reviewable.io/reviews/cockroachdb/docs/12539#-MqVoQnKtxHNBXdg4nV8-r1-7:-Mqp7ItDARqxXaq4hPAF:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/fa0dbfcb63902d1cc8d9db31c10e69ab98604bca/releases/v21.2.3.md#L7)):*
<details><summary><i>Previously, stbof (Stephanie Bodoff) wrote…</i></summary><blockquote>

```suggestion
## December 14, 2021
```
</blockquote></details>

Done.
___
*[releases/v21.2.3.md, line 86 at r1](https://reviewable.io/reviews/cockroachdb/docs/12539#-MqVoQnKtxHNBXdg4nV8-r1-86:-Mqp6rpZ9CRxFZdvSh7a:bv54h2c) ([raw file](https://github.com/cockroachdb/docs/blob/fa0dbfcb63902d1cc8d9db31c10e69ab98604bca/releases/v21.2.3.md#L86)):*
<details><summary><i>Previously, stbof (Stephanie Bodoff) wrote…</i></summary><blockquote>

I wonder if this heading should be DB Console and Cloud Console (or simply Console changes). (For the 2nd bullet).
</blockquote></details>

I'm inclined to leave it as for now since it's all changes in the DB Console (even if the changes are enabling something to work in the Cloud Console). Changes made to the Cloud Console are outlined in Cloud Release Notes
___
*[releases/v21.2.3.md, line 96 at r1](https://reviewable.io/reviews/cockroachdb/docs/12539#-MqVoQnKtxHNBXdg4nV8-r1-96:-Mqp7YEYEbkA26vVHvWf:bss4a2b) ([raw file](https://github.com/cockroachdb/docs/blob/fa0dbfcb63902d1cc8d9db31c10e69ab98604bca/releases/v21.2.3.md#L96)):*
<details><summary><i>Previously, stbof (Stephanie Bodoff) wrote…</i></summary><blockquote>

I don't think we should include `very unlikely`.  It's not really helpful.
</blockquote></details>

Removed.


<!-- Sent from Reviewable.io -->

2021-12-14 16:21 UTC, stbof approved these changes

2021-12-14 17:28 UTC, merged