Document best way to estimate Serverless usage
cockroachdb/docs pull request #12653
Opened 2021-12-23 20:18 UTC by gemma-shay

https://cockroachlabs.atlassian.net/browse/DOC-2226

The best way to estimate your resource usage is to run your workload and just see how many RUs it uses. Then you can set your spend limit accordingly.
Documented on Create a Cluster page, Cluster Management page, and FAQ.

2021-12-23 20:18 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/12653)
<!-- Reviewable:end -->

2022-01-05 21:58 UTC, jramos-crl approved these changes
LGTM!

2022-01-11 18:31 UTC, ianjevans requested changes

2022-01-11 18:31 UTC, ianjevans commented on _includes/cockroachcloud/serverless-usage.md
> +The best way to estimate your resource usage is to enter a spend limit you're comfortable and run your workload. You can see the RUs and storage your cluster has used in the **Usage this month** sect
```suggestion
The best way to estimate your resource usage is to enter a spend limit you're comfortable with and run your workload. You can see the RUs and storage your cluster has used in the **Usage this month** section of the [**Cluster Overview**](serverless-cluster-management.html#view-cluster-overview) page. Once enough usage data is available, you can also see a graph of your monthly resource usage and recommended spend limit on the [**Edit cluster**](serverless-cluster-management.html#edit-your-spend-limit) page.
```

2022-01-12 21:47 UTC, merged