Release notes for v22.1.0-alpha.1
cockroachdb/docs pull request #12726
Opened 2022-01-13 17:17 UTC by kathancox

Fixes [DOC-1904](https://cockroachlabs.atlassian.net/browse/DOC-1904)

Release notes for v22.1.0-alpha.1

2022-01-13 17:17 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/12726)
<!-- Reviewable:end -->

2022-01-13 21:23 UTC, kathancox commented on _config_base.yml
> +    start_time: 2022-18-01 11:01:26.34274101 +0000 UTC
Oooops just saw the mess up of the date here — not sure I want an 18-month year! Will fold that into the other review feedback.

2022-01-14 00:05 UTC, taroface requested changes
Comments! Mostly nits and link suggestions, some typos. Mostly blocking for 1) Incorrect date formatting in the yml, and 2) some unclear or incomplete bugfix wording in the generated notes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12726#-:-MtKthYnCd1Ln2qJ4GRZ:bjr0k1d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @celiala and @kathancox)

___
*[_config_base.yml, line 93 at r1](https://reviewable.io/reviews/cockroachdb/docs/12726#-MtJhnna0e1IJLFrUPYO:-MtJhnna0e1IJLFrUPYP:btarcjc) ([raw file](https://github.com/cockroachdb/docs/blob/23a5d38bda54611bc49489aadfa0077bf1ba16ac/_config_base.yml#L93)):*
> ```YAML
>     version: v21.2.4
>   v22.1:
>     build_time: 2022/18/01 11:00:26 (go1.16.6)
> ```

Based on the formatting of the other versions, I think the middle numeral is the month. So this should be `2022/01/18`.
___
*[_config_base.yml, line 96 at r1](https://reviewable.io/reviews/cockroachdb/docs/12726#-MtJhtih3KXoAY0Xt00e:-MtJhtih3KXoAY0Xt00f:b-89a4l7) ([raw file](https://github.com/cockroachdb/docs/blob/23a5d38bda54611bc49489aadfa0077bf1ba16ac/_config_base.yml#L96)):*
> ```YAML
>     docker_image: cockroachdb/cockroach-unstable
>     name: v22.1.0-alpha.1
>     start_time: 2022-18-01 11:01:26.34274101 +0000 UTC
> ```

Ditto
___
*[releases/v22.1.0-alpha.1.md, line 36 at r1](https://reviewable.io/reviews/cockroachdb/docs/12726#-MtJlLln1c8VJLpDbVxT:-MtJlLln1c8VJLpDbVxU:b-csdgku) ([raw file](https://github.com/cockroachdb/docs/blob/23a5d38bda54611bc49489aadfa0077bf1ba16ac/releases/v22.1.0-alpha.1.md#L36)):*
> ```Markdown
> ### Backward-incompatible changes
> 
> - Using [`SESSION_USER`](../{{site.versions["stable"]}}/functions-and-operators.html#special-syntax-forms) in a projection or `WHERE` clause now returns the `SESSION_USER` instead of the `CURRENT_USER`. For backwards compatibility, use [`session_user()`](../{{site.versions["stable"]}}/functions-and-operators.html#system-info-functions) for `SESSION_USER` and `current_user()` for `CURRENT_USER`. [#70444][#70444]
> ```

I assume this is here to direct readers to `v21.2` until `v22.1` is released, and subsequently to link to `v22.1`. Do we think it's an issue that these release notes will go to newer versions post-`v22.1`? Not sure if we've specified guidelines around this, and can't remember what I did before!



_Code quote:_
```Markdown
../{{site.versions["stable"]}}
```
___
*[releases/v22.1.0-alpha.1.md, line 36 at r1](https://reviewable.io/reviews/cockroachdb/docs/12726#-MtJm0sH4cOlxPii5l5z:-MtJm0sH4cOlxPii5l6-:b-ivlfax) ([raw file](https://github.com/cockroachdb/docs/blob/23a5d38bda54611bc49489aadfa0077bf1ba16ac/releases/v22.1.0-alpha.1.md#L36)):*
> ```Markdown
> ### Backward-incompatible changes
> 
> - Using [`SESSION_USER`](../{{site.versions["stable"]}}/functions-and-operators.html#special-syntax-forms) in a projection or `WHERE` clause now returns the `SESSION_USER` instead of the `CURRENT_USER`. For backwards compatibility, use [`session_user()`](../{{site.versions["stable"]}}/functions-and-operators.html#system-info-functions) for `SESSION_USER` and `current_user()` for `CURRENT_USER`. [#70444][#70444]
> ```

Nit: "backward" compatibility



_Code quote:_
```Markdown
backwards compatibility
```
___
*[releases/v22.1.0-alpha.1.md, line 37 at r1](https://reviewable.io/reviews/cockroachdb/docs/12726#-MtJm7898DhVlrHIYCAk:-MtJm7898DhVlrHIYCAl:b-dcjpr8) ([raw file](https://github.com/cockroachdb/docs/blob/23a5d38bda54611bc49489aadfa0077bf1ba16ac/releases/v22.1.0-alpha.1.md#L37)):*
> ```Markdown
> 
> - Using [`SESSION_USER`](../{{site.versions["stable"]}}/functions-and-operators.html#special-syntax-forms) in a projection or `WHERE` clause now returns the `SESSION_USER` instead of the `CURRENT_USER`. For backwards compatibility, use [`session_user()`](../{{site.versions["stable"]}}/functions-and-operators.html#system-info-functions) for `SESSION_USER` and `current_user()` for `CURRENT_USER`. [#70444][#70444]
> - Placeholder values (e.g. `$1`) can no longer be used for [role](../{{site.versions["stable"]}}/authorization.html#roles) names in [`ALTER ROLE`](../{{site.versions["stable"]}}/alter-role.html) statements or for role names in [`CREATE ROLE`](../{{site.versions["stable"]}}/create-role.html)/[`DROP ROLE`](../{{site.versions["stable"]}}/drop-role.html) statements. [#71498][#71498]
> ```

Nit: add comma



_Code quote:_
```Markdown
e.g.
```
___
*[releases/v22.1.0-alpha.1.md, line 41 at r1](https://reviewable.io/reviews/cockroachdb/docs/12726#-MtJmERwEQLDj44PkAfn:-MtJmERwEQLDj44PkAfo:b-74g122) ([raw file](https://github.com/cockroachdb/docs/blob/23a5d38bda54611bc49489aadfa0077bf1ba16ac/releases/v22.1.0-alpha.1.md#L41)):*
> ```Markdown
> ### Security updates
> 
> - Authenticated HTTP requests to nodes can now contain additional cookies with the same name as the one we use ("session"). Duplicates like this are permitted by the HTTP spec and will now attempt to parse all cookies with a matching name before giving up. This can resolve issues with customers who run other services on the same domain as their CockroachDB nodes. [#70792][#70792]
> ```

Is "we" CockroachDB? It might be good to spell this out. 

For the rest, I suggest:

The HTTP spec permits duplicates and will now attempt to parse all cookies with a matching name before giving up. This can resolve issues with running other services on the same domain as your CockroachDB nodes.



_Code quote:_
```Markdown
we
```
___
*[releases/v22.1.0-alpha.1.md, line 42 at r1](https://reviewable.io/reviews/cockroachdb/docs/12726#-MtJnWL5BE4m-FJCE6sC:-MtJnWL6CII_HdTZcOmA:be0ec0a) ([raw file](https://github.com/cockroachdb/docs/blob/23a5d38bda54611bc49489aadfa0077bf1ba16ac/releases/v22.1.0-alpha.1.md#L42)):*
> ```Markdown
> 
> - Authenticated HTTP requests to nodes can now contain additional cookies with the same name as the one we use ("session"). Duplicates like this are permitted by the HTTP spec and will now attempt to parse all cookies with a matching name before giving up. This can resolve issues with customers who run other services on the same domain as their CockroachDB nodes. [#70792][#70792]
> - Added a new flag `--external-io-enable-non-admin-implicit-access` that can remove the admin-only restriction on interacting with arbitrary network endpoints and using `implicit` auth in operations such as [`BACKUP`](../{{site.versions["stable"]}}/backup.html), [`IMPORT`](../{{site.versions["stable"]}}/import.html), or [`EXPORT`](../{{site.versions["stable"]}}/export.html). [#71594][#71594]
> ```

I think this needs code backticks, and also a link to the `admin` role docs.



_Code quote:_
```Markdown
admin
```
___
*[releases/v22.1.0-alpha.1.md, line 43 at r1](https://reviewable.io/reviews/cockroachdb/docs/12726#-MtJnjR41AA9rNX6EWzs:-MtJnjR41AA9rNX6EWzt:bpcn3x) ([raw file](https://github.com/cockroachdb/docs/blob/23a5d38bda54611bc49489aadfa0077bf1ba16ac/releases/v22.1.0-alpha.1.md#L43)):*
> ```Markdown
> - Authenticated HTTP requests to nodes can now contain additional cookies with the same name as the one we use ("session"). Duplicates like this are permitted by the HTTP spec and will now attempt to parse all cookies with a matching name before giving up. This can resolve issues with customers who run other services on the same domain as their CockroachDB nodes. [#70792][#70792]
> - Added a new flag `--external-io-enable-non-admin-implicit-access` that can remove the admin-only restriction on interacting with arbitrary network endpoints and using `implicit` auth in operations such as [`BACKUP`](../{{site.versions["stable"]}}/backup.html), [`IMPORT`](../{{site.versions["stable"]}}/import.html), or [`EXPORT`](../{{site.versions["stable"]}}/export.html). [#71594][#71594]
> - For context, when configuring passwords for SQL users, if the client presents the password in cleartext via `ALTER`/`CREATE USER`/`ROLE WITH PASSWORD`, CockroachDB is responsible for hashing this password before storing it. By default, this ha [...]

2022-01-14 15:32 UTC, kathancox commented
Hey @taroface, I have implemented your feedback — thanks so much! If you could do a quick eyeball over some of the formatting nits and such that would be great.

2022-01-14 17:30 UTC, taroface approved these changes
Formatting LGTM!

2022-01-18 17:50 UTC, kathancox commented
@kathancox Updates to date will be necessary when pub date is released!

2022-01-24 20:10 UTC, merged