Remove "improved", above/below for accessibility, capitalization, verb, POV  conformance.
cockroachdb/docs pull request #12767
Opened 2022-01-19 22:05 UTC by stbof

https://cockroachlabs.atlassian.net/browse/DOC-1166

2022-01-19 22:06 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/12767)
<!-- Reviewable:end -->

2022-01-26 20:00 UTC, rmloveland requested changes
98% LGTM, except:

- In a couple places, I think the edits are not strictly style but cross into removing / changing content
- Everywhere this PR says singular "CockroachDB multiregion capabilities" it should use the plural "CockroachDB's multiregion capabilities"

2022-01-26 20:02 UTC, rmloveland commented
meta comment: I think when the style team meets we should talk about PR size.  IMO PRs like this that are large and do multiple "things" (headings and some punctuation and page titles and ..) should ideally be broken up.  The review is kinda tedious for human brains to look at a bunch of strictly style edits (esp. that touch multiple points from the style guide) and it's easy to miss stuff.  Just, like, my opinion of course, but I look forward to discussing with y'all when we convene

2022-01-26 20:05 UTC, stbof commented
> meta comment: I think when the style team meets we should talk about PR size. IMO PRs like this that are large and do multiple "things" (headings and some punctuation and page titles and ..) should ideally be broken up. The review is kinda tedious for human brains to look at a bunch of strictly style edits (esp. that touch multiple points from the style guide) and it's easy to miss stuff. Just, like, my opinion of course, but I look forward to discussing with y'all when we convene

Agreed. I got carried away.

2022-01-26 20:09 UTC, stbof commented on _includes/v21.2/topology-patterns/multiregion-fundamentals.md
> +For more information about CockroachDB multi-region capabilities, review the following pages:
I think what I wrote is correct and I'm not a fan of making describing every feature of any technology in possessive terms.  It anthropomorphizes the technology. Perhaps the Style team should take this up.

2022-01-26 20:53 UTC, stbof commented
> 98% LGTM, except:
> 
> * In a couple places, I think the edits are not strictly style but cross into removing / changing content
> * Everywhere this PR says singular "CockroachDB multiregion capabilities" it should use the plural "CockroachDB's multiregion capabilities"

That's not plural, that's possessive. I don't think possessive is appropriate, but I think the Style team should decide.

2022-01-26 21:04 UTC, stbof commented on v21.2/multiregion-overview.md
> +CockroachDB multi-region capabilities make it easier to run global applications. To take advantage of these capabilities, you should understand the following concepts:
I created this: https://cockroachlabs.atlassian.net/browse/DOC-2433

2022-01-26 21:06 UTC, stbof commented on v21.2/multiregion-overview.md
> +cockroach start --locality=region=us-east-1 # ... other required flags go here
I found it confusing that while this section has the heading **Cluster regions** it defines both regions and zones and includes the zone in the example. Would it make sense to change the heading and then restore the zone info?

2022-01-26 21:07 UTC, stbof commented on v21.2/multiregion-overview.md
> +Regardless of table locality, you can access all data in a multi-region database with low latency from any [database region](#database-regions) by using stale [(follower)](follower-reads.html) reads.
Agreed. I found the first version hard to parse and my rewrite also failed. I'll try again.

2022-01-26 21:21 UTC, rmloveland commented
Stephanie Bodoff ***@***.***> writes:

> @stbof commented on this pull request.
>
> ----------------------------------------------------------------------
>
> In v21.2/multiregion-overview.md:
>
>>  
> -To take advantage of these improved capabilities, you will need to understand the following concepts:
> +CockroachDB multi-region capabilities make it easier to run global applications. To take advantage of these capabilities, you should understand the following concepts:
>
> I created this: https://cockroachlabs.atlassian.net/browse/DOC-2433

Works for me, thanks for making the issue

2022-01-26 21:22 UTC, rmloveland commented
Stephanie Bodoff ***@***.***> writes:

> @stbof commented on this pull request.
>
> ----------------------------------------------------------------------
>
> In _includes/v21.2/topology-patterns/multiregion-fundamentals.md:
>
>>  
> -For more information about our multi-region capabilities, review the following pages:
> +For more information about CockroachDB multi-region capabilities, review the following pages:
>
> I think what I wrote is correct and I'm not a fan of making describing
> every feature of any technology in possessive terms. It
> anthropomorphizes the technology. Perhaps the Style team should take
> this up.

Fair enough - it just "sounds" off to me to say "CockroachDB Feature X"
singular but maybe it's not.  Happy to discuss with the team

2022-01-26 21:27 UTC, rmloveland commented
Stephanie Bodoff ***@***.***> writes:

> @stbof commented on this pull request.
>
> ----------------------------------------------------------------------
>
> In v21.2/multiregion-overview.md:
>
>>  
>  {% include copy-clipboard.html %}
>  ~~~ shell
> -cockroach start --locality=region=us-east-1,zone=us-east-1b # ... other required flags go here
> +cockroach start --locality=region=us-east-1 # ... other required flags go here
>
> I found it confusing that while this section has the heading Cluster
> regions it defines both regions and zones and includes the zone in the
> example. Would it make sense to change the heading and then restore
> the zone info?

I'm sure this could be improved (like, for sure), but if this is a
style PR I don't think we should be opportunistically changing stuff
that isn't strictly style and that already had technical review.  Adding
a zone as well as a region is def normal and expected here, but I'm sure
we could update this to do a better job in future.  I just don't think
this PR is where to do it.

FWIW we do say "Regions and zones are defined at the node level: ..."
which is something of an intro to this topic

2022-01-26 21:31 UTC, rmloveland commented
Stephanie Bodoff ***@***.***> writes:

> @stbof commented on this pull request.
>
> ----------------------------------------------------------------------
>
> In v21.2/multiregion-overview.md:
>
>>  
>  {{site.data.alerts.callout_info}}
> -Table locality settings are used for optimizing latency under different read/write patterns. If you are optimizing for read/write access to all of your tables from a single region (the primary region), there is nothing else you need to do once you set your [database's primary region](#database-regions).
> +Regardless of table locality, you can access all data in a multi-region database with low latency from any [database region](#database-regions) by using stale [(follower)](follower-reads.html) reads.
>
> Agreed. I found the first version hard to parse and my rewrite also
> failed. I'll try again.

Hey that's totally fair re: hard to parse, I bet there's a lot of
opportunity for rewriting stuff like this across our whole doc set.  We
often use too many words, too awkwardly - esp in v1 of a doc

I think my only objection was removing some of the content (IIRC the
first sentence was removed) - would totes understand if you wanted to
kill the uses of "thing/other thing" in here, which I know we're moving
away from

2022-01-26 21:33 UTC, stbof commented
> Stephanie Bodoff ***@***.***> writes:
> @stbof commented on this pull request. ---------------------------------------------------------------------- In v21.2/multiregion-overview.md: > {% include copy-clipboard.html %} ~~~ shell -cockroach start --locality=region=us-east-1,zone=us-east-1b # ... other required flags go here +cockroach start --locality=region=us-east-1 # ... other required flags go here I found it confusing that while this section has the heading Cluster regions it defines both regions and zones and includes the zone in the example. Would it make sense to change the heading and then restore the zone info?
> I'm sure this could be improved (like, for sure), but if this is a style PR I don't think we should be opportunistically changing stuff that isn't strictly style and that already had technical review. Adding a zone as well as a region is def normal and expected here, but I'm sure we could update this to do a better job in future. I just don't think this PR is where to do it. FWIW we do say "Regions and zones are defined at the node level: ..." which is something of an intro to this topic

Agreed. Sorry for overstepping.

2022-01-26 21:33 UTC, stbof commented
> Stephanie Bodoff ***@***.***> writes:
> @stbof commented on this pull request. ---------------------------------------------------------------------- In v21.2/multiregion-overview.md: > {{site.data.alerts.callout_info}} -Table locality settings are used for optimizing latency under different read/write patterns. If you are optimizing for read/write access to all of your tables from a single region (the primary region), there is nothing else you need to do once you set your [database's primary region](#database-regions). +Regardless of table locality, you can access all data in a multi-region database with low latency from any [database region](#database-regions) by using stale [(follower)](follower-reads.html) reads. Agreed. I found the first version hard to parse and my rewrite also failed. I'll try again.
> Hey that's totally fair re: hard to parse, I bet there's a lot of opportunity for rewriting stuff like this across our whole doc set. We often use too many words, too awkwardly - esp in v1 of a doc I think my only objection was removing some of the content (IIRC the first sentence was removed) - would totes understand if you wanted to kill the uses of "thing/other thing" in here, which I know we're moving away from

Agreed. Will restore as it was.

2022-01-26 21:48 UTC, stbof commented on v21.2/data-domiciling.md
> +CockroachDB has basic support for data domiciling in multi-region clusters using the process described in this page. At a high level, this process involves:
Fixed.

2022-01-26 21:48 UTC, stbof commented on v21.2/multiregion-overview.md
> +cockroach start --locality=region=us-east-1 # ... other required flags go here
Fixed.

2022-01-26 21:48 UTC, stbof commented on v21.2/multiregion-overview.md
> -{{site.data.alerts.callout_info}}
Fixed.

2022-01-26 21:48 UTC, stbof commented on v21.2/multiregion-overview.md
> +Regardless of table locality, you can access all data in a multi-region database with low latency from any [database region](#database-regions) by using stale [(follower)](follower-reads.html) reads.
Fixed.

2022-01-26 21:48 UTC, stbof commented on v21.2/partitioning.md
>  #### Partition using secondary index
Fixed.

2022-01-27 16:14 UTC, stbof commented on _includes/v21.2/topology-patterns/multiregion-fundamentals.md
> +For more information about CockroachDB multi-region capabilities, review the following pages:
Also, CockroachDB's is a trademark violation (see https://cockroachlabs.atlassian.net/browse/DOC-2433).

2022-02-01 22:29 UTC, rmloveland commented on _includes/v21.2/topology-patterns/multiregion-fundamentals.md
> +For more information about CockroachDB multi-region capabilities, review the following pages:
hey this seems like a good argument, but also not one I'm really qualified to assess.  happy to go with your version for now and let style team figure it out going forward

2022-02-01 22:31 UTC, rmloveland approved these changes
LGTM - thanks for making all these improvements!  Looking forward to internalizing more of these style guidelines going forward

2022-02-01 22:47 UTC, merged