Cloud release notes February
cockroachdb/docs pull request #12874
Opened 2022-01-28 16:35 UTC by gemma-shay

https://cockroachlabs.atlassian.net/browse/DOC-2239

2022-01-28 16:35 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/12874)
<!-- Reviewable:end -->

2022-01-28 16:41 UTC, jramos-crl commented
@gemma-shay this is set to go live on Feb 7, it looks like? If so, we should have the decoupled UI released by then if you want to include a line for it.

2022-01-28 16:43 UTC, thtruo reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12874)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay, @jramos-crl, and @kevin-v-ngo)

___
*[releases/cloud.md, line 20 at r1](https://reviewable.io/reviews/cockroachdb/docs/12874#-MuWZ8E7ENkfV80mVxJm:-MuWZ8E7ENkfV80mVxJn:blx5kqj) ([raw file](https://github.com/cockroachdb/docs/blob/559918e2c7005d41cdce9e6ceef828377f337091/releases/cloud.md#L20)):*
> ```Markdown
> ## February 7, 2022
> 
> <h3>Console changes</h3>
> ```

@gemma-shay Do we have a policy around whether or not to announce beta functionality? FWIW we just made the Datadog metrics integration available for select customers. It's behind a feature flag. Interested customers can request to be put on the beta.



_Code quote:_
```Markdown
Console changes
```


<!-- Sent from Reviewable.io -->

2022-01-28 18:26 UTC, gemma-shay commented
@thtruo Up to you! I usually wouldn't document it until it's fully available, but if you're looking for more beta users I think it could be helpful to make a note.

2022-01-28 18:29 UTC, gemma-shay commented
@jramos-crl What's our best guess eta? If it's early this coming week, I was thinking of giving decoupled hardware its own release note. Working on changing the protocol here so major feature flags don't have to wait for monthly notes.

2022-01-28 19:09 UTC, jramos-crl commented
@gemma-shay it will probably be mid-next week or so at this point. That's a good call regarding having its own release notes. Let's do that then 👍

2022-01-28 19:18 UTC, thtruo commented
Ack that makes sense @gemma-shay in this case, no need to mention the beta version of this for the Feb release.

2022-01-31 06:01 UTC, kevin-v-ngo approved these changes

2022-02-04 21:50 UTC, gemma-shay commented
Hi @emily-horing, adding you because I just saw that new regions were added for Serverless. @ianjevans do you mind doing a quick review of the regions addition as well?

2022-02-05 00:10 UTC, ianjevans requested changes

2022-02-05 00:10 UTC, ianjevans commented on releases/cloud.md
> +- The [**Terminate session** and **Terminate Statement**](../cockroachcloud/sessions-page.html#sessions-list) options are now enabled for {{ site.data.products.db }} clusters running CockroachDB [v21
```suggestion
- The [**Terminate Session** and **Terminate Statement**](../cockroachcloud/sessions-page.html#sessions-list) options are now enabled for {{ site.data.products.db }} clusters running CockroachDB [v21.2.2](v21.2.2.html) or later.
```

2022-02-05 00:10 UTC, ianjevans commented on releases/cloud.md
> +- Selecting a transaction from the [**Transactions** page](../cockroachcloud/transactions-page.html) now opens a new [**Transaction details**](../cockroachcloud/transactions-page.html#transaction-det
```suggestion
- Selecting a transaction from the [**Transactions** page](../cockroachcloud/transactions-page.html) now opens a new [**Transaction Details**](../cockroachcloud/transactions-page.html#transaction-details-page) page with an improved design.
```

2022-02-07 17:27 UTC, emily-horing reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12874)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @jramos-crl)

___
*[releases/cloud.md, line 20 at r1](https://reviewable.io/reviews/cockroachdb/docs/12874#-MuWZ8E7ENkfV80mVxJm:-MvKDEQN2TO1_fHXf8bG:b87t5z5) ([raw file](https://github.com/cockroachdb/docs/blob/559918e2c7005d41cdce9e6ceef828377f337091/releases/cloud.md#L20)):*
<details><summary><i>Previously, thtruo (Tommy) wrote…</i></summary><blockquote>

@gemma-shay Do we have a policy around whether or not to announce beta functionality? FWIW we just made the Datadog metrics integration available for select customers. It's behind a feature flag. Interested customers can request to be put on the beta.
</blockquote></details>

cc @thtruo for datadog specifically. In general I think it's a nice way to preview functionality and get more possible beta testers to announce closed betas in notes. just my 2 cents.


<!-- Sent from Reviewable.io -->

2022-02-07 17:28 UTC, emily-horing approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12874#-:-MvKDbVy7Z9BcCYonQm9:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @gemma-shay and @jramos-crl)



<!-- Sent from Reviewable.io -->

2022-02-07 19:52 UTC, gemma-shay commented
@emily-horing @thtruo Ack, I'm going to merge this and follow up with Tommy about adding a Datadog note.

2022-02-07 19:52 UTC, merged

2022-02-07 20:08 UTC, thtruo commented
Had a followup convo with @gemma-shay - I'm cool if we exclude Datadog in the release note and instead make a mention of it in the marketing emails that go out calling for beta testers

2022-02-08 19:21 UTC, emily-horing commented
I'm just realizing (too late) that we seem to have excluded a note about faster perf for autogenerated passwords and the option to autogenerate passwords from the SQL user creation form. Unless that was covered in the prior notes? I thought it was a Jan change though. cc @JeffSwenson