Feature auth config hba docs 422
cockroachdb/docs pull request #13037
Opened 2022-02-15 21:06 UTC by MichaelTrestman

This delta reorganizes the security docs and adds several new pages, and aims to address DOCS-2559, DOCS-422, DOCS-458, DOCS-958.

The primary purpose of the reorganization is to properly separate descriptive specification-type docs from procedural 'how to do X' type docs. Previously most of the security docs, descriptive and procedural, are all together under the 'manage' header.

This PR adds a navigation header: Reference / Security, under which there is now a new 'Security Reference Overview Page', which specifies security features of the core release and compares features supported by paid products.

The Reference / Security section now also contains new pages for conceptual 'domains' of security concern, which I have broken down into Authentication, Authorization, Network Security, Encryption, and Availability/Resilience (loosely corresponding to the STRIDE model of security threats). I have not added a reference page for the last of these, but I would like to, offering a descriptive breakdown of the features of CockroachDB which specifically contribute to resilience in the face of attacks and disruptions (the fundamentally distributed nature of the db), but this requires thought so I'm creating a separate ticket

The PR also updates references to TLS, as we now support TLS 1.2 or 1.3 for client-node authentication.

2022-02-15 21:07 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/13037)
<!-- Reviewable:end -->

2022-02-16 15:13 UTC, MichaelTrestman commented
the build is currently failing until I fix all links pointing into the relocated content. in the meantime you can preview the changes here: http://34.134.119.235:4000/docs/stable/security-reference/security-overview.html

2022-02-17 16:35 UTC, knz reviewed
Very nice step forward. I do like the consolidation and the new "overview" page a lot.

One thing that made me raise an eyebrow is that this draft is silent about self-hosted cockroachdb, which still has interesting security controls that deserves to be documented. Was that an intentional choice?

> Reviewed 184 of 184 files at r1, 21 of 21 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13037#-:-Mw7XAL22uwX6-k8ZQbv:b-ynl3np)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess and @MichaelTrestman)

___
*[v20.1/import-into.md, line 18 at r1](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mw7MFb9EitljC4EZvKD:-Mw7MFbA-KwBO-ryzE1s:b-dmjljn) ([raw file](https://github.com/cockroachdb/docs/blob/345a8fc0db869a373d10617e7349ff00bac4cff3/v20.1/import-into.md#L18)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> Optimize your applications by following our [Import Performance Best Practices](import-performance-best-practices.html).
> ```

Why do I see changes related to import in this PR?

Is it possible that's because you used `git merge master` into your branch?

At CRL, we prefer to use `git rebase` and ensure the feature branch is always standalone. This clarifies intent during code reviews, by ensuring the review doesn't contain items from the `master` branch that are not relevant.
___
*[v21.2/authorization.md, line 6 at r1](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mw7O22m90mIY7Qm_-Mr:-Mw7O22m90mIY7Qm_-Ms:b7ogyj1) ([raw file](https://github.com/cockroachdb/docs/blob/f6b19a89078fd09cfeabdc9de850e81db6da922d/v21.2/authorization.md#L6)):*
> ```Markdown
> toc: true
> docs_area: manage
> ---
> ```

You've removed a lot of content from this page. As a result, there's no more summary at the top of the page to explain the reader what the page is about. Was that intentional?

Also you may want to cross- ref the new pages from here.
___
*[v21.2/encryption.md, line 7 at r1](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mw7OHBW4xdMYO87KV1e:-Mw7OHBW4xdMYO87KV1f:b-wficrq) ([raw file](https://github.com/cockroachdb/docs/blob/f6b19a89078fd09cfeabdc9de850e81db6da922d/v21.2/encryption.md#L7)):*
> ```Markdown
> docs_area: manage
> ---
> ```

You've removed a lot of content from this page. As a result, there's no summary anymore. Also, the first sub-section is now just "Example". Was this intentional?
___
*[v21.2/security-reference/authentication.md, line 7 at r1](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mw7P3DT60B6IJOqmbVN:-Mw7P3DT60B6IJOqmbVO:bq8kopf) ([raw file](https://github.com/cockroachdb/docs/blob/345a8fc0db869a373d10617e7349ff00bac4cff3/v21.2/security-reference/authentication.md#L7)):*
> ```Markdown
> docs_area: reference.security
> ---
> ```

The intro to this page should explain that crdb uses different mechanisms for:
- node-to-node authentication
- admin CLI-to-node authentication
- SQL-to-node authentication
- web browser-to-node authentication

The mechanisms you've explained below so far are focused on SQL client authentication. We also want to talk about the others. Either on this page or sister pages. In any case, the navigation between these topics should be clarified.
___
*[v21.2/security-reference/authentication.md, line 34 at r1](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mw7PgOn7tSfocp_Jkos:-Mw7PgOn7tSfocp_Jkot:b-sqw9e5) ([raw file](https://github.com/cockroachdb/docs/blob/345a8fc0db869a373d10617e7349ff00bac4cff3/v21.2/security-reference/authentication.md#L34)):*
> ```Markdown
> CockroachDB's authentication behavior is configured using a domain specific language (DSL), shared with PostgreSQL, called host-based authentication (HBA).
> 
> A specific CockroachDB cluster's authentication behavior is configured by setting it's `server.host_based_authentication.configuration` cluster setting, which accepts a single text field that must be a correctly formatted HBA manifest.
> ```

nit: its

also, "setting" is repeated.
___
*[v21.2/security-reference/authentication.md, line 36 at r1](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mw7Pbi--IsBbEQ214L5:-Mw7Pbi--IsBbEQ214L6:b-qy1y5u) ([raw file](https://github.com/cockroachdb/docs/blob/345a8fc0db869a373d10617e7349ff00bac4cff3/v21.2/security-reference/authentication.md#L36)):*
> ```Markdown
> A specific CockroachDB cluster's authentication behavior is configured by setting it's `server.host_based_authentication.configuration` cluster setting, which accepts a single text field that must be a correctly formatted HBA manifest.
> 
> See the `show cluster setting` and `set cluster setting` cockroach commands.
> ```

NB: these are not "cockroach commands", they are SQL statements.
You can also add a hyperlink to where they are documented.
___
*[v21.2/security-reference/authentication.md, line 43 at r1](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mw7PnR07dBvfULf6P9i:-Mw7PnR07dBvfULf6P9j:b-4hn7x2) ([raw file](https://github.com/cockroachdb/docs/blob/345a8fc0db869a373d10617e7349ff00bac4cff3/v21.2/security-reference/authentication.md#L43)):*
> ```Markdown
> Lines commented with '#' are ignored.
> 
> For example, the following silly but easy to understand configuration has three rules:
> ```

We typically place examples in separate sections below the reference explanation.
___
*[v21.2/security-reference/authorization.md, line 8 at r1](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mw7Q-sw2Xv7ftNB7c8i:-Mw7Q-sw2Xv7ftNB7c8j:b-opmbwa) ([raw file](https://github.com/cockroachdb/docs/blob/345a8fc0db869a373d10617e7349ff00bac4cff3/v21.2/security-reference/authorization.md#L8)):*
> ```Markdown
> ---
> 
> User authorization is the act of defining access policies for authenticated CockroachDB users. CockroachDB allows you to create, manage, and remove your cluster's SQL [users](#sql-users) and assign SQL-level [privileges](#managing-privileges) to the users. Additionally, you can use [role-based access management (RBAC)](#roles) for simplified user management.
> ```

This intro could explain that we have a unified authorization layer between the web console (and HTTP APIs), and the SQL interface.
This means that we can use a single set of authz rules for both.

(This is different for authentication which uses currently separate mechanisms, as per my comment above).
___
*[v21.2/security-reference/config-secure-hba.md, line 8 at r2](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mw7VqXYAjE4N3puhXLR:-Mw7VqXYAjE4N3puhXLS:bmp19a7) ([raw file](https://github.com/cockroachdb/docs/blob/e0d3ae23cb3a590442454c07cd1a373b9db85212/v21.2/security-reference/config-secure-hba.md#L8)):*
> ```Markdown
> ---
> 
> ## Introduction: Why customize your authentication configuration?
> ```

This page needs a summary paragraph before the first section header. It's also mildly possible that the first paragraph in the first section is an adequate summary for the entire page. I'll let you sort it out.
___
*[v21.2/security-reference/config-secure-hba.md, line 17 at r2](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mw7W6143a5DzX8vtDX4:-Mw7W6143a5DzX8vtDX5:b-cvmmgd) ([raw file](https://github.com/cockroachdb/docs/blob/e0d3ae23cb3a590442454c07cd1a373b9db85212/v21.2/security-reference/config-secure-hba.md#L17)):*
> ```Markdown
> Using Cockroach Labs' hosted CockroachDB offerings, whether Serverless or Dedicated, affords industry standard security controls at the network and infrastructure levels, and savvy users can self-deploy CockroachDB with any measure of network security they might desire. Nevertheless, a hardened authentication configuration offers a powerful measure of [security in depth](https://en.wikipedia.org/wiki/Defense_in_depth_(computing)). 
> 
> Moreover, because the only authentication method currently available for CockroachDB hosted products is username/password (which is the weakest authentication method in terms of security), limiting allowed database connections to secure IP addr [...]

2022-02-24 20:23 UTC, jseldess reviewed
Love these changes overall, Michael! Thank you! 

General comment: I'm not sure if we want to add a `security-reference` subdirectory. In most cases, we stay flat. I'm ok moving to this approach, but we shouldn't do it without discussing with the broader team. For now, I think I'd prefer not doing this. I think you're doing this because there are existing pages with the same names. If so, perhaps we can consider renaming those instructional pages to be more action-oriented? That would mean more redirects and link updates, though.

Once you've address Raphael and my comments, I think it'd be great to get @taroface to do a thorough content review as well. Ryan, you up for that?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13037#-:-MwhMdt0DMQqgfmlZqP-:b6p0l0r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess, @knz, and @MichaelTrestman)

___
*[cockroachcloud/console-access-management.md, line 25 at r9](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwhK--EB_6CoxMOixAd:-MwhK--EB_6CoxMOixAe:b37ru0l) ([raw file](https://github.com/cockroachdb/docs/blob/671c88b1f89ba4b33fc1f06cee7af03ed015eab3/cockroachcloud/console-access-management.md#L25)):*
nits: In terms of tone, I think we should aim for slightly more common diction. Can we find another way to say "is expedient"? Maybe "is fast and easy"? I actually think we can be more direct and say something like:

>For this reason, users should generally be created from the SQL client instead, and have their database resource access granted... 
___
*[cockroachcloud/frequently-asked-questions.md, line 65 at r9](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwhM02T45mgRXSuq-qr:-MwhM02T45mgRXSuq-qs:bd505xn) ([raw file](https://github.com/cockroachdb/docs/blob/671c88b1f89ba4b33fc1f06cee7af03ed015eab3/cockroachcloud/frequently-asked-questions.md#L65)):*
> ```Markdown
> ### Is encryption-at-rest enabled on {{ site.data.products.dedicated }}?
> 
> All data in Cockroach Labs' hosted CockroachDB cloud services, whether Serverless or Dedicated is encrypted-at-rest by your chosen infrastructre-as-a-service provider, Google Cloud Platform (GCP) or Amazon Web Services (AWS), at the infrastructure level.
> ```

Need closing comma for `whether Serverless or Dedicated`.
___
*[v21.2/authorization.md, line 6 at r1](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mw7O22m90mIY7Qm_-Mr:-MwhNSDH06_ywuZ4KLrc:b-vip4mx) ([raw file](https://github.com/cockroachdb/docs/blob/f6b19a89078fd09cfeabdc9de850e81db6da922d/v21.2/authorization.md#L6)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

No large chunks of content has been deleted. Stuff that was deleted from the old Authorization and Encryption pages was moved to the corresponding pages in the new Reference / Security section.
</blockquote></details>

I like this overall approach a lot. But can you think of ways to reference the conceptual docs from the instructional, and vice versa?
___
*[v21.2/encryption.md, line 7 at r1](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mw7OHBW4xdMYO87KV1e:-MwhNkRQ60EqsHaTU1-w:bpc3bo1) ([raw file](https://github.com/cockroachdb/docs/blob/f6b19a89078fd09cfeabdc9de850e81db6da922d/v21.2/encryption.md#L7)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

It's been cleaned up a bit. The intent is just to have procedures here; the section now being called "managing encryption...' where the new section is the encryption reference page.
</blockquote></details>

Again, I like this overall approach a lot. But can you think of ways to reference the conceptual docs from the instructional, and vice versa?


<!-- Sent from Reviewable.io -->

2022-02-24 20:51 UTC, taroface commented
> Once you've address Raphael and my comments, I think it'd be great to get @taroface to do a thorough content review as well. Ryan, you up for that?

Yep, feel free to add me as a reviewer when ready @MichaelTrestman

2022-02-27 14:20 UTC, knz reviewed
Thanks for this new iteration. I have a few more comments, in addition to some of my earlier comments which were not addressed yet.

> Reviewed 1 of 42 files at r3, 161 of 168 files at r6, 5 of 8 files at r7, 1 of 2 files at r8, 3 of 4 files at r9, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13037#-:-MwvYMNF4AnAv-VEkVQk:bl4ez3g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @MichaelTrestman and @taroface)

___
*[_includes/common/ui/sessions-page.md, line 38 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvTMk_2oiAK7-IrcZA:-MwvTMk_2oiAK7-IrcZB:b-nbn112) ([raw file](https://github.com/cockroachdb/docs/blob/a81b9d435dbd0589c79ce2b9766354b7aea2ce7e/_includes/common/ui/sessions-page.md#L38)):*
> ```Markdown
> Memory Usage | Amount of memory currently allocated to this session, followed by the maximum amount of memory this session has ever been allocated.
> Statement | Active SQL statement. If more than one statement is active, the most recent statement is shown.
> Actions | Options to terminate the active query and/or terminate the session. These require the [`CANCELQUERY` role option]({{ link_prefix }}authorization.html#create-and-manage-users).<br><br>**Terminate Statement:** Ends the SQL statement. The session running this statement will receive an error.<br><br>**Terminate Session:** Ends the session. The client that holds this session will receive a "connection terminated" event.
> ```

What was the rationale for removing the hyperlink?
___
*[_includes/v21.1/backups/destination-file-privileges.md, line 1 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvTDziCU2Rag1zjpoi:-MwvTDziCU2Rag1zjpoj:bgmv92v) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/_includes/v21.1/backups/destination-file-privileges.md#L1)):*
> ```Markdown
> The destination file URL does _not_ require the `ADMIN` role in the following scenarios:
> ```

`admin` should not be capitalized here.

Also, did you intend to remove the hyperlink here?
___
*[_includes/v21.1/misc/source-privileges.md, line 1 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvTQMS1-NCQHsjlcJd:-MwvTQMS1-NCQHsjlcJe:b5rk4pw) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/_includes/v21.1/misc/source-privileges.md#L1)):*
> ```Markdown
> The source file URL does _not_ require the `ADMIN` role in the following scenarios:
> ```

`admin` should not be capitalized.

Also, why remove the hyperlink?
___
*[cockroachcloud/console-access-management.md, line 25 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvTdbT1OU-K5ek5rbZ:-MwvTdbU1Ld8zVi8s9yT:b-x57mau) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/cockroachcloud/console-access-management.md#L25)):*
> ```Markdown
> SQL users created in the Console have admin privileges on the cluster by default, even if the user has [Developer](#developer) privileges for the organization. Therefore, anyone with the username and password of a default SQL user has privileges for all resources across the cluster.
> 
> For this reason, while creating SQL users in the Console is expedient it is also dangerously powerful, and on clusters with any data of value, users should generally be be [created](../{{site.versions["stable"]}}/create-user.html) from the SQL client instead, and have their database resource access granted explicitly, precisely, and in keeping with the [principle of least privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege).
> ```

Maybe also add a note this is a known limitation of the CC console and that we aim to address this in a later version of CC.
___
*[cockroachcloud/console-access-management.md, line 27 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvTj5mEs8IvVOWqd23:-MwvTj5mEs8IvVOWqd24:b-ulwwb9) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/cockroachcloud/console-access-management.md#L27)):*
> ```Markdown
> For this reason, while creating SQL users in the Console is expedient it is also dangerously powerful, and on clusters with any data of value, users should generally be be [created](../{{site.versions["stable"]}}/create-user.html) from the SQL client instead, and have their database resource access granted explicitly, precisely, and in keeping with the [principle of least privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege).
> 
> Managing SQL users' privileges requires the [`role admin` role ](../{{site.versions["stable"]}}/security-reference/authorization.html#role-admin).
> ```

There is no such thing as "role admin role". What did you intend to say?
___
*[cockroachcloud/frequently-asked-questions.md, line 68 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvTy9E9tJervGtl8B8:-MwvTy9E9tJervGtl8B9:b-zhb6or) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/cockroachcloud/frequently-asked-questions.md#L68)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> CockroachDB Serverless and Dedicated cloud offerings delegate responsibility for encryption-at-rest to the cloud provider. Hence, CockroachDB's propriety storage-layer encryption-at-rest functionality is currently only available for CockroachDB Self-Hosted Enterprise customers, and is not currently available to users of CockroachDB Serverless or Dedicated .
> ```

propriety -> proprietary
___
*[cockroachcloud/frequently-asked-questions.md, line 68 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvU0Rd8i-RhG85boIL:-MwvU0Rd8i-RhG85boIM:b-eivw9e) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/cockroachcloud/frequently-asked-questions.md#L68)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> CockroachDB Serverless and Dedicated cloud offerings delegate responsibility for encryption-at-rest to the cloud provider. Hence, CockroachDB's propriety storage-layer encryption-at-rest functionality is currently only available for CockroachDB Self-Hosted Enterprise customers, and is not currently available to users of CockroachDB Serverless or Dedicated .
> ```

nit: space before period at end.
___
*[releases/v22.1.0-alpha.1.md, line 41 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvU9gN6__KuTKdS5Hn:-MwvU9gN6__KuTKdS5Ho:bmovrx) ([raw file](https://github.com/cockroachdb/docs/blob/a81b9d435dbd0589c79ce2b9766354b7aea2ce7e/releases/v22.1.0-alpha.1.md#L41)):*
> ```Markdown
> 
> - Using [`SESSION_USER`](../{{site.versions["dev"]}}/functions-and-operators.html#special-syntax-forms) in a projection or `WHERE` clause now returns the `SESSION_USER` instead of the `CURRENT_USER`. For backward compatibility, use [`session_user()`](../{{site.versions["dev"]}}/functions-and-operators.html#system-info-functions) for `SESSION_USER` and `current_user()` for `CURRENT_USER`. [#70444][#70444]
> - Placeholder values (e.g., `$1`) can no longer be used for [role](../{{site.versions["dev"]}}/authorization.html#roles) names in [`ALTER ROLE`](../{{site.versions["dev"]}}/alter-role.html) statements or for role names in [`CREATE ROLE`](../{{site.versions["dev"]}}/create-role.html)/[`DROP ROLE`](../{{site.versions["dev"]}}/drop-role.html) statements. [#71498][#71498]
> ```

here and below, did you intend to remove these hyperlinks?
___
*[v21.2/authorization.md, line 8 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvUNZsAEtunZb7x7rt:-MwvUNZsAEtunZb7x7ru:b-pxc43r) ([raw file](https://github.com/cockroachdb/docs/blob/a81b9d435dbd0589c79ce2b9766354b7aea2ce7e/v21.2/authorization.md#L8)):*
> ```Markdown
> ---
> 
> User authorization is the act of defining access policies for authenticated CockroachDB users. CockroachDB allows you to create, manage, and remove your cluster's SQL [users](#sql-users) and assign SQL-level [priv [...]

2022-02-28 16:51 UTC, MichaelTrestman reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13037)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @MichaelTrestman, and @taroface)

___
*[cockroachcloud/console-access-management.md, line 27 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvTj5mEs8IvVOWqd23:-Mx0EN2DAYntVQjsrTql:bitfxi1) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/cockroachcloud/console-access-management.md#L27)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

There is no such thing as "role admin role". What did you intend to say?
</blockquote></details>

I didn't write this stuff. According to our docs there definitely is such a thing as "role admin role". https://www.cockroachlabs.com/docs/stable/authorization.html#role-admin


<!-- Sent from Reviewable.io -->

2022-02-28 17:01 UTC, MichaelTrestman commented
___
*[cockroachcloud/console-access-management.md, line 27 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvTj5mEs8IvVOWqd23:-Mx0GjA88V7Sp_mQ1hlI:boq4zp5) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/cockroachcloud/console-access-management.md#L27)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

I didn't write this stuff. According to our docs there definitely is such a thing as "role admin role". https://www.cockroachlabs.com/docs/stable/authorization.html#role-admin
</blockquote></details>

whoops never mind, I did write that copy, and misunderstood. fixing it. the admin role /role admin stuff is confusing. 


<!-- Sent from Reviewable.io -->

2022-02-28 17:03 UTC, MichaelTrestman commented
___
*[cockroachcloud/console-access-management.md, line 27 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvTj5mEs8IvVOWqd23:-Mx0Gvtd7ZY06HQXDt8Y:b-kzjhq) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/cockroachcloud/console-access-management.md#L27)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

whoops never mind, I did write that copy, and misunderstood. fixing it. the admin role /role admin stuff is confusing. 
</blockquote></details>

It's very confusing: "A role admin is a member of the role that's allowed to grant or revoke role membership to other users for that specific role." this sure makes it sound like `role admin` is a role, but it is ambiguous. So what is 'role admin' if it's not a role? 


<!-- Sent from Reviewable.io -->

2022-02-28 17:09 UTC, MichaelTrestman reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13037)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess, @knz, @MichaelTrestman, and @taroface)

___
*[cockroachcloud/console-access-management.md, line 25 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvTdbT1OU-K5ek5rbZ:-Mx0ISHY65l1it5aAiFg:bb4n2vp) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/cockroachcloud/console-access-management.md#L25)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Maybe also add a note this is a known limitation of the CC console and that we aim to address this in a later version of CC.
</blockquote></details>

Yes, good point. I meant to ask about this kind of 'forward messaging' about upcoming features. @jseldess @taroface thoughts?


<!-- Sent from Reviewable.io -->

2022-02-28 19:08 UTC, jseldess commented
___
*[cockroachcloud/console-access-management.md, line 25 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvTdbT1OU-K5ek5rbZ:-Mx0iIF9BT-AM0EptnC0:bpl51ny) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/cockroachcloud/console-access-management.md#L25)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

Yes, good point. I meant to ask about this kind of 'forward messaging' about upcoming features. @jseldess @taroface thoughts?
</blockquote></details>

We had a discussion on the docs team around this. We should avoid future-referencing language. However, it's helpful to users to acknowledge limitations. I think you're already doing that here. Perhaps there's an opportunity to use "warning" callout to highlight this more. Otherwise, I think we're ok. 

I think we should open a Jira isue to consider adding a "Known Limitations" doc for the Cloud Console, similar to what we have the DB. @michaeltrestman, can you create that issue? I think the Cloud writers should probably take it, but you can leave it to Lauren and I to route. 


<!-- Sent from Reviewable.io -->

2022-02-28 19:37 UTC, MichaelTrestman reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13037)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @MichaelTrestman, and @taroface)

___
*[cockroachcloud/console-access-management.md, line 27 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvTj5mEs8IvVOWqd23:-Mx0pUjZ7Tthe98-cYat:b-peufeu) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/cockroachcloud/console-access-management.md#L27)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

It's very confusing: "A role admin is a member of the role that's allowed to grant or revoke role membership to other users for that specific role." this sure makes it sound like `role admin` is a role, but it is ambiguous. So what is 'role admin' if it's not a role? 
</blockquote></details>

It'll help when I add role option stuff into the authorization doc https://cockroachlabs.atlassian.net/browse/DOC-2760
___
*[v21.2/security-reference/authorization.md, line 8 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvVzM9AHSggfQq5FRH:-Mx0pGlC-juQDTNeA8a9:bw4ckh9) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/authorization.md#L8)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You're defining "authorization" in general here. Is this your desired summary of what the reader should expect in the rest of this page?

- if yes: then the page is missing an entire section on role options (VIEWACTIVITY, etc), which are separate from privilege but much necessary to fully understand authorization.
- if no: then the summary should be restricted to the scope and identify that role options are documented elsewhere. Perhaps a title change would be useful here (e.g. "Authorization for access to SQL objects")
</blockquote></details>

Adding role options 
https://cockroachlabs.atlassian.net/browse/DOC-2760
___
*[v21.2/security-reference/config-secure-hba.md, line 17 at r2](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mw7W6143a5DzX8vtDX4:-Mx0ViEW2k4in-LL_Q0s:bx4rlfl) ([raw file](https://github.com/cockroachdb/docs/blob/e0d3ae23cb3a590442454c07cd1a373b9db85212/v21.2/security-reference/config-secure-hba.md#L17)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You changed this to "least strong". Comeone could argue that a SCRAM exchange is more secure than a poorly managed TLS CA chain. 

"Strong" is relative to some threat model. What threat model do you have in mind? 

Or are you perhaps trying to recommend a particular security setup to our customers? If that's what you want to do, why not state this explicitly?
</blockquote></details>

I feel that I do recommend a particular security setup to the customer, explicitly, in the same sentence (i.e. limiting database connections to secure IP addresses). no?
___
*[v21.2/security-reference/config-secure-hba.md, line 19 at r2](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mw7WQbg5FzXijNQ7hGR:-Mx0VzP28M5YXSs3Ph23:b-oagh8t) ([raw file](https://github.com/cockroachdb/docs/blob/e0d3ae23cb3a590442454c07cd1a373b9db85212/v21.2/security-reference/config-secure-hba.md#L19)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

- we also use a semaphore inside the product to restrict the amount of attempts per second, which blocks bruteforcing over the network
- for cases where an attacker gets access to the password database, we use hashing and specifically we use a costly hash function so that the hashing is expensive and makes bruteforcing impractical
- we also use salting to block rainbow table attacks

All this might not be documented _yet_, but the first sentence remains nonetheless inaccurate.

I also still stand by my point that "simple" is not an accurate nor useful adjective for the technology being used.
</blockquote></details>

Ok thanks. I removed the word "simple". It looks on cloud I can make at least one password attempt every two seconds (trying every second, every other attempt gets throttled), so maybe I can only make around 4k attempts per day (per user?). That's not being totally vulnerable to raw brute force password cracking, but If I care about my data, I'd still rather not allow that.


<!-- Sent from Reviewable.io -->

2022-02-28 21:07 UTC, MichaelTrestman reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13037)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @MichaelTrestman, and @taroface)

___
*[cockroachcloud/console-access-management.md, line 25 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvTdbT1OU-K5ek5rbZ:-Mx0sPx71uQ7aaQjbEZB:b-uqsd6e) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/cockroachcloud/console-access-management.md#L25)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

We had a discussion on the docs team around this. We should avoid future-referencing language. However, it's helpful to users to acknowledge limitations. I think you're already doing that here. Perhaps there's an opportunity to use "warning" callout to highlight this more. Otherwise, I think we're ok. 

I think we should open a Jira isue to consider adding a "Known Limitations" doc for the Cloud Console, similar to what we have the DB. @michaeltrestman, can you create that issue? I think the Cloud writers should probably take it, but you can leave it to Lauren and I to route. 
</blockquote></details>

Got pretty strong pushback about any kind of forward messaging when I raised this with the docs team.
___
*[v21.2/security-reference/authorization.md, line 8 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvVzM9AHSggfQq5FRH:-Mx198g-2rnMcFt-uukQ:b-7ftxm0) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/authorization.md#L8)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

Adding role options 
https://cockroachlabs.atlassian.net/browse/DOC-2760
</blockquote></details>

Also added a section on Role Options in this page until this can be followed up in the linked ticket.


<!-- Sent from Reviewable.io -->

2022-02-28 21:53 UTC, taroface requested changes
@michaeltrestman I added a bunch of in-line comments, but as I might have missed something, this comment applies to all docs:

- References to "admin" roles or privileges should be written as "`admin` role" and link to the appropriate doc.
- Use our liquid syntax for product names (https://github.com/cockroachdb/docs/blob/master/StyleGuide.md#product-names) wherever possible, to ensure consistency (I think it's only not possible on page titles).
  - Also please ensure the current product names are reflected in the page titles.
- For all ordered/unordered lists, capitalize each item and end it with a period (as here).
- Command snippets should use the copyable syntax so that users can copy-paste them.
- Use Markdown instead of HTML tags unless absolutely necessary.

On `network-security.md`, I'm with @knz in that the purpose of this doc is not clear to me, and could perhaps become part of `security-overview.md`?

I also want to +1 @jseldess in that using `security-reference` may create more difficulties further down the line in linking to/from these security docs. Perhaps consider having the security docs in the same top-level directory as (most of) the other docs. If you have a strong preference for keeping them in their own folder, I'll defer to you on it.

> Reviewed 161 of 168 files at r6, 5 of 8 files at r7, 1 of 2 files at r8, 3 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13037#-:-Mx1IsOL6zTrn9bIfy59:bh0d7jx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess, @knz, @MichaelTrestman, and @taroface)

___
*[_includes/common/ui/sessions-page.md, line 38 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwhzZSK1SG4E4FCre0H:-MwhzZSK1SG4E4FCre0I:bodrqiv) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/_includes/common/ui/sessions-page.md#L38)):*
> ```Markdown
> Memory Usage | Amount of memory currently allocated to this session, followed by the maximum amount of memory this session has ever been allocated.
> Statement | Active SQL statement. If more than one statement is active, the most recent statement is shown.
> Actions | Options to terminate the active query and/or terminate the session. These require the `CANCELQUERY` role option.<br><br>**Terminate Statement:** Ends the SQL statement. The session running this statement will receive an error.<br><br>**Terminate Session:** Ends the session. The client that holds this session will receive a "connection terminated" event.
> ```

Suggest code ticks rather than quote marks around this.

For `CANCELQUERY`, I noticed the link was removed. Is there a new one we can use here?



_Code quote:_
```Markdown
"connection terminated"
```
___
*[_includes/v21.1/backups/destination-file-privileges.md, line 1 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mwi-HmG8ML6062L9KrE:-Mwi-HmG8ML6062L9KrF:b-jzclvz) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/_includes/v21.1/backups/destination-file-privileges.md#L1)):*
> ```Markdown
> The destination file URL does _not_ require the `ADMIN` role in the following scenarios:
> ```

This is usually styled `admin`.

Also (same question as earlier), is there a new link that can be used here?



_Code quote:_
```Markdown
`ADMIN` role
```
___
*[_includes/v21.2/misc/enterprise-features.md, line 8 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mwi-hwi56Ef1Acm2rav:-Mwi-hwi56Ef1Acm2raw:b3myilx) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/_includes/v21.2/misc/enterprise-features.md#L8)):*
> ```Markdown
> [Changefeeds into a Configurable Sink](create-changefeed.html) | This feature targets an allowlist of tables. For every change, it emits a record to a configurable sink, either Apache Kafka or a cloud-storage sink, for downstream processing such as reporting, caching, or full-text indexing.
> [Node Map](enable-node-map.html) | This feature visualizes the geographical configuration of a cluster by plotting node localities on a world map.
> [Encryption at Rest](security-reference/encryption.html#encryption-at-rest-enterprise) | Supplementing CockroachDB's encryption in flight capabilities, this feature provides transparent encryption of a node's data on the local disk. It allows encryption of all files on disk using AES in counter mode, with all key sizes allowed.
> ```

"encryption-in-flight"? or "encryption in-flight"?



_Code quote:_
```Markdown
encryption in flight
```
___
*[_includes/v21.2/misc/session-vars.html, line 309 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mwi-na54Jn6HfZCqy7r:-Mwi-na54Jn6HfZCqy7s:b-yrl12l) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/_includes/v21.2/misc/session-vars.html#L309)):*
> ```HTML
>     <code>is_superuser</code>
>    </td>
>    <td><span class="version-tag">New in v21.2</span>: If <code>on</code> or <code>true</code>, the current user is a member of the <a href="security-reference/authorization.html#admin-role">admin</a> role.</td>
> ```

Code ticks around `admin`. Also recommend linking all instances of `admin` role (elsewhere in this PR I saw that it wasn't linked) to this new url.



_Code quote:_
```HTML
admin
```
___
*[_includes/v21.2/misc/source-privileges.md, line 1 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mwi-zsA0ZlKixp-3nri:-Mwi-zsA0ZlKixp-3nrj:bn9ygm2) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/_includes/v21.2/misc/source-privileges.md#L1)):*
> ```Markdown
> The source file URL does _not_ require the [`ADMIN` role](security-reference/authorization.html#admin-role) in the following scenarios:
> ```

Just reiterating that this should be styled either `ADMIN` or `admin` throughout.



_Code quote:_
```Markdown
ADMIN
```
___
*[cockroachcloud/console-access-management.md, line 23 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mwi0AvEE9NzO4Mkn0is:-Mwi0AvEE9NzO4Mkn0it:bix1yg) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/cockroachcloud/console-access-management.md#L23)):*
> ```Markdown
> [Console Admins](#console-admin) can [create and manage SQL users](user-authorization.html#create-a-sql-user). A SQL user can interact with a CockroachDB database using the built-in SQL shell or through an application.
> 
> SQL users created in the Console have admin privileges on the cluster by default, even if the user has [Developer](#developer) privileges for the organization. Therefore, anyone with the username and password of a default SQL user has privileges for all resources across the cluster.
> ```

Does "admin privileges" mean "the `admin` role"? We should be consistent in terminology across the Cloud and Self-Hosted docs, since we have the separate notion of SQL privileges. I realize you inherited this.



_Code quote:_
```Markdown
admin
```
___
*[cockroachcloud/console-access-management.md, line 27 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvTj5mEs8IvVOWqd23:-Mx0QhYp4tEfZSieRxq5:b3fs8cj) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/cockroachcloud/console-access-management.md#L27)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

It's very confusing: "A role admin is a member of the role that's allowed to grant or revoke role membership to other users for that specific role." this sure makes it sound like `role admin` is a role, but it is ambiguous. So what is 'role admin' if it's not a role? 
</blockquote></details>

Sounds like it is a member of the role, not the role itself. Maybe we need to present the concept of role "membership" more clearly (not necessarily in this PR).
___
*[cockroachcloud/frequently-asked-questions.md, line 65 at r9](https://reviewable.io/reviews/cockroachdb/d [...]

2022-03-01 02:33 UTC, MichaelTrestman commented
___
*[v21.2/security-reference/config-secure-hba.md, line 19 at r2](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mw7WQbg5FzXijNQ7hGR:-Mx2IpWL8CfpcfiS37tW:b-k331er) ([raw file](https://github.com/cockroachdb/docs/blob/e0d3ae23cb3a590442454c07cd1a373b9db85212/v21.2/security-reference/config-secure-hba.md#L19)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

Ok thanks. I removed the word "simple". It looks on cloud I can make at least one password attempt every two seconds (trying every second, every other attempt gets throttled), so maybe I can only make around 4k attempts per day (per user?). That's not being totally vulnerable to raw brute force password cracking, but If I care about my data, I'd still rather not allow that.
</blockquote></details>

Elsewhere, the (pre-existing, i.e. not written by me) docs do also refer to network protections "preventing denial-of-service and brute force password attacks" https://www.cockroachlabs.com/docs/cockroachcloud/connect-to-your-cluster.html#step-1-authorize-your-network

So perhaps the claim should be dialed back there as well? I'm not really a fan of that sentence in any case so I'll give it a tweak.


<!-- Sent from Reviewable.io -->

2022-03-01 02:35 UTC, MichaelTrestman commented
___
*[v21.2/security-reference/config-secure-hba.md, line 19 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjGJKo2lVhsQN8Sxtj:-Mx2JsnI1YXM0yFVsYAf:bkkcekx) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L19)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Nit: hyphenate
</blockquote></details>

I see non-hyphenated uses in the docs (https://www.cockroachlabs.com/docs/cockroachcloud/connect-to-your-cluster) as well as hyphenated. Is hyphenated canonical? I don't see it in the style guide.


<!-- Sent from Reviewable.io -->

2022-03-01 09:25 UTC, knz reviewed
> Reviewed 1 of 1 files at r12, 5 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13037)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess, @knz, @MichaelTrestman, and @taroface)

___
*[cockroachcloud/console-access-management.md, line 25 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvTdbT1OU-K5ek5rbZ:-Mx3iI3WAZFdkHlzN3LN:b-yhr58m) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/cockroachcloud/console-access-management.md#L25)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

Got pretty strong pushback about any kind of forward messaging when I raised this with the docs team.
</blockquote></details>

I don't see the phrasing that highlights this is a known limitation.
___
*[cockroachcloud/console-access-management.md, line 27 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvTj5mEs8IvVOWqd23:-Mx3iPk417ZNFdobu8K2:b-g5uezk) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/cockroachcloud/console-access-management.md#L27)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Sounds like it is a member of the role, not the role itself. Maybe we need to present the concept of role "membership" more clearly (not necessarily in this PR).
</blockquote></details>

"role admin" - grammar: "role" is genitive, "admin" is the main qualifier, means "a user that is administrator for its role". Note that "admin" in this case is not a noun and is not monospaced.

"`admin` role" - grammar: "admin" is dative, "role" is the noun, means "a role whose name is `admin`".

The phrase "`admin` role admin" is sensical, albeit convoluted: a user that is administrator for the role called `admin`.

The phrase "`role admin` role" is nonsensical - there is no role called "`role admin`". Hence my comment.
___
*[v21.2/security-reference/authorization.md, line 83 at r13](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx3jzPeDUxl_qgV9wA2:-Mx3jzPeDUxl_qgV9wA3:b-hyhw3v) ([raw file](https://github.com/cockroachdb/docs/blob/fd4e29cb2162a774ec69232e041d3001386a21df/v21.2/security-reference/authorization.md#L83)):*
> ```Markdown
> 
> {{site.data.alerts.callout_success}}
> The terms “`admin` role” and “`role admin`” can be confusing. A user who is a member of the `admin` role has all privileges on all database objects across the entire cluster, whereas a `role admin` has privileges limited to the role they are a member of. Assign the `admin` role to a SQL user if you want the user to have privileges across the cluster. Make a SQL user the `role admin` if you want to limit the user’s privileges to its current role, but with an option to grant or revoke role membership to other users. This applies to the `admin` role as well - only admin users with the `WITH ADMIN OPTION` can add or remove other users from the `admin` role.
> ```

The backticks around "role admin" throughout this paragraph and the sentence above it are incorrect. 

There should be a clarifying sentence somewhere:

```
The phrase "role admin" is shorthand for "role administrator", which means "administrator for the membership to a role".
```
___
*[v21.2/security-reference/authorization.md, line 150 at r13](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx3kUxm5zKY_LMwDZ2L:-Mx3kUxm5zKY_LMwDZ2M:b1a8fhl) ([raw file](https://github.com/cockroachdb/docs/blob/fd4e29cb2162a774ec69232e041d3001386a21df/v21.2/security-reference/authorization.md#L150)):*
> ```Markdown
> ## Role options
> 
> Users' authorization to perform certain actions are governed not by grants but by [`role options`](../create-user.html#role-options). These options govern whether users can perform actions such as:
> ```

Why the backticks around "role options"? these words are not SQL syntax.
___
*[v21.2/security-reference/authorization.md, line 152 at r13](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx3ka4EEd6xBFkzRuul:-Mx3ka4EEd6xBFkzRuum:brt5tms) ([raw file](https://github.com/cockroachdb/docs/blob/fd4e29cb2162a774ec69232e041d3001386a21df/v21.2/security-reference/authorization.md#L152)):*
> ```Markdown
> Users' authorization to perform certain actions are governed not by grants but by [`role options`](../create-user.html#role-options). These options govern whether users can perform actions such as:
> 
> - viewing or canceling ongoing queries and sessions owned by other roles
> ```

you've read already from Ryan that list items should be capitalized with a period at the end.
___
*[v21.2/security-reference/config-secure-hba.md, line 17 at r2](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mw7W6143a5DzX8vtDX4:-Mx3l-s59_7w3T2610Pq:b-51h7kp) ([raw file](https://github.com/cockroachdb/docs/blob/e0d3ae23cb3a590442454c07cd1a373b9db85212/v21.2/security-reference/config-secure-hba.md#L17)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

I feel that I do recommend a particular security setup to the customer, explicitly, in the same sentence (i.e. limiting database connections to secure IP addresses). no?
</blockquote></details>

I feel like the now-very-lengthy sentence is burying your lede.
What about this:

```
As a measure of defense in depth, we recommend to combine any choice of authentication method with one or more network-level protections.
At the very least, we strongly recommend using TLS encryption for all client connections.
Additionally, if access to the cluster is not restricted via a VPN or VPC virtual network, we recommend using a filter on the originating IP address via HBA rules.
```
___
*[v21.2/security-reference/config-secure-hba.md, line 39 at r13](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx3mQHRDdhN6cTiwExf:-Mx3mQHRDdhN6cTiwExg:b-p0pk9u) ([raw file](https://github.com/cockroachdb/docs/blob/fd4e29cb2162a774ec69232e041d3001386a21df/v21.2/security-reference/config-secure-hba.md#L39)):*
> ```Markdown
> ```
> 
> ## Provision a secure jumpbox
> ```

See my comment above: the term "jumpbox" needs to be defined.


<!-- Sent from Reviewable.io -->

2022-03-01 17:45 UTC, MichaelTrestman commented
___
*[v21.2/security-reference/config-secure-hba.md, line 17 at r2](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mw7W6143a5DzX8vtDX4:-Mx5_DXs91JXpozDr_hP:b-af4oj1) ([raw file](https://github.com/cockroachdb/docs/blob/e0d3ae23cb3a590442454c07cd1a373b9db85212/v21.2/security-reference/config-secure-hba.md#L17)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I feel like the now-very-lengthy sentence is burying your lede.
What about this:

```
As a measure of defense in depth, we recommend to combine any choice of authentication method with one or more network-level protections.
At the very least, we strongly recommend using TLS encryption for all client connections.
Additionally, if access to the cluster is not restricted via a VPN or VPC virtual network, we recommend using a filter on the originating IP address via HBA rules.
```



</blockquote></details>

Copy is now improved, I think. I want to make the point specifically about the case where a credential is leaked, which your suggestion didn't include.


<!-- Sent from Reviewable.io -->

2022-03-01 18:04 UTC, MichaelTrestman commented
Created a ticket to audit for admin role/role admin labeling and definitions in particular https://cockroachlabs.atlassian.net/browse/DOC-2770





<!-- Sent from Reviewable.io -->

2022-03-01 18:06 UTC, MichaelTrestman commented
dropping network-security.md as unnecessary.

adopting liquid syntax and will try and patch it in where it's missing throughout the security docs.
after discussing with Jesse, I'm going to leave the seperate dir for this little clump of docs, as it is a well-defined and narrowly scoped clump (descriptive reference specifications of security features)





<!-- Sent from Reviewable.io -->

2022-03-01 18:38 UTC, MichaelTrestman commented
___
*[_includes/v21.2/misc/enterprise-features.md, line 8 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mwi-hwi56Ef1Acm2rav:-Mx5liUx1eevVjFPgLic:b-kji88j) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/_includes/v21.2/misc/enterprise-features.md#L8)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

"encryption-in-flight"? or "encryption in-flight"?
</blockquote></details>

Making a seperate ticket to sort this out: https://cockroachlabs.atlassian.net/browse/DOC-2772


<!-- Sent from Reviewable.io -->

2022-03-01 18:58 UTC, MichaelTrestman commented
___
*[cockroachcloud/console-access-management.md, line 27 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvTj5mEs8IvVOWqd23:-Mx5qD1G5VfBR7vFXRBJ:b-k13wo1) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/cockroachcloud/console-access-management.md#L27)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

"role admin" - grammar: "role" is genitive, "admin" is the main qualifier, means "a user that is administrator for its role". Note that "admin" in this case is not a noun and is not monospaced.

"`admin` role" - grammar: "admin" is dative, "role" is the noun, means "a role whose name is `admin`".

The phrase "`admin` role admin" is sensical, albeit convoluted: a user that is administrator for the role called `admin`.

The phrase "`role admin` role" is nonsensical - there is no role called "`role admin`". Hence my comment.
</blockquote></details>

https://cockroachlabs.atlassian.net/browse/DOC-2770


<!-- Sent from Reviewable.io -->

2022-03-01 19:29 UTC, MichaelTrestman commented
___
*[cockroachcloud/console-access-management.md, line 25 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvTdbT1OU-K5ek5rbZ:-Mx5wO_7992KVxCTljSK:bibnd60) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/cockroachcloud/console-access-management.md#L25)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't see the phrasing that highlights this is a known limitation.
</blockquote></details>

https://cockroachlabs.atlassian.net/browse/DOC-2773


<!-- Sent from Reviewable.io -->

2022-03-01 19:29 UTC, MichaelTrestman reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13037)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess, @knz, @MichaelTrestman, and @taroface)

___
*[cockroachcloud/console-access-management.md, line 25 at r9](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwhK--EB_6CoxMOixAd:-Mx5pXs68khzffs5hR58:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/671c88b1f89ba4b33fc1f06cee7af03ed015eab3/cockroachcloud/console-access-management.md#L25)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

nits: In terms of tone, I think we should aim for slightly more common diction. Can we find another way to say "is expedient"? Maybe "is fast and easy"? I actually think we can be more direct and say something like:

>For this reason, users should generally be created from the SQL client instead, and have their database resource access granted... 
</blockquote></details>

Done.
___
*[cockroachcloud/console-access-management.md, line 23 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mwi0AvEE9NzO4Mkn0is:-Mx5pSzQ0PaX6mDV4wYr:bkfhhuo) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/cockroachcloud/console-access-management.md#L23)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Does "admin privileges" mean "the `admin` role"? We should be consistent in terminology across the Cloud and Self-Hosted docs, since we have the separate notion of SQL privileges. I realize you inherited this.
</blockquote></details>

Console admin is extra gross. Seperate ticket will improve this stuff: https://cockroachlabs.atlassian.net/browse/DOC-2770
___
*[v21.2/security-reference/config-secure-hba.md, line 23 at r2](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mw7WkEB6tm2SCR5kX_i:-Mx1Ardr3Q-_DevJANnc:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/e0d3ae23cb3a590442454c07cd1a373b9db85212/v21.2/security-reference/config-secure-hba.md#L23)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

the term "secure jumpbox" is not commonplace and thus needs to be defined.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-01 20:06 UTC, MichaelTrestman commented
___
*[releases/v22.1.0-alpha.1.md, line 41 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvU9gN6__KuTKdS5Hn:-Mx64NzyAyClVGjdvndX:b-bkryk5) ([raw file](https://github.com/cockroachdb/docs/blob/a81b9d435dbd0589c79ce2b9766354b7aea2ce7e/releases/v22.1.0-alpha.1.md#L41)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

here and below, did you intend to remove these hyperlinks?
</blockquote></details>

Yes. They were breaking the build so required a fix and I judged the links to have 0 helpfulness value in context (e.g., here, release notes), so removing them was a quicker fix than finding the least irrelevant thing to link it to just for the sake of having a link.


<!-- Sent from Reviewable.io -->

2022-03-01 20:40 UTC, MichaelTrestman commented
___
*[v21.2/security-reference/config-secure-hba.md, line 29 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjHsJVDrPeZ3WLaBbi:-Mx6CYFrDd5FcpRxl0pT:b-z5t6jv) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L29)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

"connect to the SQL shell"?
</blockquote></details>

'the sql shell' doesn't quite capture the fact that it's about connecting to a particular server. Changed it to "Open a SQL shell against your cluster."


<!-- Sent from Reviewable.io -->

2022-03-01 20:40 UTC, MichaelTrestman reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13037)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess, @knz, @MichaelTrestman, and @taroface)

___
*[cockroachcloud/frequently-asked-questions.md, line 68 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mwi5jJL0gUCQkCeMXgC:-Mx60sVH-0pelhWyybim:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/cockroachcloud/frequently-asked-questions.md#L68)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Ditto on liquid syntax for product names. Also for `CockroachDB Self-Hosted Enterprise`.
</blockquote></details>

Done.
___
*[cockroachcloud/frequently-asked-questions.md, line 68 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mwi5mBS5h3JY2Eg1Z7_:-Mx60wZf1tHE6-nh86Kf:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/cockroachcloud/frequently-asked-questions.md#L68)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

proprietary?
</blockquote></details>

Done.
___
*[cockroachcloud/frequently-asked-questions.md, line 68 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mwi5pMU2q4M2X4np-cF:-Mx60wFjEQbip4PQrQib:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/cockroachcloud/frequently-asked-questions.md#L68)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

extra space here
</blockquote></details>

Done.
___
*[cockroachcloud/frequently-asked-questions.md, line 70 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mwi5xb5BfU4pWjZtNTf:-Mx61MpJE-_rlPtyffQi:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/cockroachcloud/frequently-asked-questions.md#L70)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

"since the Console is unaware"?
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 27 at r2](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mw7WpR_EuhwHx3kPWlV:-Mx6BhMF7yZx2HkhhQKc:b-fsrg59) ([raw file](https://github.com/cockroachdb/docs/blob/e0d3ae23cb3a590442454c07cd1a373b9db85212/v21.2/security-reference/config-secure-hba.md#L27)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

what's the "connection comand"?
</blockquote></details>

copy is improved to clarify that it is the command displayed in the cc console
___
*[v21.2/security-reference/config-secure-hba.md, line 8 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjDa253wW72Uc7N5qT:-Mx69twj4X8f62ZE4tjy:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L8)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

I feel like this h2 might be better moved under the bulleted list below. We don't usually begin with an h2.

Also, you can cut "Introduction: "
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 15 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjErS8AqWG4c6KPiV7:-Mx69jJy46ZlznEl9lls:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L15)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

I'd suggest cutting this as we're not trying to tempt people from cloud to self-hosted deployments. Also, it implies that cloud customers are not savvy enough to self-host
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 15 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjEQFc8V--qh7GnzIz:-Mx6Alau10BtNST6lezj:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L15)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Suggest:

{{ site.data.products.serverless-plan }} and {{ site.data.products.dedicated }} provide industry-standard [...]
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 15 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjF3AhB_NWS1FDhC7V:-Mx6AmzFB6rhBitMEH4o:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L15)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Extra spaces/tab
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 15 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx19pRjEY0AwiHxL6Si:-Mx6AtYnAylVy2hyGuXT:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L15)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Hyphenate
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 17 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjFfAq3d7lof0CvCjb:-Mx6AwhD3PhovJU1m6oh:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L17)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

To avoid sounding like we are advertising a shortcoming:

Because {{ site.data.products.serverless-plan }} and {{ site.data.products.dedicated }} currently use password authentication [...]
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 17 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjGDRu0X2dxnPG8HiM:-Mx6B1Ve40Ct-opEK8hT:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L17)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

is there a typo or missing word here?
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 19 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjGMd0BXNYocbYVINN:-Mx6B8OmDh-mn5WWuGqy:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L19)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Add a comma
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 21 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjGU2g7WV2m61hSmJY:-Mx6BIi8A1YT25ReeGzO:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L21)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

denial-of-service (DoS)
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 21 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjGQC4AtO_Enp38vpC:-Mx6BJ2q1TDm7hvur_sh:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L21)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Hyphenate
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 23 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjG_kL0D0QZk-1dmcM:-Mx6BGU85UfSK78WviXZ:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b [...]

2022-03-01 20:46 UTC, MichaelTrestman commented
___
*[v21.2/security-reference/config-secure-hba.md, line 48 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjKfGt0XqGpS05jVAg:-Mx6Dh2_7hTc_KLSE0sJ:b-booydu) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L48)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Can we briefly elaborate on why Google Cloud is being used as the example? Are we recommending it for all such use cases, due to the features mentioned here, or do other platforms afford the same/similar benefits?
</blockquote></details>

added a note that you could as easily use ec2. the security comparison between compute services across IAASes seems beyond the scope of this ticket; I mention 2fa and IAM for ssh access as the relevant features, that seems like enough context, no? open to further suggestions


<!-- Sent from Reviewable.io -->

2022-03-01 20:50 UTC, MichaelTrestman commented
___
*[v21.2/security-reference/config-secure-hba.md, line 64 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjLpwv7ZiThgdXyA_U:-Mx6Eldg2UIOcKKB_bZ-:brzbmmh) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L64)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

The way these SQL commands are presented is not friendly. Here and in the remainder of the doc below, I'd look at an existing tutorial like https://www.cockroachlabs.com/docs/stable/secure-a-cluster.html#step-3-use-the-built-in-sql-client and format it similarly, where the SQL snippet is presented in a copy-able format and the result in the shell is presented separately (only if it contains useful info)
</blockquote></details>

Opening a separate ticket rather trying to fix this one spot when others are broken and there's lots of heterogeneity. Largely because there's a timeframe on this particular PR. https://cockroachlabs.atlassian.net/browse/DOC-2778


<!-- Sent from Reviewable.io -->

2022-03-01 20:53 UTC, MichaelTrestman commented
___
*[v21.2/security-reference/config-secure-hba.md, line 66 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx1AC0f2M6h4dDUyrv3:-Mx6F-Vc6P5W1DP1ENjS:b-t8rxo0) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L66)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Also, use `~~~` instead
</blockquote></details>

why? I see ``` throughout the docs. Should I open a ticket to convert all the back-tick code blocks in the security docs to tilde code blocks?


<!-- Sent from Reviewable.io -->

2022-03-01 20:56 UTC, MichaelTrestman reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13037)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess, @knz, @MichaelTrestman, and @taroface)

___
*[v21.2/security-reference/config-secure-hba.md, line 13 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjEFOrCZrr6MNdEirY:-Mx6GC81-dSaJCqAvIiE:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L13)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Suggest some style edits:

- **Who** is making the attempt (SQL user).
- **Where** on the internet (IP address) the attempt is coming from.
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 13 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjIsdE2R56W4eX_Vk-:-Mx6GG6W20fRbfZwPzTr:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L13)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

After this list, I'd add a line like "In this tutorial, you will [...]" previewing what the result will be
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 45 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjHysWBr63E5JxbzM2:-Mx6D18n2Jw-FB-JrMj5:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L45)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Extra line break
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 46 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjI3yH5dZdIEUi3r_1:-Mx6CyvjB5Gs10PyrKG9:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L46)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Use an em dash: —
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 46 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjIDPhD3C4h7K4H9qy:-Mx6DD_3-0TLUj4wA-r7:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L46)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Add an em dash between these
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 48 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjIUsKE18S-1FpBwyY:-Mx6DQoG8cYFCvKKF3b3:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L48)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

"to the compute instance"?
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 48 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjIYse3_PAEcDOBERJ:-Mx6DWPz12Z4fqD1pEt8:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L48)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Missing verb after "effectively"

Hyphenate "two-factor"
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 50 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjKyv97y2tIikCRYA9:-Mx6E1YlDUy7Z8_ya2J7:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L50)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Add code backticks
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 56 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjL0FMBTCcWhBjkIwg:-Mx6E88F6ATlY-XrKEsv:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L56)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Use sentence case for h2s ("Tighten the authentication configuration")
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 58 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjL5hdA8c_XRvMOFpf:-Mx6EDhp3qut_yhkT4qs:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L58)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

hyphenate
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 59 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjL78t0WwiMRwVJfPJ:-Mx6EFaV1jrokw-LAsWy:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L59)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Extra line break
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 61 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjLEVE9BsbKpbjltFt:-Mx6ELoa5VsSwyC6UpcQ:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L61)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Missing verb

Lowercase "cluster setting" and link to `cluster-settings.html`
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 62 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjL8QHAsNYuXxk3xwT:-Mx6ELKjELWnXRVgzQXw:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L62)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Extra line break
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 109 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjMW8I1IcW9fprScun:-Mx6FbMx3pv4PgzZFetl:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L109)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Same comment as above, except for the CLI command
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 122 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjMaob0REKQFJ8Dv32:-Mx6FqI357x4-nkJ8qkP:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L122)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

need to access
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 124 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjMeeW7pwLV-jf2c7e:-Mx6FsSwEPL3ufjRTa7f:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L124)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Extra line break
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 125 at r11](https://revi [...]

2022-03-01 20:59 UTC, MichaelTrestman commented
___
*[v21.2/security-reference/encryption.md, line 14 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjND175f4dwBF4HayV:-Mx6GmOZ22D5GHNI5ck6:b17rzot) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/encryption.md#L14)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

I don't know that we want to imply that GCP and AWS are the only possible or recommended options, i.e., there is also Azure.
</blockquote></details>

In CockroachDB Cloud you have only GCP and AWS, no?


<!-- Sent from Reviewable.io -->

2022-03-01 21:11 UTC, MichaelTrestman commented
___
*[v21.2/security-reference/encryption.md, line 20 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjPzU956VaMOjiyrZH:-Mx6JeIB8KI47t9XMh-m:b7t3086) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/encryption.md#L20)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

lowercase
</blockquote></details>

No, we have Encryption at Rest (Enterprise) as a product


<!-- Sent from Reviewable.io -->

2022-03-01 21:14 UTC, MichaelTrestman commented
___
*[v21.2/security-reference/encryption.md, line 116 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx1DFoK8JCGnlAlK_xg:-Mx6KI9-Ed4wdOwoO6WE:bv74862) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/encryption.md#L116)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

lowercase?
</blockquote></details>

product, uppercase.


<!-- Sent from Reviewable.io -->

2022-03-01 21:15 UTC, MichaelTrestman commented
___
*[v21.2/security-reference/security-overview.md, line 7 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx1GdfXAbWcl64Dj8hH:-Mx6KYKm-iGAQ3ny0M9R:bvquvzo) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/security-overview.md#L7)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

I think we should let https://www.cockroachlabs.com/get-started-cockroachdb/ do the heavy lifting of characterizing/categorizing the product and how its features differ at a high level. So I don't think we need this Product Definitions section at all IMO. The table of security features is doing quite a lot on its own.
</blockquote></details>

Discussed this with Jesse, booting decision for seperate ticket.


<!-- Sent from Reviewable.io -->

2022-03-01 21:16 UTC, MichaelTrestman commented
___
*[v21.2/security-reference/security-overview.md, line 11 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvXrWHALgfLX4zKJyB:-Mx6KhiM5M7LF_23Psqa:b-51oaw7) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/security-overview.md#L11)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You can use markdown asterisks instead of html tags here and below for bold.
</blockquote></details>

Yes thank you, previous authors have left a lot of html tags throughout the docs. I don't have time to fix these all now.


<!-- Sent from Reviewable.io -->

2022-03-01 21:17 UTC, MichaelTrestman commented
___
*[v21.2/security-reference/security-overview.md, line 19 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvXwxS8euf6uFCLBtk:-Mx6L4af4HjX2se8LimI:b-edp9rj) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/security-overview.md#L19)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

you can use a markdown hyperlink here.
</blockquote></details>

Yes thank you, previous authors have left a lot of html tags throughout the docs. I don't have time to fix these all now.


<!-- Sent from Reviewable.io -->

2022-03-01 21:23 UTC, MichaelTrestman reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13037)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess, @knz, @MichaelTrestman, and @taroface)

___
*[v21.2/security-reference/encryption.md, line 24 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx1Bh3ZC0CHkgbcJG5P:-Mx6JtNQ-L9fDv8kPFXU:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/encryption.md#L24)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Remove the line break above this line.
</blockquote></details>

Done.
___
*[v21.2/security-reference/encryption.md, line 35 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx1BwSu5KtdanskKXbu:-Mx6K2dt1RzeWLaYFt2L:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/encryption.md#L35)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Remove the line break above this line
</blockquote></details>

Done.
___
*[v21.2/security-reference/encryption.md, line 81 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx1Cx8CDnNmeJQ-e0Wb:-Mx6KDQC4O7zu1UxEd3d:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/encryption.md#L81)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

We use `-` rather than `*` for unordered lists (I know these were inherited).
</blockquote></details>

Done.
___
*[v21.2/security-reference/encryption.md, line 107 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx1D7Zx4uzkocQoYk8l:-Mx6KHE_CCQ1LZ_mWIOM:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/encryption.md#L107)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Extra line break
</blockquote></details>

Done.
___
*[v21.2/security-reference/encryption.md, line 123 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx1D8o98RC7zuusM-kJ:-Mx6KOCH52zUQXil9squ:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/encryption.md#L123)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Extra line break
</blockquote></details>

Done.
___
*[v21.2/security-reference/security-overview.md, line 14 at r1](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mw7TItbDd3h_vxGK2D2:-Mx6L0NrDe9mjDdtkcec:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/345a8fc0db869a373d10617e7349ff00bac4cff3/v21.2/security-reference/security-overview.md#L14)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I believe we've made it customary to end bullet points with a period.
</blockquote></details>

Done.
___
*[v21.2/security-reference/security-overview.md, line 17 at r1](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mw7TkSs48XnkMS_85CR:-Mx6L0uXCbtC5QtzsVqY:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/345a8fc0db869a373d10617e7349ff00bac4cff3/v21.2/security-reference/security-overview.md#L17)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you contact our stylesheet designers, I think there's something broken. The rows in this table have different font sizes:
![image.png](https://files.reviewableusercontent.io/images/reviewable/642886/wOEdrAq6_IM76hRFlx-rUkH2/image.png)

</blockquote></details>

Done.
___
*[v21.2/security-reference/security-overview.md, line 37 at r1](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mw7UBKJC0mfPuRd_-UB:-Mx6LO5m3ARrqc_ff82b:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/345a8fc0db869a373d10617e7349ff00bac4cff3/v21.2/security-reference/security-overview.md#L37)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

same as above: I think we do periods at the end of each point. But I'm not sure. Ask a coworker for stylistic guidance.
</blockquote></details>

Done.
___
*[v21.2/security-reference/security-overview.md, line 3 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx1G7DQBRWov4Cj_CvT:-Mx6KR8F87zP24h8_ItW:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/security-overview.md#L3)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

These aren't the product names: https://github.com/cockroachdb/docs/blob/master/StyleGuide.md#product-names
</blockquote></details>

Done.
___
*[v21.2/security-reference/security-overview.md, line 34 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx1HGs4C7fXFITKi_kq:-Mx6LALA2Qj2lIB18lBD:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/security-overview.md#L34)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

These product names are incorrect. Use the liquid syntax https://github.com/cockroachdb/docs/blob/master/StyleGuide.md#product-names
</blockquote></details>

Done.
___
*[v21.2/security-reference/security-overview.md, line 67 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx1HU8Z0HRn1j-W5TLL:-Mx6LQfpAxsHki1v3u3k:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/security-overview.md#L67)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

hyphenate
</blockquote></details>

Done.
___
*[v21.2/security-reference/security-overview.md, line 110 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx1Hb5qCP9u-WMq1sZD:-Mx6LSZ90C6vsS-GfHDG:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/security-overview.md#L110)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[v21.2/security-reference/security-overview.md, line 117 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx1Hf-_36VQQdp8FiTX:-Mx6LTaN77UucFLMOPG_:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/security-overview.md#L117)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

"Industry-standard encryption at rest"?
</blockquote></details>

Done.
___
*[v21.2/security-reference/security-overview.md, line 117 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx1Hqel6MSh4mmzJAk1:-Mx6LZlQCAK9fCG9wWfp:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/security-overview.md#L117)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Elastic Block Store
</blockquote></details>

Done.
___
*[v21.2/security-reference/security-overview.md, line 177 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx1HzhiAYXOMLEWv8mG:-Mx6LdpR1VapUxdwmFQE:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/security-overview.md#L177)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

No hyphen
</blockquote></details>

Done.
___
*[v21.2/security-reference/security-overview.md, line 177 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx1IFx18s3OMsm4Ohma:-Mx6LmYC2mUVNorejxJH:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/security-overview.md#L177)):*
<details><summary><i>Previously, taro [...]

2022-03-01 21:34 UTC, MichaelTrestman commented
___
*[v21.2/alter-default-privileges.md, line 9 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mwi7Obu-kOueVW60U4a:-Mx6Oqy71pnJlPTJDmPp:bqjz5cr) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/alter-default-privileges.md#L9)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Style nit: We're trying to avoid using `/` vs. "users and roles"
</blockquote></details>

Seperate ticket, this is super wide spread.


<!-- Sent from Reviewable.io -->

2022-03-01 21:34 UTC, MichaelTrestman commented
___
*[v21.2/alter-schema.md, line 29 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mwi7c_pCagfakJBV5jy:-Mx6P32k91uzkMvq8-4o:bymuptu) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/alter-schema.md#L29)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Same comment as above re: "owner" role
</blockquote></details>

Added to ticket.


<!-- Sent from Reviewable.io -->

2022-03-01 21:42 UTC, MichaelTrestman reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13037)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess, @knz, @MichaelTrestman, and @taroface)

___
*[_includes/common/ui/sessions-page.md, line 38 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvTMk_2oiAK7-IrcZA:-Mx6MaqTEvYU3swzY3Q3:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a81b9d435dbd0589c79ce2b9766354b7aea2ce7e/_includes/common/ui/sessions-page.md#L38)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

What was the rationale for removing the hyperlink?
</blockquote></details>

Done.
___
*[_includes/common/ui/sessions-page.md, line 38 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwhzZSK1SG4E4FCre0H:-Mx6MiTJ7FcEY6TaSw_Z:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/_includes/common/ui/sessions-page.md#L38)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Suggest code ticks rather than quote marks around this.

For `CANCELQUERY`, I noticed the link was removed. Is there a new one we can use here?
</blockquote></details>

Done.
___
*[_includes/v21.1/backups/destination-file-privileges.md, line 1 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mwi-HmG8ML6062L9KrE:-Mx6Mqc933vQgSWzx_rm:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/_includes/v21.1/backups/destination-file-privileges.md#L1)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

This is usually styled `admin`.

Also (same question as earlier), is there a new link that can be used here?
</blockquote></details>

Done.
___
*[_includes/v21.1/misc/source-privileges.md, line 1 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvTQMS1-NCQHsjlcJd:-Mx6MvCTCyJsWb2LcNHs:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/_includes/v21.1/misc/source-privileges.md#L1)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`admin` should not be capitalized.

Also, why remove the hyperlink?
</blockquote></details>

Done.
___
*[_includes/v21.2/misc/session-vars.html, line 309 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mwi-na54Jn6HfZCqy7r:-Mx6N6Jt-iXijzxQwoYy:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/_includes/v21.2/misc/session-vars.html#L309)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Code ticks around `admin`. Also recommend linking all instances of `admin` role (elsewhere in this PR I saw that it wasn't linked) to this new url.
</blockquote></details>

Done.
___
*[_includes/v21.2/misc/source-privileges.md, line 1 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mwi-zsA0ZlKixp-3nri:-Mx6NEzA8nS67fnZFHdA:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/_includes/v21.2/misc/source-privileges.md#L1)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Just reiterating that this should be styled either `ADMIN` or `admin` throughout.
</blockquote></details>

Done.
___
*[cockroachcloud/frequently-asked-questions.md, line 65 at r9](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwhM02T45mgRXSuq-qr:-Mx6NkIVEo7Ple0DIrsU:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/671c88b1f89ba4b33fc1f06cee7af03ed015eab3/cockroachcloud/frequently-asked-questions.md#L65)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Typo on "infrastructure".

Also recommend using the liquid syntax for the product names, where feasible: https://github.com/cockroachdb/docs/blob/master/StyleGuide.md#product-names
</blockquote></details>

Done.
___
*[cockroachcloud/frequently-asked-questions.md, line 74 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mwi63MnEEUBD8Y8wCMN:-Mx6Nnji5zEfbD7-BkXq:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/cockroachcloud/frequently-asked-questions.md#L74)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Given recent conversations, I'm not certain we want to frame these as separate "CockroachDB products" as opposed to a unified product. It might be better to consider/phrase these as different "deployment options" or similar. This is a little tricky ... @jseldess any thoughts on this?
</blockquote></details>

Done.
___
*[v21.2/add-region.md, line 38 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mwi6smu0MQQijUSBQif:-Mx6OGVe7_nA1AEf2o9g:beqlhdf) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/add-region.md#L38)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

I find references to "owner" role confusing, given that "owner" refers to a role that has ownership, not a type of role. Would it be too convoluted to phrase this like "role that has ownership" of the object?
</blockquote></details>

Agree. Fixed.
___
*[v21.2/authentication.md, line 2 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx0TZ_6BOg7ShATjetU:-Mx6PZeCEnTAg6afwUW2:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/authentication.md#L2)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

This is called `CockroachDB Self-Hosted`. See https://github.com/cockroachdb/docs/blob/master/StyleGuide.md#product-names
</blockquote></details>

Done.
___
*[v21.2/authorization.md, line 6 at r1](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mw7O22m90mIY7Qm_-Mr:-Mx6PdeG4QfJrB6nIOlM:b-dd2pal) ([raw file](https://github.com/cockroachdb/docs/blob/f6b19a89078fd09cfeabdc9de850e81db6da922d/v21.2/authorization.md#L6)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

I like this overall approach a lot. But can you think of ways to reference the conceptual docs from the instructional, and vice versa?
</blockquote></details>

Making a separate ticket to add links.
___
*[v21.2/authorization.md, line 8 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvUNZsAEtunZb7x7rt:-Mx6QDHyDrEb6cIL9cLR:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a81b9d435dbd0589c79ce2b9766354b7aea2ce7e/v21.2/authorization.md#L8)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I understand that no general content has been deleted, yet it should remain customary for every page to contain a paragraph at the top that explains to the reader what they are about to encounter below. As-is, this page does not contain such a summary any more. What do you intend to do about that?
</blockquote></details>

Done.
___
*[v21.2/authorization.md, line 8 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mwi7sPeB3CMv26Vt_wo:-Mx6QZ4d2t256CuM5wjj:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/authorization.md#L8)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

CockroachDB
</blockquote></details>

Done.
___
*[v21.2/changefeed-for.md, line 22 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mwi8FMqD4RUr7qarUq4:-Mx6QhIj1gigMZVQFkm5:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/changefeed-for.md#L22)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

"`admin` role"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-01 21:44 UTC, MichaelTrestman reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13037)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess, @knz, @MichaelTrestman, and @taroface)

___
*[v21.2/crdb-internal.md, line 119 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiArWS7xhs7SnmphIU:-Mx6R-tk9MzrfepUMpTu:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/crdb-internal.md#L119)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Same comment as earlier. Should this be "the `admin` role" (to avoid confusion with the "privileges" listed separately on this page)?
</blockquote></details>

Done.
___
*[v21.2/encryption.md, line 7 at r1](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mw7OHBW4xdMYO87KV1e:-Mx6R3RG9aZt5QuxIXXI:bwkcqje) ([raw file](https://github.com/cockroachdb/docs/blob/f6b19a89078fd09cfeabdc9de850e81db6da922d/v21.2/encryption.md#L7)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Again, I like this overall approach a lot. But can you think of ways to reference the conceptual docs from the instructional, and vice versa?
</blockquote></details>

Created a separate ticket to improve link coverage.
___
*[v21.2/encryption.md, line 8 at r1](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvUhy2BkYJQoUIrUBd:-Mx6RAkTDAZ4-8j6NRS4:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/345a8fc0db869a373d10617e7349ff00bac4cff3/v21.2/encryption.md#L8)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Same as above, this page is now missing an overall explanation at the top of what it is about. What can you do about it?
</blockquote></details>

Done.
___
*[v21.2/encryption.md, line 2 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiBgiNBVIhw6H8EFRJ:-Mx6R25v28KvWn7Ci9tE:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/encryption.md#L2)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

This should be "CockroachDB Self-Hosted" - https://github.com/cockroachdb/docs/blob/master/StyleGuide.md#product-names
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-01 21:57 UTC, MichaelTrestman commented
___
*[v21.2/security-reference/authentication.md, line 7 at r1](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mw7P3DT60B6IJOqmbVN:-Mx6Swxy0JC9DchE9eVQ:bitjgr0) ([raw file](https://github.com/cockroachdb/docs/blob/345a8fc0db869a373d10617e7349ff00bac4cff3/v21.2/security-reference/authentication.md#L7)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Ok, but then in the interim this page should clarify at the top that its scope is more narrow than the product's capabilities. 

(We always ensure that the state of the docs after each PRs is "self sufficient and accurate" even if incomplete)

Perhaps a title change should help? Something like "SQL Authentication"?
</blockquote></details>

I'm deeming this to be an acceptable intermediate state, as it's better or as good in all respects than the prior state of the docs. The gain in value from the title change you propose is not worth the work of changing all the links, given that I'll be moving forward with fleshing things out, in my opinion, as it does not provide anything useful to the hypothetical user that would be left hanging looking for non-sql authentication anyway.


<!-- Sent from Reviewable.io -->

2022-03-01 21:59 UTC, MichaelTrestman commented
___
*[v21.2/security-reference/authentication.md, line 11 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiGbpS6XTEQFldPUOe:-Mx6U_oDBjekxNEV34He:b-7xn9dl) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/authentication.md#L11)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Style nit: We generally try to end each bullet with a period.

Also I suggest replacing the caps with bold styling per our style guide https://github.com/cockroachdb/docs/blob/master/StyleGuide.md#text-format
</blockquote></details>

This makes it ungrammatical, but ok


<!-- Sent from Reviewable.io -->

2022-03-01 22:00 UTC, MichaelTrestman commented
___
*[v21.2/security-reference/authentication.md, line 27 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiHTsYCIcVVyxaqMS_:-Mx6V0eA6f3qnDAM9niR:bcsc9zo) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/authentication.md#L27)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Style nit: end each bullet with a period and capitalize "Unconditionally"
</blockquote></details>

Also ungrammatical but ok.


<!-- Sent from Reviewable.io -->

2022-03-01 22:08 UTC, taroface commented
> _[v21.2/security-reference/authentication.md, line 27 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiHTsYCIcVVyxaqMS_:-Mx6V0eA6f3qnDAM9niR:bcsc9zo) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/authentication.md#L27)):_
> 
> Previously, taroface (Ryan Kuo) wrote…
> > Style nit: end each bullet with a period and capitalize "Unconditionally"
> 
> Also ungrammatical but ok.

My bad, you're right. "Unconditionally" does not need to be capitalized in these!

2022-03-01 22:11 UTC, MichaelTrestman commented
___
*[v21.2/security-reference/authentication.md, line 50 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiJ1eq-A0QUdZyVrY1:-Mx6WjqiBOfm-De8Ee-U:b-qsseby) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/authentication.md#L50)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

On preview, `host` and `all` columns don't look like they are aligning correctly beneath `TYPE` and `DATABASE`. Not sure if this has to do with the `#` or not. 
</blockquote></details>

fixed!


<!-- Sent from Reviewable.io -->

2022-03-01 22:22 UTC, taroface commented
> why? I see ``` throughout the docs. Should I open a ticket to convert all the back-tick code blocks in the security docs to tilde code blocks?

It may be that the docs where you see those are super old. I've only ever used `~~~` and assumed it was our convention, if not technically necessary for some reason.

2022-03-01 22:33 UTC, MichaelTrestman reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13037)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess, @knz, @MichaelTrestman, and @taroface)

___
*[v21.2/pg-catalog.md, line 170 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiCorw567ahC3GjQ8z:-Mx6RDOX0Xrkx5adgbVG:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/pg-catalog.md#L170)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Same comment as earlier - "`admin` role" here?
</blockquote></details>

Done.
___
*[v21.2/pg-extension.md, line 43 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiCsXS8fvpykk4zjas:-Mx6RFFp2QlsZfMaoRYk:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/pg-extension.md#L43)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[v21.2/refresh.md, line 16 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiCzuH2VOPT6eRUrII:-Mx6RHk_7eYfZ3ByQqYo:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/refresh.md#L16)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

"be a member of the `admin` role"
</blockquote></details>

Done.
___
*[v21.2/schema-design-database.md, line 34 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiDLnpBNBCAZVd3SGi:-Mx6RP2G92e6B1K9TEEX:bg90flt) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/schema-design-database.md#L34)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

nit: capitalize this?
</blockquote></details>

why? what would be capitalized?
___
*[v21.2/schema-design-indexes.md, line 135 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiDOaP4Bkqu4Y9qwIv:-Mx6RSQi9-hos85OE8tm:bxt0i96) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/schema-design-indexes.md#L135)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

what should be capitalized? all are general concepts, no?
___
*[v21.2/schema-design-table.md, line 420 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiDT6R3M3yB5wavkWa:-Mx6RX7pDLidoGv4Y-08:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/schema-design-table.md#L420)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[v21.2/set-locality.md, line 31 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiElBB1Sf-LL029nh_:-Mx6RZNb57B4U2dIz62S:b-5h8ejx) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/set-locality.md#L31)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Same comment as earlier re: "owner" role
</blockquote></details>

new ticket covers this
___
*[v21.2/show-default-privileges.md, line 9 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiFF6zAtVJldpbnF21:-Mx6RhTj7Ukltzlha_xW:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/show-default-privileges.md#L9)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

"users and roles"
</blockquote></details>

Done.
___
*[v21.2/survive-failure.md, line 28 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiGC4G5zJ_98n9RpVX:-Mx6RtKXEnsgF-KVKT02:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/survive-failure.md#L28)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Same question as earlier re: owner role
</blockquote></details>

Done.
___
*[v21.2/ui-overview.md, line 79 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiGFs80ozMyQAdjGPo:-Mx6Rv6hEh17Cl0eOwQO:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/ui-overview.md#L79)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

perhaps "Members of the `admin` role"
</blockquote></details>

Done.
___
*[v21.2/ui-sessions-page.md, line 9 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvVAEu-i-k-k9-1m_Z:-Mx6RxPo-S7DhLh_jiOg:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a81b9d435dbd0589c79ce2b9766354b7aea2ce7e/v21.2/ui-sessions-page.md#L9)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

did you intend to remove the hyperlink?
</blockquote></details>

Done.
___
*[v21.2/security-reference/authentication.md, line 36 at r1](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mw7Pbi--IsBbEQ214L5:-Mx6VUDB-5Zv0trgbpcX:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/345a8fc0db869a373d10617e7349ff00bac4cff3/v21.2/security-reference/authentication.md#L36)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: I believe that SQL statement examples are capitalized (you can check elsewhere in the docs).
</blockquote></details>

Done.
___
*[v21.2/security-reference/authentication.md, line 8 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiGqoa9zU4msM8YTxr:-Mx6UYxx93K45LuZ_pFc:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/authentication.md#L8)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Maybe "which database connection attempts". I found this slightly hard to read within the sentence.
</blockquote></details>

Done.
___
*[v21.2/security-reference/authentication.md, line 13 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiH0C24J1P7yLyMNMO:-Mx6UfAZESKRyroJaSan:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/authentication.md#L13)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Maybe cut? I don't know that we usually forecast future functionality in docs, unless there is a clear lack that needs to be fulfilled.
</blockquote></details>

Done.
___
*[v21.2/security-reference/authentication.md, line 34 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiHeB124Iszj7oe9rW:-Mx6VUZM2oo2GudbMAyw:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/authentication.md#L34)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Capitalize SQL statements
</blockquote></details>

Done.
___
*[v21.2/security-reference/authentication.md, line 34 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiHhJS7pzYiYLvmgDn:-Mx6Vq_9CmtVoMZmbB9R:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/authentication.md#L34)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Link mentions of "cluster setting" to `cluster-settings.html`
</blockquote></details>

Done.
___
*[v21.2/security-reference/authentication.md, line 34 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiHrY_9XiBHCIWqL8-:-Mx6W-m_7CViTLJbbFBI:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/authentication.md#L34)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Ditto. Also move the period outside the link.
</blockquote></detai [...]

2022-03-01 23:48 UTC, MichaelTrestman reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13037)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess, @knz, @MichaelTrestman, and @taroface)

___
*[v21.2/cluster-api.md, line 33 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mwi8K8tBr_c3n5ZhH1a:-Mx6bm8l88G_Lkg3Vwcd:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/cluster-api.md#L33)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

"`admin` role"
</blockquote></details>

Done.
___
*[v21.2/schema-design-update.md, line 120 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiDUkC7deORV1qTRSh:-Mx6fxOI7Pl6uWWHOvnK:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/schema-design-update.md#L120)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[v21.2/security-reference/authentication.md, line 27 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiHTsYCIcVVyxaqMS_:-Mx6g-n06g0bfvM0kgO-:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/authentication.md#L27)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

My bad, you're right. "Unconditionally" does not need to be capitalized in these!
</blockquote></details>

Done.
___
*[v21.2/security-reference/authentication.md, line 92 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiKo2-8lc8r2VF9YML:-Mx6jfeME1sBpTqb5tyo:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/authentication.md#L92)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Ditto; liquid syntax
</blockquote></details>

Done.
___
*[v21.2/security-reference/authorization.md, line 8 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mwj9aWy0SRkOhMe9xsW:-Mx6kDtn2WThkd4KeNYv:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/authorization.md#L8)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Suggest using bold vs. caps, and cleaning up the parenthetical lists:

Authorization controls **who** (users, roles) can do **what** (read, write, update, delete, grant) to **which** resources (databases, tables, clusters, schemas, rows, users).
</blockquote></details>

Done.
___
*[v21.2/security-reference/authorization.md, line 14 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjAFiPAG6Qa_CBFCis:-Mx6kV1m44uSPMp6_C3V:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/authorization.md#L14)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Extra line break
</blockquote></details>

Done.
___
*[v21.2/security-reference/authorization.md, line 22 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjBdwE0pGvvOsun27z:-Mx6kVnCCdnoDIaaOywJ:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/authorization.md#L22)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[v21.2/security-reference/authorization.md, line 44 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjAqdj9gqfE8y14s0i:-Mx6kYcz1kwgvUPc5xGX:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/authorization.md#L44)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Extra line break
</blockquote></details>

Done.
___
*[v21.2/security-reference/authorization.md, line 56 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjAtM93jerEm_4ItdZ:-Mx6kb3MCwK34vI116qJ:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/authorization.md#L56)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

2 extra line breaks
</blockquote></details>

Done.
___
*[v21.2/security-reference/authorization.md, line 69 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjAxKTD1bfn0SEfLrA:-Mx6ki9s1HHttiAdeRjG:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/authorization.md#L69)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

We've been updating this syntax opportunistically to `{% include_cached copy-clipboard.html %}` to improve build times. Let's find-replace it when possible.
</blockquote></details>

Done.
___
*[v21.2/security-reference/authorization.md, line 82 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjB8_T1il77PsHPqQB:-Mx6qOHi-cctK1Fji0IY:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/authorization.md#L82)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Style nit: Avoid contractions on technical descriptions (I realize this may have been there for a while)

https://github.com/cockroachdb/docs/blob/master/StyleGuide.md#style-and-tone
</blockquote></details>

Done.
___
*[v21.2/security-reference/authorization.md, line 85 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx19ARE5rkxElU6OJYb:-Mx6qPGDDaqo6xNSNQFy:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/authorization.md#L85)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Add code ticks
</blockquote></details>

Done.
___
*[v21.2/security-reference/authorization.md, line 102 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx19FSq-WwXS9dX8VOp:-Mx6qQML4zp5juKPGZId:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/authorization.md#L102)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

See earlier comments on "owner role" phrasing, which I find unnecessarily confusing.
</blockquote></details>

Done.
___
*[v21.2/security-reference/authorization.md, line 83 at r13](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx3jzPeDUxl_qgV9wA2:-Mx6qLuP-s2XKRRbo8m4:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/fd4e29cb2162a774ec69232e041d3001386a21df/v21.2/security-reference/authorization.md#L83)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

The backticks around "role admin" throughout this paragraph and the sentence above it are incorrect. 

There should be a clarifying sentence somewhere:

```
The phrase "role admin" is shorthand for "role administrator", which means "administrator for the membership to a role".
```
</blockquote></details>

Done.
___
*[v21.2/security-reference/authorization.md, line 150 at r13](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx3kUxm5zKY_LMwDZ2L:-Mx6qydu2obl1iLFA65q:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/fd4e29cb2162a774ec69232e041d3001386a21df/v21.2/security-reference/authorization.md#L150)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Why the backticks around "role options"? these words are not SQL syntax.
</blockquote></details>

Done.
___
*[v21.2/security-reference/authorization.md, line 152 at r13](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx3ka4EEd6xBFkzRuul:-Mx6qwp70SBDwMGunwfa:b-896fix) ([raw file](https [...]

2022-03-01 23:50 UTC, MichaelTrestman commented
___
*[v21.2/security-reference/authorization.md, line 141 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjBqFc-RKeKJk7_ga3:-Mx6swEx-Ehti1RKo4zU:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/authorization.md#L141)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Extra line break
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-02 01:54 UTC, taroface requested changes
A few follow-up comments. Some of the product names are still incorrect (particularly in a few page titles).

> Reviewed 7 of 184 files at r1, 1 of 5 files at r13, 22 of 29 files at r23, 4 of 6 files at r24, 37 of 37 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13037#-:-Mx7KImy8VszdXcKRZcW:b-jke3f0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess, @knz, @MichaelTrestman, and @taroface)

___
*[v21.2/authentication.md, line 2 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx0TZ_6BOg7ShATjetU:-Mx7KBM94l2sx4o3M2Z1:b8356zs) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/authentication.md#L2)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This product name still isn't fixed.
___
*[v21.2/authorization.md, line 8 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mwi7sPeB3CMv26Vt_wo:-Mx6zeZG9PfsKKG8jB7l:ba3rgnw) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/authorization.md#L8)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nit (style): For h2s, we generally use sentence case (only capitalize first word and proper nouns)
___
*[v21.2/encryption.md, line 2 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiBgiNBVIhw6H8EFRJ:-Mx7-O_c9-YJTcBBM6XE:b4kl00m) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/encryption.md#L2)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This looks like it still needs to be changed to "CockroachDB Self-Hosted".
___
*[v21.2/schema-design-indexes.md, line 135 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiDOaP4Bkqu4Y9qwIv:-Mx7-abCDE4F8mg_kEKZ:b-cn762w) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/schema-design-indexes.md#L135)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

what should be capitalized? all are general concepts, no?
</blockquote></details>

If you're linking to a section called "Authorization best practices", I'd capitalize it as such. But not a big deal as this can be read either way.
___
*[v21.2/security-reference/authentication.md, line 11 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiGbpS6XTEQFldPUOe:-Mx7-t11BJYa9vvV4iyu:b-l9sjd1) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/authentication.md#L11)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

This makes it ungrammatical, but ok
</blockquote></details>

Nit: My suggestion was to not use caps, but only bold, e.g. **Who** and **Where**.
___
*[v21.2/security-reference/authentication.md, line 94 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwiKq5_57rVmGiQZ9aj:-Mx70zDN6ML1GMuDepDS:bthumwg) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/authentication.md#L94)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nit: Should be "CockroachDB Self-Hosted" to match the product name and other headings on this page
___
*[v21.2/security-reference/authentication.md, line 53 at r25](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx70OZQEGWMQDP_n4cc:-Mx70OZQEGWMQDP_n4cd:b-2fmser) ([raw file](https://github.com/cockroachdb/docs/blob/f948d308e077b4eebb10482e84771bf2d95a1ba5/v21.2/security-reference/authentication.md#L53)):*
> ```Markdown
> Each rule definition contains up to 6 values.
> 
> 1. Each line must begin with a connection **TYPE**. CockroachDB currently supports two connection types:
> ```

Now I understand these are referring to the column headings in the snippet. These should use backticks:

- `TYPE`
- `DATABASE`
- `USER`
- `ADDRESS`
- `IP MASK` <-- is this also capitalized? Yours is written "IP Mask"
- `METHOD`



_Code quote:_
```Markdown
**TYPE**
```
___
*[v21.2/security-reference/authentication.md, line 66 at r25](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx70m94CUbr8R2_4-Lw:-Mx70m94CUbr8R2_4-Lx:bhdq1rh) ([raw file](https://github.com/cockroachdb/docs/blob/f948d308e077b4eebb10482e84771bf2d95a1ba5/v21.2/security-reference/authentication.md#L66)):*
> ```Markdown
>   - gss
>   - reject
>   - trust
> ```

I think all these should have backticks around them
___
*[v21.2/security-reference/authorization.md, line 8 at r25](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx719ZI8shM1Rkotb6W:-Mx719ZI8shM1Rkotb6X:b-wik5ok) ([raw file](https://github.com/cockroachdb/docs/blob/f948d308e077b4eebb10482e84771bf2d95a1ba5/v21.2/security-reference/authorization.md#L8)):*
> ```Markdown
> ---
> 
> Authorization, generally, is the control over **who** (users/roles) can perform **which actions** (e.g read, write, update, delete, grant, etc.) to **which resources or targets** (databases, tables, clusters, schemas, rows, users, jobs, etc.).
> ```

This can be cut.



_Code quote:_
```Markdown
e.g 
```
___
*[v21.2/security-reference/authorization.md, line 79 at r25](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx72DWH6CmiiG9vTMe8:-Mx72DWH6CmiiG9vTMe9:babk26i) ([raw file](https://github.com/cockroachdb/docs/blob/f948d308e077b4eebb10482e84771bf2d95a1ba5/v21.2/security-reference/authorization.md#L79)):*
> ```Markdown
> #### Role admin
> 
> `Role admin` is a [role option](#role-options) that allows a given user or role to *administrate* itself, by granting and revoking it to other users and roles.
> ```

Nit (style): We use bold and not italics to provide emphasis (I just learned this very recently)



_Code quote:_
```Markdown
*administrate*
```
___
*[v21.2/security-reference/authorization.md, line 84 at r25](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx72LIe7G1lP90lSM1L:-Mx72LIe7G1lP90lSM1M:b-d1b0b0) ([raw file](https://github.com/cockroachdb/docs/blob/f948d308e077b4eebb10482e84771bf2d95a1ba5/v21.2/security-reference/authorization.md#L84)):*
> ```Markdown
> 
> {{site.data.alerts.callout_success}}
> The terms “`admin` role” and “`role admin`” can be confusing. 
> ```

Nit: Some extra tab or space here.



_Code quote:_
```Markdown
··
```
___
*[v21.2/security-reference/config-secure-hba.md, line 61 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjLEVE9BsbKpbjltFt:-Mx755g0E34zNEgNUQzC:bavhg6a) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L61)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This looks like it still needs to be fixed.
___
*[v21.2/security-reference/config-secure-hba.md, line 8 at r25](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx732ob86V29WNvBIxj:-Mx732ob86V29WNvBIxk:b6g6jhe) ([raw file](https://github.com/cockroachdb/docs/blob/f948d308e077b4eebb10482e84771bf2d95a1ba5/v21.2/security-reference/config-secure-hba.md#L8)):*
> ```Markdown
> ---
> 
> CockroachDB allows fine-grained configuration of which attempts to connect with the database it will allow to proceed to the authentication stage, and which authentication methods it will accept, based on:
> ```

We had this as "database connection attempts" earlier, right?



_Code quote:_
```Markdown
attempts to connect with the database
```
___
*[v21.2/security-reference/config-secure-hba.md, line 10 at r25](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx72vU39bVkRUXobUGG:-Mx72vU39bVkRUXobUGH:b-qvkozv) ([ra [...]

2022-03-02 15:42 UTC, MichaelTrestman reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13037)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess, @knz, @MichaelTrestman, and @taroface)

___
*[v21.2/security-reference/config-secure-hba.md, line 8 at r25](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx732ob86V29WNvBIxj:-MxAH6o85SwGBD6we4nG:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f948d308e077b4eebb10482e84771bf2d95a1ba5/v21.2/security-reference/config-secure-hba.md#L8)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

We had this as "database connection attempts" earlier, right?
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 13 at r25](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx73-oO3u8STM0JU4dB:-MxAHRan9YbQWK-YMDCr:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f948d308e077b4eebb10482e84771bf2d95a1ba5/v21.2/security-reference/config-secure-hba.md#L13)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Is there a reason this is capitalized?
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 17 at r25](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx739kZ3YPOXFDf0KBc:-MxAHa7Q7EDhHcnG7HBm:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f948d308e077b4eebb10482e84771bf2d95a1ba5/v21.2/security-reference/config-secure-hba.md#L17)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Extra tab/spaces here
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 17 at r25](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx73C9P2MStuNlD0i7O:-MxAHpO_0ZtZAwZyiuyR:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f948d308e077b4eebb10482e84771bf2d95a1ba5/v21.2/security-reference/config-secure-hba.md#L17)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

afford
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-02 15:51 UTC, MichaelTrestman reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13037)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess, @knz, @MichaelTrestman, and @taroface)

___
*[v21.2/security-reference/config-secure-hba.md, line 61 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjLEVE9BsbKpbjltFt:-MxAIG6c1CjciGTBfsEr:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L61)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

This looks like it still needs to be fixed.
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 72 at r25](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx75CWf16KUnpFGRz54:-MxAIM7o-E4g17Mcn0gb:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f948d308e077b4eebb10482e84771bf2d95a1ba5/v21.2/security-reference/config-secure-hba.md#L72)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Extra line break
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 81 at r25](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx75nB1A9_Ob6PDFSxW:-MxAIVAh4mnoy9oU8yHF:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f948d308e077b4eebb10482e84771bf2d95a1ba5/v21.2/security-reference/config-secure-hba.md#L81)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

The above lines look misaligned in this snippet, but I'm not sure
</blockquote></details>

Done.
___
*[v21.2/security-reference/config-secure-hba.md, line 103 at r25](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx76Cjr6q8AIWiao0Vj:-MxAI_qcAp0WyxRGVm3_:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f948d308e077b4eebb10482e84771bf2d95a1ba5/v21.2/security-reference/config-secure-hba.md#L103)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

extra line break
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-02 16:04 UTC, MichaelTrestman commented
___
*[v21.2/security-reference/encryption.md, line 12 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjMsxd8lOr2mzBQD5r:-MxAKeD4Dyw2MLH7TUjR:byx4gip) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/encryption.md#L12)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Sorry in case I was confused by this. Does "Encryption at rest" here refer to a product name? In that case, it should be "Encryption at Rest" like the Enterprise heading down below.
</blockquote></details>

Encryption at Rest (Enterprise) is a feature, so it has a proper name and is capitalized. Encryption at rest in the context of CockroachDB Cloud is not names and hence lower case according to our header convention. Changed this a bit to make it less weird.


<!-- Sent from Reviewable.io -->

2022-03-02 16:09 UTC, MichaelTrestman reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13037)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess, @knz, @MichaelTrestman, and @taroface)

___
*[v21.2/security-reference/config-secure-hba.md, line 132 at r25](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx76Hi74DiJKTSz8RVP:-MxAK5Cr93ILfnGeMAIV:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f948d308e077b4eebb10482e84771bf2d95a1ba5/v21.2/security-reference/config-secure-hba.md#L132)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Same comment as above; make sure the code snippet is properly aligned
</blockquote></details>

Done.
___
*[v21.2/security-reference/encryption.md, line 14 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjP6wd5OfPL0IAuodR:-MxAN2ld8ast9vNq030a:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/encryption.md#L14)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

This still looks like the old hyphenation. Should be "Industry-standard encryption at rest". If you have a separate ticket for this, disregard for now.
</blockquote></details>

Done.
___
*[v21.2/security-reference/encryption.md, line 16 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwjPLDsB2EbfX48F2QB:-MxAOA9a3duwvtmzgGhA:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/encryption.md#L16)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

- `CockroachDB Cloud` should use the liquid syntax.
- "encryption at rest" is still hyphenated here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-02 16:13 UTC, MichaelTrestman reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13037)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess, @knz, @MichaelTrestman, and @taroface)

___
*[v21.2/security-reference/encryption.md, line 81 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx1Cx8CDnNmeJQ-e0Wb:-MxAOGzS6Bj59TjBwaDV:b-juqkhe) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/encryption.md#L81)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

These are still using `*`
</blockquote></details>

Seperate ticket.
___
*[v21.2/security-reference/encryption.md, line 92 at r25](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx7J-by9WOtiLRdL_R0:-MxAOJ1q8Q1qz-mFEN9-:bbx0n72) ([raw file](https://github.com/cockroachdb/docs/blob/f948d308e077b4eebb10482e84771bf2d95a1ba5/v21.2/security-reference/encryption.md#L92)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Ditto re: `*`
</blockquote></details>


Seperate ticket.
___
*[v21.2/security-reference/security-overview.md, line 3 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx1G7DQBRWov4Cj_CvT:-MxAOlqj1M6TVrzvbk5F:b-s7yg2r) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/security-overview.md#L3)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

These product names are still incorrect.
</blockquote></details>

It's shorthand in metadata.
___
*[v21.2/security-reference/security-overview.md, line 110 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx1Hb5qCP9u-WMq1sZD:-MxAOqDT02V1F6lWA214:b-juqkhe) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/security-overview.md#L110)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

I believe all instances of this should not be hyphenated
</blockquote></details>

Seperate ticket.
___
*[v21.2/security-reference/security-overview.md, line 117 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx1Hf-_36VQQdp8FiTX:-MxAOrYnEPQ21HsO9JoG:b-juqkhe) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/security-overview.md#L117)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Same comment as earlier; this isn't fixed.
</blockquote></details>

Seperate ticket.
___
*[v21.2/security-reference/security-overview.md, line 117 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx1Hqel6MSh4mmzJAk1:-MxAOvKPETaoD5g1jGcp:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/security-overview.md#L117)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

This isn't fixed.
</blockquote></details>

Done.
___
*[v21.2/security-reference/security-overview.md, line 177 at r25](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx7JeSOCQRTQsjVwrOc:-MxAP33J2Lv1w5skCFEp:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f948d308e077b4eebb10482e84771bf2d95a1ba5/v21.2/security-reference/security-overview.md#L177)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Style note: We're not using the word "native". See https://github.com/cockroachdb/docs/blob/master/StyleGuide.md#write-about-features-and-users-in-inclusive-ways

I think this can just say "distributed SQL database".
</blockquote></details>

Done.
___
*[v21.2/security-reference/security-overview.md, line 177 at r25](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx7JnYF2tTZCEdx-8cv:-MxAP9D66yY9aJ_cdu4T:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f948d308e077b4eebb10482e84771bf2d95a1ba5/v21.2/security-reference/security-overview.md#L177)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

"A cluster"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-02 17:03 UTC, MichaelTrestman commented
___
*[_includes/common/ui/sessions-page.md, line 38 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwhzZSK1SG4E4FCre0H:-MxAZJ_x5D8Jjq4ofm7g:b-9htizl) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/_includes/common/ui/sessions-page.md#L38)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The problem is that this partial is included in multiple docs versions directories. Having a relative link (the only kind Jekyll takes) is inconsistent with re-organizing the security docs as I have done. Fortunately this is the only link that really seems to be blocked this way. The user will unfortunately have to take the hit and search for `CANCELQUERY`.
I'm sure there's a workaround with ruby logic, but it is out of scope for this story, compared to the value of this link.


<!-- Sent from Reviewable.io -->

2022-03-02 17:19 UTC, taroface commented on v21.2/security-reference/config-secure-hba.md
> +## Why customize your authenticationication configuration?
@MichaelTrestman There's a typo in "authentication".

2022-03-02 17:20 UTC, taroface approved these changes
LGTM pending that typo (above)

2022-03-02 17:59 UTC, MichaelTrestman reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13037)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess, @knz, and @taroface)

___
*[v21.2/security-reference/config-secure-hba.md, line 15 at r27](https://reviewable.io/reviews/cockroachdb/docs/13037#-MvzCRMBqgZ70ANaapIa-r27-15:-MxAfGqU-KCQtvDBTVg7:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f8689f6b3dfa68835f921321d7ca9ba749590062/v21.2/security-reference/config-secure-hba.md#L15)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

@MichaelTrestman There's a typo in "authentication".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-02 18:50 UTC, merged

2022-03-03 10:20 UTC, knz reviewed
From a process perspective, you're supposed to wait for review approvals from both the technical side and the editorial side.
I generally don't mind taking shortcuts when the situation is straightforward, but in this case you had several open technical points, and some of them are still not resolved. I think a followup fixup PR would be useful here.

> Reviewed 15 of 29 files at r23, 1 of 6 files at r24, 16 of 37 files at r25, 6 of 7 files at r27, 1 of 1 files at r28, 5 of 5 files at r29, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13037#-:-MxEHX2F-TyDF8Qh5vQp:bknc1fw)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[_includes/common/ui/sessions-page.md, line 38 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvTMk_2oiAK7-IrcZA:-MxEDqSh2PgaUeW4-PD_:b5kcvnd) ([raw file](https://github.com/cockroachdb/docs/blob/a81b9d435dbd0589c79ce2b9766354b7aea2ce7e/_includes/common/ui/sessions-page.md#L38)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What is "done"? Don't you want a hyperlink from the term "role option" to the authorization page?
___
*[v21.2/authorization.md, line 8 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvUNZsAEtunZb7x7rt:-MxEEg0t2aQk5jcd3pQb:b95d74x) ([raw file](https://github.com/cockroachdb/docs/blob/a81b9d435dbd0589c79ce2b9766354b7aea2ce7e/v21.2/authorization.md#L8)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What's done? I don't see it.
___
*[v21.2/ui-sessions-page.md, line 9 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-MwvVAEu-i-k-k9-1m_Z:-MxEEz0l9YVONnY87hjy:b-n6oufs) ([raw file](https://github.com/cockroachdb/docs/blob/a81b9d435dbd0589c79ce2b9766354b7aea2ce7e/v21.2/ui-sessions-page.md#L9)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What's done? Don't you want to hyperlink "role option"?
___
*[v21.2/security-reference/authorization.md, line 150 at r13](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx3kUxm5zKY_LMwDZ2L:-MxEG-FDEzvCAhoF5GBG:bnnf380) ([raw file](https://github.com/cockroachdb/docs/blob/fd4e29cb2162a774ec69232e041d3001386a21df/v21.2/security-reference/authorization.md#L150)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What is "done"? The phrase should not be enclosed in backticks, they are not syntax.
___
*[v21.2/security-reference/authorization.md, line 84 at r29](https://reviewable.io/reviews/cockroachdb/docs/13037#-MxEFkZS-yeFnqNSePIk:-MxEFkZS-yeFnqNSePIl:b-91cdqa) ([raw file](https://github.com/cockroachdb/docs/blob/81069dae12fd743da0dee373f1e57fd1fc236e24/v21.2/security-reference/authorization.md#L84)):*
> ```Markdown
> 
> {{site.data.alerts.callout_success}}
> The terms “`admin` role” and “`role admin`” can be confusing. 
> ```

1) "role admin" should not be enclosed within backticks.

2) "role admin" is not a role option! It's a property of a user's membership in a role.
___
*[v21.2/security-reference/config-secure-hba.md, line 66 at r11](https://reviewable.io/reviews/cockroachdb/docs/13037#-Mx1AC0f2M6h4dDUyrv3:-MxEGpFx-YMzycFA0A4S:b-yuhwhl) ([raw file](https://github.com/cockroachdb/docs/blob/a0940a933d8910b67460d1d16c816eee7d777ef5/v21.2/security-reference/config-secure-hba.md#L66)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

why? I see ``` throughout the docs. Should I open a ticket to convert all the back-tick code blocks in the security docs to tilde code blocks?
</blockquote></details>

FYI: For SQL examples, we want to use a SQL box which gets a copy-paste button by the stylesheet.


<!-- Sent from Reviewable.io -->

2022-03-07 17:07 UTC, MichaelTrestman commented
Hi Raphael, as far as I could see, all of the comments were either addressed or scoped to follow up stories. Abhinav was very clear that I needed to time-scope this story, not fixing everything in all of the touched documents. Many of your comments fell outside of the scope of the ticket, and so were under my discretion to bump to future tickets (as per the advice of my management from both docs and security side).
There is still a lot that needs to be improved about our security docs (including technical inaccuracies that slipped through your review), but progress is incremental. Feel free to add your qualms to existing tickets in the docs security backlog or open a new issue. I appreciate your diligence and attention to detail, but I am subject to my PM and docs management as far as the prioritization of how I spend my time.





<!-- Sent from Reviewable.io -->