Clarify wording for Open SQL Transactions chart
cockroachdb/docs pull request #13205
Opened 2022-03-09 22:35 UTC by rafiss

This came up as a point of confusion on this community slack thread: https://cockroachdb.slack.com/archives/CP4D9LD5F/p1646720306266029

2022-03-09 22:35 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/13205)
<!-- Reviewable:end -->

2022-03-09 22:40 UTC, stbof commented
currently open SQL transactions on the node.

It seems redundant to say "currently open". Doesn't open mean the transaction is current?

2022-03-09 22:47 UTC, stbof requested changes
See my comment about removing "currently"  from the other bullets instead of adding it to the Open SQL Transactions bullet.

2022-07-26 13:14 UTC, maryliag commented
@rafiss just checking if this PR is still valid, since I didn't see any chances based on Stephanie's comments

2022-07-26 19:16 UTC, rafiss commented
I forgot about this. I can incorporate the comments; thanks Stephanie.

2022-07-26 19:22 UTC, stbof approved these changes

2022-07-26 19:29 UTC, merged