Moved Rust into beta support
cockroachdb/docs pull request #13236
Opened 2022-03-14 16:40 UTC by ericharmeling

Fixes https://cockroachlabs.atlassian.net/browse/DOC-2894.

See https://github.com/cockroachdb/example-app-rust-postgres.

After this is merged, I'll remove the `rust` directory from [`community-tooling-samples`](https://github.com/cockroachdb/community-tooling-samples).

2022-03-14 16:40 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/13236)
<!-- Reviewable:end -->

2022-03-14 17:47 UTC, nickvigilante requested changes
Few nits, but otherwise <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13236#-:-My8XgQDDGFlmCNvp61d:bub0hx0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling and @nvanbenschoten)

___
*[v21.1/install-client-drivers.md, line 382 at r1](https://reviewable.io/reviews/cockroachdb/docs/13236#-My8XJj54KrN34kXzQW4:-My8XJj54KrN34kXzQW5:b292pr0) ([raw file](https://github.com/cockroachdb/docs/blob/81ed181c7a9d1dabf331ee18a3d460987168ce09/v21.1/install-client-drivers.md#L382)):*
> ```Markdown
> **Support level:** Beta
> 
> Install the Rust Postgres driver as described in the <a href="https://crates.io/crates/postgres" data-proofer-ignore>official documentation</a>.
> ```

Any reason for using an HTML link instead of an MD link here?
___
*[v21.2/install-client-drivers.md, line 383 at r1](https://reviewable.io/reviews/cockroachdb/docs/13236#-My8XTu57xXJKp9fsllw:-My8XTu57xXJKp9fsllx:b-1av1q4) ([raw file](https://github.com/cockroachdb/docs/blob/81ed181c7a9d1dabf331ee18a3d460987168ce09/v21.2/install-client-drivers.md#L383)):*
> ```Markdown
> **Support level:** Beta
> 
> Install the Rust Postgres driver as described in the <a href="https://crates.io/crates/postgres" data-proofer-ignore>official documentation</a>.
> ```

Same nit
___
*[v22.1/install-client-drivers.md, line 383 at r1](https://reviewable.io/reviews/cockroachdb/docs/13236#-My8Xd3E2GPwFLsUA4wT:-My8Xd3E2GPwFLsUA4wU:b-1av1q4) ([raw file](https://github.com/cockroachdb/docs/blob/81ed181c7a9d1dabf331ee18a3d460987168ce09/v22.1/install-client-drivers.md#L383)):*
> ```Markdown
> **Support level:** Beta
> 
> Install the Rust Postgres driver as described in the <a href="https://crates.io/crates/postgres" data-proofer-ignore>official documentation</a>.
> ```

Same nit


<!-- Sent from Reviewable.io -->

2022-03-14 18:00 UTC, nvanbenschoten approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> thanks @ericharmeling! We weren't testing on the latest version (`v0.19.2`) of Rust-Postgres before, but I just updated the version in https://github.com/cockroachlabs/tpc-e/commit/abe73864977b764f996a4e3b3913e5fa5bdde5cf and everything still works.

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13236#-:-My8PVG97bDZm-V7toeV:bwl2rru)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ericharmeling)



<!-- Sent from Reviewable.io -->

2022-03-14 19:04 UTC, merged

2022-03-18 09:40 UTC, martingallagher commented
@ericharmeling was this tested in an asynchronous context, for example a query inside a async web framework handler such as Axum?

Here's my own take on a solution, both sync and async support: https://github.com/martingallagher/postgres-tx-retry

Note the `block_in_place` for the synchronous version.