Reduce left and right padding of inline code.
cockroachdb/docs pull request #13295
Opened 2022-03-21 16:05 UTC by stbof

https://cockroachlabs.atlassian.net/browse/DOC-2929

To review this you might have to hard clear your browser cache.

2022-03-21 16:46 UTC, nickvigilante requested changes
Follow this guide to make CSS changes: https://cockroachlabs.atlassian.net/wiki/spaces/ED/pages/1133150833/Make+CSS+Changes

You need to start by running `sass --watch /path/to/docs/css` and then making the change in `customstyles.scss` first, and then the map and css file will automatically update. Merge all three.

2022-03-21 17:14 UTC, stbof commented
@nickvigilante I'm not sure what you mean by updating the map. The wiki page doesn't refer to it.

I've done the other required update to the `.scss` file.  At some point the instructions will need to be updated because when I did `gem install sass` I got this:

Ruby Sass has reached end-of-life and should no longer be used.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  https://sass-lang.com/blog/posts/7828841

2022-03-21 17:25 UTC, stbof commented
> @stbof Every time you make a change to the scss, the `sass` app will make an update to `customstyles.css` and `customstyles.css.map`. Both of those need to be included in this PR. They're in the same directory of `$DOCSHOME/css`.

I ran `sass` and the changes you see in this commit https://github.com/cockroachdb/docs/pull/13295/commits/932af2222624315987841b8aa9a0be19f4b0272a reflect the result of running it.

2022-03-21 20:17 UTC, nickvigilante approved these changes

2022-03-30 17:27 UTC, lnhsingh approved these changes

2022-03-30 17:35 UTC, merged