Add principles to style guide
cockroachdb/docs pull request #13333
Opened 2022-03-24 14:30 UTC by kathancox

The style team has decided to include some principles for our style guide. The aim is to provide a framework for our decision process when writing, reviewing, and creating further style guidelines. These follow Cockroach Labs' values.

2022-03-24 14:50 UTC, kathancox commented
Hey @rmloveland @ericharmeling I have added the principles to the top of the guide. I probably haven't introduced them in the most refined way—so would appreciate any thoughts there! :-) 

cc @mikeCRL @lnhsingh

2022-03-24 21:20 UTC, rmloveland approved these changes
LGTM!

2022-03-25 13:52 UTC, mikeCRL requested changes
This is great. I left a few suggestions.

2022-03-25 13:52 UTC, mikeCRL commented on StyleGuide.md
> +- **Communicate Openly and Honestly:** We produce our best documentation when we communicate openly and honestly with our users. Understanding that documenting features and limitations transparently
```suggestion
- **Communicate Openly and Honestly:** We produce our best documentation when we communicate openly and honestly with our users. Documenting features and limitations transparently enables users to effectively use Cockroach Labs products while instilling confidence in the docs as a trusted resource.
```

2022-03-25 13:52 UTC, mikeCRL commented on StyleGuide.md
> +- **Establish balance:** We establish balance between complexity and accessibility for all users. We describe complex problems through accessible technical language and links to further information,
```suggestion
- **Establish balance:** We establish balance between complexity and accessibility for all users. We describe complex problems through accessible technical language and links to further information, without obfuscating meaning through unnecessarily complicated language. We also establish balance by always considering our style guidelines, but we can break these rules—or propose new rules—when it’s better for the user or promotes our other values.
```

2022-03-25 13:52 UTC, mikeCRL commented on StyleGuide.md
>  The following guidance is provided to ensure consistency.
While we're here

```suggestion
The following guidance is provided to benefit authors and reviewers by reflecting past style decisions while promoting consistency and readability across our content, which benefits all readers.
```

2022-04-05 19:15 UTC, kathancox commented
Hey @mikeCRL should be there now!

2022-04-11 19:49 UTC, mikeCRL approved these changes
LGTM!

2022-04-11 19:52 UTC, merged