Add new KB and organize by issue type.
cockroachdb/docs pull request #13416
Opened 2022-03-29 21:42 UTC by stbof

https://cockroachlabs.atlassian.net/browse/DOC-2411

2022-03-29 21:42 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/13416)
<!-- Reviewable:end -->

2022-04-01 20:06 UTC, florence-crl requested changes
Would you be able to change this confusing sentence to bullet points?

> Suppose you have a slow query has a GROUP BY clause, uses an index that has a STORING clause, and some or all of the columns in the query's GROUP BY clause are part of the index's STORING clause and are not index key columns

TO: 

In this scenario,
* the slow query has a GROUP BY clause,
* the slow query uses an index that has a STORING clause, and
* some or all of the columns in the query’s GROUP BY clause are part of the index’s STORING clause and are not index key columns.

2022-04-01 20:13 UTC, stbof commented on v22.1/query-behavior-troubleshooting.md
> +Suppose you have a slow query has a `GROUP BY` clause, uses an index that has a `STORING` clause, and some or all of the columns in the query's `GROUP BY` clause are part of the index's `STORING` cla
Suppose you have a slow query that

-  Has a `GROUP BY` clause.
-  Uses an index that has a `STORING` clause.
-  Where some or all of the columns in the query's `GROUP BY` clause are part of the index's `STORING` clause and are **not** index key columns. 

For example:

2022-04-01 20:14 UTC, stbof commented on v22.1/query-behavior-troubleshooting.md
> +Suppose you have a slow query has a `GROUP BY` clause, uses an index that has a `STORING` clause, and some or all of the columns in the query's `GROUP BY` clause are part of the index's `STORING` cla
```suggestion
Suppose you have a slow query that

-  Has a `GROUP BY` clause.
-  Uses an index that has a `STORING` clause.
-  Where some or all of the columns in the query's `GROUP BY` clause are part of the index's `STORING` clause and are **not** index key columns. 

For example:
```

2022-04-01 20:15 UTC, stbof commented
> Would you be able to change this confusing sentence to bullet points?
> 
> > Suppose you have a slow query has a GROUP BY clause, uses an index that has a STORING clause, and some or all of the columns in the query's GROUP BY clause are part of the index's STORING clause and are not index key columns
> 
> TO:
> 
> In this scenario,
> 
> * the slow query has a GROUP BY clause,
> * the slow query uses an index that has a STORING clause, and
> * some or all of the columns in the query’s GROUP BY clause are part of the index’s STORING clause and are not index key columns.

Fixed.

2022-04-01 20:16 UTC, florence-crl approved these changes
LGTM

2022-04-05 16:44 UTC, merged