Reorg cloud reqs and recs
cockroachdb/docs pull request #13527
Opened 2022-04-07 17:38 UTC by gemma-shay

DOC-2759

2022-04-07 17:38 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/13527)
<!-- Reviewable:end -->

2022-04-29 20:01 UTC, ianjevans requested changes
I like having this info pulled into its own topic. Most of my comments are just consistency nits.

2022-05-05 14:11 UTC, gemma-shay commented
@ianjevans is this good to go or do you want to re-review?

2022-05-05 17:30 UTC, gemma-shay commented
Whoops! Missed those. Should be good now.

2022-05-06 16:41 UTC, ianjevans approved these changes

2022-05-06 19:34 UTC, merged