Updated Prisma tutorial to use Prisma Migrate
cockroachdb/docs pull request #13548
Opened 2022-04-07 20:05 UTC by ericharmeling

Fixes https://cockroachlabs.atlassian.net/browse/DOC-3031.

Related to https://github.com/cockroachlabs/example-app-node-prisma/pull/2.

2022-04-07 20:05 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/13548)
<!-- Reviewable:end -->

2022-04-08 14:02 UTC, nickvigilante requested changes
One nit, otherwise <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13548#-:-N-8TtwfD-KmcF4OcJJQ:b-1jexg8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling and @kernfeld-cockroach)

___
*[v22.1/build-a-nodejs-app-with-cockroachdb-prisma.md, line 34 at r1](https://reviewable.io/reviews/cockroachdb/docs/13548#-N-8TOeE9F8idlE8a6mH:-N-8TOeE9F8idlE8a6mI:bzessg2) ([raw file](https://github.com/cockroachdb/docs/blob/0a44b32c3d543851b2a319be872e41614b313e9c/v22.1/build-a-nodejs-app-with-cockroachdb-prisma.md#L34)):*
> ```Markdown
>     ~~~
> 
> 1. Navigate to the project directory and install the application dependencies:
> ```

Is the project directory different from the directory where you've cloned the repo? If not, is it necessary to say navigate to the project directory?


<!-- Sent from Reviewable.io -->

2022-04-11 17:09 UTC, kernfeld-cockroach approved these changes
LGTM!

2022-04-12 17:29 UTC, ericharmeling reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13548#-:-N-ToeNL5iIhGKJc2zJN:bz5mair)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nickvigilante)

___
*[v22.1/build-a-nodejs-app-with-cockroachdb-prisma.md, line 34 at r1](https://reviewable.io/reviews/cockroachdb/docs/13548#-N-8TOeE9F8idlE8a6mH:-N-ToZkXC96WFI7mZ6o7:b-qg95x2) ([raw file](https://github.com/cockroachdb/docs/blob/0a44b32c3d543851b2a319be872e41614b313e9c/v22.1/build-a-nodejs-app-with-cockroachdb-prisma.md#L34)):*
<details><summary><i>Previously, nickvigilante (Nick Vigilante) wrote…</i></summary><blockquote>

Is the project directory different from the directory where you've cloned the repo? If not, is it necessary to say navigate to the project directory?
</blockquote></details>

Good idea. Took that first clause out.


<!-- Sent from Reviewable.io -->

2022-04-12 18:18 UTC, merged