DOC-3238 v21.2.9 release notes
cockroachdb/docs pull request #13573
Opened 2022-04-11 17:20 UTC by andf-crl

Addresses: DOC-3238
- Release notes for upcoming v21.2.9 release
- Targeted for 04-12-2022

Known Issue: investigating why script created two discrete entries for #79505, with different descriptions. As this PR is timely, I wanted to provide everything else for review asap. Thanks!

Note: this release required a cherry-pick adaptation of the usual RN generation process. That cherry-picked PR is #79662, which is manually included. I incremented line 52 of `v21.2.9.md` accordingly.

Thanks!

2022-04-11 17:20 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/13573)
<!-- Reviewable:end -->

2022-04-11 17:59 UTC, taroface requested changes
Some formatting nits and suggestions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13573#-:-N-Olwao2tZB0gPajXP6:b-p9kzl2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andf-crl and @taroface)

___
*[_includes/releases/v21.2/v21.2.9.md, line 19 at r1](https://reviewable.io/reviews/cockroachdb/docs/13573#-N-Oh2gOCmGPkerJobRb:-N-Oh2gOCmGPkerJobRc:blilgul) ([raw file](https://github.com/cockroachdb/docs/blob/96f042ddbb3f619590be3aecbda3178e9d50b061/_includes/releases/v21.2/v21.2.9.md#L19)):*
> ```Markdown
> <h3 id="v21-2-9-db-console-changes">DB Console changes</h3>
> 
> - Minor styling changes on the DB Console's [Hot Ranges Page](../v21.2/ui-hot-ranges-page.html) to follow the same style as other pages. [#79498][#79498]
> ```

this can be lowercase.



_Code quote:_
```Markdown
Page
```
___
*[_includes/releases/v21.2/v21.2.9.md, line 23 at r1](https://reviewable.io/reviews/cockroachdb/docs/13573#-N-Oh5r7-ZhQPCkHpLFN:-N-Oh5r7-ZhQPCkHpLFO:b-z9l72v) ([raw file](https://github.com/cockroachdb/docs/blob/96f042ddbb3f619590be3aecbda3178e9d50b061/_includes/releases/v21.2/v21.2.9.md#L23)):*
> ```Markdown
> <h3 id="v21-2-9-bug-fixes">Bug fixes</h3>
> 
> - Fixed [`num_runs`](../v21.2/show-jobs.html) being incremented twice for certain jobs upon being started [#79051][#79051]
> ```

Add a period after this sentence.
___
*[_includes/releases/v21.2/v21.2.9.md, line 25 at r1](https://reviewable.io/reviews/cockroachdb/docs/13573#-N-OjcDC20Jz1mh6nOWP:-N-OjcDC20Jz1mh6nOWQ:b2d129t) ([raw file](https://github.com/cockroachdb/docs/blob/96f042ddbb3f619590be3aecbda3178e9d50b061/_includes/releases/v21.2/v21.2.9.md#L25)):*
> ```Markdown
> - Fixed [`num_runs`](../v21.2/show-jobs.html) being incremented twice for certain jobs upon being started [#79051][#79051]
> - Index usage stats are now properly captured for index joins. [#79240][#79240]
> - [`ALTER TABLE [ADD|DROP] COLUMN`](../v21.2/alter-table.html) are now subject to [admission control](../v21.2/architecture/admission-control.html), which will prevent these operations from overloading the storage engine. [#79211][#79211]
> ```

The preview isn't working, so I can't currently check this, but I wonder if the square brackets within the SQL syntax are confusing the Markdown?



_Code quote:_
```Markdown
[`ALTER TABLE [ADD|DROP] COLUMN`]
```
___
*[_includes/releases/v21.2/v21.2.9.md, line 26 at r1](https://reviewable.io/reviews/cockroachdb/docs/13573#-N-Ojm809U9I47VnJQSn:-N-Ojm809U9I47VnJQSo:bg6dxi4) ([raw file](https://github.com/cockroachdb/docs/blob/96f042ddbb3f619590be3aecbda3178e9d50b061/_includes/releases/v21.2/v21.2.9.md#L26)):*
> ```Markdown
> - Index usage stats are now properly captured for index joins. [#79240][#79240]
> - [`ALTER TABLE [ADD|DROP] COLUMN`](../v21.2/alter-table.html) are now subject to [admission control](../v21.2/architecture/admission-control.html), which will prevent these operations from overloading the storage engine. [#79211][#79211]
> - Fixed a performance regression released in 21.1.7 that reverted [`BACKUP`](../v21.2/backup.html) to its pre-21.2.5 memory usage and run time during planning of larger backups with many prior incremental layers. [#79267][#79267]
> ```

v21.1.7



_Code quote:_
```Markdown
21.1.7
```
___
*[_includes/releases/v21.2/v21.2.9.md, line 26 at r1](https://reviewable.io/reviews/cockroachdb/docs/13573#-N-OjoNUAMpRjK1cvrzl:-N-OjoNUAMpRjK1cvrzm:bg6dy8r) ([raw file](https://github.com/cockroachdb/docs/blob/96f042ddbb3f619590be3aecbda3178e9d50b061/_includes/releases/v21.2/v21.2.9.md#L26)):*
> ```Markdown
> - Index usage stats are now properly captured for index joins. [#79240][#79240]
> - [`ALTER TABLE [ADD|DROP] COLUMN`](../v21.2/alter-table.html) are now subject to [admission control](../v21.2/architecture/admission-control.html), which will prevent these operations from overloading the storage engine. [#79211][#79211]
> - Fixed a performance regression released in 21.1.7 that reverted [`BACKUP`](../v21.2/backup.html) to its pre-21.2.5 memory usage and run time during planning of larger backups with many prior incremental layers. [#79267][#79267]
> ```

v21.2.5



_Code quote:_
```Markdown
21.2.5
```
___
*[_includes/releases/v21.2/v21.2.9.md, line 26 at r1](https://reviewable.io/reviews/cockroachdb/docs/13573#-N-Ojps99Q6tou0pjbZX:-N-Ojps99Q6tou0pjbZY:b-78e9ob) ([raw file](https://github.com/cockroachdb/docs/blob/96f042ddbb3f619590be3aecbda3178e9d50b061/_includes/releases/v21.2/v21.2.9.md#L26)):*
> ```Markdown
> - Index usage stats are now properly captured for index joins. [#79240][#79240]
> - [`ALTER TABLE [ADD|DROP] COLUMN`](../v21.2/alter-table.html) are now subject to [admission control](../v21.2/architecture/admission-control.html), which will prevent these operations from overloading the storage engine. [#79211][#79211]
> - Fixed a performance regression released in 21.1.7 that reverted [`BACKUP`](../v21.2/backup.html) to its pre-21.2.5 memory usage and run time during planning of larger backups with many prior incremental layers. [#79267][#79267]
> ```

runtime (?)



_Code quote:_
```Markdown
run time
```
___
*[_includes/releases/v21.2/v21.2.9.md, line 28 at r1](https://reviewable.io/reviews/cockroachdb/docs/13573#-N-Oj_Nz22-ytFbsJDKP:-N-Oj_Nz22-ytFbsJDKQ:b-t4mejt) ([raw file](https://github.com/cockroachdb/docs/blob/96f042ddbb3f619590be3aecbda3178e9d50b061/_includes/releases/v21.2/v21.2.9.md#L28)):*
> ```Markdown
> - Fixed a performance regression released in 21.1.7 that reverted [`BACKUP`](../v21.2/backup.html) to its pre-21.2.5 memory usage and run time during planning of larger backups with many prior incremental layers. [#79267][#79267]
> - Fixed a bug where [`SHOW SCHEMAS FROM <schema>`](../v21.2/show-schemas.html) would not include user-defined schemas. [#79307][#79307]
> - Previously [`IMPORT INTO`](../v21.2/import-into.html) could create duplicate entries for [`UNIQUE`](../v21.2/unique.html) constraints in [`REGIONAL BY ROW`](../v21.2/multiregion-overview#regional-by-row-tables) tables and tables utilizing `UNIQUE WITHOUT INDEX` constraints. A new post-`IMPORT` validation step for those tables now fails and rolls back the `IMPORT` in such cases. [#79326][#79326]
> ```

This link is breaking the build. Does it exist?



_Code quote:_
```Markdown
../v21.2/multiregion-overview#regional-by-row-tables
```
___
*[_includes/releases/v21.2/v21.2.9.md, line 28 at r1](https://reviewable.io/reviews/cockroachdb/docs/13573#-N-OjvGQ1vdH7BwBDNiq:-N-OjvGQ1vdH7BwBDNir:bjsk9to) ([raw file](https://github.com/cockroachdb/docs/blob/96f042ddbb3f619590be3aecbda3178e9d50b061/_includes/releases/v21.2/v21.2.9.md#L28)):*
> ```Markdown
> - Fixed a performance regression released in 21.1.7 that reverted [`BACKUP`](../v21.2/backup.html) to its pre-21.2.5 memory usage and run time during planning of larger backups with many prior incremental layers. [#79267][#79267]
> - Fixed a bug where [`SHOW SCHEMAS FROM <schema>`](../v21.2/show-schemas.html) would not include user-defined schemas. [#79307][#79307]
> - Previously [`IMPORT INTO`](../v21.2/import-into.html) could create duplicate entries for [`UNIQUE`](../v21.2/unique.html) constraints in [`REGIONAL BY ROW`](../v21.2/multiregion-overview#regional-by-row-tables) tables and tables utilizing `UNIQUE WITHOUT INDEX` constraints. A new post-`IMPORT` validation step for those tables now fails and rolls back the `IMPORT` in such cases. [#79326][#79326]
> ```

Nit: Add comma



_Code quote:_
```Markdown
Previously
```
___
*[_includes/releases/v21.2/v21.2.9.md, line 28 at r1](https://reviewable.io/reviews/cockroachdb/docs/13573#-N-Ok-l0Bh3RlLGA19Vm:-N-Ok-l0Bh3RlLGA19Vn:b-w4g1vh) ([raw file](https://github.com/cockroachdb/docs/blob/96f042ddbb3f619590be3aecbda3178e9d50b061/_includes/releases/v21.2/v21.2.9.md#L28)):*
> ```Markdown
> - Fixed a performance regression released in 21.1.7 that reverted [`BACKUP`](../v21.2/backup.html) to its pre-21.2.5 memory usage and run time during planning of larger backups with  [...]

2022-04-11 22:40 UTC, andf-crl reviewed
Thank you Ryan -- great feedback! I apologize for all the nits in last round, had a bunch staged that never made it up: still finding the balance with squashing / amending. Sorry about that; think I've got it now.

Build still fails, but this time I don't think it's me. Let me know if you can tell otherwise or I can raise with the team.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13573#-:-N-Pjx3G-3tJUMzP0JD_:bf34cqx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andf-crl and @taroface)

___
*[_includes/releases/v21.2/v21.2.9.md, line 25 at r1](https://reviewable.io/reviews/cockroachdb/docs/13573#-N-OjcDC20Jz1mh6nOWP:-N-PUk990eIA3nM5loKJ:b-msmc3f) ([raw file](https://github.com/cockroachdb/docs/blob/96f042ddbb3f619590be3aecbda3178e9d50b061/_includes/releases/v21.2/v21.2.9.md#L25)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

The preview isn't working, so I can't currently check this, but I wonder if the square brackets within the SQL syntax are confusing the Markdown?
</blockquote></details>

You're right, broke this out to the two explicit commands.
___
*[_includes/releases/v21.2/v21.2.9.md, line 28 at r1](https://reviewable.io/reviews/cockroachdb/docs/13573#-N-Oj_Nz22-ytFbsJDKP:-N-PWYu51FRAvTXztDBd:b-uil9bt) ([raw file](https://github.com/cockroachdb/docs/blob/96f042ddbb3f619590be3aecbda3178e9d50b061/_includes/releases/v21.2/v21.2.9.md#L28)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

This link is breaking the build. Does it exist?
</blockquote></details>

Fixed. Missing the `.html` before the anchor text. Thank you!

However, `htmltest` is still failing due to something that appears unrelated:

6:22:22 PM: docs/v22.1/backup.html
6:22:22 PM:   hash does not exist --- docs/v22.1/backup.html --> sql-grammar.html#subdirectory
___
*[_includes/releases/v21.2/v21.2.9.md, line 28 at r1](https://reviewable.io/reviews/cockroachdb/docs/13573#-N-Ok-l0Bh3RlLGA19Vm:-N-PWfbQ49skmZmFC2-j:b-hmkg4n) ([raw file](https://github.com/cockroachdb/docs/blob/96f042ddbb3f619590be3aecbda3178e9d50b061/_includes/releases/v21.2/v21.2.9.md#L28)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

link `import.html`.
</blockquote></details>

Believe this only applies to IMPORT INTO, and not IMPORT alone. References to IMPORT in the engineer's PR release note (bug fix) entry were likely meant as shorthand for IMPORT INTO. I've expanded all references to explicitly use IMPORT INTO to avoid this confusion.
___
*[_includes/releases/v21.2/v21.2.9.md, line 31 at r1](https://reviewable.io/reviews/cockroachdb/docs/13573#-N-OkFn8Axa3em1Ojf3V:-N-PXJKIEuCDefZoZ3VP:b4ybrvq) ([raw file](https://github.com/cockroachdb/docs/blob/96f042ddbb3f619590be3aecbda3178e9d50b061/_includes/releases/v21.2/v21.2.9.md#L31)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

"in some cases" feels potentially confusing/unhelpful without more detail. I wonder if we could clarify with the PR author's help?
</blockquote></details>

I agree and thought the same thing. When I looked at the upstream PR, I found the desc to be pretty low level (storage layer: vectorized engine, specific array-based memory exhaustion trigger), so I deemed it inappropriate for RNs. However, your comment prompted me to find vectorized-execution.html#disk-spilling-operations which I think could help to clarify. I've added a little clarification in reliance on this resource. However, my edits-to-clarify may not be as technically-correct as the engineer's intent. Will run by upstream now also.


<!-- Sent from Reviewable.io -->

2022-04-12 17:56 UTC, andf-crl reviewed
TYFR!! Eng approved edit to #79353 description this morning. Also requested a removal of #79191, which has been reverted for this release. Ready to go for GA date.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13573#-:-N-Ts_By7S2KFbhX0Wqk:b-k0gs64)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andf-crl and @taroface)



<!-- Sent from Reviewable.io -->

2022-04-13 16:28 UTC, merged