WITH GRANT OPTION support
cockroachdb/docs pull request #13645
Opened 2022-04-19 21:41 UTC by gemma-shay

2022-04-19 21:41 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/13645)
<!-- Reviewable:end -->

2022-04-22 16:49 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13645)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @rafiss)

___
*[v22.1/grant.md, line 43 at r2](https://reviewable.io/reviews/cockroachdb/docs/13645#-N0GyLTpAMhHU70ilWLA:-N0HADHsDtNK3IVFlG7F:b-xl3dyn) ([raw file](https://github.com/cockroachdb/docs/blob/37645dc53ce5077f601bcab132378784d0ced58d/v22.1/grant.md#L43)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this part should be updated too:

"must have the `SELECT` privileges on that table, with the `SELECT` grant option"

(or some other phrasing that is more clear)
</blockquote></details>

maybe ""must have the `SELECT` privileges on that table, and the grant option on `SELECT`"


<!-- Sent from Reviewable.io -->

2022-04-29 20:03 UTC, ianjevans reviewed
Just a quick grammar nit.

2022-04-29 20:03 UTC, ianjevans commented on v22.1/grant.md
> +You can use `GRANT` to directly grant privileges to a role or user, or you can grant membership to an existing role, which grants that role's privileges to the grantee. Users granted a privilege with
```suggestion
You can use `GRANT` to directly grant privileges to a role or user, or you can grant membership to an existing role, which grants that role's privileges to the grantee. Users granted a privilege with `WITH GRANT OPTION` can in turn grant that privilege to others. The owner of an object implicitly has the `GRANT OPTION` for all privileges, and the `GRANT OPTION` is inherited through role memberships.
```

2022-04-29 21:37 UTC, merged