Decompose term files.
cockroachdb/docs pull request #13677
Opened 2022-04-21 21:05 UTC by stbof

2022-04-21 21:05 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/13677)
<!-- Reviewable:end -->

2022-04-21 21:29 UTC, jseldess requested changes
The h2 headings nest properly on this page: https://deploy-preview-13677--cockroachdb-docs.netlify.app/docs/stable/architecture/glossary.html

But not on these pages:
https://deploy-preview-13677--cockroachdb-docs.netlify.app/docs/stable/architecture/overview.html
https://deploy-preview-13677--cockroachdb-docs.netlify.app/docs/stable/architecture/reads-and-writes-overview.html

2022-04-21 22:58 UTC, stbof commented
> https://deploy-preview-13677--cockroachdb-docs.netlify.app/docs/stable/architecture/reads-and-writes-overview.html

Fixed.

2022-04-22 01:27 UTC, jseldess approved these changes
LGTM. Thanks, @stbof.

2022-04-22 01:45 UTC, merged