docs: add github issue links for sql features
cockroachdb/docs pull request #13681
Opened 2022-04-22 09:17 UTC by hongaar

Add links to GitHub issues for tracking support for stored procedures and triggers.

2022-04-22 09:17 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/13681)
<!-- Reviewable:end -->

2022-05-05 23:25 UTC, lnhsingh requested changes
@hongaar Thank you for contributing to our docs! Please edit based on my feedback and add your updates to the copy of the doc in the `v22.1` directory as well. Let me know if you have any questions!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13681#-:-N1LWtGk57cRomhlXkYR:b-nq0nol)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @hongaar and @lnhsingh)

___
*[`v21.2/sql-feature-support.md` line 190 at r1](https://reviewable.io/reviews/cockroachdb/docs/13681#-N1LXQkQE-IMQvMd21ZK:-N1LX1LuEqoTR2KNF5H-:b68sxab) ([raw file](https://github.com/cockroachdb/docs/blob/93769c7bbeab438809b114c040e681043b52e5fb/v21.2/sql-feature-support.md#L190)):*
> ```Markdown
>  Window functions | ✓ | Standard | [Window Functions documentation](window-functions.html)
>  Common table expressions | Partial | Common Extension | [Common Table Expressions documentation](common-table-expressions.html)
>  Stored procedures | ✗ | Common Extension | Execute a procedure explicitly. [GitHub issue tracking support for stored procedures](https://github.com/cockroachdb/cockroach/issues/17511).
> ```

Please edit the link text to say "GitHub issue tracking stored procedures support", to match the existing language in the table above.
___
*[`v21.2/sql-feature-support.md` line 192 at r1](https://reviewable.io/reviews/cockroachdb/docs/13681#-N1LX_kH1Vyo6GFlIWc6:-N1LX_kH1Vyo6GFlIWc7:b-6vwwd3) ([raw file](https://github.com/cockroachdb/docs/blob/93769c7bbeab438809b114c040e681043b52e5fb/v21.2/sql-feature-support.md#L192)):*
> ```Markdown
>  Stored procedures | ✗ | Common Extension | Execute a procedure explicitly. [GitHub issue tracking support for stored procedures](https://github.com/cockroachdb/cockroach/issues/17511).
>  Cursors | ✗ | Standard | Traverse a table's rows.
>  Triggers | ✗ | Standard | Execute a set of commands whenever a specified event occurs. [GitHub issue tracking support for triggers](https://github.com/cockroachdb/cockroach/issues/28296).
> ```

Please edit the link text to say "GitHub issue tracking trigger support"


<!-- Sent from Reviewable.io -->

2022-05-09 08:47 UTC, hongaar commented
@lnhsingh pushed the requested changes. Also added `node_modules` to `.gitignore` for DX reasons, let me know if you want me to revert this.

2022-05-16 14:12 UTC, lnhsingh reviewed
@hongaar looks great, I will merge. Thank you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13681#-:-N2CCUNy1sD2nOlxZ_Dh:bosd3vb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @hongaar and @lnhsingh)



<!-- Sent from Reviewable.io -->

2022-05-16 14:12 UTC, merged