DOC-2123 add alerting rules endpoint, events
cockroachdb/docs pull request #13692
Opened 2022-04-22 18:34 UTC by andf-crl

Addresses: DOC-2123
CRDB: (couldn't find in Jira)

- Added new `Alerting tools` section to `v22.1/monitoring-and-alerting.md`, showcasing new metrics endpoint, including: 
  - Accessing the new endpoint, configuring Alertmanager, configuring Prometheus
  - Expanded `Events to alert on` to include location of corresponding rules definition, some from old pre-defined `yaml` file, some from this PR.
- Updated code examples to use latest Prometheus | Alertmanager values on `v22.1/monitor-cockroachdb-with-prometheus.md`
- Fixed broken link on `v21.2/monitoring-and-alerting.md`

[v22.1/monitoring-and-alerting.md](url) | [ v22.1/monitor-cockroachdb-with-prometheus.md](url) | [v21.2/monitoring-and-alerting.md](url)

2022-04-22 18:34 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/13692)
<!-- Reviewable:end -->

2022-04-22 18:48 UTC, andf-crl reviewed
Hello -- I have added a few notes and questions inline below. Let me know your thoughts or feel free to reach out on Slack to discuss. Thanks so much for your time!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13692#-:-N0H_szB2iIaJGacy-kD:b-rgyads)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[v22.1/monitor-cockroachdb-with-prometheus.md, line 99 at r1](https://reviewable.io/reviews/cockroachdb/docs/13692#-N0HYZduB3OL-czwQiw2:-N0HYZduB3OL-czwQiw3:b-txoyjl) ([raw file](https://github.com/cockroachdb/docs/blob/d2e79991d24e893d053b67edfdd37b6ffcd7eb02/v22.1/monitor-cockroachdb-with-prometheus.md#L99)):*
> ```Markdown
>     ts=2022-04-20T18:57:46.811Z caller=main.go:1142 level=info msg="Loading configuration file" filename=prometheus.yml
>     ts=2022-04-20T18:57:46.973Z caller=main.go:1179 level=info msg="Completed loading of configuration file" filename=prometheus.yml totalDuration=162.470967ms db_storage=1.057µs remote_storage=5.151µs web_handler=457ns query_engine=889ns scrape=150.34215ms scrape_sd=74.253µs notify=94.531µs notify_sd=26.921µs rules=11.488407ms tracing=19.58µs
>     ts=2022-04-20T18:57:46.973Z caller=main.go:910 level=info msg="Server is ready to receive web requests."
> ```

New log format for `prometheus.log`
___
*[v22.1/monitor-cockroachdb-with-prometheus.md, line 134 at r1](https://reviewable.io/reviews/cockroachdb/docs/13692#-N0HYgK_BVNPdj6Ca0j5:-N0HYgK_BVNPdj6Ca0j6:b-hvlsbd) ([raw file](https://github.com/cockroachdb/docs/blob/d2e79991d24e893d053b67edfdd37b6ffcd7eb02/v22.1/monitor-cockroachdb-with-prometheus.md#L134)):*
> ```Markdown
>     {% include copy-clipboard.html %}
>     ~~~ shell
>     $ alertmanager --config.file=alertmanager.yml
> ```

New naming convention for Alertmanager conf filename
___
*[v22.1/monitoring-and-alerting.md, line 145 at r1](https://reviewable.io/reviews/cockroachdb/docs/13692#-N0HYmhD61zCr-hcEDB5:-N0HYmhD61zCr-hcEDB6:b-hk2bm9) ([raw file](https://github.com/cockroachdb/docs/blob/d2e79991d24e893d053b67edfdd37b6ffcd7eb02/v22.1/monitoring-and-alerting.md#L145)):*
> ```Markdown
> {{site.data.alerts.callout_info}}
> In addition to using the exported time series data to monitor a cluster via an external system, you can write alerting rules against them to make sure you are promptly notified of critical events or issues that may require intervention or investigation. See [Events to alert on](#events-to-alert-on) for more details.
> {{site.data.alerts.end}}
> ```

Fixes broken link in alert by moving `{{site.data.alerts.*}}` to their own lines.
___
*[v22.1/monitoring-and-alerting.md, line 157 at r1](https://reviewable.io/reviews/cockroachdb/docs/13692#-N0H_BRR7dSpZUaUARCS:-N0H_BRR7dSpZUaUARCT:b-b8vhku) ([raw file](https://github.com/cockroachdb/docs/blob/d2e79991d24e893d053b67edfdd37b6ffcd7eb02/v22.1/monitoring-and-alerting.md#L157)):*
> ```Markdown
> #### Prometheus alerting rules endpoint
> 
> <span class="version-tag">New in v22.1:</span> Every node of a CockroachDB cluster exports an alerting rules template at `http://<host>:<http-port>/api/v2/rules`. These rule definitions are formatted for easy integration with Prometheus' Alertmanager, and require minimal editing.
> ```

Re: "minimal editing" -- I did not appear to need to edit the rules from the rules endpoint: copy and paste per the below instructions worked for me. You mention in DOC-2123 potentially needing to edit these rules. How so?

Note: I did not attempt to import any `recording` rules. Perhaps those require manual editing?

If any rules do require manual editing beyond the steps I've outlined below, could you supply an example edit of one such rule? Thank you!
___
*[v22.1/monitoring-and-alerting.md, line 161 at r1](https://reviewable.io/reviews/cockroachdb/docs/13692#-N0HaE-X1xHFb2h-j-nz:-N0HaE-X1xHFb2h-j-o-:b-xy75um) ([raw file](https://github.com/cockroachdb/docs/blob/d2e79991d24e893d053b67edfdd37b6ffcd7eb02/v22.1/monitoring-and-alerting.md#L161)):*
> ```Markdown
> {% include_cached copy-clipboard.html %}
> ~~~ shell
> $ curl http://localhost:8080/api/v2/rules
> ```

Note: currently this does not work, and I must append a trailing `/` character to get it working. I made a note about this in DOC-2123. Ideally we support the URL without the trailing slash, as with other other endpoints we expose.
___
*[v22.1/monitoring-and-alerting.md, line 177 at r1](https://reviewable.io/reviews/cockroachdb/docs/13692#-N0HYve11YmqEzQr09Cu:-N0HYve11YmqEzQr09Cv:bskx6n1) ([raw file](https://github.com/cockroachdb/docs/blob/d2e79991d24e893d053b67edfdd37b6ffcd7eb02/v22.1/monitoring-and-alerting.md#L177)):*
> ```Markdown
>           annotations:
>             {% raw %}summary: Instance {{ $labels.instance }} has {{ $value }} tripped per-Replica circuit breakers{% endraw %}
> ...
> ```

I edited this to match `alert` with `expr` with `annotations` temporarily. Will update to match exactly when you merge your PR fix to this.
___
*[v22.1/monitoring-and-alerting.md, line 232 at r1](https://reviewable.io/reviews/cockroachdb/docs/13692#-N0HZEwzCT1NGZa58PYp:-N0HZEwzCT1NGZa58PYq:bcuw2m0) ([raw file](https://github.com/cockroachdb/docs/blob/d2e79991d24e893d053b67edfdd37b6ffcd7eb02/v22.1/monitoring-and-alerting.md#L232)):*
> ```Markdown
> {{site.data.alerts.callout_info}}
> Currently, not all events listed have corresponding alert rule definitions available from the the `api/v2/rules` endpoint. Events not yet available in this manner are either defined in the <a href="https://github.com/cockroachdb/cockroach/blob/master/monitoring/rules/alerts.rules.yml">pre-defined alerting rules</a> instead, or are forthcoming. For more details, see [Monitor CockroachDB with Prometheus](monitor-cockroachdb-with-prometheus.html).
> {{site.data.alerts.end}}
> ```

Temporary alert until 22.1.1 when you merge #80274. Will likewise update all events below to point to rules endpoint as well.
___
*[v22.1/monitoring-and-alerting.md, line 264 at r1](https://reviewable.io/reviews/cockroachdb/docs/13692#-N0HZVvv3G0DjVNMO3Cy:-N0HZVvv3G0DjVNMO3Cz:b-fmjyx6) ([raw file](https://github.com/cockroachdb/docs/blob/d2e79991d24e893d053b67edfdd37b6ffcd7eb02/v22.1/monitoring-and-alerting.md#L264)):*
> ```Markdown
> - **How to detect:** The `sql_conns` metric in the node's `_status/vars` output will be greater than `0` while the `sql_query_count` metric will be `0`. You can also break this down by statement type using `sql_select_count`, `sql_insert_count`, `sql_update_count`, and `sql_delete_count`.
> 
> - **Rule definition:** A rule definition for this alert is forthcoming.
> ```

This and other instance of this sentence to be adjusted post-#80274
___
*[v22.1/monitoring-and-alerting.md, line 330 at r1](https://reviewable.io/reviews/cockroachdb/docs/13692#-N0HZpWt7YhtmsXF7yN7:-N0HZpWt7YhtmsXF7yN8:b-sxe43d) ([raw file](https://github.com/cockroachdb/docs/blob/d2e79991d24e893d053b67edfdd37b6ffcd7eb02/v22.1/monitoring-and-alerting.md#L330)):*
> ```Markdown
> - **Rule definition:** Use the `HighOpenFDCount` alerting rule from your cluster's [`api/v2/rules` metrics endpoint](#alertmanager).
> 
> #### Node capacity
> ```

I am unclear on the differences between the various `capacity`-type recording rules, and have supplied my best guess. Please correct me liberally!

For example: what is the difference between `capacity`, `node:capacity`, and `cluster:capacity` ?


<!-- Sent from Reviewable.io -->

2022-04-27 17:41 UTC, rimadeodhar requested changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13692)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andf-crl and @rimadeodhar)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/cockroachdb/docs/13692#-N0g1QlBC2nvr9BwIcIL):*
Nit: Could your commit message be the same as your overall PR summary? Thanks.
___
*[`v22.1/monitoring-and-alerting.md` line 161 at r1](https://reviewable.io/reviews/cockroachdb/docs/13692#-N0HaE-X1xHFb2h-j-nz:-N0g3vcY7bwyxU7q5nmR:bybeo2g) ([raw file](https://github.com/cockroachdb/docs/blob/d2e79991d24e893d053b67edfdd37b6ffcd7eb02/v22.1/monitoring-and-alerting.md#L161)):*
<details><summary><i>Previously, andf-crl wrote…</i></summary><blockquote>

Note: currently this does not work, and I must append a trailing `/` character to get it working. I made a note about this in DOC-2123. Ideally we support the URL without the trailing slash, as with other other endpoints we expose.
</blockquote></details>

Thanks for calling this out. I'll fix this in an upcoming PR.
___
*[`v22.1/monitoring-and-alerting.md` line 330 at r1](https://reviewable.io/reviews/cockroachdb/docs/13692#-N0HZpWt7YhtmsXF7yN7:-N0g4f5u5PGS-Vtkv8xu:b6r3i8p) ([raw file](https://github.com/cockroachdb/docs/blob/d2e79991d24e893d053b67edfdd37b6ffcd7eb02/v22.1/monitoring-and-alerting.md#L330)):*
<details><summary><i>Previously, andf-crl wrote…</i></summary><blockquote>

I am unclear on the differences between the various `capacity`-type recording rules, and have supplied my best guess. Please correct me liberally!

For example: what is the difference between `capacity`, `node:capacity`, and `cluster:capacity` ?
</blockquote></details>

So these alerts are different from the recording rules. For node capacity alert, I've added a "NodeCapacityLow" alert in my PR https://github.com/cockroachdb/cockroach/pull/80274.

I don't think we should add the recording rules as alerts btw. The recording (or aggregation rules) only specify how a metric is to be aggregated not used for alerting. We can mention aggregation rules as guidelines on how metrics should be aggregated to view them on Prometheus/Grafana.

Regarding the difference between the individual aggregation rules, I don't believe there is any `capacity` rule, is there? We do have `node:capacity` which talks above total capacity of an individual node while `cluster:capacity` is at the overall cluster level.
___
*[`v22.1/monitoring-and-alerting.md` line 288 at r2](https://reviewable.io/reviews/cockroachdb/docs/13692#-N0g4Sxw0hUYhADk9W3U:-N0g4Sxw0hUYhADk9W3V:b87545a) ([raw file](https://github.com/cockroachdb/docs/blob/7ce41ac1fc33278ddb604e4a353a712d2085f869/v22.1/monitoring-and-alerting.md#L288)):*
> ```Markdown
> - **How to detect:** Calculate this using a threshold, where the threshold is less than the value of the [`gc.ttlseconds`](configure-replication-zones.html#replication-zone-variables) variable. For example, `changefeed.max_behind_nanos > [some threshold]`.
> 
> - **Rule definition:** A rule definition for this alert is forthcoming.
> ```

There is no way to include this in the `rules` endpoint because the threshold depends on the individual cluster setting which isn't available to us. 


<!-- Sent from Reviewable.io -->

2022-04-29 17:39 UTC, andf-crl reviewed
Thanks so much for your helpful responses! I've removed all recording rules and adapted copy accordingly. Please let me know if you'd like to see any additional changes -- thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13692#-:-N0qOmM8BAsuRdD0y6SX:b9tyu82)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rimadeodhar)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/cockroachdb/docs/13692#-N0g1QlBC2nvr9BwIcIL):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Nit: Could your commit message be the same as your overall PR summary? Thanks.
</blockquote></details>

Hi, this is not our convention in docs. Normally the PR desc would appear above as the first comment (see https://reviewable.io/reviews/cockroachdb/docs/13653#- for an example), but Exalate syncing has been broken of late per DEVINF-366. Apologies for the inconvenience during its troubleshooting.
___
*[`v22.1/monitoring-and-alerting.md` line 161 at r1](https://reviewable.io/reviews/cockroachdb/docs/13692#-N0HaE-X1xHFb2h-j-nz:-N0qHOph97Es8AUFJyjF:btgv9nk) ([raw file](https://github.com/cockroachdb/docs/blob/d2e79991d24e893d053b67edfdd37b6ffcd7eb02/v22.1/monitoring-and-alerting.md#L161)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Thanks for calling this out. I'll fix this in an upcoming PR.
</blockquote></details>

I've added the trailing slash for 22.1 GA. Will change when your upcoming PR merges the fix for 22.1.1, etc. Feel free to ping me when you merge it & I'll update quickly!
___
*[`v22.1/monitoring-and-alerting.md` line 330 at r1](https://reviewable.io/reviews/cockroachdb/docs/13692#-N0HZpWt7YhtmsXF7yN7:-N0qFSJBDaoysOUKZYdF:b-2osz0k) ([raw file](https://github.com/cockroachdb/docs/blob/d2e79991d24e893d053b67edfdd37b6ffcd7eb02/v22.1/monitoring-and-alerting.md#L330)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

So these alerts are different from the recording rules. For node capacity alert, I've added a "NodeCapacityLow" alert in my PR https://github.com/cockroachdb/cockroach/pull/80274.

I don't think we should add the recording rules as alerts btw. The recording (or aggregation rules) only specify how a metric is to be aggregated not used for alerting. We can mention aggregation rules as guidelines on how metrics should be aggregated to view them on Prometheus/Grafana.

Regarding the difference between the individual aggregation rules, I don't believe there is any `capacity` rule, is there? We do have `node:capacity` which talks above total capacity of an individual node while `cluster:capacity` is at the overall cluster level.
</blockquote></details>

Thank you! I have removed all "aggregate | recording" rules from this "events to alert on" section.

Your #80274 PR won't be included in v22.1.0 GA will it? 

The non-node, non-cluster `capacity` rule I was referring to is the first of the `ratio` rules here:

```
        - record: capacity_available:ratio
          expr: capacity_available / capacity
        - record: node:capacity_available:ratio
          expr: node:capacity_available / node:capacity
        - record: cluster:capacity_available:ratio
          expr: cluster:capacity_available/cluster:capacity
```

Discrete entries for `capacity`, `node:capacity`, and `cluster:capacity`.

But since these are recording rules, I've removed these references anyways, per above.

If you would like these rules documented for use with Grafana, let's revisit that post-GA. Happy to address then. Perhaps all can be done together post-#80274?
___
*[`v22.1/monitoring-and-alerting.md` line 288 at r2](https://reviewable.io/reviews/cockroachdb/docs/13692#-N0g4Sxw0hUYhADk9W3U:-N0qF-g2E6x_XVsMGIV5:bkw9rjb) ([raw file](https://github.com/cockroachdb/docs/blob/7ce41ac1fc33278ddb604e4a353a712d2085f869/v22.1/monitoring-and-alerting.md#L288)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

There is no way to include this in the `rules` endpoint because the threshold depends on the individual cluster setting which isn't available to us. 
</blockquote></details>

Thank you! I have removed "forthcoming" entries, and adapted the "not all events listed have corresponding rule definitions" alert to only reference the pre-defined rules.


<!-- Sent from Reviewable.io -->

2022-05-04 22:23 UTC, rimadeodhar approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13692)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andf-crl and @rimadeodhar)

___
*[`v22.1/monitoring-and-alerting.md` line 177 at r1](https://reviewable.io/reviews/cockroachdb/docs/13692#-N0HYve11YmqEzQr09Cu:-N1G9TAJ6i305ET2xn3c:bh6zc0q) ([raw file](https://github.com/cockroachdb/docs/blob/d2e79991d24e893d053b67edfdd37b6ffcd7eb02/v22.1/monitoring-and-alerting.md#L177)):*
<details><summary><i>Previously, andf-crl wrote…</i></summary><blockquote>

I edited this to match `alert` with `expr` with `annotations` temporarily. Will update to match exactly when you merge your PR fix to this.
</blockquote></details>

This has been fixed in the latest check in. The fix will go out with the 22.1.x patch release.
___
*[`v22.1/monitoring-and-alerting.md` line 330 at r1](https://reviewable.io/reviews/cockroachdb/docs/13692#-N0HZpWt7YhtmsXF7yN7:-N1G9lmj2gYTwTsJNW0u:b-kaqs48) ([raw file](https://github.com/cockroachdb/docs/blob/d2e79991d24e893d053b67edfdd37b6ffcd7eb02/v22.1/monitoring-and-alerting.md#L330)):*
<details><summary><i>Previously, andf-crl wrote…</i></summary><blockquote>

Thank you! I have removed all "aggregate | recording" rules from this "events to alert on" section.

Your #80274 PR won't be included in v22.1.0 GA will it? 

The non-node, non-cluster `capacity` rule I was referring to is the first of the `ratio` rules here:

```
        - record: capacity_available:ratio
          expr: capacity_available / capacity
        - record: node:capacity_available:ratio
          expr: node:capacity_available / node:capacity
        - record: cluster:capacity_available:ratio
          expr: cluster:capacity_available/cluster:capacity
```

Discrete entries for `capacity`, `node:capacity`, and `cluster:capacity`.

But since these are recording rules, I've removed these references anyways, per above.

If you would like these rules documented for use with Grafana, let's revisit that post-GA. Happy to address then. Perhaps all can be done together post-#80274?
</blockquote></details>

I agree with your approach that these rules don't need to be documented. However, if we feel the need later, we can revisit this.


<!-- Sent from Reviewable.io -->

2022-05-05 20:16 UTC, taroface approved these changes
Some minor suggestions. Also, we need to update the Common Issues to Monitor doc, which refers to a couple of these updated alerting rules. Awesome work in this update!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13692#-:-N1Kr8no0gdYccfX_gZb:bam6mnc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andf-crl, @rimadeodhar, and @taroface)

___
*[`v21.2/monitoring-and-alerting.md` line 144 at r3](https://reviewable.io/reviews/cockroachdb/docs/13692#-N1KeqLGDfyfLl7Cu4kG:-N1KeqLGDfyfLl7Cu4kH:bvcz8lc) ([raw file](https://github.com/cockroachdb/docs/blob/0ea9e804e02871cc20855742cb65ed89892a4279/v21.2/monitoring-and-alerting.md#L144)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> In addition to using the exported time series data to monitor a cluster via an external system, you can write alerting rules against them to make sure you are promptly notified of critical events or issues that may require intervention or investigation. See [Events to Alert On](#events-to-alert-on) for more details.
> ```

Nit: Hyphenate per our style



_Suggestion:_
```Markdown
time-series
```
___
*[`v22.1/monitoring-and-alerting.md` line 157 at r1](https://reviewable.io/reviews/cockroachdb/docs/13692#-N0H_BRR7dSpZUaUARCS:-N1Kgft1Da-pmQy2EVnh:bi7eq95) ([raw file](https://github.com/cockroachdb/docs/blob/d2e79991d24e893d053b67edfdd37b6ffcd7eb02/v22.1/monitoring-and-alerting.md#L157)):*
<details><summary><i>Previously, andf-crl wrote…</i></summary><blockquote>

Re: "minimal editing" -- I did not appear to need to edit the rules from the rules endpoint: copy and paste per the below instructions worked for me. You mention in DOC-2123 potentially needing to edit these rules. How so?

Note: I did not attempt to import any `recording` rules. Perhaps those require manual editing?

If any rules do require manual editing beyond the steps I've outlined below, could you supply an example edit of one such rule? Thank you!
</blockquote></details>

+1 to your question - as written, this implies that a user may want/need to edit the rules, and might make them wary to use them without more context? If it's possible to use them as-is, maybe we can actually say that.
___
*[`v22.1/monitoring-and-alerting.md` line 144 at r3](https://reviewable.io/reviews/cockroachdb/docs/13692#-N1KewSL51CeN45YELAA:-N1KewSL51CeN45YELAB:undefined) ([raw file](https://github.com/cockroachdb/docs/blob/0ea9e804e02871cc20855742cb65ed89892a4279/v22.1/monitoring-and-alerting.md#L144)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> In addition to using the exported time series data to monitor a cluster via an external system, you can write alerting rules against them to make sure you are promptly notified of critical events or issues that may require intervention or investigation. See [Events to alert on](#events-to-alert-on) for more details.
> ```





_Suggestion:_
```Markdown
time-series
```
___
*[`v22.1/monitoring-and-alerting.md` line 149 at r3](https://reviewable.io/reviews/cockroachdb/docs/13692#-N1Kf4IW-Vr77skQQgKR:-N1Kf4IW-Vr77skQQgKS:b-pz5pql) ([raw file](https://github.com/cockroachdb/docs/blob/0ea9e804e02871cc20855742cb65ed89892a4279/v22.1/monitoring-and-alerting.md#L149)):*
> ```Markdown
> ## Alerting tools
> 
> While the active monitoring methods described above provide useful insight into the overall health and performance of a cluster, it is also essential to configure alerting rules that promptly send notifications when your CockroachDB instance experiences events that require investigation or intervention. This section identifies the most important events that you might want to create alerting rules for, and provides pre-defined rules definitions for these events appropriate for use with Prometheus' Alertmanager.
> ```

Just a suggestion to streamline the wording a bit and avoid someone misreading this as a value judgment between monitoring and alerting (which we probably want to portray as complementary)



_Suggestion:_
```Markdown
In addition to actively monitoring the overall health and performance of a cluster, it is also essential to configure alerting rules that promptly send notifications when CockroachDB experiences events that require investigation or intervention.
```
___
*[`v22.1/monitoring-and-alerting.md` line 153 at r3](https://reviewable.io/reviews/cockroachdb/docs/13692#-N1KgLJnEoMOvsjhNU9b:-N1KgLJnEoMOvsjhNU9c:b-xp0we2) ([raw file](https://github.com/cockroachdb/docs/blob/0ea9e804e02871cc20855742cb65ed89892a4279/v22.1/monitoring-and-alerting.md#L153)):*
> ```Markdown
> ### Alertmanager
> 
> If you have configured [Prometheus](monitor-cockroachdb-with-prometheus.html) to monitor your CockroachDB instance, you can also configure Prometheus' Alertmanager to detect [important events](#events-to-alert-on) and alert you when they occur by using alerting rule definitions.
> ```

Suggestion for clarity



_Suggestion:_
```Markdown
you can also use alerting rule definitions to have Prometheus' Alertmanager detect [important events](#events-to-alert-on) and alert you when they occur.
```
___
*[`v22.1/monitoring-and-alerting.md` line 157 at r3](https://reviewable.io/reviews/cockroachdb/docs/13692#-N1KgZWH0Qq7zEtJyau8:-N1KgZWH0Qq7zEtJyau9:bpk8c1r) ([raw file](https://github.com/cockroachdb/docs/blob/0ea9e804e02871cc20855742cb65ed89892a4279/v22.1/monitoring-and-alerting.md#L157)):*
> ```Markdown
> #### Prometheus alerting rules endpoint
> 
> <span class="version-tag">New in v22.1:</span> Every node of a CockroachDB cluster exports an alerting rules template at `http://<host>:<http-port>/api/v2/rules/`. These rule definitions are formatted for easy integration with Prometheus' Alertmanager, and require minimal editing.
> ```

Suggestion for brevity



_Suggestion:_
```Markdown
CockroachDB node
```
___
*[`v22.1/monitoring-and-alerting.md` line 236 at r3](https://reviewable.io/reviews/cockroachdb/docs/13692#-N1KhOsP0GjVJkhZg7LY:-N1KhOsP0GjVJkhZg7LZ:b2hplbd) ([raw file](https://github.com/cockroachdb/docs/blob/0ea9e804e02871cc20855742cb65ed89892a4279/v22.1/monitoring-and-alerting.md#L236)):*
> ```Markdown
> #### Node is down
> 
> - **Rule:** Send an alert when a node has been down for 15 minutes or more.
> ```

We should edit the line at common-issues-to-monitor.html#node-health to reflect this update.
___
*[`v22.1/monitoring-and-alerting.md` line 244 at r3](https://reviewable.io/reviews/cockroachdb/docs/13692#-N1Khu8fCnwOj20E5Sq0:-N1Khu8g7_aSdiZ1e3jy:bin6m3t) ([raw file](https://github.com/cockroachdb/docs/blob/0ea9e804e02871cc20855742cb65ed89892a4279/v22.1/monitoring-and-alerting.md#L244)):*
> ```Markdown
> #### Node is restarting too frequently
> 
> - **Rule:** Send an alert if a node has restarted more than once in the last 10 minutes.
> ```

We should edit the line at common-issues-to-monitor.html#node-process-restarts to reflect this update. (Maybe we need includes across these docs, depending on how much we expect them to be updated?)
___
*[`v22.1/monitoring-and-alerting.md` line 288 at r3](https://reviewable.io/reviews/cockroachdb/docs/13692#-N1KjFaHEw9_wnWYjf3B:-N1KjFaHEw9_wnWYjf3C:b-rti0ed) ([raw file](https://github.com/cockroachdb/docs/blob/0ea9e804e02871cc20855742cb65ed89892a4279/v22.1/monitoring-and-alerting.md#L288)):*
> ```Markdown
> #### Unavailable ranges
> 
> - **Rule:** Send an alert when the number of ranges with less-than-quorum replicas online is non-zero for too long.
> ```

"fewer-than-quorum" maybe?



_Code quote:_
```Markdown
less-than-quorum
```
___
*[`v22.1/monitoring-and-alerting.md` line 310 at r3](https://reviewable.io/reviews/cockroachdb/docs/13692#-N1KiuIo4OZJwGyW58AH:-N1KiuIo4OZJwGyW58AI:undefined) ([raw file](https://github.com/cockroachdb/docs/blob/0ea9e804e02871cc20855742cb65ed89892a4279/v22.1/monitoring-and-alerting.md#L310)):*
> ```Markdown
> - **Rule definition:** Use the `UnderreplicatedRanges` alerting rule from your cluster's [`api/v2/rules/` metrics endpoint](#alertmanager).
> 
> #### Requests stuck in raf [...]

2022-05-06 18:08 UTC, andf-crl reviewed
TYFRs both!! Ryan great catch on Common Issue doc, I've updated the two new alert values. I realize you noted this in a comment to DOC-2123 that I thumbs-up'd and then completely forgot. Apologies && thank you!!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13692#-:-N1PPmtGBh0TkNuneJze:b-ax4b2e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andf-crl, @rimadeodhar, and @taroface)

___
*[`v22.1/monitoring-and-alerting.md` line 157 at r1](https://reviewable.io/reviews/cockroachdb/docs/13692#-N0H_BRR7dSpZUaUARCS:-N1PMu9y2soraNqG3yP7:blin6ol) ([raw file](https://github.com/cockroachdb/docs/blob/d2e79991d24e893d053b67edfdd37b6ffcd7eb02/v22.1/monitoring-and-alerting.md#L157)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

+1 to your question - as written, this implies that a user may want/need to edit the rules, and might make them wary to use them without more context? If it's possible to use them as-is, maybe we can actually say that.
</blockquote></details>

You're right. Without further guidance from upstream, I'm just going to remove the reference to "editing required".
___
*[`v22.1/monitoring-and-alerting.md` line 177 at r1](https://reviewable.io/reviews/cockroachdb/docs/13692#-N0HYve11YmqEzQr09Cu:-N1POxck-3z87QsY8BCv:bininb8) ([raw file](https://github.com/cockroachdb/docs/blob/d2e79991d24e893d053b67edfdd37b6ffcd7eb02/v22.1/monitoring-and-alerting.md#L177)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

This has been fixed in the latest check in. The fix will go out with the 22.1.x patch release.
</blockquote></details>

Thank you, I've created DOC-3417 to track that follow-up work.
___
*[`v22.1/monitoring-and-alerting.md` line 149 at r3](https://reviewable.io/reviews/cockroachdb/docs/13692#-N1Kf4IW-Vr77skQQgKR:-N1PLXPOAl9pmpSMqNB4:b8h7uqr) ([raw file](https://github.com/cockroachdb/docs/blob/0ea9e804e02871cc20855742cb65ed89892a4279/v22.1/monitoring-and-alerting.md#L149)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Just a suggestion to streamline the wording a bit and avoid someone misreading this as a value judgment between monitoring and alerting (which we probably want to portray as complementary)
</blockquote></details>

Awesome! Fully agreed.
___
*[`v22.1/monitoring-and-alerting.md` line 153 at r3](https://reviewable.io/reviews/cockroachdb/docs/13692#-N1KgLJnEoMOvsjhNU9b:-N1PMYijEqwu3NPjapkE:b-7bfx4b) ([raw file](https://github.com/cockroachdb/docs/blob/0ea9e804e02871cc20855742cb65ed89892a4279/v22.1/monitoring-and-alerting.md#L153)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Suggestion for clarity
</blockquote></details>

Definitely -- great suggestion.
___
*[`v22.1/monitoring-and-alerting.md` line 236 at r3](https://reviewable.io/reviews/cockroachdb/docs/13692#-N1KhOsP0GjVJkhZg7LY:-N1PNQPv8QEcrbqHSvUI:bhmqyaj) ([raw file](https://github.com/cockroachdb/docs/blob/0ea9e804e02871cc20855742cb65ed89892a4279/v22.1/monitoring-and-alerting.md#L236)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

We should edit the line at common-issues-to-monitor.html#node-health to reflect this update.
</blockquote></details>

Exxxxxxcellent catch! Thank you!
___
*[`v22.1/monitoring-and-alerting.md` line 244 at r3](https://reviewable.io/reviews/cockroachdb/docs/13692#-N1Khu8fCnwOj20E5Sq0:-N1PNcIN5L33bR220dzH:bc1hgik) ([raw file](https://github.com/cockroachdb/docs/blob/0ea9e804e02871cc20855742cb65ed89892a4279/v22.1/monitoring-and-alerting.md#L244)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

We should edit the line at common-issues-to-monitor.html#node-process-restarts to reflect this update. (Maybe we need includes across these docs, depending on how much we expect them to be updated?)
</blockquote></details>

Thank you! Great catch!
___
*[`v22.1/monitoring-and-alerting.md` line 288 at r3](https://reviewable.io/reviews/cockroachdb/docs/13692#-N1KjFaHEw9_wnWYjf3B:-N1PNpy7DVD84RiZH90J:b-a4xew8) ([raw file](https://github.com/cockroachdb/docs/blob/0ea9e804e02871cc20855742cb65ed89892a4279/v22.1/monitoring-and-alerting.md#L288)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

"fewer-than-quorum" maybe?
</blockquote></details>

Yes: 'fewer' is indeed correct! I found a clearer description elsewhere in the corpus and ended up using it here.
___
*[`v22.1/monitoring-and-alerting.md` line 320 at r3](https://reviewable.io/reviews/cockroachdb/docs/13692#-N1KiqCO7zACmT367bO1:-N1POcCd0A2DJ66fej3G:b-1g33hq) ([raw file](https://github.com/cockroachdb/docs/blob/0ea9e804e02871cc20855742cb65ed89892a4279/v22.1/monitoring-and-alerting.md#L320)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Perhaps link to recommended-production-settings#file-descriptors-limit if relevant
</blockquote></details>

Yes, this is an excellent addition!


<!-- Sent from Reviewable.io -->

2022-05-06 18:09 UTC, merged