Cloud May Release Notes
cockroachdb/docs pull request #13741
Opened 2022-04-28 19:28 UTC by gemma-shay

https://cockroachlabs.atlassian.net/browse/DOC-3399

2022-04-28 19:28 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/13741)
<!-- Reviewable:end -->

2022-04-28 20:48 UTC, jramos-crl approved these changes
LGTM!

2022-04-29 22:44 UTC, ianjevans approved these changes

2022-05-02 19:10 UTC, emily-horing requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13741)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay, @kevin-v-ngo, and @thtruo)

___
*[`releases/cloud.md` line 33 at r1](https://reviewable.io/reviews/cockroachdb/docs/13741#-N15AR706UAQ-6kNf0dT:-N15AR71AXDwZi3hPudh:b-eurwk4) ([raw file](https://github.com/cockroachdb/docs/blob/0c69e93b4c3ea2caf169bdf853073337897a88fd/releases/cloud.md#L33)):*
> ```Markdown
>   
> - Users without accounts can now accept invitations by creating a user using SSO-based authorization such as GitHub.
> - Timeseries charts are now displayed in UTC.
> ```

Are we missing connection changes from this list? ie. new connection flow?


<!-- Sent from Reviewable.io -->

2022-05-03 14:23 UTC, gemma-shay commented
@emily-horing those notes went out April 20 in sync with the connection changes

2022-05-03 14:23 UTC, merged