Sso updates
cockroachdb/docs pull request #13865
Opened 2022-05-16 19:21 UTC by MichaelTrestman

Adds an SSO explainer page with FAQ, and points to it from authentication related pages.
Updates mentions of Github as SSO provider to include Microsoft and Google.

https://cockroachlabs.atlassian.net/jira/software/c/projects/DOC/boards/239?modal=detail&selectedIssue=DOC-2847

2022-05-16 19:21 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/13865)
<!-- Reviewable:end -->

2022-05-16 20:14 UTC, kpatron-cockroachlabs reviewed
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13865)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kathancox and @MichaelTrestman)

___
*[`cockroachcloud/cloud-sso.md` line 3 at r1](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DTlbf6HILkEmcyq8a:-N2DTlbf6HILkEmcyq8b:bpf6chj) ([raw file](https://github.com/cockroachdb/docs/blob/1dc0baf3af8e2b89e06d36e00464580e5d71e1d8/cockroachcloud/cloud-sso.md#L3)):*
> ```Markdown
> ---
> title: Single Sign-On (SSO) for Cockroach Cloud
> summary: Learn about SSO Authentication for the Cockroach Cloud COnsole
> ```

Nit: COnsole vs Console
___
*[`cockroachcloud/cloud-sso.md` line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DUFxN18khs3j1sTe5:-N2DUFxN18khs3j1sTe6:b-uipw97) ([raw file](https://github.com/cockroachdb/docs/blob/1dc0baf3af8e2b89e06d36e00464580e5d71e1d8/cockroachcloud/cloud-sso.md#L16)):*
> ```Markdown
> - Administrators can rapidly and simply onboard and offboard users.
> 
> Cockroach Cloud Console SSO is powered by [Auth0 B2B](https://auth0.com/b2b-saas).	
> ```

Do we want to say this?
___
*[`cockroachcloud/cloud-sso.md` line 39 at r1](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DV-7t8yiPyFx0S2Cy:-N2DV-7t8yiPyFx0S2Cz:bwi1pjj) ([raw file](https://github.com/cockroachdb/docs/blob/1dc0baf3af8e2b89e06d36e00464580e5d71e1d8/cockroachcloud/cloud-sso.md#L39)):*
> ```Markdown
> 
> A future release will provide an auto-onboarding feature allowing administrators to share an organization-specific sign-in URL, which will generate a new {{ site.data.products.db }} identity when it is first used.
> n their CC organization.
> ```

stub sentence?
___
*[`cockroachcloud/cloud-sso.md` line 45 at r1](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DVDI8ECixI8BvA5Bk:-N2DVDI8ECixI8BvA5Bl:bctg8mj) ([raw file](https://github.com/cockroachdb/docs/blob/1dc0baf3af8e2b89e06d36e00464580e5d71e1d8/cockroachcloud/cloud-sso.md#L45)):*
> ```Markdown
> If a user is using SSO, deleting the user's identity at the level of the SSO provider (e.g., deleting their work Google account), will remove their access to the {{ site.data.products.db }} organization.
> 
> To remove a user's access to {{ site.data.products.db }} without deleting their SSO identity, you can [delete their {{ site.data.products.db }} team member user identity](console-access-management.html#delete-a-team-member) in the console.
> ```

There is a minor semantic thing here. You aren't deleting the user, you are removing the user from your org when you remove them in the console. I realize the link also calls it deleting a team member.
___
*[`cockroachcloud/create-an-account.md` line 2 at r1](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DTyJ3EzBnOdQhvN11:-N2DTyJ3EzBnOdQhvN12:b-p5pso2) ([raw file](https://github.com/cockroachdb/docs/blob/1dc0baf3af8e2b89e06d36e00464580e5d71e1d8/cockroachcloud/create-an-account.md#L2)):*
> ```Markdown
> ---
> title: Create a CockroachDB Cloud account
> ```

Maybe orthogonal to this change but should this page have any mention of creating accounts through invites?
___
*[`cockroachcloud/create-an-account.md` line 8 at r1](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DT5M1BxEHZL4Cx2ZI:-N2DT5M1BxEHZL4Cx2ZJ:b-64hl9l) ([raw file](https://github.com/cockroachdb/docs/blob/1dc0baf3af8e2b89e06d36e00464580e5d71e1d8/cockroachcloud/create-an-account.md#L8)):*
> ```Markdown
> ---
> 
> Before you [create a {{ site.data.products.db }} cluster](create-your-cluster.html), you must first create a {{ site.data.products.db }} account. You can register for {{ site.data.products.db }} using a GitHub account or an email address.
> ```

Do we want to include Google/Microsoft here in addition to Github?
___
*[`cockroachcloud/create-an-account.md` line 27 at r1](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DTEhB3wofsF6LoATW:-N2DTEhB3wofsF6LoATX:br7zxj6) ([raw file](https://github.com/cockroachdb/docs/blob/1dc0baf3af8e2b89e06d36e00464580e5d71e1d8/cockroachcloud/create-an-account.md#L27)):*
> ```Markdown
> <p></p>
> 
> <section class="filter-content" markdown="1" data-scope="github">
> ```

Nit: should we change the scope from github to sso?
___
*[`cockroachcloud/create-an-account.md` line 135 at r1](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DTbP_5T_XiySrYH1Q:-N2DTbP_5T_XiySrYH1R:b1dnrkx) ([raw file](https://github.com/cockroachdb/docs/blob/1dc0baf3af8e2b89e06d36e00464580e5d71e1d8/cockroachcloud/create-an-account.md#L135)):*
> ```Markdown
> If you want to change your login method, you can do so at any time:
> 
> - [Switch from a GitHub login to email](#switch-from-a-github-login-to-email)
> ```

Should the docs from here down change since it is no longer just github?


<!-- Sent from Reviewable.io -->

2022-05-17 14:41 UTC, MichaelTrestman commented
*[`cockroachcloud/cloud-sso.md` line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DUFxN18khs3j1sTe5:-N2HSms_9rOermwFE5Ko:b-m20jey) ([raw file](https://github.com/cockroachdb/docs/blob/1dc0baf3af8e2b89e06d36e00464580e5d71e1d8/cockroachcloud/cloud-sso.md#L16)):*
<details><summary><i>Previously, kpatron-cockroachlabs (Kyle) wrote…</i></summary><blockquote>

Do we want to say this?
</blockquote></details>

@abhinavg6 ?


<!-- Sent from Reviewable.io -->

2022-05-17 14:43 UTC, MichaelTrestman commented
*[`cockroachcloud/cloud-sso.md` line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DUFxN18khs3j1sTe5:-N2HTFR7-QU5hpk9BLar:b9fi29n) ([raw file](https://github.com/cockroachdb/docs/blob/1dc0baf3af8e2b89e06d36e00464580e5d71e1d8/cockroachcloud/cloud-sso.md#L16)):*
> @abhinavg6 ?
Makes sense to me to include it. It seems potentially relevant to security decisions to know how its implemented, and we have nothing to hide.


<!-- Sent from Reviewable.io -->

2022-05-17 18:27 UTC, kathancox reviewed
Some changes to consider / questions. Particularly around the product naming/liquid templating. Let me know if you want a quick scan tomorrow.

2022-05-17 18:27 UTC, kathancox commented on cockroachcloud/create-an-account.md
> +You may authenticate with Cockroach Cloud using an email and password, or with [Single Sign-on (SSO)](cloud-sso.html). Cockroach Cloud supports SSO provided by Github, Google, and Microsoft.
On this page, also check on the product naming and use the liquid templating as per the style guide.

2022-05-17 18:27 UTC, kathancox commented on cockroachcloud/create-an-account.md
> +You may authenticate with Cockroach Cloud using an email and password, or with [Single Sign-on (SSO)](cloud-sso.html). Cockroach Cloud supports SSO provided by Github, Google, and Microsoft.
And cap the H in GitHub here

2022-05-17 18:27 UTC, kathancox commented on cockroachcloud/create-an-account.md
> +Single-Sign on provides security benefits. This includes not having to manage an additional credential, and perhaps most importantly, that SSO providers support multi-factor authentication (MFA). For
"Single-Sign on" is hyphenated differently here compared to other places.

2022-05-17 18:27 UTC, kathancox commented on _includes/cockroachcloud/prefer-sso.md
> +    {{ site.data.products.db }} currently supports SSO with GitHub, Google and Microsoft.
Nit: "...users log in.." open up "login" when it is used as a verb. (I realize that was already there).

2022-05-17 18:27 UTC, kathancox commented on cockroachcloud/create-an-account.md
>  1. Navigate to the [{{ site.data.products.db }} Log In page](https://cockroachlabs.cloud/clusters).
If you take a look at this in the preview there is some formatting issues. I'm not 100% on what the issue is. Wondering if it is the liquid template in the link.

2022-05-17 18:27 UTC, kathancox commented on cockroachcloud/create-an-account.md
Perhaps here "Once you have changed your authentication method, you will receive a confirmation email."

2022-05-17 21:01 UTC, abhinavg6 requested changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13865)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kathancox, @kpatron-cockroachlabs, and @MichaelTrestman)

___
*[`cockroachcloud/cloud-sso.md` line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DUFxN18khs3j1sTe5:-N2In4jN-ubkmtjBBfyM:b-dxqimz) ([raw file](https://github.com/cockroachdb/docs/blob/1dc0baf3af8e2b89e06d36e00464580e5d71e1d8/cockroachcloud/cloud-sso.md#L16)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

> @abhinavg6 ?
Makes sense to me to include it. It seems potentially relevant to security decisions to know how its implemented, and we have nothing to hide.
</blockquote></details>

Actually we don't want to include this. Thanks for checking.
___
*[`cockroachcloud/cloud-sso.md` line 20 at r2](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2InJ5hDCyXr2m3-YSX:-N2InJ5hDCyXr2m3-YSY:bfg8xv) ([raw file](https://github.com/cockroachdb/docs/blob/f2494bb1df14259b449a1a3b7b135395dbfc8a2e/cockroachcloud/cloud-sso.md#L20)):*
> ```Markdown
> ## Frequently Asked Questions (FAQ)
> 
> ### How can I find out more about SSO for Cockroach Cloud?
> ```

CockroachDB Cloud
___
*[`cockroachcloud/cloud-sso.md` line 22 at r2](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DJJ9gR2X8RG33-64i-r2-22:-N2InO1949UFb1Cl0K1S:b8kbog5) ([raw file](https://github.com/cockroachdb/docs/blob/f2494bb1df14259b449a1a3b7b135395dbfc8a2e/cockroachcloud/cloud-sso.md#L22)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

We're OK with directing users with questions on SSO for Cloud to support? I only ask since it's the first question on the page, so it makes me think the page won't hold my answers, if you know what I mean. I also don't know what the status of SSO is? — as in, do we have any other further documentation we can direct to before the support team?
</blockquote></details>

I think it's ok to remove this entire question for now. We'll come back to it during a later release.
___
*[`cockroachcloud/cloud-sso.md` line 24 at r2](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2IndG_CyodroNbeCJF:-N2IndG_CyodroNbeCJG:b9j8xsp) ([raw file](https://github.com/cockroachdb/docs/blob/f2494bb1df14259b449a1a3b7b135395dbfc8a2e/cockroachcloud/cloud-sso.md#L24)):*
> ```Markdown
> Contact our [support team](../{{site.versions["stable"]}}/support-resources.html).
> 
> ### Will it work if I try to sign in with SSO without setting it up, if I already use an email from an SSO Provider?
> ```

Maybe give an example, like

Will it work if I try to sign in with SSO without setting it up for my account, if I already use an email from an SSO provider (like x.y@gmail.com)?
___
*[`cockroachcloud/cloud-sso.md` line 32 at r2](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2Io71A0YqGtylxQV4S:-N2Io71A0YqGtylxQV4T:b7n33a2) ([raw file](https://github.com/cockroachdb/docs/blob/f2494bb1df14259b449a1a3b7b135395dbfc8a2e/cockroachcloud/cloud-sso.md#L32)):*
> ```Markdown
> ### Once I change my active login method to a new SSO (Google / Microsoft), can I still sign in using my email/password combination or my Github identity?
> 
> No. Only one authentication method can be active for each Cockroach Cloud Console user at a time. Visit **“My Account”** in the Cockroach Cloud Console to configure which authentication method is active.
> ```

CockroachDB Cloud Console
___
*[`cockroachcloud/cloud-sso.md` line 36 at r2](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DJJ9gR2X8RG33-64i-r2-36:-N2IoNt69edrmiTUUAn0:b-sxgj9o) ([raw file](https://github.com/cockroachdb/docs/blob/f2494bb1df14259b449a1a3b7b135395dbfc8a2e/cockroachcloud/cloud-sso.md#L36)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

This question/answer is referencing future features. Are these relatively concrete? I know you have brought this to the team before... 
</blockquote></details>

Yeah we should remove the second part of this answer. Just the first part is enough.
___
*[`cockroachcloud/cloud-sso.md` line 46 at r2](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DJJ9gR2X8RG33-64i-r2-46:-N2IodIB9Mq5qvGYf8D4:b-1lk09g) ([raw file](https://github.com/cockroachdb/docs/blob/f2494bb1df14259b449a1a3b7b135395dbfc8a2e/cockroachcloud/cloud-sso.md#L46)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

Again, just a small nudge on the future-looking language here. Also, this sentence doesn't seem complete: "That feature is planned for release late." 
</blockquote></details>

Yeah, we should remove the second statement and just indicate that it's currently not supported.


<!-- Sent from Reviewable.io -->

2022-05-18 01:06 UTC, MichaelTrestman reviewed
I think I caught everything, but would certainly not turn my nose up at a final check, thank you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13865#-:-N2Jgonj4rJfFXZtAUi-:bo9u255)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abhinavg6, @kathancox, and @kpatron-cockroachlabs)

___
*[`_includes/cockroachcloud/prefer-sso.md` line 4 at r2](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DJJ9gR2X8RG33-64f-r2-4:-N2JMdh8CpXwLN97bq9T:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f2494bb1df14259b449a1a3b7b135395dbfc8a2e/_includes/cockroachcloud/prefer-sso.md#L4)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

Nit: "...users log in.." open up "login" when it is used as a verb. (I realize that was already there).
</blockquote></details>

Done.
___
*[`cockroachcloud/authentication.md` line 15 at r2](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DJJ9gR2X8RG33-64g-r2-15:-N2JMk2Q72nsFMs-8kaU:b-oue738) ([raw file](https://github.com/cockroachdb/docs/blob/f2494bb1df14259b449a1a3b7b135395dbfc8a2e/cockroachcloud/authentication.md#L15)):*
> Done.
I 
___
*[`cockroachcloud/cloud-sso.md` line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DUFxN18khs3j1sTe5:-N2JYMvH5u0dOR4zo3EZ:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/1dc0baf3af8e2b89e06d36e00464580e5d71e1d8/cockroachcloud/cloud-sso.md#L16)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

Actually we don't want to include this. Thanks for checking.
</blockquote></details>

Done.
___
*[`cockroachcloud/cloud-sso.md` line 39 at r1](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DV-7t8yiPyFx0S2Cy:-N2HTRx53ds5-rt77xR6:b-s85buy) ([raw file](https://github.com/cockroachdb/docs/blob/1dc0baf3af8e2b89e06d36e00464580e5d71e1d8/cockroachcloud/cloud-sso.md#L39)):*
<details><summary><i>Previously, kpatron-cockroachlabs (Kyle) wrote…</i></summary><blockquote>

stub sentence?
</blockquote></details>

whoops, thanks for the catch!
___
*[`cockroachcloud/cloud-sso.md` line 45 at r1](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DVDI8ECixI8BvA5Bk:-N2HTzbzBjcTKUHy7Ope:b-7aitaz) ([raw file](https://github.com/cockroachdb/docs/blob/1dc0baf3af8e2b89e06d36e00464580e5d71e1d8/cockroachcloud/cloud-sso.md#L45)):*
<details><summary><i>Previously, kpatron-cockroachlabs (Kyle) wrote…</i></summary><blockquote>

There is a minor semantic thing here. You aren't deleting the user, you are removing the user from your org when you remove them in the console. I realize the link also calls it deleting a team member.
</blockquote></details>

Thanks for clarifying.
___
*[`cockroachcloud/cloud-sso.md` line 1 at r2](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DJJ9gR2X8RG33-64i-r2-1:-N2JXQMB1Nu87OpchKOQ:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f2494bb1df14259b449a1a3b7b135395dbfc8a2e/cockroachcloud/cloud-sso.md#L1)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

There are only 4 other instances in the docs where we use "Cockroach Cloud", which makes me think in the title this should be written as "CockroachDB Cloud". 

This comment will go for the whole page (so I won't mention again). In the body text you had use the liquid template. 

Also, the "Cockroach Cloud Console" would be "CockroachDB Cloud Console" and I suppose you would use the liquid template for the first part of that.
</blockquote></details>

Done.
___
*[`cockroachcloud/cloud-sso.md` line 8 at r2](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DJJ9gR2X8RG33-64i-r2-8:-N2JY-mj0tvMBqkLb5M3:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f2494bb1df14259b449a1a3b7b135395dbfc8a2e/cockroachcloud/cloud-sso.md#L8)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

Typo: "Github" --> "GitHub" cap on the H (correct this for every instance)
</blockquote></details>

Done.
___
*[`cockroachcloud/cloud-sso.md` line 12 at r2](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DJJ9gR2X8RG33-64i-r2-12:-N2JY4Rv7DTpyyjBpnsK:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f2494bb1df14259b449a1a3b7b135395dbfc8a2e/cockroachcloud/cloud-sso.md#L12)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

Since you have spelled out MFA here beforehand, perhaps add parenthesis around "MFA".
</blockquote></details>

Done.
___
*[`cockroachcloud/cloud-sso.md` line 13 at r2](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DJJ9gR2X8RG33-64i-r2-13:-N2JYBL98X76yt-fGXLT:b-x1knpr) ([raw file](https://github.com/cockroachdb/docs/blob/f2494bb1df14259b449a1a3b7b135395dbfc8a2e/cockroachcloud/cloud-sso.md#L13)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

Nit: "double win" sounds somewhat informal. What about: 

"..., therefore minimizing these operations is beneficial/advantageous."
</blockquote></details>

"doubly advantageous" is literal enough, I think?
___
*[`cockroachcloud/cloud-sso.md` line 14 at r2](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DJJ9gR2X8RG33-64i-r2-14:-N2JYJCC2mhfFPMIuzVl:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f2494bb1df14259b449a1a3b7b135395dbfc8a2e/cockroachcloud/cloud-sso.md#L14)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

What about: "Administrators can onboard and offboard users quickly and efficiently." I tend to avoid "simply" wherever possible, as we can't really determine what feels "simple" to others, but my opinion.
</blockquote></details>

Done.
___
*[`cockroachcloud/cloud-sso.md` line 20 at r2](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2InJ5hDCyXr2m3-YSX:-N2JYOEX132wywuoI7No:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f2494bb1df14259b449a1a3b7b135395dbfc8a2e/cockroachcloud/cloud-sso.md#L20)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

CockroachDB Cloud
</blockquote></details>

Done.
___
*[`cockroachcloud/cloud-sso.md` line 22 at r2](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DJJ9gR2X8RG33-64i-r2-22:-N2JYXZsEuu05uW-GmKr:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f2494bb1df14259b449a1a3b7b135395dbfc8a2e/cockroachcloud/cloud-sso.md#L22)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

I think it's ok to remove this entire question for now. We'll come back to it during a later release.
</blockquote></details>

Done.
___
*[`cockroachcloud/cloud-sso.md` line 24 at r2](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2IndG_CyodroNbeCJF:-N2JZAfh4M4mYr4TVg4p:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f2494bb1df14259b449a1a3b7b135395dbfc8a2e/cockroachcloud/cloud-sso.md#L24)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

Maybe give an example, like

Will it work if I try to sign in with SSO without setting it up for my account, if I already use an email from an SSO provider (like x.y@gmail.com)?
</blockquote></details>

Done.
___
*[`cockroachcloud/cloud-sso.md` line 26 at r2](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DJJ9gR2X8RG33-64i-r2-26:-N2JZIxaBk7WbqWXSTlz:buqu457) ([raw file](https://github.com/cockroachdb/docs/blob/f2494bb1df14259b449a1a3b7b135395dbfc8a2e/cockroachcloud/cloud-sso.md#L26)):*
> An email associated with an SSO provider (Google or Microsoft) does not automatically enable SSO
nice rephrase!
___
*[`cockroachcloud/cloud-sso.md` line 28 at r2](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DJJ9gR2X8RG33-64i-r2-28:-N2JZMv240nmq1Rm0oXC:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f2494bb1df14259b449a1a3b7b135395dbfc8a2e/cockroachcloud/cloud-sso.md#L28)):*
< [...]

2022-05-18 13:37 UTC, kathancox commented on cockroachcloud/cloud-sso.md
> +- Administrators can onboard and offboard users quickly and efficiently
Typo: missed the period at the end of the sentence on the last bullet

2022-05-18 15:40 UTC, MichaelTrestman reviewed
Thanks. I noticed the sidebar/long-heading issue too. It's in tension with our convention of using subheaders for the Q in Q & A, as it constrains us to short questions.

We might want to switch our convention, instead of using subheaders, just do something like:

<b>Q:</b> How do I blah blah blah?
<b>A:</b> Do this one thing.

I'll post in docs-style

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13865#-:-N2MS-UvEKydVldRp7Du:bscm91l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abhinavg6, @kathancox, and @kpatron-cockroachlabs)

___
*[`cockroachcloud/authentication.md` line 13 at r3](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DJJ9gR2X8RG33-64g-r3-13:-N2MkLRwDq7RqThp1V_O:b-ix9mwb) ([raw file](https://github.com/cockroachdb/docs/blob/378d23f3109df6c5e1328c1305a933202030d346/cockroachcloud/authentication.md#L13)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

Typo: just missed out "Console" after the liquid templating
</blockquote></details>

Sorry if I'm being obtuse but I'm not sure what I missed, it looks ok to me.
___
*[`cockroachcloud/cloud-sso.md` line 2 at r3](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DJJ9gR2X8RG33-64i-r3-2:-N2MjrPD3q-uzikhbLhJ:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/378d23f3109df6c5e1328c1305a933202030d346/cockroachcloud/cloud-sso.md#L2)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

In the frontmatter here, the page title, you'll want to switch up to "CockroachDB Cloud"
</blockquote></details>

Done.
___
*[`cockroachcloud/cloud-sso.md` line 14 at r3](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DJJ9gR2X8RG33-64i-r3-14:-N2Mk-1_8CMGHm_3ogJy:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/378d23f3109df6c5e1328c1305a933202030d346/cockroachcloud/cloud-sso.md#L14)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

Typo: missed the period at the end of the sentence on the last bullet
</blockquote></details>

Done.
___
*[`cockroachcloud/create-an-account.md` line 12 at r3](https://reviewable.io/reviews/cockroachdb/docs/13865#-N2DJJ9gR2X8RG33-64h-r3-12:-N2Mk4Xy8HHDcNCk9O7I:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/378d23f3109df6c5e1328c1305a933202030d346/cockroachcloud/create-an-account.md#L12)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

Typo: "GitHub" here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-18 15:40 UTC, merged