Adding ccloud option to Quickstart.
cockroachdb/docs pull request #13881
Opened 2022-05-18 16:00 UTC by ianjevans

Closes DOC-3420.

2022-05-19 15:45 UTC, stbof commented on cockroachcloud/quickstart.md
> +You can install a {{ site.data.products.serverless }} cluster using either the CockroachDB Cloud Console, a web-based graphical user interface (GUI) tool, or <code>ccloud</code>, a command line inter
```suggestion
You can install a {{ site.data.products.serverless }} cluster using either the CockroachDB Cloud Console, a web-based graphical user interface (GUI) tool, or <code>ccloud</code>, a command-line interface (CLI) tool.
```

2022-05-19 15:46 UTC, stbof commented on cockroachcloud/quickstart.md
> +Select the **General connection string**, then copy the connection string displayed and save it in a secure location. The connection string is the line starting `postgresql://`.
```suggestion
Select **General connection string**, then copy the connection string displayed and save it in a secure location. The connection string is the line starting `postgresql://`.
```

2022-05-20 13:00 UTC, marksoper requested changes
Need to apply the "-xz instead of -xJ" change here as well.

2022-05-20 15:03 UTC, ianjevans commented
> Need to apply the "-xz instead of -xJ" change here as well.

Done in this commit: https://github.com/cockroachdb/docs/pull/13881/commits/b40715848b163c561e0f49f055bc9387891895c3

2022-05-20 22:29 UTC, jenngeorge reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13881)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ianjevans, @marksoper, and @stbof)

___
*[`_includes/cockroachcloud/ccloud/quickstart.md` line 8 at r2](https://reviewable.io/reviews/cockroachdb/docs/13881#-N2YTeJZ3eQ3hEEcBaDe:-N2YTeJZ3eQ3hEEcBaDf:b-fwb49f) ([raw file](https://github.com/cockroachdb/docs/blob/6e18e1406a4abeb1bc24c0feb231769b056134e0/_includes/cockroachcloud/ccloud/quickstart.md#L8)):*
> ```Markdown
> ~~~
> 
> The `ccloud quickstart` command will open a browser window to log you in to CockroachDB Cloud. If you are new to CockroachDB Cloud, you can log in using your GitHub account, or create a new account using an email address.
> ```

I'm not sure if it will be clear that `ccloud quickstart` supports existing users logging in, but not account creation / new users signing up (yet).

What do you think about extending the sentence like "If you are new to CockroachDB Cloud, you should log in using your GitHub account, or create a new account using an email address before using the `ccloud quickstart` command."? 

Alternatively, how about adding a sentence like "If you are new to CockroachDB Cloud, first sign up using your GitHub account or an email address at https://cockroachlabs.cloud/signup (`ccloud` support for account creation is coming soon!)." before "Run `ccloud quickstart` and follow the instructions:"?


<!-- Sent from Reviewable.io -->

2022-05-23 20:23 UTC, ianjevans commented
> What do you think about extending the sentence like "If you are new to CockroachDB Cloud, you should log in using your GitHub account, or create a new account using an email address before using the `ccloud quickstart` command."?
> 
> Alternatively, how about adding a sentence like "If you are new to CockroachDB Cloud, first sign up using your GitHub account or an email address at https://cockroachlabs.cloud/signup (`ccloud` support for account creation is coming soon!)." before "Run `ccloud quickstart` and follow the instructions:"?

I clarified, and removed the reference to GitHub as we now support multiple SSO options.

2022-05-23 23:35 UTC, jenngeorge reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13881)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ianjevans, @marksoper, and @stbof)

___
*[`_includes/cockroachcloud/ccloud/quickstart.md` line 8 at r2](https://reviewable.io/reviews/cockroachdb/docs/13881#-N2YTeJZ3eQ3hEEcBaDe:-N2nEyTP4NaWVNcLxT84:bzbw68v) ([raw file](https://github.com/cockroachdb/docs/blob/6e18e1406a4abeb1bc24c0feb231769b056134e0/_includes/cockroachcloud/ccloud/quickstart.md#L8)):*
<details><summary><i>Previously, jenngeorge (Jennifer Georgevich) wrote…</i></summary><blockquote>

I'm not sure if it will be clear that `ccloud quickstart` supports existing users logging in, but not account creation / new users signing up (yet).

What do you think about extending the sentence like "If you are new to CockroachDB Cloud, you should log in using your GitHub account, or create a new account using an email address before using the `ccloud quickstart` command."? 

Alternatively, how about adding a sentence like "If you are new to CockroachDB Cloud, first sign up using your GitHub account or an email address at https://cockroachlabs.cloud/signup (`ccloud` support for account creation is coming soon!)." before "Run `ccloud quickstart` and follow the instructions:"?
</blockquote></details>

Thanks for updating "log in using your GitHub account" to "register using one of the single-sign-on options" for `cockroachcloud/ccloud-get-started.md` in commit https://github.com/cockroachdb/docs/pull/13881/commits/38808167a1754471eb53717b76b70276a5f81767 ! Do we want to make the same update in `_includes/cockroachcloud/ccloud/quickstart.md`?
___
*[`cockroachcloud/quickstart.md` line 71 at r3](https://reviewable.io/reviews/cockroachdb/docs/13881#-N2nCJY1BRWRcfBhUyAJ:-N2nCJY24BR9zJC078li:b-jlnfyr) ([raw file](https://github.com/cockroachdb/docs/blob/38808167a1754471eb53717b76b70276a5f81767/cockroachcloud/quickstart.md#L71)):*
> ```Markdown
> {% include cockroachcloud/ccloud/install-ccloud.md %}
> 
> ## Run `ccloud quickstart` to create a new cluster, create a SQL user, and retrive the connection string.
> ```

I think "retrive" should be "retrieve".


<!-- Sent from Reviewable.io -->

2022-05-23 23:41 UTC, ianjevans commented
> Thanks for updating "log in using your GitHub account" to "register using one of the single-sign-on options" for `cockroachcloud/ccloud-get-started.md` in commit [3880816](https://github.com/cockroachdb/docs/commit/38808167a1754471eb53717b76b70276a5f81767) ! Do we want to make the same update in `_includes/cockroachcloud/ccloud/quickstart.md`?

Yes, good catch.

> I think "retrive" should be "retrieve".

Yup. Fixed. I wonder why our linter didn't catch that misspelling?

2022-05-24 00:09 UTC, jenngeorge approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> thanks! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13881#-:-N2nO2po1oc0nHtukVKz:b-1tfu21)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ianjevans, @marksoper, and @stbof)



<!-- Sent from Reviewable.io -->

2022-05-24 15:45 UTC, stbof commented on cockroachcloud/quickstart.md
> +The <code>ccloud</code> CLI tool is currently in beta.
```suggestion
The <code>ccloud</code> CLI tool is in beta.
```

2022-05-24 16:17 UTC, merged