DOC-3375: Improve usability of TAs
cockroachdb/docs pull request #13907
Opened 2022-05-20 20:38 UTC by nickvigilante

Fixes DOC-3375

2022-05-20 20:38 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/13907)
<!-- Reviewable:end -->

2022-05-21 03:59 UTC, jseldess requested changes
This looks great overall, but on the index, the advisories no longer seems sorted in reverse chronologically order by date, like on the live page. I think it's best to retain that.

2022-05-23 15:34 UTC, nickvigilante commented
@jseldess Good catch. I've fixed that now.

2022-05-25 18:16 UTC, jseldess commented
There's a conflict to resolve, though, before merging.

2022-05-26 17:01 UTC, merged