DOC-3643 Vale correctness pass - andf
cockroachdb/docs pull request #13930
Opened 2022-05-24 17:28 UTC by andf-crl

Addresses: DOC-3643

Please see my extensive notes in linked ticket.

2022-05-24 17:28 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/13930)
<!-- Reviewable:end -->

2022-05-24 20:23 UTC, lnhsingh approved these changes
Nice!

2022-05-25 14:30 UTC, nickvigilante requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> aside from nits! Great work!

> Reviewed 158 of 158 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13930#-:-N2vZsqL0SYKFPxuQDEP:bdcvied)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andf-crl)

___
*[`_includes/releases/v21.2/v21.2.0.md` line 117 at r1](https://reviewable.io/reviews/cockroachdb/docs/13930#-N2vU_Ir0BTq05UogXXx:-N2vU_Ir0BTq05UogXXy:bw9wch8) ([raw file](https://github.com/cockroachdb/docs/blob/530e52624a9096c90bc5a25490800622f05f1434/_includes/releases/v21.2/v21.2.0.md#L117)):*
> ```Markdown
> Cockroach University | **New Schema Design Course** | [Foundations of Schema Design in CockroachDB](https://university.cockroachlabs.com/courses/course-v1:crl+foundations-schema-design-cockroachdb+self-paced/about) teaches you CockroachDB's rich data types and the best practices and anti-patterns to consider when designing schema for CockroachDB.
> Cockroach University | **New Node.js Course** | [Fundamentals of CockroachDB for Node.js Developers](https://university.cockroachlabs.com/courses/course-v1:crl+fundamentals-of-crdb-for-nodejs-devs+self-paced/about) walks you through building a full-stack vehicle-sharing app in Typescript using Node.js with TypeORM and a <a href="https://cockroachlabs.cloud/signup?referralId=docs_crdb_release_notes" rel="noopener" target="_blank">CockroachCloud Free</a> cluster as the backend.
> Docs                 | **CockroachDB Cloud Guidance** | Added Node.js, Go, Python, and Java sample app code and connection guidance to the [{{ site.data.products.serverless }} Quickstart](../cockroachcloud/quickstart.html), as well as docs explaining the [{{ site.data.products.serverless }} Architecture](../cockroachcloud/architecture.html), important concepts for [planning/managing a Serverless cluster](../cockroachcloud/plan-your-cluster.html) (e.g., request units, cluster scaling), and how to run [bulk operations on {{ site.data.products.dedicated }} and Serverless clusters](../cockroachcloud/run-bulk-operations.html).
> ```

Nit: I would also replace "Serverless" with `{{ site.data.products.serverless }}`.



_Code quote:_
```Markdown
bulk operations on {{ site.data.products.dedicated }} and Serverless clusters
```
___
*[`v21.2/constraints.md` line 55 at r1](https://reviewable.io/reviews/cockroachdb/docs/13930#-N2vXKnd2FA1Yqw4X3IA:-N2vXKnd2FA1Yqw4X3IB:bz6ypy6) ([raw file](https://github.com/cockroachdb/docs/blob/530e52624a9096c90bc5a25490800622f05f1434/v21.2/constraints.md#L55)):*
> ```Markdown
>     ~~~
> 
>   - `DEFAULT` values and `NOT NULL` constraints can be added through [`ALTER TABLE...ALTER COLUMN`](alter-column.html#set-or-change-a-default-value). For example, this statement adds the `DEFAULT` value constraint to `baz.bool`:
> ```

Nit and slightly outside the scope of this ticket but: can you link to the docs page here? https://www.cockroachlabs.com/docs/v22.1/default-value.html
___
*[`v21.2/use-cloud-storage-for-bulk-operations.md` line 127 at r1](https://reviewable.io/reviews/cockroachdb/docs/13930#-N2vaawoAonf2AUyen0V:-N2vaawoAonf2AUyen0W:buodkiy) ([raw file](https://github.com/cockroachdb/docs/blob/530e52624a9096c90bc5a25490800622f05f1434/v21.2/use-cloud-storage-for-bulk-operations.md#L127)):*
> ```Markdown
> ### Implicit authentication
> 
> If the `AUTH` parameter is `implicit`, the access keys can be omitted and [the credentials will be loaded from the environment](https://docs.aws.amazon.com/sdk-for-go/api/aws/session/), i.e., the machines running the backup.
> ```

Same nit.
___
*[`v22.1/constraints.md` line 55 at r1](https://reviewable.io/reviews/cockroachdb/docs/13930#-N2vaWB0BjJq0lfibSx1:-N2vaWB0BjJq0lfibSx2:buodkiy) ([raw file](https://github.com/cockroachdb/docs/blob/530e52624a9096c90bc5a25490800622f05f1434/v22.1/constraints.md#L55)):*
> ```Markdown
>     ~~~
> 
>   - `DEFAULT` values and `NOT NULL` constraints can be added through [`ALTER TABLE...ALTER COLUMN`](alter-column.html#set-or-change-a-default-value). For example, this statement adds the `DEFAULT` value constraint to `baz.bool`:
> ```

Same nit.
___
*[`v22.1/use-cloud-storage-for-bulk-operations.md` line 127 at r1](https://reviewable.io/reviews/cockroachdb/docs/13930#-N2v_mdfC8yBf8rB9zSr:-N2v_mdfC8yBf8rB9zSs:bf4sopx) ([raw file](https://github.com/cockroachdb/docs/blob/530e52624a9096c90bc5a25490800622f05f1434/v22.1/use-cloud-storage-for-bulk-operations.md#L127)):*
> ```Markdown
> ### Implicit authentication
> 
> If the `AUTH` parameter is `implicit`, the access keys can be omitted and [the credentials will be loaded from the environment](https://docs.aws.amazon.com/sdk-for-go/api/aws/session/), i.e., the machines running the backup.
> ```

Nit: I think i.e., should be used in a parenthetical expression. Can you make that happen?


<!-- Sent from Reviewable.io -->

2022-05-25 15:43 UTC, andf-crl reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13930)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nickvigilante)

___
*[`_includes/releases/v21.2/v21.2.0.md` line 117 at r1](https://reviewable.io/reviews/cockroachdb/docs/13930#-N2vU_Ir0BTq05UogXXx:-N2vqslWD1QH7v3prxRf:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/530e52624a9096c90bc5a25490800622f05f1434/_includes/releases/v21.2/v21.2.0.md#L117)):*
<details><summary><i>Previously, nickvigilante (Nick Vigilante) wrote…</i></summary><blockquote>

Nit: I would also replace "Serverless" with `{{ site.data.products.serverless }}`.
</blockquote></details>

Done.
___
*[`v21.2/constraints.md` line 55 at r1](https://reviewable.io/reviews/cockroachdb/docs/13930#-N2vXKnd2FA1Yqw4X3IA:-N2vror78eVYE9ugNeCp:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/530e52624a9096c90bc5a25490800622f05f1434/v21.2/constraints.md#L55)):*
<details><summary><i>Previously, nickvigilante (Nick Vigilante) wrote…</i></summary><blockquote>

Nit and slightly outside the scope of this ticket but: can you link to the docs page here? https://www.cockroachlabs.com/docs/v22.1/default-value.html
</blockquote></details>

Done.
___
*[`v21.2/use-cloud-storage-for-bulk-operations.md` line 127 at r1](https://reviewable.io/reviews/cockroachdb/docs/13930#-N2vaawoAonf2AUyen0V:-N2vsBZ748Gtpm5WJTXL:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/530e52624a9096c90bc5a25490800622f05f1434/v21.2/use-cloud-storage-for-bulk-operations.md#L127)):*
<details><summary><i>Previously, nickvigilante (Nick Vigilante) wrote…</i></summary><blockquote>

Same nit.
</blockquote></details>

Done.
___
*[`v22.1/constraints.md` line 55 at r1](https://reviewable.io/reviews/cockroachdb/docs/13930#-N2vaWB0BjJq0lfibSx1:-N2vrnL9BRT54WSdhgUq:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/530e52624a9096c90bc5a25490800622f05f1434/v22.1/constraints.md#L55)):*
<details><summary><i>Previously, nickvigilante (Nick Vigilante) wrote…</i></summary><blockquote>

Same nit.
</blockquote></details>

Done.
___
*[`v22.1/use-cloud-storage-for-bulk-operations.md` line 127 at r1](https://reviewable.io/reviews/cockroachdb/docs/13930#-N2v_mdfC8yBf8rB9zSr:-N2vsAKi9aXE01fmGSK1:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/530e52624a9096c90bc5a25490800622f05f1434/v22.1/use-cloud-storage-for-bulk-operations.md#L127)):*
<details><summary><i>Previously, nickvigilante (Nick Vigilante) wrote…</i></summary><blockquote>

Nit: I think i.e., should be used in a parenthetical expression. Can you make that happen?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-25 15:55 UTC, merged