Add cmek tutorial
cockroachdb/docs pull request #14035
Opened 2022-06-06 20:04 UTC by MichaelTrestman

2022-06-06 20:04 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/14035)
<!-- Reviewable:end -->

2022-06-08 13:35 UTC, MichaelTrestman commented
Just a heads up @kathancox @adwittumuluri @abhinavg6 
The GCP page is not ready yet, but I needed to get this into review ASAP to get it published ASAP.

2022-06-08 15:11 UTC, kathancox reviewed
Hey Michael, here is the review for everything besides the GCP page. If you have questions let me know

2022-06-08 15:11 UTC, kathancox commented on cockroachcloud/managing-cmek.md
> +Eventually, you'll resolve the security incident and re-authorize CMEK for your cluster to return to normal operations.
Maybe here: 

"Once you have resolved the security incident, re-authorize CMEK for your cluster..."

To remove the future tense and "eventually", which sounds a little off – like this is going to take some time (even if it is).

2022-06-08 15:11 UTC, kathancox commented on cockroachcloud/managing-cmek.md
> +To restore CMEK after the incident has been resolved, reach out to your account team, or [creating a support ticket](https://support.cockroachlabs.com/)
Typo: "or create a support ticket" (remove the gerund)

2022-06-08 19:00 UTC, abhinavg6 requested changes
> Reviewed 1 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14035)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adwittumuluri, @kathancox, and @MichaelTrestman)

___
*[`_includes/v22.1/sidebar-data/manage.json` line 184 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43IAYc1uQ8pwxajkni:-N43IAYc1uQ8pwxajknj:b-7sxtoj) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/_includes/v22.1/sidebar-data/manage.json#L184)):*
> ```JSON
>               "items": [
>                 {
>                   "title": "Managing Customer Managed Encryption Keys (CMEK) for Cockroach Dedicated",
> ```

"CockroachDB Dedicated"
___
*[`_includes/v22.1/sidebar-data/manage.json` line 190 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43foFp4u8Pj5b7CWw5:-N43foFp4u8Pj5b7CWw6:b8uvnx9) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/_includes/v22.1/sidebar-data/manage.json#L190)):*
> ```JSON
>                 },
>                 {
>                   "title": "Provisioning Amazon Web Services (AWS) for CMEK",
> ```

I think the title is misleading. It should be something like "Provision CMEK key and role on AWS"
___
*[`_includes/v22.1/sidebar-data/manage.json` line 196 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43fzreEnm8U0MyYAyz:-N43fzreEnm8U0MyYAz-:b8uz2xy) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/_includes/v22.1/sidebar-data/manage.json#L196)):*
> ```JSON
>                 },
>                 {
>                   "title": "Provisioning Google Cloud Platform (GCP) for CMEK",
> ```

I think the title is misleading. It should be something like "Provision CMEK key and role on GCP"
___
*[`cockroachcloud/cmek-faq.md` line 26 at r2](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXa8-r2-26:-N43Jvrb2kSOG0hfV5SK:bf71775) ([raw file](https://github.com/cockroachdb/docs/blob/3790af43e19741f059f709acc127ca657ceb887d/cockroachcloud/cmek-faq.md#L26)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

on "managed backups" might link to: https://www.cockroachlabs.com/docs/cockroachcloud/backups-page.html
</blockquote></details>

"CockroachDB Dedicated"
Apart from the "managed backups" link, we could also add for "backup encryption" - https://www.cockroachlabs.com/docs/stable/take-and-restore-encrypted-backups.html
___
*[`cockroachcloud/cmek-faq.md` line 3 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43IQgTEnZKYlwJ8KOx:-N43IQgTEnZKYlwJ8KOy:b-7sxtoj) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-faq.md#L3)):*
> ```Markdown
> ---
> title: Customer Managed Encryption Keys (CMEK) Frequently Asked Questions (FAQ)
> summary: Frequently Asked Questions (FAQ)concerning Customer Managed Encryption Keys (CMEK) for CockroachDB Cloud Dedicated
> ```

"CockroachDB Dedicated"
___
*[`cockroachcloud/cmek-faq.md` line 10 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43IfvV2JdrNHMBjeAU:-N43IfvV2JdrNHMBjeAV:bdgwqfi) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-faq.md#L10)):*
> ```Markdown
> ## If we don’t enable CMEK for our CockroachDB Dedicated clusters, are those encrypted in some manner by default?
> 
> Yes, the CockroachDB Dedicated clusters are encrypted by default by the way of encrypting the cloud disks used to store the data, using cloud provider managed keys (unique to each cloud account).
> ```

Let's remove the "unique to each cloud account" as this is all managed by the cloud provider under the hood, and we may by mistake provide incorrect information. I know it was like this in my private doc, but just thinking about it now as it's about to go public.
___
*[`cockroachcloud/cmek-faq.md` line 22 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43JXZx-sMG1ffi8dYD:-N43JXZx-sMG1ffi8dYE:blzszbb) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-faq.md#L22)):*
> ```Markdown
> ## If we enable CMEK for a cluster that has been in use for some time, is the existing data encrypted at that time?
> 
> CockroachDB Dedicated does not force encryption of the older files but instead relies on normal storage engine churn for desired encryption. That means the new key is used to encrypt new writes, while the old data remains unencrypted unless it’s rewritten.
> ```

"older files -> "older data"
___
*[`cockroachcloud/cmek-faq.md` line 24 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43JcRE4hKkPHMLTcbm:-N43JcRF5LA8jXRUrsHw:bscdwrx) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-faq.md#L24)):*
> ```Markdown
> CockroachDB Dedicated does not force encryption of the older files but instead relies on normal storage engine churn for desired encryption. That means the new key is used to encrypt new writes, while the old data remains unencrypted unless it’s rewritten.
> 
> ## Are CockroachDB Cloud managed backups also encrypted using the CMEK?
> ```

"CockroachDB Dedicated managed backups...."
___
*[`cockroachcloud/cmek-ops-aws.md` line 22 at r2](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXa9-r2-22:-N43Rw9HDGjdu9GU8J7D:b-pxsjmt) ([raw file](https://github.com/cockroachdb/docs/blob/3790af43e19741f059f709acc127ca657ceb887d/cockroachcloud/cmek-ops-aws.md#L22)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

**Optional:** break up this sentence a little for clarity 

"""
Here we will create a 'cross-account IAM role', i.e., a role in your AWS account that can be temporarily assumed by users in another account, in this case, Cockroach Labs' account.
""" 

Here we will create a _cross-account IAM role_. That is, a role in your AWS account that can be temporarily assumed by users in another account, in this case, Cockroach Labs' account.
</blockquote></details>

1. I would replace "cockroach Labs" with CockroachDB Dedicated since we want to talk about the product rather than the business legal entity.
2. Remove "(temporarily)" as there's nothing temporary about it. Once they establish the trust relationship with our account, it's available for min(lifetime of the cluster, lifetime of the role)
3. "encrypt and decrypt the data for you"
___
*[`cockroachcloud/cmek-ops-aws.md` line 28 at r2](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXa9-r2-28:-N43V6Cr8LwZ0YUgGand:bcc5qb2) ([raw file](https://github.com/cockroachdb/docs/blob/3790af43e19741f059f709acc127ca657ceb887d/cockroachcloud/cmek-ops-aws.md#L28)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

period or colon at the end of this sentence.
</blockquote></details>

Also "CockroachDB Dedicated"
___
*[`cockroachcloud/cmek-ops-aws.md` line 47 at r2](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXa9-r2-47:-N43Vbto-fuBgHbiBCqA:b-w2ct0e) ([raw file](https://github.com/cockroachdb/docs/blob/3790af43e19741f059f709acc127ca657ceb887d/cockroachcloud/cmek-ops-aws.md#L47)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

"such as..." This sentence doesn't continue? I think you accidentally missed something here
</blockquote></details>

"You do not need to add any permissions." - not true. So the IAM policy permissions part is included in the KMS key setup below, but that's not what we are recommending. 

The key setup part should be mentioned first - https://docs.google.com/document/d/1-3oBmSK5ANYOfJBKjdG38-pBcnpa0NlVgYwhUjzOcWE/edit#heading=h.lytmrxxgf9l1 and then the IAM role setup part should be included - https://docs.google.com [...]

2022-06-08 20:57 UTC, adwittumuluri commented
*[`cockroachcloud/cmek-ops-gcp.md` line 32 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43a3pZ0HXOxgagnWiJ:-N444rRD3B74wfqr7YTn:b3crhqb) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-ops-gcp.md#L32)):*
> we should direct them to the cluster page on the UI

yeah, FWIW I get the cluster ID from the URL in the browser.

```
https://cockroachlabs.cloud/cluster/12433f5e-1b5b-4799-996f-65687f505560/overview
```

One can also use the [list clusters API](https://www.cockroachlabs.com/docs/api/cloud/v1#operation/CockroachCloud_ListClusters), but that may or may not be more painful.


<!-- Sent from Reviewable.io -->

2022-06-09 02:01 UTC, MichaelTrestman reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14035)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abhinavg6, @adwittumuluri, @kathancox, and @MichaelTrestman)

___
*[`cockroachcloud/cmek-ops-aws.md` line 47 at r2](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXa9-r2-47:-N45AvAcDY7GFhQRJAM8:b-ur9pv5) ([raw file](https://github.com/cockroachdb/docs/blob/3790af43e19741f059f709acc127ca657ceb887d/cockroachcloud/cmek-ops-aws.md#L47)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

"You do not need to add any permissions." - not true. So the IAM policy permissions part is included in the KMS key setup below, but that's not what we are recommending. 

The key setup part should be mentioned first - https://docs.google.com/document/d/1-3oBmSK5ANYOfJBKjdG38-pBcnpa0NlVgYwhUjzOcWE/edit#heading=h.lytmrxxgf9l1 and then the IAM role setup part should be included - https://docs.google.com/document/d/1-3oBmSK5ANYOfJBKjdG38-pBcnpa0NlVgYwhUjzOcWE/edit#heading=h.6ybbo3lwa309 where one would also setup the IAM policy to access the key.
</blockquote></details>

@adwittumuluri provided me with this KMS policy, so I adapted things to use that. https://cockroachlabs.slack.com/archives/C02Q8MLFFE0/p1654618195286519?thread_ts=1654612173.345149&cid=C02Q8MLFFE0

If you want to specify for some reason that the key must be created first, then the key must be created without reference to a pre-existing role and I'll need to add a step afterwards to update the KMS policy to refer to the user. I don't see why that is better.
___
*[`cockroachcloud/cmek-ops-aws.md` line 88 at r2](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXa9-r2-88:-N44E7ChDqG_B3j9_hQR:b7hohlq) ([raw file](https://github.com/cockroachdb/docs/blob/3790af43e19741f059f709acc127ca657ceb887d/cockroachcloud/cmek-ops-aws.md#L88)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

Is this just a case of hitting a button? No further guidance needed?
</blockquote></details>

No further guidance that is in scope for this tutorial, I believe. @abhinavg6  @adwittumuluri 
___
*[`cockroachcloud/cmek-ops-aws.md` line 64 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43XGDb-LcGYeVWcm1N:-N44ESRO3RVmKr6C-g0B:b-qeq30z) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-ops-aws.md#L64)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

Added a note above on sequencing. I think this IAM policy section should be part of the IAM role setup (like in the private doc), and the whole key setup and IAM role setup sequencing should be reversed. Otherwise, customers may confuse the IAM policy with KMS key policy.
</blockquote></details>

This is the key policy. 


<!-- Sent from Reviewable.io -->

2022-06-09 02:13 UTC, MichaelTrestman reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14035)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abhinavg6, @adwittumuluri, @kathancox, and @MichaelTrestman)

___
*[`_includes/v22.1/sidebar-data/manage.json` line 184 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43IAYc1uQ8pwxajkni:-N45C2n98hO3z8DfRN5G:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/_includes/v22.1/sidebar-data/manage.json#L184)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

"CockroachDB Dedicated"
</blockquote></details>

Done.
___
*[`_includes/v22.1/sidebar-data/manage.json` line 190 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43foFp4u8Pj5b7CWw5:-N45CK5F-yJQX5A9nF82:b9o5nr8) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/_includes/v22.1/sidebar-data/manage.json#L190)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

I think the title is misleading. It should be something like "Provision CMEK key and role on AWS"
</blockquote></details>

I'm referring to CMEK the feature. You're provisioning your IaaS resources for the feature, CMEK. If you can "enable CMEK", you can Provision GCP for CMEK. It's consistent with the way we talk throughout IMO. Is that diction incorrect?
___
*[`_includes/v22.1/sidebar-data/manage.json` line 196 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43fzreEnm8U0MyYAyz:-N45Ctg85U1T5kfOEsh5:be3mh1s) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/_includes/v22.1/sidebar-data/manage.json#L196)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

I think the title is misleading. It should be something like "Provision CMEK key and role on GCP"
</blockquote></details>

as above. I strongly dislike "CMEK key" as I do "ATM machine".
___
*[`cockroachcloud/cmek-faq.md` line 8 at r2](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXa8-r2-8:-N45DUiXE__5unvkz_uF:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3790af43e19741f059f709acc127ca657ceb887d/cockroachcloud/cmek-faq.md#L8)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

As the vale has pointed out, find and replace on the product names to use the variables
</blockquote></details>

Done.
___
*[`cockroachcloud/cmek-faq.md` line 18 at r2](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXa8-r2-18:-N45Dj52EYrEcewjdH3m:b-arbaht) ([raw file](https://github.com/cockroachdb/docs/blob/3790af43e19741f059f709acc127ca657ceb887d/cockroachcloud/cmek-faq.md#L18)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

Nit: add "The" before "ability". 

Also "would be available" or "will be available"? We don't necessarily want future looking language, but the conditional seems off here after "Not yet". It seems a little frustrating for the user to read the "Once that's ready" part of this answer... because they don't know when this will be available, so they can't enact that yet. I don't know the plans and I know you mentioned we might need to refer to future features, so this is just a thought.
</blockquote></details>

Yeah it should just be "will" grammatically. I don't know if we want this to be an exception to our antifuturist policy. I don't know who decides this. @abhinavg6 how definite is this, pretty definite right? how critical is this, pretty critical, right? The feature isn't complete if you can't rotate your key, is that not correct?
___
*[`cockroachcloud/cmek-faq.md` line 10 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43IfvV2JdrNHMBjeAU:-N45DbkKEqNVjpufzhS3:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-faq.md#L10)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

Let's remove the "unique to each cloud account" as this is all managed by the cloud provider under the hood, and we may by mistake provide incorrect information. I know it was like this in my private doc, but just thinking about it now as it's about to go public.
</blockquote></details>

Done.
___
*[`cockroachcloud/cmek-ops-gcp.md` line 8 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43X_bD9cWIeZvQ565G:-N45BzQw5Yb6lUpOboHL:b-7rl0jd) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-ops-gcp.md#L8)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

nit - "required"
</blockquote></details>

done.
___
*[`cockroachcloud/cmek-ops-gcp.md` line 13 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43XfQd8D6LCD9ySLTu:-N45BuGM2dxxa2lEN-5d:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-ops-gcp.md#L13)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

"IAM role" -> "Service account"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-09 02:40 UTC, MichaelTrestman reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14035)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abhinavg6, @adwittumuluri, @kathancox, and @MichaelTrestman)

___
*[`cockroachcloud/cmek-faq.md` line 26 at r2](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXa8-r2-26:-N45F-TxAhnV-5dTWbK9:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3790af43e19741f059f709acc127ca657ceb887d/cockroachcloud/cmek-faq.md#L26)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

"CockroachDB Dedicated"
Apart from the "managed backups" link, we could also add for "backup encryption" - https://www.cockroachlabs.com/docs/stable/take-and-restore-encrypted-backups.html
</blockquote></details>

Done.
___
*[`cockroachcloud/cmek-faq.md` line 46 at r2](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXa8-r2-46:-N45F2N-0RAuUoiKD4je:b-ghl3ph) ([raw file](https://github.com/cockroachdb/docs/blob/3790af43e19741f059f709acc127ca657ceb887d/cockroachcloud/cmek-faq.md#L46)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

Nit: cap "id"
</blockquote></details>

cluster id and cluster ego?
___
*[`cockroachcloud/cmek-faq.md` line 22 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43JXZx-sMG1ffi8dYD:-N45EKhSDugXwDvbFnt0:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-faq.md#L22)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

"older files -> "older data"
</blockquote></details>

Done.
___
*[`cockroachcloud/cmek-faq.md` line 24 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43JcRE4hKkPHMLTcbm:-N45EYjW2yUXUmEz8wxV:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-faq.md#L24)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

"CockroachDB Dedicated managed backups...."
</blockquote></details>

Done.
___
*[`cockroachcloud/cmek-ops-aws.md` line 8 at r2](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXa9-r2-8:-N45FE0gA5WoQMNdlS44:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3790af43e19741f059f709acc127ca657ceb887d/cockroachcloud/cmek-ops-aws.md#L8)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

Typo on "required"
</blockquote></details>

Done.
___
*[`cockroachcloud/cmek-ops-aws.md` line 22 at r2](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXa9-r2-22:-N45GH14-2Cl6zbIhwgc:bmfz5jc) ([raw file](https://github.com/cockroachdb/docs/blob/3790af43e19741f059f709acc127ca657ceb887d/cockroachcloud/cmek-ops-aws.md#L22)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

1. I would replace "cockroach Labs" with CockroachDB Dedicated since we want to talk about the product rather than the business legal entity.
2. Remove "(temporarily)" as there's nothing temporary about it. Once they establish the trust relationship with our account, it's available for min(lifetime of the cluster, lifetime of the role)
3. "encrypt and decrypt the data for you"
</blockquote></details>

Dones.
___
*[`cockroachcloud/cmek-ops-aws.md` line 28 at r2](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXa9-r2-28:-N45Jp8_CDPwQl-tcryV:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3790af43e19741f059f709acc127ca657ceb887d/cockroachcloud/cmek-ops-aws.md#L28)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

Also "CockroachDB Dedicated"
</blockquote></details>

Done.
___
*[`cockroachcloud/cmek-ops-aws.md` line 45 at r2](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXa9-r2-45:-N45JtP-5yQ-0a-KzCHU:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3790af43e19741f059f709acc127ca657ceb887d/cockroachcloud/cmek-ops-aws.md#L45)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

Typo: "For **Account ID**, provide the provide the" 

^ double up on "provide the"
</blockquote></details>

Done.
___
*[`cockroachcloud/cmek-ops-aws.md` line 47 at r2](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXa9-r2-47:-N45K3zm59CJVyb3ZmVI:b-gq70qv) ([raw file](https://github.com/cockroachdb/docs/blob/3790af43e19741f059f709acc127ca657ceb887d/cockroachcloud/cmek-ops-aws.md#L47)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

@adwittumuluri provided me with this KMS policy, so I adapted things to use that. https://cockroachlabs.slack.com/archives/C02Q8MLFFE0/p1654618195286519?thread_ts=1654612173.345149&cid=C02Q8MLFFE0

If you want to specify for some reason that the key must be created first, then the key must be created without reference to a pre-existing role and I'll need to add a step afterwards to update the KMS policy to refer to the user. I don't see why that is better.
</blockquote></details>

But should I do that? If so, I need a different IAM policy for the cross-account role then. @adwittumuluri could you provide that?
And if that is provided, then the key can be created with the default policy, correct?
___
*[`cockroachcloud/cmek-ops-aws.md` line 17 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43LJJY84oAdg_rf_tV:-N45FTWV8o2rqocPfu3x:b-e0lif4) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-ops-aws.md#L17)):*
> https://docs.aws.amazon.com/kms/latest/developerguide/multi-region-keys-overview.html
Added the link but I'm not seeing the upside of breaking it out into a 2 and one vs a three point list... Is there more contextual info to add to differentiate the use case or something I'm missing?
___
*[`cockroachcloud/cmek-ops-aws.md` line 25 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43TLr4AsY449jp1sk1:-N45IgFc82Ee-qoxGrIH:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-ops-aws.md#L25)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

The Organization ID is in the "Organization Settings" page - https://www.cockroachlabs.com/docs/cockroachcloud/console-access-management.html#organization.

Also, what does "link" mean in "to create this link"? Does it refer to the "cross-account connection"? If yes, could we be a bit explicit / specific here?
</blockquote></details>

Done.
___
*[`cockroachcloud/cmek-ops-aws.md` line 27 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43UR7K0rMqvr3bbsTB:-N45Jij_Exj2RAnIMt3v:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-ops-aws.md#L27)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

There's no "updated" Org ID concept now since Cloud API is in Preview and enabled for all customers. Earlier when Cloud API was in private preview, there was a difference between what kind of Org ID we showed in the UI, but that's not the case anymore. So we could remove the "updated".
</blockquote></details>

Done.
___
*[`cockroachcloud/cmek-ops-aws.md` line 32 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43V9ixA_mk5UtSp9yZ:-N45JqYx3mGVmjtzyls1:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-ops-aws.md#L32)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

"CockroachDB Dedicated"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-09 14:45 UTC, MichaelTrestman reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14035)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abhinavg6, @adwittumuluri, @kathancox, and @MichaelTrestman)

___
*[`cockroachcloud/cmek-faq.md` line 3 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43IQgTEnZKYlwJ8KOx:-N47rEH8AJ7QeeWq-j5o:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-faq.md#L3)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

"CockroachDB Dedicated"
</blockquote></details>

Done.
___
*[`cockroachcloud/cmek-ops-aws.md` line 92 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43XWM_-X_paW89IO10:-N47rHGvAQ3xhTLyYjXe:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-ops-aws.md#L92)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

"CockroachDB Dedicated"
</blockquote></details>

Done.
___
*[`cockroachcloud/cmek-ops-gcp.md` line 17 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43XjsA9OhuXAVh1N8Y:-N47rJX-9B4ltf-IgCrg:b-ruazig) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-ops-gcp.md#L17)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

Just like commented for AWS, this should be a separate statement below rather than a point in this list. Plus in GCP's case, we should indicate "You could use dual-region, multi-region or global keys as well" by linking to https://cloud.google.com/kms/docs/locations.
</blockquote></details>

same response as above, added the link but not seeing the restructure.
___
*[`cockroachcloud/cmek-ops-gcp.md` line 20 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43_c6R04da301ontez:-N47rUir2dV7QmM26zZ8:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-ops-gcp.md#L20)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

"IAM role" -> "Service account"
</blockquote></details>

Done.
___
*[`cockroachcloud/cmek-ops-gcp.md` line 22 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43_frVCFxpnPIrimIl:-N47rZgp8Tef6N2OOWhW:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-ops-gcp.md#L22)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

Same feedback as in AWS section.
</blockquote></details>

Done.
___
*[`cockroachcloud/cmek-ops-gcp.md` line 25 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43_o1l2XGgnH8MreXZ:-N47rbfjBxBBqJt_n2R2:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-ops-gcp.md#L25)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

Same feedback as in AWS section.
</blockquote></details>

Done.
___
*[`cockroachcloud/cmek-ops-gcp.md` line 27 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43_rBd0JKOCvWVKZTQ:-N47rsDJ2MiIiG8qZh91:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-ops-gcp.md#L27)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

Same feedback as in AWS section.
</blockquote></details>

Done.
___
*[`cockroachcloud/cmek-ops-gcp.md` line 30 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43_sB7A8HU-RI1f9Qp:-N47rsQ5-GkBWzQh4Lc-:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-ops-gcp.md#L30)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

"CockroachDB Dedicated"
</blockquote></details>

Done.
___
*[`cockroachcloud/cmek-ops-gcp.md` line 32 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43a3pZ0HXOxgagnWiJ:-N47v7y54_J8Dy1F_rOl:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-ops-gcp.md#L32)):*
<details><summary><i>Previously, adwittumuluri wrote…</i></summary><blockquote>

> we should direct them to the cluster page on the UI

yeah, FWIW I get the cluster ID from the URL in the browser.

```
https://cockroachlabs.cloud/cluster/12433f5e-1b5b-4799-996f-65687f505560/overview
```

One can also use the [list clusters API](https://www.cockroachlabs.com/docs/api/cloud/v1#operation/CockroachCloud_ListClusters), but that may or may not be more painful.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-09 16:31 UTC, adwittumuluri reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14035)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abhinavg6, @adwittumuluri, @kathancox, and @MichaelTrestman)

___
*[`_includes/v22.1/sidebar-data/manage.json` line 196 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43fzreEnm8U0MyYAyz:-N48BDfOA0lcEqmX4Fkt:b-d269rw) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/_includes/v22.1/sidebar-data/manage.json#L196)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

as above. I strongly dislike "CMEK key" as I do "ATM machine".
</blockquote></details>

I  dislike it as well, but I've been doing it anyway after noticing [GCP](https://cloud.google.com/kms/docs/cmek#cmek_integrations) say's "CMEK key", too :laughing: . No opinions
___
*[`_includes/v22.1/sidebar-data/manage.json` line 180 at r6](https://reviewable.io/reviews/cockroachdb/docs/14035#-N48BvxECRCQZ7kJVZYA:-N48BvxECRCQZ7kJVZYB:b-hpda0l) ([raw file](https://github.com/cockroachdb/docs/blob/715c63ac0de48f470021ac50097710599e90f3d8/_includes/v22.1/sidebar-data/manage.json#L180)):*
> ```JSON
>           "items": [
>             {
>               "title": "Customer Managed Encryption Keys (CMEK) for CockroachDB Dedicated",
> ```

pedantic nit x2: [We decided](https://cockroachlabs.slack.com/archives/C02Q8MLFFE0/p1643317344036900) that this should be "Customer-Managed Encryption Keys" (note the hyphen). Made [a similar note](https://reviewable.io/reviews/cockroachdb/docs/13963#-N3PH1i54cVHUejSCDvu) on the other docs too.
___
*[`cockroachcloud/cmek-ops-aws.md` line 88 at r2](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXa9-r2-88:-N48HD4f18IAOiV-gb_Q:b-fk3si) ([raw file](https://github.com/cockroachdb/docs/blob/3790af43e19741f059f709acc127ca657ceb887d/cockroachcloud/cmek-ops-aws.md#L88)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

No further guidance that is in scope for this tutorial, I believe. @abhinavg6  @adwittumuluri 
</blockquote></details>

Yeah, seems like we need to just hit "Finish." Just a notethough - there's a "Define key usage permissions" screen that the user can use rather than editing the key policy directly. They both amount to the same thing.

![Screen Shot 2022-06-09 at 12.25.50 PM.png](https://files.reviewableusercontent.io/images/reviewable/4492794/8TjrqF4M3KBy4PA1hEBEsoSa/Screen%20Shot%202022-06-09%20at%2012.25.50%20PM.png)
___
*[`cockroachcloud/cmek-ops-aws.md` line 17 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43LJJY84oAdg_rf_tV:-N48F62v6e3W2FFsg0kE:be0d496) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-ops-aws.md#L17)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

> https://docs.aws.amazon.com/kms/latest/developerguide/multi-region-keys-overview.html
Added the link but I'm not seeing the upside of breaking it out into a 2 and one vs a three point list... Is there more contextual info to add to differentiate the use case or something I'm missing?
</blockquote></details>

One must provide a key (same or different) for each region in the cluster. These keys can be single-region, multi-region, or any combination across regions. I think the first two points have a different context than the third. To clarify:

User's can configure: 

- same key in all regions
- different key per region
- (optional point) honestly, any combination thereof - e.g. same for 2 regions, different for third

side note: makes no difference if these keys are multi-region or single region.


<!-- Sent from Reviewable.io -->

2022-06-09 17:11 UTC, MichaelTrestman reviewed
Thanks.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14035#-:-N48Rko9DgdNFnpjgjzg:b-ucfkn4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abhinavg6, @adwittumuluri, @kathancox, @mdlinville, and @mikeCRL)

___
*[`_includes/v22.1/sidebar-data/manage.json` line 196 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43fzreEnm8U0MyYAyz:-N484SAY5TZT7BUcME6F:bdk95zz) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/_includes/v22.1/sidebar-data/manage.json#L196)):*
<details><summary><i>Previously, adwittumuluri wrote…</i></summary><blockquote>

I  dislike it as well, but I've been doing it anyway after noticing [GCP](https://cloud.google.com/kms/docs/cmek#cmek_integrations) say's "CMEK key", too :laughing: . No opinions
</blockquote></details>

Eh, I guess "CMEK key" is better than using "CMEK" for both the feature and the name of the key. I don't love it thought :/ 
___
*[`_includes/v22.1/sidebar-data/manage.json` line 180 at r6](https://reviewable.io/reviews/cockroachdb/docs/14035#-N48BvxECRCQZ7kJVZYA:-N48RdFD5Q0evO-RwOro:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/715c63ac0de48f470021ac50097710599e90f3d8/_includes/v22.1/sidebar-data/manage.json#L180)):*
<details><summary><i>Previously, adwittumuluri wrote…</i></summary><blockquote>

pedantic nit x2: [We decided](https://cockroachlabs.slack.com/archives/C02Q8MLFFE0/p1643317344036900) that this should be "Customer-Managed Encryption Keys" (note the hyphen). Made [a similar note](https://reviewable.io/reviews/cockroachdb/docs/13963#-N3PH1i54cVHUejSCDvu) on the other docs too.
</blockquote></details>

Done.
___
*[`cockroachcloud/cmek-ops-aws.md` line 88 at r2](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXa9-r2-88:-N48Msfo6KBLf8rglE32:b-xrt6tg) ([raw file](https://github.com/cockroachdb/docs/blob/3790af43e19741f059f709acc127ca657ceb887d/cockroachcloud/cmek-ops-aws.md#L88)):*
<details><summary><i>Previously, adwittumuluri wrote…</i></summary><blockquote>

Yeah, seems like we need to just hit "Finish." Just a notethough - there's a "Define key usage permissions" screen that the user can use rather than editing the key policy directly. They both amount to the same thing.

![Screen Shot 2022-06-09 at 12.25.50 PM.png](https://files.reviewableusercontent.io/images/reviewable/4492794/8TjrqF4M3KBy4PA1hEBEsoSa/Screen%20Shot%202022-06-09%20at%2012.25.50%20PM.png)

</blockquote></details>

Yeah, about KMS stuff, @adwittumuluri, we need to chat and get clear what we're doing here.
___
*[`cockroachcloud/cmek-ops-aws.md` line 17 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43LJJY84oAdg_rf_tV:-N48MlkV4WSGjQSbOlYh:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-ops-aws.md#L17)):*
<details><summary><i>Previously, adwittumuluri wrote…</i></summary><blockquote>

One must provide a key (same or different) for each region in the cluster. These keys can be single-region, multi-region, or any combination across regions. I think the first two points have a different context than the third. To clarify:

User's can configure: 

- same key in all regions
- different key per region
- (optional point) honestly, any combination thereof - e.g. same for 2 regions, different for third

side note: makes no difference if these keys are multi-region or single region.
</blockquote></details>

Done.
___
*[`cockroachcloud/cmek-ops-gcp.md` line 45 at r4](https://reviewable.io/reviews/cockroachdb/docs/14035#-N43bbLjBVch4PK3d0tw:-N486Tju5Ndx3GWZ8lgn:bzaqh6h) ([raw file](https://github.com/cockroachdb/docs/blob/91dd10741fb5fb19f9b5e927473163bfbbd82a2b/cockroachcloud/cmek-ops-gcp.md#L45)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

I guess all of this needs to change
</blockquote></details>

Yes, this page wasn't ready for review...
___
*[`cockroachcloud/managing-cmek.md` line 2 at r2](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXaA-r2-2:-N47vaQF4DfEaGiRaPlF:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3790af43e19741f059f709acc127ca657ceb887d/cockroachcloud/managing-cmek.md#L2)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

The product name in the title isn't quite right here. Missing the "DB"
</blockquote></details>

Done.
___
*[`cockroachcloud/managing-cmek.md` line 10 at r2](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXaA-r2-10:-N47vmVq6PnE3JtqJM-M:bb7f2mf) ([raw file](https://github.com/cockroachdb/docs/blob/3790af43e19741f059f709acc127ca657ceb887d/cockroachcloud/managing-cmek.md#L10)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

Switch out "walks the user through" for "demonstrates" or similar for inclusivity
</blockquote></details>

done
___
*[`cockroachcloud/managing-cmek.md` line 19 at r2](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXaA-r2-19:-N47w3Rp8Vb513B4U2yl:biulu04) ([raw file](https://github.com/cockroachdb/docs/blob/3790af43e19741f059f709acc127ca657ceb887d/cockroachcloud/managing-cmek.md#L19)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

"CockroachDB Dedicated"
</blockquote></details>

Done.
We use "overview" everywhere, but that is actually quite explicitly ableist. Gonna bring this up in #docs-style
___
*[`cockroachcloud/managing-cmek.md` line 34 at r2](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXaA-r2-34:-N4873CB-fVIFUxDL2N3:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3790af43e19741f059f709acc127ca657ceb887d/cockroachcloud/managing-cmek.md#L34)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

"service team" -> "support team"
</blockquote></details>

Done.
___
*[`cockroachcloud/managing-cmek.md` line 54 at r2](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXaA-r2-54:-N48AitF1ByUcpLH2fHI:bb7f2mf) ([raw file](https://github.com/cockroachdb/docs/blob/3790af43e19741f059f709acc127ca657ceb887d/cockroachcloud/managing-cmek.md#L54)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

Optional nit: "You can do this either of two ways" 
this doesn't sound quite right. I wonder if "You can do this one of two ways" might be clearer
</blockquote></details>

done
___
*[`cockroachcloud/managing-cmek.md` line 73 at r2](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXaA-r2-73:-N48FkYf2F3MnfjLJ-WO:b-mixmr) ([raw file](https://github.com/cockroachdb/docs/blob/3790af43e19741f059f709acc127ca657ceb887d/cockroachcloud/managing-cmek.md#L73)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

OK, not sure on this, is Check CMEK Status under Step 4? And then "Revoking CMEK for a cluster" is a new section?
</blockquote></details>

I meant Check CMEK Status to be a h2, it's a seperate operation you can do a la cart. And I link to it from a couple places.
___
*[`cockroachcloud/managing-cmek.md` line 88 at r2](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXaA-r2-88:-N48N3_332JBmx8M7LgZ:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3790af43e19741f059f709acc127ca657ceb887d/cockroachcloud/managing-cmek.md#L88)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

"database" -> "cluster"
</blockquote></details>

Done.
___
*[`cockroachcloud/managing-cmek.md` line 100 at r2](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXaA-r2-100:-N48N87jDhulIKC_49Ed:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3790af43e19741f059f709acc127ca657ceb887d/cockroachcloud/managing-cmek.md#L100)):*
<details><summary><i>Previously,  [...]

2022-06-09 22:36 UTC, kathancox approved these changes
A couple of places where there are some minor rendering issues to fix and a couple of typos. Otherwise, LGTM

2022-06-09 22:36 UTC, kathancox commented on cockroachcloud/cmek-ops-aws.md
> +1. Find your {{ site.data.products.dedicated }} organization ID in the {{ site.data.products.db }} [organization settings page] [cluster page](https://cockroachlabs.cloud/settings).
This is the same on the GCP page?

2022-06-09 22:36 UTC, kathancox commented on cockroachcloud/cmek-ops-gcp.md
> +1. Find your {{ site.data.products.dedicated }} cluster's associated GCP Project ID
Missing a period at the end of this sentence after "Project ID"

2022-06-09 22:36 UTC, kathancox commented on cockroachcloud/cmek-ops-gcp.md
> +	- `id`: your cluster id
Cap "id" on "cluster ID"?

2022-06-09 22:36 UTC, kathancox commented on cockroachcloud/cmek-ops-gcp.md
> +1.  Create a a cross-tenant service account in your GCP project:
Typo: Double-up on "a" after "Create" here

2022-06-09 22:36 UTC, kathancox commented on cockroachcloud/managing-cmek.md
> +- [Encryption at Rest (enterprise)](../{{site.versions["stable"]}}/security-reference/encryption.html#encryption-at-rest-enterprise)
Cap on "(enterprise)" here

2022-06-09 22:36 UTC, kathancox commented on cockroachcloud/managing-cmek.md
> +### Step 1. Prepare your {{ site.data.products.dedicated }} Organization
At the top here you have a period after "Step" and the step number. Lower down you have a colon. Looking over other docs, looks as though we use periods after steps more widely. So, update the lower ones? I just realized I might have put ":" in some earlier feedback — sorry about that, not sure why that was in my head. So I would switch to period.

2022-06-09 22:36 UTC, kathancox commented on cockroachcloud/managing-cmek.md
> +You can do this two ways:
I think you need to add a blank line here after "You can do this two ways:" because the bullets following it aren't rendering correctly.

2022-06-10 13:30 UTC, MichaelTrestman reviewed
Thanks!!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14035#-:-N4Cnm2J7tgW0UoyBJL4:b-hay2ia)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abhinavg6, @adwittumuluri, @kathancox, @mdlinville, and @mikeCRL)

___
*[`cockroachcloud/cmek-faq.md` line 26 at r8](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXa8-r8-26:-N4CnHsE8TUe1OxKO0r2:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/9bf0c19774a4c368bb01cc27c0097ce0e6e667ac/cockroachcloud/cmek-faq.md#L26)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

I've not seen links in header text before, perhaps move the link to "managed backups" in the answer
</blockquote></details>

Done.
___
*[`cockroachcloud/cmek-faq.md` line 28 at r8](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXa8-r8-28:-N4CnM296Iklu-4QQYH7:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/9bf0c19774a4c368bb01cc27c0097ce0e6e667ac/cockroachcloud/cmek-faq.md#L28)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

There's an additional parenthesis before the start of the link address, which is making this not render properly.
</blockquote></details>

Done.
___
*[`cockroachcloud/cmek-ops-aws.md` line 20 at r8](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXa9-r8-20:-N4CndexDhzFRhOJbAwJ:bs9ri0f) ([raw file](https://github.com/cockroachdb/docs/blob/9bf0c19774a4c368bb01cc27c0097ce0e6e667ac/cockroachcloud/cmek-ops-aws.md#L20)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

This is the same on the GCP page?
</blockquote></details>

Ooh thanks, yeah I bungled that!
___
*[`cockroachcloud/cmek-ops-gcp.md` line 32 at r8](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3yp6pwnf__c18s6uMy-r8-32:-N4Cm5PMDmlIonXlywpV:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/9bf0c19774a4c368bb01cc27c0097ce0e6e667ac/cockroachcloud/cmek-ops-gcp.md#L32)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

Missing a period at the end of this sentence after "Project ID"
</blockquote></details>

Done.
___
*[`cockroachcloud/cmek-ops-gcp.md` line 44 at r8](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3yp6pwnf__c18s6uMy-r8-44:-N4CmuVyEastCU18ryJf:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/9bf0c19774a4c368bb01cc27c0097ce0e6e667ac/cockroachcloud/cmek-ops-gcp.md#L44)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

Cap "id" on "cluster ID"?
</blockquote></details>

Done.
___
*[`cockroachcloud/cmek-ops-gcp.md` line 46 at r8](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3yp6pwnf__c18s6uMy-r8-46:-N4CmF4b0FDoi3d8Utve:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/9bf0c19774a4c368bb01cc27c0097ce0e6e667ac/cockroachcloud/cmek-ops-gcp.md#L46)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

Typo: Double-up on "a" after "Create" here
</blockquote></details>

Done.
___
*[`cockroachcloud/managing-cmek.md` line 17 at r8](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXaA-r8-17:-N4CmJ3x7vFgn5zqquKf:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/9bf0c19774a4c368bb01cc27c0097ce0e6e667ac/cockroachcloud/managing-cmek.md#L17)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

Cap on "(enterprise)" here
</blockquote></details>

Done.
___
*[`cockroachcloud/managing-cmek.md` line 38 at r8](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXaA-r8-38:-N4CmaYD7B_pMKnnj9Zd:bupvrak) ([raw file](https://github.com/cockroachdb/docs/blob/9bf0c19774a4c368bb01cc27c0097ce0e6e667ac/cockroachcloud/managing-cmek.md#L38)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

At the top here you have a period after "Step" and the step number. Lower down you have a colon. Looking over other docs, looks as though we use periods after steps more widely. So, update the lower ones? I just realized I might have put ":" in some earlier feedback — sorry about that, not sure why that was in my head. So I would switch to period.
</blockquote></details>

No worries. Whenever there's a thing that can be arbitrarily one of two ways I have a hard time not randomly toggling it in my memory!
___
*[`cockroachcloud/managing-cmek.md` line 110 at r8](https://reviewable.io/reviews/cockroachdb/docs/14035#-N3ubgG7tmzefkTsCXaA-r8-110:-N4Cn-jg8b9g85wsGjCq:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/9bf0c19774a4c368bb01cc27c0097ce0e6e667ac/cockroachcloud/managing-cmek.md#L110)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

I think you need to add a blank line here after "You can do this two ways:" because the bullets following it aren't rendering correctly.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-10 14:52 UTC, merged