Request Units redefine and restructure
cockroachdb/docs pull request #14241
Opened 2022-06-09 17:30 UTC by gemma-shay

https://cockroachlabs.atlassian.net/browse/DOC-3403
https://cockroachlabs.atlassian.net/browse/DOC-4540

2022-06-09 17:45 UTC, gemma-shay commented
@emily-horing lmk your thoughts on this sidebar structure

2022-06-21 15:47 UTC, emily-horing requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14241)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing and @gemma-shay)

___
*[`_includes/v22.1/sidebar-data/deploy.json` line 27 at r1](https://reviewable.io/reviews/cockroachdb/docs/14241#-N55rN5y5f8SChQk1o5T:-N55rN5y5f8SChQk1o5U:b-em9s21) ([raw file](https://github.com/cockroachdb/docs/blob/72b4c1657e17701970c22e7eb7ea383f719e3101/_includes/v22.1/sidebar-data/deploy.json#L27)):*
> ```JSON
>               "items": [
>                 {
>                   "title": "Learn about CockroachDB Serverless",
> ```

this title seems too vague. can we just be more direct and call it "Learn about Request Units"?
___
*[`cockroachcloud/architecture.md` line 63 at r1](https://reviewable.io/reviews/cockroachdb/docs/14241#-N55ryhC-bFeASmvcfQ4:-N55ryhC-bFeASmvcfQ5:b-q9423m) ([raw file](https://github.com/cockroachdb/docs/blob/72b4c1657e17701970c22e7eb7ea383f719e3101/cockroachcloud/architecture.md#L63)):*
> ```Markdown
> ### Request Units
> 
> With CockroachDB Serverless, you are charged for the resources your cluster consumes. Storage is measured in GiB per month, based on the total volume of storage used over the billing period. Cluster activity, including SQL queries, bulk operations, and background jobs, is measured in Request Units. A Request Unit, or RU, is an abstracted metric that represents the compute, network, and I/O resources your cluster consumes. Request Unit consumption scales to zero when your cluster has no activity, so you will only be charged for what you use.
> ```

I don't think. it makes much sense to talk about pricing structure under "architecture". I would remove all of this from this page.
___
*[`cockroachcloud/architecture.md` line 77 at r1](https://reviewable.io/reviews/cockroachdb/docs/14241#-N55v3Ey7SvpPI1vsBon:-N55v3Ey7SvpPI1vsBoo:baao83f) ([raw file](https://github.com/cockroachdb/docs/blob/72b4c1657e17701970c22e7eb7ea383f719e3101/cockroachcloud/architecture.md#L77)):*
> ```Markdown
> 1 GiB storage per month | $0.50
> 
> Queries           | RUs per 1 query    | Price per 1M queries
> ```

move this to the other page
___
*[`cockroachcloud/learn-about-serverless.md` line 9 at r1](https://reviewable.io/reviews/cockroachdb/docs/14241#-N55sXcsCd6ONpDVwAov:-N55sXcsCd6ONpDVwAow:b-c3fb74) ([raw file](https://github.com/cockroachdb/docs/blob/72b4c1657e17701970c22e7eb7ea383f719e3101/cockroachcloud/learn-about-serverless.md#L9)):*
> ```Markdown
> ---
> 
> This page describes how resource usage and cluster scaling works in {{ site.data.products.serverless }}.
> ```

simplify --> "this page describes how request units and pricing work in serverless"
___
*[`cockroachcloud/learn-about-serverless.md` line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/14241#-N55sfX73AjlFFw_ffSL:-N55sfX73AjlFFw_ffSM:b895ugb) ([raw file](https://github.com/cockroachdb/docs/blob/72b4c1657e17701970c22e7eb7ea383f719e3101/cockroachcloud/learn-about-serverless.md#L13)):*
> ```Markdown
> ## Request Units
> 
> With {{ site.data.products.serverless }}, you are charged for the storage and activity of your cluster. All cluster activity, including SQL queries, bulk operations, and background jobs, is measured in Request Units, or RUs. RUs are an abstracted metric that represent the size and complexity of requests made to your cluster. All database operations cost a certain amount of RUs depending on the resources used. For example, a "small read" might cost 2 RUs, and a "large read" such as a full table scan with indexes might cost 100 RUs.
> ```

i would remove the the rough "for example" estimates in favor of actual examples. Maybe "...depending on the resources used. As a baseline, a point read of a 64 byte row will cost ~1 RU. "
___
*[`cockroachcloud/learn-about-serverless.md` line 15 at r1](https://reviewable.io/reviews/cockroachdb/docs/14241#-N55uQoB9oUOdFbkMJhC:-N55uQoB9oUOdFbkMJhD:b-j2bp56) ([raw file](https://github.com/cockroachdb/docs/blob/72b4c1657e17701970c22e7eb7ea383f719e3101/cockroachcloud/learn-about-serverless.md#L15)):*
> ```Markdown
> With {{ site.data.products.serverless }}, you are charged for the storage and activity of your cluster. All cluster activity, including SQL queries, bulk operations, and background jobs, is measured in Request Units, or RUs. RUs are an abstracted metric that represent the size and complexity of requests made to your cluster. All database operations cost a certain amount of RUs depending on the resources used. For example, a "small read" might cost 2 RUs, and a "large read" such as a full table scan with indexes might cost 100 RUs.
> 
> The cost to do a prepared point read (fetching a single row by its key) of a 64 byte row is approximately 1 RU:
> ```

I would remove these shell examples. I'm finding them to be a bit confusing because of the $1 (does that mean it costs a dollar?) and I don't think they're necessary.
___
*[`cockroachcloud/learn-about-serverless.md` line 32 at r1](https://reviewable.io/reviews/cockroachdb/docs/14241#-N55vx2YELFr9AqCpNj_:-N55vx2YELFr9AqCpNja:b-6g8ofw) ([raw file](https://github.com/cockroachdb/docs/blob/72b4c1657e17701970c22e7eb7ea383f719e3101/cockroachcloud/learn-about-serverless.md#L32)):*
> ```Markdown
>   ------------------------|------
>   10M Request Units       | $1.00
>   1 GiB storage per month | $0.50
> ```

add here instructions on where you can see your usage each month
___
*[`cockroachcloud/learn-about-serverless.md` line 34 at r1](https://reviewable.io/reviews/cockroachdb/docs/14241#-N55utyG-o7y-xjFyROc:-N55utyG-o7y-xjFyROd:b-jcn1r7) ([raw file](https://github.com/cockroachdb/docs/blob/72b4c1657e17701970c22e7eb7ea383f719e3101/cockroachcloud/learn-about-serverless.md#L34)):*
> ```Markdown
>   1 GiB storage per month | $0.50
> 
> ## Cluster scaling
> ```

before this section we should include a section of "examples of query costs" -- see note from the "architecture" page.
___
*[`cockroachcloud/learn-about-serverless.md` line 44 at r1](https://reviewable.io/reviews/cockroachdb/docs/14241#-N55vZOH804_MgCV7PrY:-N55vZOH804_MgCV7PrZ:b8fk7ss) ([raw file](https://github.com/cockroachdb/docs/blob/72b4c1657e17701970c22e7eb7ea383f719e3101/cockroachcloud/learn-about-serverless.md#L44)):*
> ```Markdown
> <img src="{{ 'images/cockroachcloud/ru-diagram.png' | relative_url }}" alt="RU diagram" style="max-width:100%" />
> 
> ## Resource usage
> ```

replace this section (not actually possible to do EXPLAIN) with a "setting spend limits" section. This should just explain what a spend limit is and when you get notified about approaching limits
___
*[`cockroachcloud/learn-about-serverless.md` line 50 at r1](https://reviewable.io/reviews/cockroachdb/docs/14241#-N55wEiv80eB3J5rs0Xs:-N55wEiv80eB3J5rs0Xt:b-md20r6) ([raw file](https://github.com/cockroachdb/docs/blob/72b4c1657e17701970c22e7eb7ea383f719e3101/cockroachcloud/learn-about-serverless.md#L50)):*
> ```Markdown
> All [Console Admins](console-access-management.html#console-admin) will receive email alerts when your cluster reaches 75% and 100% of its burst capacity or storage limit. If you set a spend limit, you will also receive alerts at 50%, 75%, and 100% of your spend limit.
> 
> ## Serverless Example 
> ```

lets call this scaling example
___
*[`cockroachcloud/learn-about-serverless.md` line 54 at r1](https://reviewable.io/reviews/cockroachdb/docs/14241#-N55wLK0DXqCLPc35XVP:-N55wLK0DXqCLPc35XVQ:b77rx8h) ([raw file](https://github.com/cockroachdb/docs/blob/72b4c1657e17701970c22e7eb7ea383f719e3101/cockroachcloud/learn-about-serverless.md#L54)):*
> ```Markdown
> Let's say you have an application that processes sensor data at the end of the week. Most of the week it handles only occasional read requests and uses under the 100 RUs per second baseline. At the end of the week the sensors send in their data to the application, requiring a performance burst over the 100 RUs per second baseline. When the cluster requires more than 100 RUs per second to cov [...]

2022-06-22 08:20 UTC, andy-kimball reviewed
I think the biggest problem for us to resolve is whether to talk in terms of "size and complexity of operations" or "resource usage". When do we talk about one vs. the other? I'm concerned it might be confusing to talk about both in the same breath. Can you explain how you're thinking we should resolve that problem?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14241#-:-N59U6MiAGDZwky4qBdl:bclupm7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @emily-horing, and @gemma-shay)

___
*[`cockroachcloud/architecture.md` line 63 at r1](https://reviewable.io/reviews/cockroachdb/docs/14241#-N55ryhC-bFeASmvcfQ4:-N59Jl2tCzvvnHSfGFaZ:b-qqlc51) ([raw file](https://github.com/cockroachdb/docs/blob/72b4c1657e17701970c22e7eb7ea383f719e3101/cockroachcloud/architecture.md#L63)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

I don't think. it makes much sense to talk about pricing structure under "architecture". I would remove all of this from this page.
</blockquote></details>

This mixes the "resources" language with the "activity" language. Do RUs measure the resources your cluster consumes? Or do they measure "cluster activity"? Also, this description doesn't match the other page where you say that RUs measure the "size and complexity of requests". It seems wrong to define RUs in two different places in the doc, using different language. I think we should have exactly one definition, and then one other detail section (somewhere) that drills down into the component parts of an RU. That detail section should specify exactly how we measure "activity" (i.e. the size and complexity of requests is determined based on measuring the CPU, egress, and I/O that those requests consume).
___
*[`cockroachcloud/architecture.md` line 77 at r1](https://reviewable.io/reviews/cockroachdb/docs/14241#-N55v3Ey7SvpPI1vsBon:-N59KQGLCB9fIKB4nEVY:b-59ydj3) ([raw file](https://github.com/cockroachdb/docs/blob/72b4c1657e17701970c22e7eb7ea383f719e3101/cockroachcloud/architecture.md#L77)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

move this to the other page
</blockquote></details>

These also need to be updated to match the latest numbers. See the "Proposed V6" tab in this spreadsheet: https://docs.google.com/spreadsheets/d/1_fm2chL5wp0nJVyyvhhWmX2MJ39U7WzRHxJ72J34OzU/edit#gid=933994728, rows 76-98.
___
*[`cockroachcloud/learn-about-serverless.md` line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/14241#-N59LPnR-a6aHWFjG-5Z:-N59LPnR-a6aHWFjG-5_:b-5rheti) ([raw file](https://github.com/cockroachdb/docs/blob/72b4c1657e17701970c22e7eb7ea383f719e3101/cockroachcloud/learn-about-serverless.md#L13)):*
> ```Markdown
> ## Request Units
> 
> With {{ site.data.products.serverless }}, you are charged for the storage and activity of your cluster. All cluster activity, including SQL queries, bulk operations, and background jobs, is measured in Request Units, or RUs. RUs are an abstracted metric that represent the size and complexity of requests made to your cluster. All database operations cost a certain amount of RUs depending on the resources used. For example, a "small read" might cost 2 RUs, and a "large read" such as a full table scan with indexes might cost 100 RUs.
> ```

I think it's confusing to say a "small read" might cost 2 RUs, since we say below that a small read costs 1 RU. Also a large read with a full table scan and indexes would never cost 100 RUs - it would be way more. Also, indexes make no difference for reads, just for writes.
___
*[`cockroachcloud/learn-about-serverless.md` line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/14241#-N59QgaA1TyYcOOib65E:-N59QgaBBo6zHm31Ijg8:b9kt9g4) ([raw file](https://github.com/cockroachdb/docs/blob/72b4c1657e17701970c22e7eb7ea383f719e3101/cockroachcloud/learn-about-serverless.md#L13)):*
> ```Markdown
> ## Request Units
> 
> With {{ site.data.products.serverless }}, you are charged for the storage and activity of your cluster. All cluster activity, including SQL queries, bulk operations, and background jobs, is measured in Request Units, or RUs. RUs are an abstracted metric that represent the size and complexity of requests made to your cluster. All database operations cost a certain amount of RUs depending on the resources used. For example, a "small read" might cost 2 RUs, and a "large read" such as a full table scan with indexes might cost 100 RUs.
> ```

I thought we were going to get rid of the word "resources" when describing RUs at a high-level, and just stick with the "activity" and "size and complexity of request" language.
___
*[`cockroachcloud/learn-about-serverless.md` line 15 at r1](https://reviewable.io/reviews/cockroachdb/docs/14241#-N55uQoB9oUOdFbkMJhC:-N59JOFC8Lt63aoV_PQX:b4drd05) ([raw file](https://github.com/cockroachdb/docs/blob/72b4c1657e17701970c22e7eb7ea383f719e3101/cockroachcloud/learn-about-serverless.md#L15)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

I would remove these shell examples. I'm finding them to be a bit confusing because of the $1 (does that mean it costs a dollar?) and I don't think they're necessary.
</blockquote></details>

These would be recognizable to any developer who's used Postgres (or most any other database for that matter) - they're query parameters and are in almost every query you'll ever write. However, if the examples aren't needed, we can get rid of them.
___
*[`cockroachcloud/learn-about-serverless.md` line 21 at r1](https://reviewable.io/reviews/cockroachdb/docs/14241#-N59K5pA0E6pHkEOFlos:-N59K5pA0E6pHkEOFlot:b68ivcw) ([raw file](https://github.com/cockroachdb/docs/blob/72b4c1657e17701970c22e7eb7ea383f719e3101/cockroachcloud/learn-about-serverless.md#L21)):*
> ```Markdown
>   ~~~
> 
> Writing a 64 byte row costs approximately7 RUs, which includes the cost of replicating the write 3 times for high availability and durability:
> ```

NIT: need space before 7
___
*[`cockroachcloud/serverless-faqs.md` line 40 at r1](https://reviewable.io/reviews/cockroachdb/docs/14241#-N55qIE5BCF1EhEM-GHk:-N59PBL_CDJNZUSWtwn2:b-s9zafa) ([raw file](https://github.com/cockroachdb/docs/blob/72b4c1657e17701970c22e7eb7ea383f719e3101/cockroachcloud/serverless-faqs.md#L40)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

We should maybe update the "small read" v "large read" example amounts. cc @andy-kimball, do you have any suggestion on what basic example can go here?
</blockquote></details>

The point of updating the model was to get more specific with costs for common operations, but we're not taking advantage of that here. We can now say, "The cost to read a 64 byte row is ~1 RU, plus 1 RU for each additional KiB. The cost to write a 64 byte row is ~7 RU, plus 3 RU for each additional KiB. Every other database operation is similarly assigned a cost based on its size and complexity."


<!-- Sent from Reviewable.io -->

2022-07-11 19:32 UTC, gemma-shay commented
@andy-kimball Yes sorry, not quite ready for another review yet, just had to push an in-progress commit to work on a loaner laptop today.

2022-07-20 17:47 UTC, emily-horing requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14241)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing, @gemma-shay, and @rmloveland)

___
*[`cockroachcloud/learn-about-pricing.md` line 13 at r5](https://reviewable.io/reviews/cockroachdb/docs/14241#-N7He0aP-jvLJC4Aq3Aj:-N7He0aP-jvLJC4Aq3Ak:b-dylrsq) ([raw file](https://github.com/cockroachdb/docs/blob/508ed3c5b2234d78146efea61f411faf3be3469b/cockroachcloud/learn-about-pricing.md#L13)):*
Rereading this again, I think the one piece that isn't quite clear is that a single activity/request can cost > 1 request unit. I'm not sure what the best way to include this is though. Perhaps we can just use what Andy wrote in his doc? 
> With CockroachDB Serverless, you are charged for the storage and activity of your cluster. Cluster storage is measured in GiB per month, based on the total volume of storage used over the billing period. Cluster activity, including SQL queries, bulk operations, and background jobs, is measured in Request Units. A Request Unit, or RU, is an abstracted metric that represents the size and complexity of requests made to your cluster. Request Unit consumption scales to zero when your cluster has no activity, so you will only be charged for what you use.

not totally sure if this solves the issue but i like that we talk about both storage and ru here
___
*[`cockroachcloud/learn-about-pricing.md` line 17 at r5](https://reviewable.io/reviews/cockroachdb/docs/14241#-N7Hg52KDP2XWveQO8GH:-N7Hg52KDP2XWveQO8GI:b-gy0xkh) ([raw file](https://github.com/cockroachdb/docs/blob/508ed3c5b2234d78146efea61f411faf3be3469b/cockroachcloud/learn-about-pricing.md#L17)):*
> ```Markdown
> RU and storage consumption is prorated at the following prices:
> 
>   Activity Measure        | Cost
> ```

I think "activity measure" is not the right title? maybe... "unit"?
___
*[`cockroachcloud/learn-about-pricing.md` line 36 at r5](https://reviewable.io/reviews/cockroachdb/docs/14241#-N7Rd6weC6RyhR_q5ICA:-N7Rd6weC6RyhR_q5ICB:ba361hp) ([raw file](https://github.com/cockroachdb/docs/blob/508ed3c5b2234d78146efea61f411faf3be3469b/cockroachcloud/learn-about-pricing.md#L36)):*
> ```Markdown
> {{ site.data.products.serverless }} clusters scale based on your workload. Baseline performance for a Serverless cluster is 100 RUs per second, and any usage above that is called [burst performance](architecture.html#cockroachdb-cloud-terms). Clusters start with 10M RUs of free burst capacity each month and earn 100 RUs per second up to a maximum of 250M free RUs per month. Earned RUs can be used immediately or accumulated as burst capacity. If you use all of your burst capacity, your cluster will revert to baseline performance.
> 
> You can set your spend limit higher to maintain a high level of performance with larger workloads. If you have set a spend limit, your cluster will not be throttled to baseline performance once you use all of your free earned RUs. Instead, it will continue to use burst performance as needed until you reach your spend limit. You will only be charged for the resources you use up to your spend limit. If you reach your spend limit, your cluster will revert to the baseline performance of 100 RUs per second.
> ```

I think technically this is actually not 100% right but the result is the same so just a nit. You wouldn't ever use up "all" of your free ru because it is still being dripped in at 100/s. So when you hit your limit, technically you are ONLY using your free RU. So really, if you set a spend limit, you get the equivalent # of RU upfront each month as burst in addition to your free burst. When you run out of all the burst capacity, you're left with 100/s free rus, which is a throttled rate.
___
*[`cockroachcloud/learn-about-pricing.md` line 40 at r5](https://reviewable.io/reviews/cockroachdb/docs/14241#-N7ReIFU8FiiDediKvFi:-N7ReIFV5FAucRhrYP7N:biscb9z) ([raw file](https://github.com/cockroachdb/docs/blob/508ed3c5b2234d78146efea61f411faf3be3469b/cockroachcloud/learn-about-pricing.md#L40)):*
> ```Markdown
> The following diagram shows how RUs are accumulated and consumed:
> 
> <img src="{{ 'images/cockroachcloud/ru-diagram.png' | relative_url }}" alt="RU diagram" style="max-width:100%" />
> ```

tbh i don't understand this diagram. We're changing the way this works though so i'm not that fussed about changing it now
___
*[`cockroachcloud/learn-about-request-units.md` line 18 at r6](https://reviewable.io/reviews/cockroachdb/docs/14241#-N7Rek5L9ffsWzOgtXVr:-N7Rek5L9ffsWzOgtXVs:brz14kw) ([raw file](https://github.com/cockroachdb/docs/blob/d7fb2e8591b50bf776bde9b62407aec58826ede5/cockroachcloud/learn-about-request-units.md#L18)):*
> ```Markdown
> ### Pricing
> 
> The examples that follow show the costs of some common queries and how they increase with the size and complexity of the query. Note that the prices listed are estimates and your actual costs may vary slightly.
> ```

nit: let's say that its an estimate in the first sentence. "examples show cost estimates of.."
___
*[`cockroachcloud/optimize-serverless-workload.md` line 49 at r6](https://reviewable.io/reviews/cockroachdb/docs/14241#-N7Rh5Ci0ROeHuc9AaN7:-N7Rh5Ci0ROeHuc9AaN8:b8ihhnw) ([raw file](https://github.com/cockroachdb/docs/blob/d7fb2e8591b50bf776bde9b62407aec58826ede5/cockroachcloud/optimize-serverless-workload.md#L49)):*
> ```Markdown
> - Don't disable automatic statistics, as they are needed to power the [optimizer](../stable/cost-based-optimizer.html).
> 
> ## Example Request Unit calculation
> ```

I don't believe serverless users would have the CPU/egress/io numbers to do this calculation on their own? I would cut this. cc @andy-kimball to confirm 
___
*[`cockroachcloud/serverless-faqs.md` line 42 at r6](https://reviewable.io/reviews/cockroachdb/docs/14241#-N7Rhj0T629fgWIw_LQ3:-N7Rhj0T629fgWIw_LQ4:b2xcac3) ([raw file](https://github.com/cockroachdb/docs/blob/d7fb2e8591b50bf776bde9b62407aec58826ede5/cockroachcloud/serverless-faqs.md#L42)):*
> ```Markdown
> With {{ site.data.products.serverless }}, you are charged for the storage and activity of your cluster. All cluster activity, including SQL queries, bulk operations, and background jobs, is measured in [Request Units](learn-about-request-units.html), or RUs. RUs are an abstracted metric that represent the size and complexity of requests made to your cluster.
> 
> For example, the cost to do a prepared point read (fetching a single row by its key) of a 64 byte row is approximately 1 RU, plus 1 RU for each additional KiB. Writing a 64 byte row costs approximately 7 RUs, which includes the cost of replicating the write 3 times for high availability and durability, plus 3 RUs for each additional KiB. Request Unit consumption scales to zero when your cluster has no activity, so you will only be charged for what you use.
> ```

I think this is better, but let's just keep it a bit shorter: "for example, fetching a single 64 byte row by its key costs about 1 RU, while a write of the same row would cost around 7 RU, including 3 way replication."
something like that.


<!-- Sent from Reviewable.io -->

2022-07-21 16:34 UTC, lnhsingh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14241)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing, @gemma-shay, and @rmloveland)

___
*[`cockroachcloud/learn-about-pricing.md` line 13 at r5](https://reviewable.io/reviews/cockroachdb/docs/14241#-N7He0aP-jvLJC4Aq3Aj:-N7WZfQP9-iWYRPvnws_:bn6av38) ([raw file](https://github.com/cockroachdb/docs/blob/508ed3c5b2234d78146efea61f411faf3be3469b/cockroachcloud/learn-about-pricing.md#L13)):*
What if we add that info in after the RU definition? So something like:

> [...] A Request Unit, or RU, is an abstracted metric that represents the size and complexity of requests made to your cluster. Note that a single activity or request could cost more than 1 Request Unit. Request Unit consumption scales to zero [...]


<!-- Sent from Reviewable.io -->

2022-07-21 17:04 UTC, emily-horing reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14241)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @emily-horing, @gemma-shay, and @lnhsingh)

___
*[`cockroachcloud/learn-about-pricing.md` line 13 at r5](https://reviewable.io/reviews/cockroachdb/docs/14241#-N7He0aP-jvLJC4Aq3Aj:-N7Whtlu7K-5MIMWknPF:b-o7u062) ([raw file](https://github.com/cockroachdb/docs/blob/508ed3c5b2234d78146efea61f411faf3be3469b/cockroachcloud/learn-about-pricing.md#L13)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

What if we add that info in after the RU definition? So something like:

> [...] A Request Unit, or RU, is an abstracted metric that represents the size and complexity of requests made to your cluster. Note that a single activity or request could cost more than 1 Request Unit. Request Unit consumption scales to zero [...]
</blockquote></details>

Yep that would work for me!


<!-- Sent from Reviewable.io -->

2022-07-22 20:26 UTC, emily-horing commented
cc @nathanstilwell if you're still up for it, would love to have some fresh eyes reviewing these!

2022-07-25 16:43 UTC, andy-kimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14241)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @emily-horing, @gemma-shay, and @lnhsingh)

___
*[`cockroachcloud/learn-about-request-units.md` line 24 at r6](https://reviewable.io/reviews/cockroachdb/docs/14241#-N7qDPoo2vQ7WPXCg-7X:-N7qDPoo2vQ7WPXCg-7Y:b-b4gtz5) ([raw file](https://github.com/cockroachdb/docs/blob/d7fb2e8591b50bf776bde9b62407aec58826ede5/cockroachcloud/learn-about-request-units.md#L24)):*
> ```Markdown
>   Query                    | RUs per 1 query    | Price per 1M queries
>   -------------------------|--------------------|----------
>   Read 1 row of 64 bytes   | 1.03               | $0.04
> ```

These prices are not correct. It would be $0.10, $0.20, and $0.30 for each of these three examples, because 10M RU = $1.
___
*[`cockroachcloud/learn-about-request-units.md` line 32 at r6](https://reviewable.io/reviews/cockroachdb/docs/14241#-N7qD_-J9PKkNP20b64K:-N7qD_-J9PKkNP20b64L:b-bal8a6) ([raw file](https://github.com/cockroachdb/docs/blob/d7fb2e8591b50bf776bde9b62407aec58826ede5/cockroachcloud/learn-about-request-units.md#L32)):*
> ```Markdown
>   Query                     | RUs per 1 query    | Price per 1M queries
>   --------------------------|--------------------|----------
>   Write 1 row of 64 bytes   | 6.71               | $0.12
> ```

This should be $0.67, $0.96, $1.26.
___
*[`cockroachcloud/learn-about-request-units.md` line 40 at r6](https://reviewable.io/reviews/cockroachdb/docs/14241#-N7qDjaxCi0XjfKLGAtL:-N7qDjaxCi0XjfKLGAtM:b-x669d3) ([raw file](https://github.com/cockroachdb/docs/blob/d7fb2e8591b50bf776bde9b62407aec58826ede5/cockroachcloud/learn-about-request-units.md#L40)):*
> ```Markdown
>   Query                                     | RUs per 1 query    | Price per 1M queries
>   ------------------------------------------|--------------------|----------
>   Write 1 row of 1024 bytes, with 0 indexes | 9.59               | $0.31
> ```

This should be $.96, $1.87, $2.78.
___
*[`cockroachcloud/learn-about-request-units.md` line 48 at r6](https://reviewable.io/reviews/cockroachdb/docs/14241#-N7qDnin1npuCUTJEK7-:-N7qDnin1npuCUTJEK70:brwnuw4) ([raw file](https://github.com/cockroachdb/docs/blob/d7fb2e8591b50bf776bde9b62407aec58826ede5/cockroachcloud/learn-about-request-units.md#L48)):*
> ```Markdown
>   Query                                 | RUs per 1 query | Price per 1M queries
>   --------------------------------------|-----------------|----------
>   Scan 1K rows of 64 bytes, return 1    | 3.26            | $0.11
> ```

This should be $0.33, $2.24, $19.61.
___
*[`cockroachcloud/learn-about-request-units.md` line 56 at r6](https://reviewable.io/reviews/cockroachdb/docs/14241#-N7qDuHl7XKD1iiZrB11:-N7qDuHl7XKD1iiZrB12:b6mxv3r) ([raw file](https://github.com/cockroachdb/docs/blob/d7fb2e8591b50bf776bde9b62407aec58826ede5/cockroachcloud/learn-about-request-units.md#L56)):*
> ```Markdown
>   Query                    | RUs per 1 query  | Price per 1M queries
>   -------------------------|------------------|----------
>   Establish SQL Connection | 4.36             | $0.22
> ```

This should be $.44.
___
*[`cockroachcloud/optimize-serverless-workload.md` line 49 at r6](https://reviewable.io/reviews/cockroachdb/docs/14241#-N7Rh5Ci0ROeHuc9AaN7:-N7qE5hv2ZDLKB9GKx1D:bq0gvdo) ([raw file](https://github.com/cockroachdb/docs/blob/d7fb2e8591b50bf776bde9b62407aec58826ede5/cockroachcloud/optimize-serverless-workload.md#L49)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

I don't believe serverless users would have the CPU/egress/io numbers to do this calculation on their own? I would cut this. cc @andy-kimball to confirm 
</blockquote></details>

We should be exposing this information as metrics - it will be very important for certain customers.


<!-- Sent from Reviewable.io -->

2022-08-15 19:08 UTC, emily-horing requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14241)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @emily-horing, @gemma-shay, and @lnhsingh)

___
*[`cockroachcloud/learn-about-pricing.md` line 30 at r8](https://reviewable.io/reviews/cockroachdb/docs/14241#-N9XobIBCDCa41A7PFlC:-N9XobIBCDCa41A7PFlD:b6lwn30) ([raw file](https://github.com/cockroachdb/docs/blob/6ee53ade6f33f99e3a9dded4d1cfc259fa2f3b79/cockroachcloud/learn-about-pricing.md#L30)):*
> ```Markdown
> We recommend setting your spend limit to about 30% higher than your expected usage to prevent unexpected throttling. To learn about tuning your workload to reduce costs, see [Optimize Your {{ site.data.products.serverless }} Workload](optimize-serverless-workload.html).
> 
> All [Console Admins](console-access-management.html#console-admin) will receive email alerts when your cluster reaches 75% and 100% of its burst capacity or storage limit. If you set a spend limit, you will also receive alerts at 50%, 75%, and 100% of your spend limit.
> ```

clarify free v paid upfront: "All [Console Admins](console-access-management.html#console-admin) will receive email alerts when a free cluster reaches 75% and 100% of its burst capacity or storage limit. For clusters with a spend limit, you will receive alerts at 50%, 75%, and 100% of your spend limit."
___
*[`cockroachcloud/optimize-serverless-workload.md` line 49 at r6](https://reviewable.io/reviews/cockroachdb/docs/14241#-N7Rh5Ci0ROeHuc9AaN7:-N9Xt8hkB3S-4z-LwtAq:b-4eo4ty) ([raw file](https://github.com/cockroachdb/docs/blob/d7fb2e8591b50bf776bde9b62407aec58826ede5/cockroachcloud/optimize-serverless-workload.md#L49)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

We should be exposing this information as metrics - it will be very important for certain customers.
</blockquote></details>

I think a stronger example for this section would be to show an unoptimized query, the cost, and how you would then optimize that query. As is it doesn't feel that related to the headline goal for this page.
___
*[`cockroachcloud/serverless-faqs.md` line 42 at r6](https://reviewable.io/reviews/cockroachdb/docs/14241#-N7Rhj0T629fgWIw_LQ3:-N9Xtk3s7W0zXeXDueUd:b-hv05ma) ([raw file](https://github.com/cockroachdb/docs/blob/d7fb2e8591b50bf776bde9b62407aec58826ede5/cockroachcloud/serverless-faqs.md#L42)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

I think this is better, but let's just keep it a bit shorter: "for example, fetching a single 64 byte row by its key costs about 1 RU, while a write of the same row would cost around 7 RU, including 3 way replication."
something like that.
</blockquote></details>

Just updating this comment. I think we should just link to the RU docs from here and not go into much specifics in this page.


<!-- Sent from Reviewable.io -->

2022-08-15 23:03 UTC, andy-kimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14241)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @emily-horing, @gemma-shay, and @lnhsingh)

___
*[`cockroachcloud/optimize-serverless-workload.md` line 49 at r6](https://reviewable.io/reviews/cockroachdb/docs/14241#-N7Rh5Ci0ROeHuc9AaN7:-N9Yj8Fa9yhSsNxv4UT-:b1o3vr2) ([raw file](https://github.com/cockroachdb/docs/blob/d7fb2e8591b50bf776bde9b62407aec58826ede5/cockroachcloud/optimize-serverless-workload.md#L49)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

I think a stronger example for this section would be to show an unoptimized query, the cost, and how you would then optimize that query. As is it doesn't feel that related to the headline goal for this page.
</blockquote></details>

I don't think we should be covering query optimization in this section - it's way too deep of a subject. I think the problem may be that this example is included under the "Understanding which queries to optimize" and "Tips for reducing RU usage" sections. This example has nothing to do with those sections. Instead, it's an example for the "Understanding your resource usage" section. I believe that to understand that answer, developers will _need_ an example like this.


<!-- Sent from Reviewable.io -->

2022-08-16 14:50 UTC, gemma-shay commented
@emily-horing @andy-kimball If we move the example, which I think makes sense, we also need to move the **Understanding your resource usage** section for context on the CPU/egress/storage-related calculations. If we want to do that, I am wondering if we should just fit everything on one somewhat large page. I think this screenshot might be hard to see, so this is the order of sections I'm proposing:

# Learn About Request Units
## Request Units
### Pricing
## Workload optimization
### Understanding your resource usage
### Understanding which queries to optimize
### Tips for reducing RU usage
## Example RU calculation
## Learn more

-------------

<img width="1339" alt="Screen Shot 2022-08-16 at 10 47 25 AM" src="https://user-images.githubusercontent.com/75328174/184909398-f1c1bf3c-f0f7-475b-9843-dd9b1adce3a1.png">

Just an idea. LMK what you think.

2022-08-16 16:59 UTC, gemma-shay commented
Sorry, I misread your comment and thought you were requesting that the example be moved to the request units page. Moving it up the page to be under the **Understanding your resource usage** is much simpler, I'll push the changes in a minute.

2022-09-06 20:43 UTC, andy-kimball requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14241)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @emily-horing, @gemma-shay, and @lnhsingh)

___
*[`cockroachcloud/learn-about-pricing.md` line 20 at r9](https://reviewable.io/reviews/cockroachdb/docs/14241#-NBJWwv75yAmbloL-mdi:-NBJWwv75yAmbloL-mdj:b-ui4e3l) ([raw file](https://github.com/cockroachdb/docs/blob/c6abf5c997aa5976e3043771c2c0b1f70f3dd213/cockroachcloud/learn-about-pricing.md#L20)):*
> ```Markdown
>   ------------------------|------
>   10M Request Units       | $1.00
>   1 GiB storage per month | $0.50
> ```

This should be $1 / 1 GiB, since we're holding off on changing the pricing.


<!-- Sent from Reviewable.io -->

2022-09-06 21:04 UTC, andy-kimball approved these changes
LGTM

2022-09-07 15:31 UTC, merged