21.2.13 release notes
cockroachdb/docs pull request #14401
Opened 2022-06-29 16:27 UTC by gemma-shay

https://cockroachlabs.atlassian.net/browse/DOC-1899
For July 5, 2022

2022-06-29 16:27 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/14401)
<!-- Reviewable:end -->

2022-06-29 18:23 UTC, ianjevans requested changes

2022-06-29 18:23 UTC, ianjevans commented on _includes/releases/v21.2/v21.2.13.md
> +- Fixed an issue where [`SHOW BACKUP with privileges`](../v21.2/show-backup.html#show-a-backup-with-privileges) displayed grant statements with incorrect syntax (specifically, without the object type
```suggestion
- Fixed an issue where [`SHOW BACKUP with privileges`](../v21.2/show-backup.html#show-a-backup-with-privileges) output grant statements with incorrect syntax (specifically, without the object type). For example, previously `SHOW BACKUP with privileges` output: `GRANT ALL ON status TO j4;` Now it correctly outputs: `GRANT ALL ON TYPE status TO j4;`. [#82831][#82831]
```

2022-06-29 18:23 UTC, ianjevans commented on _includes/releases/v21.2/v21.2.13.md
> +- Fix an issue with the [`soundex` function](../v21.2/functions-and-operators.html#built-in-functions) where certain unicode inputs could result in crashes, errors, or incorrect outputs. [#83434][#83
```suggestion
- Fixed an issue with the [`soundex` function](../v21.2/functions-and-operators.html#built-in-functions) where certain unicode inputs could result in crashes, errors, or incorrect outputs. [#83434][#83434]
```

2022-06-30 16:01 UTC, gemma-shay commented
thank you for the review Ian!

2022-07-05 15:17 UTC, merged