DOC-1010: Add clarification note of CRDB antipatterns
cockroachdb/docs pull request #14451
Opened 2022-07-05 20:02 UTC by nickvigilante

Fixes DOC-1010

2022-07-05 21:41 UTC, hand-crdb requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14451)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nickvigilante)

___
*[`v22.1/migrate-from-postgres.md` line 24 at r1](https://reviewable.io/reviews/cockroachdb/docs/14451#-N6FGghZ6UPB5N_b3RX8:-N6FGghZ6UPB5N_b3RX9:b-yv2ro3) ([raw file](https://github.com/cockroachdb/docs/blob/16194defd4abfaa739a15df66c0e278ebf56cfc7/v22.1/migrate-from-postgres.md#L24)):*
> ```Markdown
> PostgreSQL and CockroachDB have differences in best practices surrounding [primary keys](primary-key.html) on tables. While it's common to see sequences and auto-incrementing primary keys in PostgreSQL, these features can cause hotspots within your cluster when reading or writing large amounts of data. The preferred approaches for  are using [multi-column primary keys](performance-best-practices-overview.html#use-multi-column-primary-keys) or using the [`UUID`](uuid.html) datatype for primary key columns.
> 
> If you are working with a table that must be indexed on sequential keys, use [hash-sharded indexes](hash-sharded-indexes.html).
> ```

Overall, this new section is great.  Regarding this particular sentence...

Whether or not to use hash-sharded indexes is more complex than that.  Consider rewording to something like:

If you are working with a table that must be indexed on sequential keys, consider using [hash-sharded indexes](hash-sharded-indexes.html).  As part of this, it is a good idea to do performance testing with and without hash-sharded indexes to see which works best for your application.


<!-- Sent from Reviewable.io -->

2022-07-06 15:25 UTC, hand-crdb reviewed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14451)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nickvigilante)



<!-- Sent from Reviewable.io -->

2022-07-07 21:43 UTC, stbof commented on v22.1/migrate-from-postgres.md
> +For further information, see [Unique ID best practices](performance-best-practices-overview.html#unique-id-best-practices) and [3 Basic Rules for Choosing Indexes](https://www.cockroachlabs.com/blog/
```suggestion
For further information, see [Unique ID best practices](performance-best-practices-overview.html#unique-id-best-practices) and [3 Basic Rules for Choosing Indexes](https://www.cockroachlabs.com/blog/how-to-choose-db-index-keys/).
```

2022-07-07 21:44 UTC, stbof commented on v22.1/migrate-from-postgres.md
> +PostgreSQL and CockroachDB have differences in best practices surrounding [primary keys](primary-key.html) on tables. While it's common to see sequences and auto-incrementing primary keys in PostgreS
```suggestion
PostgreSQL and CockroachDB have differences in best practices surrounding [primary keys](primary-key.html) on tables. While it's common to see sequences and auto-incrementing primary keys in PostgreSQL, these features can cause hotspots within your cluster when reading or writing large amounts of data. Cockroach Labs recommends that you use [multi-column primary keys](performance-best-practices-overview.html#use-multi-column-primary-keys) or the [`UUID`](uuid.html) datatype for primary key columns.
```

2022-07-07 21:46 UTC, stbof requested changes
See suggestions.

2022-07-07 21:47 UTC, stbof approved these changes

2022-07-08 14:06 UTC, merged