Add query latency threshold to troubleshooting guide.
cockroachdb/docs pull request #14551
Opened 2022-07-15 17:29 UTC by stbof

DOC-2479

2022-07-15 17:29 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/14551)
<!-- Reviewable:end -->

2022-07-15 19:36 UTC, kevin-v-ngo commented on v22.1/query-behavior-troubleshooting.md
> +High latency SQL statements are displayed on the [Statements](ui-statements-page.html) page of the DB Console. To help you focus on such statements, when you create a [diagnostics bundle](ui-statemen
How about this?

High latency SQL statements can be identified on the Statements page of the DB console. You can collect richer diagnostics of a high latency statement by creating a diagnostics bundle when a statement fingerprint exceeds a certain latency.

2022-07-20 22:07 UTC, taroface requested changes
Just blocking for the formatting typo on DB Console.

2022-07-20 22:07 UTC, taroface commented on v22.1/query-behavior-troubleshooting.md
> +You can identify high latency SQL statements on the [Statements](ui-statements-page.html) page of the DB console. You can collect richer diagnostics of a high latency statement by creating a [diagnos
```suggestion
You can identify high-latency SQL statements on the [Statements](ui-statements-page.html) page of the DB Console. You can collect richer diagnostics of a high-latency statement by creating a [diagnostics bundle](ui-statements-page.html#diagnostics) when a statement fingerprint exceeds a certain latency.
```

2022-07-20 22:22 UTC, taroface approved these changes

2022-07-20 22:29 UTC, merged