DOC-4868 dedicated log export
cockroachdb/docs pull request #14739
Opened 2022-08-08 21:31 UTC by andf-crl

Addresses: DOC-4868

- Preview instructions for Dedicated log export feature to AWS CloudWatch.
- Renames and uses CMEK's private preview include
- Places new instructions under Reference > Logs.

DISCUSSION

- Is this the desired location in the sidebar? Should it appear elsewhere?

[export-logs.md](url)

2022-08-08 21:31 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/14739)
<!-- Reviewable:end -->

2022-08-08 23:58 UTC, andf-crl reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14739)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[`cockroachcloud/export-logs.md` line 84 at r1](https://reviewable.io/reviews/cockroachdb/docs/14739#-N8zpkmB83sLZXPqwktG:-N8zpkmB83sLZXPqwktH:b-y64qho) ([raw file](https://github.com/cockroachdb/docs/blob/e5e929dd7201da7f94c088b1986151982b53b498/cockroachcloud/export-logs.md#L84)):*
> ```Markdown
>     The entry for `Resource` allows for more granular control of log export if desired. You can adjust this value in one or more of the following manners:
> 
>         1. To limit log export from {{ site.data.products.dedicated }} to a specific single AWS region, provide the name of the desired region as the fourth value to the `Resource` entry, for example:
> ```

This was described as 'fiddly' in [David's RFC](https://github.com/cockroachlabs/managed-service/pull/8994/files), how do we feel about it now? Keep? Delete?
___
*[`cockroachcloud/export-logs.md` line 102 at r1](https://reviewable.io/reviews/cockroachdb/docs/14739#-N8zq5Yu41xY0rciMukr:-N8zq5Yu41xY0rciMuks:b-w7groe) ([raw file](https://github.com/cockroachdb/docs/blob/e5e929dd7201da7f94c088b1986151982b53b498/cockroachcloud/export-logs.md#L102)):*
> ```Markdown
>             ~~~
> 
>             If this log group does not exist, this configuration will create it in AWS CloudWatch. If this log group does exist,
> ```

Question: What log group name is created by default with `*` specified here?
___
*[`cockroachcloud/export-logs.md` line 114 at r1](https://reviewable.io/reviews/cockroachdb/docs/14739#-N8zqBIr4dGF3a3R_kJt:-N8zqBIr4dGF3a3R_kJu:b-syue9b) ([raw file](https://github.com/cockroachdb/docs/blob/e5e929dd7201da7f94c088b1986151982b53b498/cockroachcloud/export-logs.md#L114)):*
> ```Markdown
>             ~~~
> 
>             If this log stream does not exist, this configuration will create it in AWS CloudWatch. If this log stream does exist,
> ```

Question: What log stream name is created by default with `*` specified here?
___
*[`cockroachcloud/export-logs.md` line 149 at r1](https://reviewable.io/reviews/cockroachdb/docs/14739#-N8zqMp4DxsyqedkxHlX:-N8zqMp4DxsyqedkxHlY:bn7wmfs) ([raw file](https://github.com/cockroachdb/docs/blob/e5e929dd7201da7f94c088b1986151982b53b498/cockroachcloud/export-logs.md#L149)):*
Is it correct to add:

> If you specified a log group name in step 5b, ensure that you specify the same name here.
___
*[`cockroachcloud/export-logs.md` line 160 at r1](https://reviewable.io/reviews/cockroachdb/docs/14739#-N8zr0LG39YO1IFLujc9:-N8zr0LG39YO1IFLujcA:blj0af6) ([raw file](https://github.com/cockroachdb/docs/blob/e5e929dd7201da7f94c088b1986151982b53b498/cockroachcloud/export-logs.md#L160)):*
> ```Markdown
>     ~~~
> 
>     Once the command returns `ENABLED`, logs will begin appearing in CloudWatch under log group you configured in step 7. Since the configuration is applied to cluster nodes in a rolling fashion, you may see some logs appear even before the `GET` command returns an `ENABLED` status.
> ```

I will update this tomorrow to reflect that we are running `GET` multiple times i.e. the command does not self-refresh returned content. This is not `top`.
___
*[`cockroachcloud/export-logs.md` line 164 at r1](https://reviewable.io/reviews/cockroachdb/docs/14739#-N8zrA028TAFe8GMbP32:-N8zrA028TAFe8GMbP33:b4n9p5q) ([raw file](https://github.com/cockroachdb/docs/blob/e5e929dd7201da7f94c088b1986151982b53b498/cockroachcloud/export-logs.md#L164)):*
> ```Markdown
> ## Monitor the status of a log export configuration
> 
> To check the status of an existing {{ site.data.products.dedicated }} log export configuration, use the following Cluster API command:
> ```

This will also include a likewise mention of a need to refresh-for-the-latest-truth
___
*[`cockroachcloud/export-logs.md` line 197 at r1](https://reviewable.io/reviews/cockroachdb/docs/14739#-N8zrLmU8F6JMHYmCiWS:-N8zrLmU8F6JMHYmCiWT:bkvfkij) ([raw file](https://github.com/cockroachdb/docs/blob/e5e929dd7201da7f94c088b1986151982b53b498/cockroachcloud/export-logs.md#L197)):*
> ```Markdown
> 
> 
> ## Limitations
> ```

This section largely from David's RFC. Is everything here still true?


<!-- Sent from Reviewable.io -->

2022-08-09 19:59 UTC, thtruo requested changes
This first draft looks comprehensive, thank you @andf-crl ! I noted a few nits around making references to "Cloud API" not "Cluster API" and added a suggestion to further explain how one might enable SENSITIVE_ACCESS logs to get exported to CloudWatch

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14739#-:-N93Ay6k2Vwrk6wiR7bq:bx4jbvd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abhinavg6, @andf-crl, and @dhartunian)

___
*[`cockroachcloud/export-logs.md` line 8 at r2](https://reviewable.io/reviews/cockroachdb/docs/14739#-N9382z_8cVqpPZXEeoF:-N9382z_8cVqpPZXEeoG:b4qad2q) ([raw file](https://github.com/cockroachdb/docs/blob/ea887d2e60023338bb22d21678f6b4e020b0cacf/cockroachcloud/export-logs.md#L8)):*
> ```Markdown
> ---
> 
> {{ site.data.products.dedicated }} users can use the [Cluster API](/docs/{{site.versions["stable"]}}/cluster-api.html) to configure log export to [AWS CloudWatch](https://aws.amazon.com/cloudwatch/). Once the export is configured, logs will flow from all nodes in all regions of your {{ site.data.products.dedicated }} cluster to your CloudWatch log sink.
> ```

I believe we should note this as the Cloud API (distinct from the Cluster API) and point this to https://www.cockroachlabs.com/docs/cockroachcloud/cloud-api.html 



_Code quote:_
```Markdown
[Cluster API](/docs/{{site.versions["stable"]}}/cluster-api.html)
```
___
*[`cockroachcloud/export-logs.md` line 35 at r2](https://reviewable.io/reviews/cockroachdb/docs/14739#-N938S-31NKhZOYwiDGY:-N938S-31NKhZOYwiDGZ:b-efj662) ([raw file](https://github.com/cockroachdb/docs/blob/ea887d2e60023338bb22d21678f6b4e020b0cacf/cockroachcloud/export-logs.md#L35)):*
> ```Markdown
> ## Enable log export
> 
> 1. Determine the AWS account ID of your {{ site.data.products.dedicated }} cluster, by issuing the following Cluster API command:
> ```

correction: Cloud API



_Code quote:_
```Markdown
Cluster API command
```
___
*[`cockroachcloud/export-logs.md` line 45 at r2](https://reviewable.io/reviews/cockroachdb/docs/14739#-N938Vma5VJUv7xr7SD9:-N938Vma5VJUv7xr7SDA:b-efj662) ([raw file](https://github.com/cockroachdb/docs/blob/ea887d2e60023338bb22d21678f6b4e020b0cacf/cockroachcloud/export-logs.md#L45)):*
> ```Markdown
>     Where:
>     - The `{cluster_id}` can be found in the URL of the [admin web interface](https://cockroachlabs.cloud/cluster/) for the specific cluster you wish to configure, resembling `f78b7feb-b6cf-4396-9d7f-494982d7d81e`.
>     - The `{api_session_token}` can be generated by [authenticating to your cluster via the Cluster API](/docs/{{site.versions["stable"]}}/cluster-api.html#authentication).
> ```

correction: Cloud API



_Code quote:_
```Markdown
Cluster API
```
___
*[`cockroachcloud/export-logs.md` line 137 at r2](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93AQ469AiIHfRJSIYX:-N93AQ469AiIHfRJSIYY:b-efj662) ([raw file](https://github.com/cockroachdb/docs/blob/ea887d2e60023338bb22d21678f6b4e020b0cacf/cockroachcloud/export-logs.md#L137)):*
> ```Markdown
> 1. Note the [Amazon Resource Name (ARN)](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html) of the `CockroachCloudLogExportRole` role found under **Summary**, which is needed for the next step.
> 
> 1. Issue the following Cluster API command to enable log export for your {{ site.data.products.dedicated }} cluster:
> ```

correction: Cloud API



_Code quote:_
```Markdown
Cluster API
```
___
*[`cockroachcloud/export-logs.md` line 148 at r2](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93AS197e36lEj-A7mb:-N93AS197e36lEj-A7mc:b-efj662) ([raw file](https://github.com/cockroachdb/docs/blob/ea887d2e60023338bb22d21678f6b4e020b0cacf/cockroachcloud/export-logs.md#L148)):*
> ```Markdown
>     Where:
>     - The `{cluster_id}` can be found in the URL of your [admin web interface](https://cockroachlabs.cloud/cluster/) for the specific cluster you wish to configure, resembling `f78b7feb-b6cf-4396-9d7f-494982d7d81e`.
>     - The `{api_session_token}` can be generated by [authenticating to your cluster via the Cluster API](/docs/{{site.versions["stable"]}}/cluster-api.html#authentication).
> ```

correction: Cloud API



_Code quote:_
```Markdown
Cluster API
```
___
*[`cockroachcloud/export-logs.md` line 152 at r2](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93AUErATmvfTO96but:-N93AUErATmvfTO96buu:b-efj662) ([raw file](https://github.com/cockroachdb/docs/blob/ea887d2e60023338bb22d21678f6b4e020b0cacf/cockroachcloud/export-logs.md#L152)):*
> ```Markdown
>     - `{role_arn}` is the ARN for the `CockroachCloudLogExportRole` role you copied in step 7.
> 
> 1. Depending on the size of your cluster and how many regions it spans, the configuration may take a moment. You can monitor the ongoing status of the configuration using the following Cluster API command:
> ```

correction: Cloud API



_Code quote:_
```Markdown
Cluster API
```
___
*[`cockroachcloud/export-logs.md` line 164 at r2](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93AWUk8sL_RotnMx9L:-N93AWUk8sL_RotnMx9M:b-efj662) ([raw file](https://github.com/cockroachdb/docs/blob/ea887d2e60023338bb22d21678f6b4e020b0cacf/cockroachcloud/export-logs.md#L164)):*
> ```Markdown
> ## Monitor the status of a log export configuration
> 
> To check the status of an existing {{ site.data.products.dedicated }} log export configuration, use the following Cluster API command:
> ```

correction: Cloud API



_Code quote:_
```Markdown
Cluster API
```
___
*[`cockroachcloud/export-logs.md` line 175 at r2](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93AYq94KqiLYD2pVeV:-N93AYq94KqiLYD2pVeW:b-efj662) ([raw file](https://github.com/cockroachdb/docs/blob/ea887d2e60023338bb22d21678f6b4e020b0cacf/cockroachcloud/export-logs.md#L175)):*
> ```Markdown
> 
> - The `{cluster_id}` can be found in the URL of your [admin web interface](https://cockroachlabs.cloud/cluster/) for the specific cluster you wish to configure, resembling `f78b7feb-b6cf-4396-9d7f-494982d7d81e`.
> - The `{api_session_token}` can be generated by [authenticating to your cluster via the Cluster API](/docs/{{site.versions["stable"]}}/cluster-api.html#authentication).
> ```

correction: Cloud API



_Code quote:_
```Markdown
Cluster API
```
___
*[`cockroachcloud/export-logs.md` line 179 at r2](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93A_bm59fAJ1lRvVh5:-N93A_bm59fAJ1lRvVh6:b-efj662) ([raw file](https://github.com/cockroachdb/docs/blob/ea887d2e60023338bb22d21678f6b4e020b0cacf/cockroachcloud/export-logs.md#L179)):*
> ```Markdown
> ## Update an existing log export configuration
> 
> To update an existing {{ site.data.products.dedicated }} log export configuration, make any necessary changes to your AWS CloudWatch configuration, then issue the same `POST` Cluster API command as shown in step 8 of the [Enable log export](#enable-log-export) instructions with the desired updated configuration. Follow the [Monitor the status of a log export configuration](#monitor-the-status-of-a-log-export-configuration) instructions to ensure the update completes successfully.
> ```

correction: Cloud API



_Code quote:_
```Markdown
Cluster API
```
___
*[`cockroachcloud/export-logs.md` line 183 at r2](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93AbTX4RVBhsjp_bnw:-N93AbTX4RVBhsjp_bnx:b-efj662) ([raw file](https://github.com/cockroachdb/docs/blob/ea887d2e60023338bb22d21678f6b4e020b0cacf/cockroachcloud/export-logs.md#L183)):*
> ```Markdown
> ## Disable log export
> 
> To disable an existing {{ site.data.products.dedicated }} log export configuration, and stop sending logs to your AWS CloudWatch log sink, use the following Cluster API command:
> ```

correction: Cloud API



_Code quote:_
```Markdown
Cluster API
```
___
*[`cockroachcloud/export-logs.md` line 194 at r2](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93Adp657Oe70ZOywaW:-N93Adp657Oe70ZOywaX:b-efj662) ([r [...]

2022-08-09 22:28 UTC, andf-crl commented
TYFR Tommy, updated per your comments.

2022-08-09 22:53 UTC, andf-crl reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14739)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abhinavg6, @andf-crl, @dhartunian, and @thtruo)

___
*[`cockroachcloud/export-logs.md` line 160 at r1](https://reviewable.io/reviews/cockroachdb/docs/14739#-N8zr0LG39YO1IFLujc9:-N93n4DN7Sdh9LvUReEO:b-bw8e1h) ([raw file](https://github.com/cockroachdb/docs/blob/e5e929dd7201da7f94c088b1986151982b53b498/cockroachcloud/export-logs.md#L160)):*
<details><summary><i>Previously, andf-crl wrote…</i></summary><blockquote>

I will update this tomorrow to reflect that we are running `GET` multiple times i.e. the command does not self-refresh returned content. This is not `top`.
</blockquote></details>

Updated!
___
*[`cockroachcloud/export-logs.md` line 202 at r2](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93AhxM3Atg7J3ojqzd:-N93o2np9XMfHntkYJ2J:bzid1ru) ([raw file](https://github.com/cockroachdb/docs/blob/ea887d2e60023338bb22d21678f6b4e020b0cacf/cockroachcloud/export-logs.md#L202)):*
<details><summary><i>Previously, thtruo (Tommy) wrote…</i></summary><blockquote>

Suggestion: it might be worth calling out that this log channel requires an additional step by the user. They'd need to explicitly enable audit logging with `ALTER TABLE...WITH EXPERIMENTAL_AUDIT` according to https://deploy-preview-14739--cockroachdb-docs.netlify.app/docs/v22.1/experimental-audit
</blockquote></details>

Thanks Tommy, I've added this in.


<!-- Sent from Reviewable.io -->

2022-08-09 23:04 UTC, dhartunian requested changes
Sorry for delay here, just went through with comments. Thank you for writing this up @andf-crl.

> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14739#-:-N93qVWp8W40G3-PXRU2:b-2l3ub3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abhinavg6, @andf-crl, and @thtruo)

___
*[`cockroachcloud/export-logs.md` line 84 at r1](https://reviewable.io/reviews/cockroachdb/docs/14739#-N8zpkmB83sLZXPqwktG:-N93otgp92AG4u71inSM:b-1z8lh5) ([raw file](https://github.com/cockroachdb/docs/blob/e5e929dd7201da7f94c088b1986151982b53b498/cockroachcloud/export-logs.md#L84)):*
<details><summary><i>Previously, andf-crl wrote…</i></summary><blockquote>

This was described as 'fiddly' in [David's RFC](https://github.com/cockroachlabs/managed-service/pull/8994/files), how do we feel about it now? Keep? Delete?
</blockquote></details>

I think this is fine to keep as it's not "wrong". If they do sincerely want to limit logs to a region they can. If they limit it to a region that they don't have a cluster in, or to a region that only partially covers a cluster's nodes they will have missing logs.
___
*[`cockroachcloud/export-logs.md` line 102 at r1](https://reviewable.io/reviews/cockroachdb/docs/14739#-N8zq5Yu41xY0rciMukr:-N93oivE6Wwi5ifNB2Y4:b-4vcmia) ([raw file](https://github.com/cockroachdb/docs/blob/e5e929dd7201da7f94c088b1986151982b53b498/cockroachcloud/export-logs.md#L102)):*
<details><summary><i>Previously, andf-crl wrote…</i></summary><blockquote>

Question: What log group name is created by default with `*` specified here?
</blockquote></details>

The group created here will use the `log_name` parameter they provide to the CC API when enabling log export. There is no other option at this point.
___
*[`cockroachcloud/export-logs.md` line 114 at r1](https://reviewable.io/reviews/cockroachdb/docs/14739#-N8zqBIr4dGF3a3R_kJt:-N93oaLUAK9yDiPhTuJr:b-skyd6x) ([raw file](https://github.com/cockroachdb/docs/blob/e5e929dd7201da7f94c088b1986151982b53b498/cockroachcloud/export-logs.md#L114)):*
<details><summary><i>Previously, andf-crl wrote…</i></summary><blockquote>

Question: What log stream name is created by default with `*` specified here?
</blockquote></details>

This should be removed as many log streams can be created here that correspond to different node IDs and logging channels. If we added new logging channels in the future it they should flow through to customers automatically.
___
*[`cockroachcloud/export-logs.md` line 149 at r1](https://reviewable.io/reviews/cockroachdb/docs/14739#-N8zqMp4DxsyqedkxHlX:-N93peYZ6UCqO0yGE9sU:bab3ph) ([raw file](https://github.com/cockroachdb/docs/blob/e5e929dd7201da7f94c088b1986151982b53b498/cockroachcloud/export-logs.md#L149)):*
yes you should add that.

> If `*`, a log group will be created automatically on enablement.

this is not currently a supported feature so it should be omitted. the customer *must* provide a value here.
___
*[`cockroachcloud/export-logs.md` line 197 at r1](https://reviewable.io/reviews/cockroachdb/docs/14739#-N8zrLmU8F6JMHYmCiWS:-N93qBxC3KR2gCdThx6b:bu70nup) ([raw file](https://github.com/cockroachdb/docs/blob/e5e929dd7201da7f94c088b1986151982b53b498/cockroachcloud/export-logs.md#L197)):*
<details><summary><i>Previously, andf-crl wrote…</i></summary><blockquote>

This section largely from David's RFC. Is everything here still true?
</blockquote></details>

ack. yes it's all still true. we'll make redaction a configuration flag in the near future but for now you can't enable it.
___
*[`cockroachcloud/export-logs.md` line 12 at r3](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93m5xA5sPIni9VrCVh:-N93m5xA5sPIni9VrCVi:bfo9ujt) ([raw file](https://github.com/cockroachdb/docs/blob/350299a6a6d7304d7a3692c6d21e1014147c1ae5/cockroachcloud/export-logs.md#L12)):*
> ```Markdown
> {% include cockroachcloud/private-preview.md %}
> 
> Currently, the {{ site.data.products.dedicated }} log export feature is limited to AWS CloudWatch only, but additional cloud log sinks are planned for the future.
> ```

maybe i missed it but we should clarify that you can only configure an AWS cluster to export to AWS Cloudwatch. Exporting from a dedicated cluster hosted in GCP won't work.
___
*[`cockroachcloud/export-logs.md` line 40 at r3](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93mNPs-13XxMwBm7IL:-N93mNPs-13XxMwBm7IM:b-umv5dl) ([raw file](https://github.com/cockroachdb/docs/blob/350299a6a6d7304d7a3692c6d21e1014147c1ae5/cockroachcloud/export-logs.md#L40)):*
> ```Markdown
>     ~~~shell
>     curl -H GET https://cockroachlabs.cloud/api/v1/clusters/{cluster_id}/  \
>       Authorization: Bearer {secret_key}
> ```

This should be:
```
curl -X GET https://cockroachlabs.cloud/api/v1/clusters/{cluster_id} --header "Authorization:Bearer {secret key}"
```

(in particular the trailing `/` after the ID will make the request fail, it must be omitted)
___
*[`cockroachcloud/export-logs.md` line 44 at r3](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93nDlvCUQmVo8ss0W2:-N93nDlvCUQmVo8ss0W3:bbryhio) ([raw file](https://github.com/cockroachdb/docs/blob/350299a6a6d7304d7a3692c6d21e1014147c1ae5/cockroachcloud/export-logs.md#L44)):*
> ```Markdown
> 
>     Where:
>     - The `{cluster_id}` can be found in the URL of the [Cloud Console](https://cockroachlabs.cloud/clusters/) for the specific cluster you wish to configure, resembling `f78b7feb-b6cf-4396-9d7f-494982d7d81e`.
> ```

Customers can also be directed to the Actions -> Get Support option on the cluster page, which will show the cluster ID to them directly.

![Screen Shot 2022-08-09 at 6.50.12 PM.png](https://files.reviewableusercontent.io/images/reviewable/986307/N-LYdp0sdcd--D9ym48Y3fJ5/Screen%20Shot%202022-08-09%20at%206.50.12%20PM.png)

![Screen Shot 2022-08-09 at 6.49.54 PM.png](https://files.reviewableusercontent.io/images/reviewable/986307/0GPqzcxffwFbVAqG0Ncp8DXF/Screen%20Shot%202022-08-09%20at%206.49.54%20PM.png)
___
*[`cockroachcloud/export-logs.md` line 55 at r3](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93ncKgDS5F9RSFt6tr:-N93ncKgDS5F9RSFt6ts:b-w13hiu) ([raw file](https://github.com/cockroachdb/docs/blob/350299a6a6d7304d7a3692c6d21e1014147c1ae5/cockroachcloud/export-logs.md#L55)):*
> ```Markdown
> 1. Select the new role, and create a new policy for this role. These instructions will use the policy name `CockroachCloudLogExportPolicy`.
> 
> 1. Select the new policy, and paste the following into the **Permissions** tab, with the **{} JSON** option selected, providing your own `{aws_acct_id}` as returned from step 1:
> ```

this is incorrect. The AWS account ID must match the target account where the role is being created, **not** the cluster. 

Customers can see this on the right hand side of the IAM page in the web console on AWS.
![Screen Shot 2022-08-09 at 6.53.32 PM.png](https://files.reviewableusercontent.io/images/reviewable/986307/Km_LZOACjXTZ8Rtg5TfxLSmR/Screen%20Shot%202022-08-09%20at%206.53.32%20PM.png)
___
*[`cockroachcloud/export-logs.md` line 105 at r3](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93oN5s3Xij6a30qLsO:-N93oN5tE3KwASNQuiC1:bdee2ak) ([raw file](https://github.com/cockroachdb/docs/blob/350299a6a6d7304d7a3692c6d21e1014147c1ae5/cockroachcloud/export-logs.md#L105)):*
> ```Markdown
>           you may optionally remove the `"logs:CreateLogGroup"` entry from the policy permissions configuration to further restrict permissions given to the `CockroachCloudLogExportRole` role.
> 
>       1. To export {{ site.data.products.dedicated }} logs to a specific AWS CloudWatch [log stream](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/iam-access-control-overview-cwl.html#CWL_ARN_Format), provide the name of the desired log stream as the eighth value to the `Resource` entry, for example:
> ```

I think this should be removed as it's not really a supported feature. One *could* guess ahead of time what the stream naming convention would be but that's subject to chang [...]

2022-08-09 23:05 UTC, thtruo requested changes
Nice @andf-crl thanks for the new iteration! 

I'll suggest a few more nits given some of my recent acceptance testing experience, mostly around the curl request code snippets to help aid the reader with a quicker copy/paste flow. 

I also think there's a correction to be made for step 6's reference to `{aws_acct_id}` 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14739#-:-N93k6-CCIJ7_ZW3DnFo:b-e5kg9m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abhinavg6, @andf-crl, and @thtruo)

___
*[`cockroachcloud/export-logs.md` line 41 at r3](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93kl140tqPR0ixYYoS:-N93kl140tqPR0ixYYoT:b-46hvbh) ([raw file](https://github.com/cockroachdb/docs/blob/350299a6a6d7304d7a3692c6d21e1014147c1ae5/cockroachcloud/export-logs.md#L41)):*
> ```Markdown
>     curl -H GET https://cockroachlabs.cloud/api/v1/clusters/{cluster_id}/  \
>       Authorization: Bearer {secret_key}
>     ~~~
> ```

Could we include the --url and --header flags, like:
    ~~~shell
    curl -H GET --url https://cockroachlabs.cloud/api/v1/clusters/{cluster_id}/  \
      --header "Authorization: Bearer {secret_key}"
    ~~~



_Code quote:_
```Markdown
    ~~~shell
    curl -H GET https://cockroachlabs.cloud/api/v1/clusters/{cluster_id}/  \
      Authorization: Bearer {secret_key}
    ~~~
```
___
*[`cockroachcloud/export-logs.md` line 47 at r3](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93nlh44tC8a8OyG4DS:-N93nlh44tC8a8OyG4DT:bo5p3v1) ([raw file](https://github.com/cockroachdb/docs/blob/350299a6a6d7304d7a3692c6d21e1014147c1ae5/cockroachcloud/export-logs.md#L47)):*
> ```Markdown
>     - The `{secret_key}` can be generated from the {{ site.data.products.dedicated }}Console. See [API Access](console-access-management.html) for instructions.
> 
>     The command returns diagnostic and status information, including an `account_id` field, which contains the AWS Account ID for your {{ site.data.products.dedicated }} cluster. Note this account ID for later use in this procedure.
> ```

I think we need to clarify and disambiguate between the `account_id` and `{aws_account_id}`. 
* The `account_id` should be applied to the "trust relationships" trust policy for the IAM role in step 6. But currently step 6 incorrectly references the `{aws_acct_id}` (I fell into this trap in my acceptance testing path which prevented log export from working. I had used `{aws_acct_id}` when it should be `account_id`)
* Whereas the `{aws_acct_id}` (correctly mentioned in step 5) should perhaps get an explicit sentence describing where to the reader that this is their AWS Console's Account ID (again, different from `account_id` that comes from `GET` `/api/v1/clusters/{cluster_id}`



_Code quote:_
```Markdown
Note this account ID for later use in this procedure.
```
___
*[`cockroachcloud/export-logs.md` line 144 at r3](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93mJyOD2ik5x-ui19S:-N93mJyOD2ik5x-ui19T:b-rx0m04) ([raw file](https://github.com/cockroachdb/docs/blob/350299a6a6d7304d7a3692c6d21e1014147c1ae5/cockroachcloud/export-logs.md#L144)):*
> ```Markdown
>       Authorization: Bearer {secret_key} \
>       {"type": "AWS_CLOUDWATCH", "log_name": "{aws_log_group}", "auth_principal": "{role_arn}"}
>     ~~~
> ```

Nit: could we include --url, --header, and --data flags, like:
    ~~~shell
    curl -H POST --url https://cockroachlabs.cloud/api/v1/clusters/{cluster_id}/logexport \
      --header Authorization: Bearer {secret_key} \
      --data '{"type": "AWS_CLOUDWATCH", "log_name": "{aws_log_group}", "auth_principal": "{role_arn}"}'
    ~~~



_Code quote:_
```Markdown
    ~~~shell
    curl -H POST https://cockroachlabs.cloud/api/v1/clusters/{cluster_id}/logexport \
      Authorization: Bearer {secret_key} \
      {"type": "AWS_CLOUDWATCH", "log_name": "{aws_log_group}", "auth_principal": "{role_arn}"}
    ~~~
```
___
*[`cockroachcloud/export-logs.md` line 158 at r3](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93lJ-k48-72JEFP_ZV:-N93lJ-l2KgNEuNTJpD0:boxc1ii) ([raw file](https://github.com/cockroachdb/docs/blob/350299a6a6d7304d7a3692c6d21e1014147c1ae5/cockroachcloud/export-logs.md#L158)):*
> ```Markdown
>     curl -H GET https://cockroachlabs.cloud/api/v1/clusters/{cluster_id}/logexport \
>       Authorization: Bearer {secret_key}
>     ~~~
> ```

Could we include the --url and --header flags? Like:

    ~~~shell
    curl -H GET --url https://cockroachlabs.cloud/api/v1/clusters/{cluster_id}/logexport \
      --header "Authorization: Bearer {secret_key}"
    ~~~



_Code quote:_
```Markdown
    ~~~shell
    curl -H GET https://cockroachlabs.cloud/api/v1/clusters/{cluster_id}/logexport \
      Authorization: Bearer {secret_key}
    ~~~
```
___
*[`cockroachcloud/export-logs.md` line 170 at r3](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93m8NA-2vEC0ved5G5:-N93m8NA-2vEC0ved5G6:b4nboya) ([raw file](https://github.com/cockroachdb/docs/blob/350299a6a6d7304d7a3692c6d21e1014147c1ae5/cockroachcloud/export-logs.md#L170)):*
> ```Markdown
> curl -H GET https://cockroachlabs.cloud/api/v1/clusters/{cluster_id}/logexport \
>   Authorization: Bearer {secret_key}
> ~~~
> ```

similar nit: can we include --url and --header flags here?



_Code quote:_
```Markdown
~~~shell
curl -H GET https://cockroachlabs.cloud/api/v1/clusters/{cluster_id}/logexport \
  Authorization: Bearer {secret_key}
~~~
```
___
*[`cockroachcloud/export-logs.md` line 189 at r3](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93m2hU6kBuqYU1lpWV:-N93m2hU6kBuqYU1lpWW:bikp53a) ([raw file](https://github.com/cockroachdb/docs/blob/350299a6a6d7304d7a3692c6d21e1014147c1ae5/cockroachcloud/export-logs.md#L189)):*
> ```Markdown
> curl -H DELETE https://cockroachlabs.cloud/api/v1/clusters/{cluster_id}/logexport \
>   Authorization: Bearer {secret_key}
> ~~~
> ```

nit: similarly could we include --url and --header flags here?



_Code quote:_
```Markdown
~~~shell
curl -H DELETE https://cockroachlabs.cloud/api/v1/clusters/{cluster_id}/logexport \
  Authorization: Bearer {secret_key}
~~~
```


<!-- Sent from Reviewable.io -->

2022-08-10 03:22 UTC, abhinavg6 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14739)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abhinavg6, @andf-crl, @dhartunian, and @thtruo)

___
*[`cockroachcloud/export-logs.md` line 84 at r1](https://reviewable.io/reviews/cockroachdb/docs/14739#-N8zpkmB83sLZXPqwktG:-N94emSaBEn3KI62hs34:b-l24pcj) ([raw file](https://github.com/cockroachdb/docs/blob/e5e929dd7201da7f94c088b1986151982b53b498/cockroachcloud/export-logs.md#L84)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I think this is fine to keep as it's not "wrong". If they do sincerely want to limit logs to a region they can. If they limit it to a region that they don't have a cluster in, or to a region that only partially covers a cluster's nodes they will have missing logs.
</blockquote></details>

I think we should provide a recommendation rather than vague flexibility in this case. It should be something like "To limit log export from your Dedicated cluster to only the regions configured for that cluster, provide one ARN per region, where the region is the fourth value to the `Resource` entry. E.g. in case of a three-region cluster, there should be three per-region resources to restrict log export."
___
*[`cockroachcloud/export-logs.md` line 102 at r1](https://reviewable.io/reviews/cockroachdb/docs/14739#-N8zq5Yu41xY0rciMukr:-N94fzIXE9lqerMRW0lG:bgqf64w) ([raw file](https://github.com/cockroachdb/docs/blob/e5e929dd7201da7f94c088b1986151982b53b498/cockroachcloud/export-logs.md#L102)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

The group created here will use the `log_name` parameter they provide to the CC API when enabling log export. There is no other option at this point.
</blockquote></details>

I think we should "recommend" that customers pre-create the log group and then specify in the resource ARN to restrict the export. Then the statement below for removing the createloggroup permission could be bundled with that. And we should ask them to note it down, so they could then provide it in the step to invoke the API later.
___
*[`cockroachcloud/export-logs.md` line 114 at r1](https://reviewable.io/reviews/cockroachdb/docs/14739#-N8zqBIr4dGF3a3R_kJt:-N94ghRG6Tb7zyODIvDt:b32v57) ([raw file](https://github.com/cockroachdb/docs/blob/e5e929dd7201da7f94c088b1986151982b53b498/cockroachcloud/export-logs.md#L114)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

This should be removed as many log streams can be created here that correspond to different node IDs and logging channels. If we added new logging channels in the future it they should flow through to customers automatically.
</blockquote></details>

+1
___
*[`cockroachcloud/export-logs.md` line 149 at r1](https://reviewable.io/reviews/cockroachdb/docs/14739#-N8zqMp4DxsyqedkxHlX:-N94iNzE95XSUXKZSkIT:bl7qi5x) ([raw file](https://github.com/cockroachdb/docs/blob/e5e929dd7201da7f94c088b1986151982b53b498/cockroachcloud/export-logs.md#L149)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

yes you should add that.

> If `*`, a log group will be created automatically on enablement.

this is not currently a supported feature so it should be omitted. the customer *must* provide a value here.
</blockquote></details>

Apart from this, added a related comment to the above step where we are providing optionality to restrict resource config in the IAM policy. We should recommend pre-creating the log group, and instead mention us auto-creating the log group as an optional thing if customer doesn't do so.
___
*[`cockroachcloud/export-logs.md` line 45 at r2](https://reviewable.io/reviews/cockroachdb/docs/14739#-N938Vma5VJUv7xr7SD9:-N94dfXZEBihzFEBiGU9:b-uptf4k) ([raw file](https://github.com/cockroachdb/docs/blob/ea887d2e60023338bb22d21678f6b4e020b0cacf/cockroachcloud/export-logs.md#L45)):*
<details><summary><i>Previously, thtruo (Tommy) wrote…</i></summary><blockquote>

correction: Cloud API
</blockquote></details>

I think we should add a prep step before the "Enable log export" header similar to this - https://www.cockroachlabs.com/docs/cockroachcloud/managing-cmek.html#step-1-prepare-your-cockroachdb-dedicated-organization. Creating a API key is part of that, plus enabling the Cloud org for the log export feature would also be part of that.
___
*[`cockroachcloud/export-logs.md` line 179 at r2](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93A_bm59fAJ1lRvVh5:-N94jEsJAMdREuVdeYj5:b3wgqod) ([raw file](https://github.com/cockroachdb/docs/blob/ea887d2e60023338bb22d21678f6b4e020b0cacf/cockroachcloud/export-logs.md#L179)):*
<details><summary><i>Previously, thtruo (Tommy) wrote…</i></summary><blockquote>

correction: Cloud API
</blockquote></details>

@dhartunian - Do we support simple update of the log group name or the AWS IAM role? Just checking for if we want to include the "update" step.
___
*[`cockroachcloud/export-logs.md` line 202 at r2](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93AhxM3Atg7J3ojqzd:-N94jpPY0axx7yEUm3VG:b-s5su1d) ([raw file](https://github.com/cockroachdb/docs/blob/ea887d2e60023338bb22d21678f6b4e020b0cacf/cockroachcloud/export-logs.md#L202)):*
<details><summary><i>Previously, andf-crl wrote…</i></summary><blockquote>

Thanks Tommy, I've added this in.
</blockquote></details>

A meta comment. Rather than listing these as limitations, it would be better if we post them as Q&A, like this - https://www.cockroachlabs.com/docs/cockroachcloud/cmek-faq.html or this - https://www.cockroachlabs.com/docs/cockroachcloud/cloud-sso#cockroachdb-cloud-sso-frequently-asked-questions-faq

Like:
- Is it possible to configure exported logs to be redacted at source? - and then respond that we export those as redactable by default, and would consider providing optionality to redact at source.
- Can we configure multiple log export configurations to send different log channels to different log groups in AWS Cloudwatch? - and then response that it's not supported today.
- For a multi-region cluster, are the logs exported to one Cloudwatch region? - and then respond that every cluster region's logs are exported to the corresponding Cloudwatch region in your account, so make sure that the log group with same name is configured in all those regions and the IAM role is allowed to access all those regional log groups.
- Do you allow configuring SQL audit logs as part of the log export capability? - and then respond that yes it's supported, though one should enable the per-table setting...
___
*[`cockroachcloud/export-logs.md` line 8 at r3](https://reviewable.io/reviews/cockroachdb/docs/14739#-N94bq-30H4DRjlIKHo8:-N94bq-30H4DRjlIKHo9:baykzr9) ([raw file](https://github.com/cockroachdb/docs/blob/350299a6a6d7304d7a3692c6d21e1014147c1ae5/cockroachcloud/export-logs.md#L8)):*
> ```Markdown
> ---
> 
> {{ site.data.products.dedicated }} users can use the [Cloud API](cloud-api.html) to configure log export to [AWS CloudWatch](https://aws.amazon.com/cloudwatch/). Once the export is configured, logs will flow from all nodes in all regions of your {{ site.data.products.dedicated }} cluster to your CloudWatch log sink.
> ```

I think we should mention that this is specifically for AWS clusters. Just want to make sure that GCP customers don't think that they could export to AWS Cloudwatch.
___
*[`cockroachcloud/export-logs.md` line 12 at r3](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93m5xA5sPIni9VrCVh:-N94c1Gu3xeABE_uoSZX:b-nssdxr) ([raw file](https://github.com/cockroachdb/docs/blob/350299a6a6d7304d7a3692c6d21e1014147c1ae5/cockroachcloud/export-logs.md#L12)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

maybe i missed it but we should clarify that you can only configure an AWS cluster to export to AWS Cloudwatch. Exporti [...]

2022-08-10 15:54 UTC, andf-crl reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14739)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abhinavg6, @andf-crl, @dhartunian, and @thtruo)

___
*[`cockroachcloud/export-logs.md` line 84 at r1](https://reviewable.io/reviews/cockroachdb/docs/14739#-N8zpkmB83sLZXPqwktG:-N977GxG2og8EJIdMtsa:b45yheo) ([raw file](https://github.com/cockroachdb/docs/blob/e5e929dd7201da7f94c088b1986151982b53b498/cockroachcloud/export-logs.md#L84)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

I think we should provide a recommendation rather than vague flexibility in this case. It should be something like "To limit log export from your Dedicated cluster to only the regions configured for that cluster, provide one ARN per region, where the region is the fourth value to the `Resource` entry. E.g. in case of a three-region cluster, there should be three per-region resources to restrict log export."
</blockquote></details>

Done: David. Now warning of repercussions of poor region choice. 

Question: Tommy: I don't understand.
___
*[`cockroachcloud/export-logs.md` line 102 at r1](https://reviewable.io/reviews/cockroachdb/docs/14739#-N8zq5Yu41xY0rciMukr:-N977uAm9ilSIXcFEXaY:b-s3kd2b) ([raw file](https://github.com/cockroachdb/docs/blob/e5e929dd7201da7f94c088b1986151982b53b498/cockroachcloud/export-logs.md#L102)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

I think we should "recommend" that customers pre-create the log group and then specify in the resource ARN to restrict the export. Then the statement below for removing the createloggroup permission could be bundled with that. And we should ask them to note it down, so they could then provide it in the step to invoke the API later.
</blockquote></details>

David: Done. Extrapolated from demo video, featuring `*`.

Tommy: Added log group creation step as step 1. Why would anyone need `"logs:CreateLogGroup"` then? Shouldn't we remove it from the template JSON conf?

All: I have removed the copy (in favor of pre-creating, new step 1) but left the `"logs:CreateLogGroup"` `Action`. in the template code.
___
*[`cockroachcloud/export-logs.md` line 114 at r1](https://reviewable.io/reviews/cockroachdb/docs/14739#-N8zqBIr4dGF3a3R_kJt:-N97EsDk7Xtt2eIDtxZ_:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/e5e929dd7201da7f94c088b1986151982b53b498/cockroachcloud/export-logs.md#L114)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`cockroachcloud/export-logs.md` line 149 at r1](https://reviewable.io/reviews/cockroachdb/docs/14739#-N8zqMp4DxsyqedkxHlX:-N97HEAJ-bXg0NRw4TKV:b-9eep2k) ([raw file](https://github.com/cockroachdb/docs/blob/e5e929dd7201da7f94c088b1986151982b53b498/cockroachcloud/export-logs.md#L149)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

Apart from this, added a related comment to the above step where we are providing optionality to restrict resource config in the IAM policy. We should recommend pre-creating the log group, and instead mention us auto-creating the log group as an optional thing if customer doesn't do so.
</blockquote></details>

David: Thanks, this is superseded by simply mandating the reuse of the manually-created log group from step 1. Removed `*` reference.

Abhinav: addressed via other comments.
___
*[`cockroachcloud/export-logs.md` line 197 at r1](https://reviewable.io/reviews/cockroachdb/docs/14739#-N8zrLmU8F6JMHYmCiWS:-N97JSuZ8Z1qStDFwbQS:b-9755fa) ([raw file](https://github.com/cockroachdb/docs/blob/e5e929dd7201da7f94c088b1986151982b53b498/cockroachcloud/export-logs.md#L197)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

ack. yes it's all still true. we'll make redaction a configuration flag in the near future but for now you can't enable it.
</blockquote></details>

Thank you.
___
*[`cockroachcloud/export-logs.md` line 45 at r2](https://reviewable.io/reviews/cockroachdb/docs/14739#-N938Vma5VJUv7xr7SD9:-N976UId6Nw8_KMkfoyN:bf1grzk) ([raw file](https://github.com/cockroachdb/docs/blob/ea887d2e60023338bb22d21678f6b4e020b0cacf/cockroachcloud/export-logs.md#L45)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

I think we should add a prep step before the "Enable log export" header similar to this - https://www.cockroachlabs.com/docs/cockroachcloud/managing-cmek.html#step-1-prepare-your-cockroachdb-dedicated-organization. Creating a API key is part of that, plus enabling the Cloud org for the log export feature would also be part of that.
</blockquote></details>

Earlier replacement adds, indeed.
___
*[`cockroachcloud/export-logs.md` line 202 at r2](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93AhxM3Atg7J3ojqzd:-N97J_pD-73lOEZFis1q:bl0y15) ([raw file](https://github.com/cockroachdb/docs/blob/ea887d2e60023338bb22d21678f6b4e020b0cacf/cockroachcloud/export-logs.md#L202)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

A meta comment. Rather than listing these as limitations, it would be better if we post them as Q&A, like this - https://www.cockroachlabs.com/docs/cockroachcloud/cmek-faq.html or this - https://www.cockroachlabs.com/docs/cockroachcloud/cloud-sso#cockroachdb-cloud-sso-frequently-asked-questions-faq

Like:
- Is it possible to configure exported logs to be redacted at source? - and then respond that we export those as redactable by default, and would consider providing optionality to redact at source.
- Can we configure multiple log export configurations to send different log channels to different log groups in AWS Cloudwatch? - and then response that it's not supported today.
- For a multi-region cluster, are the logs exported to one Cloudwatch region? - and then respond that every cluster region's logs are exported to the corresponding Cloudwatch region in your account, so make sure that the log group with same name is configured in all those regions and the IAM role is allowed to access all those regional log groups.
- Do you allow configuring SQL audit logs as part of the log export capability? - and then respond that yes it's supported, though one should enable the per-table setting...
</blockquote></details>

Let's revisit this next week.
___
*[`cockroachcloud/export-logs.md` line 8 at r3](https://reviewable.io/reviews/cockroachdb/docs/14739#-N94bq-30H4DRjlIKHo8:-N972BojC4H7SQxK6DGa:bhs3kri) ([raw file](https://github.com/cockroachdb/docs/blob/350299a6a6d7304d7a3692c6d21e1014147c1ae5/cockroachcloud/export-logs.md#L8)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

I think we should mention that this is specifically for AWS clusters. Just want to make sure that GCP customers don't think that they could export to AWS Cloudwatch.
</blockquote></details>

Done, noted in two places in the intro.
___
*[`cockroachcloud/export-logs.md` line 12 at r3](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93m5xA5sPIni9VrCVh:-N972FH48Cg3gbWkRjXx:b4g2mci) ([raw file](https://github.com/cockroachdb/docs/blob/350299a6a6d7304d7a3692c6d21e1014147c1ae5/cockroachcloud/export-logs.md#L12)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

+1 - that's comment I left above too. But this statement doesn't have any language for private preview, assuming it will be highlighted. We should indicate that customers should reach out to their Cockroach Labs account team to get it enabled for their CockroachDB Cloud Organization. 

@dhartunian - Is this a normal feature flag which TSE team could enable too? If yes, we could mention to reach out to our support too.
</blockquote></details>

Done, noted in two places in the intro.

PP is the include at [top of page](https://deploy-preview-14739--cockr [...]

2022-08-10 18:00 UTC, thtruo approved these changes
Latest iteration looks good to me @andf-crl - ack that we'll followup in a separate consistency pass to unblock publishing this in time for private preview 
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14739#-:-N97uOyxBFyVw2DSLsb8:b-f8endk)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abhinavg6, @andf-crl, @dhartunian, and @thtruo)



<!-- Sent from Reviewable.io -->

2022-08-10 18:02 UTC, dhartunian reviewed
thx for the quick edits @andf-crl 

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> once we remove the extra "edit trust policy" step.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14739#-:-N97uqe7DNJ0Zi7loxN9:bjo9z80)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @abhinavg6, @andf-crl, @dhartunian, and @thtruo)

___
*[`cockroachcloud/export-logs.md` line 179 at r2](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93A_bm59fAJ1lRvVh5:-N97u5h24jI32ns9GhJB:b-gamxrc) ([raw file](https://github.com/cockroachdb/docs/blob/ea887d2e60023338bb22d21678f6b4e020b0cacf/cockroachcloud/export-logs.md#L179)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

@dhartunian - Do we support simple update of the log group name or the AWS IAM role? Just checking for if we want to include the "update" step.
</blockquote></details>

Yes you can POST again with new configs and they will take. You *cannot* post with partial config fields. They must all be provided again. I think the language we have already in there should cover it.
___
*[`cockroachcloud/export-logs.md` line 12 at r3](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93m5xA5sPIni9VrCVh:-N97Wiup38AddGCAeizY:b-acnqrj) ([raw file](https://github.com/cockroachdb/docs/blob/350299a6a6d7304d7a3692c6d21e1014147c1ae5/cockroachcloud/export-logs.md#L12)):*
> @dhartunian - Is this a normal feature flag which TSE team could enable too? If yes, we could mention to reach out to our support too.

@abhinavg6 yes this is a standard feature flag that can be enabled by anyone with superuser access. 
___
*[`cockroachcloud/export-logs.md` line 44 at r3](https://reviewable.io/reviews/cockroachdb/docs/14739#-N93nDlvCUQmVo8ss0W2:-N97XAmO3jhS_keAnImA:b-6z2vsy) ([raw file](https://github.com/cockroachdb/docs/blob/350299a6a6d7304d7a3692c6d21e1014147c1ae5/cockroachcloud/export-logs.md#L44)):*
<details><summary><i>Previously, andf-crl wrote…</i></summary><blockquote>

Conflicting guidance: match CMEK steps. Possible after-publish enhancement, both locations?
</blockquote></details>

sgtm, thx
___
*[`cockroachcloud/export-logs.md` line 120 at r4](https://reviewable.io/reviews/cockroachdb/docs/14739#-N97tYUJDqG4F49nRzqj:-N97tYUJDqG4F49nRzqk:bel5kem) ([raw file](https://github.com/cockroachdb/docs/blob/c615b0b2b6dde3bbb2ac681cfd9c974f6a25faf1/cockroachcloud/export-logs.md#L120)):*
> ```Markdown
>     Specifying an AWS region that you do not have a cluster in, or a region that only partially covers your cluster's nodes will result in missing logs.
> 
> 1. Select the **Trust relationships** tab then click **Edit trust policy** and add the following trust policy, providing your {{ site.data.products.dedicated }} cluster's AWS account ID as returned from step 4 (**not** your AWS account ID as used in step 7):
> ```

This entire step can be omitted because the language you added in step 5 adds the account as a "Trusted Entity". That creates this entry in the trust relationships automatically.


<!-- Sent from Reviewable.io -->

2022-08-10 19:01 UTC, andf-crl reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14739)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @abhinavg6, @andf-crl, @dhartunian, and @thtruo)

___
*[`cockroachcloud/export-logs.md` line 102 at r1](https://reviewable.io/reviews/cockroachdb/docs/14739#-N8zq5Yu41xY0rciMukr:-N987W2FAs8vJ2NGgcwA:b-fh16h7) ([raw file](https://github.com/cockroachdb/docs/blob/e5e929dd7201da7f94c088b1986151982b53b498/cockroachcloud/export-logs.md#L102)):*
<details><summary><i>Previously, andf-crl wrote…</i></summary><blockquote>

David: Done. Extrapolated from demo video, featuring `*`.

Tommy: Added log group creation step as step 1. Why would anyone need `"logs:CreateLogGroup"` then? Shouldn't we remove it from the template JSON conf?

All: I have removed the copy (in favor of pre-creating, new step 1) but left the `"logs:CreateLogGroup"` `Action`. in the template code.


</blockquote></details>

Tagging this question for follow-up next week.
___
*[`cockroachcloud/export-logs.md` line 120 at r4](https://reviewable.io/reviews/cockroachdb/docs/14739#-N97tYUJDqG4F49nRzqj:-N987Kl5EqUgVxoIcwFk:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c615b0b2b6dde3bbb2ac681cfd9c974f6a25faf1/cockroachcloud/export-logs.md#L120)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

This entire step can be omitted because the language you added in step 5 adds the account as a "Trusted Entity". That creates this entry in the trust relationships automatically.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-10 19:17 UTC, merged

2022-08-10 19:17 UTC, andf-crl commented
TYFRs all.