Add troubleshooting_mode_enabled session variable.
cockroachdb/docs pull request #14759
Opened 2022-08-09 18:22 UTC by stbof

DOC-5147
DOC-5148

2022-08-09 18:22 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/14759)
<!-- Reviewable:end -->

2022-08-09 19:48 UTC, maryliag approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14759#-:-N938jTqDut11URvG5MO:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2022-08-10 14:16 UTC, taroface requested changes
Suggesting an edit for correctness

2022-08-10 14:16 UTC, taroface commented on _includes/v21.2/misc/session-vars.html
> +   <td>When enabled, avoid performing additional work on queries, particularly when the cluster is experiencing issues, unavailability, or failure. This session variable is used to avoid collecting a
I think this is technically more correct:

```suggestion
   <td>When enabled, avoid performing additional work on queries, such as collecting and emitting telemetry data. This session variable is particularly useful when the cluster is experiencing issues, unavailability, or failure.</td>
```

2022-08-10 14:16 UTC, taroface commented on _includes/v22.1/misc/session-vars.md
> +| <a name="troubleshooting_mode_enabled"></a> `troubleshooting_mode_enabled` | When enabled, avoid performing additional work on queries, particularly when the cluster is experiencing issues, unavail
Same suggestion as above

2022-08-10 14:25 UTC, stbof commented on _includes/v22.1/misc/session-vars.md
> +| <a name="troubleshooting_mode_enabled"></a> `troubleshooting_mode_enabled` | When enabled, avoid performing additional work on queries, particularly when the cluster is experiencing issues, unavail
```suggestion
| <a name="troubleshooting_mode_enabled"></a> `troubleshooting_mode_enabled` | When enabled, avoid performing additional work on queries, such as collecting and emitting telemetry data. This session variable is particularly useful when the cluster is experiencing issues, unavailability, or failure. | `off` | Yes | Yes |
```

2022-08-10 16:16 UTC, taroface approved these changes
LGTM

2022-08-10 16:28 UTC, merged