fix side nav, undoing inadvertant changes
cockroachdb/docs pull request #14841
Opened 2022-08-16 17:13 UTC by MichaelTrestman

2022-08-16 17:13 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/14841)
<!-- Reviewable:end -->

2022-08-16 17:25 UTC, stbof requested changes
It looks right. I'll approve after you merge master to pick up the 22.2 docs and propagate this fix to that version.

2022-08-17 18:21 UTC, MichaelTrestman commented
@stbof looks ok now, eh?

2022-08-17 18:30 UTC, stbof commented
> @stbof looks ok now, eh?

Yes. In the future, to request a re-review could you click this double circular arrow? 

<img width="384" alt="Screen Shot 2022-08-17 at 11 28 50 AM" src="https://user-images.githubusercontent.com/20482960/185215926-f6d26904-efae-4b96-9f6d-c421fd292eb8.png">

2022-08-17 20:57 UTC, merged