DOC-5359 log export aws consistency pass
cockroachdb/docs pull request #14881
Opened 2022-08-18 19:02 UTC by andf-crl

Addresses: DOC-5359

- Converts `## Limitations` to FAQ style, following style presented in CMEK docs.
- Updates all `curl` invocations to use the `--request` and `--url` flags to match existing CMEK docs.

Note: not matching external `json` conf file approach in CMEK step 4, see comment to Jira ticket.

[export-logs.md](url)

2022-08-18 19:02 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/14881)
<!-- Reviewable:end -->

2022-08-18 21:38 UTC, thtruo approved these changes
Nice @andf-crl - this latest pass LGTM. I agree with your take that we don't need to match the `json` conf file like in the CMEK docs 

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14881#-:-N9msaHQ4T8fyVkWZnY5:b4sxml1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andf-crl)



<!-- Sent from Reviewable.io -->

2022-08-19 14:41 UTC, andf-crl commented
Thanks Tommy. @abhinavg6 new FAQ items look OK to you?

2022-08-19 19:43 UTC, abhinavg6 requested changes

2022-08-19 19:43 UTC, abhinavg6 commented on cockroachcloud/export-logs.md
> +Logs exported in this fashion retain [`redactable`](/docs/{{site.versions["stable"]}}/configure-logs.html#redact-logs) markers, but are **not** themselves redacted. Do not use this feature with sensi
```suggestion
Logs exported in this fashion retain [`redactable`](/docs/{{site.versions["stable"]}}/configure-logs.html#redact-logs) markers, but are **not** themselves redacted. Based on your needs, you could optionally redact sensitive data in the logs at your end by making use of `redactable` markers, before the logs are consumed by your team.
```

2022-08-19 19:43 UTC, abhinavg6 commented on cockroachcloud/export-logs.md
> +### For a multi-region cluster, are the logs exported to one CloudWatch region?
```suggestion
### For a multi-region cluster, are the logs from all regions exported to one CloudWatch region?
```

2022-08-19 19:43 UTC, abhinavg6 commented on cockroachcloud/export-logs.md
> +Yes, logs for each region in your cluster are exported to the corresponding CloudWatch region configured for your account. Ensure that the target AWS CloudWatch [log group](https://docs.aws.amazon.co
```suggestion
No, logs for each region in your cluster are exported to the corresponding CloudWatch region configured for your account. Ensure that the target AWS CloudWatch [log group] is configured with the same name in all target regions, and that the [IAM role](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html) you are using has permission to access each regional log group.
```

2022-08-19 19:43 UTC, abhinavg6 commented on cockroachcloud/export-logs.md
> +Yes, the [SQL Audit Log](/docs/{{site.versions["stable"]}}/sql-audit-logging.html) is exported via the `SENSITIVE_ACCESS` log channel by default, as long as you have first enabled audit logging on de
```suggestion
Yes, the [SQL Audit Log](/docs/{{site.versions["stable"]}}/sql-audit-logging.html) is exported via the `SENSITIVE_ACCESS` log channel by default, as long as you have previously enabled audit logging on desired tables using the [`ALTER TABLE ...EXPERIMENTAL_AUDIT`](/docs/{{site.versions["stable"]}}/experimental-audit.html) statement.
```

2022-08-19 20:09 UTC, andf-crl commented
TYFR @abhinavg6 , changes made. PTAL.

2022-08-19 23:26 UTC, abhinavg6 approved these changes

2022-08-22 15:40 UTC, andf-crl commented
@MichaelTrestman ready for review! This was the feature we released on a timetable (Aug 10) and skipped copy review. As you have time, I would very much appreciate a review pass on the whole `export-logs.md` page. Thanks so much!

2022-08-25 19:43 UTC, MichaelTrestman commented on cockroachcloud/export-logs.md
> +Logs exported in this fashion retain [`redactable`](/docs/{{site.versions["stable"]}}/configure-logs.html#redact-logs) markers, but are **not** themselves redacted. Based on your needs, you could opt
"at your end" meaning you need to put another proxy application in between CRDB and whatever "team" was going to consume "your logs", in order to do the redaction? that is more non-trivial than this makes it sound, no?
You could do that with Satori I think, maybe link to the Satori integration page if that is correct? In any case I'd suggest fleshing out "at your end" a bit more in a way that is helpful for decision-making/estimating the complexity of what is involved.

2022-08-25 19:46 UTC, MichaelTrestman approved these changes
LGTM, other than (optionally) that spot where I noted clarification could be helpful.

2022-08-25 19:55 UTC, andf-crl commented
@MichaelTrestman thanks so much; I'll clarify!

2022-08-25 20:32 UTC, merged