Serverless cost estimator
cockroachdb/docs pull request #15045
Opened 2022-09-08 18:55 UTC by gemma-shay

Partially closes https://cockroachlabs.atlassian.net/browse/DOC-4836
Related to https://github.com/cockroachdb/docs/pull/13354

Document the serverless usage cost estimator and add a release note. The movr estimation tutorial also uses this tool.

2022-09-08 18:55 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/15045)
<!-- Reviewable:end -->

2022-09-12 14:11 UTC, emily-horing requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/15045)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing and @gemma-shay)

___
*[`cockroachcloud/serverless-cluster-management.md` line 52 at r1](https://reviewable.io/reviews/cockroachdb/docs/15045#-NBm1ShMEVZWLC5U0ki8:-NBm1ShNA_HGTgF6B8w2:bltpdwl) ([raw file](https://github.com/cockroachdb/docs/blob/ecc2c9ea089cd52ea424b7a9de3829e930af42aa/cockroachcloud/serverless-cluster-management.md#L52)):*
> ```Markdown
> 1. Select a time frame in which your workload was active.
> 
>     Your used RUs, used storage, and spend from the selected time frame will be shown along with your monthly cost estimate.
> ```

The free resources are not accounted for in the spend amount. You say it isn't included in the estimate for the month below, but we should note both, maybe just up top here.
___
*[`cockroachcloud/serverless-cluster-management.md` line 54 at r1](https://reviewable.io/reviews/cockroachdb/docs/15045#-NBm0RO_-c9t8hIdWk1X:-NBm0ROa2I9KwqEIjMc5:b6qllap) ([raw file](https://github.com/cockroachdb/docs/blob/ecc2c9ea089cd52ea424b7a9de3829e930af42aa/cockroachcloud/serverless-cluster-management.md#L54)):*
> ```Markdown
>     Your used RUs, used storage, and spend from the selected time frame will be shown along with your monthly cost estimate.
> 
> The monthly cost estimate is calculated using simple extrapolation that assumes your workload during the selected time frame is an accurate representative of your workload over the month. If you haven't been running a workload for at least the length of the selected time frame, your results will likely be inaccurate. It's also important to note that this estimate does not account for the [free resources](learn-about-pricing.html#free-vs-paid-usage) granted to every {{ site.data.products.serverless }} cluster, which you would have to use up before spending anything.
> ```

Nit: "is an accurate _representation_" or "is representative"
Nit: "your results will be inaccurate" - remove "likely"
Nit: "before being charged", since we called it "spend" earlier, it's confusing to now say you won't spend anything.


<!-- Sent from Reviewable.io -->

2022-09-19 19:17 UTC, emily-horing approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/15045#-:-NCMArqCAwDmJcR9SZZx:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @emily-horing)



<!-- Sent from Reviewable.io -->

2022-09-21 18:26 UTC, rmloveland approved these changes
LGTM, had a couple comments about links that are not blockers

2022-09-21 18:26 UTC, rmloveland commented on cockroachcloud/serverless-cluster-management.md
> +    Your used RUs, used storage, and spend from the selected time frame will be shown along with your monthly cost estimate. The spend and cost estimate do not account for the [free resources](learn-
PS maybe for another PR, but the mention of Request Units / RUs in the table on 'Cluster Overview Page > Usage this month' could also link to the above, I think

2022-09-21 21:12 UTC, merged