Not visible indexes.
cockroachdb/docs pull request #15090
Opened 2022-09-13 22:16 UTC by stbof

2022-09-13 22:17 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/15090)
<!-- Reviewable:end -->

2022-09-19 14:22 UTC, chengxiong-ruan approved these changes
Thanks for working on this! lgtm, other than a few nits.
Also would be nice if @cockroachdb/sql-queries folk can take a look at optimizer doc updates.

2022-09-19 14:22 UTC, chengxiong-ruan commented on v22.2/alter-index.md
> +1. Explain the query that filters on revenue. Since there is no index on the `revenue` column, the query performs a full scan.
`1.` -> `2.` ?

2022-09-19 14:22 UTC, chengxiong-ruan commented on v22.2/alter-index.md
> +1. Create the recommended index.
`1.` -> `3.`? and I guess all the following bulletin number should be in a sequence :)

2022-09-19 14:26 UTC, chengxiong-ruan commented on v22.2/alter-index.md
> +1. Explain the query that filters on revenue. Since there is no index on the `revenue` column, the query performs a full scan.
ah, cool, lgtm then, thanks!

2022-09-23 16:01 UTC, rytaft reviewed
Thanks! Just a couple corrections.

> Reviewed 11 of 15 files at r1, 1 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/15090#-:-NCf41EnB7V3SQfEorhC:b-olpe99)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @devadvocado, @mgartner, and @stbof)

___
*[`_includes/v22.2/misc/session-vars.md` line 6 at r3](https://reviewable.io/reviews/cockroachdb/docs/15090#-NCf-io-9ehbgTI4SDok:-NCf-io0-_hwM7fCrWqw:bjrx6qk) ([raw file](https://github.com/cockroachdb/docs/blob/788c6a3265fa4a404ab7fc05269ad5007119cd73/_includes/v22.2/misc/session-vars.md#L6)):*
> ```Markdown
> | <a name="bytea-output"></a> `bytea_output` | The [mode for conversions from `STRING` to `BYTES`](bytes.html#supported-conversions). | hex | Yes | Yes |
> | <a name="client-min-messages"></a> `client_min_messages` | The severity level of notices displayed in the [SQL shell](cockroach-sql.html). Accepted values include `debug5`, `debug4`, `debug3`, `debug2`, `debug1`, `log`, `notice`, `warning`, and `error`. | `notice` | Yes | Yes |
> | <a name="cost-scans-with-default-col-size"></a> `cost_scans_with_default_col_size` | Whether to allow the optimizer to consider column size when costing plans. | `false` | Yes | Yes |
> ```

This is slightly incorrect, since the setting actually controls whether to *disallow* the optimizer from considering column sizes when costing plans. Setting it to true causes the optimizer to use the same size for all columns to compute scan cost.
___
*[`v22.2/cost-based-optimizer.md` line 196 at r3](https://reviewable.io/reviews/cockroachdb/docs/15090#-NCf358H4OK9__PLxirN:-NCf358H4OK9__PLxirO:b-jokupl) ([raw file](https://github.com/cockroachdb/docs/blob/788c6a3265fa4a404ab7fc05269ad5007119cd73/v22.2/cost-based-optimizer.md#L196)):*
> ```Markdown
> ## Control whether the optimizer uses an index
> 
> You can specify whether an [index is visible](alter-index.html#set-an-index-to-be-not-visible) to the cost-based optimizer. If not visible, the index won't be used in queries unless specifically selected with an [index hint](indexes.html#selection). This allows you to create an index and check for corruption without affecting production queries. For an example, see [Set an index to be not visible](alter-index.html#set-an-index-to-be-not-visible).
> ```

"check for corruption" seems like not what we want to say. Perhaps "check for query plan changes"? Or "check for query performance changes"?


<!-- Sent from Reviewable.io -->

2022-09-23 16:25 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/15090#-:-NCf9o924Jvct52cERiG:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @devadvocado, @mgartner, and @stbof)



<!-- Sent from Reviewable.io -->

2022-09-27 21:29 UTC, taroface requested changes
A few nits/suggestions, mostly focused on `alter-index.md`.

2022-09-27 21:29 UTC, taroface commented on v22.2/alter-index.md
> +`[NOT] VISIBLE`| Set whether an index is visible to the [cost-based optimizer](cost-based-optimizer.html#control-whether-the-optimizer-uses-an-index). If not visible, the index won't be used in queri
This row doesn't look like it belongs in this table, which is under a `Subcommands` heading. As you mentioned separately, `NOT VISIBLE` is not a subcommand. Based on our existing conventions, it seems this should either be in a separate `Parameters` table or unlisted (which doesn't seem ideal). I'm not sure what is best in that case.

2022-09-27 21:29 UTC, taroface commented on v22.2/alter-index.md
> +1. Alter the index to be not visible to the optimizer.
```suggestion
1. Alter the index to be not visible to the optimizer, specifying the `NOT VISIBLE` clause.
```

2022-09-27 21:29 UTC, taroface commented on v22.2/create-table.md
> +`opt_index_visible` | An optional annotation that indicates whether the index should be visible to the [cost-based optimizer](cost-based-optimizer.html#control-whether-the-optimizer-uses-an-index). I
You might consider adding a short `CREATE TABLE` example that uses `NOT VISIBLE`. If you feel this is beyond the scope of the linked tickets, I'll handle as part of DOC-4743.

2022-09-27 21:29 UTC, taroface commented on v22.2/create-index.md
> +`opt_index_visible` | An optional annotation that indicates whether the index is visible to the [cost-based optimizer](cost-based-optimizer.html#control-whether-the-optimizer-uses-an-index). If not v
You might consider adding a short `CREATE INDEX` example that uses `NOT VISIBLE`. If you feel this is beyond the scope of the linked tickets, I'll handle as part of DOC-4743.

2022-09-28 22:27 UTC, taroface approved these changes
LGTM! A couple small follow-up comments. I learned a lot from this PR.

2022-09-28 22:27 UTC, taroface commented on v22.2/alter-index.md
> +Use `[NOT] VISIBLE` to set whether an index is visible to the [cost-based optimizer](cost-based-optimizer.html#control-whether-the-optimizer-uses-an-index). If not visible, the index will not be used
I wanted to double-check whether `[NOT] VISIBLE` is a standard way of representing syntax like this, as opposed to "`VISIBLE` and `NOT VISIBLE`". I haven't seen the former used elsewhere in our docs, but may have missed a similar usage.

For example:
```suggestion
Use `VISIBLE` or `NOT VISIBLE` to set whether an index is visible to the [cost-based optimizer](cost-based-optimizer.html#control-whether-the-optimizer-uses-an-index). If `NOT VISIBLE`, the index will not be used in queries unless specifically selected with [index hint](indexes.html#selection). For an example, see [Set an index to be not visible](#set-an-index-to-be-not-visible).
```

2022-09-28 22:27 UTC, taroface commented on v22.2/cost-based-optimizer.md
> +Cockroach Labs recommends that you allow the optimizer to consider column size when costing plans. If you are an advanced user and need to disable using `avg_size` for troubleshooting or performance
Any thoughts on this one? I don't feel strongly, but the current usage feels outdated relative to the majority of our docs.

2022-09-28 22:47 UTC, stbof commented on v22.2/cost-based-optimizer.md
> +Cockroach Labs recommends that you allow the optimizer to consider column size when costing plans. If you are an advanced user and need to disable using `avg_size` for troubleshooting or performance
I don't like "we" but since this https://cockroachlabs.atlassian.net/browse/DOC-2708 is still open, I'll go with your suggestion.

2022-10-03 16:58 UTC, merged