[DOC-5471] Document partion-rate store field
cockroachdb/docs pull request #15665
Opened 2022-11-22 00:22 UTC by mdlinville

[DOC-5471]

## Previews
TBD

## Tests
- [x] Local build
- [x] Linkcheck

2022-11-22 14:22 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/15665)
<!-- Reviewable:end -->

2022-11-22 14:53 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/15665)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mdlinville)

___
*[`v22.2/cockroach-start.md` line 212 at r1](https://reviewable.io/reviews/cockroachdb/docs/15665#-NHUof0z933Nb8rLwspM:-NHUof1-3z7YeWIZg0V-:b-g95831) ([raw file](https://github.com/cockroachdb/docs/blob/de49388ea1155e84b2a86e415435e7b91ab9b55d/v22.2/cockroach-start.md#L212)):*
> ```Markdown
> <a name="store-size"></a> `size` | The maximum size allocated to the node. When this size is reached, CockroachDB attempts to rebalance data to other nodes with available capacity. When no other nodes have available capacity, this limit will be exceeded. Data may also be written to the node faster than the cluster can rebalance it away; as long as capacity is available elsewhere, CockroachDB will gradually rebalance data down to the store limit.<br><br> The `size` can be specified either in a bytes-based unit or as a percentage of hard drive space (notated as a decimal or with `%`), for example: <br><br>`--store=path=/mnt/ssd01,size=10000000000 ----> 10000000000 bytes`<br>`--store=path=/mnt/ssd01,size=20GB ----> 20000000000 bytes`<br>`--store=path=/mnt/ssd01,size=20GiB ----> 21474836480 bytes`<br>`--store=path=/mnt/ssd01,size=0.02TiB ----> 21474836480 bytes`<br>`--store=path=/mnt/ssd01,size=20% ----> 20% of available space`<br>`--store=path=/mnt/ssd01,size=0.2 ----> 20% of available space`<br>`--store=path=/mnt/ssd01,size=.2 ----> 20% of available space`<br><br>**Default:** 100%<br><br>For an in-memory store, the `size` field is required and must be set to the true maximum bytes or percentage of available memory, for example:<br><br>`--store=type=mem,size=20GB`<br>`--store=type=mem,size=90%`<br><br><strong>Note:</strong> If you use the `%` notation, you might need to escape the `%` sign, for instance, while configuring CockroachDB through `systemd` service files. For this reason, it's recommended to use the decimal notation instead.
> <a name="fields-ballast-size"></a> `ballast-size` | Configure the size of the automatically created emergency ballast file. Accepts the same value formats as the [`size` field](#store-size). For more details, see [Automatic ballast files](cluster-setup-troubleshooting.html#automatic-ballast-files).<br><br>To disable automatic ballast file creation, set the value to `0`:<br><br>`--store=path=/mnt/ssd01,ballast-size=0`
> <a name="store-partition-rate"></a> `partition-rate` | A mapping of a store name to a bandwidth limit, expressed in bytes per second. A value of `0` (the default) represents unlimited bandwidth. For example: <br /><br />`--store=partition-rate=disk-name=/mnt/ssd01=200`<br /><br />This value overrides the [`kv.store.admission.provisioned_bandwidth` cluster setting](cluster-settings.html#settings).
> ```

I don't understand the term partition-rate. What I had added was provisioned-rate: see the release note in  https://github.com/cockroachdb/cockroach/pull/86063.
Also the code comment may be helpful:
```
//   - provisioned-rate=disk-name=<disk-name>[:bandwidth=<bandwidth-bytes/s>] The
//     provisioned-rate can be used for admission control for operations on the
//     store. The bandwidth is optional, and if unspecified, a cluster setting
//     (kv.store.admission.provisioned_bandwidth) will be used.
```


<!-- Sent from Reviewable.io -->

2022-11-22 19:17 UTC, mdlinville reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/15665)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`v22.2/cockroach-start.md` line 212 at r1](https://reviewable.io/reviews/cockroachdb/docs/15665#-NHUof0z933Nb8rLwspM:-NHVlUd6AHIJfgtwR5Y3:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/de49388ea1155e84b2a86e415435e7b91ab9b55d/v22.2/cockroach-start.md#L212)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't understand the term partition-rate. What I had added was provisioned-rate: see the release note in  https://github.com/cockroachdb/cockroach/pull/86063.
Also the code comment may be helpful:
```
//   - provisioned-rate=disk-name=<disk-name>[:bandwidth=<bandwidth-bytes/s>] The
//     provisioned-rate can be used for admission control for operations on the
//     store. The bandwidth is optional, and if unspecified, a cluster setting
//     (kv.store.admission.provisioned_bandwidth) will be used.
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-29 18:54 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/15665#-:-NI3jKgu3eg4JB3zRLfb:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mdlinville)



<!-- Sent from Reviewable.io -->

2022-11-30 16:08 UTC, taroface approved these changes
LGTM plus one suggestion

2022-11-30 16:08 UTC, taroface commented on v22.2/cockroach-start.md
> +<a name="store-provisioned-rate"></a> `provisioned-rate` | A mapping of a store name to a bandwidth limit, expressed in bytes per second. This constrains the bandwidth used for [admission control](ad
Suggesting for consistency with the other rows

```suggestion
<a name="store-provisioned-rate"></a> `provisioned-rate` | A mapping of a store name to a bandwidth limit, expressed in bytes per second. This constrains the bandwidth used for [admission control](admission-control.html) for operations on the store. The disk name is separated from the bandwidth value by a colon (`:`). A value of `0` (the default) represents unlimited bandwidth. For example: <br /><br />`--store=provisioned-rate=disk-name=/mnt/ssd01:200`<br /><br />**Default:** 0<br /><br />If the bandwidth value is omited, bandwidth is limited to the value of the  [`kv.store.admission.provisioned_bandwidth` cluster setting](cluster-settings.html#settings). <strong>Modify this setting only in consultation with your <a href="https://support.cockroachlabs.com/hc/en-us">support team</a>.</strong>
```

2022-11-30 20:08 UTC, merged