Cloud January Release Notes
cockroachdb/docs pull request #15911
Opened 2023-01-03 18:31 UTC by gemma-shay

2023-01-04 20:26 UTC, abhinavg6 commented on releases/cloud.md
> +- The [create cluster](../cockroachcloud/cloud-api.html#create-a-new-cluster) request now exposes the `RestrictEgressTraffic` boolean field to allow clusters to be created with a [deny-by-default egr
```suggestion
- The [create cluster](../cockroachcloud/cloud-api.html#create-a-new-cluster) request now exposes the `restrict-egress-traffic` boolean field to allow clusters to be created with a [deny-by-default egress traffic policy](../cockroachcloud/egress-perimeter-controls.html#use-a-deny-by-default-egress-traffic-policy).
```

2023-01-04 20:36 UTC, abhinavg6 requested changes
Requested a change to cloud API create cluster change. Thanks.

2023-01-04 22:14 UTC, thtruo commented on releases/cloud.md
> +- {{ site.data.products.dedicated }} clusters now have access to the [**Metrics** page](../v22.2/ui-custom-chart-debug-page.html#available-metrics).
@gemma-shay we're still gating this behind a feature flag and have not opened it up for all users yet. I recommend we cut this for the Jan release note.

2023-01-09 01:00 UTC, abhinavg6 approved these changes

2023-01-09 21:54 UTC, rmloveland approved these changes
LGTM!

2023-01-10 16:41 UTC, merged