Remove border around code blocks within callouts
cockroachdb/docs pull request #16055
Opened 2023-01-20 21:19 UTC by ianjevans

This PR clarifies the format of connection strings when using SQLAlchemy.

It also includes a change to the CSS so code blocks within callouts don't have a border around them.

Closes DOC-6587.

2023-01-23 16:02 UTC, nickvigilante requested changes
If you're in the office this week, let me know and we can work on this together.

2023-01-23 16:02 UTC, nickvigilante commented on css/bs/bootstrap-grid.css
> +/*
Can you give these files an extension of `.scss` instead and delete the error comments?

2023-02-02 20:24 UTC, gemma-shay commented
I can see in the convo history that you were working on this, but something weird is still going on with the code blocks. 
<img width="847" alt="Screenshot 2023-02-02 at 3 22 56 PM" src="https://user-images.githubusercontent.com/75328174/216441708-9294a814-9861-4820-8a5c-c614da1237fc.png">

2023-02-02 20:27 UTC, ianjevans commented
> I can see in the convo history that you were working on this, but something weird is still going on with the code blocks. <img alt="Screenshot 2023-02-02 at 3 22 56 PM" width="847" src="https://user-images.githubusercontent.com/75328174/216441708-9294a814-9861-4820-8a5c-c614da1237fc.png">

Yes, the CSS change is now in #16174, which ideally we would merge before this PR so I can pull it in.

2023-02-02 20:28 UTC, gemma-shay approved these changes
gotcha, this lgtm!

2023-02-06 17:53 UTC, merged