Dedicated base and advanced tiers
cockroachdb/docs pull request #16068
Opened 2023-01-23 21:51 UTC by gemma-shay

https://cockroachlabs.atlassian.net/browse/DOC-4811

2023-03-20 16:50 UTC, gemma-shay commented
@jramos-crl waiting on https://github.com/cockroachdb/docs/pull/14741 still but ready for preliminary review

2023-03-20 19:45 UTC, jramos-crl requested changes
@gemma-shay Overall looks good but left some comments.

2023-03-20 19:45 UTC, jramos-crl commented on cockroachcloud/cluster-management.md
> +- The cluster's **Plan Type** (Serverless, Dedicated base, or Dedicated advanced)
Dedicated standard* is the name of the tier

2023-03-20 19:45 UTC, jramos-crl commented on cockroachcloud/cluster-management.md
> +- Single Sign-On (SSO) for both your [{{ site.data.products.db }} organization](configure-cloud-org-sso.html) and the [DB Console](../{{site.versions["stable"]}}/sso-db-console.html)
SSO should be at the org level and the cluster level. Is the DB Console the cluster level one or is that a different SSO? I am not sure how we refer to it for the cluster level.

2023-03-20 19:45 UTC, jramos-crl commented on cockroachcloud/create-your-cluster.md
> +1. Select the **Dedicated base** or **Dedicated advanced** plan.
Same as above, this should be Dedicated standard.

2023-03-20 19:45 UTC, jramos-crl commented on cockroachcloud/create-your-cluster.md
> +{{ site.data.products.dedicated }} advanced clusters have access to features required for [PCI compliance](../{{site.versions["stable"]}}/security-reference/security-overview.html) in addition to all
"base features" change to "standard features"

2023-03-20 19:45 UTC, jramos-crl commented on cockroachcloud/plan-your-cluster.md
> +You should choose {{ site.data.products.dedicated }} advanced if your cluster needs access to all features required for [PCI compliance](../{{site.versions["stable"]}}/security-reference/security-ove
"base clusters" change to "standard clusters"

2023-03-20 19:45 UTC, jramos-crl commented on cockroachcloud/production-checklist.md
> +## Configure PCI compliant features (Dedicated advanced)
we should refer to it as "PCI ready features" since we can't ensure PCI compliance.

2023-03-20 19:45 UTC, jramos-crl commented on cockroachcloud/production-checklist.md
> +{{ site.data.products.dedicated }} advanced has access to all features required for PCI compliance. You should configure these settings to make your cluster PCI compliant:
same as above, we should call it "PCI ready" rather than "PCI compliant"

2023-03-20 19:45 UTC, jramos-crl commented on v22.2/choose-a-deployment-option.md
> +Cockroach Labs offers four ways to deploy CockroachDB: three managed services&mdash;{{ site.data.products.serverless }}, {{ site.data.products.dedicated }} base, and {{ site.data.products.dedicated }
"standard" instead of "base"

2023-03-20 19:45 UTC, jramos-crl commented on v22.2/choose-a-deployment-option.md
> +        <li><a id="dedicated-base"></a><b><a href="../cockroachcloud/quickstart-trial-cluster.html">{{ site.data.products.dedicated }} base</a></b>: A fully managed, single tenant CockroachDB deploym
"standard" instead of "base"

2023-03-20 19:45 UTC, jramos-crl commented on v22.2/choose-a-deployment-option.md
> +        <li><b>Advanced security</b>: Access to all features required for PCI compliance, including CMEK and egress rules.</li>
"PCI readiness" instead of "PCI compliance". "Egress Perimeter Controls" instead of "egress rules" for consistency.

2023-03-20 19:45 UTC, jramos-crl commented on v22.2/choose-a-deployment-option.md
> +        <li>Applications that need to be PCI compliant.</li>
This one might be ok to leave as "PCI compliant" since it is talking about the application as a whole.

2023-04-03 19:06 UTC, jramos-crl reviewed
@gemma-shay everything looks good - left one comment re: the fact that advanced clusters are only available for contract customers.

2023-04-03 19:06 UTC, jramos-crl commented on cockroachcloud/quickstart-trial-cluster.md
> +    Free trials do not apply to **Dedicated advanced** clusters.
@gemma-shay this sentence reminded me that advanced clusters aren't available for credit card customers. I don't think we call that out anywhere but perhaps it is worth calling it out here.

2023-04-04 14:52 UTC, jramos-crl approved these changes
LGTM!

2023-04-06 18:59 UTC, ianjevans approved these changes
LGTM, just a small nit.

2023-04-06 18:59 UTC, ianjevans commented on cockroachcloud/plan-your-cluster.md
> +You should choose {{ site.data.products.dedicated }} advanced if your cluster needs access to all features required for [PCI readiness](../{{site.versions["stable"]}}/security-reference/security-over
```suggestion
You should choose {{ site.data.products.dedicated }} advanced if your cluster needs access to all features required for [PCI readiness](../{{site.versions["stable"]}}/security-reference/security-overview.html). {{ site.data.products.dedicated }} advanced clusters have all the features of {{ site.data.products.dedicated }} standard clusters plus these security features.
```

2023-04-06 20:24 UTC, merged