TA 96465
cockroachdb/docs pull request #16191
Opened 2023-02-06 17:36 UTC by gemma-shay

https://cockroachlabs.atlassian.net/browse/DOC-6836

2023-02-06 18:25 UTC, rafiss requested changes
looks good overall, except for one detail!

2023-02-06 18:25 UTC, rafiss commented on advisories/a96465.md
> +affected_versions: v22.2.0-v22.2.4
v22.2.4 contains the fix, so it's not an affected version

2023-02-06 19:31 UTC, rafiss approved these changes
looks good from my end, thank you! i'm not sure if we need to wait until v22.2.4 is published before posting this TA. @abhinavg6 or @dikshant might have a thought.

2023-02-06 19:32 UTC, gemma-shay commented
Yeah, we need to wait so that the build will succeed

2023-02-08 21:07 UTC, rmloveland approved these changes
LGTM

2023-02-14 18:02 UTC, merged