Update CMEK FAQ
cockroachdb/docs pull request #16365
Opened 2023-02-27 18:54 UTC by mdlinville

Update CMEK Faq
- Request: https://cockroachlabs.slack.com/archives/C02Q8MLFFE0/p1677380623240759
- Add two questions
- Update one question
- Reorganization

2023-02-27 19:42 UTC, abhinavg6 requested changes
Requested change to context of one of the questions.

2023-02-27 19:42 UTC, abhinavg6 commented on cockroachcloud/cmek-faq.md
> +## Can we enable CMEK when we add a new region to a cluster?
```suggestion
## Can we enable CMEK for a new region when it's added to a CMEK-enabled cluster?
```

2023-02-27 19:42 UTC, abhinavg6 commented on cockroachcloud/cmek-faq.md
> +Yes, when you add a new CMEK-enabled region to a cluster, you must also enable CMEK on its existing regions if it is not already enabled. Refer to [Activate CMEK for your {{ site.data.products.dedica
```suggestion
Yes, when you add a new region to a CMEK-enabled cluster, you can enable CMEK for that region. Refer to [Add a Region to a CMEK-enabled Cluster](/docs/cockroachcloud/managing-cmek.html#add-a-region-to-a-cmek-enabled-cluster).
```

2023-02-27 23:32 UTC, taroface approved these changes
LGTM. Reformatted an apostrophe.

2023-02-27 23:32 UTC, taroface commented on cockroachcloud/cmek-faq.md
> +{{ site.data.products.dedicated }} does not force encryption of previously-written data but instead relies on normal storage engine churn for desired encryption. That means the new key is used to enc
```suggestion
{{ site.data.products.dedicated }} does not force encryption of previously-written data but instead relies on normal storage engine churn for desired encryption. That means the new key is used to encrypt newly-written data, while previously-written data remains unencrypted unless it's rewritten.
```

2023-02-28 00:01 UTC, abhinavg6 approved these changes

2023-02-28 20:23 UTC, merged