DOC-7211 export metrics|logs no creation date restriction
cockroachdb/docs pull request #16516
Opened 2023-03-17 16:08 UTC by andf-crl

Addresses: DOC-7211

- Removed mentions of create date restriction from both `export-logs.md` and `export-metrics.md`.

Staging

WIP

2023-03-17 18:58 UTC, thtruo approved these changes
Nice @andf-crl this LGTM!

2023-03-21 18:23 UTC, MichaelTrestman approved these changes
lgtm

2023-04-21 20:06 UTC, abarganier requested changes

2023-04-21 20:06 UTC, abarganier commented on cockroachcloud/export-logs.md
> -The {{ site.data.products.dedicated }} log export feature is only available on clusters created after August 11, 2022 (AWS) or September 9, 2022 (GCP).
Note: the limitation was removed for **GCP only**. AWS still has this limitation. We're working on fixing this right now, but until it's merged, deployed, and run, the AWS limitation still exists.

Can we rework this to only remove the GCP bit, leaving the AWS piece?

2023-04-21 20:09 UTC, abarganier commented on cockroachcloud/export-metrics.md
> -Exporting metrics to AWS CloudWatch is only available on {{ site.data.products.dedicated }} clusters which are hosted on AWS, and were created after August 11, 2022. Metrics export to Datadog is supp
Note: the AWS limitation also still exists for metric export.

We're hoping to resolve this soon, but I think we should scope this PR to only removing the text about the GCP limitation, and then follow up with another PR once the AWS limitation is removed.

2023-06-12 15:07 UTC, thtruo commented
Update: this is now complete https://cockroachlabs.atlassian.net/browse/CC-9775 so we can fully remove the mentions of creation date restriction from both `export-logs.md` and `export-metrics.md`.

2023-06-12 16:18 UTC, thtruo commented
One more request: in https://www.cockroachlabs.com/docs/cockroachcloud/export-logs.html we mention that Log Export is in Limited Preview. Now that we removed this creation date limitation for older clusters, we can treat Log Export as a Preview feature. Can we use the same language as in our Metric Export doc https://www.cockroachlabs.com/docs/cockroachcloud/export-metrics.html?

> This feature is in [preview](https://www.cockroachlabs.com/docs/v23.1/cockroachdb-feature-availability). This feature is subject to change. To share feedback and/or issues, contact [Support](https://support.cockroachlabs.com/hc/en-us).

2023-06-14 20:40 UTC, florence-crl commented
I could not merge this PR. After consulting with @lnhsingh, I created and merged #17241.

2023-06-14 20:40 UTC, closed without merging