DOC-7210 metrics export endpoints
cockroachdb/docs pull request #16534
Opened 2023-03-20 16:48 UTC by andf-crl

Addresses: DOC-7210

- Introduced duality of metrics export endpoints: `metricexport/cloudwatch` and `metricexport/datadog`
- Updated `curl` examples per Jenn's super-helpful testing document && Jira comment -- thank you!!

Staging

WIP

2023-03-21 01:04 UTC, jenngeorge requested changes

2023-03-21 01:04 UTC, jenngeorge commented on cockroachcloud/export-metrics.md
>        --data '{"cloudwatch":{"target_region": "{aws_region}", "role_arn": "arn:aws:iam::{role_arn}:role/CockroachCloudMetricsExportRole", "log_group_name": "{log_group_name}"}}'
The "cloudwatch" config is unnested now, so this line can be replaced with `--data '{"target_region": "{aws_region}", "role_arn": "arn:aws:iam::{role_arn}:role/CockroachCloudMetricsExportRole", "log_group_name": "{log_group_name}"}'`

2023-03-21 01:04 UTC, jenngeorge commented on cockroachcloud/export-metrics.md
>        --data '{"datadog":{"site": "{datadog_site}", "api_key": "{datadog_api_key}}"}}'
The "datadog" config is unnested now, so this line can be replaced with `--data '{"site": "{datadog_site}", "api_key": "{datadog_api_key}"}'`

2023-03-21 20:51 UTC, jenngeorge approved these changes
LGTM thank you!

2023-03-21 20:52 UTC, andf-crl commented
Thanks @jenngeorge !

2023-03-23 15:20 UTC, andf-crl commented
CC weekly release with new endpoints is now live. Merging this PR.

2023-03-23 15:20 UTC, merged