DOC-6342 reinstate log flags as aliases
cockroachdb/docs pull request #16619
Opened 2023-03-28 17:02 UTC by andf-crl

Addresses: DOC-6342

- Reinstates 8 deprecated log flags as aliases.
	- Reconciled new descriptions (`pkg/cli/cliflags/flags.go`), with also-new descriptions (`pkg/cli/flags_test.go`), with slightly different `cockroach -h` output from the v23.1.0-alpha.8 binary, with the existing docs copy ([live](https://www.cockroachlabs.com/docs/stable/cockroach-start.html#logging)). Let me know if some of the previous copy is no longer correct in the new reality of cockroach log flag aliases.

Suggested

- Some tweaks to your [PR](https://github.com/cockroachdb/cockroach/pull/93255); just minor consistency fixes:
	- Extra trailing `}` character in descriptions to the following flags in file [`pkg/cli/cliflags/flags.go`](https://github.com/cockroachdb/cockroach/pull/93255/files#diff-db7714cb00e3771c8f364fb2424a85323aaf11f5e90ae8437f9e32bc2f3893da):
		- `--log-file-verbosity`
		- `--redactable-logs`
	- Convert `"` to `` ` `` for `Description` to flag `--log-file-max-size` in file [`pkg/cli/cliflags/flags.go`](https://github.com/cockroachdb/cockroach/pull/93255/files#diff-db7714cb00e3771c8f364fb2424a85323aaf11f5e90ae8437f9e32bc2f3893da).

Staging

- [v23.1/cockroach-start.md](https://deploy-preview-16619--cockroachdb-docs.netlify.app/docs/dev/cockroach-start.html#logging)

2023-04-06 19:19 UTC, knz approved these changes
thank you

2023-04-06 19:24 UTC, andf-crl commented
@knz thanks!

2023-05-25 18:03 UTC, mdlinville commented
Since the DOC issue is assigned to me, let me quickly review this so we can get it merged.

2023-05-25 18:26 UTC, mdlinville requested changes
Here are some small copyedit suggestions. Thanks for the change. By the way, I could not figure out what actually changed in lines 3 and 4 before my suggested edit, even after careful scrutiny.

2023-05-25 18:26 UTC, mdlinville commented on _includes/v23.1/misc/logging-flags.md
> +`--log` |  Configure logging parameters by specifying a YAML payload. For details, see [Configure logs](configure-logs.html#flag). If a YAML configuration is not specified, the [default configuration
```suggestion
`--log` |  Configure logging parameters by specifying a YAML payload. For details, see [Configure logs](configure-logs.html#flag). If a YAML configuration is not specified, the [default configuration](configure-logs.html#default-logging-configuration) is used.<br/><br/>`--log-config-file` can also be used.<br/><br/>**Note:** The logging flags below cannot be combined with `--log`, but can be defined instead in the YAML payload.
```

2023-05-25 18:26 UTC, mdlinville commented on _includes/v23.1/misc/logging-flags.md
> +`--log-config-file` |  Configure logging parameters by specifying a path to a YAML file. For details, see [Configure logs](configure-logs.html#flag). If a YAML configuration is not specified, the [de
```suggestion
`--log-config-file` |  Configure logging parameters by specifying a path to a YAML file. For details, see [Configure logs](configure-logs.html#flag). If a YAML configuration is not specified, the [default configuration](configure-logs.html#default-logging-configuration) is used.<br/><br/>`--log` can also be used.<br/><br/>**Note:** The logging flags below cannot be combined with `--log-config-file`, but can be defined instead in the YAML file.
```

2023-05-25 18:26 UTC, mdlinville commented on _includes/v23.1/misc/logging-flags.md
> +`--log-group-max-size` | An alias for the [`--log`](configure-logs.html#flag) flag, for configuring the maximum logging group (i.e., `cockroach`, `cockroach-sql-audit`, `cockroach-auth`, `cockroach-s
```suggestion
`--log-group-max-size` | An alias for the [`--log`](configure-logs.html#flag) flag, for configuring the maximum size for a logging group (for example, `cockroach`, `cockroach-sql-audit`, `cockroach-auth`, `cockroach-sql-exec`, `cockroach-pebble`), after which the oldest log file is deleted. `--log-group-max-size=XXX` is an alias for `--log='file-defaults: {max-group-size: XXX}'`. Accepts a valid file size, such as `--log-group-max-size=1GiB`.<br/><br/>**Default:** `100MiB`
```

2023-05-25 18:26 UTC, mdlinville commented on _includes/v23.1/misc/logging-flags.md
> +`--log-file-max-size` | An alias for the [`--log`](configure-logs.html#flag) flag, for configuring the maximum size of log files. before a new log file is created. Specifically, `--log-file-max-size=
```suggestion
`--log-file-max-size` | An alias for [`--log`](configure-logs.html#flag), used to specify the maximum size that a log file can grow before a new log file is created. `--log-file-max-size=XXX` is an alias for `--log='file-defaults: {max-file-size: XXX}'`. Accepts a valid file size, such as `--log-file-max-size=2MiB`. **Requires** logging to files.<br/><br/>**Default:** `10MiB`
```

2023-05-25 18:26 UTC, mdlinville commented on _includes/v23.1/misc/logging-flags.md
> +`--log-file-verbosity` | An alias for the [`--log`](configure-logs.html#flag) flag, for configuring log output [severity level](logging.html#logging-levels-severities). Specifically, `--log-file-verb
```suggestion
`--log-file-verbosity` | An alias for [`--log`](configure-logs.html#flag), used to specify the minimum [severity level](logging.html#logging-levels-severities) of messages that are logged. `--log-file-verbosity=XXX` is an alias for `--log='file-defaults: {filter: XXX}'`. When a severity is specified, such as `--log-file-verbosity=WARNING`, log messages that are below the specified severity level are not written to the target log file. **Requires** logging to files.<br/><br/>**Default:** `INFO`
```

2023-05-25 18:26 UTC, mdlinville commented on _includes/v23.1/misc/logging-flags.md
> +`--logtostderr` |  An alias for the [`--log`](configure-logs.html#flag) flag, for configuring log output to the `stderr` sink. Specifically, `--logtostderr=XXX` is an alias for `--log='sinks: {stderr
```suggestion
`--logtostderr` |  An alias for [`--log`](configure-logs.html#flag), to optionally output log messages at or above the configured  [severity level](logging.html#logging-levels-severities) to the `stderr` sink. `--logtostderr=XXX` is an alias for `--log='sinks: {stderr: {filter: XXX}}'`. Accepts a valid [severity level](logging.html#logging-levels-severities). If no value is specified, by default messages related to server commands are logged to `stderr` at `INFO` severity and above, and messages related to client commands are logged to `stderr` at `WARNING` severity and above.<br/><br/>Setting `--logtostderr=NONE` disables logging to `stderr`.<br><br>**Default:** `UNKNOWN`
```

2023-05-25 18:26 UTC, mdlinville commented on _includes/v23.1/misc/logging-flags.md
> +`--no-color` | An alias for the [`--log`](configure-logs.html#flag) flag, for configuring colorization of log output to the `stderr` sink. Specifically, `--no-color=XXX` is an alias for `--log='sinks
```suggestion
`--no-color` | An alias for [`--log`](configure-logs.html#flag) flag, used to control whether log output to the `stderr` sinc is colorized. `--no-color=XXX` is an alias for `--log='sinks: {stderr: {no-color: XXX}}'`. Accepts either `true` or `false`.<br/><br/>When set to `false`, messages logged to `stderr` are colorized based on [severity level](logging.html#logging-levels-severities).<br><br>**Default:** `false`
```

2023-05-25 18:26 UTC, mdlinville commented on _includes/v23.1/misc/logging-flags.md
> +`--redactable-logs` | An alias for the [`--log`](configure-logs.html#flag) flag, for configuring [redaction markers](configure-logs.html#redact-logs) in log messages. Specifically, `--redactable-logs
```suggestion
`--redactable-logs` | An alias for [`--log`](configure-logs.html#flag) flag, used to whether [redaction markers](configure-logs.html#redact-logs) are used in place of secret or sensitive information in log messages. `--redactable-logs=XXX` is an alias for `--log='file-defaults: {redactable: XXX}'`. Accepts `true` or `false`.<br><br>**Default:** `false`
```

2023-05-25 18:26 UTC, mdlinville commented on _includes/v23.1/misc/logging-flags.md
> +`--sql-audit-dir` | An alias for the [`--log`](configure-logs.html#flag) flag, for configuring log output of the `SENSITIVE_ACCESS` [logging channel](logging-overview.html#logging-channels) to the in
```suggestion
`--sql-audit-dir` | An alias for [`--log`](configure-logs.html#flag), used to optionally confine log output of the `SENSITIVE_ACCESS` [logging channel](logging-overview.html#logging-channels) to a separate directory. `--sql-audit-dir=XXX` is an alias for `--log='sinks: {file-groups: {sql-audit: {channels: SENSITIVE_ACCESS, dir: ...}}}'`.<br><br>Enabling `SENSITIVE_ACCESS` logs can negatively impact performance. As a result, we recommend using the `SENSITIVE_ACCESS` channel for security purposes only. For more information, refer to [Security and Audit Monitoring](logging-use-cases.html#security-and-audit-monitoring).
```

2023-05-25 18:29 UTC, mdlinville approved these changes

2023-05-25 20:06 UTC, merged