Rework sidenav / page titles to better match
cockroachdb/docs pull request #17607
Opened 2023-08-03 19:43 UTC by lnhsingh

Closes DOC-8393

2023-08-03 22:05 UTC, nickvigilante requested changes
One blocking change, one optional nit, but overall LGTM! Let me know if you need help with the blocking change.

2023-08-04 13:05 UTC, lnhsingh commented on src/current/_includes/v23.1/sidebar-data/sql.json
> +                "title": "`POINT`",
Done - Thank you!

2023-08-04 13:05 UTC, lnhsingh commented on src/current/_includes/v23.1/sidebar-data/cloud-deployments.json
> +                    "title": "Export Metrics From a Dedicated Cluster",
I think I'll leave this hardcoded for now to make sure the sidenav stays the way we want it to

2023-08-04 13:30 UTC, nickvigilante approved these changes
Beautiful! LGTM!

2023-08-08 17:46 UTC, taroface commented
<img width="171" alt="image" src="https://github.com/cockroachdb/docs/assets/8740013/64f544ef-a739-43af-942f-13fb6e4c60be">

Do we want to make this "Overview" for consistency with the naming/renaming elsewhere?

2023-08-08 17:50 UTC, lnhsingh commented
@taroface - I think the Security-related edits you proposed will be updated with @MichaelTrestman's [PR](https://github.com/cockroachdb/docs/pull/17595)

2023-08-08 18:00 UTC, taroface reviewed
Mostly non-blocking nits/comments except for one slightly inaccurate title and one typo.

2023-08-08 18:01 UTC, taroface commented
<img width="147" alt="image" src="https://github.com/cockroachdb/docs/assets/8740013/431ff433-cfbd-4496-bedd-8080b2275811">

Should "From" be lowercase here?

2023-08-08 19:21 UTC, lnhsingh commented on src/current/v23.1/inverted-indexes.md
> +title: Index JSON and Array Data with Generalized Inverted Indexes
I'll just revert back for now.

2023-08-08 21:44 UTC, merged