self-hosted core in overview table
cockroachdb/docs pull request #17688
Opened 2023-08-17 17:30 UTC by MichaelTrestman

2023-08-17 18:09 UTC, kathancox commented
As discussed in the slack thread, it might be good to prefix Enterprise with "Self-Hosted" here to differentiate. Otherwise LGTM.

2023-08-17 19:36 UTC, abhinavg6 requested changes
Requesting one change, thanks.

2023-08-17 19:36 UTC, abhinavg6 commented on src/current/v23.1/security-reference/security-overview.md
> +### Self-Hosted Core
I think this should remain as-is, as it's about the overall SH offering.

2023-08-18 16:58 UTC, abhinavg6 approved these changes
LGTM

2023-08-18 16:58 UTC, merged