[DOC-8986] New Azure regions
cockroachdb/docs pull request #17971
Opened 2023-10-05 20:38 UTC by mdlinville

[DOC-8986] New Azure regions

2023-10-05 23:05 UTC, ianjevans approved these changes

2023-10-06 15:53 UTC, adwittumuluri requested changes
We didn't add `centralindia` yet, only `southeastasia`. We should have centralindia sometime next week. Is it preferable to send out just one docs update for both of these regions to reduce the overhead of these PRs?

2023-10-06 15:53 UTC, adwittumuluri commented on src/current/_includes/releases/cloud/2023-10-04.md
> +  - Pune (`centralindia`)
We didn't add `centralindia` yet, only `southeastasia`. We should have centralindia sometime next week.

2023-10-06 19:16 UTC, mdlinville commented
> We didn't add `centralindia` yet, only `southeastasia`. We should have centralindia sometime next week. Is it preferable to send out just one docs update for both of these regions to reduce the overhead of these PRs?

Moved to #17974

2023-10-06 19:24 UTC, adwittumuluri approved these changes

2023-10-06 19:31 UTC, merged