[DOC-9753] Document minimum supported vCPU per node for Dedicated on Azure
cockroachdb/docs pull request #18320
Opened 2024-02-23 22:59 UTC by mdlinville

[DOC-9753] Document minimum supported vCPU per node for Dedicated on Azure

2024-02-26 20:50 UTC, adwittumuluri requested changes

2024-02-26 20:50 UTC, adwittumuluri commented on src/current/cockroachcloud/create-your-cluster.md
> +    Clusters deployed in CockroachDB Cloud can be created with a minimum of 2vCPUs per node on AWS and GCP or 4vcPUs per node on Azure (Limited Access).
Azure isn't in limited access; it's been GA-ed. Is that what's meant here and below by "Limited Access"?

2024-02-27 19:38 UTC, mdlinville commented on src/current/cockroachcloud/production-checklist.md
> +CockroachDB Dedicated clusters can be created with a minimum of 2vCPUs per node on AWS and GCP or 4vcPUs per node on Azure (Limited Access).
```suggestion
CockroachDB Dedicated clusters can be created with a minimum of 2vCPUs per node on AWS and GCP or 4vcPUs per node on Azure.
```

2024-02-27 19:38 UTC, mdlinville commented on src/current/v22.2/recommended-production-settings.md
> +    Clusters deployed in CockroachDB Cloud can be created with a minimum of 2vCPUs per node on AWS and GCP or 4vcPUs per node on Azure (Limited Access).
```suggestion
    Clusters deployed in CockroachDB Cloud can be created with a minimum of 2vCPUs per node on AWS and GCP or 4vcPUs per node on Azure.
```

2024-02-27 19:39 UTC, mdlinville commented on src/current/v23.1/recommended-production-settings.md
> +    Clusters deployed in CockroachDB Cloud can be created with a minimum of 2vCPUs per node on AWS and GCP or 4vcPUs per node on Azure (Limited Access).
```suggestion
    Clusters deployed in CockroachDB Cloud can be created with a minimum of 2vCPUs per node on AWS and GCP or 4vcPUs per node on Azure.
```

2024-02-27 20:43 UTC, adwittumuluri approved these changes

2024-02-27 20:44 UTC, adwittumuluri commented
Thanks for the addition!!

2024-02-28 14:45 UTC, kathancox commented on src/current/cockroachcloud/cockroachdb-dedicated-on-azure.md
> +{{ site.data.products.dedicated }} clusters can be created with a minimum of 4vcPUs per node on Azure.
The page is not rendering correctly here because of this trailing end note liquid

2024-02-28 14:45 UTC, kathancox commented on src/current/cockroachcloud/cockroachdb-dedicated-on-azure.md
> +    {{site.data.alerts.end}}
```suggestion
```

2024-02-28 14:50 UTC, kathancox commented on src/current/cockroachcloud/production-checklist.md
> +CockroachDB Dedicated clusters can be created with a minimum of 2vCPUs per node on AWS and GCP or 4vcPUs per node on Azure.
Should we use the product variable for Dedicated?

2024-02-28 16:26 UTC, mdlinville commented on src/current/cockroachcloud/production-checklist.md
> +CockroachDB Dedicated clusters can be created with a minimum of 2vCPUs per node on AWS and GCP or 4vcPUs per node on Azure.
```suggestion
CockroachDB {{ site.data.products.dedicated }} clusters can be created with a minimum of 2vCPUs per node on AWS and GCP or 4vcPUs per node on Azure.
```

2024-02-28 16:26 UTC, mdlinville commented on src/current/v22.2/recommended-production-settings.md
> +    Clusters deployed in CockroachDB Cloud can be created with a minimum of 2vCPUs per node on AWS and GCP or 4vcPUs per node on Azure.
```suggestion
    Clusters deployed in CockroachDB {{ site.data.products.cloud }} can be created with a minimum of 2vCPUs per node on AWS and GCP or 4vcPUs per node on Azure.
```

2024-02-28 16:26 UTC, mdlinville commented on src/current/v23.1/recommended-production-settings.md
> +    Clusters deployed in CockroachDB Cloud can be created with a minimum of 2vCPUs per node on AWS and GCP or 4vcPUs per node on Azure.
```suggestion
    Clusters deployed in CockroachDB {{ site.data.products.cloud }} can be created with a minimum of 2vCPUs per node on AWS and GCP or 4vcPUs per node on Azure.
```

2024-02-28 16:26 UTC, mdlinville commented on src/current/v23.2/recommended-production-settings.md
> +    Clusters deployed in CockroachDB Cloud can be created with a minimum of 2vCPUs per node on AWS and GCP or 4vcPUs per node on Azure.
```suggestion
    Clusters deployed in CockroachDB {{ site.data.products.cloud }} can be created with a minimum of 2vCPUs per node on AWS and GCP or 4vcPUs per node on Azure.
```

2024-02-28 17:03 UTC, mdlinville commented on src/current/cockroachcloud/cockroachdb-dedicated-on-azure.md
> +CockroachDB {{ site.data.products.dedicated }} clusters can be created with a minimum of 4vcPUs per node on Azure.
```suggestion
CockroachDB {{ site.data.products.dedicated }} clusters can be created with a minimum of 4 vcPUs per node on Azure.
```

2024-02-28 17:03 UTC, mdlinville commented on src/current/cockroachcloud/create-your-cluster.md
> +    Clusters deployed in CockroachDB Cloud can be created with a minimum of 2vCPUs per node on AWS and GCP or 4vcPUs per node on Azure.
```suggestion
    Clusters deployed in CockroachDB Cloud can be created with a minimum of 2 vCPUs per node on AWS and GCP or 4 vCPUs per node on Azure.
```

2024-02-28 17:03 UTC, mdlinville commented on src/current/cockroachcloud/production-checklist.md
> +CockroachDB {{ site.data.products.dedicated }} clusters can be created with a minimum of 2vCPUs per node on AWS and GCP or 4vcPUs per node on Azure.
```suggestion
CockroachDB {{ site.data.products.dedicated }} clusters can be created with a minimum of 2 vCPUs per node on AWS and GCP or 4 vCPUs per node on Azure.
```

2024-02-28 17:03 UTC, mdlinville commented on src/current/v22.2/recommended-production-settings.md
> +    Clusters deployed in CockroachDB {{ site.data.products.cloud }} can be created with a minimum of 2vCPUs per node on AWS and GCP or 4vcPUs per node on Azure.
```suggestion
    Clusters deployed in CockroachDB {{ site.data.products.cloud }} can be created with a minimum of 2 vCPUs per node on AWS and GCP or 4 vCPUs per node on Azure.
```

2024-02-28 17:03 UTC, mdlinville commented on src/current/v23.1/recommended-production-settings.md
> +    Clusters deployed in CockroachDB {{ site.data.products.cloud }} can be created with a minimum of 2vCPUs per node on AWS and GCP or 4vcPUs per node on Azure.
```suggestion
    Clusters deployed in CockroachDB {{ site.data.products.cloud }} can be created with a minimum of 2 vCPUs per node on AWS and GCP or 4 vCPUs per node on Azure.
```

2024-02-28 17:03 UTC, mdlinville commented on src/current/v23.2/recommended-production-settings.md
> +    Clusters deployed in CockroachDB {{ site.data.products.cloud }} can be created with a minimum of 2vCPUs per node on AWS and GCP or 4vcPUs per node on Azure.
```suggestion
    Clusters deployed in CockroachDB {{ site.data.products.cloud }} can be created with a minimum of 2 vCPUs per node on AWS and GCP or 4 vCPUs per node on Azure.
```

2024-02-28 17:07 UTC, merged