[DOC-9694] Document JWT autofetching of signing keys
cockroachdb/docs pull request #18367
Opened 2024-03-11 22:46 UTC by mdlinville

[DOC-9694] Document JWT autofetching of signing keys

2024-03-15 00:19 UTC, BabuSrithar requested changes

2024-03-15 00:19 UTC, BabuSrithar commented on src/current/v23.1/sso-sql.md
> +| `server.jwt_authentication.jwks` | A list of public signing keys for allowed IdPs; must include your IdP's key. If `server.jwt_authentication.jwksAutoFetchEnabled` is `true`, keys are fetched autom
The setting name is `server.jwt_authentication.jwks_auto_fetch.enabled`

2024-03-15 00:19 UTC, BabuSrithar commented on src/current/v23.1/sso-sql.md
> +    This must match your cluster's configured value for `server.oidc_authentication.provider_url`. Refer to [Single Sign-on (SSO) for DB Console](sso-db-console.html#cluster-settings). Issues typical
Issuers

2024-03-15 00:19 UTC, BabuSrithar commented on src/current/v23.1/sso-sql.md
> +    This must match your cluster's configured value for `server.oidc_authentication.provider_url`. Refer to [Single Sign-on (SSO) for DB Console](sso-db-console.html#cluster-settings). Issues typical
Not typically, they are "expected to".

2024-03-15 00:19 UTC, BabuSrithar commented on src/current/v23.1/sso-sql.md
> +    IdPs such as Google rotate their signing keys periodically. You must update your cluster with a new signing key before the previous one expires, or your SQL clients will be unable to connect with
`server.jwt_authentication.jwks_auto_fetch.enabled`

2024-03-15 00:19 UTC, BabuSrithar commented on src/current/v23.1/sso-sql.md
> +    IdPs such as Google rotate their signing keys periodically. You must update your cluster with a new signing key before the previous one expires, or your SQL clients will be unable to connect with
`server.jwt_authentication.jwks_auto_fetch.enabled`

2024-03-15 00:19 UTC, BabuSrithar commented on src/current/v23.1/sso-sql.md
> +1. Instead of setting `server.jwt_authentication.jwks` to a list of static signing keys, you can set `server.jwt_authentication.jwksAutoFetchEnabled` to `true` to enable automatic fetching of signing
`server.jwt_authentication.jwks_auto_fetch.enabled`

2024-03-15 00:44 UTC, BabuSrithar commented on src/current/v23.1/sso-sql.md
> +1. Add your IdP's formal `issuer` name to your cluster's list of accepted token issuers. The `issuer` name is usually the issuer's domain and must match the `issuer` field in the JWT itself.
"iss" is the field name.

2024-03-15 19:16 UTC, dikshant reviewed
A couple of places we need to change the cluster setting to `server.jwt_authentication.jwks_auto_fetch.enabled`

2024-03-15 19:16 UTC, dikshant commented on src/current/v23.2/sso-sql.md
> +| `server.jwt_authentication.jwksAutoFetchEnabled` | If `true`, public signing keys are automatically fetched from the issuer and there is no need to set `server.jwt_authentication.jwks`. Defaults to
`server.jwt_authentication.jwks_auto_fetch.enabled` as Srithar pointed out.

2024-03-15 19:17 UTC, dikshant commented on src/current/v23.1/sso-sql.md
> +| {% include_cached new-in.html version="v23.1" %}`server.jwt_authentication.jwksAutoFetchEnabled` | If `true`, public signing keys are automatically fetched from the domains specified in `server.jwt
`server.jwt_authentication.jwks_auto_fetch.enabled` instead of `server.jwt_authentication.jwksAutoFetchEnabled` as Srithar pointed out above.

2024-03-18 17:20 UTC, dikshant approved these changes
LGTM 🚀

2024-03-19 02:54 UTC, BabuSrithar approved these changes
LGTM, Thanks @mdlinville

2024-03-19 18:48 UTC, rmloveland approved these changes
LGTM, few non-blocking suggestions

2024-03-19 18:48 UTC, rmloveland commented on src/current/v23.1/sso-sql.md
> +1. Set `server.jwt_authentication.claim` to the field in the JWT that the cluster will use as the identity of the SQL user. To use the email field in the JWT, set `server.jwt_authentication.claim` to
'SQL user' could be a link to https://www.cockroachlabs.com/docs/cockroachcloud/managing-access#manage-sql-users-on-a-cluster

2024-03-19 18:48 UTC, rmloveland commented on src/current/v23.1/sso-sql.md
> +    Maps a single external identity with the hard-coded ID to the SQL user `roach`.
'SQL user' could be a link to that SQL user mgmt doc I shared above

2024-03-19 18:48 UTC, rmloveland commented on src/current/v23.2/sso-sql.md
> +    Maps a single external identity with the hard-coded ID to the SQL user `roach`.
'SQL user' could link to those SQL user mgmt docs

2024-03-19 18:48 UTC, rmloveland commented on src/current/v24.1/sso-sql.md
> +    Maps a single external identity with the hard-coded ID to the SQL user `roach`.
'SQL user' could be a link to the SQL user mgmt docs

2024-03-19 20:46 UTC, mdlinville commented on src/current/v23.1/sso-sql.md
> +1. Set `server.jwt_authentication.claim` to the field in the JWT that the cluster will use as the identity of the SQL user. To use the email field in the JWT, set `server.jwt_authentication.claim` to
```suggestion
1. Set `server.jwt_authentication.claim` to the field in the JWT that the cluster will use as the identity of the [SQL user](https://www.cockroachlabs.com/docs/cockroachcloud/managing-access#manage-sql-users-on-a-cluster). To use the email field in the JWT, set `server.jwt_authentication.claim` to `email`.
```

2024-03-19 20:46 UTC, mdlinville commented on src/current/v23.1/sso-sql.md
> +    Maps a single external identity with the hard-coded ID to the SQL user `roach`.
```suggestion
    Maps a single external identity with the hard-coded ID to the [SQL user](https://www.cockroachlabs.com/docs/cockroachcloud/managing-access#manage-sql-users-on-a-cluster) `roach`.
```

2024-03-19 20:46 UTC, mdlinville commented on src/current/v23.2/sso-sql.md
> +    Maps a single external identity with the hard-coded ID to the SQL user `roach`.
```suggestion
    Maps a single external identity with the hard-coded ID to the [SQL user](https://www.cockroachlabs.com/docs/cockroachcloud/managing-access#manage-sql-users-on-a-cluster) `roach`.
```

2024-03-19 20:46 UTC, mdlinville commented on src/current/v24.1/sso-sql.md
> +    Maps a single external identity with the hard-coded ID to the SQL user `roach`.
```suggestion
    Maps a single external identity with the hard-coded ID to the [SQL user](https://www.cockroachlabs.com/docs/cockroachcloud/managing-access#manage-sql-users-on-a-cluster) `roach`.
```

2024-03-19 20:54 UTC, merged