[DOC-9332] Document new regions on Azure (Part 2 of N, CC-25999)
cockroachdb/docs pull request #18430
Opened 2024-03-28 21:25 UTC by mdlinville

[DOC-9332] Document new regions on Azure (Part 2 of N, CC-25999)

TODO: Update the date when known

2024-04-17 01:59 UTC, adwittumuluri requested changes
We will not be offering the following regions, which'll need to be removed from this pr:

* `northcentralus`
* `westcentralus`
* `italynorth`
* `westus`
* `israelcentral`
* `brazilsouth`

2024-04-17 01:59 UTC, adwittumuluri commented on src/current/_includes/releases/cloud/2024-04-04.md
> +                    | `australiaeast`      | New South Wales
we always supported `australiaeast` and `germanywestcentral`, they can be removed from this list.

2024-04-17 01:59 UTC, adwittumuluri commented on src/current/_includes/releases/cloud/2024-04-04.md
> +                    | `australiaeast`      | New South Wales
The full list of regions is given by any org in staging right now.

2024-04-17 21:34 UTC, adwittumuluri approved these changes
LGTM!

2024-04-18 15:00 UTC, rmloveland approved these changes
LGTM once the broken table render is fixed

2024-04-18 16:59 UTC, mdlinville commented on src/current/_includes/releases/cloud/2024-04-18.md
> +                    | `switzerlandnorth`   | Zürich
```suggestion
    Geographic Area  | Region Name          | Location
    -----------------|----------------------|---------
    Africa           | `southafricanorth`   | Johannesburg
    Asia Pacific     | `japaneast`          | Tokyo
                     | `koreacentral`       | Seoul
    Middle East      | `qatarcentral`       | Doha
                     | `uaenorth`           | Dubai
                     | `southcentralus`     | Texas
                     | `westus3`            | Washington
    Western Europe   | `francecentral`      | Paris
                     | `norwayeast`         | Oslo
                     | `polandcentral`      | Warsaw
                     | `swedencentral`      | Gävle
                     | `switzerlandnorth`   | Zürich
```

2024-04-18 17:07 UTC, merged