[POC] Use common includes for v24.2 orchestration pages
cockroachdb/docs pull request #18894
Opened 2024-09-11 18:48 UTC by mdlinville

Within each major version, a series of pages about Kubernetes is driven by a series of includes about Kubernetes. Kubernetes itself is CRDB-version-agnostic.  Rather than moving the content pages around, this PR is the first step / proof of concept toward sharing the common includes among all major version docs.

This PR:

- Moves `images/v24.2/kubernetes*.png` to `images/common/`
- Moves `_includes/v24.2/orchesteration/` to `_includes/common/orchestration`
- Updates includes within `_includes/common/orchestration` to point to the common content for their own includes and to use the common images.
  - No includes other than orchestration includes are called within `_includes/v24.2` and no other v24.2 pages use the common images.
- Updates pages within `v24.2/` to point to the common content for orchestration includes.
- Tweak the `cockroachcloud/use-cloud-instead.md` include to be cacheable by removing a link.
- Where the include contains no Liquid, update related `include` statements to `include_cached`.

Tests:
- Local build
- Local linkcheck

TODO:
- Backport through v23.1, comparing each version-specific include with the common to find and accommodate any differences. I do not expect any.

2024-10-15 18:47 UTC, taroface requested changes
Blocking because a few files/filenames got mixed up here, causing the wrong content to be shown.

2024-10-15 18:47 UTC, taroface commented on src/current/v23.1/upgrade-cockroachdb-kubernetes.md
Same comment as earlier; this is the wrong file content.

2024-10-15 18:47 UTC, taroface commented on src/current/v24.2/upgrade-cockroachdb-kubernetes.md
Ditto

2024-10-15 18:47 UTC, taroface commented on src/current/v24.3/upgrade-cockroachdb-kubernetes.md
Ditto

2024-10-28 23:59 UTC, mdlinville commented on src/current/_includes/cockroachcloud/use-cockroachcloud-instead.md
> +To deploy a free CockroachDB Cloud cluster instead of running CockroachDB yourself, see the [Quickstart]({% link cockroachcloud/quickstart.md %}).
I can't remember. I put it back, with a slight reword.

2024-10-29 00:00 UTC, mdlinville commented on src/current/_includes/common/orchestration/start-cockroachdb-helm-insecure.md
> +      {% include_cached copy-clipboard.html %}
Done

2024-10-29 00:01 UTC, mdlinville commented on src/current/_includes/common/orchestration/start-cockroachdb-insecure.md
> +   Modify the file wherever there is a `TODO` comment, then use the file to create the StatefulSet and start the cluster:
It's just missing a single space. Done.

2024-10-29 00:04 UTC, mdlinville commented on src/current/_includes/common/orchestration/test-cluster-insecure.md
>      -f https://raw.githubusercontent.com/cockroachdb/cockroach-operator/v{{ latest_operator_version }}/examples/client-secure-operator.yaml
We don't, it's a bit awkward but I'm OK with it for now. The Operator is not widely used, much less likely to be used in insecure mode than not.

2024-10-29 00:10 UTC, mdlinville commented on src/current/_includes/common/orchestration/test-cluster-insecure.md
Done

2024-10-29 00:13 UTC, mdlinville commented on src/current/v22.2/upgrade-cockroachdb-kubernetes.md
Done

2024-10-29 00:13 UTC, mdlinville commented on src/current/v23.1/upgrade-cockroachdb-kubernetes.md
Done

2024-11-07 22:46 UTC, mdlinville commented
@taroface The simplest way for me to address the include mistakes was to go back to before the backports, fix the mistakes in v24.3, and make sure that v24.2 and v24.3 were in sync. I will pause here for your re-review before redoing the remaining backports.

2024-11-07 23:45 UTC, mdlinville commented on src/current/_includes/common/orchestration/start-cockroachdb-insecure.md
> +   Modify the file wherever there is a `TODO` comment, then use the file to create the StatefulSet and start the cluster:
```suggestion
    Modify the file wherever there is a `TODO` comment, then use the file to create the StatefulSet and start the cluster:
```
Refixing this.

2024-11-07 23:48 UTC, mdlinville commented on src/current/_includes/common/orchestration/start-cockroachdb-helm-insecure.md
> +      ~~~
```suggestion
        {% include_cached copy-clipboard.html %}
        ~~~
        statefulset:
          resources:
            limits:
              memory: "8Gi"
            requests:
              memory: "8Gi"
        conf:
          cache: "2Gi"
          max-sql-memory: "2Gi"
        ~~~
```

2025-01-17 18:52 UTC, closed without merging