fix read committed connection parameter
cockroachdb/docs pull request #18922
Opened 2024-09-19 15:43 UTC by taroface

DOC-11182

2024-09-19 17:31 UTC, rafiss requested changes

2024-09-19 17:31 UTC, rafiss commented on src/current/v23.2/read-committed.md
> +	cockroach sql --url='postgresql://{username}@{host}:{port}/{database}?default_transaction_isolation=read committed'
although the `options` parameter is more complex, unfortuntately PGJDBC, which is one of the most popular drivers, doesn't support configuring session variables in the URL unless they are in the `options` section.

i think it makes sense to keep the old example, but just fix the spacing. so it should be
```
postgresql://{username}@{host}:{port}/{database}?options=-c default_transaction_isolation=read\ committed
```

i left this comment in the thread where @smcvey initially filed this issue too: https://cockroachlabs.slack.com/archives/C04E47S4KK9/p1726758096559559?thread_ts=1726751860.181139&cid=C04E47S4KK9

2024-09-20 05:53 UTC, rafiss approved these changes
thanks for the fix!

2024-09-20 14:46 UTC, florence-crl approved these changes
lgtm

2024-09-20 18:22 UTC, merged