Update Yugabyte info in cockroachdb-in-comparison.md
cockroachdb/docs pull request #19248
Opened 2024-12-17 20:16 UTC by hari90

Updating some minor errors about Yugabyte.
- Database horizontal scale: Leaders in yb are automatically balanced and spread across the newly added nodes. https://docs.yugabyte.com/preview/explore/linear-scalability/
- Automated repair and RPO(Recovery Point Objective): Yugabyte has 0 RPO, and 3s RTO. https://docs.yugabyte.com/preview/explore/fault-tolerance
- SQL: Yugabyte is SQL compatible. https://docs.yugabyte.com/preview/api/ysql/
- Data Geo-partitioning: There are CRDB blogs with examples that show geo partitioning in YB. https://www.cockroachlabs.com/blog/postgresql-compatible-database-cockroachdb/
- Multi-region: Yugabyte can be deployed across multi regions with writes on both sides. https://docs.yugabyte.com/preview/explore/fault-tolerance/handling-region-failures/
- Multi-cloud: Yugabyte can be deployed across multi clouds. https://docs.yugabyte.com/preview/yugabyte-platform/create-deployments/create-universe-multi-cloud/

2024-12-18 07:56 UTC, codingconcepts requested changes
Just a couple of points from me!

2024-12-18 07:56 UTC, codingconcepts commented on src/current/v24.3/cockroachdb-in-comparison.md
> +      <span class="support" data-dbs='["Spanner"]'>"Automated repair RPO &lt;10 sec"</span>
Is there any reason these have quotes and others don't?

2024-12-18 07:56 UTC, codingconcepts commented on src/current/v24.3/cockroachdb-in-comparison.md
> +      <span class="support" data-dbs='["Spanner"]'>"Automated repair RPO &lt;10 sec"</span>
Same with this

2024-12-18 07:56 UTC, codingconcepts commented on src/current/v24.3/cockroachdb-in-comparison.md
> +      <span class="support " data-dbs='["Spanner", "Yugabyte"]'>Yes</span>
Yugabyte also supports row-level geo-partitioning: https://docs.yugabyte.com/preview/explore/multi-region-deployments/row-level-geo-partitioning

I'd just change both Yugabyte's and CockroachDB's values to "Yes".

2024-12-18 18:20 UTC, hari90 commented
> Just a couple of points from me!

@codingconcepts Thanks for the quick review. I have addressed your comments.

2025-01-03 21:50 UTC, hari90 commented
@codingconcepts a gentle ping on this.

2025-03-14 22:45 UTC, closed without merging