CHAR subtypes
cockroachdb/docs pull request #8250
Opened 2020-09-08 19:21 UTC by ericharmeling

Fixes #7859.

@otan ... not sure who else to add to this. 

I'm particularly skeptical about this claim I added in there:

"By default, `STRING` values are variable-length, with a limit. As such, `CHARACTER VARYING` and `VARCHAR` types are aliases for `STRING`."

2020-09-08 19:21 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/8250)
<!-- Reviewable:end -->

2020-09-08 19:52 UTC, otan commented
string is a CockroachDB only thing, I believe it is handled exactly like TEXT (i.e. no limit).

2020-09-09 14:06 UTC, ericharmeling commented
Making this a WIP PR until we more carefully look at the expected differences between the subtypes

@jordanlewis

2021-05-24 21:08 UTC, ericharmeling commented
@rafiss 

I've updated this PR following our conversation. PTAL.

2021-05-25 03:34 UTC, rafiss requested changes
just one comment, then lgtm!

2021-05-25 03:34 UTC, rafiss commented on v19.2/string.md
> +`TEXT`                                                                | Variable-length, with no limit
i think the last two lines should look more like

```
`CHARACTER VARYING(n)`,  `VARCHAR(n)`                                 | Variable-length, with a limit  
`TEXT`, `VARCHAR`, `CHARACTER VARYING`, `STRING`                      | Variable-length, with no limit
```

(this looks correct on the docs for the other versions below)

2021-05-25 07:42 UTC, ckoehn commented on releases/v20.2.0-alpha.2.md
> -- The `CHAR` column [`type`](../v20.2/data-types.html) will now truncate the trailing space characters in line with Postgres. Existing stored `CHAR` entries with spaces at the end of the `CHAR` colum
The GA release notes of `20.2` don't mention this change at all. Shouldn't it be added there?

2021-05-25 17:28 UTC, ericharmeling reviewed
@rafiss 

TFTR !

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8250#-:-MaZX14H52az1KFXnIUS:b-mntzw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[v19.2/string.md, line 17 at r1](https://reviewable.io/reviews/cockroachdb/docs/8250#-MGj9cBh5joLQKieV8Sx-r1-17:-MaZW1msArmZh7h3AHdz:blpinxg) ([raw file](https://github.com/cockroachdb/docs/blob/f171eafcb8a635945eadefd31ac045e5afcbe589/v19.2/string.md#L17)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think the last two lines should look more like

```
`CHARACTER VARYING(n)`,  `VARCHAR(n)`                                 | Variable-length, with a limit  
`TEXT`, `VARCHAR`, `CHARACTER VARYING`, `STRING`                      | Variable-length, with no limit
```

(this looks correct on the docs for the other versions below)
</blockquote></details>

Ah. I missed the updates on this version of the page since we don't officially support 19.2 anymore.

I updated the page anyways.

Also - I added `STRING(n)` to that second row in all updated versions. Is that correct?


<!-- Sent from Reviewable.io -->

2021-05-25 17:37 UTC, ericharmeling reviewed
@ckoehn 

> The GA release notes of 20.2 don't mention this change at all. Shouldn't it be added there?

That's a good shout, but we try to reserve the GA release note [feature summary](https://www.cockroachlabs.com/docs/releases/v20.2.0#feature-summary) to "the most significant user-facing changes" in a GA release. And I wouldn't consider this change a significant user-facing change.

I do, however, think that this change is important enough to document in the testing release notes, and to call out on the appropriate docs page (i.e., [the `STRING` page](https://www.cockroachlabs.com/docs/v21.1/string.html)). Note that the GA release note [feature summary](https://www.cockroachlabs.com/docs/releases/v20.2.0#feature-summary) points users to testing release notes and "New in 20.2" callouts for minor user-facing updates.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8250#-:-MaZZZEw3qYB5xEYh-iM:bjelrfh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)



<!-- Sent from Reviewable.io -->

2021-05-25 17:56 UTC, rafiss approved these changes
this lgtm! thanks for the updates

2021-05-26 01:46 UTC, ianjevans approved these changes

2021-05-26 13:52 UTC, merged