User-defined schemas
cockroachdb/docs pull request #8273
Opened 2020-09-10 21:19 UTC by ericharmeling

Fixes #8164.
Fixes #5993.

- Added new pages for `CREATE SCHEMA`, `ALTER SCHEMA`, and `DROP SCHEMA`.
- Updated `SHOW SCHEMAS` page, and other references to user-defined schema support.

Note that this PR pilots using CLI help text instead of SQL diagrams for statement syntax documentation.

2020-09-10 21:19 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/8273)
<!-- Reviewable:end -->

2020-09-10 21:23 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/50a6d50933c0cf01705d7602233783b90e1a152f/

Edited pages:
- [v19.2/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/50a6d50933c0cf01705d7602233783b90e1a152f/v19.2/sql-feature-support.html)
- [v19.2/sql-name-resolution.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/50a6d50933c0cf01705d7602233783b90e1a152f/v19.2/sql-name-resolution.html)
- [v20.1/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/50a6d50933c0cf01705d7602233783b90e1a152f/v20.1/sql-feature-support.html)
- [v20.1/sql-name-resolution.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/50a6d50933c0cf01705d7602233783b90e1a152f/v20.1/sql-name-resolution.html)
- [v20.2/alter-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/50a6d50933c0cf01705d7602233783b90e1a152f/v20.2/alter-schema.html)
- [v20.2/create-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/50a6d50933c0cf01705d7602233783b90e1a152f/v20.2/create-schema.html)
- [v20.2/detailed-sql-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/50a6d50933c0cf01705d7602233783b90e1a152f/v20.2/detailed-sql-support.html)
- [v20.2/drop-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/50a6d50933c0cf01705d7602233783b90e1a152f/v20.2/drop-schema.html)
- [v20.2/show-schemas.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/50a6d50933c0cf01705d7602233783b90e1a152f/v20.2/show-schemas.html)
- [v20.2/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/50a6d50933c0cf01705d7602233783b90e1a152f/v20.2/sql-feature-support.html)
- [v20.2/sql-name-resolution.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/50a6d50933c0cf01705d7602233783b90e1a152f/v20.2/sql-name-resolution.html)
- [v20.2/sql-statements.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/50a6d50933c0cf01705d7602233783b90e1a152f/v20.2/sql-statements.html)

2020-09-10 21:36 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8687076f1579c248aae8cadb5cb5072aa9815d09/

Edited pages:
- [v19.2/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8687076f1579c248aae8cadb5cb5072aa9815d09/v19.2/sql-feature-support.html)
- [v19.2/sql-name-resolution.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8687076f1579c248aae8cadb5cb5072aa9815d09/v19.2/sql-name-resolution.html)
- [v20.1/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8687076f1579c248aae8cadb5cb5072aa9815d09/v20.1/sql-feature-support.html)
- [v20.1/sql-name-resolution.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8687076f1579c248aae8cadb5cb5072aa9815d09/v20.1/sql-name-resolution.html)
- [v20.2/alter-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8687076f1579c248aae8cadb5cb5072aa9815d09/v20.2/alter-schema.html)
- [v20.2/create-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8687076f1579c248aae8cadb5cb5072aa9815d09/v20.2/create-schema.html)
- [v20.2/detailed-sql-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8687076f1579c248aae8cadb5cb5072aa9815d09/v20.2/detailed-sql-support.html)
- [v20.2/drop-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8687076f1579c248aae8cadb5cb5072aa9815d09/v20.2/drop-schema.html)
- [v20.2/show-schemas.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8687076f1579c248aae8cadb5cb5072aa9815d09/v20.2/show-schemas.html)
- [v20.2/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8687076f1579c248aae8cadb5cb5072aa9815d09/v20.2/sql-feature-support.html)
- [v20.2/sql-name-resolution.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8687076f1579c248aae8cadb5cb5072aa9815d09/v20.2/sql-name-resolution.html)
- [v20.2/sql-statements.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8687076f1579c248aae8cadb5cb5072aa9815d09/v20.2/sql-statements.html)

2020-09-21 17:16 UTC, ericharmeling commented
@lucy-zhang 

Friendly review reminder :)

2020-09-22 14:44 UTC, lucy-zhang commented
I'll get to this today.

2020-09-22 14:47 UTC, lucy-zhang commented
It might also be good to get someone on SQL Features to look at this. Maybe @arulajmani or @solongordon?

2020-09-22 15:05 UTC, arulajmani commented
I can take a look later today.

2020-09-22 15:09 UTC, ericharmeling commented
Awesome. Thanks, y'all!

2020-09-23 03:32 UTC, lucy-zhang reviewed
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8273)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @ericharmeling)

___
*[v20.2/alter-schema.md, line 3 at r1](https://reviewable.io/reviews/cockroachdb/docs/8273#-MHsvR497p3hELjjCVa8:-MHsvR497p3hELjjCVa9:bgbcuwx) ([raw file](https://github.com/cockroachdb/docs/blob/8687076f1579c248aae8cadb5cb5072aa9815d09/v20.2/alter-schema.md#L3)):*
> ```Markdown
> ---
> title: ALTER SCHEMA
> summary: The ALTER SCHEMA statement modifies a user-defined data type in a database.
> ```

s/data type/schema
___
*[v20.2/alter-schema.md, line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/8273#-MHsx2o-02lTNfm_0APs:-MHsx2o-02lTNfm_0APt:b-h6xmt8) ([raw file](https://github.com/cockroachdb/docs/blob/8687076f1579c248aae8cadb5cb5072aa9815d09/v20.2/alter-schema.md#L13)):*
> ```Markdown
> ~~~
> ALTER SCHEMA ... RENAME TO <newschemaname>
> ALTER SCHEMA ... OWNER TO {<newowner> | CURRENT_USER | SESSION_USER }
> ```

This isn't specific to schemas and maybe isn't even a documentation issue per se, but I'm confused about what the `{<newowner> | CURRENT_USER | SESSION_USER }` part means, since something like `ALTER SCHEMA sc OWNER TO CURRENT_USER` gives me an error about there not being a user `current_user` instead of recognizing this syntax. How is this syntax supposed to work? cc @arulajmani
___
*[v20.2/create-schema.md, line 3 at r1](https://reviewable.io/reviews/cockroachdb/docs/8273#-MHszFxi1rILv1e4_uht:-MHszFxj7yechNOvDAjV:bf61b1q) ([raw file](https://github.com/cockroachdb/docs/blob/8687076f1579c248aae8cadb5cb5072aa9815d09/v20.2/create-schema.md#L3)):*
> ```Markdown
> ---
> title: CREATE SCHEMA
> summary: The CREATE SCHEMA statement creates a new, user-defined schema.
> ```

nit: I don't think this needs a comma.
___
*[v20.2/create-schema.md, line 7 at r1](https://reviewable.io/reviews/cockroachdb/docs/8273#-MHszK7aC7lBrqpsBkGv:-MHszK7aC7lBrqpsBkGw:b-j3hpat) ([raw file](https://github.com/cockroachdb/docs/blob/8687076f1579c248aae8cadb5cb5072aa9815d09/v20.2/create-schema.md#L7)):*
> ```Markdown
> ---
> 
> <span class="version-tag">New in v20.2</span>: The `CREATE SCHEMA` [statement](sql-statements.html) creates a user-defined [schema](sql-name-resolution.html#logical-schemas-and-namespaces). With multiple schemas, you can create databases of the same name that belong to separate schemas.
> ```

I'm not sure what this last sentence means. Should that be "tables" instead of "databases"?


<!-- Sent from Reviewable.io -->

2020-09-23 14:25 UTC, arulajmani requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8273)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @lucy-zhang)

___
*[v20.2/alter-schema.md, line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/8273#-MHsx2o-02lTNfm_0APs:-MHvIFqY39FnjaXUrAgb:b-imxoge) ([raw file](https://github.com/cockroachdb/docs/blob/8687076f1579c248aae8cadb5cb5072aa9815d09/v20.2/alter-schema.md#L13)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

This isn't specific to schemas and maybe isn't even a documentation issue per se, but I'm confused about what the `{<newowner> | CURRENT_USER | SESSION_USER }` part means, since something like `ALTER SCHEMA sc OWNER TO CURRENT_USER` gives me an error about there not being a user `current_user` instead of recognizing this syntax. How is this syntax supposed to work? cc @arulajmani
</blockquote></details>

This definitely looks like a bug, yeah. Nice catch. I've filed https://github.com/cockroachdb/cockroach/issues/54696 for investigation. 
___
*[v20.2/create-schema.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/8273#-MHvKfkT0j3_3KokrBP3:-MHvKfkT0j3_3KokrBP4:b-mo28qr) ([raw file](https://github.com/cockroachdb/docs/blob/8687076f1579c248aae8cadb5cb5072aa9815d09/v20.2/create-schema.md#L16)):*
> ```Markdown
> 
> ~~~
> CREATE SCHEMA [IF NOT EXISTS] { <schemaname> | [<schemaname>] AUTHORIZATION {user_name | CURRENT_USER | SESSION_USER} }
> ```

Similar to @lucy-zhang's catch above, this CURRENT_USER/SESSION_USER stuff doesn't play well either because of https://github.com/cockroachdb/cockroach/issues/54696, not sure if this will affect docs. 
___
*[v20.2/create-schema.md, line 140 at r1](https://reviewable.io/reviews/cockroachdb/docs/8273#-MHvLJVG4_0vKP2_bAlp:-MHvLJVG4_0vKP2_bAlq:b-w4kmnz) ([raw file](https://github.com/cockroachdb/docs/blob/8687076f1579c248aae8cadb5cb5072aa9815d09/v20.2/create-schema.md#L140)):*
> ```Markdown
> ~~~
> 
> If no schema name is specified in a `CREATE SCHEMA` statement with an `AUTHORIZATION` clause, the schema will be named after the user specified:
> ```

Maybe it's worth extending this example by creating two tables with the same name, one in the public schema and one in the `$user` schema and showing how the name resolution works in that case? See my point/linked PR in the name resolution section for v20.2
___
*[v20.2/sql-name-resolution.md, line 46 at r1](https://reviewable.io/reviews/cockroachdb/docs/8273#-MHvC25wET5n9j9JUUtK:-MHvC25wET5n9j9JUUtL:bzfdsjm) ([raw file](https://github.com/cockroachdb/docs/blob/8687076f1579c248aae8cadb5cb5072aa9815d09/v20.2/sql-name-resolution.md#L46)):*
> ```Markdown
> 
> 1. If the name already fully specifies the database and schema, use that.
> 2. If the name has a single component prefix, try to find a schema with that name. If no such schema exists, use the `public` schema in the database with the prefix name.
> ```

I think recently we added a fix https://github.com/cockroachdb/cockroach/pull/54538 which might impact this section as well. 


<!-- Sent from Reviewable.io -->

2020-09-23 18:42 UTC, ericharmeling reviewed
TFTR @arulajmani @lucy-zhang 

I can either merge this ahead of cockroachdb/cockroach#54696 being resolved (i.e., publish documentation of desired behavior, but not current behavior), or we can wait until that issue is resolved before merging this. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8273#-:-MHvtDuX5GODHaj86Qu8:b-k7wvy0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @lucy-zhang)

___
*[v20.2/alter-schema.md, line 3 at r1](https://reviewable.io/reviews/cockroachdb/docs/8273#-MHsvR497p3hELjjCVa8:-MHvWMGf4QqTYPm7Ai1S:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/8687076f1579c248aae8cadb5cb5072aa9815d09/v20.2/alter-schema.md#L3)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

s/data type/schema
</blockquote></details>

Done.
___
*[v20.2/create-schema.md, line 3 at r1](https://reviewable.io/reviews/cockroachdb/docs/8273#-MHszFxi1rILv1e4_uht:-MHvWdNGBOQoQuQ7Cgcz:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/8687076f1579c248aae8cadb5cb5072aa9815d09/v20.2/create-schema.md#L3)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

nit: I don't think this needs a comma.
</blockquote></details>

Done.
___
*[v20.2/create-schema.md, line 7 at r1](https://reviewable.io/reviews/cockroachdb/docs/8273#-MHszK7aC7lBrqpsBkGv:-MHvX3szC8MQoC-CAYL5:b-gdckh3) ([raw file](https://github.com/cockroachdb/docs/blob/8687076f1579c248aae8cadb5cb5072aa9815d09/v20.2/create-schema.md#L7)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I'm not sure what this last sentence means. Should that be "tables" instead of "databases"?
</blockquote></details>

I removed this sentence, and made a new example to demonstrate that you can create two *tables* of the same name in separate schemas.
___
*[v20.2/create-schema.md, line 140 at r1](https://reviewable.io/reviews/cockroachdb/docs/8273#-MHvLJVG4_0vKP2_bAlp:-MHvirM874FEMPV3YflY:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/8687076f1579c248aae8cadb5cb5072aa9815d09/v20.2/create-schema.md#L140)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Maybe it's worth extending this example by creating two tables with the same name, one in the public schema and one in the `$user` schema and showing how the name resolution works in that case? See my point/linked PR in the name resolution section for v20.2
</blockquote></details>

Done.
___
*[v20.2/sql-name-resolution.md, line 46 at r1](https://reviewable.io/reviews/cockroachdb/docs/8273#-MHvC25wET5n9j9JUUtK:-MHvavTNAieR2QXCN0LV:bwbf91y) ([raw file](https://github.com/cockroachdb/docs/blob/8687076f1579c248aae8cadb5cb5072aa9815d09/v20.2/sql-name-resolution.md#L46)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I think recently we added a fix https://github.com/cockroachdb/cockroach/pull/54538 which might impact this section as well. 
</blockquote></details>

Thanks for the heads-up!

Updated this page.


<!-- Sent from Reviewable.io -->

2020-09-23 18:45 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3010ad91b6ff8637869b40e5e806aef7bde3a550/

Edited pages:
- [v19.2/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3010ad91b6ff8637869b40e5e806aef7bde3a550/v19.2/sql-feature-support.html)
- [v19.2/sql-name-resolution.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3010ad91b6ff8637869b40e5e806aef7bde3a550/v19.2/sql-name-resolution.html)
- [v20.1/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3010ad91b6ff8637869b40e5e806aef7bde3a550/v20.1/sql-feature-support.html)
- [v20.1/sql-name-resolution.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3010ad91b6ff8637869b40e5e806aef7bde3a550/v20.1/sql-name-resolution.html)
- [v20.2/alter-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3010ad91b6ff8637869b40e5e806aef7bde3a550/v20.2/alter-schema.html)
- [v20.2/create-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3010ad91b6ff8637869b40e5e806aef7bde3a550/v20.2/create-schema.html)
- [v20.2/detailed-sql-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3010ad91b6ff8637869b40e5e806aef7bde3a550/v20.2/detailed-sql-support.html)
- [v20.2/drop-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3010ad91b6ff8637869b40e5e806aef7bde3a550/v20.2/drop-schema.html)
- [v20.2/show-schemas.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3010ad91b6ff8637869b40e5e806aef7bde3a550/v20.2/show-schemas.html)
- [v20.2/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3010ad91b6ff8637869b40e5e806aef7bde3a550/v20.2/sql-feature-support.html)
- [v20.2/sql-name-resolution.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3010ad91b6ff8637869b40e5e806aef7bde3a550/v20.2/sql-name-resolution.html)
- [v20.2/sql-statements.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3010ad91b6ff8637869b40e5e806aef7bde3a550/v20.2/sql-statements.html)

2020-09-24 14:19 UTC, arulajmani commented
I'm leaning towards publishing this as-is unless @lucy-zhang  has reservations. This stuff is mostly about user defined schemas and the ownership concept is orthogonal to this. Also, the ownership stuff is broken everywhere (not just schemas) -- you can't use CURRENT_USER/SESSION_USER for databases/tables etc.

2020-09-24 14:32 UTC, lucy-zhang approved these changes
Yeah, that's fine with me.

I don't know what the scope of that bug is, but if we don't fix it for 20.2, maybe we should just remove the syntax from the docs (everywhere, not just for schemas)?

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8273#-:-MI-WemB3057etC_p8cf:b-9ohtgs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @ericharmeling)

___
*[v20.2/alter-schema.md, line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/8273#-MHsx2o-02lTNfm_0APs:-MI-Vpme2K5WfdOJVk_5:b-1q0ap6) ([raw file](https://github.com/cockroachdb/docs/blob/8687076f1579c248aae8cadb5cb5072aa9815d09/v20.2/alter-schema.md#L13)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

This definitely looks like a bug, yeah. Nice catch. I've filed https://github.com/cockroachdb/cockroach/issues/54696 for investigation. 
</blockquote></details>

Thanks for looking into this.
___
*[v20.2/create-schema.md, line 108 at r2](https://reviewable.io/reviews/cockroachdb/docs/8273#-MI-W62A6T8rGU-AF189:-MI-W62A6T8rGU-AF18A:bpaqupl) ([raw file](https://github.com/cockroachdb/docs/blob/3010ad91b6ff8637869b40e5e806aef7bde3a550/v20.2/create-schema.md#L108)):*
> ```Markdown
> ~~~
> 
> ### Create two tables of the same name, in the same database
> ```

I find this a slightly confusing heading. Maybe "Create tables of the same name in different schemas"?


<!-- Sent from Reviewable.io -->

2020-09-24 14:35 UTC, ericharmeling reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8273)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @lucy-zhang)

___
*[v20.2/create-schema.md, line 108 at r2](https://reviewable.io/reviews/cockroachdb/docs/8273#-MI-W62A6T8rGU-AF189:-MI-XF9q8fFcu3H_fXxm:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3010ad91b6ff8637869b40e5e806aef7bde3a550/v20.2/create-schema.md#L108)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I find this a slightly confusing heading. Maybe "Create tables of the same name in different schemas"?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-24 14:39 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/

Edited pages:
- [v19.2/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v19.2/sql-feature-support.html)
- [v19.2/sql-name-resolution.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v19.2/sql-name-resolution.html)
- [v20.1/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v20.1/sql-feature-support.html)
- [v20.1/sql-name-resolution.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v20.1/sql-name-resolution.html)
- [v20.2/alter-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v20.2/alter-schema.html)
- [v20.2/create-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v20.2/create-schema.html)
- [v20.2/detailed-sql-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v20.2/detailed-sql-support.html)
- [v20.2/drop-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v20.2/drop-schema.html)
- [v20.2/show-schemas.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v20.2/show-schemas.html)
- [v20.2/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v20.2/sql-feature-support.html)
- [v20.2/sql-name-resolution.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v20.2/sql-name-resolution.html)
- [v20.2/sql-statements.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v20.2/sql-statements.html)

2020-09-24 14:49 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6ada6cd0b4395d96e7e09e7a484261812c6d340d/

Edited pages:
- [v19.2/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6ada6cd0b4395d96e7e09e7a484261812c6d340d/v19.2/sql-feature-support.html)
- [v19.2/sql-name-resolution.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6ada6cd0b4395d96e7e09e7a484261812c6d340d/v19.2/sql-name-resolution.html)
- [v20.1/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6ada6cd0b4395d96e7e09e7a484261812c6d340d/v20.1/sql-feature-support.html)
- [v20.1/sql-name-resolution.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6ada6cd0b4395d96e7e09e7a484261812c6d340d/v20.1/sql-name-resolution.html)
- [v20.2/alter-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6ada6cd0b4395d96e7e09e7a484261812c6d340d/v20.2/alter-schema.html)
- [v20.2/create-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6ada6cd0b4395d96e7e09e7a484261812c6d340d/v20.2/create-schema.html)
- [v20.2/detailed-sql-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6ada6cd0b4395d96e7e09e7a484261812c6d340d/v20.2/detailed-sql-support.html)
- [v20.2/drop-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6ada6cd0b4395d96e7e09e7a484261812c6d340d/v20.2/drop-schema.html)
- [v20.2/show-schemas.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6ada6cd0b4395d96e7e09e7a484261812c6d340d/v20.2/show-schemas.html)
- [v20.2/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6ada6cd0b4395d96e7e09e7a484261812c6d340d/v20.2/sql-feature-support.html)
- [v20.2/sql-name-resolution.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6ada6cd0b4395d96e7e09e7a484261812c6d340d/v20.2/sql-name-resolution.html)
- [v20.2/sql-statements.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6ada6cd0b4395d96e7e09e7a484261812c6d340d/v20.2/sql-statements.html)

2020-09-24 15:27 UTC, lnhsingh reviewed
Some nits but once fixed, LGTM!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8273#-:-MI-iTfs6GvTrg0jbawk:b-9kfz2y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @ericharmeling, and @lucy-zhang)

___
*[v20.2/alter-schema.md, line 20 at r3](https://reviewable.io/reviews/cockroachdb/docs/8273#-MI-_U307s9KA3Pq9Jmn:-MI-_U323jsgZWyDiR_H:b-jr9w25) ([raw file](https://github.com/cockroachdb/docs/blob/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v20.2/alter-schema.md#L20)):*
> ```Markdown
> Parameter | Description
> ----------|------------
> `RENAME TO ...` | Rename the schema.
> ```

Does the schema name need to be unique?
___
*[v20.2/alter-schema.md, line 21 at r3](https://reviewable.io/reviews/cockroachdb/docs/8273#-MI-_BkwCxkP9glxwD7w:-MI-_BkwCxkP9glxwD7x:bdtx0o2) ([raw file](https://github.com/cockroachdb/docs/blob/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v20.2/alter-schema.md#L21)):*
> ```Markdown
> ----------|------------
> `RENAME TO ...` | Rename the schema.
> `OWNER TO ...` | Change the owner of the schema. You can specify the new owner with a string literal or the [`CURRENT_USER` or `SESSION_USER` keywords](functions-and-operators.html#special-syntax-forms).
> ```

Possibly link to string.html here?
___
*[v20.2/alter-schema.md, line 123 at r3](https://reviewable.io/reviews/cockroachdb/docs/8273#-MI-_z5W4KGEvSOr_T9C:-MI-_z5W4KGEvSOr_T9D:bmuvo7x) ([raw file](https://github.com/cockroachdb/docs/blob/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v20.2/alter-schema.md#L123)):*
> ```Markdown
> ~~~
> 
> Rename the schema as its owner:
> ```

Suggestion: reword to be something like `As its owner, you can rename the schema:`
___
*[v20.2/alter-schema.md, line 174 at r3](https://reviewable.io/reviews/cockroachdb/docs/8273#-MI-eAD677KHOIG-8KVO:-MI-eAD677KHOIG-8KVP:bvav2qw) ([raw file](https://github.com/cockroachdb/docs/blob/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v20.2/alter-schema.md#L174)):*
> ```
> the current owner must belong to the role of the new owner (in this case, `max`)
> ```

Should the order on this be flipped since the _new_ owner must be in the same role as the old owner? So: `...the new owner must belong to the role of the current owner`

Also, should the parenthetical be `(in this case, `admin`)` since that's the _role_ of the current owner?  If that's the case, the next SQL statement should be `GRANT max to admin` right?
___
*[v20.2/create-schema.md, line 25 at r3](https://reviewable.io/reviews/cockroachdb/docs/8273#-MI-gme45vTpWhuqEh-8:-MI-gme45vTpWhuqEh-9:b-xv010l) ([raw file](https://github.com/cockroachdb/docs/blob/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v20.2/create-schema.md#L25)):*
> ```Markdown
> `IF NOT EXISTS` | Create a new schema only if a schema of the same name does not already exist. If one does exist, do not return an error.
> `schemaname` | The name of the schema to create, which must be unique and follow these [identifier rules](keywords-and-identifiers.html#identifiers).
> `AUTHORIZATION ...` | Optionally identify a user to be the owner of the schema. You can specify the owner with a string literal, or the [`CURRENT_USER` or `SESSION_USER` keywords](functions-and-operators.html#special-syntax-forms).<br><br>If a `CREATE SCHEMA` statement has an `AUTHORIZATION` clause, but no `schemaname`, the schema will be named after the specified owner of the schema. If a `CREATE SCHEMA` statement does not have an `AUTHORIZATION` clause, the user executing the statement will be named the owner.
> ```

Link to string.html?
___
*[v20.2/create-schema.md, line 275 at r3](https://reviewable.io/reviews/cockroachdb/docs/8273#-MI-hZiA0BmnU664HIFh:-MI-hZiA0BmnU664HIFi:b4dtcx8) ([raw file](https://github.com/cockroachdb/docs/blob/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v20.2/create-schema.md#L275)):*
> ```Markdown
> ~~~
> 
> `max` then inserts some values into the `accounts` table, without specifying a schema.
> ```

nit: end with a `:`


<!-- Sent from Reviewable.io -->

2020-09-24 18:10 UTC, ericharmeling reviewed
TFTR @lnhsingh!

I addressed all of your comments, but my knowledge on a couple things might need verification from engineering.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8273#-:-MI08s2x3YPGrt5eVO6u:bmpmnnl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @lnhsingh, and @lucy-zhang)

___
*[v20.2/alter-schema.md, line 20 at r3](https://reviewable.io/reviews/cockroachdb/docs/8273#-MI-_U307s9KA3Pq9Jmn:-MI07SmgEw-6rNLWhCkt:be35akj) ([raw file](https://github.com/cockroachdb/docs/blob/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v20.2/alter-schema.md#L20)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Does the schema name need to be unique?
</blockquote></details>

I think the new schema name must follow the same rules as the new table name in `RENAME TABLE`. Updated this description in a new commit.

@lucy-zhang 
Does this look correct?
___
*[v20.2/alter-schema.md, line 21 at r3](https://reviewable.io/reviews/cockroachdb/docs/8273#-MI-_BkwCxkP9glxwD7w:-MI07i945Y6xu-eKRp5S:b-k2al1y) ([raw file](https://github.com/cockroachdb/docs/blob/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v20.2/alter-schema.md#L21)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Possibly link to string.html here?
</blockquote></details>

I'm not sure the `STRING` page will help here, since that page is about column data types rather than string literals. I linked instead to the wikipedia page for "String literal" (https://en.wikipedia.org/wiki/String_literal).
___
*[v20.2/alter-schema.md, line 123 at r3](https://reviewable.io/reviews/cockroachdb/docs/8273#-MI-_z5W4KGEvSOr_T9C:-MI08CE1-pY2DYDgEsAJ:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v20.2/alter-schema.md#L123)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Suggestion: reword to be something like `As its owner, you can rename the schema:`
</blockquote></details>

Done.
___
*[v20.2/alter-schema.md, line 174 at r3](https://reviewable.io/reviews/cockroachdb/docs/8273#-MI-eAD677KHOIG-8KVO:-MI08uY-3pSYMdLRTbMY:b5o9mcm) ([raw file](https://github.com/cockroachdb/docs/blob/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v20.2/alter-schema.md#L174)):*
> Should the order on this be flipped since the new owner must be in the same role as the old owner?

That would make sense, but I don't think that's technically how it's checked.

See the description of https://github.com/cockroachdb/cockroach/pull/52781: 

> the following conditions must be met:
...
The user executing the command must be a member of the new owner role.
...

And in the logic tests at https://github.com/cockroachdb/cockroach/pull/52781/files#diff-1273a3998fbd62a94eafd18b2369954fR11 : 

```
# Ensure the current user is a member of the role we're setting to.
statement error pq: must be member of role "testuser"
ALTER SCHEMA s OWNER TO testuser
```

The new owner (`max`) doesn't need any roles or privileges except `CREATE` on the database containing the schema. And the current user and current/old owner of the schema (`root`) needs to have the role of the new owner (`max`). Hence the need to grant the role `max` to `root`.

----

> Also, should the parenthetical be `(in this case, `admin`)` since that's the role of the current owner? If that's the case, the next SQL statement should be `GRANT max to admin` right?

It's the current user (`root`) that needs to be a member of the new owner's role (`max`). Since `root` is the current user, you need to grant `max` to `root`. 

IIUC, users and roles are kind of the same thing (e.g., `CREATE USER` and `CREATE ROLE` are aliases). A user has privileges. That user can be operationalized as a "role". `root` is a member of the `admin` role, which just means that `root` has all of the privileges of the `root` user *and* all of the privileges of the `admin` user. When you grant a user the "role" of another user, you just copy those privileges over to that user. Very confusing haha. @arulajmani does that sounds correct?
___
*[v20.2/create-schema.md, line 25 at r3](https://reviewable.io/reviews/cockroachdb/docs/8273#-MI-gme45vTpWhuqEh-8:-MI08H_aEi2dk-rcEm_S:b-d22waz) ([raw file](https://github.com/cockroachdb/docs/blob/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v20.2/create-schema.md#L25)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Link to string.html?
</blockquote></details>

Same response as above.
___
*[v20.2/create-schema.md, line 275 at r3](https://reviewable.io/reviews/cockroachdb/docs/8273#-MI-hZiA0BmnU664HIFh:-MI08dN2Dnqk7rXEOsw3:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v20.2/create-schema.md#L275)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

nit: end with a `:`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-24 18:14 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d7473e402dd979dd0e72d4d66069cca37fb1753c/

Edited pages:
- [v19.2/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d7473e402dd979dd0e72d4d66069cca37fb1753c/v19.2/sql-feature-support.html)
- [v19.2/sql-name-resolution.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d7473e402dd979dd0e72d4d66069cca37fb1753c/v19.2/sql-name-resolution.html)
- [v20.1/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d7473e402dd979dd0e72d4d66069cca37fb1753c/v20.1/sql-feature-support.html)
- [v20.1/sql-name-resolution.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d7473e402dd979dd0e72d4d66069cca37fb1753c/v20.1/sql-name-resolution.html)
- [v20.2/alter-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d7473e402dd979dd0e72d4d66069cca37fb1753c/v20.2/alter-schema.html)
- [v20.2/create-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d7473e402dd979dd0e72d4d66069cca37fb1753c/v20.2/create-schema.html)
- [v20.2/detailed-sql-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d7473e402dd979dd0e72d4d66069cca37fb1753c/v20.2/detailed-sql-support.html)
- [v20.2/drop-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d7473e402dd979dd0e72d4d66069cca37fb1753c/v20.2/drop-schema.html)
- [v20.2/show-schemas.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d7473e402dd979dd0e72d4d66069cca37fb1753c/v20.2/show-schemas.html)
- [v20.2/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d7473e402dd979dd0e72d4d66069cca37fb1753c/v20.2/sql-feature-support.html)
- [v20.2/sql-name-resolution.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d7473e402dd979dd0e72d4d66069cca37fb1753c/v20.2/sql-name-resolution.html)
- [v20.2/sql-statements.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d7473e402dd979dd0e72d4d66069cca37fb1753c/v20.2/sql-statements.html)

2020-09-24 19:07 UTC, lucy-zhang reviewed
Deferring to @arulajmani for details on privileges.

> Reviewed 1 of 1 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8273#-:-MI0Vf-y1R_bNP-ksYOS:bl133lu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @ericharmeling, and @lnhsingh)

___
*[v20.2/alter-schema.md, line 20 at r3](https://reviewable.io/reviews/cockroachdb/docs/8273#-MI-_U307s9KA3Pq9Jmn:-MI0UW6O-U67oBIAqTuT:b-3bmua5) ([raw file](https://github.com/cockroachdb/docs/blob/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v20.2/alter-schema.md#L20)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

I think the new schema name must follow the same rules as the new table name in `RENAME TABLE`. Updated this description in a new commit.

@lucy-zhang 
Does this look correct?
</blockquote></details>

Unfortunately referring to schemas as `database.schema` doesn't work. It's only possible to refer to schemas in the current database. (This will likely be improved in 21.1.)

I think this is potentially confusing enough to users that it's worth highlighting (here and in all the new schema-related syntax). I should have mentioned that before.
___
*[v20.2/alter-schema.md, line 21 at r3](https://reviewable.io/reviews/cockroachdb/docs/8273#-MI-_BkwCxkP9glxwD7w:-MI0V-DLCvHkMwQfrSxL:bf3hwht) ([raw file](https://github.com/cockroachdb/docs/blob/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v20.2/alter-schema.md#L21)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

I'm not sure the `STRING` page will help here, since that page is about column data types rather than string literals. I linked instead to the wikipedia page for "String literal" (https://en.wikipedia.org/wiki/String_literal).
</blockquote></details>

I think this should just say `You can specify the new owner by name or`...

Same goes for the other usages.
___
*[v20.2/create-schema.md, line 108 at r5](https://reviewable.io/reviews/cockroachdb/docs/8273#-MI0V_a51mW7nGgvnQeB:-MI0V_a51mW7nGgvnQeC:bmg8uph) ([raw file](https://github.com/cockroachdb/docs/blob/d7473e402dd979dd0e72d4d66069cca37fb1753c/v20.2/create-schema.md#L108)):*
> ```Markdown
> ~~~
> 
> ### Create two tables of the same name in the same schema
> ```

`in different schemas`


<!-- Sent from Reviewable.io -->

2020-09-24 20:53 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/665e95c8b232806d54461d4de5e9e8a2a5f525e6/

Edited pages:
- [v19.2/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/665e95c8b232806d54461d4de5e9e8a2a5f525e6/v19.2/sql-feature-support.html)
- [v19.2/sql-name-resolution.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/665e95c8b232806d54461d4de5e9e8a2a5f525e6/v19.2/sql-name-resolution.html)
- [v20.1/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/665e95c8b232806d54461d4de5e9e8a2a5f525e6/v20.1/sql-feature-support.html)
- [v20.1/sql-name-resolution.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/665e95c8b232806d54461d4de5e9e8a2a5f525e6/v20.1/sql-name-resolution.html)
- [v20.2/alter-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/665e95c8b232806d54461d4de5e9e8a2a5f525e6/v20.2/alter-schema.html)
- [v20.2/create-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/665e95c8b232806d54461d4de5e9e8a2a5f525e6/v20.2/create-schema.html)
- [v20.2/detailed-sql-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/665e95c8b232806d54461d4de5e9e8a2a5f525e6/v20.2/detailed-sql-support.html)
- [v20.2/drop-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/665e95c8b232806d54461d4de5e9e8a2a5f525e6/v20.2/drop-schema.html)
- [v20.2/show-schemas.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/665e95c8b232806d54461d4de5e9e8a2a5f525e6/v20.2/show-schemas.html)
- [v20.2/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/665e95c8b232806d54461d4de5e9e8a2a5f525e6/v20.2/sql-feature-support.html)
- [v20.2/sql-name-resolution.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/665e95c8b232806d54461d4de5e9e8a2a5f525e6/v20.2/sql-name-resolution.html)
- [v20.2/sql-statements.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/665e95c8b232806d54461d4de5e9e8a2a5f525e6/v20.2/sql-statements.html)

2020-09-24 20:58 UTC, ericharmeling reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8273)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @lnhsingh, and @lucy-zhang)

___
*[v20.2/alter-schema.md, line 20 at r3](https://reviewable.io/reviews/cockroachdb/docs/8273#-MI-_U307s9KA3Pq9Jmn:-MI0n4D75lCESVcB_oK-:b4pkyd5) ([raw file](https://github.com/cockroachdb/docs/blob/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v20.2/alter-schema.md#L20)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Unfortunately referring to schemas as `database.schema` doesn't work. It's only possible to refer to schemas in the current database. (This will likely be improved in 21.1.)

I think this is potentially confusing enough to users that it's worth highlighting (here and in all the new schema-related syntax). I should have mentioned that before.
</blockquote></details>

Thanks @lucy-zhang !

Updated `ALTER SCHEMA`, `CREATE SCHEMA`, and `DROP SCHEMA` pages.
___
*[v20.2/alter-schema.md, line 21 at r3](https://reviewable.io/reviews/cockroachdb/docs/8273#-MI-_BkwCxkP9glxwD7w:-MI0rJMYACumCjdjQlqT:b-896fja) ([raw file](https://github.com/cockroachdb/docs/blob/4a7cc46373fe8e85f1a28b511bedb9fb233053bb/v20.2/alter-schema.md#L21)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I think this should just say `You can specify the new owner by name or`...

Same goes for the other usages.
</blockquote></details>

Done!
___
*[v20.2/create-schema.md, line 108 at r5](https://reviewable.io/reviews/cockroachdb/docs/8273#-MI0V_a51mW7nGgvnQeB:-MI0rWCJ52kFJfeP9B5C:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/d7473e402dd979dd0e72d4d66069cca37fb1753c/v20.2/create-schema.md#L108)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

`in different schemas`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-24 21:04 UTC, lucy-zhang requested changes
> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8273)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @ericharmeling, and @lnhsingh)

___
*[v20.2/create-schema.md, line 108 at r6](https://reviewable.io/reviews/cockroachdb/docs/8273#-MI0vY5N7lqHUWZVT_Ud:-MI0vY5N7lqHUWZVT_Ue:blrigps) ([raw file](https://github.com/cockroachdb/docs/blob/665e95c8b232806d54461d4de5e9e8a2a5f525e6/v20.2/create-schema.md#L108)):*
> ```Markdown
> ~~~
> 
> ### Create two tables of the same name in the different schemas
> ```

I don't think you need `the`


<!-- Sent from Reviewable.io -->

2020-09-24 21:05 UTC, lucy-zhang approved these changes
Wait, I meant to approve it (aside from that nit).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8273#-:-MI0vjCLDl4dRH-Q41Lq:b-8fhb0i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @ericharmeling, and @lnhsingh)



<!-- Sent from Reviewable.io -->

2020-09-24 21:16 UTC, ericharmeling reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8273)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @lnhsingh, and @lucy-zhang)

___
*[v20.2/create-schema.md, line 108 at r6](https://reviewable.io/reviews/cockroachdb/docs/8273#-MI0vY5N7lqHUWZVT_Ud:-MI0yMOmBYDfgCgoBhBB:bhmf0a6) ([raw file](https://github.com/cockroachdb/docs/blob/665e95c8b232806d54461d4de5e9e8a2a5f525e6/v20.2/create-schema.md#L108)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I don't think you need `the`
</blockquote></details>

Agh! Fixed. Thanks!


<!-- Sent from Reviewable.io -->

2020-09-24 21:20 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eca3a88c084899a232db6079a115f8c89e2f45a4/

Edited pages:
- [v19.2/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eca3a88c084899a232db6079a115f8c89e2f45a4/v19.2/sql-feature-support.html)
- [v19.2/sql-name-resolution.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eca3a88c084899a232db6079a115f8c89e2f45a4/v19.2/sql-name-resolution.html)
- [v20.1/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eca3a88c084899a232db6079a115f8c89e2f45a4/v20.1/sql-feature-support.html)
- [v20.1/sql-name-resolution.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eca3a88c084899a232db6079a115f8c89e2f45a4/v20.1/sql-name-resolution.html)
- [v20.2/alter-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eca3a88c084899a232db6079a115f8c89e2f45a4/v20.2/alter-schema.html)
- [v20.2/create-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eca3a88c084899a232db6079a115f8c89e2f45a4/v20.2/create-schema.html)
- [v20.2/detailed-sql-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eca3a88c084899a232db6079a115f8c89e2f45a4/v20.2/detailed-sql-support.html)
- [v20.2/drop-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eca3a88c084899a232db6079a115f8c89e2f45a4/v20.2/drop-schema.html)
- [v20.2/show-schemas.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eca3a88c084899a232db6079a115f8c89e2f45a4/v20.2/show-schemas.html)
- [v20.2/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eca3a88c084899a232db6079a115f8c89e2f45a4/v20.2/sql-feature-support.html)
- [v20.2/sql-name-resolution.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eca3a88c084899a232db6079a115f8c89e2f45a4/v20.2/sql-name-resolution.html)
- [v20.2/sql-statements.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eca3a88c084899a232db6079a115f8c89e2f45a4/v20.2/sql-statements.html)

2020-09-28 13:57 UTC, ericharmeling commented
@arulajmani 

If you've got no objections to the privileges-related docs here (see https://github.com/cockroachdb/docs/pull/8273#pullrequestreview-495828951), then I'm going to merge this.

2020-09-28 16:13 UTC, merged