Materialized views
cockroachdb/docs pull request #8445
Opened 2020-09-22 20:53 UTC by ericharmeling

Fixes #8254. 
Fixes #8121. 
Fixes #8334. 
Fixes #8358. 

- Updated `CREATE VIEW`, `ALTER VIEW`, and `DROP VIEW` diagrams.
- Updated Views page examples.
- Added new "Materialized views" section to Views page, with examples.
- Added new `REFRESH` syntax page, with examples. 
*Note that this page pilots the new approach to using help text for SQL syntax!*

2020-09-22 20:53 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/8445)
<!-- Reviewable:end -->

2020-09-22 20:58 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c667ec56b6aea90dcb3f6f8a58abdd9975d5900f/

Edited pages:
- [v20.2/alter-view.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c667ec56b6aea90dcb3f6f8a58abdd9975d5900f/v20.2/alter-view.html)
- [v20.2/create-view.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c667ec56b6aea90dcb3f6f8a58abdd9975d5900f/v20.2/create-view.html)
- [v20.2/drop-view.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c667ec56b6aea90dcb3f6f8a58abdd9975d5900f/v20.2/drop-view.html)
- [v20.2/migrate-from-oracle.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c667ec56b6aea90dcb3f6f8a58abdd9975d5900f/v20.2/migrate-from-oracle.html)
- [v20.2/refresh.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c667ec56b6aea90dcb3f6f8a58abdd9975d5900f/v20.2/refresh.html)
- [v20.2/sql-statements.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c667ec56b6aea90dcb3f6f8a58abdd9975d5900f/v20.2/sql-statements.html)
- [v20.2/views.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c667ec56b6aea90dcb3f6f8a58abdd9975d5900f/v20.2/views.html)

2020-09-22 21:05 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cd0bf04f36e6c7f6c58f78de90d974a0a06b569b/

Edited pages:
- [v20.2/alter-view.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cd0bf04f36e6c7f6c58f78de90d974a0a06b569b/v20.2/alter-view.html)
- [v20.2/create-view.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cd0bf04f36e6c7f6c58f78de90d974a0a06b569b/v20.2/create-view.html)
- [v20.2/drop-view.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cd0bf04f36e6c7f6c58f78de90d974a0a06b569b/v20.2/drop-view.html)
- [v20.2/migrate-from-oracle.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cd0bf04f36e6c7f6c58f78de90d974a0a06b569b/v20.2/migrate-from-oracle.html)
- [v20.2/refresh.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cd0bf04f36e6c7f6c58f78de90d974a0a06b569b/v20.2/refresh.html)
- [v20.2/sql-statements.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cd0bf04f36e6c7f6c58f78de90d974a0a06b569b/v20.2/sql-statements.html)
- [v20.2/views.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cd0bf04f36e6c7f6c58f78de90d974a0a06b569b/v20.2/views.html)

2020-10-02 20:56 UTC, solongordon requested changes
I wonder if it would be worth saying something about why users might choose a materialized view over a regular view. Basically that they can offer better performance at the expense of additional storage and the data being up-to-date.

> Reviewed 9 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8445#-:-MIf5A34BW-DWHKT0bWv:bbbud51)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @solongordon)

___
*[v20.2/migrate-from-oracle.md, line 382 at r1](https://reviewable.io/reviews/cockroachdb/docs/8445#-MIf-zgd9pMFa9J4_0ql:-MIf-zgd9pMFa9J4_0qm:b-lgxazs) ([raw file](https://github.com/cockroachdb/docs/blob/a4e467988f4c50bc6c69948a09a157f2e8bcf135/v20.2/migrate-from-oracle.md#L382)):*
> ```Markdown
> - [Views](views.html)
> 
>     CockroachDB does not have a materialized view implementation.
> ```

I wonder if we should still specify that we do not support materialized views which are refreshed on commit.
___
*[v20.2/refresh.md, line 11 at r1](https://reviewable.io/reviews/cockroachdb/docs/8445#-MIf2id8AdBIfrfK1bod:-MIf2id8AdBIfrfK1boe:bgt9e0k) ([raw file](https://github.com/cockroachdb/docs/blob/cd0bf04f36e6c7f6c58f78de90d974a0a06b569b/v20.2/refresh.md#L11)):*
> ```Markdown
> ## Required privileges
> 
> The user must have the `SELECT` [privilege](authorization.html#assign-privileges) on the materialized view.
> ```

Interesting, seems like there are two problems here: 1) Postgres says only the owner should be able to refresh 2) it doesn't seem like we enforce that the user even has SELECT privileges. I opened https://github.com/cockroachdb/cockroach/issues/55191.


<!-- Sent from Reviewable.io -->

2020-10-06 14:09 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3db4644cb02ed500a1b78a17f2a37ffaf9ab4968/

Edited pages:
- [v20.2/alter-view.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3db4644cb02ed500a1b78a17f2a37ffaf9ab4968/v20.2/alter-view.html)
- [v20.2/create-view.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3db4644cb02ed500a1b78a17f2a37ffaf9ab4968/v20.2/create-view.html)
- [v20.2/drop-view.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3db4644cb02ed500a1b78a17f2a37ffaf9ab4968/v20.2/drop-view.html)
- [v20.2/migrate-from-oracle.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3db4644cb02ed500a1b78a17f2a37ffaf9ab4968/v20.2/migrate-from-oracle.html)
- [v20.2/refresh.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3db4644cb02ed500a1b78a17f2a37ffaf9ab4968/v20.2/refresh.html)
- [v20.2/sql-statements.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3db4644cb02ed500a1b78a17f2a37ffaf9ab4968/v20.2/sql-statements.html)
- [v20.2/views.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3db4644cb02ed500a1b78a17f2a37ffaf9ab4968/v20.2/views.html)

2020-10-06 14:10 UTC, ericharmeling reviewed
@solongordon TFTR

I think I addressed all 3 of your comments. I have a remaining question re: privileges.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8445#-:-MIyEfEbEIaBUllQTcqk:b-ndg9r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[v20.2/migrate-from-oracle.md, line 382 at r1](https://reviewable.io/reviews/cockroachdb/docs/8445#-MIf-zgd9pMFa9J4_0ql:-MIyEeEl6ddWJQeRYSAU:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a4e467988f4c50bc6c69948a09a157f2e8bcf135/v20.2/migrate-from-oracle.md#L382)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I wonder if we should still specify that we do not support materialized views which are refreshed on commit.
</blockquote></details>

Done.
___
*[v20.2/refresh.md, line 11 at r1](https://reviewable.io/reviews/cockroachdb/docs/8445#-MIf2id8AdBIfrfK1bod:-MIyAG5u2WmSjlc3RH1L:bcwm57l) ([raw file](https://github.com/cockroachdb/docs/blob/cd0bf04f36e6c7f6c58f78de90d974a0a06b569b/v20.2/refresh.md#L11)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Interesting, seems like there are two problems here: 1) Postgres says only the owner should be able to refresh 2) it doesn't seem like we enforce that the user even has SELECT privileges. I opened https://github.com/cockroachdb/cockroach/issues/55191.
</blockquote></details>

@solongordon 

Good catch.

I'm in favor of documenting the privileges on this statement *as they should be*, and not as they are. Do we plan to require the user to be an owner of the view to refresh it?


<!-- Sent from Reviewable.io -->

2020-10-06 14:13 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/30b2203b6479736e9fd96d4c946a7183a69b847d/

Edited pages:
- [v20.2/alter-view.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/30b2203b6479736e9fd96d4c946a7183a69b847d/v20.2/alter-view.html)
- [v20.2/create-view.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/30b2203b6479736e9fd96d4c946a7183a69b847d/v20.2/create-view.html)
- [v20.2/drop-view.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/30b2203b6479736e9fd96d4c946a7183a69b847d/v20.2/drop-view.html)
- [v20.2/migrate-from-oracle.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/30b2203b6479736e9fd96d4c946a7183a69b847d/v20.2/migrate-from-oracle.html)
- [v20.2/refresh.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/30b2203b6479736e9fd96d4c946a7183a69b847d/v20.2/refresh.html)
- [v20.2/sql-statements.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/30b2203b6479736e9fd96d4c946a7183a69b847d/v20.2/sql-statements.html)
- [v20.2/views.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/30b2203b6479736e9fd96d4c946a7183a69b847d/v20.2/views.html)

2020-10-12 16:28 UTC, ericharmeling commented
@solongordon 

Friendly follow-up review reminder :)

2020-10-12 16:31 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/81e8f909602948113108ed4b6dc9efb614bd1ce4/

Edited pages:
- [v20.2/alter-view.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/81e8f909602948113108ed4b6dc9efb614bd1ce4/v20.2/alter-view.html)
- [v20.2/create-view.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/81e8f909602948113108ed4b6dc9efb614bd1ce4/v20.2/create-view.html)
- [v20.2/drop-view.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/81e8f909602948113108ed4b6dc9efb614bd1ce4/v20.2/drop-view.html)
- [v20.2/migrate-from-oracle.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/81e8f909602948113108ed4b6dc9efb614bd1ce4/v20.2/migrate-from-oracle.html)
- [v20.2/refresh.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/81e8f909602948113108ed4b6dc9efb614bd1ce4/v20.2/refresh.html)
- [v20.2/sql-statements.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/81e8f909602948113108ed4b6dc9efb614bd1ce4/v20.2/sql-statements.html)
- [v20.2/views.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/81e8f909602948113108ed4b6dc9efb614bd1ce4/v20.2/views.html)

2020-10-19 13:33 UTC, ericharmeling commented
@solongordon
Passing this to writer review. (We can always make revisions post-merge if need be.)

2020-10-19 13:34 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/faf1dcb10941d0865235e70ffe8b2da761d6995a/

Edited pages:
- [v20.2/alter-view.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/faf1dcb10941d0865235e70ffe8b2da761d6995a/v20.2/alter-view.html)
- [v20.2/create-view.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/faf1dcb10941d0865235e70ffe8b2da761d6995a/v20.2/create-view.html)
- [v20.2/drop-view.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/faf1dcb10941d0865235e70ffe8b2da761d6995a/v20.2/drop-view.html)
- [v20.2/migrate-from-oracle.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/faf1dcb10941d0865235e70ffe8b2da761d6995a/v20.2/migrate-from-oracle.html)
- [v20.2/refresh.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/faf1dcb10941d0865235e70ffe8b2da761d6995a/v20.2/refresh.html)
- [v20.2/sql-statements.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/faf1dcb10941d0865235e70ffe8b2da761d6995a/v20.2/sql-statements.html)
- [v20.2/views.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/faf1dcb10941d0865235e70ffe8b2da761d6995a/v20.2/views.html)

2020-10-19 16:40 UTC, lnhsingh reviewed
A few nits but otherwise LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8445#-:-MK0ir4z2rBhzzlRC4mS:b51zjt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @lnhsingh, and @solongordon)

___
*[v20.2/refresh.md, line 30 at r2](https://reviewable.io/reviews/cockroachdb/docs/8445#-MK0hksT6TkziAUwhjDp:-MK0hksT6TkziAUwhjDq:b-5j78oi) ([raw file](https://github.com/cockroachdb/docs/blob/faf1dcb10941d0865235e70ffe8b2da761d6995a/v20.2/refresh.md#L30)):*
> ```Markdown
> `WITH NO DATA` | Drop the query results of the materialized view from storage.
> `WITH DATA` | (*Default behavior*) Refresh the stored query results.
> `CONCURRENTLY` | (*Default behavior*) This keyword is a no-op, added for PostgreSQL compatibility. All materialized views are refreshed concurrently with other jobs.
> ```

nit: I think `CONCURRENTLY` should be the first row in the table since it appears first in the syntax
___
*[v20.2/views.md, line 9 at r2](https://reviewable.io/reviews/cockroachdb/docs/8445#-MK0iDblCYvHCe6hAK8P:-MK0iDbm3worRyjJH8os:bls710i) ([raw file](https://github.com/cockroachdb/docs/blob/faf1dcb10941d0865235e70ffe8b2da761d6995a/v20.2/views.md#L9)):*
> ```Markdown
> A view is a stored and named [selection query](selection-queries.html). By default, CockroachDB's views are **dematerialized**: they do not store the results of the underlying queries. Instead, the underlying query is executed anew every time the view is used.
> 
> <span class="version-tag">New in v20.2:</span> CockroachDB also supports **materialized views**. [Materialized views](#materialized-views) are views that store their selection query results.
> ```

nit: The first mention of `materialized views` (the one that's bolded here) should also be the link 
___
*[v20.2/views.md, line 425 at r2](https://reviewable.io/reviews/cockroachdb/docs/8445#-MK0iWb60d2CXiIhR-RJ:-MK0iWb60d2CXiIhR-RK:b-sh0ipk) ([raw file](https://github.com/cockroachdb/docs/blob/faf1dcb10941d0865235e70ffe8b2da761d6995a/v20.2/views.md#L425)):*
> ```Markdown
> <span class="version-tag">New in v20.2:</span> CockroachDB supports [materialized views](https://en.wikipedia.org/wiki/Materialized_view). Materialized views are views that store the results of their underlying queries.
> 
> When you [select](selection-queries.html) from a materialized view, the stored query data that is returned might be out-of-date. This contrasts with a standard (i.e. "dematerialized") view, which runs its underlying query every time it is used, returning the latest results. In order to get the latest results from a materialized view, you must [refresh the view](refresh.html), and then select from it.
> ```

nit: `i.e.,`


<!-- Sent from Reviewable.io -->

2020-10-19 19:44 UTC, ericharmeling reviewed
TFTR @lnhsingh !

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8445#-:-MK1NzPdC8GhSfVCLGqG:bhjhpnt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[v20.2/refresh.md, line 30 at r2](https://reviewable.io/reviews/cockroachdb/docs/8445#-MK0hksT6TkziAUwhjDp:-MK1NWdB7ZQ2Yy1is5xY:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/faf1dcb10941d0865235e70ffe8b2da761d6995a/v20.2/refresh.md#L30)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

nit: I think `CONCURRENTLY` should be the first row in the table since it appears first in the syntax
</blockquote></details>

Done.
___
*[v20.2/views.md, line 9 at r2](https://reviewable.io/reviews/cockroachdb/docs/8445#-MK0iDblCYvHCe6hAK8P:-MK1NkgMDAenzH57Lw0_:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/faf1dcb10941d0865235e70ffe8b2da761d6995a/v20.2/views.md#L9)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

nit: The first mention of `materialized views` (the one that's bolded here) should also be the link 
</blockquote></details>

Done.
___
*[v20.2/views.md, line 425 at r2](https://reviewable.io/reviews/cockroachdb/docs/8445#-MK0iWb60d2CXiIhR-RJ:-MK1Ny7t4uWQ3NRXO-K2:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/faf1dcb10941d0865235e70ffe8b2da761d6995a/v20.2/views.md#L425)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

nit: `i.e.,`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-19 19:48 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/56d04946acec29e92b22e82eeb0e166f2b5474c3/

Edited pages:
- [v20.2/alter-view.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/56d04946acec29e92b22e82eeb0e166f2b5474c3/v20.2/alter-view.html)
- [v20.2/create-view.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/56d04946acec29e92b22e82eeb0e166f2b5474c3/v20.2/create-view.html)
- [v20.2/drop-view.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/56d04946acec29e92b22e82eeb0e166f2b5474c3/v20.2/drop-view.html)
- [v20.2/migrate-from-oracle.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/56d04946acec29e92b22e82eeb0e166f2b5474c3/v20.2/migrate-from-oracle.html)
- [v20.2/refresh.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/56d04946acec29e92b22e82eeb0e166f2b5474c3/v20.2/refresh.html)
- [v20.2/sql-statements.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/56d04946acec29e92b22e82eeb0e166f2b5474c3/v20.2/sql-statements.html)
- [v20.2/views.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/56d04946acec29e92b22e82eeb0e166f2b5474c3/v20.2/views.html)

2020-10-19 19:49 UTC, merged