ALTER TABLE ... OWNER TO and ALTER DATABASE ... OWNER TO
cockroachdb/docs pull request #8519
Opened 2020-09-30 20:28 UTC by ericharmeling

Fixes #8300.  
Fixes #8316. 

- Added `OWNER TO` page.

In the future, we should look into knocking subcommands down a level in the ToC. For example, placing a page like `OWNER TO` beneath `ALTER TABLE`.

2020-09-30 20:28 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/8519)
<!-- Reviewable:end -->

2020-09-30 20:31 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4c1383f4469e9aa023d927e3d7d3eff4c4815d05/

Edited pages:
- [v20.2/alter-database.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4c1383f4469e9aa023d927e3d7d3eff4c4815d05/v20.2/alter-database.html)
- [v20.2/alter-table.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4c1383f4469e9aa023d927e3d7d3eff4c4815d05/v20.2/alter-table.html)
- [v20.2/owner-to.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4c1383f4469e9aa023d927e3d7d3eff4c4815d05/v20.2/owner-to.html)

2020-10-07 18:04 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7bd2fd5a107d81b246054a993ae6ddc3d775f218/

Edited pages:
- [v20.2/alter-database.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7bd2fd5a107d81b246054a993ae6ddc3d775f218/v20.2/alter-database.html)
- [v20.2/alter-table.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7bd2fd5a107d81b246054a993ae6ddc3d775f218/v20.2/alter-table.html)
- [v20.2/owner-to.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7bd2fd5a107d81b246054a993ae6ddc3d775f218/v20.2/owner-to.html)

2020-10-12 14:44 UTC, ericharmeling commented
@solongordon 

Friendly ping on review :)

2020-10-15 16:05 UTC, solongordon requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8519)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @solongordon)

___
*[v20.2/owner-to.md, line 15 at r1](https://reviewable.io/reviews/cockroachdb/docs/8519#-MIfAvsKBIAwN4XqyUha:-MIfAvsKBIAwN4XqyUhb:btill2d) ([raw file](https://github.com/cockroachdb/docs/blob/4c1383f4469e9aa023d927e3d7d3eff4c4815d05/v20.2/owner-to.md#L15)):*
> ```Markdown
> ## Required privileges
> 
> - To change the owner of a database, the user must be the current owner of the database, and a member of the new owner [role](authorization.html#roles).
> ```

The user must also have the CREATEDB role privilege.
___
*[v20.2/owner-to.md, line 37 at r1](https://reviewable.io/reviews/cockroachdb/docs/8519#-MIfBRNh7mWdHl4mnrCF:-MIfBRNh7mWdHl4mnrCG:bp2ouko) ([raw file](https://github.com/cockroachdb/docs/blob/4c1383f4469e9aa023d927e3d7d3eff4c4815d05/v20.2/owner-to.md#L37)):*
> ```Markdown
> ----------|------------
> `name` | The name of the table or database.
> `newowner` | The name of the new owner. You can specify the new owner by name or with the [`CURRENT_USER` or `SESSION_USER` keywords](functions-and-operators.html#special-syntax-forms).
> ```

CURRENT_USER/SESSION_USER is currently not working and I don't expect this will be fixed for 20.2, so maybe let's call it out yet. See https://github.com/cockroachdb/cockroach/issues/54696.
___
*[v20.2/owner-to.md, line 64 at r1](https://reviewable.io/reviews/cockroachdb/docs/8519#-MIfBjLvDZj8zRza3bUF:-MIfBjLvDZj8zRza3bUG:b7oew97) ([raw file](https://github.com/cockroachdb/docs/blob/4c1383f4469e9aa023d927e3d7d3eff4c4815d05/v20.2/owner-to.md#L64)):*
> ```Markdown
> ~~~
> 
> To verify that the owner is now `max`, [open a SQL shell](cockroach-sql.html) to the running cluster, as the user `max`:
> ```

A nicer way to verify might be to query `pg_catalog`:
```
SELECT rolname FROM pg_database d JOIN pg_roles r ON d.datdba = r.oid WHERE datname = 'movr';
```
We'll also be adding an owner column to the SHOW DATABASES command but this might not be in until 20.2.1.


<!-- Sent from Reviewable.io -->

2020-10-15 16:07 UTC, solongordon reviewed
Do we describe elsewhere what it actually means to be an owner?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8519#-:-MJh0-oq-YaN7bra2Xib:b-39rjiq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @solongordon)



<!-- Sent from Reviewable.io -->

2020-10-15 17:20 UTC, ericharmeling reviewed
TFTR, @solongordon !

@amruta-ranade is working on object ownership docs for this release. The tracking issue is here: https://github.com/cockroachdb/docs/issues/8153.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8519#-:-MJh6VNS7v3MZexiERma:b-hlm1e6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[v20.2/owner-to.md, line 15 at r1](https://reviewable.io/reviews/cockroachdb/docs/8519#-MIfAvsKBIAwN4XqyUha:-MJh7zxDEILM7Pnggdma:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/4c1383f4469e9aa023d927e3d7d3eff4c4815d05/v20.2/owner-to.md#L15)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

The user must also have the CREATEDB role privilege.
</blockquote></details>

Done.
___
*[v20.2/owner-to.md, line 37 at r1](https://reviewable.io/reviews/cockroachdb/docs/8519#-MIfBRNh7mWdHl4mnrCF:-MJh83ju8Vg66WpbUwQ6:b-usy7vm) ([raw file](https://github.com/cockroachdb/docs/blob/4c1383f4469e9aa023d927e3d7d3eff4c4815d05/v20.2/owner-to.md#L37)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

CURRENT_USER/SESSION_USER is currently not working and I don't expect this will be fixed for 20.2, so maybe let's call it out yet. See https://github.com/cockroachdb/cockroach/issues/54696.
</blockquote></details>

Done.

I also removed CURRENT_USER/SESSION_USER from `CREATE SCHEMA` and `ALTER SCHEMA`.
___
*[v20.2/owner-to.md, line 64 at r1](https://reviewable.io/reviews/cockroachdb/docs/8519#-MIfBjLvDZj8zRza3bUF:-MJhFJcE3DS5OMUjWmcn:b-vp093p) ([raw file](https://github.com/cockroachdb/docs/blob/4c1383f4469e9aa023d927e3d7d3eff4c4815d05/v20.2/owner-to.md#L64)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

A nicer way to verify might be to query `pg_catalog`:
```
SELECT rolname FROM pg_database d JOIN pg_roles r ON d.datdba = r.oid WHERE datname = 'movr';
```
We'll also be adding an owner column to the SHOW DATABASES command but this might not be in until 20.2.1.
</blockquote></details>

Done.

I also updated the table example below to use `SHOW TABLES`, which shows the owner.


<!-- Sent from Reviewable.io -->

2020-10-15 17:23 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ad4cca4de27a04633163fd29e8815b0622baf5a9/

Edited pages:
- [v20.2/alter-database.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ad4cca4de27a04633163fd29e8815b0622baf5a9/v20.2/alter-database.html)
- [v20.2/alter-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ad4cca4de27a04633163fd29e8815b0622baf5a9/v20.2/alter-schema.html)
- [v20.2/alter-table.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ad4cca4de27a04633163fd29e8815b0622baf5a9/v20.2/alter-table.html)
- [v20.2/create-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ad4cca4de27a04633163fd29e8815b0622baf5a9/v20.2/create-schema.html)
- [v20.2/owner-to.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ad4cca4de27a04633163fd29e8815b0622baf5a9/v20.2/owner-to.html)

2020-10-15 17:30 UTC, solongordon reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8519)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[v20.2/owner-to.md, line 64 at r1](https://reviewable.io/reviews/cockroachdb/docs/8519#-MIfBjLvDZj8zRza3bUF:-MJhISvV9s3PVZ2CSR_0:bag0xbe) ([raw file](https://github.com/cockroachdb/docs/blob/4c1383f4469e9aa023d927e3d7d3eff4c4815d05/v20.2/owner-to.md#L64)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

Done.

I also updated the table example below to use `SHOW TABLES`, which shows the owner.
</blockquote></details>

Hm, be careful because the change to add owner to `SHOW TABLES` and other `SHOW` commands is only on master and not slated for v20.2.0. I think we'll likely want to backport it for v20.2.1 though.


<!-- Sent from Reviewable.io -->

2020-10-15 17:37 UTC, ericharmeling reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8519)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[v20.2/owner-to.md, line 64 at r1](https://reviewable.io/reviews/cockroachdb/docs/8519#-MIfBjLvDZj8zRza3bUF:-MJhJuuGD69ZIxQnlhnL:bo3pt4c) ([raw file](https://github.com/cockroachdb/docs/blob/4c1383f4469e9aa023d927e3d7d3eff4c4815d05/v20.2/owner-to.md#L64)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Hm, be careful because the change to add owner to `SHOW TABLES` and other `SHOW` commands is only on master and not slated for v20.2.0. I think we'll likely want to backport it for v20.2.1 though.
</blockquote></details>

Oh ... good to know...*sigh*  (I need to revert https://github.com/cockroachdb/docs/pull/8584)


<!-- Sent from Reviewable.io -->

2020-10-15 17:45 UTC, ericharmeling reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8519)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[v20.2/owner-to.md, line 64 at r1](https://reviewable.io/reviews/cockroachdb/docs/8519#-MIfBjLvDZj8zRza3bUF:-MJhMIP03-ybouiYH0i7:bwe5erf) ([raw file](https://github.com/cockroachdb/docs/blob/4c1383f4469e9aa023d927e3d7d3eff4c4815d05/v20.2/owner-to.md#L64)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

Oh ... good to know...*sigh*  (I need to revert https://github.com/cockroachdb/docs/pull/8584)
</blockquote></details>

Thanks for calling this out!

Also, updated the example to query `pg_catalog` as well.


<!-- Sent from Reviewable.io -->

2020-10-15 17:48 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cce40979b76a21f31d0c76622a3d02f4f7d3b633/

Edited pages:
- [v20.2/alter-database.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cce40979b76a21f31d0c76622a3d02f4f7d3b633/v20.2/alter-database.html)
- [v20.2/alter-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cce40979b76a21f31d0c76622a3d02f4f7d3b633/v20.2/alter-schema.html)
- [v20.2/alter-table.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cce40979b76a21f31d0c76622a3d02f4f7d3b633/v20.2/alter-table.html)
- [v20.2/create-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cce40979b76a21f31d0c76622a3d02f4f7d3b633/v20.2/create-schema.html)
- [v20.2/owner-to.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cce40979b76a21f31d0c76622a3d02f4f7d3b633/v20.2/owner-to.html)

2020-10-15 18:57 UTC, solongordon approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8519)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @solongordon)

___
*[v20.2/owner-to.md, line 106 at r3](https://reviewable.io/reviews/cockroachdb/docs/8519#-MJhbl-W8t8OKyy2tkHA:-MJhbl-W8t8OKyy2tkHB:b58ak5t) ([raw file](https://github.com/cockroachdb/docs/blob/cce40979b76a21f31d0c76622a3d02f4f7d3b633/v20.2/owner-to.md#L106)):*
> ```Markdown
> ~~~
> 
> ~~~
> ```

Extra lines here maybe?


<!-- Sent from Reviewable.io -->

2020-10-15 19:27 UTC, ericharmeling reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8519)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[v20.2/owner-to.md, line 106 at r3](https://reviewable.io/reviews/cockroachdb/docs/8519#-MJhbl-W8t8OKyy2tkHA:-MJhiRih-2HFFUSFCCzF:b80k13) ([raw file](https://github.com/cockroachdb/docs/blob/cce40979b76a21f31d0c76622a3d02f4f7d3b633/v20.2/owner-to.md#L106)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Extra lines here maybe?
</blockquote></details>

Lines of prose? Or is the output looking off?


<!-- Sent from Reviewable.io -->

2020-10-15 19:30 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a4162625f0d8e87e9122614b1224760bf1c9b969/

Edited pages:
- [v20.2/alter-database.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a4162625f0d8e87e9122614b1224760bf1c9b969/v20.2/alter-database.html)
- [v20.2/alter-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a4162625f0d8e87e9122614b1224760bf1c9b969/v20.2/alter-schema.html)
- [v20.2/alter-table.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a4162625f0d8e87e9122614b1224760bf1c9b969/v20.2/alter-table.html)
- [v20.2/create-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a4162625f0d8e87e9122614b1224760bf1c9b969/v20.2/create-schema.html)
- [v20.2/owner-to.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a4162625f0d8e87e9122614b1224760bf1c9b969/v20.2/owner-to.html)

2020-10-15 20:48 UTC, lnhsingh reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8519#-:-MJi0LC16wT9X0CvhAAn:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lnhsingh and @solongordon)

___
*[v20.2/owner-to.md, line 106 at r3](https://reviewable.io/reviews/cockroachdb/docs/8519#-MJhbl-W8t8OKyy2tkHA:-MJi0HuX31YRMEKYVEoz:b-l70jfk) ([raw file](https://github.com/cockroachdb/docs/blob/cce40979b76a21f31d0c76622a3d02f4f7d3b633/v20.2/owner-to.md#L106)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

Lines of prose? Or is the output looking off?
</blockquote></details>

Output looks fine


<!-- Sent from Reviewable.io -->

2020-10-15 21:22 UTC, merged