update rolling upgrades guidance
cockroachdb/docs pull request #8615
Opened 2020-10-08 23:35 UTC by taroface

Fixes #6163.

- For non-orchestrated deployments, this uses guidance from @knz on determining that a node is ready to accept SQL and the next node can be stopped.
- For K8s deployments, uses the guidance from @DuskEagle in the linked issue.

@DuskEagle for the Kubernetes section, it seems the partition would have to be removed from the StatefulSet after the upgrade? Otherwise wouldn't any updates to the STS only affect a single pod? Can you advise on how this would be done?

Also, I am not 100% certain the Helm command is correct. Will need to test.

2020-10-08 23:36 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/8615)
<!-- Reviewable:end -->

2020-10-08 23:39 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/2610845d3a37a60ed16b62b3bd55475165938614/

Edited pages:
- [v20.1/admin-ui-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/2610845d3a37a60ed16b62b3bd55475165938614/v20.1/admin-ui-overview.html)
- [v20.1/upgrade-cockroach-version.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/2610845d3a37a60ed16b62b3bd55475165938614/v20.1/upgrade-cockroach-version.html)
- [v20.2/admin-ui-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/2610845d3a37a60ed16b62b3bd55475165938614/v20.2/admin-ui-overview.html)
- [v20.2/upgrade-cockroach-version.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/2610845d3a37a60ed16b62b3bd55475165938614/v20.2/upgrade-cockroach-version.html)

2020-10-09 07:44 UTC, knz approved these changes
Just a minor nit on my side. I'll let Joel evaluate the k8s guidance.

2020-10-09 07:44 UTC, knz commented on v20.2/upgrade-cockroach-version.md
> +    The command should complete. If it hangs, the node is not yet ready.
The command always complete. The text should explain "The command will automatically wait to complete until the node is ready."

2020-10-12 14:59 UTC, DuskEagle requested changes
Helm instructions LGTM.

> @DuskEagle for the Kubernetes section, it seems the partition would have to be removed from the StatefulSet after the upgrade? Otherwise wouldn't any updates to the STS only affect a single pod? Can you advise on how this would be done?

No, because the partition value ensures that any pods numbered **greater than or equal to** the partition value are updated. For example, if the partition value is 1, and we have pods `cockroachdb-0`, `cockroachdb-1`, and `cockroachdb-2`, then `cockroachdb-1` and `cockroachdb-2` will be updated. 

If the partition value is 0, then that implies all pods will be updated.

It is also fine to remove the partition value after the update is finished; it's just not necessary.

2020-10-12 14:59 UTC, DuskEagle commented on v20.2/upgrade-cockroach-version.md
> +    The node should have at least 70% of the [memory usage](admin-ui-cluster-overview-page.html#node-details) you observed before stopping the node.
I don't think this advice is sound, it depends too much on how long the node was running previously and what the workload was on the node before it was restarted. For example, if the node was running for long enough that the RocksDB/Pebble cache was full, but there was relatively little load on the cluster, the memory usage on the cluster could be expected to be much lower after starting the node again.

2020-10-12 18:27 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/357dc85be9184adab4474ed6bb6b420cf8a98c3a/

Edited pages:
- [v20.1/admin-ui-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/357dc85be9184adab4474ed6bb6b420cf8a98c3a/v20.1/admin-ui-overview.html)
- [v20.1/upgrade-cockroach-version.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/357dc85be9184adab4474ed6bb6b420cf8a98c3a/v20.1/upgrade-cockroach-version.html)
- [v20.2/admin-ui-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/357dc85be9184adab4474ed6bb6b420cf8a98c3a/v20.2/admin-ui-overview.html)
- [v20.2/upgrade-cockroach-version.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/357dc85be9184adab4474ed6bb6b420cf8a98c3a/v20.2/upgrade-cockroach-version.html)

2020-10-12 21:59 UTC, taroface reviewed
Got it. I added this clarification to the doc.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8615#-:-MJSzMapC3J6P7tIO7B2:bqy5xp5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DuskEagle and @knz)

___
*[v20.2/upgrade-cockroach-version.md, line 188 at r1](https://reviewable.io/reviews/cockroachdb/docs/8615#-MJ9ZZM-QaM0QG4Yz00U-r1-188:-MJSzci-EN37zPqXGUvs:b-7i85n1) ([raw file](https://github.com/cockroachdb/docs/blob/2610845d3a37a60ed16b62b3bd55475165938614/v20.2/upgrade-cockroach-version.md#L188)):*
<details><summary><i>Previously, DuskEagle (Joel Kenny) wrote…</i></summary><blockquote>

I don't think this advice is sound, it depends too much on how long the node was running previously and what the workload was on the node before it was restarted. For example, if the node was running for long enough that the RocksDB/Pebble cache was full, but there was relatively little load on the cluster, the memory usage on the cluster could be expected to be much lower after starting the node again.
</blockquote></details>

Okay, will strike the memory usage from the guidance.
___
*[v20.2/upgrade-cockroach-version.md, line 208 at r1](https://reviewable.io/reviews/cockroachdb/docs/8615#-MJ9ZZM-QaM0QG4Yz00U-r1-208:-MJT27WqEPXqyb457vQo:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/2610845d3a37a60ed16b62b3bd55475165938614/v20.2/upgrade-cockroach-version.md#L208)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

The command always completes. The text should explain "The command will automatically wait to complete until the node is ready."
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-13 16:17 UTC, Amruta-Ranade approved these changes

2020-10-13 16:17 UTC, Amruta-Ranade commented on v20.2/upgrade-cockroach-version.md
> +    Unless there are tens of thousands of ranges on the node, it's usually sufficient to wait at least one minute. To be certain that the node is ready, run the following command:
nit:"at least" seems contradictory to what the statement seems to convey.

2020-10-13 16:17 UTC, Amruta-Ranade commented on _includes/v20.1/orchestration/kubernetes-upgrade-cluster.md
> +1. After the pod has been restarted with the new image, get a shell into the pod and start the CockroachDB [built-in SQL client](cockroach-sql.html):
The numbering seems off here but renders correctly ¯\_(ツ)_/¯

2020-10-13 16:17 UTC, Amruta-Ranade commented on _includes/v20.1/orchestration/kubernetes-upgrade-cluster.md
> +1. Add a [partition](https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#staging-an-update) to the `updateStrategy` defined in the StatefulSet. Only the pods numbered greate
nit: Should this be "the `updateStrategy` field"?

2020-10-13 16:17 UTC, Amruta-Ranade commented on _includes/v20.1/orchestration/kubernetes-upgrade-cluster.md
> +1. Kick off the upgrade process by changing the desired Docker image:
Suggestion: "desired Docker image" > "Docker image used in the CockroachDB StatefulSet "

2020-10-13 19:22 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f0028336feb4f7eae574a4151368f7ad677acb47/

Edited pages:
- [v20.1/admin-ui-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f0028336feb4f7eae574a4151368f7ad677acb47/v20.1/admin-ui-overview.html)
- [v20.1/upgrade-cockroach-version.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f0028336feb4f7eae574a4151368f7ad677acb47/v20.1/upgrade-cockroach-version.html)
- [v20.2/admin-ui-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f0028336feb4f7eae574a4151368f7ad677acb47/v20.2/admin-ui-overview.html)
- [v20.2/upgrade-cockroach-version.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f0028336feb4f7eae574a4151368f7ad677acb47/v20.2/upgrade-cockroach-version.html)

2020-10-13 20:53 UTC, taroface reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8615)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Amruta-Ranade, @DuskEagle, and @knz)

___
*[_includes/v20.1/orchestration/kubernetes-upgrade-cluster.md, line 84 at r2](https://reviewable.io/reviews/cockroachdb/docs/8615#-MJ9ZZM-QaM0QG4Yz00P-r2-84:-MJYNjV8Ec2Qn-e6iEF0:b-bqi2nw) ([raw file](https://github.com/cockroachdb/docs/blob/357dc85be9184adab4474ed6bb6b420cf8a98c3a/_includes/v20.1/orchestration/kubernetes-upgrade-cluster.md#L84)):*
<details><summary><i>Previously, Amruta-Ranade (Amruta Ranade) wrote…</i></summary><blockquote>

nit: Should this be "the `updateStrategy` field"?
</blockquote></details>

Hmm good point. I'm just going to make this "update strategy" to avoid getting too far into the weeds.
___
*[_includes/v20.1/orchestration/kubernetes-upgrade-cluster.md, line 108 at r2](https://reviewable.io/reviews/cockroachdb/docs/8615#-MJ9ZZM-QaM0QG4Yz00P-r2-108:-MJYO0HeD8nWo3Tp85eG:b1natol) ([raw file](https://github.com/cockroachdb/docs/blob/357dc85be9184adab4474ed6bb6b420cf8a98c3a/_includes/v20.1/orchestration/kubernetes-upgrade-cluster.md#L108)):*
<details><summary><i>Previously, Amruta-Ranade (Amruta Ranade) wrote…</i></summary><blockquote>

Suggestion: "desired Docker image" > "Docker image used in the CockroachDB StatefulSet "
</blockquote></details>

Perfect! Done.
___
*[_includes/v20.1/orchestration/kubernetes-upgrade-cluster.md, line 176 at r2](https://reviewable.io/reviews/cockroachdb/docs/8615#-MJ9ZZM-QaM0QG4Yz00P-r2-176:-MJYO3YpBXJyoKsaLffb:bpqk4ih) ([raw file](https://github.com/cockroachdb/docs/blob/357dc85be9184adab4474ed6bb6b420cf8a98c3a/_includes/v20.1/orchestration/kubernetes-upgrade-cluster.md#L176)):*
<details><summary><i>Previously, Amruta-Ranade (Amruta Ranade) wrote…</i></summary><blockquote>

The numbering seems off here but renders correctly ¯\_(ツ)_/¯
</blockquote></details>

Yeah, Markdown automatically uses correct numbering regardless of the number used. I think we settled on using `1.` throughout ordered lists as a docs practice. IMO this helps keep the numbering clear as steps are added and removed in updates.
___
*[v20.2/upgrade-cockroach-version.md, line 197 at r2](https://reviewable.io/reviews/cockroachdb/docs/8615#-MJ9ZZM-QaM0QG4Yz00U-r2-197:-MJYOevJ4MKhAcEUltLZ:bi2qzy1) ([raw file](https://github.com/cockroachdb/docs/blob/357dc85be9184adab4474ed6bb6b420cf8a98c3a/v20.2/upgrade-cockroach-version.md#L197)):*
<details><summary><i>Previously, Amruta-Ranade (Amruta Ranade) wrote…</i></summary><blockquote>

nit:"at least" seems contradictory to what the statement seems to convey. 
</blockquote></details>

Good point ... I removed this.


<!-- Sent from Reviewable.io -->

2020-10-29 22:40 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1db2b5fa023761dc2ee0c58ecd2d2ae7001db315/

Edited pages:
- [v20.1/admin-ui-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1db2b5fa023761dc2ee0c58ecd2d2ae7001db315/v20.1/admin-ui-overview.html)
- [v20.1/upgrade-cockroach-version.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1db2b5fa023761dc2ee0c58ecd2d2ae7001db315/v20.1/upgrade-cockroach-version.html)
- [v20.2/admin-ui-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1db2b5fa023761dc2ee0c58ecd2d2ae7001db315/v20.2/admin-ui-overview.html)
- [v20.2/upgrade-cockroach-version.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1db2b5fa023761dc2ee0c58ecd2d2ae7001db315/v20.2/upgrade-cockroach-version.html)

2020-10-29 22:42 UTC, merged