Add docs on spatial indexes
cockroachdb/docs pull request #8617
Opened 2020-10-09 17:14 UTC by rmloveland

Fixes #8563.

Addresses #7835, #7900, #7901, #7902, #7903, #8172, #8356, #8377, #8513, #8567.

Summary of changes:

- Add a new page 'Spatial Indexes' that:

  - Describes what they are and how they work at high and lower(ish)
    levels

  - Provides some examples of usage, including how to tune them to
    generate tighter or looser coverings with 'CREATE INDEX', as well as
    exploring potential coverings with 'st_s2covering'.

- Add links to/from 'CREATE INDEX', 'Indexes', and 'Inverted Indexes'
  pages.

- Also, add lots of cross-linking among various spatial pages,
  esp. where indexing is mentioned in the text thereof.

2020-10-09 17:15 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/8617)
<!-- Reviewable:end -->

2020-10-09 17:19 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1a563a0b0472b665b4befce5134e696cf57f3f76/

Edited pages:
- [v20.2/create-index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/create-index.html)
- [v20.2/indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/indexes.html)
- [v20.2/install-cockroachdb-spatial.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/install-cockroachdb-spatial.html)
- [v20.2/inverted-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/inverted-indexes.html)
- [v20.2/migrate-from-geojson.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/migrate-from-geojson.html)
- [v20.2/migrate-from-geopackage.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/migrate-from-geopackage.html)
- [v20.2/migrate-from-openstreetmap.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/migrate-from-openstreetmap.html)
- [v20.2/migrate-from-shapefiles.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/migrate-from-shapefiles.html)
- [v20.2/spatial-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-data.html)
- [v20.2/spatial-features.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-features.html)
- [v20.2/spatial-glossary.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-glossary.html)
- [v20.2/spatial-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.html)

2020-10-09 17:23 UTC, rmloveland commented
Hi Becca, Oliver, Sumeer:

Sorry to ping all of you - wasn't sure if it would be enough to get just one person's eyes - I think this doc could benefit from each of your perspectives, since it's kind of trying to be the all-singing all-dancing spatial indexes page (for now).

In addition to pointing out any errors, would appreciate suggestions on how to make this better so it's more helpful to users trying to understand stuff.

Thanks!

2020-10-09 17:35 UTC, otan commented
___
*[v20.2/spatial-indexes.md, line 130 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJDPdB60V_hd6OTOEIP:-MJDPdB60V_hd6OTOEIQ:bo9nhzb) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.md#L130)):*
> ```Markdown
> | `s2_max_level`   | 30                                            | The maximum level of S2 cell used in the covering. Allowed values: 1-30. Setting it to less than the default means that CockroachDB will be forced to generate coverings using larger cells.                                                |
> | `s2_max_cells`   | 4                                             | The maximum number of S2 cells used in the covering. Provides a limit on how much work is done exploring the possible coverings. Allowed values: 1-30. You may want to use higher values for odd-shaped regions such as skinny rectangles. |
> | `geometry_min_x` | Derived from SRID bounds, else `-(1 << 31)`   | Minimum X-value of the [spatial reference system](spatial-glossary.html#spatial-reference-system) for the object(s) being covered. This only needs to be set if you are using a custom [SRID](spatial-glossary.html#srid).                  |
> ```

This only needs to be set if the default bounds of the SRID is too large/small for the given data, or SRID = 0 and you wish to use a smaller range (unfortunately this is currently not exposed, but is viewable on https://epsg.io/3857).
By default, SRID = 0 assumes [-min int32, max int32] ranges.


<!-- Sent from Reviewable.io -->

2020-10-09 17:35 UTC, otan reviewed
> Reviewed 2 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8617)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @rmloveland, @rytaft, and @sumeerbhola)

___
*[v20.2/spatial-indexes.md, line 12 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJDOLTUAeGepTulkVHS:-MJDOLTUAeGepTulkVHT:bryezxb) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.md#L12)):*
> ```Markdown
> 
> - What spatial indexes are
> - How they works
> ```

nit: how they work
___
*[v20.2/spatial-indexes.md, line 27 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJDOT5tECCPJnZ43l6A:-MJDOT5tECCPJnZ43l6B:belcz9z) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.md#L27)):*
> ```Markdown
> - Fast filtering of lists of shapes based on spatial predicate functions such as `ST_Contains`.
> 
> - Speeding up joins between spatial and non-spatial data.
> ```

not sure how spatial indexes achieve this -- mind elaborating?
___
*[v20.2/spatial-indexes.md, line 33 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJDOZJt7hoxWnY5RE4S:-MJDOZJt7hoxWnY5RE4T:bpjvmmj) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.md#L33)):*
> ```Markdown
> - Their inner workings are specialized to operate on 2-dimensional (finite) `GEOMETRY` and `GEOGRAPHY` data types. They are stored by CockroachDB as a special type of [inverted index](inverted-indexes.html). For more details, see below.
> 
> - If needed, they can be tuned to store looser or tighter coverings of the shapes being indexed, depending on the needs of your application. Tighter coverings are more expensive to generate and store (and update), but can perform better in some cases because they return fewer false positives during the initial index lookup. However, most users will not need to change the default settings. For more information, see [Tuning spatial indexes](#tuning-spatial-indexes) below.
> ```

they can also perform worse because there's more to inverted index rows, so it's a bit of a tradeoff.
___
*[v20.2/spatial-indexes.md, line 111 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJDOu0iE0HKs5g0xeed:-MJDOu0iE0HKs5g0xeee:b-ot9mc7) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.md#L111)):*
> ```Markdown
> 
> ~~~
> 'LINESTRING(-76.4955 42.4405,  -75.6608 41.4102,-73.5422 41.052, -73.929 41.707, -76.4955 42.4405)'
> ```

i think you want an SRID=4326 in front of this to ensure ST_S2Covering uses the right bounds.
this will use the default bounds, instead of the lat lng bounds, which may generate different results.


<!-- Sent from Reviewable.io -->

2020-10-09 23:38 UTC, sumeerbhola requested changes
Generally looks good. Thanks for putting this together!

> Reviewed 1 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8617#-:-MJEiQV370QqvQYN4dl1:b2p9atn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @rmloveland, @rytaft, and @sumeerbhola)

___
*[v20.2/inverted-indexes.md, line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJEakMs9sawgpTdq5sr:-MJEakMs9sawgpTdq5ss:b6hov3x) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/inverted-indexes.md#L13)):*
> ```Markdown
> - [JSONB](jsonb.html)
> - [Arrays](array.html)
> - [Spatial data (finite `GEOMETRY` and `GEOGRAPHY` types)](spatial-indexes.html)
> ```

is "finite" something that needs to be said? I don't know if one can even represent an infinite plane in these types, let alone index them. 
___
*[v20.2/spatial-indexes.md, line 31 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJEbvZq33eLEZZxNkL1:-MJEbvZq33eLEZZxNkL2:b-qjlxrm) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.md#L31)):*
> ```Markdown
> Spatial indexes differ from other types of indexes as follows:
> 
> - Their inner workings are specialized to operate on 2-dimensional (finite) `GEOMETRY` and `GEOGRAPHY` data types. They are stored by CockroachDB as a special type of [inverted index](inverted-indexes.html). For more details, see below.
> ```

same question about needing to mention "finite".
___
*[v20.2/spatial-indexes.md, line 33 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJDOZJt7hoxWnY5RE4S:-MJEc3yv3fphAPIibXCG:b-pbrn5j) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.md#L33)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

they can also perform worse because there's more to inverted index rows, so it's a bit of a tradeoff.
</blockquote></details>

And more scans. We should definitely say there is a tradeoff that can make performance worse.
___
*[v20.2/spatial-indexes.md, line 39 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJEcXW7-RnqEIY2ouuF:-MJEcXW7-RnqEIY2ouuG:b-4cb30r) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.md#L39)):*
> ```Markdown
> ### Overview
> 
> There are two main approaches to building geospatial indexes in use:
> ```

nit: the "in use" seems unnecessary in the sentence.
___
*[v20.2/spatial-indexes.md, line 55 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJEcthv10wUjLfRY_IO:-MJEcthv10wUjLfRY_IP:b-xpxdjp) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.md#L55)):*
> ```Markdown
> - Allows advanced users to make a per-object tradeoff between index size and false positives during index creation. (See [Tuning spatial indexes](#tuning-spatial-indexes) below.)
> 
> Disadvantages of the "divide the space" approach include:
> ```

Do we typically try to run through the space of design options in our docs? I worry this will just confuse the user -- they just want it to work. We could just say:
Some of the reasons CockroachDB uses the "divide the space" approach are:
and list the reasons above, and cut out the disadvantages section.
(since we are no longer trying to argue for one over the other)
___
*[v20.2/spatial-indexes.md, line 57 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJEdNJ45tlHhklxV6IR:-MJEdNJ52NRfONtn4o07:b-n2au6r) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.md#L57)):*
> ```Markdown
> Disadvantages of the "divide the space" approach include:
> 
> - It does not support indexing infinite `GEOMETRY` types. Because the space is divided before it can be indexed, it must be finite. This means that CockroachDB's spatial indexing works for `GEOGRAPHY` (spherical) and for finite `GEOMETRY` (planar) objects, but not for infinite `GEOMETRY`.
> ```

This is confusing. I don't think there are infinite shapes. It is just that for GEOMETRY one needs to know the coordinates that will contain all shapes for optimal indexing. Can we just say something about this in a "how to use geometry indexing section". Something like:
The divide the space approach needs the bounding coordinates that will contain all or most of the shapes. For known SRIDs, CockroachDB automatically derives these bounding coordinates. For others, it uses the default ..., that can be changed. Note that if a rare shape falls outside these bounding coordinates, the database will behave correctly -- there will just be a performance loss in that such shapes may not be eliminated by the index lookup.
___
*[v20.2/spatial-indexes.md, line 58 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJEe_q9DTe5u_UDYyvR:-MJEe_q9DTe5u_UDYyvS:b-j3kssd) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.md#L58)):*
> ```Markdown
> 
> - It does not support indexing infinite `GEOMETRY` types. Because the space is divided before it can be indexed, it must be finite. This means that CockroachDB's spatial indexing works for `GEOGRAPHY` (spherical) and for finite `GEOMETRY` (planar) objects, but not for infinite `GEOMETRY`.
> - Includes more false positives in the index by default, which must then be filtered out during SQL execution. CockroachDB mitigates this by providing advanced users with the ability to [tune spatial indexes](#tuning-spatial-indexes).
> ```

We should not say this. There are many cases where coverings can be better than using a bounding box. 
___
*[v20.2/spatial-indexes.md, line 76 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJEgJay4fCfyhQqZQ53:-MJEgJay4fCfyhQqZQ54:b-s6yb3s) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.md#L76)):*
> ```Markdown
> <img style="display: block; margin-left: auto; margin-right: auto; width: 50%" src="{{ 'images/v20.2/geospatial/s2-cubed-sphere-3d.png' | relative_url }}" alt="S2 Cubed Sphere - 3D">
> 
> When you index a spatial object, a covering is computed using some number of the cells in the quadtree. The number of covering cells can vary per indexed object by passing special arguments to `CREATE INDEX` that tell CockroachDB how many levels of s2 cells to use. The leaf nodes of the S2 quadtree are at level 30, and measure 1cm across the Earth's surface. This means that advanced users can tune the accuracy of indexes down to 1cm, depending on the shapes being covered. However, most users will get the best performance with the default settings. For more information, see [Tuning spatial indexes](#tuning-spatial-indexes) below.
> ```

I've suggested some changes below, which say up front that users are getting that 1cm of precision by default for GEOGRAPHY.

When you index a spatial object, a covering is computed using some number of the cells in the quadtree. The number of covering cells can vary per indexed object by passing special arguments to `CREATE INDEX` that tell CockroachDB how many levels of s2 cells to use. The leaf nodes of the S2 quadtree are at level 30, and for GEOGRAPHY measure 1cm across the Earth's surface. By default, GEOGRAPHY indexes use up to level 30, so get this level of precision. We also use S2 cell coverings, in a slightly different way, for GEOMETRY indexes. The precision one gets there is the bounding length of the GEOMETRY index divided by 4^30. For more information, see [Tuning spatial indexes](#tuning-spatial-indexes) below.
___
*[v20.2/spatial-indexes.md, line 78 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJEhP9qDcXJZAHWQXNj:-MJEhP9qDcXJZAHWQXNk:b-zcidy8) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-i [...]

2020-10-12 16:18 UTC, rmloveland reviewed
Thanks Sumeer!  And many thanks to you and Oliver for the reviews! (And to y'all and Becca for the very informative and educational RFC).

I think my latest update has addressed your feedback.  PTAL and let me know!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8617#-:-MJS_v3B8f2pFQRFob8z:b95kqrq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @rytaft, and @sumeerbhola)

___
*[v20.2/inverted-indexes.md, line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJEakMs9sawgpTdq5sr:-MJSBJF96gFE1qGW3p2M:btaev32) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/inverted-indexes.md#L13)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is "finite" something that needs to be said? I don't know if one can even represent an infinite plane in these types, let alone index them. 
</blockquote></details>

Probably not - removed it!
___
*[v20.2/spatial-indexes.md, line 12 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJDOLTUAeGepTulkVHS:-MJSBT849dil4bJHmsKH:bu065vj) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.md#L12)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: how they work
</blockquote></details>

HA - fixed thanks

(I guess at least it didn't say "how they workses my preciousssssss")
___
*[v20.2/spatial-indexes.md, line 27 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJDOT5tECCPJnZ43l6A:-MJSBb2P2uDmYUnihOZR:b1l23gw) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.md#L27)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

not sure how spatial indexes achieve this -- mind elaborating?
</blockquote></details>

Hmmm I think what I meant to write was "Speeding up joins that involve spatial data columns."  Does that sound more reasonable?

Not sure where I got the other idea.  Maybe low blood sugar?
___
*[v20.2/spatial-indexes.md, line 31 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJEbvZq33eLEZZxNkL1:-MJSBwkE5EL5eHh71YGf:bss4a1y) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.md#L31)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

same question about needing to mention "finite".
</blockquote></details>

Removed!
___
*[v20.2/spatial-indexes.md, line 33 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJDOZJt7hoxWnY5RE4S:-MJSCQ75EtkdIv4YLh3f:b-wm4g0o) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.md#L33)):*
Updated to add

> ... Tighter coverings can also lead to worse performance due to more rows in the index, and more scans at the storage layer.  That's why we recommend that most users should not need to change the default settings. For more information, see ...

Is that an accurate representation?
___
*[v20.2/spatial-indexes.md, line 39 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJEcXW7-RnqEIY2ouuF:-MJSCdYJ67gJI5gyAxto:bss4a1y) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.md#L39)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: the "in use" seems unnecessary in the sentence.
</blockquote></details>

Removed!
___
*[v20.2/spatial-indexes.md, line 55 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJEcthv10wUjLfRY_IO:-MJSCr5Q9ibGXvk9YVii:bj8j86m) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.md#L55)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Do we typically try to run through the space of design options in our docs? I worry this will just confuse the user -- they just want it to work. We could just say:
Some of the reasons CockroachDB uses the "divide the space" approach are:
and list the reasons above, and cut out the disadvantages section.
(since we are no longer trying to argue for one over the other)

</blockquote></details>

I have updated it as you suggest, and removed the disadvantages part.

Agree we should avoid describing the design space too much.  I think I kept a bit too much of the RFC hanging around in this doc, and need to whittle more of it away.
___
*[v20.2/spatial-indexes.md, line 57 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJEdNJ45tlHhklxV6IR:-MJSDlPRAxgqRq3Rxqx0:b-lv0n9s) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.md#L57)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This is confusing. I don't think there are infinite shapes. It is just that for GEOMETRY one needs to know the coordinates that will contain all shapes for optimal indexing. Can we just say something about this in a "how to use geometry indexing section". Something like:
The divide the space approach needs the bounding coordinates that will contain all or most of the shapes. For known SRIDs, CockroachDB automatically derives these bounding coordinates. For others, it uses the default ..., that can be changed. Note that if a rare shape falls outside these bounding coordinates, the database will behave correctly -- there will just be a performance loss in that such shapes may not be eliminated by the index lookup.
</blockquote></details>

Removed this whole section via your previous comment
___
*[v20.2/spatial-indexes.md, line 58 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJEe_q9DTe5u_UDYyvR:-MJSDtr77EbGIlAqkyn4:b-lv0n9s) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.md#L58)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We should not say this. There are many cases where coverings can be better than using a bounding box. 
</blockquote></details>

Removed this whole section via your previous comment
___
*[v20.2/spatial-indexes.md, line 76 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJEgJay4fCfyhQqZQ53:-MJSMP1CE8SMS2GInrhw:blb7et2) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.md#L76)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I've suggested some changes below, which say up front that users are getting that 1cm of precision by default for GEOGRAPHY.

When you index a spatial object, a covering is computed using some number of the cells in the quadtree. The number of covering cells can vary per indexed object by passing special arguments to `CREATE INDEX` that tell CockroachDB how many levels of s2 cells to use. The leaf nodes of the S2 quadtree are at level 30, and for GEOGRAPHY measure 1cm across the Earth's surface. By default, GEOGRAPHY indexes use up to level 30, so get this level of precision. We also use S2 cell coverings, in a slightly different way, for GEOMETRY indexes. The precision one gets there is the bounding length of the GEOMETRY index divided by 4^30. For more information, see [Tuning spatial indexes](#tuning-spatial-indexes) below.

</blockquote></details>

Thanks! I've updated the section with your text (very lightly edited)
___
*[v20.2/spatial-indexes.md, line 78 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJEhP9qDcXJZAHWQXNj:-MJSMlEUAkZh0uM0widp:bcq9pxs) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.md#L78)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The example is somewhat confusing since the keys are cells and not some arbitrary shapes. I'm not sure how to [...]

2020-10-12 16:22 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5494887fb45bf35eb62d0ec71da0868b9a550733/

Edited pages:
- [v20.2/create-index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5494887fb45bf35eb62d0ec71da0868b9a550733/v20.2/create-index.html)
- [v20.2/indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5494887fb45bf35eb62d0ec71da0868b9a550733/v20.2/indexes.html)
- [v20.2/install-cockroachdb-spatial.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5494887fb45bf35eb62d0ec71da0868b9a550733/v20.2/install-cockroachdb-spatial.html)
- [v20.2/inverted-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5494887fb45bf35eb62d0ec71da0868b9a550733/v20.2/inverted-indexes.html)
- [v20.2/migrate-from-geojson.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5494887fb45bf35eb62d0ec71da0868b9a550733/v20.2/migrate-from-geojson.html)
- [v20.2/migrate-from-geopackage.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5494887fb45bf35eb62d0ec71da0868b9a550733/v20.2/migrate-from-geopackage.html)
- [v20.2/migrate-from-openstreetmap.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5494887fb45bf35eb62d0ec71da0868b9a550733/v20.2/migrate-from-openstreetmap.html)
- [v20.2/migrate-from-shapefiles.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5494887fb45bf35eb62d0ec71da0868b9a550733/v20.2/migrate-from-shapefiles.html)
- [v20.2/spatial-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5494887fb45bf35eb62d0ec71da0868b9a550733/v20.2/spatial-data.html)
- [v20.2/spatial-features.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5494887fb45bf35eb62d0ec71da0868b9a550733/v20.2/spatial-features.html)
- [v20.2/spatial-glossary.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5494887fb45bf35eb62d0ec71da0868b9a550733/v20.2/spatial-glossary.html)
- [v20.2/spatial-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5494887fb45bf35eb62d0ec71da0868b9a550733/v20.2/spatial-indexes.html)

2020-10-12 17:23 UTC, rytaft reviewed
Looks great!

> Reviewed 18 of 20 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8617#-:-MJSpLFr1v1uQRbRxNAQ:b9bkkp1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @rmloveland, and @sumeerbhola)

___
*[v20.2/spatial-glossary.md, line 177 at r2](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJSeZqWDnOoViDmdb77:-MJSeZqX1LezPWEw4zRZ:bw8x1tz) ([raw file](https://github.com/cockroachdb/docs/blob/5494887fb45bf35eb62d0ec71da0868b9a550733/v20.2/spatial-glossary.md#L177)):*
> ```Markdown
> <a name="s2"></a>
> 
> - _S2_: The [S2 Geometry Library](http://s2geometry.io) is a C++ code library for doing spherical geometry.  It models a sphere using a [quadtree](https://en.wikipedia.org/wiki/Quadtree) "divide the space" approach, and is used by CockroachDB.
> ```

[nit] Instead of "doing spherical geometry", maybe something like "performing spherical geometry computations"?
___
*[v20.2/spatial-indexes.md, line 27 at r2](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJSjd9iC3E069Uw9CIr:-MJSjd9iC3E069Uw9CIs:bedg5sf) ([raw file](https://github.com/cockroachdb/docs/blob/5494887fb45bf35eb62d0ec71da0868b9a550733/v20.2/spatial-indexes.md#L27)):*
> ```Markdown
> - Fast filtering of lists of shapes based on spatial predicate functions such as `ST_Contains`.
> 
> - Speeding up joins that involve spatial data columns.
> ```

It might help to include some example queries that can take advantage of a spatial index (or at least a link to another page with some examples). Let me know if you want some ideas.
___
*[v20.2/spatial-indexes.md, line 41 at r2](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJSfd8J66muZC2u0OFf:-MJSfd8J66muZC2u0OFg:b-pmlo4q) ([raw file](https://github.com/cockroachdb/docs/blob/5494887fb45bf35eb62d0ec71da0868b9a550733/v20.2/spatial-indexes.md#L41)):*
> ```Markdown
> There are two main approaches to building geospatial indexes:
> 
> - One approach is to "divide the objects". This works by inserting the objects into a tree (usually an [R-tree](https://en.wikipedia.org/wiki/R-tree)) whose shape depends on the data being indexed.
> ```

Perhaps mention that this is the approach that PostGIS uses
___
*[v20.2/spatial-indexes.md, line 106 at r2](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJSiHcv0BMybka-JIVt:-MJSiHcv0BMybka-JIVu:bhjwfsj) ([raw file](https://github.com/cockroachdb/docs/blob/5494887fb45bf35eb62d0ec71da0868b9a550733/v20.2/spatial-indexes.md#L106)):*
> ```Markdown
> <img style="display: block; margin-left: auto; margin-right: auto; width: 50%" src="{{ 'images/v20.2/geospatial/s2-coverings.gif' | relative_url }}" alt="Animated GIF of S2 Coverings - Levels 1 to 30">
> 
> Below are the same images presented in a grid. You can see that as we turn up the `s2_max_cells` parameter, more work is done by CockroachDB to discover a tighter and tighter covering (that is, a covering using fewer and smaller cells). The covering for this particular shape reaches a reasonable level of accuracy when `s2_max_cells` reaches 10, and stops improving much past 12.
> ```

should "fewer and smaller cells" actually be "more and smaller cells"?


<!-- Sent from Reviewable.io -->

2020-10-12 17:32 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 4 of 20 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8617#-:-MJSrgasDn7SumgImG_6:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan, @rmloveland, and @sumeerbhola)

___
*[v20.2/spatial-indexes.md, line 33 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJDOZJt7hoxWnY5RE4S:-MJSpiqKB8usJUfJuzfq:b-47fafm) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.md#L33)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Updated to add

> ... Tighter coverings can also lead to worse performance due to more rows in the index, and more scans at the storage layer.  That's why we recommend that most users should not need to change the default settings. For more information, see ...

Is that an accurate representation?
</blockquote></details>

looks good
___
*[v20.2/spatial-indexes.md, line 57 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJEdNJ45tlHhklxV6IR:-MJSqk9bEx0bQ6605VOL:b-utz3gm) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.md#L57)):*
> The divide the space approach needs the bounding coordinates that will contain all or most of the shapes. For known SRIDs, CockroachDB automatically derives these bounding coordinates. For others, it uses the default ..., that can be changed. Note that if a rare shape falls outside these bounding coordinates, the database will behave correctly -- there will just be a performance loss in that such shapes may not be eliminated by the index lookup.

The content in the sentence that starts with "Note ..." should be conveyed somewhere. Maybe where the doc describes the `geometry_min_x,...` parameters?


<!-- Sent from Reviewable.io -->

2020-10-12 19:31 UTC, rmloveland reviewed
Thanks for the review Becca! And for the additional comments, Sumeer.

I think I have addressed the latest round of comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8617#-:-MJTFIApCUqZDg3Ca_nb:bzohhk)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan, @rytaft, and @sumeerbhola)

___
*[v20.2/spatial-glossary.md, line 177 at r2](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJSeZqWDnOoViDmdb77:-MJTCAdQ1JSYkTAYM24j:bu1labn) ([raw file](https://github.com/cockroachdb/docs/blob/5494887fb45bf35eb62d0ec71da0868b9a550733/v20.2/spatial-glossary.md#L177)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] Instead of "doing spherical geometry", maybe something like "performing spherical geometry computations"?
</blockquote></details>

Much better - updated, thanks
___
*[v20.2/spatial-indexes.md, line 57 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJEdNJ45tlHhklxV6IR:-MJTEnvHBcs9itRGoMgd:bgp74e5) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.md#L57)):*
Oh nice catch!  I have added it to a note just above the s2 settings params that reads 

> If a shape falls outside the bounding coordinates determined by the `geometry_*` settings below, there will be a performance loss in that such shapes may not be eliminated by the index lookup, but the database will still return the correct answers.

Please let me know if I have introduced a subtle error in the re-wording, though
___
*[v20.2/spatial-indexes.md, line 27 at r2](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJSjd9iC3E069Uw9CIr:-MJTCHni4INZgcLQnfE7:b-qo9rpq) ([raw file](https://github.com/cockroachdb/docs/blob/5494887fb45bf35eb62d0ec71da0868b9a550733/v20.2/spatial-indexes.md#L27)):*
I agree, it would be very helpful!  We could add a few to the 'Examples' section on this page, and also link to them from the Joins page

If it's OK with you, I have filed a separate issue #8638 to work on adding more join info to this page separately.  Figure it will be better to get this published ASAP and then improve it since I have not played with spatial joins much at all yet.

> Let me know if you want some ideas.

Yes please!  Do you mind commenting on #8638  with some suggestions and ideas?  I would really appreciate it.
___
*[v20.2/spatial-indexes.md, line 41 at r2](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJSfd8J66muZC2u0OFf:-MJTDPK37b-NjmFj4Z-p:bgrfpw0) ([raw file](https://github.com/cockroachdb/docs/blob/5494887fb45bf35eb62d0ec71da0868b9a550733/v20.2/spatial-indexes.md#L41)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Perhaps mention that this is the approach that PostGIS uses
</blockquote></details>

Updated to add "This is the approach taken by [PostGIS](https://postgis.net)."
___
*[v20.2/spatial-indexes.md, line 106 at r2](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJSiHcv0BMybka-JIVt:-MJTFBzS3U_na8WgVjsU:bsk0n5e) ([raw file](https://github.com/cockroachdb/docs/blob/5494887fb45bf35eb62d0ec71da0868b9a550733/v20.2/spatial-indexes.md#L106)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

should "fewer and smaller cells" actually be "more and smaller cells"?
</blockquote></details>

Fixed!  :sweat: 


<!-- Sent from Reviewable.io -->

2020-10-12 19:35 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/905b38b6198e08a79f847916ea3a1867bbc11f9d/

Edited pages:
- [v20.2/create-index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/905b38b6198e08a79f847916ea3a1867bbc11f9d/v20.2/create-index.html)
- [v20.2/indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/905b38b6198e08a79f847916ea3a1867bbc11f9d/v20.2/indexes.html)
- [v20.2/install-cockroachdb-spatial.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/905b38b6198e08a79f847916ea3a1867bbc11f9d/v20.2/install-cockroachdb-spatial.html)
- [v20.2/inverted-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/905b38b6198e08a79f847916ea3a1867bbc11f9d/v20.2/inverted-indexes.html)
- [v20.2/migrate-from-geojson.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/905b38b6198e08a79f847916ea3a1867bbc11f9d/v20.2/migrate-from-geojson.html)
- [v20.2/migrate-from-geopackage.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/905b38b6198e08a79f847916ea3a1867bbc11f9d/v20.2/migrate-from-geopackage.html)
- [v20.2/migrate-from-openstreetmap.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/905b38b6198e08a79f847916ea3a1867bbc11f9d/v20.2/migrate-from-openstreetmap.html)
- [v20.2/migrate-from-shapefiles.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/905b38b6198e08a79f847916ea3a1867bbc11f9d/v20.2/migrate-from-shapefiles.html)
- [v20.2/spatial-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/905b38b6198e08a79f847916ea3a1867bbc11f9d/v20.2/spatial-data.html)
- [v20.2/spatial-features.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/905b38b6198e08a79f847916ea3a1867bbc11f9d/v20.2/spatial-features.html)
- [v20.2/spatial-glossary.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/905b38b6198e08a79f847916ea3a1867bbc11f9d/v20.2/spatial-glossary.html)
- [v20.2/spatial-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/905b38b6198e08a79f847916ea3a1867bbc11f9d/v20.2/spatial-indexes.html)

2020-10-12 19:50 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Thanks!

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8617#-:-MJTM13-DkOdmzAhHpjp:b-g2a5fb)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @otan, @rmloveland, and @sumeerbhola)

___
*[v20.2/spatial-indexes.md, line 27 at r2](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJSjd9iC3E069Uw9CIr:-MJTLXI61jNNvamK__he:behqle0) ([raw file](https://github.com/cockroachdb/docs/blob/5494887fb45bf35eb62d0ec71da0868b9a550733/v20.2/spatial-indexes.md#L27)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

I agree, it would be very helpful!  We could add a few to the 'Examples' section on this page, and also link to them from the Joins page

If it's OK with you, I have filed a separate issue #8638 to work on adding more join info to this page separately.  Figure it will be better to get this published ASAP and then improve it since I have not played with spatial joins much at all yet.

> Let me know if you want some ideas.

Yes please!  Do you mind commenting on #8638  with some suggestions and ideas?  I would really appreciate it.
</blockquote></details>

Sounds good! Will do.


<!-- Sent from Reviewable.io -->

2020-10-13 14:17 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a72ea7416f650b3f18f9acccc26a1eb7b810e502/

Edited pages:
- [v20.2/create-index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a72ea7416f650b3f18f9acccc26a1eb7b810e502/v20.2/create-index.html)
- [v20.2/indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a72ea7416f650b3f18f9acccc26a1eb7b810e502/v20.2/indexes.html)
- [v20.2/install-cockroachdb-spatial.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a72ea7416f650b3f18f9acccc26a1eb7b810e502/v20.2/install-cockroachdb-spatial.html)
- [v20.2/inverted-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a72ea7416f650b3f18f9acccc26a1eb7b810e502/v20.2/inverted-indexes.html)
- [v20.2/migrate-from-geojson.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a72ea7416f650b3f18f9acccc26a1eb7b810e502/v20.2/migrate-from-geojson.html)
- [v20.2/migrate-from-geopackage.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a72ea7416f650b3f18f9acccc26a1eb7b810e502/v20.2/migrate-from-geopackage.html)
- [v20.2/migrate-from-openstreetmap.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a72ea7416f650b3f18f9acccc26a1eb7b810e502/v20.2/migrate-from-openstreetmap.html)
- [v20.2/migrate-from-shapefiles.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a72ea7416f650b3f18f9acccc26a1eb7b810e502/v20.2/migrate-from-shapefiles.html)
- [v20.2/spatial-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a72ea7416f650b3f18f9acccc26a1eb7b810e502/v20.2/spatial-data.html)
- [v20.2/spatial-features.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a72ea7416f650b3f18f9acccc26a1eb7b810e502/v20.2/spatial-features.html)
- [v20.2/spatial-glossary.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a72ea7416f650b3f18f9acccc26a1eb7b810e502/v20.2/spatial-glossary.html)
- [v20.2/spatial-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a72ea7416f650b3f18f9acccc26a1eb7b810e502/v20.2/spatial-indexes.html)

2020-10-13 14:24 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/

Edited pages:
- [v20.2/create-index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/create-index.html)
- [v20.2/indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/indexes.html)
- [v20.2/install-cockroachdb-spatial.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/install-cockroachdb-spatial.html)
- [v20.2/inverted-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/inverted-indexes.html)
- [v20.2/migrate-from-geojson.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/migrate-from-geojson.html)
- [v20.2/migrate-from-geopackage.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/migrate-from-geopackage.html)
- [v20.2/migrate-from-openstreetmap.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/migrate-from-openstreetmap.html)
- [v20.2/migrate-from-shapefiles.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/migrate-from-shapefiles.html)
- [v20.2/spatial-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/spatial-data.html)
- [v20.2/spatial-features.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/spatial-features.html)
- [v20.2/spatial-glossary.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/spatial-glossary.html)
- [v20.2/spatial-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/spatial-indexes.html)

2020-10-13 18:01 UTC, ericharmeling reviewed
Awesome work, Rich! The spatial indexes page is rad, (especially the details part). Very impressive, technical docs.

I had a few comments, some grammar-related, some include-file-related, some syntax-reference-related, which might demand some not-so-small changes, should you find my points valid and worth addressing...

Also, (I don't note this in my comments below), you might need to update the index_def.html diagram and the corresponding parameter description on the create-table.html page.

> Reviewed 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8617#-:-MJXv9by7uC4uUp262TG:b-i5vxf0)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @otan, @rmloveland, and @sumeerbhola)

___
*[_includes/v20.2/sql/spatial-support-new.md, line 1 at r4](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJXpQ3t6c1lYF0Sr-9s:-MJXpQ3u3o8HBe5MP3dt:b-q3bf9o) ([raw file](https://github.com/cockroachdb/docs/blob/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/_includes/v20.2/sql/spatial-support-new.md#L1)):*
> ```Markdown
> <span class="version-tag">New in v20.2</span>: CockroachDB supports efficiently storing and querying spatial data.
> ```

TBH, IDK if this needs to be an include file, on every page that covers a spatial feature. This seems more like an overview-page-type sentence (you actually have this sentence on spatial-features.html, but not in an include). It might be best to remove it from all pages except that overview page, and then add a version tag in its place.
___
*[v20.2/create-index.md, line 31 at r4](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJXvkArEjldaEsp26kC:-MJXvkAs7foN39XCQPHh:bq59bzs) ([raw file](https://github.com/cockroachdb/docs/blob/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/create-index.md#L31)):*
> ```
> <section>{% include {{ page.version.version }}/sql/diagrams/create_index.html %}</section>
> ```

I think spatial index syntax is covered by this diagram (`USING name`, right?), but it might still be worth regenerating it to make sure?
___
*[v20.2/create-index.md, line 46 at r4](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJXvf2LDpFuBoKnHdn3:-MJXvf2LDpFuBoKnHdn4:b4dg9r5) ([raw file](https://github.com/cockroachdb/docs/blob/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/create-index.md#L46)):*
> ```
> `USING name` 
> ```

This parameter description might need to be updated for spatial index syntax.
___
*[v20.2/indexes.md, line 70 at r4](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJXq1Ud2REZ-vDP1Q4I:-MJXq1Ud2REZ-vDP1Q4J:bam7z78) ([raw file](https://github.com/cockroachdb/docs/blob/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/indexes.md#L70)):*
> ```
> ## Spatial indexes
> ```

Inverted and partial indexes are special types of indexes that also have their own pages, but we don't call them out in their own level-2 header like this (we don't even call out inverted indexes at all on this page). It might be more consistent to have a short paragraph under "How do indexes work?", like we do for partial indexes. 

> {% include {{page.version.version}}/sql/spatial-support-new.md %}
> For more information about spatial indexes, see [Spatial Indexes](spatial-indexes.html).

This include says nothing about spatial indexes, and I don't think it adds much information. I'd remove it, and add a sentence more specific to spatial indexes.

My suggestion (end of top-level of "How do indexes work?" section):

```
<span class="version-tag">New in v20.2</span>: To index [spatial data](spatial-data.html), CockroachDB uses *spatial indexes*. For more information about spatial indexes, see [Spatial Indexes](spatial-indexes.html).
```

Another idea would be to add this as a level 2 header to the inverted-indexes.html page, since spatial indexes are, in fact, inverted indexes.
___
*[v20.2/install-cockroachdb-spatial.md, line 10 at r4](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJY4yNH6w2jBqq68756:-MJY4yNH6w2jBqq68757:b5tfz76) ([raw file](https://github.com/cockroachdb/docs/blob/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/install-cockroachdb-spatial.md#L10)):*
> ```
> {% include {{page.version.version}}/sql/spatial-support-new.md %}
> ```

Idk if this needs to be included here.
___
*[v20.2/spatial-data.md, line 7 at r4](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJY599DEaaTXoSpecte:-MJY599DEaaTXoSpectf:bxfcq6k) ([raw file](https://github.com/cockroachdb/docs/blob/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/spatial-data.md#L7)):*
> ```
> {% include {{page.version.version}}/sql/spatial-support-new.md %}
> ```

Again, IDK how much this include adds to the page.
___
*[v20.2/spatial-data.md, line 9 at r4](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJY53tJ42C1rP_Yyaot:-MJY53tJ42C1rP_Yyaou:b-97plgt) ([raw file](https://github.com/cockroachdb/docs/blob/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/spatial-data.md#L9)):*
> ```
> spatial data types
> ```

[spatial](spatial-features.html) data types
___
*[v20.2/spatial-features.md, line 7 at r4](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJXugiK6zGUQHwAXDOZ:-MJXugiL9rMgZv9boyDd:b-lgv6w0) ([raw file](https://github.com/cockroachdb/docs/blob/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/spatial-features.md#L7)):*
> ```
> <span class="version-tag">New in v20.2</span>: CockroachDB supports efficiently storing and querying spatial data.
> ```

This seems like the best place for this kind of sentence.
___
*[v20.2/spatial-glossary.md, line 31 at r4](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJXv4jp7zIk_QiGd31Z:-MJXv4jq1QlfUtiAcnRf:bralhll) ([raw file](https://github.com/cockroachdb/docs/blob/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/spatial-glossary.md#L31)):*
> ```
> lie to the outside of
> ```

lie outside of
___
*[v20.2/spatial-indexes.md, line 7 at r4](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJY5MA0CZde89qGGBo3:-MJY5MA0CZde89qGGBo4:b-buh2rw) ([raw file](https://github.com/cockroachdb/docs/blob/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/spatial-indexes.md#L7)):*
> ```
> {% include {{page.version.version}}/sql/spatial-support-new.md %}
> ```

Again, IDK how much this include adds to this doc.
___
*[v20.2/spatial-indexes.md, line 9 at r4](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJXwX7l2EA5gm42WnX_:-MJXwX7l2EA5gm42WnXa:b-g71ncs) ([raw file](https://github.com/cockroachdb/docs/blob/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/spatial-indexes.md#L9)):*
> ```
> spatial data
> ```

`[spatial data](spatial-data.html)`
___
*[v20.2/spatial-indexes.md, line 21 at r4](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJXw6te49T9dWHlTW-7:-MJXw6tf5oDsrxgwMczg:b-rjkflu) ([raw file](https://github.com/cockroachdb/docs/blob/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/spatial-indexes.md#L21)):*
> ```
> Its purpose in life is to 
> ```

Its purpose is to
___
*[v20.2/spatial-indexes.md, line 31 at r4](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJXwo_W6NzqyEyGmisp:-MJXwo_W6NzqyEyGmisq:b-5biqrt) ([raw file](https://github.com/cockroachdb/docs/blob/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/spatial-indexes.md#L31)):*
> ```
> Their inner workings are 
> ```

They are
___
*[v20.2/spatial-indexes.md, line 31 at r4](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJXwsnZBR9ASeqNuQcc:-MJXwsn_7u_LAy_KDDfv:b-vxdkex) ([raw file](https://github.com/cockroachdb/docs/blob/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/spatial-indexes.md#L31)):*
> ```
> For more details, see below.
> ```

For more details, see [below](#details).
___
*[v20.2/spatial-indexes.md, line 33 at r4](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJXx3T73LwP9Wh65o8t:-MJXx3T73LwP9Wh65o8u:b-2muqjp) ([raw file](https://github.com/cockroachdb/docs/blob/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/spatial-indexes.md#L33)):*
> ```
> generate and store (and update)
> ```

generate, store, and update
___
*[v20.2/spatial-indexes.md, line 41 at r4](https://reviewable.io/reviews/cockroac [...]

2020-10-13 18:41 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8617)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @otan, @rmloveland, and @sumeerbhola)

___
*[v20.2/spatial-indexes.md, line 57 at r1](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJEdNJ45tlHhklxV6IR:-MJYG4SYBzFsss3Gh9lI:b-47fafm) ([raw file](https://github.com/cockroachdb/docs/blob/1a563a0b0472b665b4befce5134e696cf57f3f76/v20.2/spatial-indexes.md#L57)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Oh nice catch!  I have added it to a note just above the s2 settings params that reads 

> If a shape falls outside the bounding coordinates determined by the `geometry_*` settings below, there will be a performance loss in that such shapes may not be eliminated by the index lookup, but the database will still return the correct answers.

Please let me know if I have introduced a subtle error in the re-wording, though
</blockquote></details>

looks good


<!-- Sent from Reviewable.io -->

2020-10-14 21:34 UTC, rmloveland reviewed
Thanks for the review Eric!!!  I really appreciate your feedback.  I have tried to address everything you mentioned, including needing add'l syntax documentation for `CREATE INDEX`, and checking the diagrams.  PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8617#-:-MJd0zE20vgK2rZwH4xn:b-xyh129)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ericharmeling, @otan, @rmloveland, and @sumeerbhola)

___
*[_includes/v20.2/sql/spatial-support-new.md, line 1 at r4](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJXpQ3t6c1lYF0Sr-9s:-MJcYex-7CiVMXNT09sY:bf8tezk) ([raw file](https://github.com/cockroachdb/docs/blob/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/_includes/v20.2/sql/spatial-support-new.md#L1)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

TBH, IDK if this needs to be an include file, on every page that covers a spatial feature. This seems more like an overview-page-type sentence (you actually have this sentence on spatial-features.html, but not in an include). It might be best to remove it from all pages except that overview page, and then add a version tag in its place.
</blockquote></details>

Makes sense to me.  I have deleted the include and removed all mentions of this line except from the overview page 'Spatial Features' and from the 'Install CockroachDB spatial' page.
___
*[v20.2/create-index.md, line 31 at r4](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJXvkArEjldaEsp26kC:-MJci7Za02BSfyrtivoH:b3zzivw) ([raw file](https://github.com/cockroachdb/docs/blob/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/create-index.md#L31)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> <section>{% include {{ page.version.version }}/sql/diagrams/create_index.html %}</section>
> ```

I think spatial index syntax is covered by this diagram (`USING name`, right?), but it might still be worth regenerating it to make sure?
</blockquote></details>

I regenerated the diagram for `CREATE INDEX` but according to `git status` the file contents of the diagram (for v20.2) were not changed, so I think you are correct that it is covered by `USING (name)`.
___
*[v20.2/create-index.md, line 46 at r4](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJXvf2LDpFuBoKnHdn3:-MJccLeR3vP0oX-Y69IB:b-x8b36d) ([raw file](https://github.com/cockroachdb/docs/blob/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/create-index.md#L46)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> `USING name` 
> ```

This parameter description might need to be updated for spatial index syntax.
</blockquote></details>

Nice catch, thanks - updated to add `gist` with a link to the spatial index page.
___
*[v20.2/indexes.md, line 70 at r4](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJXq1Ud2REZ-vDP1Q4I:-MJcdE1r5U5Q9yAjyNPl:bwy8kbr) ([raw file](https://github.com/cockroachdb/docs/blob/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/indexes.md#L70)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> ## Spatial indexes
> ```

Inverted and partial indexes are special types of indexes that also have their own pages, but we don't call them out in their own level-2 header like this (we don't even call out inverted indexes at all on this page). It might be more consistent to have a short paragraph under "How do indexes work?", like we do for partial indexes. 

> {% include {{page.version.version}}/sql/spatial-support-new.md %}
> For more information about spatial indexes, see [Spatial Indexes](spatial-indexes.html).

This include says nothing about spatial indexes, and I don't think it adds much information. I'd remove it, and add a sentence more specific to spatial indexes.

My suggestion (end of top-level of "How do indexes work?" section):

```
<span class="version-tag">New in v20.2</span>: To index [spatial data](spatial-data.html), CockroachDB uses *spatial indexes*. For more information about spatial indexes, see [Spatial Indexes](spatial-indexes.html).
```

Another idea would be to add this as a level 2 header to the inverted-indexes.html page, since spatial indexes are, in fact, inverted indexes.
</blockquote></details>

Went with your suggested sentence at the end of the "How do indexes work?" section.

Agree re: adding more info to the 'Inverted Indexes' page.  It's in the plan to add more spatial index info to both 'Indexes' and 'Inverted Indexes' Real Soon (tm) (via #7902 and #7903)
___
*[v20.2/install-cockroachdb-spatial.md, line 10 at r4](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJY4yNH6w2jBqq68756:-MJcfEnCEg36Iwb343K1:bss4a2b) ([raw file](https://github.com/cockroachdb/docs/blob/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/install-cockroachdb-spatial.md#L10)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> {% include {{page.version.version}}/sql/spatial-support-new.md %}
> ```

Idk if this needs to be included here.
</blockquote></details>

Removed.
___
*[v20.2/spatial-data.md, line 7 at r4](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJY599DEaaTXoSpecte:-MJcfeos4Z_Z8P454Pqi:btr8juj) ([raw file](https://github.com/cockroachdb/docs/blob/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/spatial-data.md#L7)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> {% include {{page.version.version}}/sql/spatial-support-new.md %}
> ```

Again, IDK how much this include adds to the page.
</blockquote></details>

Removed this from all pages except the overview page 'Spatial Features'.
___
*[v20.2/spatial-data.md, line 9 at r4](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJY53tJ42C1rP_Yyaot:-MJcfrGy9vuTugHlgd4T:btnidkz) ([raw file](https://github.com/cockroachdb/docs/blob/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/spatial-data.md#L9)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> spatial data types
> ```

[spatial](spatial-features.html) data types
</blockquote></details>

Updated to add the link
___
*[v20.2/spatial-features.md, line 7 at r4](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJXugiK6zGUQHwAXDOZ:-MJcfu9h5wek87E2gr4J:b-980o99) ([raw file](https://github.com/cockroachdb/docs/blob/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/spatial-features.md#L7)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> <span class="version-tag">New in v20.2</span>: CockroachDB supports efficiently storing and querying spatial data.
> ```

This seems like the best place for this kind of sentence.
</blockquote></details>

Cool - left this one alone
___
*[v20.2/spatial-glossary.md, line 31 at r4](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJXv4jp7zIk_QiGd31Z:-MJcg50g9K1jE-M7S9aE:b-886gsx) ([raw file](https://github.com/cockroachdb/docs/blob/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/spatial-glossary.md#L31)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> lie to the outside of
> ```

lie outside of
</blockquote></details>

Fixed
___
*[v20.2/spatial-indexes.md, line 7 at r4](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJY5MA0CZde89qGGBo3:-MJcg6bl3lDU-qQjCeoW:bss4a1y) ([raw file](https://github.com/cockroachdb/docs/blob/0da33b6e8b6c5b1c687e43d0c9a3e9738a60f269/v20.2/spatial-indexes.md#L7)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> {% include {{page.version.version}}/sql/spatial-support-new.md %}
> ```

Again, IDK how much this include adds to this doc.
</blockquote></details>

Removed!
___
*[v20.2/spatial-indexes.md, line 9 at r4](https://reviewable.io/reviews/cockroachdb/docs/8617#-MJXwX7l2EA5gm42WnX_:-MJcgFQ [...]

2020-10-14 21:37 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d05f499eab3d1f3f966bddf61810cd390438c34a/

Edited pages:
- [v20.2/create-index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d05f499eab3d1f3f966bddf61810cd390438c34a/v20.2/create-index.html)
- [v20.2/indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d05f499eab3d1f3f966bddf61810cd390438c34a/v20.2/indexes.html)
- [v20.2/install-cockroachdb-spatial.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d05f499eab3d1f3f966bddf61810cd390438c34a/v20.2/install-cockroachdb-spatial.html)
- [v20.2/inverted-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d05f499eab3d1f3f966bddf61810cd390438c34a/v20.2/inverted-indexes.html)
- [v20.2/migrate-from-geojson.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d05f499eab3d1f3f966bddf61810cd390438c34a/v20.2/migrate-from-geojson.html)
- [v20.2/migrate-from-geopackage.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d05f499eab3d1f3f966bddf61810cd390438c34a/v20.2/migrate-from-geopackage.html)
- [v20.2/migrate-from-openstreetmap.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d05f499eab3d1f3f966bddf61810cd390438c34a/v20.2/migrate-from-openstreetmap.html)
- [v20.2/migrate-from-shapefiles.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d05f499eab3d1f3f966bddf61810cd390438c34a/v20.2/migrate-from-shapefiles.html)
- [v20.2/spatial-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d05f499eab3d1f3f966bddf61810cd390438c34a/v20.2/spatial-data.html)
- [v20.2/spatial-features.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d05f499eab3d1f3f966bddf61810cd390438c34a/v20.2/spatial-features.html)
- [v20.2/spatial-glossary.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d05f499eab3d1f3f966bddf61810cd390438c34a/v20.2/spatial-glossary.html)
- [v20.2/spatial-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d05f499eab3d1f3f966bddf61810cd390438c34a/v20.2/spatial-indexes.html)

2020-10-19 20:54 UTC, rmloveland commented
Hey Eric, thanks again for your careful review of this PR.  Sorry that I seem to have missed some obvious things.  What do you think of the recent changes?  Do you feel like they address your feedback?  If not please let me know and I will try to fix.

(Also, sorry for forgetting to mention that I also ran the scripts to update the diagrams for `create_table` and `index_def` as you suggested in your opening comment.  It looks like no changes were generated for the 20.2 pages, so it seems they are up to date as well.)

2020-10-19 21:06 UTC, ericharmeling approved these changes
@rmloveland So sorry for not getting back on this sooner!

Thanks for carefully going through my nit-picking and lengthy review comments. :)

I just looked over all your follow-up comments and changes and everything LGTM now!

> Reviewed 7 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8617#-:-MK1fcO2CG16YtQHWJDi:bqa4qhk)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @otan, @rmloveland, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2020-10-20 18:43 UTC, merged