Implicit array casting
cockroachdb/docs pull request #8709
Opened 2020-10-19 19:24 UTC by ericharmeling

Fixes #8689.

2020-10-19 19:24 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/8709)
<!-- Reviewable:end -->

2020-10-19 19:29 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d488effe1cb9d8f740bf598d1686b4570803b2dd/

Edited pages:
- [v20.2/array.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d488effe1cb9d8f740bf598d1686b4570803b2dd/v20.2/array.html)
- [v20.2/data-types.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d488effe1cb9d8f740bf598d1686b4570803b2dd/v20.2/data-types.html)
- [v20.2/string.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d488effe1cb9d8f740bf598d1686b4570803b2dd/v20.2/string.html)

2020-10-19 20:44 UTC, rafiss requested changes

2020-10-19 20:44 UTC, rafiss commented on v20.2/data-types.md
> + CockroachDB also supports implicit casting from string literals to all data types except [`BYTES`](bytes.html), [`ENUM`](enum.html), [`JSONB`](jsonb.html), and [`SERIAL`](serial.html). For an exampl
should be "to arrays of all data types"

also, Box2D, Geometry, and Geography types are not supported

2020-10-19 20:44 UTC, rafiss commented on v20.2/array.md
> +CockroachDB supports implicit casting from string literals to arrays of all data types except [`BYTES`](bytes.html), [`ENUM`](enum.html), [`JSONB`](jsonb.html), and [`SERIAL`](serial.html).
Box2D, Geometry, and Geography types are not supported too

2020-10-19 20:44 UTC, rafiss commented on v20.2/string.md
> +`ARRAY` | Requires supported [`ARRAY`](array.html) string format, e.g., `'{1,2,3}'`.<br>Note that string literals can be implicitly cast to any supported `ARRAY` data type except [`BYTES`](bytes.html
same comment re: Box2D, Geometry, and Geography

2020-10-19 21:33 UTC, ericharmeling reviewed
TFTR @rafiss !

I updated the pages with those spatial types, and changed the formatting a bit. I don't think we currently document support for Box2D, but that could be in the works. @rmloveland 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8709#-:-MK1jLTN2CEBAQS5A_i6:b-yq3trf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[v20.2/array.md, line 267 at r1](https://reviewable.io/reviews/cockroachdb/docs/8709#-MK1JYUOmokUuUZl4de6-r1-267:-MK1hsZM97FqgnEiefEi:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/d488effe1cb9d8f740bf598d1686b4570803b2dd/v20.2/array.md#L267)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

Box2D, Geometry, and Geography types are not supported too
</blockquote></details>

Done.
___
*[v20.2/data-types.md, line 50 at r1](https://reviewable.io/reviews/cockroachdb/docs/8709#-MK1JYUOmokUuUZl4de7-r1-50:-MK1i6Iy07KHOBtfGEik:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/d488effe1cb9d8f740bf598d1686b4570803b2dd/v20.2/data-types.md#L50)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should be "to arrays of all data types"

also, Box2D, Geometry, and Geography types are not supported
</blockquote></details>

Done.
___
*[v20.2/string.md, line 116 at r1](https://reviewable.io/reviews/cockroachdb/docs/8709#-MK1JYUOmokUuUZl4de8-r1-116:-MK1jKe84hJLsn6bqSFi:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/d488effe1cb9d8f740bf598d1686b4570803b2dd/v20.2/string.md#L116)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

same comment re: Box2D, Geometry, and Geography
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-19 21:36 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f731b93dcd41e4bb942ccdad083879cd69bc92a6/

Edited pages:
- [v20.2/array.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f731b93dcd41e4bb942ccdad083879cd69bc92a6/v20.2/array.html)
- [v20.2/data-types.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f731b93dcd41e4bb942ccdad083879cd69bc92a6/v20.2/data-types.html)
- [v20.2/string.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f731b93dcd41e4bb942ccdad083879cd69bc92a6/v20.2/string.html)

2020-10-20 14:55 UTC, lnhsingh reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8709#-:-MK5V_T92A3nmLjLwFXT:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lnhsingh and @rafiss)



<!-- Sent from Reviewable.io -->

2020-10-20 15:15 UTC, merged

2020-10-20 15:19 UTC, rmloveland commented
Eric Harmeling <notifications@github.com> writes:

> I updated the pages with those spatial types, and changed the
> formatting a bit. I don't think we currently document support for
> Box2D, but that could be in the works. @rmloveland

We don't have docs yet!  It's not on the "required shortlist" of things
for the release, but it Will Definitely Get Done Eventually (tm).