cockroach userfile upload / list / delete
cockroachdb/docs pull request #8729
Opened 2020-10-21 23:20 UTC by lnhsingh

Closes #7929.
Closes #8200.
Closes #8221.

2020-10-21 23:20 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/8729)
<!-- Reviewable:end -->

2020-10-21 23:24 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/

Edited pages:
- [v20.2/cockroach-commands.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-commands.html)
- [v20.2/cockroach-nodelocal-upload.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-nodelocal-upload.html)
- [v20.2/cockroach-userfile-delete.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-delete.html)
- [v20.2/cockroach-userfile-list.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-list.html)
- [v20.2/cockroach-userfile-upload.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-upload.html)
- [v20.2/create-schedule-for-backup.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/create-schedule-for-backup.html)
- [v20.2/import.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/import.html)
- [v20.2/use-userfile-for-bulk-operations.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/use-userfile-for-bulk-operations.html)

2020-10-28 18:06 UTC, lnhsingh commented
@adityamaru / @mwang1026 friendly nudge to review please :)

2020-10-28 18:09 UTC, lnhsingh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8729)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @mwang1026)

___
*[_includes/sidebar-data-v20.2.json, line 572 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKkOWmt0rDhvLefGBlL:-MKkOWmu0IRTQYNy6UBf:bdqdlxi) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/_includes/sidebar-data-v20.2.json#L572)):*
> ```JSON
>               },
>               {
>                 "title": "User-scoped Storage",
> ```

This should be "Userfile"


<!-- Sent from Reviewable.io -->

2020-10-28 22:02 UTC, adityamaru requested changes
> Reviewed 8 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8729)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @lnhsingh, and @mwang1026)

___
*[v20.2/cockroach-userfile-delete.md, line 11 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKl4DA66CkhUB7ukztr:-MKl4DA66CkhUB7ukzts:b-2tlwzc) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-delete.md#L11)):*
> ```
> CockroachD
> ```
nit: CockroachDB
___
*[v20.2/cockroach-userfile-delete.md, line 11 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKl4IKN7aJObA1aVQVu:-MKl4IKN7aJObA1aVQVv:b-l426ja) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-delete.md#L11)):*
> ```
> .
> ```
might be worth adding that it will revoke all access from every other user in the cluster except root/admin.
___
*[v20.2/cockroach-userfile-delete.md, line 11 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKl4XQ-3nmMNwMQhR5K:-MKl4XQ-3nmMNwMQhR5L:bqu7oqs) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-delete.md#L11)):*
> ```
> subdirectory with the name matching their username
> ```
I think we can edit this line to say that a user can only delete data in his/her user scoped storage which they can reference via the userfile URI they provided during upload. Or the default URI which is userfile://defaultdb.public.userfiles_$username
___
*[v20.2/cockroach-userfile-delete.md, line 15 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKl4ueD1IEisTd_d8HS:-MKl4ueD1IEisTd_d8HT:b8n8eo4) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-delete.md#L15)):*
> ```
> Upload a file
> ```
should this be "delete a file"?
___
*[v20.2/cockroach-userfile-delete.md, line 54 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKl58TW2MAfTYxKNR1P:-MKl58TW2MAfTYxKNR1Q:bu7dp1z) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-delete.md#L54)):*
> ```
> the directory
> ```
*a fully qualified userfile URI was not specified...
___
*[v20.2/cockroach-userfile-delete.md, line 75 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKl6PPI5qxkFpeevg8r:-MKl6PPI5qxkFpeevg8s:b-ruykk9) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-delete.md#L75)):*
> ```
> *.csv
> ```
'*.csv' here and throughout this doc. doing * without quotes can be problematic if I remember from my testing because it takes all files from your local file system in that case.
___
*[v20.2/cockroach-userfile-delete.md, line 82 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKl5LTJ6FvwXzFDR2Kk:-MKl5LTJ6FvwXzFDR2Kl:b-uq60g2) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-delete.md#L82)):*
> ```Markdown
> deleted userfile://defaultdb.public.userfiles_root/test-data.csv
> ~~~
> ```

Do we want a section about how the user can provide a non-default userfile URI to delete from? So something like:
cockroach userfile delete userfile://defaultdb.public.this-is-the-name-i-gave/test-data.cscv

We have this for list and upload.
___
*[v20.2/cockroach-userfile-list.md, line 15 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKl5sLz37LK881nC0Yi:-MKl5sLz37LK881nC0Yj:b-8u4b6s) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-list.md#L15)):*
> ```
> Upload a file:
> ```
should this be list?
___
*[v20.2/cockroach-userfile-upload.md, line 39 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKlCfSlAhIj7xC6gwSE:-MKlCfSlAhIj7xC6gwSF:b-ucc27l) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-upload.md#L39)):*
> ```Markdown
> ## File destination
> 
> When an file is uploaded to userfile, there are two tables created: `files` and `payload`. The default URI is `userfile://defaultdb.public.userfiles_$user/`.
> ```

i'm a little concerned about how digestible this portion is for a user. Maybe we shouldn't dive into details about how we pick the table names but just outline the three behaviors with examples? I'll bring this up offline.
___
*[v20.2/cockroach-userfile-upload.md, line 55 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKlAwfV4t02Ik0PwgP7:-MKlAwfV4t02Ik0PwgP8:b-ajm6a1) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-upload.md#L55)):*
> ```
> All destination paths must start with `/`.
> ```
this is not true, you can just specify `test.csv` and it should work as well.
___
*[v20.2/cockroach-userfile-upload.md, line 56 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKlB6v5Dfo9n6vPCkkH:-MKlB6v5Dfo9n6vPCkkI:bcu23og) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-upload.md#L56)):*
> ```Markdown
> 
> - All destination paths must start with `/`.
> - Destination paths cannot contain `..`.
> ```

I think we should say that the supplied file path should be the same after normalization. If the user passes any path that post normalization results in a different path, we will reject it.


<!-- Sent from Reviewable.io -->

2020-10-29 21:22 UTC, lnhsingh reviewed
TFTR! PTAL at the updated File Destination section (on cockroach-userfile-upload.md - I also linked to this section from the other pages too)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8729#-:-MKqELdTCi1B_csO_22n:b-y6ulxq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @lnhsingh, and @mwang1026)

___
*[_includes/sidebar-data-v20.2.json, line 572 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKkOWmt0rDhvLefGBlL:-MKq7fKHDfgtrr-Vv6xS:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/_includes/sidebar-data-v20.2.json#L572)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

This should be "Userfile"
</blockquote></details>

Done.
___
*[v20.2/cockroach-userfile-delete.md, line 11 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKl4DA66CkhUB7ukztr:-MKpeW-ECXYLbc8bzepS:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-delete.md#L11)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

> ```
> CockroachD
> ```
nit: CockroachDB
</blockquote></details>

Done.
___
*[v20.2/cockroach-userfile-delete.md, line 11 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKl4IKN7aJObA1aVQVu:-MKpfZk27GweLyuQHVio:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-delete.md#L11)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

> ```
> .
> ```
might be worth adding that it will revoke all access from every other user in the cluster except root/admin.
</blockquote></details>

Done.
___
*[v20.2/cockroach-userfile-delete.md, line 11 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKl4XQ-3nmMNwMQhR5K:-MKqCjCj81yzEpTWqvNW:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-delete.md#L11)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

> ```
> subdirectory with the name matching their username
> ```
I think we can edit this line to say that a user can only delete data in his/her user scoped storage which they can reference via the userfile URI they provided during upload. Or the default URI which is userfile://defaultdb.public.userfiles_$username
</blockquote></details>

Done.
___
*[v20.2/cockroach-userfile-delete.md, line 15 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKl4ueD1IEisTd_d8HS:-MKpfuuf5yZ4aqCNXXIY:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-delete.md#L15)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

> ```
> Upload a file
> ```
should this be "delete a file"?
</blockquote></details>

Done.
___
*[v20.2/cockroach-userfile-delete.md, line 54 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKl58TW2MAfTYxKNR1P:-MKphZ7CDml8em9LzXvT:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-delete.md#L54)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

> ```
> the directory
> ```
*a fully qualified userfile URI was not specified...
</blockquote></details>

Done.
___
*[v20.2/cockroach-userfile-delete.md, line 75 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKl6PPI5qxkFpeevg8r:-MKq1yBxBDx9XLyyTQy9:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-delete.md#L75)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

> ```
> *.csv
> ```
'*.csv' here and throughout this doc. doing * without quotes can be problematic if I remember from my testing because it takes all files from your local file system in that case.
</blockquote></details>

Done.
___
*[v20.2/cockroach-userfile-delete.md, line 82 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKl5LTJ6FvwXzFDR2Kk:-MKq2P18-FQBTgyKAo6K:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-delete.md#L82)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

Do we want a section about how the user can provide a non-default userfile URI to delete from? So something like:
cockroach userfile delete userfile://defaultdb.public.this-is-the-name-i-gave/test-data.cscv

We have this for list and upload.
</blockquote></details>

Done.
___
*[v20.2/cockroach-userfile-list.md, line 15 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKl5sLz37LK881nC0Yi:-MKq2QEl0VYc2TEJeI8r:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-list.md#L15)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

> ```
> Upload a file:
> ```
should this be list?
</blockquote></details>

Done.
___
*[v20.2/cockroach-userfile-upload.md, line 39 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKlCfSlAhIj7xC6gwSE:-MKq9pE3EuQUBq5qxxvj:b-oo1r70) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-upload.md#L39)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

i'm a little concerned about how digestible this portion is for a user. Maybe we shouldn't dive into details about how we pick the table names but just outline the three behaviors with examples? I'll bring this up offline.
</blockquote></details>

Edited - PTAL
___
*[v20.2/cockroach-userfile-upload.md, line 55 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKlAwfV4t02Ik0PwgP7:-MKq4ZFSAIvm7anh63y2:bss4a2b) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-upload.md#L55)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

> ```
> All destination paths must start with `/`.
> ```
this is not true, you can just specify `test.csv` and it should work as well.
</blockquote></details>

Removed.
___
*[v20.2/cockroach-userfile-upload.md, line 56 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKlB6v5Dfo9n6vPCkkH:-MKq5rGnCOECA-BY4VHq:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-upload.md#L56)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

I think we should say that the supplied file path should be the same after normalization. If the user passes any path that post normalization results in a different path, we will reject it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-29 21:26 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4b7b8d4869ca8147a0f4e6e3a80da535ef60a8e7/

Edited pages:
- [v20.2/cockroach-commands.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4b7b8d4869ca8147a0f4e6e3a80da535ef60a8e7/v20.2/cockroach-commands.html)
- [v20.2/cockroach-nodelocal-upload.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4b7b8d4869ca8147a0f4e6e3a80da535ef60a8e7/v20.2/cockroach-nodelocal-upload.html)
- [v20.2/cockroach-userfile-delete.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4b7b8d4869ca8147a0f4e6e3a80da535ef60a8e7/v20.2/cockroach-userfile-delete.html)
- [v20.2/cockroach-userfile-list.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4b7b8d4869ca8147a0f4e6e3a80da535ef60a8e7/v20.2/cockroach-userfile-list.html)
- [v20.2/cockroach-userfile-upload.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4b7b8d4869ca8147a0f4e6e3a80da535ef60a8e7/v20.2/cockroach-userfile-upload.html)
- [v20.2/create-schedule-for-backup.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4b7b8d4869ca8147a0f4e6e3a80da535ef60a8e7/v20.2/create-schedule-for-backup.html)
- [v20.2/import.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4b7b8d4869ca8147a0f4e6e3a80da535ef60a8e7/v20.2/import.html)
- [v20.2/use-userfile-for-bulk-operations.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4b7b8d4869ca8147a0f4e6e3a80da535ef60a8e7/v20.2/use-userfile-for-bulk-operations.html)

2020-10-29 22:28 UTC, mwang1026 requested changes
I have to go take the kids now but I got through 80% of it. I'll take another pass maybe tomorrow.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8729#-:-MKqTP1JBd66iYQDfS67:b-3j1bkw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @lnhsingh, and @mwang1026)

___
*[_includes/v20.2/misc/userfile.md, line 2 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKCSiMs78m5cTwCVf95-r1-2:-MKqJFA3CbiztrWrApgH:bppsjl5) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/_includes/v20.2/misc/userfile.md#L2)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

more of a product question so maybe @mwang1026, but what do we mean by managed?
</blockquote></details>

I'm not sure what I meant by managed :joy: I think just saying `as it is user scoped and therefore more secure` is fine
___
*[v20.2/cockroach-userfile-delete.md, line 11 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKl4XQ-3nmMNwMQhR5K:-MKqK8BRDCQjLlvvDcUg:b24epxu) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-delete.md#L11)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can admin delete from any user @adityamaru ?
___
*[v20.2/cockroach-userfile-delete.md, line 11 at r2](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKqKBcvB-Ap2dtxtDsM:-MKqKBcvB-Ap2dtxtDsN:bb9dthb) ([raw file](https://github.com/cockroachdb/docs/blob/4b7b8d4869ca8147a0f4e6e3a80da535ef60a8e7/v20.2/cockroach-userfile-delete.md#L11)):*
> ```Markdown
> ## Required privileges
> 
> The user must have the `CREATE` [privilege](authorization.html#assign-privileges) on the target database. CockroachDB will proactively grant the user `GRANT`, `SELECT`, `INSERT`, `DROP`, `DELETE` on the metadata and file tables.
> ```

Is this true to use `delete`? I think the required permission for `delete` is just that they created it OR they are admin right @adityamaru ? Seems weird to mention requiring the `CREATE` privilege on the `cockroach userfile delete` doc
___
*[v20.2/cockroach-userfile-delete.md, line 20 at r2](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKqKUfE55th6eDcw-Dd:-MKqKUfE55th6eDcw-De:bpjp5cc) ([raw file](https://github.com/cockroachdb/docs/blob/4b7b8d4869ca8147a0f4e6e3a80da535ef60a8e7/v20.2/cockroach-userfile-delete.md#L20)):*
> ```
> list
> ```
uhh... `delete` right?
___
*[v20.2/cockroach-userfile-delete.md, line 26 at r2](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKqKX385H_GUFl9K9IC:-MKqKX385H_GUFl9K9ID:b5mse0q) ([raw file](https://github.com/cockroachdb/docs/blob/4b7b8d4869ca8147a0f4e6e3a80da535ef60a8e7/v20.2/cockroach-userfile-delete.md#L26)):*
> ```Markdown
> 
> ~~~ shell
> $ cockroach userfile list --help
> ```

same. should be `cockroach userfile delete`
___
*[v20.2/cockroach-userfile-list.md, line 11 at r2](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKqNJ7JC6Es6E69XHe8:-MKqNJ7JC6Es6E69XHe9:bzmqqg) ([raw file](https://github.com/cockroachdb/docs/blob/4b7b8d4869ca8147a0f4e6e3a80da535ef60a8e7/v20.2/cockroach-userfile-list.md#L11)):*
> ```Markdown
> ## Required privileges
> 
> The user must have the `CREATE` [privilege](authorization.html#assign-privileges) on the target database. CockroachD will proactively grant the user `GRANT`, `SELECT`, `INSERT`, `DROP`, `DELETE` on the metadata and file tables.
> ```

Same delete, in that I think the `CREATE `privilege is only relevant to uploading, right? @adityamaru to help confirm here. List privilege is same as delete (in that it's your files, or if you're admin)
___
*[v20.2/cockroach-userfile-upload.md, line 12 at r2](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKqOPrI5K_ATI4mFKni:-MKqOPrI5K_ATI4mFKnj:b-b6typ9) ([raw file](https://github.com/cockroachdb/docs/blob/4b7b8d4869ca8147a0f4e6e3a80da535ef60a8e7/v20.2/cockroach-userfile-upload.md#L12)):*
> ```Markdown
> 
> {{site.data.alerts.callout_note}}
> Userfile uses storage space in the cluster, and is replicated with the rest of the cluster's data. We recommended using `cockroach userfile upload` for quick imports from your client (about 15MB or smaller).
> ```

Wanted to confirm where we got that 15MB from?
___
*[v20.2/cockroach-userfile-upload.md, line 19 at r2](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKqPJJv2C1dh-2ZnZhL:-MKqPJJv2C1dh-2ZnZhM:b-ds0puz) ([raw file](https://github.com/cockroachdb/docs/blob/4b7b8d4869ca8147a0f4e6e3a80da535ef60a8e7/v20.2/cockroach-userfile-upload.md#L19)):*
> ```
> A user can only upload their user-scoped storage, which can be reference through the [userfile URI](#file-destination) provided
> ```

This sentence is confusing to me. What were you trying to say here?
___
*[v20.2/cockroach-userfile-upload.md, line 57 at r2](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKqPv-z8CZrOukSQm5_:-MKqPv-z8CZrOukSQm5a:bkr4yyk) ([raw file](https://github.com/cockroachdb/docs/blob/4b7b8d4869ca8147a0f4e6e3a80da535ef60a8e7/v20.2/cockroach-userfile-upload.md#L57)):*
> ```
> Therefore, a file with a `.tmp` prefix indicates that the upload may have only partially succeeded
> ```

This is a weird one. Maybe it's already implied with the prior sentence but it's more specifically if it has a .tmp suffix (I think type in this sentence too which says prefix) that you believe has completed upload, usually if for instance a connection drops during upload.


<!-- Sent from Reviewable.io -->

2020-10-30 14:56 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/30b50c86688af23a1fdbb596176631d86bd47112/

Edited pages:
- [v20.2/cockroach-commands.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/30b50c86688af23a1fdbb596176631d86bd47112/v20.2/cockroach-commands.html)
- [v20.2/cockroach-nodelocal-upload.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/30b50c86688af23a1fdbb596176631d86bd47112/v20.2/cockroach-nodelocal-upload.html)
- [v20.2/cockroach-userfile-delete.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/30b50c86688af23a1fdbb596176631d86bd47112/v20.2/cockroach-userfile-delete.html)
- [v20.2/cockroach-userfile-list.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/30b50c86688af23a1fdbb596176631d86bd47112/v20.2/cockroach-userfile-list.html)
- [v20.2/cockroach-userfile-upload.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/30b50c86688af23a1fdbb596176631d86bd47112/v20.2/cockroach-userfile-upload.html)
- [v20.2/create-schedule-for-backup.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/30b50c86688af23a1fdbb596176631d86bd47112/v20.2/create-schedule-for-backup.html)
- [v20.2/import.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/30b50c86688af23a1fdbb596176631d86bd47112/v20.2/import.html)
- [v20.2/use-userfile-for-bulk-operations.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/30b50c86688af23a1fdbb596176631d86bd47112/v20.2/use-userfile-for-bulk-operations.html)

2020-10-30 15:05 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03270ddc5c2dcefcd94e40d9e39e5d0a7fca3d82/

Edited pages:
- [v20.2/cockroach-commands.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03270ddc5c2dcefcd94e40d9e39e5d0a7fca3d82/v20.2/cockroach-commands.html)
- [v20.2/cockroach-nodelocal-upload.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03270ddc5c2dcefcd94e40d9e39e5d0a7fca3d82/v20.2/cockroach-nodelocal-upload.html)
- [v20.2/cockroach-userfile-delete.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03270ddc5c2dcefcd94e40d9e39e5d0a7fca3d82/v20.2/cockroach-userfile-delete.html)
- [v20.2/cockroach-userfile-list.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03270ddc5c2dcefcd94e40d9e39e5d0a7fca3d82/v20.2/cockroach-userfile-list.html)
- [v20.2/cockroach-userfile-upload.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03270ddc5c2dcefcd94e40d9e39e5d0a7fca3d82/v20.2/cockroach-userfile-upload.html)
- [v20.2/create-schedule-for-backup.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03270ddc5c2dcefcd94e40d9e39e5d0a7fca3d82/v20.2/create-schedule-for-backup.html)
- [v20.2/import.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03270ddc5c2dcefcd94e40d9e39e5d0a7fca3d82/v20.2/import.html)
- [v20.2/use-userfile-for-bulk-operations.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03270ddc5c2dcefcd94e40d9e39e5d0a7fca3d82/v20.2/use-userfile-for-bulk-operations.html)

2020-10-31 17:58 UTC, lnhsingh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8729)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @lnhsingh, and @mwang1026)

___
*[_includes/v20.2/misc/userfile.md, line 2 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKCSiMs78m5cTwCVf95-r1-2:-MKzjKV51r16_UVDVBGN:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/_includes/v20.2/misc/userfile.md#L2)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

I'm not sure what I meant by managed :joy: I think just saying `as it is user scoped and therefore more secure` is fine
</blockquote></details>

Done.
___
*[v20.2/cockroach-userfile-delete.md, line 20 at r2](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKqKUfE55th6eDcw-Dd:-MKzjU8aC-ODwZW69zHt:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/4b7b8d4869ca8147a0f4e6e3a80da535ef60a8e7/v20.2/cockroach-userfile-delete.md#L20)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

> ```
> list
> ```
uhh... `delete` right?
</blockquote></details>

Done.
___
*[v20.2/cockroach-userfile-delete.md, line 26 at r2](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKqKX385H_GUFl9K9IC:-MKzjVwg8qSKge-JAZb-:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/4b7b8d4869ca8147a0f4e6e3a80da535ef60a8e7/v20.2/cockroach-userfile-delete.md#L26)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

same. should be `cockroach userfile delete`
</blockquote></details>

Done.
___
*[v20.2/cockroach-userfile-upload.md, line 12 at r2](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKqOPrI5K_ATI4mFKni:-MKzjfCT2o8VInZLp1Cz:b-tlzr85) ([raw file](https://github.com/cockroachdb/docs/blob/4b7b8d4869ca8147a0f4e6e3a80da535ef60a8e7/v20.2/cockroach-userfile-upload.md#L12)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

Wanted to confirm where we got that 15MB from?
</blockquote></details>

DT mentioned in slack that we recommend a "small" file (he said no more than around 10 MB) but our test data files are about 15 MB so I fudged the number a bit. I can change to 10 MB if you're more comfortable with that.
___
*[v20.2/cockroach-userfile-upload.md, line 19 at r2](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKqPJJv2C1dh-2ZnZhL:-MKzkBLe9jObt6gszaRy:bcp4c74) ([raw file](https://github.com/cockroachdb/docs/blob/4b7b8d4869ca8147a0f4e6e3a80da535ef60a8e7/v20.2/cockroach-userfile-upload.md#L19)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

> ```
> A user can only upload their user-scoped storage, which can be reference through the [userfile URI](#file-destination) provided
> ```

This sentence is confusing to me. What were you trying to say here?
</blockquote></details>

Changed to "A user can only upload files to their own user-scoped storage, which is accessed through the userfile URI." Also updated this sentence on the other pages
___
*[v20.2/cockroach-userfile-upload.md, line 57 at r2](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKqPv-z8CZrOukSQm5_:-MKznsis0tRJ7OWHGemv:bymwld) ([raw file](https://github.com/cockroachdb/docs/blob/4b7b8d4869ca8147a0f4e6e3a80da535ef60a8e7/v20.2/cockroach-userfile-upload.md#L57)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

> ```
> Therefore, a file with a `.tmp` prefix indicates that the upload may have only partially succeeded
> ```

This is a weird one. Maybe it's already implied with the prior sentence but it's more specifically if it has a .tmp suffix (I think type in this sentence too which says prefix) that you believe has completed upload, usually if for instance a connection drops during upload.
</blockquote></details>

Reworded the sentence = PTAL


<!-- Sent from Reviewable.io -->

2020-10-31 18:01 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cc87bb1b0053878d0ba22a5afd15fdb93557a3f3/

Edited pages:
- [v20.2/cockroach-commands.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cc87bb1b0053878d0ba22a5afd15fdb93557a3f3/v20.2/cockroach-commands.html)
- [v20.2/cockroach-nodelocal-upload.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cc87bb1b0053878d0ba22a5afd15fdb93557a3f3/v20.2/cockroach-nodelocal-upload.html)
- [v20.2/cockroach-userfile-delete.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cc87bb1b0053878d0ba22a5afd15fdb93557a3f3/v20.2/cockroach-userfile-delete.html)
- [v20.2/cockroach-userfile-list.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cc87bb1b0053878d0ba22a5afd15fdb93557a3f3/v20.2/cockroach-userfile-list.html)
- [v20.2/cockroach-userfile-upload.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cc87bb1b0053878d0ba22a5afd15fdb93557a3f3/v20.2/cockroach-userfile-upload.html)
- [v20.2/create-schedule-for-backup.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cc87bb1b0053878d0ba22a5afd15fdb93557a3f3/v20.2/create-schedule-for-backup.html)
- [v20.2/import.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cc87bb1b0053878d0ba22a5afd15fdb93557a3f3/v20.2/import.html)
- [v20.2/use-userfile-for-bulk-operations.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cc87bb1b0053878d0ba22a5afd15fdb93557a3f3/v20.2/use-userfile-for-bulk-operations.html)

2020-11-01 19:37 UTC, adityamaru approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8729)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @lnhsingh, and @mwang1026)

___
*[v20.2/cockroach-userfile-delete.md, line 11 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKl4XQ-3nmMNwMQhR5K:-ML4FqDZ9WzQN1STWGE3:balz7hk) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-delete.md#L11)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

Can admin delete from any user @adityamaru ?
</blockquote></details>

Yeah admin/root can delete from any user.
___
*[v20.2/cockroach-userfile-delete.md, line 11 at r2](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKqKBcvB-Ap2dtxtDsM:-MKzoRyB5rZ57was0dQz:bf4oqrk) ([raw file](https://github.com/cockroachdb/docs/blob/4b7b8d4869ca8147a0f4e6e3a80da535ef60a8e7/v20.2/cockroach-userfile-delete.md#L11)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

Is this true to use `delete`? I think the required permission for `delete` is just that they created it OR they are admin right @adityamaru ? Seems weird to mention requiring the `CREATE` privilege on the `cockroach userfile delete` doc
</blockquote></details>

This is a weird one, if you run delete (or list) before having uploaded anything, we attempt to "create" the underlying userfile tables. So if the user does not have CREATE privileges then they will see an error to that effect. Arguably, some improvements can be made to decouple connecting to a userfile storage and creating one, but in the current implementation both those are the same method. So in some sense, the user will get a nicer error to the effect that "x is not found" if they have create privs in the first place.
___
*[v20.2/cockroach-userfile-list.md, line 11 at r2](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKqNJ7JC6Es6E69XHe8:-ML4GEIK4QOhDmuiHpL_:b-88kf0u) ([raw file](https://github.com/cockroachdb/docs/blob/4b7b8d4869ca8147a0f4e6e3a80da535ef60a8e7/v20.2/cockroach-userfile-list.md#L11)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

Same delete, in that I think the `CREATE `privilege is only relevant to uploading, right? @adityamaru to help confirm here. List privilege is same as delete (in that it's your files, or if you're admin)
</blockquote></details>

ditto response to above.
___
*[v20.2/cockroach-userfile-upload.md, line 50 at r5](https://reviewable.io/reviews/cockroachdb/docs/8729#-ML4Gfzl68hzBy9AA45e:-ML4Gfzl68hzBy9AA45f:b-sst7is) ([raw file](https://github.com/cockroachdb/docs/blob/cc87bb1b0053878d0ba22a5afd15fdb93557a3f3/v20.2/cockroach-userfile-upload.md#L50)):*
> ```
> path
> ```
path after normalization

Also can we move this to the notice below where it says userfile is not a file system?


<!-- Sent from Reviewable.io -->

2020-11-02 18:20 UTC, lnhsingh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8729)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @mwang1026)

___
*[v20.2/cockroach-userfile-delete.md, line 11 at r1](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKl4XQ-3nmMNwMQhR5K:-ML99peU-1bAUbuU_Qa1:bkec8qo) ([raw file](https://github.com/cockroachdb/docs/blob/755a5afa1b1d68b6d326ca7d5238bdc4ae1e06e5/v20.2/cockroach-userfile-delete.md#L11)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

Yeah admin/root can delete from any user.
</blockquote></details>

Added that info here.
___
*[v20.2/cockroach-userfile-delete.md, line 11 at r2](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKqKBcvB-Ap2dtxtDsM:-ML9A3m18M-PMy6kGFf9:b9bc380) ([raw file](https://github.com/cockroachdb/docs/blob/4b7b8d4869ca8147a0f4e6e3a80da535ef60a8e7/v20.2/cockroach-userfile-delete.md#L11)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

This is a weird one, if you run delete (or list) before having uploaded anything, we attempt to "create" the underlying userfile tables. So if the user does not have CREATE privileges then they will see an error to that effect. Arguably, some improvements can be made to decouple connecting to a userfile storage and creating one, but in the current implementation both those are the same method. So in some sense, the user will get a nicer error to the effect that "x is not found" if they have create privs in the first place.
</blockquote></details>

I'm going to leave as-is, unless you think otherwise.
___
*[v20.2/cockroach-userfile-list.md, line 11 at r2](https://reviewable.io/reviews/cockroachdb/docs/8729#-MKqNJ7JC6Es6E69XHe8:-ML9ACal4B6wTte8b2ny:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/4b7b8d4869ca8147a0f4e6e3a80da535ef60a8e7/v20.2/cockroach-userfile-list.md#L11)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

ditto response to above.
</blockquote></details>

Done.
___
*[v20.2/cockroach-userfile-upload.md, line 50 at r5](https://reviewable.io/reviews/cockroachdb/docs/8729#-ML4Gfzl68hzBy9AA45e:-ML9AvCS8GXr4a7tlLv7:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/cc87bb1b0053878d0ba22a5afd15fdb93557a3f3/v20.2/cockroach-userfile-upload.md#L50)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

> ```
> path
> ```
path after normalization

Also can we move this to the notice below where it says userfile is not a file system?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-02 18:24 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/460d53e1c14d17034d0415dce9b191e95c1bac0f/

Edited pages:
- [v20.2/cockroach-commands.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/cockroach-commands.html)
- [v20.2/cockroach-nodelocal-upload.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/cockroach-nodelocal-upload.html)
- [v20.2/cockroach-userfile-delete.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/cockroach-userfile-delete.html)
- [v20.2/cockroach-userfile-list.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/cockroach-userfile-list.html)
- [v20.2/cockroach-userfile-upload.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/cockroach-userfile-upload.html)
- [v20.2/create-schedule-for-backup.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/create-schedule-for-backup.html)
- [v20.2/import.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/import.html)
- [v20.2/use-userfile-for-bulk-operations.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/use-userfile-for-bulk-operations.html)

2020-11-02 19:06 UTC, adityamaru commented
This LGTM! Thank you for working through this 🙂

2020-11-03 15:00 UTC, lnhsingh commented
@adityamaru thank YOU!

@mwang1026 - I'm going to move this to Docs review to move this along a little, but feel free to add any additional feedback you have!

2020-11-04 16:41 UTC, mwang1026 approved these changes
One typo and one revision request. Otherwise LGTM so approving. Thanks!

> Reviewed 2 of 6 files at r2, 2 of 4 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8729#-:-MLJ7Q4iCSMRtks4wI7a:b-zfi0zo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @lnhsingh, @mwang1026, and @taroface)

___
*[v20.2/cockroach-userfile-upload.md, line 17 at r6](https://reviewable.io/reviews/cockroachdb/docs/8729#-MLJ52tv7k2M5VO1g9gy:-MLJ52twBF0AyGJUgk3P:b7e4diw) ([raw file](https://github.com/cockroachdb/docs/blob/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/cockroach-userfile-upload.md#L17)):*
> ```
> CockroachD
> ```
typo
___
*[v20.2/create-schedule-for-backup.md, line 43 at r6](https://reviewable.io/reviews/cockroachdb/docs/8729#-MLJ4eva-3GXIvGVBziB:-MLJ4evb3-Vn47tXPLYt:bvcmx9y) ([raw file](https://github.com/cockroachdb/docs/blob/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/create-schedule-for-backup.md#L43)):*
> ```Markdown
> `table_pattern`                         | The [table(s)](create-table.html) or [view(s)](views.html) you want to back up.
> `database_name`                         | The name of the [database(s)](create-database.html) you want to back up (i.e., create backups of all tables and views in the database).
> `location`                              | The URI where you want to store the backup. The backup files will be stored in year > month > day subdirectories. The location can be [cloud storage](use-cloud-storage-for-bulk-operations.html), `nodelocal`, or [`userfile`](use-userfile-for-bulk-operations.html).
> ```

IMO we shouldn't include userfile here since there's no command for retrieving those files yet (i.e. no `userfile get`)


<!-- Sent from Reviewable.io -->

2020-11-04 16:44 UTC, taroface approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8729)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @lnhsingh, and @mwang1026)

___
*[v20.2/cockroach-userfile-delete.md, line 7 at r6](https://reviewable.io/reviews/cockroachdb/docs/8729#-MLJ0Ibf2p4pSFu-0Wq9:-MLJ0Ibf2p4pSFu-0WqA:bcp473o) ([raw file](https://github.com/cockroachdb/docs/blob/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/cockroach-userfile-delete.md#L7)):*
nit: "which match" -> "that match"

> If passed the pattern `'*'`

Should this be "If the pattern `'*'` is passed", or something similar? I could be misreading.
___
*[v20.2/cockroach-userfile-delete.md, line 33 at r6](https://reviewable.io/reviews/cockroachdb/docs/8729#-MLJ0rNt-yO9PWJQq1G6:-MLJ0rNt-yO9PWJQq1G7:b1miq69) ([raw file](https://github.com/cockroachdb/docs/blob/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/cockroach-userfile-delete.md#L33)):*
> ```Markdown
>  Flag            | Description
> -----------------+-----------------------------------------------------
> `--cert-principal-map` | A comma separated list of `<cert-principal>:<db-principal>` mappings. This allows mapping the principal in a cert to a DB principal such as `node` or `root` or any SQL user. This is intended for use in situations where the certificate management system places restrictions on the `Subject.CommonName` or `SubjectAlternateName` fields in the certificate (e.g., disallowing a `CommonName` like `node` or `root`). If multiple mappings are provided for the same `<cert-principal>`, the last one specified in the list takes precedence. A principal not specified in the map is passed through as-is via the identity function. A cert is allowed to authenticate a DB principal if the DB principal name is contained in the mapped `CommonName` or DNS-type `SubjectAlternateName` fields.
> ```

Nit: "comma-separated"
___
*[v20.2/cockroach-userfile-list.md, line 11 at r6](https://reviewable.io/reviews/cockroachdb/docs/8729#-MLJ4Sno7ODx0u4tOxIa:-MLJ4Sno7ODx0u4tOxIb:bpua4ae) ([raw file](https://github.com/cockroachdb/docs/blob/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/cockroach-userfile-list.md#L11)):*
> ```
> CockroachD 
> ```

typo
___
*[v20.2/cockroach-userfile-list.md, line 33 at r6](https://reviewable.io/reviews/cockroachdb/docs/8729#-MLJ2iVU799MI7oiuVqB:-MLJ2iVU799MI7oiuVqC:b1miq69) ([raw file](https://github.com/cockroachdb/docs/blob/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/cockroach-userfile-list.md#L33)):*
> ```Markdown
>  Flag            | Description
> -----------------+-----------------------------------------------------
> `--cert-principal-map` | A comma separated list of `<cert-principal>:<db-principal>` mappings. This allows mapping the principal in a cert to a DB principal such as `node` or `root` or any SQL user. This is intended for use in situations where the certificate management system places restrictions on the `Subject.CommonName` or `SubjectAlternateName` fields in the certificate (e.g., disallowing a `CommonName` like `node` or `root`). If multiple mappings are provided for the same `<cert-principal>`, the last one specified in the list takes precedence. A principal not specified in the map is passed through as-is via the identity function. A cert is allowed to authenticate a DB principal if the DB principal name is contained in the mapped `CommonName` or DNS-type `SubjectAlternateName` fields.
> ```

Nit: "comma-separated"
___
*[v20.2/cockroach-userfile-upload.md, line 12 at r6](https://reviewable.io/reviews/cockroachdb/docs/8729#-MLJ8D4BC-ooTz87YsFO:-MLJ8D4BC-ooTz87YsFP:b-o7tzfp) ([raw file](https://github.com/cockroachdb/docs/blob/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/cockroach-userfile-upload.md#L12)):*
> ```
> Userfile
> ```

Should this either be "A userfile" or "`Userfile`" for consistency?
___
*[v20.2/cockroach-userfile-upload.md, line 17 at r6](https://reviewable.io/reviews/cockroachdb/docs/8729#-MLJ4h_x-gLfPjBEW-nb:-MLJ4h_x-gLfPjBEW-nc:beg2aai) ([raw file](https://github.com/cockroachdb/docs/blob/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/cockroach-userfile-upload.md#L17)):*
> ```
> CockroachD
> ```

typo
___
*[v20.2/cockroach-userfile-upload.md, line 47 at r6](https://reviewable.io/reviews/cockroachdb/docs/8729#-MLJ5OlS8PfQqAnZsUbZ:-MLJ5OlS8PfQqAnZsUb_:b4g4pqg) ([raw file](https://github.com/cockroachdb/docs/blob/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/cockroach-userfile-upload.md#L47)):*
> ```
> use use
> ```

will use
___
*[v20.2/cockroach-userfile-upload.md, line 64 at r6](https://reviewable.io/reviews/cockroachdb/docs/8729#-MLJ7alk6KUf0g__gNOu:-MLJ7alk6KUf0g__gNOv:b1miq69) ([raw file](https://github.com/cockroachdb/docs/blob/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/cockroach-userfile-upload.md#L64)):*
> ```Markdown
>  Flag            | Description
> -----------------+-----------------------------------------------------
> `--cert-principal-map` | A comma separated list of `<cert-principal>:<db-principal>` mappings. This allows mapping the principal in a cert to a DB principal such as `node` or `root` or any SQL user. This is intended for use in situations where the certificate management system places restrictions on the `Subject.CommonName` or `SubjectAlternateName` fields in the certificate (e.g., disallowing a `CommonName` like `node` or `root`). If multiple mappings are provided for the same `<cert-principal>`, the last one specified in the list takes precedence. A principal not specified in the map is passed through as-is via the identity function. A cert is allowed to authenticate a DB principal if the DB principal name is contained in the mapped `CommonName` or DNS-type `SubjectAlternateName` fields.
> ```

Nit: "comma-separated"


<!-- Sent from Reviewable.io -->

2020-11-04 17:53 UTC, lnhsingh reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8729#-:-MLJNzkv9bD5YsDRULif:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @mwang1026, and @taroface)

___
*[v20.2/cockroach-userfile-delete.md, line 7 at r6](https://reviewable.io/reviews/cockroachdb/docs/8729#-MLJ0Ibf2p4pSFu-0Wq9:-MLJJs6b9JI2fb5wDxa6:bt2vr1b) ([raw file](https://github.com/cockroachdb/docs/blob/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/cockroach-userfile-delete.md#L7)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

nit: "which match" -> "that match"

> If passed the pattern `'*'`

Should this be "If the pattern `'*'` is passed", or something similar? I could be misreading.
</blockquote></details>

Fixed.
___
*[v20.2/cockroach-userfile-delete.md, line 33 at r6](https://reviewable.io/reviews/cockroachdb/docs/8729#-MLJ0rNt-yO9PWJQq1G6:-MLJMS5-Bm_AARXW4P8F:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/cockroach-userfile-delete.md#L33)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Nit: "comma-separated"
</blockquote></details>

Done.
___
*[v20.2/cockroach-userfile-list.md, line 11 at r6](https://reviewable.io/reviews/cockroachdb/docs/8729#-MLJ4Sno7ODx0u4tOxIa:-MLJMXnO-KwKgeoZPuqG:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/cockroach-userfile-list.md#L11)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> CockroachD 
> ```

typo
</blockquote></details>

Done.
___
*[v20.2/cockroach-userfile-list.md, line 33 at r6](https://reviewable.io/reviews/cockroachdb/docs/8729#-MLJ2iVU799MI7oiuVqB:-MLJMZlb8wSoFm9J4T-c:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/cockroach-userfile-list.md#L33)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Nit: "comma-separated"
</blockquote></details>

Done.
___
*[v20.2/cockroach-userfile-upload.md, line 12 at r6](https://reviewable.io/reviews/cockroachdb/docs/8729#-MLJ8D4BC-ooTz87YsFO:-MLJMyFg5C3AsH32cGhh:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/cockroach-userfile-upload.md#L12)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> Userfile
> ```

Should this either be "A userfile" or "`Userfile`" for consistency?
</blockquote></details>

Done.
___
*[v20.2/cockroach-userfile-upload.md, line 17 at r6](https://reviewable.io/reviews/cockroachdb/docs/8729#-MLJ4h_x-gLfPjBEW-nb:-MLJN0lh6NtFSG5Uz_yT:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/cockroach-userfile-upload.md#L17)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> CockroachD
> ```

typo
</blockquote></details>

Done.
___
*[v20.2/cockroach-userfile-upload.md, line 17 at r6](https://reviewable.io/reviews/cockroachdb/docs/8729#-MLJ52tv7k2M5VO1g9gy:-MLJN0xCEDYFV8cWJ4wz:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/cockroach-userfile-upload.md#L17)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

> ```
> CockroachD
> ```
typo
</blockquote></details>

Done.
___
*[v20.2/cockroach-userfile-upload.md, line 47 at r6](https://reviewable.io/reviews/cockroachdb/docs/8729#-MLJ5OlS8PfQqAnZsUbZ:-MLJN49x0Now2vdoxwcY:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/cockroach-userfile-upload.md#L47)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> use use
> ```

will use
</blockquote></details>

Done.
___
*[v20.2/cockroach-userfile-upload.md, line 64 at r6](https://reviewable.io/reviews/cockroachdb/docs/8729#-MLJ7alk6KUf0g__gNOu:-MLJN9sE9f8gNxcyraH9:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/cockroach-userfile-upload.md#L64)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Nit: "comma-separated"
</blockquote></details>

Done.
___
*[v20.2/create-schedule-for-backup.md, line 43 at r6](https://reviewable.io/reviews/cockroachdb/docs/8729#-MLJ4eva-3GXIvGVBziB:-MLJNxc29WY7uB2skjsf:bss4a2b) ([raw file](https://github.com/cockroachdb/docs/blob/460d53e1c14d17034d0415dce9b191e95c1bac0f/v20.2/create-schedule-for-backup.md#L43)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

IMO we shouldn't include userfile here since there's no command for retrieving those files yet (i.e. no `userfile get`)
</blockquote></details>

Removed.


<!-- Sent from Reviewable.io -->

2020-11-04 17:56 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/132c7537a77e117e9fcf537ff10c8e6b0bf92cc6/

Edited pages:
- [v20.2/cockroach-commands.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/132c7537a77e117e9fcf537ff10c8e6b0bf92cc6/v20.2/cockroach-commands.html)
- [v20.2/cockroach-nodelocal-upload.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/132c7537a77e117e9fcf537ff10c8e6b0bf92cc6/v20.2/cockroach-nodelocal-upload.html)
- [v20.2/cockroach-userfile-delete.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/132c7537a77e117e9fcf537ff10c8e6b0bf92cc6/v20.2/cockroach-userfile-delete.html)
- [v20.2/cockroach-userfile-list.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/132c7537a77e117e9fcf537ff10c8e6b0bf92cc6/v20.2/cockroach-userfile-list.html)
- [v20.2/cockroach-userfile-upload.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/132c7537a77e117e9fcf537ff10c8e6b0bf92cc6/v20.2/cockroach-userfile-upload.html)
- [v20.2/create-schedule-for-backup.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/132c7537a77e117e9fcf537ff10c8e6b0bf92cc6/v20.2/create-schedule-for-backup.html)
- [v20.2/import.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/132c7537a77e117e9fcf537ff10c8e6b0bf92cc6/v20.2/import.html)
- [v20.2/use-userfile-for-bulk-operations.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/132c7537a77e117e9fcf537ff10c8e6b0bf92cc6/v20.2/use-userfile-for-bulk-operations.html)

2020-11-04 17:59 UTC, merged