Add docs for POINT, LINE, POLYGON, and collections
cockroachdb/docs pull request #8747
Opened 2020-10-23 20:35 UTC by rmloveland

Specifically, this change adds basic reference docs for the following
spatial objects:

- POINT
- LINESTRING
- POLYGON
- MULTIPOINT
- MULTILINESTRING
- MULTIPOLYGON
- GEOMETRYCOLLECTION

Fixes #8567, #8568, #8569, #8570.

2020-10-23 20:35 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/8747)
<!-- Reviewable:end -->

2020-10-23 20:39 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3e2f2bfc7317fb392c003bcc8f790440b3c21b1f/

Edited pages:
- [v20.2/geometrycollection.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3e2f2bfc7317fb392c003bcc8f790440b3c21b1f/v20.2/geometrycollection.html)
- [v20.2/linestring.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3e2f2bfc7317fb392c003bcc8f790440b3c21b1f/v20.2/linestring.html)
- [v20.2/multilinestring.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3e2f2bfc7317fb392c003bcc8f790440b3c21b1f/v20.2/multilinestring.html)
- [v20.2/multipoint.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3e2f2bfc7317fb392c003bcc8f790440b3c21b1f/v20.2/multipoint.html)
- [v20.2/multipolygon.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3e2f2bfc7317fb392c003bcc8f790440b3c21b1f/v20.2/multipolygon.html)
- [v20.2/point.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3e2f2bfc7317fb392c003bcc8f790440b3c21b1f/v20.2/point.html)
- [v20.2/polygon.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3e2f2bfc7317fb392c003bcc8f790440b3c21b1f/v20.2/polygon.html)
- [v20.2/spatial-features.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3e2f2bfc7317fb392c003bcc8f790440b3c21b1f/v20.2/spatial-features.html)

2020-10-23 23:12 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7afebec09dede98c63723143b04464a3e80f43ee/

Edited pages:
- [v20.2/geometrycollection.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7afebec09dede98c63723143b04464a3e80f43ee/v20.2/geometrycollection.html)
- [v20.2/linestring.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7afebec09dede98c63723143b04464a3e80f43ee/v20.2/linestring.html)
- [v20.2/multilinestring.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7afebec09dede98c63723143b04464a3e80f43ee/v20.2/multilinestring.html)
- [v20.2/multipoint.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7afebec09dede98c63723143b04464a3e80f43ee/v20.2/multipoint.html)
- [v20.2/multipolygon.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7afebec09dede98c63723143b04464a3e80f43ee/v20.2/multipolygon.html)
- [v20.2/point.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7afebec09dede98c63723143b04464a3e80f43ee/v20.2/point.html)
- [v20.2/polygon.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7afebec09dede98c63723143b04464a3e80f43ee/v20.2/polygon.html)
- [v20.2/spatial-features.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7afebec09dede98c63723143b04464a3e80f43ee/v20.2/spatial-features.html)

2020-10-26 18:55 UTC, sumeerbhola requested changes
Generally looks good.

> Reviewed 8 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8747#-:-MKaFwkzDwnwVaL1bTDw:b8x89dh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rmloveland)

___
*[v20.2/geometrycollection.md, line 7 at r1](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKaBWIsAMXcYghyjppW:-MKaBWIt6BAEM-r0uG2e:b-ipv94i) ([raw file](https://github.com/cockroachdb/docs/blob/7afebec09dede98c63723143b04464a3e80f43ee/v20.2/geometrycollection.md#L7)):*
> ```Markdown
> ---
> 
> A `GEOMETRYCOLLECTION` is a "box" or "bag" used for gathering 1 or more of the other types of [spatial objects](spatial-features.html#spatial-objects) into a group: namely, [Points](point.html), [Linestrings](linestring.html), or [Polygons](polygon.html). It provides a way of referring to a group of spatial objects as one "thing" so that you can operate on it/them more conveniently using various SQL functions.
> ```

I think we can simplify to (it is important to mention heterogeneous and that it can contain other GEOMETRYCOLLECTIONs) :
A GEOMETRYCOLLECTION is a bag or collection of heterogeneous spatial objects, such as Points, Linestrings etc. A GEOMETRYCOLLECTION can contain other GEOMETRYCOLLECTIONs. It provides ... 
___
*[v20.2/linestring.md, line 7 at r1](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKaCZg294KJrCj49I6B:-MKaCZg294KJrCj49I6C:b9upm3b) ([raw file](https://github.com/cockroachdb/docs/blob/7afebec09dede98c63723143b04464a3e80f43ee/v20.2/linestring.md#L7)):*
> ```Markdown
> ---
> 
> A `LINESTRING` is a collection of [Points](point.html) that are "strung together" into one geometric object, like a necklace. If the "necklace" were "closed", it could also represent a [Polygon](polygon.html). A Linestring can also be used to represent an arbitrary curve, such as a [Bézier curve](https://en.wikipedia.org/wiki/Bézier_curve).
> ```

suggest removing the "like a necklace", since that suggests closed. Also, I don't think we should mention `POLYGON` here -- that it a different type. It may be helpful to give some examples of things that LINESTRING is useful for e.g. roads, rivers. 
___
*[v20.2/multilinestring.md, line 11 at r1](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKaDxGK96eu6bm24JKS:-MKaDxGK96eu6bm24JKT:bk5tr3n) ([raw file](https://github.com/cockroachdb/docs/blob/7afebec09dede98c63723143b04464a3e80f43ee/v20.2/multilinestring.md#L11)):*
> ```Markdown
> ## Examples
> 
> A MultiLinestring can be created from SQL by calling the `st_geomfromtext` function on a MultiLinestring definition expressed in the [Well Known Text (WKT)](spatial-glossary.html#wkt) format.
> ```

We should also mention `ST_Collect` -- we implement the aggregator https://postgis.net/docs/ST_Collect.html
___
*[v20.2/multipoint.md, line 11 at r1](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKaENX7ASUkKMfMK3DQ:-MKaENX7ASUkKMfMK3DR:bv002ym) ([raw file](https://github.com/cockroachdb/docs/blob/7afebec09dede98c63723143b04464a3e80f43ee/v20.2/multipoint.md#L11)):*
> ```Markdown
> ## Examples
> 
> A MultiPoint can be created from SQL by calling the `st_geomfromtext` function on a MultiPoint definition expressed in the [Well Known Text (WKT)](spatial-glossary.html#wkt) format.
> ```

ditto, about mentioning `ST_Collect`.
___
*[v20.2/multipolygon.md, line 7 at r1](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKaEhDR5W4nnweLAzdr:-MKaEhDR5W4nnweLAzds:b-lppoxu) ([raw file](https://github.com/cockroachdb/docs/blob/7afebec09dede98c63723143b04464a3e80f43ee/v20.2/multipolygon.md#L7)):*
> ```Markdown
> ---
> 
> A `MULTIPOLYGON` is a collection of [Polygons](polygon.html).  MultiPolygons are useful for gathering a group of Polygons into one geometry: for example, you may want to gather the Polygons denoting a group of properties in a particular municipality.
> ```

Also states/countries with islands would be represented using a multipolygon.
___
*[v20.2/polygon.md, line 7 at r1](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKaExEb0bYcia43SdLv:-MKaExEb0bYcia43SdLw:b-tp2s7e) ([raw file](https://github.com/cockroachdb/docs/blob/7afebec09dede98c63723143b04464a3e80f43ee/v20.2/polygon.md#L7)):*
> ```Markdown
> ---
> 
> A `POLYGON` is a closed shape that can be made up of straight or curved lines. It can be thought of as a "closed" [Linestring](linestring.html). Irregular Polygons can take on almost any arbitrary shape. Common regular Polygons include: squares, rectangles, hexagons, and so forth. For more information about regular Polygons, see the ['Regular polygon' Wikipedia article](https://en.wikipedia.org/wiki/Regular_polygon).
> ```

I am guessing "curved lines" is a reference to spherical geometry, where lines align with great circles. If so, I think it will confuse readers -- we should just say line.

Also, I don't think we need to talk about regular polygons since in modeling the real world it does not matter whether it is regular or not. It is more important to talk about polygons with holes (the PostGIS documentation also mentions those http://postgis.net/workshops/postgis-intro/geometries.html)


<!-- Sent from Reviewable.io -->

2020-10-27 14:19 UTC, rmloveland reviewed
Thanks for the review, Sumeer!  I have tried to address your feedback below.  PTAL - happy to make any additional changes needed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8747#-:-MKePd9D521FyRKTnZRa:b-7selv7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[v20.2/geometrycollection.md, line 7 at r1](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKaBWIsAMXcYghyjppW:-MKePRqH8aqAnJ_DGyzi:bgcfosk) ([raw file](https://github.com/cockroachdb/docs/blob/7afebec09dede98c63723143b04464a3e80f43ee/v20.2/geometrycollection.md#L7)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think we can simplify to (it is important to mention heterogeneous and that it can contain other GEOMETRYCOLLECTIONs) :
A GEOMETRYCOLLECTION is a bag or collection of heterogeneous spatial objects, such as Points, Linestrings etc. A GEOMETRYCOLLECTION can contain other GEOMETRYCOLLECTIONs. It provides ... 
</blockquote></details>

Updated to this language - thanks!
___
*[v20.2/linestring.md, line 7 at r1](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKaCZg294KJrCj49I6B:-MKePU209-W8FFqGqhM_:bemodkc) ([raw file](https://github.com/cockroachdb/docs/blob/7afebec09dede98c63723143b04464a3e80f43ee/v20.2/linestring.md#L7)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

suggest removing the "like a necklace", since that suggests closed. Also, I don't think we should mention `POLYGON` here -- that it a different type. It may be helpful to give some examples of things that LINESTRING is useful for e.g. roads, rivers. 
</blockquote></details>

Updated - PTAL
___
*[v20.2/multilinestring.md, line 11 at r1](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKaDxGK96eu6bm24JKS:-MKeJMAg9_7qTakEK_Gy:b-fcdwvi) ([raw file](https://github.com/cockroachdb/docs/blob/7afebec09dede98c63723143b04464a3e80f43ee/v20.2/multilinestring.md#L11)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We should also mention `ST_Collect` -- we implement the aggregator https://postgis.net/docs/ST_Collect.html
</blockquote></details>

Done!  Added a second example that mentions `st_collect` and `st_union` - ended up using `st_union` because that is on the shortlist of the first batch of spatial functions we need docs for in the release.  Once #8735 is in we can link to it.

However, please let me know if using `ST_Union` instead of `ST_Collect` causes an issue (my understanding is that `ST_Union` merges/modifies the geometries), and I can change it if needed.
___
*[v20.2/multipoint.md, line 11 at r1](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKaENX7ASUkKMfMK3DQ:-MKeJufK5J8OHnnSac3I:b-n8c94i) ([raw file](https://github.com/cockroachdb/docs/blob/7afebec09dede98c63723143b04464a3e80f43ee/v20.2/multipoint.md#L11)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

ditto, about mentioning `ST_Collect`.
</blockquote></details>

Added - using same strategy / format as above.
___
*[v20.2/multipolygon.md, line 7 at r1](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKaEhDR5W4nnweLAzdr:-MKeKKHQ9rIRR2b8e3m-:blvr7us) ([raw file](https://github.com/cockroachdb/docs/blob/7afebec09dede98c63723143b04464a3e80f43ee/v20.2/multipolygon.md#L7)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Also states/countries with islands would be represented using a multipolygon.
</blockquote></details>

Thanks, added a line mentioning that
___
*[v20.2/polygon.md, line 7 at r1](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKaExEb0bYcia43SdLv:-MKePClR1w2CDRr9veph:b-rnnz3i) ([raw file](https://github.com/cockroachdb/docs/blob/7afebec09dede98c63723143b04464a3e80f43ee/v20.2/polygon.md#L7)):*
OK - Updated to say

> A `POLYGON` is a shape with a closed exterior that is made up of lines. Polygons can also contain holes.  Polygons are often used to represent areas such as countries, states, or municipalities.

Also, added an example of a polygon with a hole to the examples at the bottom of the page


<!-- Sent from Reviewable.io -->

2020-10-27 14:23 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/af26ff9cb14f9b02d9b04292ae74d1000b0e1f5e/

Edited pages:
- [v20.2/geometrycollection.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/af26ff9cb14f9b02d9b04292ae74d1000b0e1f5e/v20.2/geometrycollection.html)
- [v20.2/linestring.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/af26ff9cb14f9b02d9b04292ae74d1000b0e1f5e/v20.2/linestring.html)
- [v20.2/multilinestring.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/af26ff9cb14f9b02d9b04292ae74d1000b0e1f5e/v20.2/multilinestring.html)
- [v20.2/multipoint.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/af26ff9cb14f9b02d9b04292ae74d1000b0e1f5e/v20.2/multipoint.html)
- [v20.2/multipolygon.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/af26ff9cb14f9b02d9b04292ae74d1000b0e1f5e/v20.2/multipolygon.html)
- [v20.2/point.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/af26ff9cb14f9b02d9b04292ae74d1000b0e1f5e/v20.2/point.html)
- [v20.2/polygon.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/af26ff9cb14f9b02d9b04292ae74d1000b0e1f5e/v20.2/polygon.html)
- [v20.2/spatial-features.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/af26ff9cb14f9b02d9b04292ae74d1000b0e1f5e/v20.2/spatial-features.html)

2020-10-27 14:48 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8747#-:-MKeX1O35HbuhXG0e3AO:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rmloveland and @sumeerbhola)

___
*[v20.2/multilinestring.md, line 44 at r2](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKeVozp6Wrh5TCtpoQc:-MKeVozp6Wrh5TCtpoQd:b-qpc761) ([raw file](https://github.com/cockroachdb/docs/blob/af26ff9cb14f9b02d9b04292ae74d1000b0e1f5e/v20.2/multilinestring.md#L44)):*
> ```Markdown
> ~~~
> 
> Next, build a MultiLinestring from the individual [Linestrings](linestring.html) using `ST_Union`, and check the output with `ST_GeometryType` to verify that it is indeed a MultiLinestring:
> ```

I wonder if this will make someone believe that it should always be a MultiLineString. `ST_Union` is a geometric union (unlike `ST_Collect`) so depending on the input it could return another LineString.
___
*[v20.2/multipoint.md, line 28 at r2](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKeWX0C1OBn3sJEEGlx:-MKeWX0C1OBn3sJEEGly:bhbka2n) ([raw file](https://github.com/cockroachdb/docs/blob/af26ff9cb14f9b02d9b04292ae74d1000b0e1f5e/v20.2/multipoint.md#L28)):*
> ```Markdown
> ~~~
> 
> Next, build a MultiPoint from the individual [Points](point.html) using `ST_Union`, and check the output with `ST_GeometryType` to verify that it is indeed a MultiPoint:
> ```

Same comment as LineString. If the input points are the same, I believe the output is a Point.
___
*[v20.2/multipolygon.md, line 7 at r2](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKeWoXj2BhGzl_z-M0F:-MKeWoXj2BhGzl_z-M0G:b-yy46vk) ([raw file](https://github.com/cockroachdb/docs/blob/af26ff9cb14f9b02d9b04292ae74d1000b0e1f5e/v20.2/multipolygon.md#L7)):*
> ```Markdown
> ---
> 
> A `MULTIPOLYGON` is a collection of [Polygons](polygon.html).  MultiPolygons are useful for gathering a group of Polygons into one geometry: for example, you may want to gather the Polygons denoting a group of properties in a particular municipality.  Another use of MultiPolygons is to represent states or countries that include islands, or that are otherwise made up of physically distinct shapes.
> ```

how about "non-overlapping shapes"?


<!-- Sent from Reviewable.io -->

2020-10-27 20:51 UTC, rmloveland reviewed
Thanks Sumeer!  Updated per your latest comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8747#-:-MKfmXyP6feWq-pOY8Ey:b-j1hwo2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[v20.2/multilinestring.md, line 44 at r2](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKeVozp6Wrh5TCtpoQc:-MKflw2v5hs0HUfgkP--:b-ty6biw) ([raw file](https://github.com/cockroachdb/docs/blob/af26ff9cb14f9b02d9b04292ae74d1000b0e1f5e/v20.2/multilinestring.md#L44)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I wonder if this will make someone believe that it should always be a MultiLineString. `ST_Union` is a geometric union (unlike `ST_Collect`) so depending on the input it could return another LineString.
</blockquote></details>

Makes sense - updated to use `ST_Collect`
___
*[v20.2/multipoint.md, line 28 at r2](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKeWX0C1OBn3sJEEGlx:-MKfmHeL-gdOvxPN8SVB:b-o09wlj) ([raw file](https://github.com/cockroachdb/docs/blob/af26ff9cb14f9b02d9b04292ae74d1000b0e1f5e/v20.2/multipoint.md#L28)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Same comment as LineString. If the input points are the same, I believe the output is a Point.
</blockquote></details>

Also updated to use `ST_Collect`
___
*[v20.2/multipolygon.md, line 7 at r2](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKeWoXj2BhGzl_z-M0F:-MKfmRjN-p7sSn177lt8:bp8fwl5) ([raw file](https://github.com/cockroachdb/docs/blob/af26ff9cb14f9b02d9b04292ae74d1000b0e1f5e/v20.2/multipolygon.md#L7)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

how about "non-overlapping shapes"?
</blockquote></details>

Sounds good!  Updated to use that instead.


<!-- Sent from Reviewable.io -->

2020-10-27 20:56 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a14e31705dea9ef8594c85c1f5ce11a776388bb1/

Edited pages:
- [v20.2/geometrycollection.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a14e31705dea9ef8594c85c1f5ce11a776388bb1/v20.2/geometrycollection.html)
- [v20.2/linestring.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a14e31705dea9ef8594c85c1f5ce11a776388bb1/v20.2/linestring.html)
- [v20.2/multilinestring.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a14e31705dea9ef8594c85c1f5ce11a776388bb1/v20.2/multilinestring.html)
- [v20.2/multipoint.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a14e31705dea9ef8594c85c1f5ce11a776388bb1/v20.2/multipoint.html)
- [v20.2/multipolygon.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a14e31705dea9ef8594c85c1f5ce11a776388bb1/v20.2/multipolygon.html)
- [v20.2/point.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a14e31705dea9ef8594c85c1f5ce11a776388bb1/v20.2/point.html)
- [v20.2/polygon.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a14e31705dea9ef8594c85c1f5ce11a776388bb1/v20.2/polygon.html)
- [v20.2/spatial-features.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a14e31705dea9ef8594c85c1f5ce11a776388bb1/v20.2/spatial-features.html)

2020-10-28 13:52 UTC, otan reviewed
(quick chime, hope you don't mind @rmloveland !)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8747#-:-MKjTau17lFkakDhgKSi:b-w7mby5)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rmloveland and @sumeerbhola)

___
*[v20.2/linestring.md, line 7 at r3](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKjTMZb5BL3zrTZbJNv:-MKjTMZb5BL3zrTZbJNw:b-qovvkb) ([raw file](https://github.com/cockroachdb/docs/blob/a14e31705dea9ef8594c85c1f5ce11a776388bb1/v20.2/linestring.md#L7)):*
> ```Markdown
> ---
> 
> A `LINESTRING` is a collection of [Points](point.html) that are "strung together" into one geometric object. A Linestring can be used to represent an arbitrary curve, such as a [Bézier curve](https://en.wikipedia.org/wiki/Bézier_curve).  In practice, this means that Linestrings are useful for representing real-world objects such as roads and rivers.
> ```

we seem to change upper LINESTRING and Linestring here. I think LineString is the correct non-lowercased version here, but curious when we use the upper and lowercased versions.
___
*[v20.2/multipoint.md, line 32 at r3](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKjTTuRE_KXYzHwF19z:-MKjTTuRE_KXYzHwF1A-:bxx45jf) ([raw file](https://github.com/cockroachdb/docs/blob/a14e31705dea9ef8594c85c1f5ce11a776388bb1/v20.2/multipoint.md#L32)):*
> ```Markdown
> {% include copy-clipboard.html %}
> ~~~ sql
> SELECT st_geometrytype(st_collect(geom)) AS output FROM tmp_points;
> ```

can we use the casing that seems consistent with PostGIS, i.e. ST_GeometryType/ST_Collect for all of these?


<!-- Sent from Reviewable.io -->

2020-10-29 14:09 UTC, rmloveland reviewed
np - thanks Oliver!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8747#-:-MKoegR1BsDNDf6-FqqR:b2b0n6n)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ericharmeling, @otan, and @sumeerbhola)

___
*[v20.2/linestring.md, line 7 at r3](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKjTMZb5BL3zrTZbJNv:-MKoei_yCP8zbTpYY419:bhgq89y) ([raw file](https://github.com/cockroachdb/docs/blob/a14e31705dea9ef8594c85c1f5ce11a776388bb1/v20.2/linestring.md#L7)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

we seem to change upper LINESTRING and Linestring here. I think LineString is the correct non-lowercased version here, but curious when we use the upper and lowercased versions.
</blockquote></details>

Makes sense - just changed everything that said 'Linestring' in prose to 'LineString'.  I am leaving the "code+caps" versions for now though, so when #8782 is in I can come back and link these mentions to the WKT docs as well.
___
*[v20.2/multipoint.md, line 32 at r3](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKjTTuRE_KXYzHwF19z:-MKofo7tAvAHhb-8ADNA:b-7fpwt5) ([raw file](https://github.com/cockroachdb/docs/blob/a14e31705dea9ef8594c85c1f5ce11a776388bb1/v20.2/multipoint.md#L32)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

can we use the casing that seems consistent with PostGIS, i.e. ST_GeometryType/ST_Collect for all of these?
</blockquote></details>

Yes!  I have ST_Edited all of the ST_Examples from this ST_PullRequest :-} 


<!-- Sent from Reviewable.io -->

2020-10-29 14:13 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3c5bfc4a63c1eaaf1aa5a5364f5cf77966c10f41/

Edited pages:
- [v20.2/geometrycollection.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3c5bfc4a63c1eaaf1aa5a5364f5cf77966c10f41/v20.2/geometrycollection.html)
- [v20.2/linestring.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3c5bfc4a63c1eaaf1aa5a5364f5cf77966c10f41/v20.2/linestring.html)
- [v20.2/multilinestring.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3c5bfc4a63c1eaaf1aa5a5364f5cf77966c10f41/v20.2/multilinestring.html)
- [v20.2/multipoint.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3c5bfc4a63c1eaaf1aa5a5364f5cf77966c10f41/v20.2/multipoint.html)
- [v20.2/multipolygon.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3c5bfc4a63c1eaaf1aa5a5364f5cf77966c10f41/v20.2/multipolygon.html)
- [v20.2/point.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3c5bfc4a63c1eaaf1aa5a5364f5cf77966c10f41/v20.2/point.html)
- [v20.2/polygon.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3c5bfc4a63c1eaaf1aa5a5364f5cf77966c10f41/v20.2/polygon.html)
- [v20.2/spatial-features.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3c5bfc4a63c1eaaf1aa5a5364f5cf77966c10f41/v20.2/spatial-features.html)
- [v20.2/spatial-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3c5bfc4a63c1eaaf1aa5a5364f5cf77966c10f41/v20.2/spatial-indexes.html)

2020-10-29 20:22 UTC, ericharmeling approved these changes
LGTM! Had only a few comments. Just nits, really.

> Reviewed 1 of 9 files at r1, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8747#-:-MKq0V4R4H96kvA1cSP9:b2oe7kl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan, @rmloveland, and @sumeerbhola)

___
*[v20.2/geometrycollection.md, line 7 at r4](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKpn9Ru9OQfvCXahlOb:-MKpn9Rv-JZLlYOu2UKa:bnol69) ([raw file](https://github.com/cockroachdb/docs/blob/3c5bfc4a63c1eaaf1aa5a5364f5cf77966c10f41/v20.2/geometrycollection.md#L7)):*
> ```
> a bag or collection
> ```

Can we just say "collection"?
___
*[v20.2/geometrycollection.md, line 11 at r4](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKppMYc1VLeizDLDe63:-MKppMYd41wx5mFJjjM9:bz3zlh2) ([raw file](https://github.com/cockroachdb/docs/blob/3c5bfc4a63c1eaaf1aa5a5364f5cf77966c10f41/v20.2/geometrycollection.md#L11)):*
> ```
> GeometryCollection
> ```

Should this (and all other instances) be `GEOMETRYCOLLECTION`? I guess this is a more general comment on how we want to represent these objects in prose format.
___
*[v20.2/linestring.md, line 7 at r4](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKppWm57Lmj7yIDtjyA:-MKppWm57Lmj7yIDtjyB:b-nssceo) ([raw file](https://github.com/cockroachdb/docs/blob/3c5bfc4a63c1eaaf1aa5a5364f5cf77966c10f41/v20.2/linestring.md#L7)):*
> ```
> Bézier
> ```

Fancy :)
___
*[v20.2/multilinestring.md, line 7 at r4](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKpusfv1ZhJYM_nbkH-:-MKpusfv1ZhJYM_nbkH0:b-6gx3vy) ([raw file](https://github.com/cockroachdb/docs/blob/3c5bfc4a63c1eaaf1aa5a5364f5cf77966c10f41/v20.2/multilinestring.md#L7)):*
> ```
> geometry: for
> ```

nit:

geometry. For
___
*[v20.2/multilinestring.md, line 29 at r4](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKpvHELCSE_ATf70kLu:-MKpvHELCSE_ATf70kLv:b-6bnt08) ([raw file](https://github.com/cockroachdb/docs/blob/3c5bfc4a63c1eaaf1aa5a5364f5cf77966c10f41/v20.2/multilinestring.md#L29)):*
> ```
> `ST_Collect` or `ST_Union`
> ```

Once those docs merge, would be nice to add the link once that's all merged. (I think you mention that here or in that PR).
___
*[v20.2/multipoint.md, line 7 at r4](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKpxOvN2xiMo5qCYfX8:-MKpxOvN2xiMo5qCYfX9:b-epjd92) ([raw file](https://github.com/cockroachdb/docs/blob/3c5bfc4a63c1eaaf1aa5a5364f5cf77966c10f41/v20.2/multipoint.md#L7)):*
> ```
> geometry: for
> ```

nit: 

geometry. For example,
___
*[v20.2/multipolygon.md, line 7 at r4](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKpy8XIAgehLpSktnQw:-MKpy8XJ6VMi8VccZGLN:bbkl1yr) ([raw file](https://github.com/cockroachdb/docs/blob/3c5bfc4a63c1eaaf1aa5a5364f5cf77966c10f41/v20.2/multipolygon.md#L7)):*
> ```
> geometry: for
> ```

geometry. For


<!-- Sent from Reviewable.io -->

2020-10-30 15:28 UTC, rmloveland reviewed
Thanks for the review Eric!  I think all is fixed.

PS I had to fix some conflicts when rebasing on master (merged the ST_OtherPR with the ST_Functions), but should be green now.  Sorry if it creates extra noise.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8747#-:-MKu5Ysf5R5_pXeE6W5C:baspxee)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ericharmeling, @otan, and @sumeerbhola)

___
*[v20.2/geometrycollection.md, line 7 at r4](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKpn9Ru9OQfvCXahlOb:-MKu3Ojx5qy2-LA7cma5:b-896fja) ([raw file](https://github.com/cockroachdb/docs/blob/3c5bfc4a63c1eaaf1aa5a5364f5cf77966c10f41/v20.2/geometrycollection.md#L7)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> a bag or collection
> ```

Can we just say "collection"?
</blockquote></details>

Done!
___
*[v20.2/geometrycollection.md, line 11 at r4](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKppMYc1VLeizDLDe63:-MKu3R1tA-ZRv0PQIpHg:bup31zn) ([raw file](https://github.com/cockroachdb/docs/blob/3c5bfc4a63c1eaaf1aa5a5364f5cf77966c10f41/v20.2/geometrycollection.md#L11)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> GeometryCollection
> ```

Should this (and all other instances) be `GEOMETRYCOLLECTION`? I guess this is a more general comment on how we want to represent these objects in prose format.
</blockquote></details>

Maybe!  In a different review convo with Oliver, my hallucination at that time was: for the most part, we want to represent the objects in prose using CamelCase, e.g. GeometryCollection.  For the cases where we mention them in code font, that's the "Well Known Text" representation, which I will link to the WKT docs once that other PR is in.

I think I will go back once the separate WKT docs PR is merged and:

- Link mentions of 'GeometryCollection' to this doc (unless they are in this doc :-} )
- Link mentions of objects that are expressed in code font (such as `GEOMETRYCOLLECTION`) to the Well Known Text (WKT) docs, since that is another format in which such objects can be expressed to the DB

Basically I'm trying to maximize the cross-linkage between:

- thing
- textual representation of thing in data format
___
*[v20.2/linestring.md, line 7 at r4](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKppWm57Lmj7yIDtjyA:-MKu5LZV3rxfrDaBpMq3:bz0h7vp) ([raw file](https://github.com/cockroachdb/docs/blob/3c5bfc4a63c1eaaf1aa5a5364f5cf77966c10f41/v20.2/linestring.md#L7)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> Bézier
> ```

Fancy :)
</blockquote></details>

Ha!  So rare for me to venture beyond ASCII - luckily my editor knows all the Unicode names cuz I don't :-} 
___
*[v20.2/multilinestring.md, line 7 at r4](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKpusfv1ZhJYM_nbkH-:-MKu4ebOE1Bj6S8SErNH:b-896fja) ([raw file](https://github.com/cockroachdb/docs/blob/3c5bfc4a63c1eaaf1aa5a5364f5cf77966c10f41/v20.2/multilinestring.md#L7)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> geometry: for
> ```

nit:

geometry. For
</blockquote></details>

Done!
___
*[v20.2/multilinestring.md, line 29 at r4](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKpvHELCSE_ATf70kLu:-MKu4uqR5wijR40Av1oc:b5dnwsw) ([raw file](https://github.com/cockroachdb/docs/blob/3c5bfc4a63c1eaaf1aa5a5364f5cf77966c10f41/v20.2/multilinestring.md#L29)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> `ST_Collect` or `ST_Union`
> ```

Once those docs merge, would be nice to add the link once that's all merged. (I think you mention that here or in that PR).
</blockquote></details>

Did it!  Here and in the multipoint doc
___
*[v20.2/multipoint.md, line 7 at r4](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKpxOvN2xiMo5qCYfX8:-MKu50om82lyeKOp1qUN:b-896fja) ([raw file](https://github.com/cockroachdb/docs/blob/3c5bfc4a63c1eaaf1aa5a5364f5cf77966c10f41/v20.2/multipoint.md#L7)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> geometry: for
> ```

nit: 

geometry. For example,
</blockquote></details>

Done!
___
*[v20.2/multipolygon.md, line 7 at r4](https://reviewable.io/reviews/cockroachdb/docs/8747#-MKpy8XIAgehLpSktnQw:-MKu563s3ZhGx_llzXcd:b-60vi4y) ([raw file](https://github.com/cockroachdb/docs/blob/3c5bfc4a63c1eaaf1aa5a5364f5cf77966c10f41/v20.2/multipolygon.md#L7)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> geometry: for
> ```

geometry. For
</blockquote></details>

Done!  My love for incorrect colon usage is too strong!


<!-- Sent from Reviewable.io -->

2020-10-30 15:32 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8d6d55502434e7b3c5ee8edd8c83b440ee2648f4/

Edited pages:
- [v20.2/geometrycollection.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8d6d55502434e7b3c5ee8edd8c83b440ee2648f4/v20.2/geometrycollection.html)
- [v20.2/linestring.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8d6d55502434e7b3c5ee8edd8c83b440ee2648f4/v20.2/linestring.html)
- [v20.2/multilinestring.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8d6d55502434e7b3c5ee8edd8c83b440ee2648f4/v20.2/multilinestring.html)
- [v20.2/multipoint.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8d6d55502434e7b3c5ee8edd8c83b440ee2648f4/v20.2/multipoint.html)
- [v20.2/multipolygon.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8d6d55502434e7b3c5ee8edd8c83b440ee2648f4/v20.2/multipolygon.html)
- [v20.2/point.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8d6d55502434e7b3c5ee8edd8c83b440ee2648f4/v20.2/point.html)
- [v20.2/polygon.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8d6d55502434e7b3c5ee8edd8c83b440ee2648f4/v20.2/polygon.html)
- [v20.2/spatial-features.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8d6d55502434e7b3c5ee8edd8c83b440ee2648f4/v20.2/spatial-features.html)
- [v20.2/spatial-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8d6d55502434e7b3c5ee8edd8c83b440ee2648f4/v20.2/spatial-indexes.html)

2020-10-30 15:34 UTC, merged