Fix url bugs in docs
cockroachdb/docs pull request #8824
Opened 2020-11-04 14:22 UTC by saintmalik

## Summary

Easy navigation and easy reading for others

2020-11-04 14:22 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/8824)
<!-- Reviewable:end -->

2020-11-04 14:27 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4747a86e9929763891bb4308a4be9bf7899e1457/

Edited pages:
- [v20.1/build-a-spring-app-with-cockroachdb-jpa.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4747a86e9929763891bb4308a4be9bf7899e1457/v20.1/build-a-spring-app-with-cockroachdb-jpa.html)

2020-11-04 14:39 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e6587cb7392443e9c6ad7df32a64ab62bddeaa1b/

Edited pages:
- [v20.1/build-a-spring-app-with-cockroachdb-jdbc.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e6587cb7392443e9c6ad7df32a64ab62bddeaa1b/v20.1/build-a-spring-app-with-cockroachdb-jdbc.html)
- [v20.1/build-a-spring-app-with-cockroachdb-jpa.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e6587cb7392443e9c6ad7df32a64ab62bddeaa1b/v20.1/build-a-spring-app-with-cockroachdb-jpa.html)

2020-11-06 17:30 UTC, saintmalik commented
@RaduBerinde can you look into this sir

2020-11-06 18:58 UTC, ericharmeling requested changes
@saintmalik Thanks for fixing these links!

The URLs for JDBC look spot-on, but the JPA ones are slightly off. See my inline comments.

An additional request: could you propagate these changes to:

- v20.2/build-a-spring-app-with-cockroachdb-jdbc.md
- v20.2/build-a-spring-app-with-cockroachdb-jpa.md

Thanks

2020-11-06 18:58 UTC, ericharmeling commented on v20.1/build-a-spring-app-with-cockroachdb-jpa.md
> +Here are the contents of [`Account.java`](https://github.com/cockroachlabs/roach-data/blob/master/roach-data-jpa/src/main/java/io/roach/data/jpa/Account.java):
The url is now actually 

https://github.com/cockroachlabs/roach-data/tree/master/roach-data-jpa/src/main/java/io/roach/data/json/Account.java

2020-11-06 18:58 UTC, ericharmeling commented on v20.1/build-a-spring-app-with-cockroachdb-jpa.md
> +The contents of [`AccountModel.java`](https://github.com/cockroachlabs/roach-data/blob/master/roach-data-jpa/src/main/java/io/roach/data/jpa/AccountModel.java):
The url is now actually

https://github.com/cockroachlabs/roach-data/tree/master/roach-data-jpa/src/main/java/io/roach/data/json/AccountModel.java

2020-11-06 18:58 UTC, ericharmeling commented on v20.1/build-a-spring-app-with-cockroachdb-jpa.md
> +[`AccountRepository.java`](https://github.com/cockroachlabs/roach-data/blob/master/roach-data-jpa/src/main/java/io/roach/data/jpa/AccountRepository.java) defines the main repository for the `accounts
The url is now actually

https://github.com/cockroachlabs/roach-data/tree/master/roach-data-jpa/src/main/java/io/roach/data/json/AccountRepository.java

2020-11-06 18:58 UTC, ericharmeling commented on v20.1/build-a-spring-app-with-cockroachdb-jpa.md
> +There are several endpoints exposed by the application's web layer, some of which monitor the health of the application, and some that map to queries executed against the connected database. All of t
The url is now actually

https://github.com/cockroachlabs/roach-data/tree/master/roach-data-jpa/src/main/java/io/roach/data/json/AccountController.java

2020-11-06 18:58 UTC, ericharmeling commented on v20.1/build-a-spring-app-with-cockroachdb-jpa.md
> +In this application, transaction retry logic is written into the methods of the `RetryableTransactionAspect` class, declared an aspect with the `@Aspect` annotation. Here are the contents of [`Retrya
The url is now actually

https://github.com/cockroachlabs/roach-data/blob/master/roach-data-jpa/src/main/java/io/roach/data/json/RetryableTransactionAspect.java

2020-11-06 21:44 UTC, saintmalik commented
Made the fix both in v20.1 and v20.2

2020-11-06 21:47 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/775e346fb8258c337a3bef4054a89c44c98c762a/

Edited pages:
- [v20.1/build-a-spring-app-with-cockroachdb-jdbc.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/775e346fb8258c337a3bef4054a89c44c98c762a/v20.1/build-a-spring-app-with-cockroachdb-jdbc.html)
- [v20.1/build-a-spring-app-with-cockroachdb-jpa.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/775e346fb8258c337a3bef4054a89c44c98c762a/v20.1/build-a-spring-app-with-cockroachdb-jpa.html)

2020-11-06 22:14 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/81d1b7eff8611aa4251bde83faafb2b60497a4a2/

Edited pages:
- [v20.1/build-a-spring-app-with-cockroachdb-jdbc.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/81d1b7eff8611aa4251bde83faafb2b60497a4a2/v20.1/build-a-spring-app-with-cockroachdb-jdbc.html)
- [v20.1/build-a-spring-app-with-cockroachdb-jpa.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/81d1b7eff8611aa4251bde83faafb2b60497a4a2/v20.1/build-a-spring-app-with-cockroachdb-jpa.html)
- [v20.2/build-a-spring-app-with-cockroachdb-jdbc.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/81d1b7eff8611aa4251bde83faafb2b60497a4a2/v20.2/build-a-spring-app-with-cockroachdb-jdbc.html)
- [v20.2/build-a-spring-app-with-cockroachdb-jpa.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/81d1b7eff8611aa4251bde83faafb2b60497a4a2/v20.2/build-a-spring-app-with-cockroachdb-jpa.html)

2020-11-10 15:39 UTC, ericharmeling approved these changes
@saintmalik Thanks for updating this! Looks good to me now. :)

2020-11-10 17:08 UTC, merged

2020-12-08 03:43 UTC, SWDevAngel commented
@saintmalik Thank you for contributing to CockroachDB this year. As a token of our appreciation we would like to send you a gift. Please DM me on our [community Slack](https://cockroa.ch/slack) `@lisa` so I can send you a link. (If you don’t want a gift, we also have a charitable contribution choice.) All orders need to be in by December 13, so please send this asap. :)