Golang Hello World updates (PGX)
cockroachdb/docs pull request #8991
Opened 2020-11-23 22:57 UTC by ericharmeling

Related to https://github.com/cockroachlabs/hello-world-go-pgx/pull/1.
Related to https://github.com/cockroachdb/docs/issues/8899.

2020-11-23 22:57 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/8991)
<!-- Reviewable:end -->

2020-11-23 23:02 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4d643da7bd16dd1cf504cf62c63109e0a9fa9975/

Edited pages:
- [v20.2/build-a-go-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4d643da7bd16dd1cf504cf62c63109e0a9fa9975/v20.2/build-a-go-app-with-cockroachdb.html)

2020-11-25 17:45 UTC, ianjevans requested changes
Everything works, I'd just eliminate the first 2 step sections.

2020-11-25 17:45 UTC, ianjevans commented on v20.2/build-a-go-app-with-cockroachdb.md
> +## Step 3. Start CockroachDB
I believe running `go mod init` below eliminates the need for Steps 1 & 2. All the library deps are resolved at that point.

2020-11-30 16:14 UTC, ericharmeling reviewed
@ianjevans TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8991#-:-MNOvfdm403kmGIoYnjx:bbrucpj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ianjevans)

___
*[v20.2/build-a-go-app-with-cockroachdb.md, line 35 at r1](https://reviewable.io/reviews/cockroachdb/docs/8991#-MMrJzlv8r-c28DRtgZy-r1-35:-MNOve8lE9F-XjszT0QS:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/4d643da7bd16dd1cf504cf62c63109e0a9fa9975/v20.2/build-a-go-app-with-cockroachdb.md#L35)):*
<details><summary><i>Previously, ianjevans (Ian Evans) wrote…</i></summary><blockquote>

I believe running `go mod init` below eliminates the need for Steps 1 & 2. All the library deps are resolved at that point.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-30 16:18 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/74fef3e07841cd5c17c0ae0465c23df236cbe201/

Edited pages:
- [v20.1/transactions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/74fef3e07841cd5c17c0ae0465c23df236cbe201/v20.1/transactions.html)
- [v20.2/build-a-go-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/74fef3e07841cd5c17c0ae0465c23df236cbe201/v20.2/build-a-go-app-with-cockroachdb.html)
- [v20.2/transactions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/74fef3e07841cd5c17c0ae0465c23df236cbe201/v20.2/transactions.html)

2020-11-30 16:20 UTC, ianjevans approved these changes

2020-11-30 16:20 UTC, merged