Improve clarity on database restore naming
cockroachdb/docs pull request #9054
Opened 2020-12-04 21:00 UTC by shermanCRL

Driven by a question from @Mattcrdb. into_db only applies to tables restores, not database restores, but this was hard to infer from the existing text.

2020-12-04 21:01 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/9054)
<!-- Reviewable:end -->

2020-12-04 21:04 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8d6a475485a9d6eb05bc0a221a63f35c45ef4024/

Edited pages:
- [v20.2/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8d6a475485a9d6eb05bc0a221a63f35c45ef4024/v20.2/restore.html)

2020-12-07 14:46 UTC, mattcrdb commented
Thanks for putting this together!
19.1 and 19.2 docs have this explanation which I think is sufficient:
![image](https://user-images.githubusercontent.com/51930844/101364857-0b7af700-3871-11eb-977f-a21e716b939c.png)

20.1 has the old one, should we include your change in the 20.1 doc as well?

2020-12-07 16:54 UTC, mwang1026 requested changes
LGTM overall. Nits on language but content is correct. I say good to send to docs for review.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9054#-:-MNy6ysIAf6eaioIX3-b:b-cf6foq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mwang1026 and @shermanCRL)

___
*[v20.2/restore.md, line 92 at r1](https://reviewable.io/reviews/cockroachdb/docs/9054#-MNy4lldDsheeWDIaKDl:-MNy4lldDsheeWDIaKDm:b80v5x3) ([raw file](https://github.com/cockroachdb/docs/blob/8d6a475485a9d6eb05bc0a221a63f35c45ef4024/v20.2/restore.md#L92)):*
> ```
> , and you cannot specify the target database's name while doing a database restore
> ```

I feel like this is unnecessary
___
*[v20.2/restore.md, line 94 at r1](https://reviewable.io/reviews/cockroachdb/docs/9054#-MNy4xRDCdV9FwlmJOsM:-MNy4xRDCdV9FwlmJOsN:bftnpp2) ([raw file](https://github.com/cockroachdb/docs/blob/8d6a475485a9d6eb05bc0a221a63f35c45ef4024/v20.2/restore.md#L94)):*
> ```
> If you would like to restore a database into a database with a different name, or into an existing database, you might try doing a _table_ restore instead:
> ```

Alternate wording suggestion:

"If dropping or renaming the database in the existing cluster is not an option, you can use _table_ restore to restore all of the table data from the database backup into another database"

I have trouble with the phrase "would like to restore a database into a database with a different name" because it's not restoring the database, per se
___
*[v20.2/restore.md, line 114 at r1](https://reviewable.io/reviews/cockroachdb/docs/9054#-MNy6LFc0iem2x_IsPhh:-MNy6LFc0iem2x_IsPhi:b-hb9lqz) ([raw file](https://github.com/cockroachdb/docs/blob/8d6a475485a9d6eb05bc0a221a63f35c45ef4024/v20.2/restore.md#L114)):*
> ```
> By default, tables and views are restored into a database with the name of the database from which they were backed up. However, also consider:
> - If it no longer exists, you must [create the target database](create-database.html).
> - You can choose to [change the target database](#into_db).
> ```

alternative ("also consider" seems too passive of language. they just want to be told what to do).

"By default, tables and views are restored into a database with the name of the database from which they were backed up. In order for the RESTORE to succeed, the database must exist AND the target database must not have tables or views with the same name as the tables or views you're restoring.

If the database you wish to restore to does not exist, you must [create the target database](create-database.html).

If any of the restore target's names are being used in the database that you want to restore to, you can:
___
*[v20.2/restore.md, line 117 at r1](https://reviewable.io/reviews/cockroachdb/docs/9054#-MNy5vfgCBJ4vp9YD4in:-MNy5vfgCBJ4vp9YD4io:b-n61exd) ([raw file](https://github.com/cockroachdb/docs/blob/8d6a475485a9d6eb05bc0a221a63f35c45ef4024/v20.2/restore.md#L117)):*
> ```
> have not have
> ```

 should just be "not have"


<!-- Sent from Reviewable.io -->

2020-12-07 20:50 UTC, shermanCRL commented
@mattcrdb Yep, I will ‘backport’ to the 20.1 docs once the 20.2 verbiage is agreed. I’ll update with Michael’s feedback and ping you both.

2020-12-08 18:46 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5e92b2ed5fc82c678da260b43b0a145c6316a048/

Edited pages:
- [v20.2/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5e92b2ed5fc82c678da260b43b0a145c6316a048/v20.2/restore.html)

2020-12-09 22:48 UTC, mwang1026 submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9054)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh, @mwang1026, and @shermanCRL)

___
*[v20.2/restore.md, line 119 at r2](https://reviewable.io/reviews/cockroachdb/docs/9054#-MO8fqnA7u0II7gn3l1X:-MO8fqnB5z3uuNo7TMxx:b-l42pah) ([raw file](https://github.com/cockroachdb/docs/blob/5e92b2ed5fc82c678da260b43b0a145c6316a048/v20.2/restore.md#L119)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> By default, tables and views are restored into a database with the name of the database from which they were backed up. In order for the RESTORE to succeed, the database must exist AND the target database must not have tables or views with the same name as the tables or views you're restoring.
> If the database you wish to restore to does not exist, you must create the target [create the target database](create-database.html). You can choose to [change the target database](#into_db).
> If any of the restore target's names are being used, you can:
> - [`DROP TABLE`](drop-table.html), [`DROP VIEW`](drop-view.html), or [`DROP SEQUENCE`](drop-sequence.html) and then restore them. Note that a sequence cannot be dropped while it is being used in a column's `DEFAULT` expression, so those expressions must be dropped before the sequence is dropped, and recreated after the sequence is recreated. The `setval` [function](functions-and-operators.html#sequence-functions) can be used to set the value of the sequence to what it was previously.
> - [Restore the table or view into a different database](#into_db).
> ```
</details>


This flows weirdly (also my use of all caps (`AND`) shouldn't be in an official doc :) )

Maybe can be more decision tree? First decide y, if y and z then a, etc.


<!-- Sent from Reviewable.io -->

2020-12-10 17:59 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/602510a3eedf3a6a848e679dfbb83c6bdf8e8f6d/

Edited pages:
- [v20.2/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/602510a3eedf3a6a848e679dfbb83c6bdf8e8f6d/v20.2/restore.html)

2020-12-10 18:02 UTC, shermanCRL commented
@mwang1026 OK, maybe it’s reasonably readable now. I don’t have good ideas for a decision tree, though I like the spirit of that idea -- a feeling of step-by-step instruction instead of “hey, you could X”.

2020-12-10 19:06 UTC, lnhsingh reviewed
Related to https://github.com/cockroachdb/docs/issues/8541 (#1).

A couple of small edits but otherwise <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> ! Thanks for the edits. Like Matt said, this should also be edited in v20.1, and sorry for the bad timing / extra work, but also v21.1 now too. You might have to rebase with master to pull down the new v21.1 directory.

Thank you!!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9054#-:-MOD-ZB99742-4Ltqr5S:bqvrj8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lnhsingh and @shermanCRL)

___
*[v20.2/restore.md, line 52 at r3](https://reviewable.io/reviews/cockroachdb/docs/9054#-MOD-lIyDUKxZjrBjkl3:-MOD-lIyDUKxZjrBjkl4:b-d7xwak) ([raw file](https://github.com/cockroachdb/docs/blob/602510a3eedf3a6a848e679dfbb83c6bdf8e8f6d/v20.2/restore.md#L52)):*
> ```Markdown
>  Option                                                             | <div style="width:75px">Value</div>         | Description
>  -------------------------------------------------------------------+---------------+-------------------------------------------------------
> <a name="into_db"></a>`into_db`                                     | Database name                               | Use to [change the target database](restore.html#restore-tables-into-a-different-database) for table restores. (Does not apply to database or cluster restores.)<br><br>Example: `WITH into_db = 'newdb'`
> ```

I think the example should be updated too to make it clear that it's for tables. (e.g., `WITH into_db = 'new_table'`
___
*[v20.2/restore.md, line 94 at r3](https://reviewable.io/reviews/cockroachdb/docs/9054#-MOD0AVa0v_k8jXJTQKr:-MOD0AVa0v_k8jXJTQKs:b9ft9e) ([raw file](https://github.com/cockroachdb/docs/blob/602510a3eedf3a6a848e679dfbb83c6bdf8e8f6d/v20.2/restore.md#L94)):*
> ```Markdown
> The created database will have the name of the database in the backup. The database cannot already exist in the target cluster.
> 
> If dropping or renaming the database in the existing cluster is not an option, you can use _table_ restore to restore all of the table data from the database backup into another database:
> ```

Can you add cross links to `drop-database.md` and `rename-database.md`?

```
If [dropping](drop-database.md) or [renaming](rename-database.html) the database in the existing cluster [...]
```
___
*[v20.2/restore.md, line 112 at r3](https://reviewable.io/reviews/cockroachdb/docs/9054#-MOD0l98EyzGSc-vxiKB:-MOD0l98EyzGSc-vxiKC:b-x7ps0g) ([raw file](https://github.com/cockroachdb/docs/blob/602510a3eedf3a6a848e679dfbb83c6bdf8e8f6d/v20.2/restore.md#L112)):*
> ```Markdown
> {{site.data.alerts.end}}
> 
> By default, tables and views are restored into a target database matching the name of the database from which they were backed up. If the target database does not exist, you must [create it](create-database.html). You can choose to change the target database by with the [`into_db` parameter](#into_db). 
> ```

nit: `parameter` > `option`


<!-- Sent from Reviewable.io -->

2020-12-10 21:06 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d8876dbec450e6cdf0df5d2b01df239974a2e85d/

Edited pages:
- [v20.2/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d8876dbec450e6cdf0df5d2b01df239974a2e85d/v20.2/restore.html)

2020-12-10 21:06 UTC, shermanCRL commented
@lnhsingh Thanks, I’ve made those changes. The first one however, I think it’s correct as-is: `into_db` is used with _table_ restores, but takes a _database_ as its argument.

Thanks for the reminder that this was previously discussed, I had forgotten!

2020-12-10 21:39 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7571309c08437809fd05ed8c14fa748aec4da57d/

Edited pages:
- [v20.2/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7571309c08437809fd05ed8c14fa748aec4da57d/v20.2/restore.html)

2020-12-10 22:03 UTC, lnhsingh reviewed
Makes sense to me! Also, I noticed the TC build is failing on these broken links:

```
[page broken link is on] --> [link that needs to be fixed]
/v20.2/take-full-and-incremental-backups.html --> restore.html#restore-into-a-different-database
/v20.2/backup.html --> restore.html#restore-into-a-different-database
/v20.2/restore.html --> alter-type
```

First and second should now be `restore.html#restore-tables-into-a-different-database`
Third one needs a `.html` at the end 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9054#-:-MODewrZCY4POjbcIl9N:brzvs10)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @shermanCRL)



<!-- Sent from Reviewable.io -->

2020-12-10 22:23 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f44d5bf02904541e633b7d1af7cc1c282d72db0e/

Edited pages:
- [v20.2/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f44d5bf02904541e633b7d1af7cc1c282d72db0e/v20.2/restore.html)
- [v20.2/take-full-and-incremental-backups.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f44d5bf02904541e633b7d1af7cc1c282d72db0e/v20.2/take-full-and-incremental-backups.html)

2020-12-10 22:29 UTC, shermanCRL commented
Once final, let’s publish, then I’ll update 20.1 and 21.1.

2020-12-10 22:55 UTC, lnhsingh reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> LMK if you need me to merge

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9054#-:-MODrPaX-oDP7GKvJ-Ni:b-74nvlc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @shermanCRL)



<!-- Sent from Reviewable.io -->

2020-12-10 23:42 UTC, merged