first draft of privatelink docs
cockroachdb/docs pull request #9315
Opened 2021-01-07 23:22 UTC by gemma-shay

Closes #9314.
Waiting for UI to be finalized for some steps.

2021-01-07 23:22 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/9315)
<!-- Reviewable:end -->

2021-01-07 23:29 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/

Edited pages:
- [cockroachcloud/connect-to-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/cockroachcloud/connect-to-your-cluster.html)
- [cockroachcloud/create-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/cockroachcloud/create-your-cluster.html)
- [cockroachcloud/network-authorization.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/cockroachcloud/network-authorization.html)

2021-01-08 23:29 UTC, lnhsingh reviewed
Nice job! This is a good first pass. A few things:

- I noted a few things re: style, active voice, and formatting -- all things that I'm sure you'll pick up once you're better acquainted with the docs!
- Comments marked with "nit" just mean "small nit pick".
- Many of the suggestions are just that -- suggestions. You can take them or try to come up with a better fix.
- One general edit is that we do numbered lists in markdown all starting with `1.` For example: `1. xxxx 1. yyy 1. zzz` Markdown will render the steps in the correct order. We do this so if we have to use an include with steps, Markdown is smart enough to automatically ordered them correctly (vs. step numbers being hardcoded and possibly out of order). It's also easier if you have to add a step later to just add a new step with `1.` instead of having to re-number everything following it.

Let me know if you have any questions about the comments I left-- you can just reply to them in Reviewable. Once you have a finalized UI and a draft that's ready for engineering / PM review, feel free to ask for those reviews. I'll do a final review after that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9315#-:-MQZIRBA8_UJAZiOcAph:b-fj6gzm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @lnhsingh)

___
*[cockroachcloud/connect-to-your-cluster.md, line 65 at r1](https://reviewable.io/reviews/cockroachdb/docs/9315#-MQZ8M6c-z1Yz6yusQmM:-MQZ8M6d2NFhKXiVH32f:b-mf8yje) ([raw file](https://github.com/cockroachdb/docs/blob/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/cockroachcloud/connect-to-your-cluster.md#L65)):*
> ```Markdown
> <section class="filter-content" markdown="1" data-scope="gcp">
> 
> #### VPC peering
> ```

I don't think you need these H4 headings since you have a tab named the same thing right above. Since you link to this section in a step below, you should add in anchor tags to replace the headings.
___
*[cockroachcloud/connect-to-your-cluster.md, line 80 at r1](https://reviewable.io/reviews/cockroachdb/docs/9315#-MQZ9bgL2W3i7Lq0bLNc:-MQZ9bgL2W3i7Lq0bLNd:b-h6a9gd) ([raw file](https://github.com/cockroachdb/docs/blob/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/cockroachcloud/connect-to-your-cluster.md#L80)):*
> ```Markdown
> #### AWS PrivateLink
> 
> 1. Navigate to your cluster's **Networking** page and click **PrivateLink**.
> ```

I realize that you're emulating the existing steps, however, each step should have one action, so this should either be:

```
1. Navigate to your cluster's Networking page.
2. Click Peering.
```

Or:

```
1. On the Networking page, click Peering.
```

Either works, as long as you apply the same change to the VPC Peering steps too.
___
*[cockroachcloud/connect-to-your-cluster.md, line 124 at r1](https://reviewable.io/reviews/cockroachdb/docs/9315#-MQZBU8M94Gc6dd8aZK0:-MQZBU8M94Gc6dd8aZK1:b-ovqrni) ([raw file](https://github.com/cockroachdb/docs/blob/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/cockroachcloud/connect-to-your-cluster.md#L124)):*
> ```Markdown
>     For GCP clusters, you can select **VPC Peering** if you have already:
>   - [Enabled VPC peering while creating your cluster](create-your-cluster.html#step-7-enable-vpc-peering-optional)
>   - [Established a VPC Peering connection](#vpc-peering)
> ```

This link only works if you had selected VPC Peering in the above step. Since you have two sets of instructions here (one for AWS and one for GCP), can you add in the filtering logic here as well so you just select one of the tabs once and then the rest of the instructions is filtered for you?
___
*[cockroachcloud/network-authorization.md, line 50 at r1](https://reviewable.io/reviews/cockroachdb/docs/9315#-MQZCHyf3OZf594lINpL:-MQZCHyf3OZf594lINpM:b-qxqgtu) ([raw file](https://github.com/cockroachdb/docs/blob/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/cockroachcloud/network-authorization.md#L50)):*
> ```Markdown
> ## AWS PrivateLink
> 
> If your Cloud provider is AWS, you can use [AWS PrivateLink](https://aws.amazon.com/privatelink/) to securely connect your AWS application with your CockroachCloud cluster using a private endpoint. Like VPC Peering, a PrivateLink connection will prevent your traffic from being exposed to the public internet and reduce network latency.
> ```

nit: I think `Cloud provider` should be `cloud provider` (needs to be edited in the VPC Peering section too)
___
*[cockroachcloud/network-authorization.md, line 58 at r1](https://reviewable.io/reviews/cockroachdb/docs/9315#-MQZCcBl37mUTHljPca1:-MQZCcBl37mUTHljPca2:b-dsmyup) ([raw file](https://github.com/cockroachdb/docs/blob/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/cockroachcloud/network-authorization.md#L58)):*
> ```Markdown
> 3.  [Enable private DNS](#enable-private-dns)
> 
> To get started, use the CockroachCloud Console to [create your CockroachCloud cluster](https://www.cockroachlabs.com/docs/cockroachcloud/stable/cockroachcloud-create-your-cluster.html) on AWS in the same region as your application. After creating your cluster, navigate to the **Networking** page and select the **PrivateLink** tab. Click **Set up a PrivateLink connection** to open the connection modal.
> ```

Should this be in its own section and added above as a step? Like, step 1 is to create your Create your CC cluster and then this paragraph of info can be broken into a numbered list of steps?
___
*[cockroachcloud/network-authorization.md, line 63 at r1](https://reviewable.io/reviews/cockroachdb/docs/9315#-MQZDUdR96Oy-07iazxN:-MQZDUdR96Oy-07iazxO:b-otpnnl) ([raw file](https://github.com/cockroachdb/docs/blob/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/cockroachcloud/network-authorization.md#L63)):*
> ```Markdown
> 
> 1. On the [Amazon VPC Console](https://console.aws.amazon.com/vpc/), click **Your VPCs** in the sidebar. 
> 2. Locate the VPC ID of the VPC you want to create your endpoint in. This will probably be the same VPC as the VPC your EC2 instances and application are running in. 
> ```

Suggested formatting: the extra info (`This will probably be...`) should be on a new line, under the main step. For example:

```
2. Locate the VPC ID of the VPC you want to create your endpoint in. 

    This will probably be the same VPC as the VPC your EC2 instances and application are running in. You can also choose a different VPC, as long as it is peered to the VPC your application is running in.
```
___
*[cockroachcloud/network-authorization.md, line 65 at r1](https://reviewable.io/reviews/cockroachdb/docs/9315#-MQZDsR56GJK_OvexAda:-MQZDsR56GJK_OvexAdb:b-89nllv) ([raw file](https://github.com/cockroachdb/docs/blob/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/cockroachcloud/network-authorization.md#L65)):*
> ```Markdown
> 2. Locate the VPC ID of the VPC you want to create your endpoint in. This will probably be the same VPC as the VPC your EC2 instances and application are running in. 
> You can also choose a different VPC, as long as it is peered to the VPC your application is running in.
> On the Your VPCs page, locate the IPv4 CIDR corresponding to the VPC you chose in Step 1.
> ```

Should this be a numbered step?
___
*[cockroachcloud/network-authorization.md, line 66 at r1](https://reviewable.io/reviews/cockroachdb/docs/9315#-MQZE09e0DaSW0jpaG5z:-MQZE09e0DaSW0jpaG6-:bnhgomh) ([raw file](https://github.com/cockroachdb/docs/blob/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/cockroachcloud/network-authorization.md#L66)):*
> ```Markdown
> You can also choose a different VPC, as long as it is peered to the VPC your application is running in.
> On the Your VPCs page, locate the IPv4 CIDR corresponding to the VPC you chose in Step 1.
> 3. Click **Subnets** in the sidebar. Locate the subnet IDs corresponding to the VPC you chose in Step 1.
> ```

Similar to the suggestion of keeping each step limited to one action, I would suggest changing the wording here to either something like:

```
3. Navigate to the Subnets page.
4. Locate the subnet IDs...
```

or:

```
3. On the Subnets page, locate  [...]

2021-01-11 22:24 UTC, gemma-shay commented
___
*[cockroachcloud/connect-to-your-cluster.md, line 124 at r1](https://reviewable.io/reviews/cockroachdb/docs/9315#-MQZBU8M94Gc6dd8aZK0:-MQmVqWP7USImlEgcbdI:b-4q9ny0) ([raw file](https://github.com/cockroachdb/docs/blob/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/cockroachcloud/connect-to-your-cluster.md#L124)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

This link only works if you had selected VPC Peering in the above step. Since you have two sets of instructions here (one for AWS and one for GCP), can you add in the filtering logic here as well so you just select one of the tabs once and then the rest of the instructions is filtered for you?
</blockquote></details>

I'm struggling with getting the links to the filtered sections to work correctly. Everything I've tried seems to break the formatting somehow. I think the best solution might be to just link to the ### Establish VPC Peering or AWS PrivateLink heading unless you know of a better way.


<!-- Sent from Reviewable.io -->

2021-01-11 22:28 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/70078d22c793c27bafd7d218e28f31b66d88225e/

Edited pages:
- [cockroachcloud/connect-to-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/70078d22c793c27bafd7d218e28f31b66d88225e/cockroachcloud/connect-to-your-cluster.html)
- [cockroachcloud/create-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/70078d22c793c27bafd7d218e28f31b66d88225e/cockroachcloud/create-your-cluster.html)
- [cockroachcloud/network-authorization.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/70078d22c793c27bafd7d218e28f31b66d88225e/cockroachcloud/network-authorization.html)

2021-01-12 02:31 UTC, lnhsingh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9315)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

___
*[cockroachcloud/connect-to-your-cluster.md, line 124 at r1](https://reviewable.io/reviews/cockroachdb/docs/9315#-MQZBU8M94Gc6dd8aZK0:-MQoQWo63hoEWpZWS5a4:b-1bk162) ([raw file](https://github.com/cockroachdb/docs/blob/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/cockroachcloud/connect-to-your-cluster.md#L124)):*
<details><summary><i>Previously, gemma-shay (Gemma Shay) wrote…</i></summary><blockquote>

I'm struggling with getting the links to the filtered sections to work correctly. Everything I've tried seems to break the formatting somehow. I think the best solution might be to just link to the ### Establish VPC Peering or AWS PrivateLink heading unless you know of a better way.
</blockquote></details>

I don't know of a better way off the top of my head. I think linking to the headings is ok - once you add that I can take another look and see if there's a better/different way


<!-- Sent from Reviewable.io -->

2021-01-13 15:59 UTC, gemma-shay reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9315)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

___
*[cockroachcloud/connect-to-your-cluster.md, line 65 at r1](https://reviewable.io/reviews/cockroachdb/docs/9315#-MQZ8M6c-z1Yz6yusQmM:-MQwLZnV7O05t6ZanF3_:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/cockroachcloud/connect-to-your-cluster.md#L65)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

I don't think you need these H4 headings since you have a tab named the same thing right above. Since you link to this section in a step below, you should add in anchor tags to replace the headings.
</blockquote></details>

Done.
___
*[cockroachcloud/connect-to-your-cluster.md, line 80 at r1](https://reviewable.io/reviews/cockroachdb/docs/9315#-MQZ9bgL2W3i7Lq0bLNc:-MQwLawlDX3PVtIL1kTo:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/cockroachcloud/connect-to-your-cluster.md#L80)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

I realize that you're emulating the existing steps, however, each step should have one action, so this should either be:

```
1. Navigate to your cluster's Networking page.
2. Click Peering.
```

Or:

```
1. On the Networking page, click Peering.
```

Either works, as long as you apply the same change to the VPC Peering steps too.
</blockquote></details>

Done.
___
*[cockroachcloud/connect-to-your-cluster.md, line 124 at r1](https://reviewable.io/reviews/cockroachdb/docs/9315#-MQZBU8M94Gc6dd8aZK0:-MQwLeP794czlRy7oNVe:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/cockroachcloud/connect-to-your-cluster.md#L124)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

I don't know of a better way off the top of my head. I think linking to the headings is ok - once you add that I can take another look and see if there's a better/different way
</blockquote></details>

Done.
___
*[cockroachcloud/network-authorization.md, line 58 at r1](https://reviewable.io/reviews/cockroachdb/docs/9315#-MQZCcBl37mUTHljPca1:-MQwLiMCAyN9ZUe2oaT1:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/cockroachcloud/network-authorization.md#L58)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Should this be in its own section and added above as a step? Like, step 1 is to create your Create your CC cluster and then this paragraph of info can be broken into a numbered list of steps?
</blockquote></details>

Done.
___
*[cockroachcloud/network-authorization.md, line 63 at r1](https://reviewable.io/reviews/cockroachdb/docs/9315#-MQZDUdR96Oy-07iazxN:-MQwLjhQAzusgRlhTUJS:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/cockroachcloud/network-authorization.md#L63)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Suggested formatting: the extra info (`This will probably be...`) should be on a new line, under the main step. For example:

```
2. Locate the VPC ID of the VPC you want to create your endpoint in. 

    This will probably be the same VPC as the VPC your EC2 instances and application are running in. You can also choose a different VPC, as long as it is peered to the VPC your application is running in.
```
</blockquote></details>

Done.
___
*[cockroachcloud/network-authorization.md, line 65 at r1](https://reviewable.io/reviews/cockroachdb/docs/9315#-MQZDsR56GJK_OvexAda:-MQwLkNy90OlrZXThk2T:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/cockroachcloud/network-authorization.md#L65)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Should this be a numbered step?
</blockquote></details>

Done.
___
*[cockroachcloud/network-authorization.md, line 66 at r1](https://reviewable.io/reviews/cockroachdb/docs/9315#-MQZE09e0DaSW0jpaG5z:-MQwLlQ61akWRCWf37Va:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/cockroachcloud/network-authorization.md#L66)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Similar to the suggestion of keeping each step limited to one action, I would suggest changing the wording here to either something like:

```
3. Navigate to the Subnets page.
4. Locate the subnet IDs...
```

or:

```
3. On the Subnets page, locate the subnet IDs...
```
</blockquote></details>

Done.
___
*[cockroachcloud/network-authorization.md, line 67 at r1](https://reviewable.io/reviews/cockroachdb/docs/9315#-MQZEnmq9PwmhNrY802s:-MQwS_7h6KVMK6Lsz2x0:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/cockroachcloud/network-authorization.md#L67)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Same comment as above re: splitting actions across multiple steps
</blockquote></details>

Done.
___
*[cockroachcloud/network-authorization.md, line 74 at r1](https://reviewable.io/reviews/cockroachdb/docs/9315#-MQZF10o2E8EnWSdDHz2:-MQwScYQBm2t_S-UW6wT:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/cockroachcloud/network-authorization.md#L74)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

This code block should be indented in-line with the sub-bullet that it's a child of
</blockquote></details>

Done.
___
*[cockroachcloud/network-authorization.md, line 91 at r1](https://reviewable.io/reviews/cockroachdb/docs/9315#-MQZFQCG9C9cUw9MkOdf:-MQwSkzB6DUGsdar_4Kz:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/cockroachcloud/network-authorization.md#L91)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

> ```
> The VPC Endpoint ID is displayed. 
> ```

Rule of thumb to not start a task step with "x displays". You should aim to have steps start with an action. In this case, you can move `The VPC Endpoint ID is displayed` to be subtext under the step above this one. Also edit to be active: `The VPC Endpoint ID displays.`
</blockquote></details>

Done.
___
*[cockroachcloud/network-authorization.md, line 95 at r1](https://reviewable.io/reviews/cockroachdb/docs/9315#-MQZHmXh54nR8L7e7Uhp:-MQwSuE19Hx6nnMdeYyA:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/cockroachcloud/network-authorization.md#L95)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Suggestion on wording: `...if the status is listed as Available on the **Endpoints** page`
</blockquote></details>

Done.
___
*[cockroachcloud/network-authorization.md, line 99 at r1](https://reviewable.io/reviews/cockroachdb/docs/9315#-MQZHNqQAlya0HShmbAc:-MQwSzdTDzvj7KGN0Thr:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/cockroachcloud/network-authorization.md#L99)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Should `available` be `Available` since that's what (I assume) will display on the page?
</blockquote></details>

Done.
___
*[cockroachcloud/network-authorization.md, line 105 at r1](https://reviewable.io/reviews/cockroachdb/docs/9315#-MQZHBYhEBQ1q5b5T3h-:-MQwT76E1i7tVJFUZE3F:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/858e6f6a7c0708073fe02867b2cf7bb11eb4a3cb/cockroachcloud/network-authorization.md#L105)):*
<details><summary><i>Pr [...]

2021-01-13 19:37 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1842bbda9fcfa6e948d79338fe8c7b080bef30fe/

Edited pages:
- [cockroachcloud/connect-to-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1842bbda9fcfa6e948d79338fe8c7b080bef30fe/cockroachcloud/connect-to-your-cluster.html)
- [cockroachcloud/create-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1842bbda9fcfa6e948d79338fe8c7b080bef30fe/cockroachcloud/create-your-cluster.html)
- [cockroachcloud/network-authorization.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1842bbda9fcfa6e948d79338fe8c7b080bef30fe/cockroachcloud/network-authorization.html)

2021-01-13 20:17 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1842bbda9fcfa6e948d79338fe8c7b080bef30fe/

Edited pages:
- [cockroachcloud/connect-to-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1842bbda9fcfa6e948d79338fe8c7b080bef30fe/cockroachcloud/connect-to-your-cluster.html)
- [cockroachcloud/create-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1842bbda9fcfa6e948d79338fe8c7b080bef30fe/cockroachcloud/create-your-cluster.html)
- [cockroachcloud/network-authorization.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1842bbda9fcfa6e948d79338fe8c7b080bef30fe/cockroachcloud/network-authorization.html)

2021-01-13 20:49 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1976481dcbe22b543da876f0083202f4acef290/

Edited pages:
- [cockroachcloud/connect-to-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1976481dcbe22b543da876f0083202f4acef290/cockroachcloud/connect-to-your-cluster.html)
- [cockroachcloud/create-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1976481dcbe22b543da876f0083202f4acef290/cockroachcloud/create-your-cluster.html)
- [cockroachcloud/network-authorization.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1976481dcbe22b543da876f0083202f4acef290/cockroachcloud/network-authorization.html)

2021-01-13 20:57 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e0a41ed37e578bb41e12a1cd111083d262d04ce8/

Edited pages:
- [cockroachcloud/connect-to-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e0a41ed37e578bb41e12a1cd111083d262d04ce8/cockroachcloud/connect-to-your-cluster.html)
- [cockroachcloud/create-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e0a41ed37e578bb41e12a1cd111083d262d04ce8/cockroachcloud/create-your-cluster.html)
- [cockroachcloud/network-authorization.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e0a41ed37e578bb41e12a1cd111083d262d04ce8/cockroachcloud/network-authorization.html)

2021-01-19 16:35 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/465a2e05dc440f1ee1f13e2f75eb92f8d37dae7d/

Edited pages:
- [cockroachcloud/connect-to-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/465a2e05dc440f1ee1f13e2f75eb92f8d37dae7d/cockroachcloud/connect-to-your-cluster.html)
- [cockroachcloud/create-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/465a2e05dc440f1ee1f13e2f75eb92f8d37dae7d/cockroachcloud/create-your-cluster.html)
- [cockroachcloud/network-authorization.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/465a2e05dc440f1ee1f13e2f75eb92f8d37dae7d/cockroachcloud/network-authorization.html)

2021-02-02 18:59 UTC, gemma-shay commented
cc: @tommy @rsadres if interested

2021-02-03 20:42 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/480be52c5eefcd99c19a28d1c529c1d4201c4a62/

Edited pages:
- [cockroachcloud/connect-to-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/480be52c5eefcd99c19a28d1c529c1d4201c4a62/cockroachcloud/connect-to-your-cluster.html)
- [cockroachcloud/create-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/480be52c5eefcd99c19a28d1c529c1d4201c4a62/cockroachcloud/create-your-cluster.html)
- [cockroachcloud/network-authorization.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/480be52c5eefcd99c19a28d1c529c1d4201c4a62/cockroachcloud/network-authorization.html)

2021-02-03 21:51 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/97b3e489ca930da75f83585d3428b41307a4e82c/

Edited pages:
- [cockroachcloud/connect-to-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/97b3e489ca930da75f83585d3428b41307a4e82c/cockroachcloud/connect-to-your-cluster.html)
- [cockroachcloud/create-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/97b3e489ca930da75f83585d3428b41307a4e82c/cockroachcloud/create-your-cluster.html)
- [cockroachcloud/network-authorization.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/97b3e489ca930da75f83585d3428b41307a4e82c/cockroachcloud/network-authorization.html)

2021-02-03 23:52 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7bea847f792a77fd0760c9dc27bf81e13c2a126e/

Edited pages:
- [cockroachcloud/connect-to-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7bea847f792a77fd0760c9dc27bf81e13c2a126e/cockroachcloud/connect-to-your-cluster.html)
- [cockroachcloud/create-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7bea847f792a77fd0760c9dc27bf81e13c2a126e/cockroachcloud/create-your-cluster.html)
- [cockroachcloud/network-authorization.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7bea847f792a77fd0760c9dc27bf81e13c2a126e/cockroachcloud/network-authorization.html)

2021-02-04 22:19 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ef4af076e85dca9bf9b6d488584f94079067f963/

Edited pages:
- [cockroachcloud/connect-to-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ef4af076e85dca9bf9b6d488584f94079067f963/cockroachcloud/connect-to-your-cluster.html)
- [cockroachcloud/create-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ef4af076e85dca9bf9b6d488584f94079067f963/cockroachcloud/create-your-cluster.html)
- [cockroachcloud/network-authorization.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ef4af076e85dca9bf9b6d488584f94079067f963/cockroachcloud/network-authorization.html)

2021-02-08 17:55 UTC, gemma-shay commented
cc: @j-low for awareness

2021-02-08 20:13 UTC, lnhsingh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9315)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay, @lnhsingh, and @thtruo)

___
*[cockroachcloud/connect-to-your-cluster.md, line 84 at r4](https://reviewable.io/reviews/cockroachdb/docs/9315#-MT2FAC38f0P7B9bU-Y_:-MT2FAC42bbOmDygEIih:b-z2ibjb) ([raw file](https://github.com/cockroachdb/docs/blob/ef4af076e85dca9bf9b6d488584f94079067f963/cockroachcloud/connect-to-your-cluster.md#L84)):*
> ```Markdown
> 
> 1. Navigate to your cluster's **Networking > PrivateLink** tab.
> 1. Click **Set up a PrivateLink connection**.
> ```

nit: it looks like this button is now named "Add PrivateLink connection"
___
*[cockroachcloud/connect-to-your-cluster.md, line 85 at r4](https://reviewable.io/reviews/cockroachdb/docs/9315#-MT2FKa84Xja8r_B4fl0:-MT2FKa84Xja8r_B4fl1:b-hygq9d) ([raw file](https://github.com/cockroachdb/docs/blob/ef4af076e85dca9bf9b6d488584f94079067f963/cockroachcloud/connect-to-your-cluster.md#L85)):*
> ```Markdown
> 1. Navigate to your cluster's **Networking > PrivateLink** tab.
> 1. Click **Set up a PrivateLink connection**.
> 1. Use the service name provided to [create an AWS endpoint](network-authorization.html#create-an-aws-endpoint) in the AWS console.
> ```

nit: "Use the service name provided in the dialog to create an AWS endpoint..."
___
*[cockroachcloud/connect-to-your-cluster.md, line 92 at r4](https://reviewable.io/reviews/cockroachdb/docs/9315#-MT2G0Uj1n62s9lawBzc:-MT2G0Uj1n62s9lawBzd:bdu31ci) ([raw file](https://github.com/cockroachdb/docs/blob/ef4af076e85dca9bf9b6d488584f94079067f963/cockroachcloud/connect-to-your-cluster.md#L92)):*
> ```Markdown
> 1. Return to the AWS console to [enable private DNS](network-authorization.html#enable-private-dns).
> 1. Click **Complete**.
> 1. On the **Networking** page, verify the connection status is Active.
> ```

nit: I thnk "Active" should be "Available", according to what is showing in the Console
___
*[cockroachcloud/connect-to-your-cluster.md, line 106 at r4](https://reviewable.io/reviews/cockroachdb/docs/9315#-MT2GGlT4Z1vKiT6P-jH:-MT2GGlT4Z1vKiT6P-jI:b-nmkba1) ([raw file](https://github.com/cockroachdb/docs/blob/ef4af076e85dca9bf9b6d488584f94079067f963/cockroachcloud/connect-to-your-cluster.md#L106)):*
> ```Markdown
>     The **Connect** dialog displays.  
> 
> 1. **IP Allowlist** is selected by default as the **Network Security** option. 
> ```

I don't think this should be a numbered step since it is just describing the default state of the dialog. I would move this sentence up to be included with the "The Connect dialog displays" sentence. This numbered step can be something like:

```
1. Select the **Network Security** type:

    For AWS clusters...

    For GCP clusters ...
```


<!-- Sent from Reviewable.io -->

2021-02-08 23:35 UTC, gemma-shay reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9315)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh and @thtruo)

___
*[cockroachcloud/connect-to-your-cluster.md, line 84 at r4](https://reviewable.io/reviews/cockroachdb/docs/9315#-MT2FAC38f0P7B9bU-Y_:-MT2Kk9f2JA1TazWHACx:bkec58z) ([raw file](https://github.com/cockroachdb/docs/blob/ef4af076e85dca9bf9b6d488584f94079067f963/cockroachcloud/connect-to-your-cluster.md#L84)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

nit: it looks like this button is now named "Add PrivateLink connection"
</blockquote></details>

Only when there are other PL connections already set up. Could add a note or extra sentence saying that it changes?
___
*[cockroachcloud/connect-to-your-cluster.md, line 85 at r4](https://reviewable.io/reviews/cockroachdb/docs/9315#-MT2FKa84Xja8r_B4fl0:-MT2Lbsz877rJMUYeGIy:bb7f2mf) ([raw file](https://github.com/cockroachdb/docs/blob/ef4af076e85dca9bf9b6d488584f94079067f963/cockroachcloud/connect-to-your-cluster.md#L85)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

nit: "Use the service name provided in the dialog to create an AWS endpoint..."
</blockquote></details>

done
___
*[cockroachcloud/connect-to-your-cluster.md, line 92 at r4](https://reviewable.io/reviews/cockroachdb/docs/9315#-MT2G0Uj1n62s9lawBzc:-MT2L_8V9xJPPDU1oc4m:bd30ifx) ([raw file](https://github.com/cockroachdb/docs/blob/ef4af076e85dca9bf9b6d488584f94079067f963/cockroachcloud/connect-to-your-cluster.md#L92)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

nit: I thnk "Active" should be "Available", according to what is showing in the Console
</blockquote></details>

good catch
___
*[cockroachcloud/connect-to-your-cluster.md, line 106 at r4](https://reviewable.io/reviews/cockroachdb/docs/9315#-MT2GGlT4Z1vKiT6P-jH:-MT2Mil7C_ZNzyHDSZYa:bb7f2mf) ([raw file](https://github.com/cockroachdb/docs/blob/ef4af076e85dca9bf9b6d488584f94079067f963/cockroachcloud/connect-to-your-cluster.md#L106)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

I don't think this should be a numbered step since it is just describing the default state of the dialog. I would move this sentence up to be included with the "The Connect dialog displays" sentence. This numbered step can be something like:

```
1. Select the **Network Security** type:

    For AWS clusters...

    For GCP clusters ...
```
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-02-08 23:41 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/9bba157a45b6cfaab04b1daa837c37bfbdcd083d/

Edited pages:
- [cockroachcloud/connect-to-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/9bba157a45b6cfaab04b1daa837c37bfbdcd083d/cockroachcloud/connect-to-your-cluster.html)
- [cockroachcloud/create-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/9bba157a45b6cfaab04b1daa837c37bfbdcd083d/cockroachcloud/create-your-cluster.html)
- [cockroachcloud/network-authorization.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/9bba157a45b6cfaab04b1daa837c37bfbdcd083d/cockroachcloud/network-authorization.html)

2021-02-10 20:44 UTC, KapedRebooster approved these changes

2021-02-10 20:45 UTC, KapedRebooster approved these changes
> `
Wap.bootstrap,leans`

2021-02-10 20:46 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/02711d8d3e2b9d283f308e924f4d7a2fbe6f5c4b/

Edited pages:
- [cockroachcloud/connect-to-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/02711d8d3e2b9d283f308e924f4d7a2fbe6f5c4b/cockroachcloud/connect-to-your-cluster.html)
- [cockroachcloud/create-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/02711d8d3e2b9d283f308e924f4d7a2fbe6f5c4b/cockroachcloud/create-your-cluster.html)
- [cockroachcloud/network-authorization.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/02711d8d3e2b9d283f308e924f4d7a2fbe6f5c4b/cockroachcloud/network-authorization.html)
- [cockroachcloud/security-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/02711d8d3e2b9d283f308e924f4d7a2fbe6f5c4b/cockroachcloud/security-overview.html)

2021-02-11 04:47 UTC, thtruo commented
Nice @gemma-shay this is looking good! I just noticed a nit:

- The tab between VPC Peering and AWS PrivateLink seems misaligned ([link](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/02711d8d3e2b9d283f308e924f4d7a2fbe6f5c4b/cockroachcloud/connect-to-your-cluster.html#aws))
![Screen Recording 2021-02-10 at 11 41 PM](https://user-images.githubusercontent.com/1474303/107603075-a25d8a00-6bf9-11eb-8985-e1397c0efb6b.gif)

2021-02-11 04:49 UTC, thtruo requested changes
Content looks good. If we could fix up the tab alignment at this [spot](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/02711d8d3e2b9d283f308e924f4d7a2fbe6f5c4b/cockroachcloud/connect-to-your-cluster.html#establish-vpc-peering-or-aws-privatelink) then it lgtm!

2021-02-11 15:51 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e814b7b16123e4b013dc99a6c2e2624750e22705/

Edited pages:
- [cockroachcloud/connect-to-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e814b7b16123e4b013dc99a6c2e2624750e22705/cockroachcloud/connect-to-your-cluster.html)
- [cockroachcloud/create-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e814b7b16123e4b013dc99a6c2e2624750e22705/cockroachcloud/create-your-cluster.html)
- [cockroachcloud/network-authorization.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e814b7b16123e4b013dc99a6c2e2624750e22705/cockroachcloud/network-authorization.html)
- [cockroachcloud/security-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e814b7b16123e4b013dc99a6c2e2624750e22705/cockroachcloud/security-overview.html)

2021-02-16 20:29 UTC, merged