Update multi-region-setup.md
cockroachdb/docs pull request #9324
Opened 2021-01-11 20:36 UTC by fabiog1901

wrong indentation on list

2021-01-11 20:36 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/9324)
<!-- Reviewable:end -->

2021-01-11 20:41 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f7c610fb65636a98ac641ebf9a6cc16ac73c671c/

Edited pages:
- [v20.2/multi-region-setup.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f7c610fb65636a98ac641ebf9a6cc16ac73c671c/v20.2/multi-region-setup.html)

2021-04-22 15:05 UTC, rmloveland requested changes
Closer but I think the indenting needs a tweak!  (PS thanks for the PR!!!!1!)

2021-04-22 15:05 UTC, rmloveland commented on v20.2/multi-region-setup.md
> +- [CockroachDB](install-cockroachdb-mac.html)
Hi Fabio!  This is still rendering weirdly in [the preview page](https://deploy-preview-9324--cockroachdb-docs.netlify.app/docs/v20.2/multi-region-setup.html).  To get this sublist to nest correctly, try indenting these bulleted links in by 4 spaces.

2021-09-25 02:16 UTC, jseldess commented
@rmloveland, can you please take this one over? You may need to open a fresh PR at this point.

2021-09-27 00:09 UTC, fabiog1901 reviewed
Hi Rich, trying to figure out how to accept your suggestions so we can move forward..

2021-09-27 14:26 UTC, rmloveland commented
> can you please take this one over? You may need to open a fresh PR at this point.

Sure!

2022-01-26 22:12 UTC, rmloveland commented
In the meantime, this appears to be fixed everywhere now as of this writing

- https://www.cockroachlabs.com/docs/v20.1/multi-region-setup.html
- https://www.cockroachlabs.com/docs/v20.2/multi-region-setup.html
- https://www.cockroachlabs.com/docs/v21.1/movr-flask-setup.html
- https://www.cockroachlabs.com/docs/v21.2/movr-flask-setup.html

Thanks for the PR @fabiog1901 - sorry for my delay.  This is now fixed at least :-)

2022-01-26 22:12 UTC, closed without merging