Licensing
cockroachdb/docs pull request #9338
Opened 2021-01-14 23:31 UTC by gemma-shay

Resolves #8990.
Update Licensing FAQ to reflect newer versions licensed under BSL.
Create new licensing reference doc that clarifies differences between BSL, CCL (free), and CCL (paid).
Move licensing info previously under Enterprise Features page into new Licensing page.

2021-01-14 23:31 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/9338)
<!-- Reviewable:end -->

2021-01-14 23:37 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/61541fffa6a02784ff5fb5fd1a66df55a46efe5b/

Edited pages:
- [v20.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/61541fffa6a02784ff5fb5fd1a66df55a46efe5b/v20.1/enterprise-licensing.html)
- [v20.1/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/61541fffa6a02784ff5fb5fd1a66df55a46efe5b/v20.1/licensing-faqs.html)
- [v20.1/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/61541fffa6a02784ff5fb5fd1a66df55a46efe5b/v20.1/licensing.html)
- [v20.2/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/61541fffa6a02784ff5fb5fd1a66df55a46efe5b/v20.2/enterprise-licensing.html)
- [v20.2/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/61541fffa6a02784ff5fb5fd1a66df55a46efe5b/v20.2/licensing-faqs.html)
- [v20.2/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/61541fffa6a02784ff5fb5fd1a66df55a46efe5b/v20.2/licensing.html)
- [v21.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/61541fffa6a02784ff5fb5fd1a66df55a46efe5b/v21.1/enterprise-licensing.html)
- [v21.1/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/61541fffa6a02784ff5fb5fd1a66df55a46efe5b/v21.1/licensing-faqs.html)
- [v21.1/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/61541fffa6a02784ff5fb5fd1a66df55a46efe5b/v21.1/licensing.html)

2021-01-19 22:08 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/

Edited pages:
- [v20.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.1/enterprise-licensing.html)
- [v20.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.1/gssapi_authentication.html)
- [v20.1/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.1/licensing-faqs.html)
- [v20.1/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.1/licensing.html)
- [v20.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.1/partitioning.html)
- [v20.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.1/restore.html)
- [v20.2/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/enterprise-licensing.html)
- [v20.2/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/gssapi_authentication.html)
- [v20.2/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/licensing-faqs.html)
- [v20.2/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/licensing.html)
- [v20.2/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/partitioning.html)
- [v20.2/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/restore.html)
- [v21.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v21.1/enterprise-licensing.html)
- [v21.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v21.1/gssapi_authentication.html)
- [v21.1/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v21.1/licensing-faqs.html)
- [v21.1/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v21.1/licensing.html)
- [v21.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v21.1/partitioning.html)
- [v21.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v21.1/restore.html)

2021-01-20 19:39 UTC, lnhsingh requested changes
Nice job! Only reviewed one version of each page, but comments apply to all edited versions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9338#-:-MRWIi-YBWK-WJge8cbL:b-nstzl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

___
*[v20.1/enterprise-licensing.md, line 9 at r2](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWC3k4-JFCI8JaG1WN:-MRWC3k5EA2hYywxXSOM:b-p92fks) ([raw file](https://github.com/cockroachdb/docs/blob/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.1/enterprise-licensing.md#L9)):*
> ```Markdown
> CockroachDB distributes a single binary that contains both core and [enterprise features](https://www.cockroachlabs.com/pricing/). You can use core features without any license key. However, to use the enterprise features, you need either a trial or an enterprise license key.
> 
> This page lists enterprise features. To obtain and set trial and enterprise license keys for CockroachDB, see [Licensing](licensing.html)
> ```

Suggested edit: `For information on how to obtain [...]`
___
*[v20.2/licensing.md, line 7 at r2](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWGh8L3ScWNe8OArA2:-MRWGh8L3ScWNe8OArA3:b69vhm) ([raw file](https://github.com/cockroachdb/docs/blob/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/licensing.md#L7)):*
> ```Markdown
> ---
> 
> ## Licensing Overview
> ```

Remove this H2 since there's no content above it and the title displays on the doc
___
*[v20.2/licensing.md, line 9 at r2](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWGmDf8CuxIN6p_WUn:-MRWGmDf8CuxIN6p_WUo:b-auxx6v) ([raw file](https://github.com/cockroachdb/docs/blob/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/licensing.md#L9)):*
> ```Markdown
> ## Licensing Overview
> 
> CockroachDB code is licensed in three ways: the Business Source License (BSL), Cockroach Community License (Free), and Cockroach Community License (Paid). Core features after version 19.1 are licensed under the BSL for three years before converting to the Apache 2.0 license. All enterprise features are licensed under the Cockroach Community License (CCL).
> ```

Suggestion: Make the first sentence a bulleted list for scanability
___
*[v20.2/licensing.md, line 11 at r2](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWGqVA9dkE_Np9GpFR:-MRWGqVA9dkE_Np9GpFS:b-x2uhl3) ([raw file](https://github.com/cockroachdb/docs/blob/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/licensing.md#L11)):*
> ```Markdown
> CockroachDB code is licensed in three ways: the Business Source License (BSL), Cockroach Community License (Free), and Cockroach Community License (Paid). Core features after version 19.1 are licensed under the BSL for three years before converting to the Apache 2.0 license. All enterprise features are licensed under the Cockroach Community License (CCL).
> 
> ### Types of licenses
> ```

This can be promoted to H2 now
___
*[v20.2/licensing.md, line 17 at r2](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWGtj4DRlCMt4h4fod:-MRWGtj4DRlCMt4h4foe:b-t3u0p0) ([raw file](https://github.com/cockroachdb/docs/blob/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/licensing.md#L17)):*
> ```Markdown
> **Business Source License** | BSL Features are free to use and the source code is available, but users may not use CockroachDB as a service without an agreement with Cockroach Labs.
> **Cockroach Community License (Free)** | CCL (Free) features are free to use, but the source code is not available to users.
> **Cockroach Community License (Paid)** | CCL (paid) features require an enterprise license key to access.
> ```

nit:  `CCL (paid)` > `CCL (Paid)`
___
*[v20.2/licensing.md, line 19 at r2](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWGwv88Wvafbf_OWsI:-MRWGwv88Wvafbf_OWsJ:b-ptbmew) ([raw file](https://github.com/cockroachdb/docs/blob/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/licensing.md#L19)):*
> ```Markdown
> **Cockroach Community License (Paid)** | CCL (paid) features require an enterprise license key to access.
> 
> All CockroachDB Code is included in the same binary. No license key is required to access BSL and CCL (Free) features. To access CCL (Paid) features, users have two options:
> ```

nit: `CockroachDB Code` > `CockroachDB code`
___
*[v20.2/licensing.md, line 28 at r2](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWH0VA-PkQLfk7sJ7o:-MRWH0VA-PkQLfk7sJ7p:boie7dw) ([raw file](https://github.com/cockroachdb/docs/blob/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/licensing.md#L28)):*
> ```Markdown
> {{site.data.alerts.end}}
> 
> ### Core feature licensing
> ```

This can also be promoted to H2
___
*[v20.2/licensing.md, line 30 at r2](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWGjaBBSCr84ngx1_D:-MRWGjaCEw60nidaBU6P:b-x2p2yl) ([raw file](https://github.com/cockroachdb/docs/blob/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/licensing.md#L30)):*
> ```Markdown
> ### Core feature licensing
> 
> The matrix below shows how core features are licensed. For a complete list of enterprise features, see [Enterprise Features](enterprise-licensing.html).
> ```

nit: `matrix` > `table`

Suggestion: Change the first sentence's punctuation from a period to a colon and move the second sentence to be after the table 
___
*[v20.2/licensing.md, line 32 at r2](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWGdwoEsUJ3LkrIKNk:-MRWGdwoEsUJ3LkrIKNl:b-wb637w) ([raw file](https://github.com/cockroachdb/docs/blob/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/licensing.md#L32)):*
> ```Markdown
> The matrix below shows how core features are licensed. For a complete list of enterprise features, see [Enterprise Features](enterprise-licensing.html).
> 
> Feature          | BSL | CCL (free)      | CCL (paid) 
> ```

The list of features should link to their relevant docs
___
*[v20.2/licensing.md, line 37 at r2](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWG_wH5nIGSPQf-5ul:-MRWG_wH5nIGSPQf-5um:b-fx8frx) ([raw file](https://github.com/cockroachdb/docs/blob/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/licensing.md#L37)):*
> ```Markdown
> **Export** | ✓ | |
> **Restore** | | ✓ |
> **Backup** (full backup) | | ✓ |
> ```

Suggestion: `Backup (full backup)` > `Full backup`

Also, link to `take-full-and-incremental-backups.html#full-backups`

^ Note that this link is only available in v20.2+, so you'll have to find a relevant link for 20.1
___
*[v20.2/licensing.md, line 38 at r2](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWGXLq2M8d0-wCZKKD:-MRWGXLq2M8d0-wCZKKE:bw0ts7y) ([raw file](https://github.com/cockroachdb/docs/blob/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/licensing.md#L38)):*
> ```Markdown
> **Restore** | | ✓ |
> **Backup** (full backup) | | ✓ |
> **Backup** (everything else) | | | ✓
> ```

Suggestion: maybe split this into two lines, one for`[Incremental Backups](take-full-and-incremental-backups.html#incremental-backups)` and another for [`Other Advanced Backup Usage`](take-full-and-incremental-backups.html#advanced-examples)

^ Note that these links are only available in v20.2+, so you'll have to find relevant links for 20.1
___
*[v20.2/licensing.md, line 44 at r2](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWHqKACHCgrCzEu67z:-MRWHqKB0vbDdv_kbTMH:b91mdw8) ([raw file](https://github.com/cockroachdb/docs/blob/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/licensing.md#L44)):*
> ```Markdown
> ## Obtain a license
> 
> To obtain a trial license, fill out [the registration form](https://www.cockroachlabs.com/get-cockroachdb/) and receive your trial license via email within a few minutes.
> ```

Suggestion: make these two lines bullets so their easier to differentiate
___
*[v20.2/licensing.md, line 50 at r2](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWID_A9iHFrfksTrOF:-MRWID_A9iHFrfksTrOG:b-7dpizn) ([raw file](https://github.com/cockroachdb/docs/blob/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/licensing.md#L50)):*
> ```Markdown
> ## Set a license
> 
> As th [...]

2021-01-20 21:30 UTC, gemma-shay reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9338)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

___
*[v20.1/enterprise-licensing.md, line 9 at r2](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWC3k4-JFCI8JaG1WN:-MRWVpz42_DVc6qMnyHq:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.1/enterprise-licensing.md#L9)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Suggested edit: `For information on how to obtain [...]`
</blockquote></details>

Done.
___
*[v20.2/licensing.md, line 7 at r2](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWGh8L3ScWNe8OArA2:-MRWW5iJ8hrTc8xWcBGX:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/licensing.md#L7)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Remove this H2 since there's no content above it and the title displays on the doc
</blockquote></details>

Done.
___
*[v20.2/licensing.md, line 9 at r2](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWGmDf8CuxIN6p_WUn:-MRWWY1bDsGLFXlFoOSw:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/licensing.md#L9)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Suggestion: Make the first sentence a bulleted list for scanability
</blockquote></details>

Done.
___
*[v20.2/licensing.md, line 11 at r2](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWGqVA9dkE_Np9GpFR:-MRWWq1K2Oxbfj5zfSuW:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/licensing.md#L11)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

This can be promoted to H2 now
</blockquote></details>

Done.
___
*[v20.2/licensing.md, line 28 at r2](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWH0VA-PkQLfk7sJ7o:-MRWX0I_C0YKYPnIz0Ad:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/licensing.md#L28)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

This can also be promoted to H2
</blockquote></details>

Done.
___
*[v20.2/licensing.md, line 32 at r2](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWGdwoEsUJ3LkrIKNk:-MRWXjJIEpY-MJS4MzmW:b-yjxn89) ([raw file](https://github.com/cockroachdb/docs/blob/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/licensing.md#L32)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

The list of features should link to their relevant docs
</blockquote></details>

Done. Just realized I only did this/my last round of editing in the 21.1 docs. Woops!
___
*[v20.2/licensing.md, line 37 at r2](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWG_wH5nIGSPQf-5ul:-MRWZ9gn3mNytG5veR8X:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/licensing.md#L37)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Suggestion: `Backup (full backup)` > `Full backup`

Also, link to `take-full-and-incremental-backups.html#full-backups`

^ Note that this link is only available in v20.2+, so you'll have to find a relevant link for 20.1
</blockquote></details>

Done.
___
*[v20.2/licensing.md, line 38 at r2](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWGXLq2M8d0-wCZKKD:-MRWZE0c2pkoDbAeTt_b:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/licensing.md#L38)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Suggestion: maybe split this into two lines, one for`[Incremental Backups](take-full-and-incremental-backups.html#incremental-backups)` and another for [`Other Advanced Backup Usage`](take-full-and-incremental-backups.html#advanced-examples)

^ Note that these links are only available in v20.2+, so you'll have to find relevant links for 20.1
</blockquote></details>

Done.
___
*[v20.2/licensing.md, line 44 at r2](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWHqKACHCgrCzEu67z:-MRW_3iLDxSDdv9-dQ7X:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/licensing.md#L44)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Suggestion: make these two lines bullets so their easier to differentiate
</blockquote></details>

Done.
___
*[v20.2/licensing.md, line 50 at r2](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWID_A9iHFrfksTrOF:-MRW_Azf0lahQe21OciU:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/licensing.md#L50)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Link to `set-cluster-setting.html`  
</blockquote></details>

Done.
___
*[v20.2/licensing.md, line 69 at r2](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWIMt3CmFWx8jO0S8i:-MRW_KmfAMkWMwaJO-oV:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/licensing.md#L69)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Link to `show-cluster-setting.html`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-20 21:35 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1476f4ee47c154939ea301884283fad507dcc21/

Edited pages:
- [v20.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1476f4ee47c154939ea301884283fad507dcc21/v20.1/enterprise-licensing.html)
- [v20.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1476f4ee47c154939ea301884283fad507dcc21/v20.1/gssapi_authentication.html)
- [v20.1/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1476f4ee47c154939ea301884283fad507dcc21/v20.1/licensing-faqs.html)
- [v20.1/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1476f4ee47c154939ea301884283fad507dcc21/v20.1/licensing.html)
- [v20.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1476f4ee47c154939ea301884283fad507dcc21/v20.1/partitioning.html)
- [v20.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1476f4ee47c154939ea301884283fad507dcc21/v20.1/restore.html)
- [v20.2/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1476f4ee47c154939ea301884283fad507dcc21/v20.2/enterprise-licensing.html)
- [v20.2/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1476f4ee47c154939ea301884283fad507dcc21/v20.2/gssapi_authentication.html)
- [v20.2/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1476f4ee47c154939ea301884283fad507dcc21/v20.2/licensing-faqs.html)
- [v20.2/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1476f4ee47c154939ea301884283fad507dcc21/v20.2/licensing.html)
- [v20.2/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1476f4ee47c154939ea301884283fad507dcc21/v20.2/partitioning.html)
- [v20.2/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1476f4ee47c154939ea301884283fad507dcc21/v20.2/restore.html)
- [v21.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1476f4ee47c154939ea301884283fad507dcc21/v21.1/enterprise-licensing.html)
- [v21.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1476f4ee47c154939ea301884283fad507dcc21/v21.1/gssapi_authentication.html)
- [v21.1/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1476f4ee47c154939ea301884283fad507dcc21/v21.1/licensing-faqs.html)
- [v21.1/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1476f4ee47c154939ea301884283fad507dcc21/v21.1/licensing.html)
- [v21.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1476f4ee47c154939ea301884283fad507dcc21/v21.1/partitioning.html)
- [v21.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1476f4ee47c154939ea301884283fad507dcc21/v21.1/restore.html)

2021-01-20 21:54 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3583f8530e9c368a437b986a8f5671e60d277edc/

Edited pages:
- [v20.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3583f8530e9c368a437b986a8f5671e60d277edc/v20.1/enterprise-licensing.html)
- [v20.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3583f8530e9c368a437b986a8f5671e60d277edc/v20.1/gssapi_authentication.html)
- [v20.1/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3583f8530e9c368a437b986a8f5671e60d277edc/v20.1/licensing-faqs.html)
- [v20.1/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3583f8530e9c368a437b986a8f5671e60d277edc/v20.1/licensing.html)
- [v20.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3583f8530e9c368a437b986a8f5671e60d277edc/v20.1/partitioning.html)
- [v20.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3583f8530e9c368a437b986a8f5671e60d277edc/v20.1/restore.html)
- [v20.2/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3583f8530e9c368a437b986a8f5671e60d277edc/v20.2/enterprise-licensing.html)
- [v20.2/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3583f8530e9c368a437b986a8f5671e60d277edc/v20.2/gssapi_authentication.html)
- [v20.2/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3583f8530e9c368a437b986a8f5671e60d277edc/v20.2/licensing-faqs.html)
- [v20.2/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3583f8530e9c368a437b986a8f5671e60d277edc/v20.2/licensing.html)
- [v20.2/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3583f8530e9c368a437b986a8f5671e60d277edc/v20.2/partitioning.html)
- [v20.2/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3583f8530e9c368a437b986a8f5671e60d277edc/v20.2/restore.html)
- [v21.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3583f8530e9c368a437b986a8f5671e60d277edc/v21.1/enterprise-licensing.html)
- [v21.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3583f8530e9c368a437b986a8f5671e60d277edc/v21.1/gssapi_authentication.html)
- [v21.1/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3583f8530e9c368a437b986a8f5671e60d277edc/v21.1/licensing-faqs.html)
- [v21.1/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3583f8530e9c368a437b986a8f5671e60d277edc/v21.1/licensing.html)
- [v21.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3583f8530e9c368a437b986a8f5671e60d277edc/v21.1/partitioning.html)
- [v21.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3583f8530e9c368a437b986a8f5671e60d277edc/v21.1/restore.html)

2021-01-20 22:24 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/82145ced3c02d75056fff7b1f2bbafe188a1395d/

Edited pages:
- [v20.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/82145ced3c02d75056fff7b1f2bbafe188a1395d/v20.1/enterprise-licensing.html)
- [v20.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/82145ced3c02d75056fff7b1f2bbafe188a1395d/v20.1/gssapi_authentication.html)
- [v20.1/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/82145ced3c02d75056fff7b1f2bbafe188a1395d/v20.1/licensing-faqs.html)
- [v20.1/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/82145ced3c02d75056fff7b1f2bbafe188a1395d/v20.1/licensing.html)
- [v20.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/82145ced3c02d75056fff7b1f2bbafe188a1395d/v20.1/partitioning.html)
- [v20.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/82145ced3c02d75056fff7b1f2bbafe188a1395d/v20.1/restore.html)
- [v20.2/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/82145ced3c02d75056fff7b1f2bbafe188a1395d/v20.2/enterprise-licensing.html)
- [v20.2/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/82145ced3c02d75056fff7b1f2bbafe188a1395d/v20.2/gssapi_authentication.html)
- [v20.2/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/82145ced3c02d75056fff7b1f2bbafe188a1395d/v20.2/licensing-faqs.html)
- [v20.2/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/82145ced3c02d75056fff7b1f2bbafe188a1395d/v20.2/licensing.html)
- [v20.2/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/82145ced3c02d75056fff7b1f2bbafe188a1395d/v20.2/partitioning.html)
- [v20.2/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/82145ced3c02d75056fff7b1f2bbafe188a1395d/v20.2/restore.html)
- [v21.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/82145ced3c02d75056fff7b1f2bbafe188a1395d/v21.1/enterprise-licensing.html)
- [v21.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/82145ced3c02d75056fff7b1f2bbafe188a1395d/v21.1/gssapi_authentication.html)
- [v21.1/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/82145ced3c02d75056fff7b1f2bbafe188a1395d/v21.1/licensing-faqs.html)
- [v21.1/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/82145ced3c02d75056fff7b1f2bbafe188a1395d/v21.1/licensing.html)
- [v21.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/82145ced3c02d75056fff7b1f2bbafe188a1395d/v21.1/partitioning.html)
- [v21.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/82145ced3c02d75056fff7b1f2bbafe188a1395d/v21.1/restore.html)

2021-01-20 22:28 UTC, lnhsingh requested changes
Couple more minor edits that apply to all versions!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9338#-:-MRWuRWE3MFhO6y4HHVV:bsni12z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @lnhsingh)

___
*[v20.2/licensing.md, line 38 at r2](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWGXLq2M8d0-wCZKKD:-MRWtwCl2EjtOKUawUwC:b-61ual8) ([raw file](https://github.com/cockroachdb/docs/blob/5f541cdec00dfbf2a81e0865b1e892f8f2ed38bc/v20.2/licensing.md#L38)):*
<details><summary><i>Previously, gemma-shay (Gemma Shay) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`Other Advanced Backups` > `Other Advanced Backup Features` maybe?
___
*[v20.2/licensing.md, line 8 at r3](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWu2y76JCcspnHKeKw:-MRWu2y76JCcspnHKeKx:b-rx5nrn) ([raw file](https://github.com/cockroachdb/docs/blob/82145ced3c02d75056fff7b1f2bbafe188a1395d/v20.2/licensing.md#L8)):*
> ```Markdown
> 
> Current CockroachDB code is licensed in three ways: 
> -  Business Source License (BSL)
> ```

Need an empty line before the bulleted list or else it won't render correctly


<!-- Sent from Reviewable.io -->

2021-01-21 15:34 UTC, gemma-shay reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9338)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

___
*[v20.2/licensing.md, line 8 at r3](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRWu2y76JCcspnHKeKw:-MR__0lyD9yBIad02S0i:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/82145ced3c02d75056fff7b1f2bbafe188a1395d/v20.2/licensing.md#L8)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Need an empty line before the bulleted list or else it won't render correctly
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-21 15:39 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1b0e0ef6b97383383e18ce8616f354de07382e8/

Edited pages:
- [v20.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1b0e0ef6b97383383e18ce8616f354de07382e8/v20.1/enterprise-licensing.html)
- [v20.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1b0e0ef6b97383383e18ce8616f354de07382e8/v20.1/gssapi_authentication.html)
- [v20.1/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1b0e0ef6b97383383e18ce8616f354de07382e8/v20.1/licensing-faqs.html)
- [v20.1/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1b0e0ef6b97383383e18ce8616f354de07382e8/v20.1/licensing.html)
- [v20.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1b0e0ef6b97383383e18ce8616f354de07382e8/v20.1/partitioning.html)
- [v20.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1b0e0ef6b97383383e18ce8616f354de07382e8/v20.1/restore.html)
- [v20.2/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1b0e0ef6b97383383e18ce8616f354de07382e8/v20.2/enterprise-licensing.html)
- [v20.2/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1b0e0ef6b97383383e18ce8616f354de07382e8/v20.2/gssapi_authentication.html)
- [v20.2/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1b0e0ef6b97383383e18ce8616f354de07382e8/v20.2/licensing-faqs.html)
- [v20.2/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1b0e0ef6b97383383e18ce8616f354de07382e8/v20.2/licensing.html)
- [v20.2/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1b0e0ef6b97383383e18ce8616f354de07382e8/v20.2/partitioning.html)
- [v20.2/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1b0e0ef6b97383383e18ce8616f354de07382e8/v20.2/restore.html)
- [v21.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1b0e0ef6b97383383e18ce8616f354de07382e8/v21.1/enterprise-licensing.html)
- [v21.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1b0e0ef6b97383383e18ce8616f354de07382e8/v21.1/gssapi_authentication.html)
- [v21.1/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1b0e0ef6b97383383e18ce8616f354de07382e8/v21.1/licensing-faqs.html)
- [v21.1/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1b0e0ef6b97383383e18ce8616f354de07382e8/v21.1/licensing.html)
- [v21.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1b0e0ef6b97383383e18ce8616f354de07382e8/v21.1/partitioning.html)
- [v21.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1b0e0ef6b97383383e18ce8616f354de07382e8/v21.1/restore.html)

2021-01-21 18:19 UTC, lnhsingh approved these changes
LGTM! A couple minor suggestions due to how the tables are rendering, but feel free to send this for technical review

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9338#-:-MRa9caPCM3d3j39i_z-:b-t32w04)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @lnhsingh)

___
*[v20.2/licensing.md, line 17 at r4](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRa9l1M4woxqPWSSVoJ:-MRa9l1M4woxqPWSSVoK:b-24ivrr) ([raw file](https://github.com/cockroachdb/docs/blob/f1b0e0ef6b97383383e18ce8616f354de07382e8/v20.2/licensing.md#L17)):*
> ```Markdown
> ## Types of licenses
> 
> Type | Description
> ```

Since the license names are long, they are wrapping funny. Can you add some HTML to the header for the Type column to keep that column at a fixed width so the license names are easier to read?
___
*[v20.2/licensing.md, line 30 at r4](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRa9xmA0WnIDobhRz5L:-MRa9xmA0WnIDobhRz5M:bpfyiql) ([raw file](https://github.com/cockroachdb/docs/blob/f1b0e0ef6b97383383e18ce8616f354de07382e8/v20.2/licensing.md#L30)):*
> ```Markdown
> Feature          | BSL | CCL (free)      | CCL (paid) 
> -----------------|-----|-----------------|---------------
> **[Import](import.html)** | | ✓ |
> ```

Can you use HTML to center the checkmarks so they are directly under their column header? I think that will make it a little easier to scan/read


<!-- Sent from Reviewable.io -->

2021-01-21 19:29 UTC, gemma-shay reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9338)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh and @piyush-singh)

___
*[v20.2/licensing.md, line 17 at r4](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRa9l1M4woxqPWSSVoJ:-MRaPwkF29DKKSYL7uCQ:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f1b0e0ef6b97383383e18ce8616f354de07382e8/v20.2/licensing.md#L17)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Since the license names are long, they are wrapping funny. Can you add some HTML to the header for the Type column to keep that column at a fixed width so the license names are easier to read?
</blockquote></details>

Done.
___
*[v20.2/licensing.md, line 30 at r4](https://reviewable.io/reviews/cockroachdb/docs/9338#-MRa9xmA0WnIDobhRz5L:-MRaPxeECDfwpUZU8jsE:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f1b0e0ef6b97383383e18ce8616f354de07382e8/v20.2/licensing.md#L30)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Can you use HTML to center the checkmarks so they are directly under their column header? I think that will make it a little easier to scan/read
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-21 19:29 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/79305947ef5e7e7ebac139750fbd53f13e092469/

Edited pages:
- [v20.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/79305947ef5e7e7ebac139750fbd53f13e092469/v20.1/enterprise-licensing.html)
- [v20.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/79305947ef5e7e7ebac139750fbd53f13e092469/v20.1/gssapi_authentication.html)
- [v20.1/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/79305947ef5e7e7ebac139750fbd53f13e092469/v20.1/licensing-faqs.html)
- [v20.1/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/79305947ef5e7e7ebac139750fbd53f13e092469/v20.1/licensing.html)
- [v20.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/79305947ef5e7e7ebac139750fbd53f13e092469/v20.1/partitioning.html)
- [v20.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/79305947ef5e7e7ebac139750fbd53f13e092469/v20.1/restore.html)
- [v20.2/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/79305947ef5e7e7ebac139750fbd53f13e092469/v20.2/enterprise-licensing.html)
- [v20.2/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/79305947ef5e7e7ebac139750fbd53f13e092469/v20.2/gssapi_authentication.html)
- [v20.2/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/79305947ef5e7e7ebac139750fbd53f13e092469/v20.2/licensing-faqs.html)
- [v20.2/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/79305947ef5e7e7ebac139750fbd53f13e092469/v20.2/licensing.html)
- [v20.2/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/79305947ef5e7e7ebac139750fbd53f13e092469/v20.2/partitioning.html)
- [v20.2/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/79305947ef5e7e7ebac139750fbd53f13e092469/v20.2/restore.html)
- [v21.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/79305947ef5e7e7ebac139750fbd53f13e092469/v21.1/enterprise-licensing.html)
- [v21.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/79305947ef5e7e7ebac139750fbd53f13e092469/v21.1/gssapi_authentication.html)
- [v21.1/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/79305947ef5e7e7ebac139750fbd53f13e092469/v21.1/licensing-faqs.html)
- [v21.1/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/79305947ef5e7e7ebac139750fbd53f13e092469/v21.1/licensing.html)
- [v21.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/79305947ef5e7e7ebac139750fbd53f13e092469/v21.1/partitioning.html)
- [v21.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/79305947ef5e7e7ebac139750fbd53f13e092469/v21.1/restore.html)

2021-01-25 19:51 UTC, gemma-shay commented
Wondering where to put the new Licensing page in the side nav. Lauren and I were thinking either under **Reference** or **Get Started**. Any thoughts, @jseldess @piyush-singh?

2021-01-25 19:56 UTC, jseldess commented
@lnhsingh, @gemma-shay, would we consider incorporating this info and guidance into the Licensing FAQ? It would be nice to be able to reference that single page...

2021-01-25 20:15 UTC, lnhsingh commented
@jseldess I think if we want to combine the new content with the FAQ into one page, it should be an "overview" rather than an FAQ. So either way, we need to find a new place for licensing content because I don't think it should live under FAQs

2021-01-25 20:32 UTC, gemma-shay commented
@lnhsingh @jseldess One page sounds good! I'll work the FAQ info into the Licensing Overview if that's okay.

2021-01-25 21:27 UTC, jseldess commented
@lnhsingh, @gemma-shay, I defer to you on this. That suggestion was a bit of a drive-by.

2021-01-26 19:26 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/

Edited pages:
- [releases/v20.1.0-beta.3.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/releases/v20.1.0-beta.3.html)
- [releases/v20.1.0.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/releases/v20.1.0.html)
- [v20.1/cockroach-version.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.1/cockroach-version.html)
- [v20.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.1/enterprise-licensing.html)
- [v20.1/frequently-asked-questions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.1/frequently-asked-questions.html)
- [v20.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.1/gssapi_authentication.html)
- [v20.1/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.1/index.html)
- [v20.1/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.1/licensing.html)
- [v20.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.1/partitioning.html)
- [v20.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.1/restore.html)
- [v20.2/cockroach-version.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/cockroach-version.html)
- [v20.2/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/enterprise-licensing.html)
- [v20.2/frequently-asked-questions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/frequently-asked-questions.html)
- [v20.2/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/gssapi_authentication.html)
- [v20.2/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/index.html)
- [v20.2/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/licensing.html)
- [v20.2/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/partitioning.html)
- [v20.2/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/restore.html)
- [v21.1/cockroach-version.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/v21.1/cockroach-version.html)
- [v21.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/v21.1/enterprise-licensing.html)
- [v21.1/frequently-asked-questions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/v21.1/frequently-asked-questions.html)
- [v21.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/v21.1/gssapi_authentication.html)
- [v21.1/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/v21.1/index.html)
- [v21.1/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/v21.1/licensing.html)
- [v21.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/v21.1/partitioning.html)
- [v21.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b7e6a2984465b170a0745cc22b3da3cee5da5616/v21.1/restore.html)

2021-01-26 22:31 UTC, lnhsingh requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9338)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @lnhsingh)

___
*[v20.2/licensing.md, line 10 at r6](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS-agHnEm4kkBUnypHl:-MS-agHnEm4kkBUnypHm:b-f8tu2e) ([raw file](https://github.com/cockroachdb/docs/blob/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/licensing.md#L10)):*
> ```Markdown
> Current CockroachDB code is licensed in three ways: 
> 
> -  Business Source License (BSL)
> ```

Suggestion: Add anchor links to the BSL / CCL lines in the Types of licenses table and link these bullets to those new anchor links
___
*[v20.2/licensing.md, line 14 at r6](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS-b57KBIdCk_4KG4gp:-MS-b57KBIdCk_4KG4gq:b-ke7uja) ([raw file](https://github.com/cockroachdb/docs/blob/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/licensing.md#L14)):*
> ```Markdown
> -  Cockroach Community License (Paid)
> 
> Core features released up to and including version 19.1 are licensed under Apache 2.0. After version 19.1, core features are licensed under the BSL for three years before converting to the Apache 2.0 license. Once a release is published under the BSL, the license cannot be changed to prevent code from becoming open source at the specified change date.
> ```

Link to an Apache anchor link (add anchor to Types of licenses table)
___
*[v20.2/licensing.md, line 14 at r6](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS-bQGTCL2zla41SzTA:-MS-bQGTCL2zla41SzTB:b-6auydu) ([raw file](https://github.com/cockroachdb/docs/blob/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/licensing.md#L14)):*
> ```Markdown
> -  Cockroach Community License (Paid)
> 
> Core features released up to and including version 19.1 are licensed under Apache 2.0. After version 19.1, core features are licensed under the BSL for three years before converting to the Apache 2.0 license. Once a release is published under the BSL, the license cannot be changed to prevent code from becoming open source at the specified change date.
> ```

"Core features" should link to the `Core feature licensing` section
___
*[v20.2/licensing.md, line 22 at r6](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS-_ykT7pdMm9GvMMTH:-MS-_ykT7pdMm9GvMMTI:b-t6ebg6) ([raw file](https://github.com/cockroachdb/docs/blob/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/licensing.md#L22)):*
> ```Markdown
> Type | Description
> -------------|------------
> **Apache 2.0 License** | Core features under the Apache License are free to use and fully open-source. BSL features convert to this license three years after their release. For license conversion dates, see the table below.
> ```

"See the table below" should either be a link (and add an anchor link to the table) or changed to the new heading title (see next comment) and linked.
___
*[v20.2/licensing.md, line 29 at r6](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS-_r3rEMNc6lri0nCK:-MS-_r3rEMNc6lri0nCL:ba3a01n) ([raw file](https://github.com/cockroachdb/docs/blob/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/licensing.md#L29)):*
> ```Markdown
> For additional custom licensing options, [contact us](https://support.cockroachlabs.com/hc/en-us).
> 
> The following table lists the current license for non-CCL features for each published release:
> ```

I think this needs a H3 called "License conversion timeline" or something along those lines, and more context. I think you can repeat some of the information presented in the "Types of licenses" table:

```
BSL features convert to this license three years after their release. The following table lists the current license for non-CCL features for each published release:
```
___
*[v20.2/licensing.md, line 40 at r6](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS-_Q5g09CrMfzKZPVb:-MS-_Q5g09CrMfzKZPVc:bw0i7l3) ([raw file](https://github.com/cockroachdb/docs/blob/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/licensing.md#L40)):*
> ```Markdown
> 2.0 | Apache 2.0 | -
> 
> {{site.data.alerts.callout_success}}
> ```

I think this callout can be deleted since the switch to BSL happened in 19.2.
___
*[v20.2/licensing.md, line 46 at r6](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS-jsdB4w8s6a2fFhKw:-MS-jsdB4w8s6a2fFhKx:bm2ehha) ([raw file](https://github.com/cockroachdb/docs/blob/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/licensing.md#L46)):*
> ```Markdown
> ## Core feature licensing
> 
> The table below shows how core features are licensed. For a complete list of enterprise features, see [Enterprise Features](enterprise-licensing.html).
> ```

I think this first sentence is a little misleading-- it's a table showing how _some_ core features are licensed. Do we have a full list of core features in the docs that we can refer to? If not, I think you can add a link to the marketing page Andy sent you to a row at the bottom of the table that says "All other core features" and select the license it falls under (I think BSL, right?).

Similarly, the second sentence here is confusing because it talks about enterprise features, even though we're in a section about core features. I would suggest moving the second sentence to be after the table, perhaps as a callout that also gives more context something like:

```
<callout>
[All enterprise features](link) are included in the CCL Paid. See [Obtain a license](#obtain-a-license) for more information.
</callout>
```

___
*[v20.2/licensing.md, line 67 at r6](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS-o43b0KVARF3QxmxV:-MS-o43b0KVARF3QxmxW:b-7kd516) ([raw file](https://github.com/cockroachdb/docs/blob/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/licensing.md#L67)):*
> ```Markdown
> 
> {{site.data.alerts.callout_success}}
> For quick local testing of Enterprise features, you can use the [`cockroach demo`](cockroach-demo.html) command, which starts a temporary, in-memory cluster with a SQL shell open and a trial license applied automatically.
> ```

nit: "enterprise features" doesn't need to be capitalized
___
*[v20.2/licensing.md, line 131 at r6](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS-oa1854pqry5JFw9W:-MS-oa1854pqry5JFw9X:b-sko1xy) ([raw file](https://github.com/cockroachdb/docs/blob/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/licensing.md#L131)):*
> ```Markdown
> To renew an expired license, <a href="mailto:sales@cockroachlabs.com">contact Sales</a> and then [set](licensing.html#set-a-license) the new license.
> 
> ## Additional FAQs
> ```

This can just be called FAQs
___
*[v20.2/licensing.md, line 141 at r6](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS-oPtB-Tl2Iz1Hu2x5:-MS-oPtB-Tl2Iz1Hu2x6:bskhddh) ([raw file](https://github.com/cockroachdb/docs/blob/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/licensing.md#L141)):*
> ```Markdown
> Hosting CockroachDB as a service means creating an offering that allows third parties (other than your employees and contractors) to operate a database. Specifically, third parties cannot modify table schemas.
> 
> ### What are the differences between the BSL for CockroachDB and MariaDB’s MaxScale?
> ```

I think this question can be removed
___
*[v20.2/licensing.md, line 155 at r6](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS-o9sp52UIgAvlc8v0:-MS-o9sq4RgEl7MeD5FV:bn8j7ha) ([raw file](https://github.com/cockroachdb/docs/blob/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/licensing.md#L155)):*
> ```Markdown
> ### I work for a non-profit, as a student, or in academia, and I would like to use CockroachDB. Do I need a license to access enterprise features?
> 
> Cockroach Labs is willing to offer self-hosted CockroachDB enterprise features free of charge and discounted prices for CockroachCloud to select non-profit organizations and non-commercial academic projects. To learn more, please [contact us](https://support.cockroachlabs.com/hc/en-us).
> ```

I think we can get rid of this FAQ and move the answer [...]

2021-01-27 16:45 UTC, gemma-shay reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9338)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

___
*[v20.2/licensing.md, line 10 at r6](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS-agHnEm4kkBUnypHl:-MS3ZeGT56WcN67AV12n:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/licensing.md#L10)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Suggestion: Add anchor links to the BSL / CCL lines in the Types of licenses table and link these bullets to those new anchor links
</blockquote></details>

Done.
___
*[v20.2/licensing.md, line 14 at r6](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS-b57KBIdCk_4KG4gp:-MS3ZfHa2lOrztJOmza7:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/licensing.md#L14)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Link to an Apache anchor link (add anchor to Types of licenses table)
</blockquote></details>

Done.
___
*[v20.2/licensing.md, line 14 at r6](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS-bQGTCL2zla41SzTA:-MS3ZhchE2gb9fnRix9u:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/licensing.md#L14)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

"Core features" should link to the `Core feature licensing` section
</blockquote></details>

Done.
___
*[v20.2/licensing.md, line 22 at r6](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS-_ykT7pdMm9GvMMTH:-MS3ZnzT6FO4LT80Kvcm:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/licensing.md#L22)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

"See the table below" should either be a link (and add an anchor link to the table) or changed to the new heading title (see next comment) and linked.
</blockquote></details>

Done.
___
*[v20.2/licensing.md, line 29 at r6](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS-_r3rEMNc6lri0nCK:-MS3ZpzG1A2i2br4QhZY:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/licensing.md#L29)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

I think this needs a H3 called "License conversion timeline" or something along those lines, and more context. I think you can repeat some of the information presented in the "Types of licenses" table:

```
BSL features convert to this license three years after their release. The following table lists the current license for non-CCL features for each published release:
```
</blockquote></details>

Done.
___
*[v20.2/licensing.md, line 40 at r6](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS-_Q5g09CrMfzKZPVb:-MS3ZrXj-mfghflu9MGf:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/licensing.md#L40)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

I think this callout can be deleted since the switch to BSL happened in 19.2.
</blockquote></details>

Done.
___
*[v20.2/licensing.md, line 46 at r6](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS-jsdB4w8s6a2fFhKw:-MS3_k8Z6ApA8I5xGi_6:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/licensing.md#L46)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

I think this first sentence is a little misleading-- it's a table showing how _some_ core features are licensed. Do we have a full list of core features in the docs that we can refer to? If not, I think you can add a link to the marketing page Andy sent you to a row at the bottom of the table that says "All other core features" and select the license it falls under (I think BSL, right?).

Similarly, the second sentence here is confusing because it talks about enterprise features, even though we're in a section about core features. I would suggest moving the second sentence to be after the table, perhaps as a callout that also gives more context something like:

```
<callout>
[All enterprise features](link) are included in the CCL Paid. See [Obtain a license](#obtain-a-license) for more information.
</callout>
</blockquote></details>

Done.
___
*[v20.2/licensing.md, line 131 at r6](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS-oa1854pqry5JFw9W:-MS3efWQ5vnzPiz_bSWl:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/licensing.md#L131)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

This can just be called FAQs
</blockquote></details>

Done.
___
*[v20.2/licensing.md, line 141 at r6](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS-oPtB-Tl2Iz1Hu2x5:-MS3eivD5PAeUlzVxCPo:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/licensing.md#L141)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

I think this question can be removed
</blockquote></details>

Done.
___
*[v20.2/licensing.md, line 155 at r6](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS-o9sp52UIgAvlc8v0:-MS3eobi6MdlE9H4Ndrd:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/b7e6a2984465b170a0745cc22b3da3cee5da5616/v20.2/licensing.md#L155)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

I think we can get rid of this FAQ and move the answer into a note callout in Obtain a License
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-27 16:49 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/

Edited pages:
- [releases/v20.1.0-beta.3.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/releases/v20.1.0-beta.3.html)
- [releases/v20.1.0.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/releases/v20.1.0.html)
- [v20.1/cockroach-version.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/v20.1/cockroach-version.html)
- [v20.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/v20.1/enterprise-licensing.html)
- [v20.1/frequently-asked-questions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/v20.1/frequently-asked-questions.html)
- [v20.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/v20.1/gssapi_authentication.html)
- [v20.1/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/v20.1/index.html)
- [v20.1/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/v20.1/licensing.html)
- [v20.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/v20.1/partitioning.html)
- [v20.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/v20.1/restore.html)
- [v20.2/cockroach-version.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/v20.2/cockroach-version.html)
- [v20.2/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/v20.2/enterprise-licensing.html)
- [v20.2/frequently-asked-questions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/v20.2/frequently-asked-questions.html)
- [v20.2/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/v20.2/gssapi_authentication.html)
- [v20.2/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/v20.2/index.html)
- [v20.2/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/v20.2/licensing.html)
- [v20.2/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/v20.2/partitioning.html)
- [v20.2/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/v20.2/restore.html)
- [v21.1/cockroach-version.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/v21.1/cockroach-version.html)
- [v21.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/v21.1/enterprise-licensing.html)
- [v21.1/frequently-asked-questions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/v21.1/frequently-asked-questions.html)
- [v21.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/v21.1/gssapi_authentication.html)
- [v21.1/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/v21.1/index.html)
- [v21.1/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/v21.1/licensing.html)
- [v21.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/v21.1/partitioning.html)
- [v21.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6f03fe314efb5236ae947a8b59fd2be365993e28/v21.1/restore.html)

2021-01-27 20:53 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/

Edited pages:
- [releases/v20.1.0-beta.3.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/releases/v20.1.0-beta.3.html)
- [releases/v20.1.0.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/releases/v20.1.0.html)
- [v20.1/cockroach-version.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/v20.1/cockroach-version.html)
- [v20.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/v20.1/enterprise-licensing.html)
- [v20.1/frequently-asked-questions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/v20.1/frequently-asked-questions.html)
- [v20.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/v20.1/gssapi_authentication.html)
- [v20.1/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/v20.1/index.html)
- [v20.1/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/v20.1/licensing.html)
- [v20.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/v20.1/partitioning.html)
- [v20.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/v20.1/restore.html)
- [v20.2/cockroach-version.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/v20.2/cockroach-version.html)
- [v20.2/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/v20.2/enterprise-licensing.html)
- [v20.2/frequently-asked-questions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/v20.2/frequently-asked-questions.html)
- [v20.2/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/v20.2/gssapi_authentication.html)
- [v20.2/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/v20.2/index.html)
- [v20.2/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/v20.2/licensing.html)
- [v20.2/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/v20.2/partitioning.html)
- [v20.2/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/v20.2/restore.html)
- [v21.1/cockroach-version.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/v21.1/cockroach-version.html)
- [v21.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/v21.1/enterprise-licensing.html)
- [v21.1/frequently-asked-questions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/v21.1/frequently-asked-questions.html)
- [v21.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/v21.1/gssapi_authentication.html)
- [v21.1/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/v21.1/index.html)
- [v21.1/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/v21.1/licensing.html)
- [v21.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/v21.1/partitioning.html)
- [v21.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1e914310f194e00a350b362d946a5d8adf4b68d/v21.1/restore.html)

2021-01-28 16:53 UTC, bdarnell reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9338)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay, @lnhsingh, and @piyush-singh)

___
*[v21.1/licensing.md, line 14 at r7](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS8qStP7MOaqk8jmdCO:-MS8qStP7MOaqk8jmdCP:b-nojsbq) ([raw file](https://github.com/cockroachdb/docs/blob/f1e914310f194e00a350b362d946a5d8adf4b68d/v21.1/licensing.md#L14)):*
> ```Markdown
> -  [Cockroach Community License (Paid)](#ccl-paid)
> 
> [Core features](#core-feature-licensing) released up to and including version 19.1 are licensed under [Apache 2.0](#apache). After version 19.1, core features are licensed under the BSL for three years before converting to the Apache 2.0 license.
> ```

One thing we've not been very clear about is whether "core" is equivalent to BSL/Apache or if it's everything you can use for free. I think we mainly use the latter now so *some* core features are BSL/apache while others are CCL-free. 
___
*[v21.1/licensing.md, line 23 at r7](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS8rBQQ4Ps8MlvEJWlz:-MS8rBQQ4Ps8MlvEJWm-:b-clt4zy) ([raw file](https://github.com/cockroachdb/docs/blob/f1e914310f194e00a350b362d946a5d8adf4b68d/v21.1/licensing.md#L23)):*
> ```Markdown
> -------------|------------
> <a name="apache"></a>**Apache 2.0 License** | Core features under the Apache License are free to use and fully open-source. BSL features convert to this license three years after their release. For license conversion dates, see the [table below](#license-conversion-timeline).
> <a name="bsl"></a>**Business Source License**| BSL features are free to use and the source code is available, but users may not use CockroachDB [as a service](#what-constitutes-hosting-cockroachdb-as-a-service) without an agreement with Cockroach Labs. Outside of this usage, BSL features will continue to be free to use and source code will continue to be available. Although MariaDB has not certified the BSL as complying to the [Open Source Definition](https://en.wikipedia.org/wiki/The_Open_Source_Definition) by the [Open Source Initiative](https://en.wikipedia.org/wiki/Open_Source_Initiative) (OSI), most of the OSI criteria are met.
> ```

Remove the reference to MariaDB here - either use the passive voice or make the OSI the subject of the sentence ("The Open Source Initiative has not certified the BSL...").

"Most of the OSI criteria are met" sounds weirdly defensive to me. I'm not sure if we want to say this. 
___
*[v21.1/licensing.md, line 24 at r7](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS8rl4A5rsNKPJ0PUq0:-MS8rl4A5rsNKPJ0PUq1:bdkrujj) ([raw file](https://github.com/cockroachdb/docs/blob/f1e914310f194e00a350b362d946a5d8adf4b68d/v21.1/licensing.md#L24)):*
> ```Markdown
> <a name="apache"></a>**Apache 2.0 License** | Core features under the Apache License are free to use and fully open-source. BSL features convert to this license three years after their release. For license conversion dates, see the [table below](#license-conversion-timeline).
> <a name="bsl"></a>**Business Source License**| BSL features are free to use and the source code is available, but users may not use CockroachDB [as a service](#what-constitutes-hosting-cockroachdb-as-a-service) without an agreement with Cockroach Labs. Outside of this usage, BSL features will continue to be free to use and source code will continue to be available. Although MariaDB has not certified the BSL as complying to the [Open Source Definition](https://en.wikipedia.org/wiki/The_Open_Source_Definition) by the [Open Source Initiative](https://en.wikipedia.org/wiki/Open_Source_Initiative) (OSI), most of the OSI criteria are met.
> <a name="ccl-free"></a>**Cockroach <br/> Community License (Free)** | CCL (Free) features are free to use and the source code is available to view, but the source code cannot be used without an agreement with Cockroach Labs.
> ```

Free CCL features do not require an agreement with Cockroach Labs. 

For both free and paid CCL features, the source code is available to both view and modify; only the ability to *use* it is restricted (in the case of paid enterprise features). 
___
*[v21.1/licensing.md, line 44 at r7](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS8sUvW-vUSIGkgBbo1:-MS8sUvW-vUSIGkgBbo2:b-rzj2hh) ([raw file](https://github.com/cockroachdb/docs/blob/f1e914310f194e00a350b362d946a5d8adf4b68d/v21.1/licensing.md#L44)):*
> ```Markdown
> ## Core feature licensing
> 
> The table below shows how certain core features are licensed:
> ```

Remove "core" this list isn't just core features. 

Why is export the only BSL feature called out separately instead of being in "all other core"? 

The most important thing here is that we list all the CCL features and whether they're paid or free (I don't think we have this information easily available elsewhere). Maybe we should remove the BSL column and focus on that?

This list also changes over time - RBAC used to be CCL-paid and moved to BSL (I think; maybe it was CCL-free), and backup/restore moved from CCL-paid to CCL-free. (The backup/restore move happened in 20.2 so the 20.1 version of this page needs to be corrected)  We should probably mention that you need to view the version of this page corresponding to your version of cockroachdb (and maybe add annotations listing changes?)


<!-- Sent from Reviewable.io -->

2021-02-01 16:25 UTC, gemma-shay reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9338)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @gemma-shay, @lnhsingh, and @piyush-singh)

___
*[v21.1/licensing.md, line 24 at r7](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS8rl4A5rsNKPJ0PUq0:-MSTKr3OC-UL6mOHOUaB:br3tn0h) ([raw file](https://github.com/cockroachdb/docs/blob/f1e914310f194e00a350b362d946a5d8adf4b68d/v21.1/licensing.md#L24)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Free CCL features do not require an agreement with Cockroach Labs. 

For both free and paid CCL features, the source code is available to both view and modify; only the ability to *use* it is restricted (in the case of paid enterprise features). 
</blockquote></details>

I've been struggling with how to phrase this. Would it be correct to say the CCL (free) source code cannot be *reused* without an agreement?
___
*[v21.1/licensing.md, line 44 at r7](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS8sUvW-vUSIGkgBbo1:-MSTM38C1prXfKShoEmu:b-3nuvvy) ([raw file](https://github.com/cockroachdb/docs/blob/f1e914310f194e00a350b362d946a5d8adf4b68d/v21.1/licensing.md#L44)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Remove "core" this list isn't just core features. 

Why is export the only BSL feature called out separately instead of being in "all other core"? 

The most important thing here is that we list all the CCL features and whether they're paid or free (I don't think we have this information easily available elsewhere). Maybe we should remove the BSL column and focus on that?

This list also changes over time - RBAC used to be CCL-paid and moved to BSL (I think; maybe it was CCL-free), and backup/restore moved from CCL-paid to CCL-free. (The backup/restore move happened in 20.2 so the 20.1 version of this page needs to be corrected)  We should probably mention that you need to view the version of this page corresponding to your version of cockroachdb (and maybe add annotations listing changes?)
</blockquote></details>

I think the BSL features are useful to contrast/show the boundaries of CCL licensing, but can remove if it distracts from the point. Maybe @piyush-singh has an opinion?

Good catch on the version changes, thank you for that! I'll add a callout. Should I add RBAC to the table? I believe it changed in 20.1, so it would just be under BSL for all pages.


<!-- Sent from Reviewable.io -->

2021-02-01 17:24 UTC, bdarnell reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9338)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay, @lnhsingh, and @piyush-singh)

___
*[v21.1/licensing.md, line 24 at r7](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS8rl4A5rsNKPJ0PUq0:-MSTb-YeCA87eVgcOIjo:bi1dsaz) ([raw file](https://github.com/cockroachdb/docs/blob/f1e914310f194e00a350b362d946a5d8adf4b68d/v21.1/licensing.md#L24)):*
<details><summary><i>Previously, gemma-shay (Gemma Shay) wrote…</i></summary><blockquote>

I've been struggling with how to phrase this. Would it be correct to say the CCL (free) source code cannot be *reused* without an agreement?
</blockquote></details>

This is a question for Dan. There aren't a lot of restrictions on what you can do with the free-CCL code, but there are some and I'm not sure how to sum it up concisely and accurately. 
___
*[v21.1/licensing.md, line 44 at r7](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS8sUvW-vUSIGkgBbo1:-MST_O6B-Qc7h4HDdD-t:b1zttap) ([raw file](https://github.com/cockroachdb/docs/blob/f1e914310f194e00a350b362d946a5d8adf4b68d/v21.1/licensing.md#L44)):*
<details><summary><i>Previously, gemma-shay (Gemma Shay) wrote…</i></summary><blockquote>

I think the BSL features are useful to contrast/show the boundaries of CCL licensing, but can remove if it distracts from the point. Maybe @piyush-singh has an opinion?

Good catch on the version changes, thank you for that! I'll add a callout. Should I add RBAC to the table? I believe it changed in 20.1, so it would just be under BSL for all pages.
</blockquote></details>

It's a little odd seeing export as the only BSL feature. I'd lean towards either removing it or adding more BSL features that help define the boundaries. For example, you could add `cockroach dump` in the BSL column (especially for 20.1 where backup/restore was paid).

I'd add all of the enterprise features from https://www.cockroachlabs.com/docs/stable/enterprise-licensing.html here. Then we could add table-level zone configs as a BSL feature (the free counterpart to geo-partitioning), and password and certificate authentication as the BSL counterpart to GSSAPI/kerberos.

RBAC is probably worth a mention in this expanded table with a footnote about the historical change. 


<!-- Sent from Reviewable.io -->

2021-02-02 15:45 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/

Edited pages:
- [releases/v20.1.0-beta.3.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/releases/v20.1.0-beta.3.html)
- [releases/v20.1.0.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/releases/v20.1.0.html)
- [v20.1/cockroach-version.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v20.1/cockroach-version.html)
- [v20.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v20.1/enterprise-licensing.html)
- [v20.1/frequently-asked-questions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v20.1/frequently-asked-questions.html)
- [v20.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v20.1/gssapi_authentication.html)
- [v20.1/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v20.1/index.html)
- [v20.1/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v20.1/licensing.html)
- [v20.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v20.1/partitioning.html)
- [v20.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v20.1/restore.html)
- [v20.2/cockroach-version.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v20.2/cockroach-version.html)
- [v20.2/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v20.2/enterprise-licensing.html)
- [v20.2/frequently-asked-questions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v20.2/frequently-asked-questions.html)
- [v20.2/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v20.2/gssapi_authentication.html)
- [v20.2/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v20.2/index.html)
- [v20.2/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v20.2/licensing.html)
- [v20.2/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v20.2/partitioning.html)
- [v20.2/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v20.2/restore.html)
- [v21.1/cockroach-version.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v21.1/cockroach-version.html)
- [v21.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v21.1/enterprise-licensing.html)
- [v21.1/frequently-asked-questions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v21.1/frequently-asked-questions.html)
- [v21.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v21.1/gssapi_authentication.html)
- [v21.1/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v21.1/index.html)
- [v21.1/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v21.1/licensing.html)
- [v21.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v21.1/partitioning.html)
- [v21.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v21.1/restore.html)

2021-02-02 15:48 UTC, gemma-shay reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9338)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @lnhsingh, and @piyush-singh)

___
*[v21.1/licensing.md, line 14 at r7](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS8qStP7MOaqk8jmdCO:-MSUYbycAjw9veMnGi3y:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f1e914310f194e00a350b362d946a5d8adf4b68d/v21.1/licensing.md#L14)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

One thing we've not been very clear about is whether "core" is equivalent to BSL/Apache or if it's everything you can use for free. I think we mainly use the latter now so *some* core features are BSL/apache while others are CCL-free. 
</blockquote></details>

Done.
___
*[v21.1/licensing.md, line 23 at r7](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS8rBQQ4Ps8MlvEJWlz:-MSUZcD09fAjm9Dp5d-P:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f1e914310f194e00a350b362d946a5d8adf4b68d/v21.1/licensing.md#L23)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Remove the reference to MariaDB here - either use the passive voice or make the OSI the subject of the sentence ("The Open Source Initiative has not certified the BSL...").

"Most of the OSI criteria are met" sounds weirdly defensive to me. I'm not sure if we want to say this. 
</blockquote></details>

Done.
___
*[v21.1/licensing.md, line 24 at r7](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS8rl4A5rsNKPJ0PUq0:-MSUZipi5LsAsy33T1MW:b3r2cwk) ([raw file](https://github.com/cockroachdb/docs/blob/f1e914310f194e00a350b362d946a5d8adf4b68d/v21.1/licensing.md#L24)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This is a question for Dan. There aren't a lot of restrictions on what you can do with the free-CCL code, but there are some and I'm not sure how to sum it up concisely and accurately. 
</blockquote></details>

According to Dan there are some potential revisions to our licensing coming soon, so it would be best to put this on hold until that's done. Changing the wording for now but will come back to this.
___
*[v21.1/licensing.md, line 44 at r7](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS8sUvW-vUSIGkgBbo1:-MSYLT-N8tGG4v0amEGq:bb6un1j) ([raw file](https://github.com/cockroachdb/docs/blob/f1e914310f194e00a350b362d946a5d8adf4b68d/v21.1/licensing.md#L44)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

It's a little odd seeing export as the only BSL feature. I'd lean towards either removing it or adding more BSL features that help define the boundaries. For example, you could add `cockroach dump` in the BSL column (especially for 20.1 where backup/restore was paid).

I'd add all of the enterprise features from https://www.cockroachlabs.com/docs/stable/enterprise-licensing.html here. Then we could add table-level zone configs as a BSL feature (the free counterpart to geo-partitioning), and password and certificate authentication as the BSL counterpart to GSSAPI/kerberos.

RBAC is probably worth a mention in this expanded table with a footnote about the historical change. 
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-02-02 16:40 UTC, bdarnell approved these changes
> Reviewed 2 of 20 files at r6, 1 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9338)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @lnhsingh, and @piyush-singh)



<!-- Sent from Reviewable.io -->

2021-02-02 19:06 UTC, piyush-singh requested changes
> Reviewed 15 of 18 files at r2, 3 of 9 files at r3, 15 of 20 files at r6, 2 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9338)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @gemma-shay, and @lnhsingh)

___
*[v20.1/licensing.md, line 14 at r7](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS8ncm89MszMiU0poaS:-MS8ncm89MszMiU0poaT:b-ndnchf) ([raw file](https://github.com/cockroachdb/docs/blob/f1e914310f194e00a350b362d946a5d8adf4b68d/v20.1/licensing.md#L14)):*
> ```
> After version 19.1
> ```
Perhaps "Starting with 19.2"
___
*[v20.1/licensing.md, line 76 at r8](https://reviewable.io/reviews/cockroachdb/docs/9338#-MSYeSnJ8II0KGrOBM21:-MSYeSnJ8II0KGrOBM22:b-tr19ob) ([raw file](https://github.com/cockroachdb/docs/blob/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v20.1/licensing.md#L76)):*
> ```Markdown
> ## Obtain a license
> 
> All CockroachDB code is included in the same binary. No license key is required to access BSL and CCL (Free) features. To access CCL (Paid) features, users have two options:
> ```

It may be worth calling out the 30 day free trial of CockroachCloud as it includes enterprise functionality. Will defer to you and perhaps @lnhsingh on whether this is the best place to include that. This would apply across versions.
___
*[v20.2/licensing.md, line 109 at r8](https://reviewable.io/reviews/cockroachdb/docs/9338#-MSYmA1OA6kl5L8eB5r9:-MSYmA1OA6kl5L8eB5rA:b-3g4z32) ([raw file](https://github.com/cockroachdb/docs/blob/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v20.2/licensing.md#L109)):*
> ```Markdown
> ~~~
> 
> ## Verify a license
> ```

I think it would make sense to add a section here that highlights monitoring for license expiry. We now have a time series metric that users can monitor to determine if their license is about to expire (see this PR: https://github.com/cockroachdb/cockroach/pull/56463). Adding a section after "verify a license" and before "renew an expired license" to point users to the metric would help answer common questions we get from customers. This change was added in v20.2.


<!-- Sent from Reviewable.io -->

2021-02-04 17:29 UTC, gemma-shay reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9338)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @lnhsingh, and @piyush-singh)

___
*[v20.1/licensing.md, line 14 at r7](https://reviewable.io/reviews/cockroachdb/docs/9338#-MS8ncm89MszMiU0poaS:-MSi3dls59deOvzJVqig:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f1e914310f194e00a350b362d946a5d8adf4b68d/v20.1/licensing.md#L14)):*
<details><summary><i>Previously, piyush-singh (Piyush Singh) wrote…</i></summary><blockquote>

> ```
> After version 19.1
> ```
Perhaps "Starting with 19.2"
</blockquote></details>

Done.
___
*[v20.1/licensing.md, line 76 at r8](https://reviewable.io/reviews/cockroachdb/docs/9338#-MSYeSnJ8II0KGrOBM21:-MSi3wlo8yTV4Vd2WmNX:b-xfhdet) ([raw file](https://github.com/cockroachdb/docs/blob/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v20.1/licensing.md#L76)):*
<details><summary><i>Previously, piyush-singh (Piyush Singh) wrote…</i></summary><blockquote>

It may be worth calling out the 30 day free trial of CockroachCloud as it includes enterprise functionality. Will defer to you and perhaps @lnhsingh on whether this is the best place to include that. This would apply across versions.
</blockquote></details>

Included the trial as an option for obtaining a license instead of a callout as there were already 2 callouts below and 2 above, so it was looking a little crowded.
___
*[v20.2/licensing.md, line 109 at r8](https://reviewable.io/reviews/cockroachdb/docs/9338#-MSYmA1OA6kl5L8eB5r9:-MSi4KjeBgY4EDOgVH9i:b-7rl0jq) ([raw file](https://github.com/cockroachdb/docs/blob/c30f7f9f201c0bfd5ca4e544e432fdc452131609/v20.2/licensing.md#L109)):*
<details><summary><i>Previously, piyush-singh (Piyush Singh) wrote…</i></summary><blockquote>

I think it would make sense to add a section here that highlights monitoring for license expiry. We now have a time series metric that users can monitor to determine if their license is about to expire (see this PR: https://github.com/cockroachdb/cockroach/pull/56463). Adding a section after "verify a license" and before "renew an expired license" to point users to the metric would help answer common questions we get from customers. This change was added in v20.2.
</blockquote></details>

done!


<!-- Sent from Reviewable.io -->

2021-02-04 17:33 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/

Edited pages:
- [releases/v20.1.0-beta.3.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/releases/v20.1.0-beta.3.html)
- [releases/v20.1.0.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/releases/v20.1.0.html)
- [v20.1/cockroach-version.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/v20.1/cockroach-version.html)
- [v20.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/v20.1/enterprise-licensing.html)
- [v20.1/frequently-asked-questions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/v20.1/frequently-asked-questions.html)
- [v20.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/v20.1/gssapi_authentication.html)
- [v20.1/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/v20.1/index.html)
- [v20.1/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/v20.1/licensing.html)
- [v20.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/v20.1/partitioning.html)
- [v20.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/v20.1/restore.html)
- [v20.2/cockroach-version.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/v20.2/cockroach-version.html)
- [v20.2/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/v20.2/enterprise-licensing.html)
- [v20.2/frequently-asked-questions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/v20.2/frequently-asked-questions.html)
- [v20.2/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/v20.2/gssapi_authentication.html)
- [v20.2/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/v20.2/index.html)
- [v20.2/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/v20.2/licensing.html)
- [v20.2/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/v20.2/partitioning.html)
- [v20.2/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/v20.2/restore.html)
- [v21.1/cockroach-version.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/v21.1/cockroach-version.html)
- [v21.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/v21.1/enterprise-licensing.html)
- [v21.1/frequently-asked-questions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/v21.1/frequently-asked-questions.html)
- [v21.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/v21.1/gssapi_authentication.html)
- [v21.1/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/v21.1/index.html)
- [v21.1/licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/v21.1/licensing.html)
- [v21.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/v21.1/partitioning.html)
- [v21.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/49481cdffce5412fe72ee7711152cf0e8d88bac6/v21.1/restore.html)

2021-02-11 22:39 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/186f571bf0598682bdc033b5b183ce8e94a87d8c/

Edited pages:
- [v20.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/186f571bf0598682bdc033b5b183ce8e94a87d8c/v20.1/enterprise-licensing.html)
- [v20.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/186f571bf0598682bdc033b5b183ce8e94a87d8c/v20.1/gssapi_authentication.html)
- [v20.1/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/186f571bf0598682bdc033b5b183ce8e94a87d8c/v20.1/index.html)
- [v20.1/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/186f571bf0598682bdc033b5b183ce8e94a87d8c/v20.1/licensing-faqs.html)
- [v20.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/186f571bf0598682bdc033b5b183ce8e94a87d8c/v20.1/partitioning.html)
- [v20.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/186f571bf0598682bdc033b5b183ce8e94a87d8c/v20.1/restore.html)
- [v20.2/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/186f571bf0598682bdc033b5b183ce8e94a87d8c/v20.2/enterprise-licensing.html)
- [v20.2/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/186f571bf0598682bdc033b5b183ce8e94a87d8c/v20.2/gssapi_authentication.html)
- [v20.2/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/186f571bf0598682bdc033b5b183ce8e94a87d8c/v20.2/index.html)
- [v20.2/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/186f571bf0598682bdc033b5b183ce8e94a87d8c/v20.2/licensing-faqs.html)
- [v20.2/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/186f571bf0598682bdc033b5b183ce8e94a87d8c/v20.2/partitioning.html)
- [v20.2/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/186f571bf0598682bdc033b5b183ce8e94a87d8c/v20.2/restore.html)
- [v21.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/186f571bf0598682bdc033b5b183ce8e94a87d8c/v21.1/enterprise-licensing.html)
- [v21.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/186f571bf0598682bdc033b5b183ce8e94a87d8c/v21.1/gssapi_authentication.html)
- [v21.1/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/186f571bf0598682bdc033b5b183ce8e94a87d8c/v21.1/index.html)
- [v21.1/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/186f571bf0598682bdc033b5b183ce8e94a87d8c/v21.1/licensing-faqs.html)
- [v21.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/186f571bf0598682bdc033b5b183ce8e94a87d8c/v21.1/partitioning.html)
- [v21.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/186f571bf0598682bdc033b5b183ce8e94a87d8c/v21.1/restore.html)

2021-02-17 19:22 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a2c96480162d3107bfd9dcd9d3d31532353a77d6/

Edited pages:
- [v20.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a2c96480162d3107bfd9dcd9d3d31532353a77d6/v20.1/enterprise-licensing.html)
- [v20.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a2c96480162d3107bfd9dcd9d3d31532353a77d6/v20.1/gssapi_authentication.html)
- [v20.1/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a2c96480162d3107bfd9dcd9d3d31532353a77d6/v20.1/index.html)
- [v20.1/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a2c96480162d3107bfd9dcd9d3d31532353a77d6/v20.1/licensing-faqs.html)
- [v20.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a2c96480162d3107bfd9dcd9d3d31532353a77d6/v20.1/partitioning.html)
- [v20.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a2c96480162d3107bfd9dcd9d3d31532353a77d6/v20.1/restore.html)
- [v20.2/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a2c96480162d3107bfd9dcd9d3d31532353a77d6/v20.2/enterprise-licensing.html)
- [v20.2/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a2c96480162d3107bfd9dcd9d3d31532353a77d6/v20.2/gssapi_authentication.html)
- [v20.2/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a2c96480162d3107bfd9dcd9d3d31532353a77d6/v20.2/index.html)
- [v20.2/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a2c96480162d3107bfd9dcd9d3d31532353a77d6/v20.2/licensing-faqs.html)
- [v20.2/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a2c96480162d3107bfd9dcd9d3d31532353a77d6/v20.2/partitioning.html)
- [v20.2/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a2c96480162d3107bfd9dcd9d3d31532353a77d6/v20.2/restore.html)
- [v21.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a2c96480162d3107bfd9dcd9d3d31532353a77d6/v21.1/enterprise-licensing.html)
- [v21.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a2c96480162d3107bfd9dcd9d3d31532353a77d6/v21.1/gssapi_authentication.html)
- [v21.1/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a2c96480162d3107bfd9dcd9d3d31532353a77d6/v21.1/index.html)
- [v21.1/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a2c96480162d3107bfd9dcd9d3d31532353a77d6/v21.1/licensing-faqs.html)
- [v21.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a2c96480162d3107bfd9dcd9d3d31532353a77d6/v21.1/partitioning.html)
- [v21.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a2c96480162d3107bfd9dcd9d3d31532353a77d6/v21.1/restore.html)

2021-02-18 20:24 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ad435434488b2d9067ae13b89c7a264936f7053e/

Edited pages:
- [v20.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ad435434488b2d9067ae13b89c7a264936f7053e/v20.1/enterprise-licensing.html)
- [v20.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ad435434488b2d9067ae13b89c7a264936f7053e/v20.1/gssapi_authentication.html)
- [v20.1/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ad435434488b2d9067ae13b89c7a264936f7053e/v20.1/index.html)
- [v20.1/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ad435434488b2d9067ae13b89c7a264936f7053e/v20.1/licensing-faqs.html)
- [v20.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ad435434488b2d9067ae13b89c7a264936f7053e/v20.1/partitioning.html)
- [v20.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ad435434488b2d9067ae13b89c7a264936f7053e/v20.1/restore.html)
- [v20.2/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ad435434488b2d9067ae13b89c7a264936f7053e/v20.2/enterprise-licensing.html)
- [v20.2/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ad435434488b2d9067ae13b89c7a264936f7053e/v20.2/gssapi_authentication.html)
- [v20.2/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ad435434488b2d9067ae13b89c7a264936f7053e/v20.2/index.html)
- [v20.2/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ad435434488b2d9067ae13b89c7a264936f7053e/v20.2/licensing-faqs.html)
- [v20.2/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ad435434488b2d9067ae13b89c7a264936f7053e/v20.2/partitioning.html)
- [v20.2/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ad435434488b2d9067ae13b89c7a264936f7053e/v20.2/restore.html)
- [v21.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ad435434488b2d9067ae13b89c7a264936f7053e/v21.1/enterprise-licensing.html)
- [v21.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ad435434488b2d9067ae13b89c7a264936f7053e/v21.1/gssapi_authentication.html)
- [v21.1/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ad435434488b2d9067ae13b89c7a264936f7053e/v21.1/index.html)
- [v21.1/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ad435434488b2d9067ae13b89c7a264936f7053e/v21.1/licensing-faqs.html)
- [v21.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ad435434488b2d9067ae13b89c7a264936f7053e/v21.1/partitioning.html)
- [v21.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ad435434488b2d9067ae13b89c7a264936f7053e/v21.1/restore.html)

2021-02-23 17:41 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8066446163e11295124f4d4ed79c462e11296dea/

Edited pages:
- [v20.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8066446163e11295124f4d4ed79c462e11296dea/v20.1/enterprise-licensing.html)
- [v20.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8066446163e11295124f4d4ed79c462e11296dea/v20.1/gssapi_authentication.html)
- [v20.1/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8066446163e11295124f4d4ed79c462e11296dea/v20.1/index.html)
- [v20.1/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8066446163e11295124f4d4ed79c462e11296dea/v20.1/licensing-faqs.html)
- [v20.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8066446163e11295124f4d4ed79c462e11296dea/v20.1/partitioning.html)
- [v20.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8066446163e11295124f4d4ed79c462e11296dea/v20.1/restore.html)
- [v20.2/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8066446163e11295124f4d4ed79c462e11296dea/v20.2/enterprise-licensing.html)
- [v20.2/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8066446163e11295124f4d4ed79c462e11296dea/v20.2/gssapi_authentication.html)
- [v20.2/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8066446163e11295124f4d4ed79c462e11296dea/v20.2/index.html)
- [v20.2/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8066446163e11295124f4d4ed79c462e11296dea/v20.2/licensing-faqs.html)
- [v20.2/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8066446163e11295124f4d4ed79c462e11296dea/v20.2/partitioning.html)
- [v20.2/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8066446163e11295124f4d4ed79c462e11296dea/v20.2/restore.html)
- [v21.1/enterprise-licensing.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8066446163e11295124f4d4ed79c462e11296dea/v21.1/enterprise-licensing.html)
- [v21.1/gssapi_authentication.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8066446163e11295124f4d4ed79c462e11296dea/v21.1/gssapi_authentication.html)
- [v21.1/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8066446163e11295124f4d4ed79c462e11296dea/v21.1/index.html)
- [v21.1/licensing-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8066446163e11295124f4d4ed79c462e11296dea/v21.1/licensing-faqs.html)
- [v21.1/partitioning.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8066446163e11295124f4d4ed79c462e11296dea/v21.1/partitioning.html)
- [v21.1/restore.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8066446163e11295124f4d4ed79c462e11296dea/v21.1/restore.html)

2021-02-23 20:42 UTC, merged