Cc account
cockroachdb/docs pull request #9469
Opened 2021-01-22 19:38 UTC by lnhsingh

2021-01-22 19:38 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/9469)
<!-- Reviewable:end -->

2021-01-22 19:42 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4ce0e16d4e560131097927000df9ce679270682a/

Edited pages:
- [cockroachcloud/connect-to-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4ce0e16d4e560131097927000df9ce679270682a/cockroachcloud/connect-to-your-cluster.html)
- [cockroachcloud/create-an-account.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4ce0e16d4e560131097927000df9ce679270682a/cockroachcloud/create-an-account.html)
- [cockroachcloud/user-authorization.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4ce0e16d4e560131097927000df9ce679270682a/cockroachcloud/user-authorization.html)

2021-01-22 19:45 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/572acca48312a4449c42e5d21fb16967d09ceb88/

Edited pages:
- [cockroachcloud/connect-to-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/572acca48312a4449c42e5d21fb16967d09ceb88/cockroachcloud/connect-to-your-cluster.html)
- [cockroachcloud/create-an-account.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/572acca48312a4449c42e5d21fb16967d09ceb88/cockroachcloud/create-an-account.html)
- [cockroachcloud/user-authorization.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/572acca48312a4449c42e5d21fb16967d09ceb88/cockroachcloud/user-authorization.html)

2021-01-25 15:06 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4e070066e0f999600681175d76c62b38b10034d9/

Edited pages:
- [cockroachcloud/connect-to-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4e070066e0f999600681175d76c62b38b10034d9/cockroachcloud/connect-to-your-cluster.html)
- [cockroachcloud/create-an-account.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4e070066e0f999600681175d76c62b38b10034d9/cockroachcloud/create-an-account.html)
- [cockroachcloud/user-authorization.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4e070066e0f999600681175d76c62b38b10034d9/cockroachcloud/user-authorization.html)

2021-01-26 23:20 UTC, lnhsingh commented
@emily-horing friendly ping to review - lmk if someone else should review instead. I'd like to get this to docs review by tomorrow so I have time for updates if needed. Thanks!

2021-01-26 23:23 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/067a1de2d0da62d92b1155bdce71ae59229dc74e/

Edited pages:
- [cockroachcloud/connect-to-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/connect-to-your-cluster.html)
- [cockroachcloud/create-an-account.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/create-an-account.html)
- [cockroachcloud/user-authorization.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/user-authorization.html)

2021-01-27 04:22 UTC, emily-horing requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9469)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

___
*[cockroachcloud/connect-to-your-cluster.md, line 9 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS11I5HAa1FyKkeqlUx:-MS11I5HAa1FyKkeqlUy:bysl3bb) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/connect-to-your-cluster.md#L9)):*
> ```Markdown
> ---
> 
> This page shows you how to connect to your CockroachCloud cluster.
> ```

I think we should have a note here to skip to step 3 if you're using a CC free beta cluster
___
*[cockroachcloud/connect-to-your-cluster.md, line 17 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS11UiD1yiE_2AppASo:-MS11UiD1yiE_2AppASp:b-wuhs0m) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/connect-to-your-cluster.md#L17)):*
> ```Markdown
> - In a development environment, you need to authorize your application server’s network and your local machine’s network. If you change your location, you need to authorize the new location’s network, or else the connection from that network will be rejected.
> - In a production environment, you need to authorize your application server’s network.
> - If you have a GCP cluster, you can set up and authorize [a VPC peered network](create-your-cluster.html#step-7-enable-vpc-peering-optional).
> ```

should we note that you can contact support for AWS private link? Or are we purposefully holding off until that's GA?
___
*[cockroachcloud/connect-to-your-cluster.md, line 46 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS11tdpCY7lm7emnAHw:-MS11tdpCY7lm7emnAHx:bn9stl3) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/connect-to-your-cluster.md#L46)):*
> ```Markdown
>      {{site.data.alerts.end}}
> 
>      To add a range of IP addresses, use the CIDR (Classless Inter-Domain Routing) notation. The CIDR notation is constructed from an IP address (e.g., `192.168.15.161`), a slash (`/`), and a number (e.g., `32`). The number is the count of leading 1-bits in the network identifier. In the example above, the IP address is 32-bits and the number is `32`, so the full IP address is also the network identifier. For more information, see Digital Ocean's [Understanding IP Addresses, Subnets, and CIDR Notation for Networking](https://www.digitalocean.com/community/tutorials/understanding-ip-addresses-subnets-and-cidr-notation-for-networking#cidr-notation).
> ```

I thought all the allowlisted IPs needed to use CIDR notation. Is that not the case for your local/app network?
___
*[cockroachcloud/connect-to-your-cluster.md, line 48 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS12DacDdammrPPu0Vx:-MS12DacDdammrPPu0Vy:b-4ip773) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/connect-to-your-cluster.md#L48)):*
> ```Markdown
>      To add a range of IP addresses, use the CIDR (Classless Inter-Domain Routing) notation. The CIDR notation is constructed from an IP address (e.g., `192.168.15.161`), a slash (`/`), and a number (e.g., `32`). The number is the count of leading 1-bits in the network identifier. In the example above, the IP address is 32-bits and the number is `32`, so the full IP address is also the network identifier. For more information, see Digital Ocean's [Understanding IP Addresses, Subnets, and CIDR Notation for Networking](https://www.digitalocean.com/community/tutorials/understanding-ip-addresses-subnets-and-cidr-notation-for-networking#cidr-notation).
> 
> 6. Select whether the network can connect to the cluster's **UI**, **SQL** client, or both.
> ```

We should update to use the same language in the UI. I think we say "DB Console" and "SQL access" or something like that now
___
*[cockroachcloud/connect-to-your-cluster.md, line 100 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS12uoP9HOh4XewUjhM:-MS12uoP9HOh4XewUjhN:b-tl615b) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/connect-to-your-cluster.md#L100)):*
> ```Markdown
>     To connect to your cluster using the [in-built SQL client](#use-the-cockroachdb-sql-client), use the command displayed on the **CockroachDB Client** tab.
> 
>     To connect to your cluster [using a Postgres ORM or driver](#use-a-postgres-driver-or-orm), use either the **Connection String** or the **Parameters** as required by your ORM or driver.
> ```

I think technically we labeled them "Your app" and "your tool" but I think we're actually going to change it back to "connection string" and "parameters" after some initial feedback. But FYI that's not what it says in the UI as of today
___
*[cockroachcloud/connect-to-your-cluster.md, line 110 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS13BZz2cAeFTFvhrIX:-MS13BZz2cAeFTFvhrIY:b-4mwgp0) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/connect-to-your-cluster.md#L110)):*
> ```Markdown
> 9. Create a `certs` directory and move the `ca.crt` file to the `certs` directory. The `ca.crt` file must be available on every machine from which you want to connect to the cluster and must be referenced in the connection string.
> 
>     You will need to replace the `<certs_dir>` placeholders with the path to your certs directory in the CockroachDB client command or the connection string.
> ```

<certs-dir> was updated to <your-certs-directory>
___
*[cockroachcloud/connect-to-your-cluster.md, line 120 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS13SW0A_x60r78Fln6:-MS13SW0A_x60r78Fln7:b-2edhnr) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/connect-to-your-cluster.md#L120)):*
> ```Markdown
> On the machine where you want to run the CockroachDB SQL client:
> 
> 1. [Download the CockroachDB binary](../stable/install-cockroachdb.html):
> ```

We let you download this directly from the connect modal. Maybe worth noting here?
___
*[cockroachcloud/create-an-account.md, line 25 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS0FFUxBxe8SSJVN7nq:-MS0FFUxBxe8SSJVN7nr:bil8vba) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/create-an-account.md#L25)):*
> ```Markdown
> {{site.data.alerts.end}}
> 
> If you do not have access yet, you can start your first cluster using a 30-day free trial.
> ```

I don't think this is meant to be here, maybe copied from another page?
___
*[cockroachcloud/create-an-account.md, line 29 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS0FMZI7MwRBUx8S4D7:-MS0FMZI7MwRBUx8S4D8:b-19jq12) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/create-an-account.md#L29)):*
> ```Markdown
> 1. Enter your GitHub **Username or email address** associated with your account.
> 1. Enter your GitHub **Password**
> 1. Click **Sign in**
> ```

These are all numbered 1. They also don't show up as a list like I would expect in the preview
___
*[cockroachcloud/create-an-account.md, line 32 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS0Fcxi9aWMtB5R45aH:-MS0Fcxi9aWMtB5R45aI:b-wjji69) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/create-an-account.md#L32)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> GitHub should verify your identity using [GitHub 2FA](https://docs.github.com/en/github/authenticating-to-github/about-two-factor-authentication).
> ```

I don't think 2fa is required to use github? @laurenbarker maybe you can correct me 
___
*[cockroachcloud/create-an-account.md, line 43 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS0xG1f2P [...]

2021-01-27 04:22 UTC, emily-horing reviewed
Sorry for the delay! Added comments for review

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9469#-:-MS13yMX26wbN7oSZJQ_:bie21uv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)



<!-- Sent from Reviewable.io -->

2021-01-27 15:52 UTC, lnhsingh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9469)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing, @gemma-shay, @laurenbarker, and @lnhsingh)

___
*[cockroachcloud/connect-to-your-cluster.md, line 9 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS11I5HAa1FyKkeqlUx:-MS3KPkRE5CpCv1ArINc:b-2i3qjb) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/connect-to-your-cluster.md#L9)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

I think we should have a note here to skip to step 3 if you're using a CC free beta cluster
</blockquote></details>

This is being addressed in a separate PR - https://github.com/cockroachdb/docs/pull/9481
___
*[cockroachcloud/connect-to-your-cluster.md, line 17 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS11UiD1yiE_2AppASo:-MS3KVAR-_BPIiv6tYLX:b1hoevx) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/connect-to-your-cluster.md#L17)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

should we note that you can contact support for AWS private link? Or are we purposefully holding off until that's GA?
</blockquote></details>

@gemma-shay is working on PrivateLink docs and won't publish until PrivateLink is in GA. Gemma, heads up that you might need to rebase with master once all of the Free tier docs are merged so you are working off of the latest version of the docs. We can sync once this happens.
___
*[cockroachcloud/connect-to-your-cluster.md, line 46 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS11tdpCY7lm7emnAHw:-MS3NXAHAt3x_hY1Uexf:bw8ej13) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/connect-to-your-cluster.md#L46)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

I thought all the allowlisted IPs needed to use CIDR notation. Is that not the case for your local/app network?
</blockquote></details>

Moved this question to #9481 and will address there.
___
*[cockroachcloud/connect-to-your-cluster.md, line 48 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS12DacDdammrPPu0Vx:-MS3Nh-CCGSXNTjiFwny:bu0omlt) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/connect-to-your-cluster.md#L48)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

We should update to use the same language in the UI. I think we say "DB Console" and "SQL access" or something like that now
</blockquote></details>

Will address in #9481
___
*[cockroachcloud/connect-to-your-cluster.md, line 100 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS12uoP9HOh4XewUjhM:-MS3Oc3d-MeBSxEDGIbn:bu0omlt) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/connect-to-your-cluster.md#L100)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

I think technically we labeled them "Your app" and "your tool" but I think we're actually going to change it back to "connection string" and "parameters" after some initial feedback. But FYI that's not what it says in the UI as of today
</blockquote></details>

Will address in #9481
___
*[cockroachcloud/connect-to-your-cluster.md, line 110 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS13BZz2cAeFTFvhrIX:-MS3P8Ze6jp1mlaV6wuL:b4pjogw) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/connect-to-your-cluster.md#L110)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

<certs-dir> was updated to <your-certs-directory>
</blockquote></details>

Can you elaborate here?
___
*[cockroachcloud/connect-to-your-cluster.md, line 120 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS13SW0A_x60r78Fln6:-MS3PO2601TzjNXK9d8T:bu0omlt) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/connect-to-your-cluster.md#L120)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

We let you download this directly from the connect modal. Maybe worth noting here?
</blockquote></details>

Will address in #9481
___
*[cockroachcloud/create-an-account.md, line 25 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS0FFUxBxe8SSJVN7nq:-MS3Pmyf8L_iAVb_yafx:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/create-an-account.md#L25)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

I don't think this is meant to be here, maybe copied from another page?
</blockquote></details>

Done.
___
*[cockroachcloud/create-an-account.md, line 29 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS0FMZI7MwRBUx8S4D7:-MS3Q2x8BTRtGCKARxCO:b-o7jtzg) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/create-an-account.md#L29)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

These are all numbered 1. They also don't show up as a list like I would expect in the preview
</blockquote></details>

Done - This should be fixed by removing that lingering line that you pointed out above. The `1.` are intentional-- they are "smart" in that they auto-number when rendered.
___
*[cockroachcloud/create-an-account.md, line 32 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS0Fcxi9aWMtB5R45aH:-MS3QKh2AiVPSur__H1L:b-ivg27m) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/create-an-account.md#L32)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

I don't think 2fa is required to use github? @laurenbarker maybe you can correct me 
</blockquote></details>

It's not required but will happen if you have 2FA enabled. Maybe the wording here should be "GitHub will verify... if you have it enabled."
___
*[cockroachcloud/create-an-account.md, line 43 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS0xG1f2P2-CgVUf6zJ:-MS3QferAYxBqpXFYsji:b-p0cdld) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/create-an-account.md#L43)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

would be nice to add "you can edit this later" too.
</blockquote></details>

Done. Added a new "Edit your org name" section.
___
*[cockroachcloud/create-an-account.md, line 46 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS0xSotDHp7gcNvoAnd:-MS3VHIR5xiLl2PqZc1X:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/create-an-account.md#L46)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

Missing "go to your email and click the verification link". This is required to complete account creation
</blockquote></details>

Done.
___
*[cockroachcloud/create-an-account.md, line 62 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS0y-P5-j4vFxH2U0-V:-MS3Vapy4XIW4tkLHfTp:brpowi8) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/create-an-account.md#L62)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

Not sure why, but this line seems to have extra margin on top compared to the other list items. Same for the email version
</blockquote></details>

Thanks for pointing this out - I think it has to do with our CSS, so will note for later.
___
*[cockroachcloud/user-authorization.md, line 11 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS1-MU_AMtyibdEQ0r3:-MS3Vxcx64 [...]

2021-01-27 15:56 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1cbf1020a4c6318c4985d3a6d15323d32cc18654/

Edited pages:
- [cockroachcloud/connect-to-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1cbf1020a4c6318c4985d3a6d15323d32cc18654/cockroachcloud/connect-to-your-cluster.html)
- [cockroachcloud/create-an-account.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1cbf1020a4c6318c4985d3a6d15323d32cc18654/cockroachcloud/create-an-account.html)
- [cockroachcloud/user-authorization.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1cbf1020a4c6318c4985d3a6d15323d32cc18654/cockroachcloud/user-authorization.html)

2021-01-27 19:13 UTC, lnhsingh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9469)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing, @gemma-shay, and @laurenbarker)

___
*[cockroachcloud/create-an-account.md, line 117 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS0yS0r3dtgqbm0QhLw:-MS4FnlyB3_EBzydUJBK:b-yc4eb8) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/create-an-account.md#L117)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

If we are including directions to sign up with github I would expect us to also have instructions on how to switch between sign up methods. Unless you're expecting sign up to be available first? I could be wrong but I think they will be ready at the same time. @laurenbarker please correct me if I'm wrong here!
</blockquote></details>

Yep, makes sense. I was planning on adding that as a fast follow up (i.e., I didn't think that info was _necessary_ for the Tuesday release): https://github.com/cockroachdb/docs/issues/9468


<!-- Sent from Reviewable.io -->

2021-01-27 20:13 UTC, emily-horing approved these changes
Updated changes all <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9469#-:-MS4TbHa0nI4fZe0DEXV:bwdyk8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @emily-horing, @gemma-shay, @laurenbarker, @lnhsingh, and @rmloveland)

___
*[cockroachcloud/connect-to-your-cluster.md, line 110 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS13BZz2cAeFTFvhrIX:-MS4SuJAEtznPREDHA7g:b-6kapxa) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/connect-to-your-cluster.md#L110)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Can you elaborate here?
</blockquote></details>

Ah weird my comment got cut off. The modal says <your-certs-directory> , not <certs-dir> now
___
*[cockroachcloud/create-an-account.md, line 32 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS0Fcxi9aWMtB5R45aH:-MS4T6jZ9OGc4KfrACuw:b290cxk) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/create-an-account.md#L32)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

It's not required but will happen if you have 2FA enabled. Maybe the wording here should be "GitHub will verify... if you have it enabled."
</blockquote></details>

Yep that makes sense to me
___
*[cockroachcloud/create-an-account.md, line 117 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS0yS0r3dtgqbm0QhLw:-MS4TBk80RJEsR8RXNDv:b-pcr4zi) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/create-an-account.md#L117)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Yep, makes sense. I was planning on adding that as a fast follow up (i.e., I didn't think that info was _necessary_ for the Tuesday release): https://github.com/cockroachdb/docs/issues/9468
</blockquote></details>

+1 probably not necessary. I don't think GH sign up will even be really available publically for Tuesday, might be a week after. I'm fine having preemptive docs for it though
___
*[cockroachcloud/user-authorization.md, line 160 at r1](https://reviewable.io/reviews/cockroachdb/docs/9469#-MS1-y-YBGqSmZhON-EM:-MS4TUrW5YGxio-v-ntI:bbrsb2q) ([raw file](https://github.com/cockroachdb/docs/blob/067a1de2d0da62d92b1155bdce71ae59229dc74e/cockroachcloud/user-authorization.md#L160)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

I think this is incorrect as is - it should say "All of of a role's privileges must be revoked before the _role_ can be dropped"
</blockquote></details>

Yeah that makes more sense!


<!-- Sent from Reviewable.io -->

2021-01-29 16:42 UTC, rmloveland approved these changes
LGTM with some random comments

2021-01-29 16:42 UTC, rmloveland commented on _includes/cockroachcloud/create-a-sql-user.md
> +    The **Add User** modal displays.
I think "dialog" is a more common term than "modal" - AIUI "modal" is an adjective that we are noun-ifying - it refers to a "modal dialog".

My (non-binding) opinion is that we should replace "modal" with "dialog" everywhere

2021-01-29 16:42 UTC, rmloveland commented on _includes/cockroachcloud/create-a-sql-user.md
> +    Password must be at least 12 characters long.
This feels like something we should leave to UI to validate (also, it will probably change)

2021-01-29 16:42 UTC, rmloveland commented on cockroachcloud/user-authorization.md
> +Once you have [connected to the cluster's SQL client](connect-to-your-cluster.html#use-the-cockroachdb-sql-client), you can grant user privileges.
This could say "[connected to the cluster]()" without losing anything IMO.

2021-01-29 16:42 UTC, rmloveland commented on cockroachcloud/user-authorization.md
> +Once you have [connected to the cluster's SQL client](connect-to-your-cluster.html#use-the-cockroachdb-sql-client), you can grant user privileges.
(Same for other uses)

2021-01-29 23:19 UTC, lnhsingh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9469)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @emily-horing, @gemma-shay, @laurenbarker, @lnhsingh, and @rmloveland)

___
*[_includes/cockroachcloud/create-a-sql-user.md, line 9 at r2](https://reviewable.io/reviews/cockroachdb/docs/9469#-MRfamwH_X8vhCnLBxxZ-r2-9:-MSFQTO6CkMr_geRX6PN:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/1cbf1020a4c6318c4985d3a6d15323d32cc18654/_includes/cockroachcloud/create-a-sql-user.md#L9)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

I think "dialog" is a more common term than "modal" - AIUI "modal" is an adjective that we are noun-ifying - it refers to a "modal dialog".

My (non-binding) opinion is that we should replace "modal" with "dialog" everywhere
</blockquote></details>

Done.
___
*[_includes/cockroachcloud/create-a-sql-user.md, line 13 at r2](https://reviewable.io/reviews/cockroachdb/docs/9469#-MRfamwH_X8vhCnLBxxZ-r2-13:-MSFQkW-D8tP-JEcfqtC:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/1cbf1020a4c6318c4985d3a6d15323d32cc18654/_includes/cockroachcloud/create-a-sql-user.md#L13)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

This feels like something we should leave to UI to validate (also, it will probably change)
</blockquote></details>

Done.
___
*[cockroachcloud/user-authorization.md, line 43 at r2](https://reviewable.io/reviews/cockroachdb/docs/9469#-MRfamwH_X8vhCnLBxxc-r2-43:-MSFRWfZ20y2FOY5p4el:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/1cbf1020a4c6318c4985d3a6d15323d32cc18654/cockroachcloud/user-authorization.md#L43)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

(Same for other uses)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-29 23:26 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d34ad468cefd2a314dc0e4718af0d506bbcd47d7/

Edited pages:
- [cockroachcloud/connect-to-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d34ad468cefd2a314dc0e4718af0d506bbcd47d7/cockroachcloud/connect-to-your-cluster.html)
- [cockroachcloud/create-an-account.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d34ad468cefd2a314dc0e4718af0d506bbcd47d7/cockroachcloud/create-an-account.html)
- [cockroachcloud/deploy-a-python-to-do-app-with-flask-kubernetes-and-cockroachcloud.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d34ad468cefd2a314dc0e4718af0d506bbcd47d7/cockroachcloud/deploy-a-python-to-do-app-with-flask-kubernetes-and-cockroachcloud.html)
- [cockroachcloud/quickstart-trial-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d34ad468cefd2a314dc0e4718af0d506bbcd47d7/cockroachcloud/quickstart-trial-cluster.html)
- [cockroachcloud/quickstart.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d34ad468cefd2a314dc0e4718af0d506bbcd47d7/cockroachcloud/quickstart.html)
- [cockroachcloud/user-authorization.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d34ad468cefd2a314dc0e4718af0d506bbcd47d7/cockroachcloud/user-authorization.html)
- [releases/v20.1.0-beta.3.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d34ad468cefd2a314dc0e4718af0d506bbcd47d7/releases/v20.1.0-beta.3.html)
- [v20.2/build-a-go-app-with-cockroachdb-gorm.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d34ad468cefd2a314dc0e4718af0d506bbcd47d7/v20.2/build-a-go-app-with-cockroachdb-gorm.html)
- [v20.2/build-a-go-app-with-cockroachdb-pq.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d34ad468cefd2a314dc0e4718af0d506bbcd47d7/v20.2/build-a-go-app-with-cockroachdb-pq.html)
- [v20.2/build-a-go-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d34ad468cefd2a314dc0e4718af0d506bbcd47d7/v20.2/build-a-go-app-with-cockroachdb.html)
- [v20.2/build-a-python-app-with-cockroachdb-django.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d34ad468cefd2a314dc0e4718af0d506bbcd47d7/v20.2/build-a-python-app-with-cockroachdb-django.html)
- [v20.2/build-a-python-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d34ad468cefd2a314dc0e4718af0d506bbcd47d7/v20.2/build-a-python-app-with-cockroachdb.html)
- [v20.2/sso.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d34ad468cefd2a314dc0e4718af0d506bbcd47d7/v20.2/sso.html)
- [v21.1/sso.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d34ad468cefd2a314dc0e4718af0d506bbcd47d7/v21.1/sso.html)

2021-01-29 23:35 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c355d5928cf50f584c28bc23130c03d96190fb1e/

Edited pages:
- [cockroachcloud/connect-to-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c355d5928cf50f584c28bc23130c03d96190fb1e/cockroachcloud/connect-to-your-cluster.html)
- [cockroachcloud/create-an-account.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c355d5928cf50f584c28bc23130c03d96190fb1e/cockroachcloud/create-an-account.html)
- [cockroachcloud/deploy-a-python-to-do-app-with-flask-kubernetes-and-cockroachcloud.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c355d5928cf50f584c28bc23130c03d96190fb1e/cockroachcloud/deploy-a-python-to-do-app-with-flask-kubernetes-and-cockroachcloud.html)
- [cockroachcloud/quickstart-trial-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c355d5928cf50f584c28bc23130c03d96190fb1e/cockroachcloud/quickstart-trial-cluster.html)
- [cockroachcloud/quickstart.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c355d5928cf50f584c28bc23130c03d96190fb1e/cockroachcloud/quickstart.html)
- [cockroachcloud/user-authorization.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c355d5928cf50f584c28bc23130c03d96190fb1e/cockroachcloud/user-authorization.html)
- [releases/v20.1.0-beta.3.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c355d5928cf50f584c28bc23130c03d96190fb1e/releases/v20.1.0-beta.3.html)
- [v20.2/build-a-go-app-with-cockroachdb-gorm.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c355d5928cf50f584c28bc23130c03d96190fb1e/v20.2/build-a-go-app-with-cockroachdb-gorm.html)
- [v20.2/build-a-go-app-with-cockroachdb-pq.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c355d5928cf50f584c28bc23130c03d96190fb1e/v20.2/build-a-go-app-with-cockroachdb-pq.html)
- [v20.2/build-a-go-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c355d5928cf50f584c28bc23130c03d96190fb1e/v20.2/build-a-go-app-with-cockroachdb.html)
- [v20.2/build-a-python-app-with-cockroachdb-django.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c355d5928cf50f584c28bc23130c03d96190fb1e/v20.2/build-a-python-app-with-cockroachdb-django.html)
- [v20.2/build-a-python-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c355d5928cf50f584c28bc23130c03d96190fb1e/v20.2/build-a-python-app-with-cockroachdb.html)
- [v20.2/sso.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c355d5928cf50f584c28bc23130c03d96190fb1e/v20.2/sso.html)
- [v21.1/sso.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c355d5928cf50f584c28bc23130c03d96190fb1e/v21.1/sso.html)

2021-01-29 23:44 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d9861083e545bea804eb396dd1fbb4827c418759/

Edited pages:
- [cockroachcloud/connect-to-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d9861083e545bea804eb396dd1fbb4827c418759/cockroachcloud/connect-to-your-cluster.html)
- [cockroachcloud/create-an-account.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d9861083e545bea804eb396dd1fbb4827c418759/cockroachcloud/create-an-account.html)
- [cockroachcloud/deploy-a-python-to-do-app-with-flask-kubernetes-and-cockroachcloud.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d9861083e545bea804eb396dd1fbb4827c418759/cockroachcloud/deploy-a-python-to-do-app-with-flask-kubernetes-and-cockroachcloud.html)
- [cockroachcloud/quickstart-trial-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d9861083e545bea804eb396dd1fbb4827c418759/cockroachcloud/quickstart-trial-cluster.html)
- [cockroachcloud/quickstart.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d9861083e545bea804eb396dd1fbb4827c418759/cockroachcloud/quickstart.html)
- [cockroachcloud/user-authorization.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d9861083e545bea804eb396dd1fbb4827c418759/cockroachcloud/user-authorization.html)
- [releases/v20.1.0-beta.3.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d9861083e545bea804eb396dd1fbb4827c418759/releases/v20.1.0-beta.3.html)
- [v20.2/build-a-go-app-with-cockroachdb-gorm.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d9861083e545bea804eb396dd1fbb4827c418759/v20.2/build-a-go-app-with-cockroachdb-gorm.html)
- [v20.2/build-a-go-app-with-cockroachdb-pq.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d9861083e545bea804eb396dd1fbb4827c418759/v20.2/build-a-go-app-with-cockroachdb-pq.html)
- [v20.2/build-a-go-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d9861083e545bea804eb396dd1fbb4827c418759/v20.2/build-a-go-app-with-cockroachdb.html)
- [v20.2/build-a-python-app-with-cockroachdb-django.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d9861083e545bea804eb396dd1fbb4827c418759/v20.2/build-a-python-app-with-cockroachdb-django.html)
- [v20.2/build-a-python-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d9861083e545bea804eb396dd1fbb4827c418759/v20.2/build-a-python-app-with-cockroachdb.html)
- [v20.2/sso.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d9861083e545bea804eb396dd1fbb4827c418759/v20.2/sso.html)
- [v21.1/sso.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d9861083e545bea804eb396dd1fbb4827c418759/v21.1/sso.html)

2021-01-29 23:49 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/dea6c371f7b7100dc12c0e40dec30fb33fec3ff8/

Edited pages:
- [cockroachcloud/connect-to-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/dea6c371f7b7100dc12c0e40dec30fb33fec3ff8/cockroachcloud/connect-to-your-cluster.html)
- [cockroachcloud/create-an-account.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/dea6c371f7b7100dc12c0e40dec30fb33fec3ff8/cockroachcloud/create-an-account.html)
- [cockroachcloud/deploy-a-python-to-do-app-with-flask-kubernetes-and-cockroachcloud.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/dea6c371f7b7100dc12c0e40dec30fb33fec3ff8/cockroachcloud/deploy-a-python-to-do-app-with-flask-kubernetes-and-cockroachcloud.html)
- [cockroachcloud/quickstart-trial-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/dea6c371f7b7100dc12c0e40dec30fb33fec3ff8/cockroachcloud/quickstart-trial-cluster.html)
- [cockroachcloud/quickstart.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/dea6c371f7b7100dc12c0e40dec30fb33fec3ff8/cockroachcloud/quickstart.html)
- [cockroachcloud/user-authorization.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/dea6c371f7b7100dc12c0e40dec30fb33fec3ff8/cockroachcloud/user-authorization.html)
- [releases/v20.1.0-beta.3.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/dea6c371f7b7100dc12c0e40dec30fb33fec3ff8/releases/v20.1.0-beta.3.html)
- [v20.2/build-a-go-app-with-cockroachdb-gorm.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/dea6c371f7b7100dc12c0e40dec30fb33fec3ff8/v20.2/build-a-go-app-with-cockroachdb-gorm.html)
- [v20.2/build-a-go-app-with-cockroachdb-pq.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/dea6c371f7b7100dc12c0e40dec30fb33fec3ff8/v20.2/build-a-go-app-with-cockroachdb-pq.html)
- [v20.2/build-a-go-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/dea6c371f7b7100dc12c0e40dec30fb33fec3ff8/v20.2/build-a-go-app-with-cockroachdb.html)
- [v20.2/build-a-python-app-with-cockroachdb-django.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/dea6c371f7b7100dc12c0e40dec30fb33fec3ff8/v20.2/build-a-python-app-with-cockroachdb-django.html)
- [v20.2/build-a-python-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/dea6c371f7b7100dc12c0e40dec30fb33fec3ff8/v20.2/build-a-python-app-with-cockroachdb.html)
- [v20.2/sso.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/dea6c371f7b7100dc12c0e40dec30fb33fec3ff8/v20.2/sso.html)
- [v21.1/sso.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/dea6c371f7b7100dc12c0e40dec30fb33fec3ff8/v21.1/sso.html)

2021-01-29 23:59 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eb0ed3f7bf71eb8cc517d3c4fe6a696d9d3cbc90/

Edited pages:
- [cockroachcloud/connect-to-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eb0ed3f7bf71eb8cc517d3c4fe6a696d9d3cbc90/cockroachcloud/connect-to-your-cluster.html)
- [cockroachcloud/create-an-account.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eb0ed3f7bf71eb8cc517d3c4fe6a696d9d3cbc90/cockroachcloud/create-an-account.html)
- [cockroachcloud/deploy-a-python-to-do-app-with-flask-kubernetes-and-cockroachcloud.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eb0ed3f7bf71eb8cc517d3c4fe6a696d9d3cbc90/cockroachcloud/deploy-a-python-to-do-app-with-flask-kubernetes-and-cockroachcloud.html)
- [cockroachcloud/quickstart-trial-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eb0ed3f7bf71eb8cc517d3c4fe6a696d9d3cbc90/cockroachcloud/quickstart-trial-cluster.html)
- [cockroachcloud/quickstart.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eb0ed3f7bf71eb8cc517d3c4fe6a696d9d3cbc90/cockroachcloud/quickstart.html)
- [cockroachcloud/user-authorization.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eb0ed3f7bf71eb8cc517d3c4fe6a696d9d3cbc90/cockroachcloud/user-authorization.html)
- [releases/v20.1.0-beta.3.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eb0ed3f7bf71eb8cc517d3c4fe6a696d9d3cbc90/releases/v20.1.0-beta.3.html)
- [v20.2/build-a-go-app-with-cockroachdb-gorm.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eb0ed3f7bf71eb8cc517d3c4fe6a696d9d3cbc90/v20.2/build-a-go-app-with-cockroachdb-gorm.html)
- [v20.2/build-a-go-app-with-cockroachdb-pq.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eb0ed3f7bf71eb8cc517d3c4fe6a696d9d3cbc90/v20.2/build-a-go-app-with-cockroachdb-pq.html)
- [v20.2/build-a-go-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eb0ed3f7bf71eb8cc517d3c4fe6a696d9d3cbc90/v20.2/build-a-go-app-with-cockroachdb.html)
- [v20.2/build-a-python-app-with-cockroachdb-django.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eb0ed3f7bf71eb8cc517d3c4fe6a696d9d3cbc90/v20.2/build-a-python-app-with-cockroachdb-django.html)
- [v20.2/build-a-python-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eb0ed3f7bf71eb8cc517d3c4fe6a696d9d3cbc90/v20.2/build-a-python-app-with-cockroachdb.html)
- [v20.2/sso.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eb0ed3f7bf71eb8cc517d3c4fe6a696d9d3cbc90/v20.2/sso.html)
- [v21.1/sso.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/eb0ed3f7bf71eb8cc517d3c4fe6a696d9d3cbc90/v21.1/sso.html)

2021-01-30 00:07 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/24cd867010f6a6e2f98846b41e996a3f16ab2038/

Edited pages:
- [cockroachcloud/connect-to-your-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/24cd867010f6a6e2f98846b41e996a3f16ab2038/cockroachcloud/connect-to-your-cluster.html)
- [cockroachcloud/create-an-account.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/24cd867010f6a6e2f98846b41e996a3f16ab2038/cockroachcloud/create-an-account.html)
- [cockroachcloud/deploy-a-python-to-do-app-with-flask-kubernetes-and-cockroachcloud.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/24cd867010f6a6e2f98846b41e996a3f16ab2038/cockroachcloud/deploy-a-python-to-do-app-with-flask-kubernetes-and-cockroachcloud.html)
- [cockroachcloud/quickstart-trial-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/24cd867010f6a6e2f98846b41e996a3f16ab2038/cockroachcloud/quickstart-trial-cluster.html)
- [cockroachcloud/quickstart.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/24cd867010f6a6e2f98846b41e996a3f16ab2038/cockroachcloud/quickstart.html)
- [cockroachcloud/user-authorization.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/24cd867010f6a6e2f98846b41e996a3f16ab2038/cockroachcloud/user-authorization.html)
- [releases/v20.1.0-beta.3.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/24cd867010f6a6e2f98846b41e996a3f16ab2038/releases/v20.1.0-beta.3.html)
- [v20.2/build-a-go-app-with-cockroachdb-gorm.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/24cd867010f6a6e2f98846b41e996a3f16ab2038/v20.2/build-a-go-app-with-cockroachdb-gorm.html)
- [v20.2/build-a-go-app-with-cockroachdb-pq.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/24cd867010f6a6e2f98846b41e996a3f16ab2038/v20.2/build-a-go-app-with-cockroachdb-pq.html)
- [v20.2/build-a-go-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/24cd867010f6a6e2f98846b41e996a3f16ab2038/v20.2/build-a-go-app-with-cockroachdb.html)
- [v20.2/build-a-python-app-with-cockroachdb-django.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/24cd867010f6a6e2f98846b41e996a3f16ab2038/v20.2/build-a-python-app-with-cockroachdb-django.html)
- [v20.2/build-a-python-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/24cd867010f6a6e2f98846b41e996a3f16ab2038/v20.2/build-a-python-app-with-cockroachdb.html)
- [v20.2/sso.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/24cd867010f6a6e2f98846b41e996a3f16ab2038/v20.2/sso.html)
- [v21.1/sso.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/24cd867010f6a6e2f98846b41e996a3f16ab2038/v21.1/sso.html)

2021-01-30 00:09 UTC, merged