Add a Multiregion Overview, in a new section
cockroachdb/docs pull request #9723
Opened 2021-02-05 17:19 UTC by rmloveland

Fixes #9263.

Summary of changes:

- Add 'Multiregion overview' document, which explains the new
  multiregion UX coming in v21.1 at a high level.

- Create a new 'Deploy > Multiregion Clusters' section.  This new
  section, and the overview doc described above, paves the way for
  adding more detailed documentation on the new multiregion UX.

2021-02-05 17:19 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/9723)
<!-- Reviewable:end -->

2021-02-05 17:25 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/65bb7bf5d35434a073167a560612c0a7da686a01/

Edited pages:
- [v21.1/multiregion-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.html)

2021-02-05 17:28 UTC, rmloveland commented
Hi Adam and Nathan:

This is an edited version of the MR overview wiki page we have discussed some already.  I have attempted to incorporate feedback from that page and its related comments.

Please let me know if you think further improvements, clarifications, etc., are needed!

Also please let me know if I have introduced any errors in translation or during the additional rounds of edits here.

Thanks!

2021-02-05 20:52 UTC, nvanbenschoten reviewed
This is starting to take shape very nicely! It's great to see things on the docs site.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9723#-:-MSnxmqnEAn5Qj0hl2wX:bxklkcm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @rmloveland)

___
*[v21.1/multiregion-overview.md, line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSnqNiSEho9jUE0i2AL:-MSnqNiSEho9jUE0i2AM:b-idhnkz) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L13)):*
@rmloveland what do you think about this? We've copied it from doc to doc, but it seems void of any real meaning. In https://docs.google.com/document/d/1V3OnmwsGqDN12oD3Tyi1iEcQi1tYLDqt75MimV0sskI/edit#heading=h.altxv9aivgxv, we changed it to:

> a geographic region that a given database operates within and that a user specifies from the list of available cluster regions
___
*[v21.1/multiregion-overview.md, line 14 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSnrF_BAL7uYIai-fCJ:-MSnrF_C2NoD02tZBgEc:b-gpuer9) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L14)):*
> ```Markdown
> 
> - [_Database Regions_](#database-regions), which provide an abstraction for cloud provider regions and zones.
> - [_Table Localities_](#table-locality), which tell CockroachDB how to optimize access to a table's underlying data.
> ```

Is the word "underlying" needed here?
___
*[v21.1/multiregion-overview.md, line 22 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSnrVUFAWCtNaFI_r_a:-MSnrVUFAWCtNaFI_r_b:bhjpzjq) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L22)):*
> ```Markdown
> 
> 1. Set region information for the cluster at startup using [node startup locality options](cockroach-start.html#locality).
> 2. Add a primary region to a database, making it a "multi-region" database.
> ```

What about adding other regions to the database?
___
*[v21.1/multiregion-overview.md, line 26 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSnriuRCQ8VVHkfs3u9:-MSnriuRCQ8VVHkfs3uA:b-fwzc9g) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L26)):*
> ```
> the best experience for many users
> ```

I think we talked about how this wording was a little off and that there's more nuance here about when a user will want to play with neither, one, or both of these knobs. Did we want to rephrase this?
___
*[v21.1/multiregion-overview.md, line 38 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSns62m5B63wA3w73Si:-MSns62m5B63wA3w73Sj:bx4m8an) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L38)):*
> ```Markdown
>  _Database regions_ are a high-level abstraction for a geographic region. Each region is broken into multiple zones. These terms are meant to correspond directly to the region and zone terminology used by cloud providers.
> 
> Regions and zones are defined at the cluster level using the following [node startup locality options](cockroach-start.html#locality):
> ```

This would be a little easier to follow if we more clearly separated "cluster regions" (those shown with `SHOW REGIONS FROM CLUSTER`) from "database regions" (those added to the database from the list of available cluster regions). I'm imagining showing the `cockroach start --locality=` and the corresponding impact on `SHOW REGIONS FROM CLUSTER` in one step of the example. Then, in a separate step, we add regions to a database and show the impact on `SHOW REGIONS FROM DATABASE`.
___
*[v21.1/multiregion-overview.md, line 57 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSntFoF1Y-eub7Xy6ix:-MSntFoF1Y-eub7Xy6iy:bo7dpc6) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L57)):*
> ```Markdown
> ~~~
> 
> Now that the database has a primary region assigned to it, it is a "multi-region database."  All data in that database is stored within its assigned regions, and CockroachDB optimizes access to the database's underlying data from the primary region.
> ```

We should demonstrate how other regions are added to the database. In a cluster with many regions, it can be beneficial to create a database with only a primary region, but the reason for this is nuanced and non-intuitive. It will be much more common for users to add multiple regions to the database when running a multi-region cluster, so that's the story we should tell.
___
*[v21.1/multiregion-overview.md, line 81 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSnuEXw-TtLvGaIGuXv:-MSnuEXw-TtLvGaIGuXw:bpmatny) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L81)):*
> ```Markdown
> ### Regional tables
> 
> For _regional_ tables, access to the table will be fast in the table's "home region" and slower in other regions. In other words, CockroachDB optimizes access to data in regional tables from a single region. By default, a regional table's home region is the [database's primary region](#database-regions), but that can be changed to use any region available to the cluster.
> ```

"any region added to the database"
___
*[v21.1/multiregion-overview.md, line 100 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSnuVR71S_4hSWFI6hQ:-MSnuVR71S_4hSWFI6hR:b-vl7mrn) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L100)):*
> ```
> (such as promo codes)
> ```

This example isn't particularly helpful if I don't already know the movr schema. Maybe we should just remove it since we talk about it in the next paragraph as well.
___
*[v21.1/multiregion-overview.md, line 133 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSnvO5m2FIxi31f9C2d:-MSnvO5nBuak2IN2W7sC:b-d7kguh) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L133)):*
`s/computed column/hidden column/`

> The `crdb_region` column is computed for every row in a multi-region database.

I'm not sure what we're trying to say here.
___
*[v21.1/multiregion-overview.md, line 133 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSnvT7E5ZCozasCD0WS:-MSnvT7E5ZCozasCD0WT:b3xijkj) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L133)):*
> ```Markdown
> ~~~
> 
> After issuing the above statement, you will then have to modify each row's home region explicitly with an [`UPDATE`](update.html) statement that operates on a computed column called `crdb_region`. The `crdb_region` column is computed for every row in a multi-region database. It is used to determine the home region of each row.
> ```

I think it would be worthwhile to be a little more explicit about how every row in one of these tables has a hidden `crdb_region` column. And it can be selected with a statement like `SELECT id, crdb_region FROM <table>`.
___
*[v21.1/multiregion-overview.md, line 139 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSnuw9_-GKcBNvlfZEv:-MSnuw9_-GKcBNvlfZEw:b2f9mw9) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L139)):*
> ```Markdown
> UPDATE <table> SET crdb_region = 'eu-west' WHERE id IN (...)
> ~~~
> ```

I think it would be worth pointing out in a section here that regardless of table locality, users can access all data in a multi-region database with low latency from any of the database's regions by using stale follower reads. And we could then link to the follower reads docs.
___
*[v21.1/multiregion-overv [...]

2021-02-09 20:11 UTC, awoods187 requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9723)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @nvanbenschoten, and @rmloveland)

___
*[v21.1/multiregion-overview.md, line 2 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MT7BEJ_0yyndCXSWCrZ:-MT7BEJ_0yyndCXSWCr_:b-kwzy1t) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L2)):*
> ```Markdown
> ---
> title: Multiregion Overview
> ```

Do we want to be multiregion or multi-region moving forward? I have a slight preference for multi-region
___
*[v21.1/multiregion-overview.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MT7BONY63KH-Ivh46Xh:-MT7BONY63KH-Ivh46Xi:bjc51w0) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L5)):*
> ```Markdown
> summary: Learn how to use CockroachDB's improved multiregion user experience.
> toc: true
> ---
> ```

Do we need a note that's like "this functionality will be increasingly available in 21.1 Alphas."
___
*[v21.1/multiregion-overview.md, line 12 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MT7OA8g75t8D_V28zD1:-MT7OA8g75t8D_V28zD2:b-v8kx20) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L12)):*
> ```Markdown
> 
> To take advantage of these improved capabilities, you will need to understand the following concepts:
> ```

Can we call this cluster & database regions?
___
*[v21.1/multiregion-overview.md, line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSnqNiSEho9jUE0i2AL:-MT7O8tI0oP3pig0AhP3:b2ngthx) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L13)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

@rmloveland what do you think about this? We've copied it from doc to doc, but it seems void of any real meaning. In https://docs.google.com/document/d/1V3OnmwsGqDN12oD3Tyi1iEcQi1tYLDqt75MimV0sskI/edit#heading=h.altxv9aivgxv, we changed it to:

> a geographic region that a given database operates within and that a user specifies from the list of available cluster regions
</blockquote></details>

+1 
___
*[v21.1/multiregion-overview.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MT7OFFzAlEeQx3n1jNR:-MT7OFFzAlEeQx3n1jNS:bocswcv) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L16)):*
> ```Markdown
> - [_Table Localities_](#table-locality), which tell CockroachDB how to optimize access to a table's underlying data.
> - [_Survivability Goals_](#survivability-goals), which dictate the blast radius of failure(s) that a database can survive.
> ```

I still think survival goals should come after database regions and before patterns. They apply to the entire DB and their decision may dictate table choice in some cases and certainly, they are more closely aligned with regions.
___
*[v21.1/multiregion-overview.md, line 22 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSnrVUFAWCtNaFI_r_a:-MT7OW7hBtA0NQU0m3C5:b2ngthx) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L22)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What about adding other regions to the database?
</blockquote></details>

+1 
___
*[v21.1/multiregion-overview.md, line 22 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MT7Oai-BQEnh5dF56r2:-MT7Oai-BQEnh5dF56r3:b-7prtjl) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L22)):*
> ```Markdown
> 
> 1. Set region information for the cluster at startup using [node startup locality options](cockroach-start.html#locality).
> 2. Add a primary region to a database, making it a "multi-region" database.
> ```

Do we need to explain why primary region?
___
*[v21.1/multiregion-overview.md, line 54 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MT7OvM139NsS-5YQFAz:-MT7OvM139NsS-5YQFB-:b-o5kso7) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L54)):*
> ```Markdown
> {% include copy-clipboard.html %}
> ~~~ sql
> ALTER DATABASE <db> SET PRIMARY REGION 'us-east-2';
> ```

we should show how to have additional regions with syntax here 
___
*[v21.1/multiregion-overview.md, line 88 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MT7P7_N49m3FY8B93Na:-MT7P7_OADYglCFxvomt:b-nao8e8) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L88)):*
> ```Markdown
> 
> {% include copy-clipboard.html %}
> ~~~ sql
> ```

we probably want to show the primary region syntax here too
___
*[v21.1/multiregion-overview.md, line 102 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MT7PF_E0amwORfv5eu-:-MT7PF_E0amwORfv5eu0:b-s9d1mh) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L102)):*
> ```Markdown
> Use global tables when your application has a "read-mostly" table of reference data (such as promo codes) that is rarely updated, and needs to be available to all regions.
> 
> For an example of a table that can benefit from the _global_ table locality setting in a multi-region deployment, see the `promo_codes` table from the [MovR application](https://www.cockroachlabs.com/docs/v21.1/movr).
> ```

Other examples include zip codes or any table which isn't frequently written to.
___
*[v21.1/multiregion-overview.md, line 111 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MT7PL4VBI4aIb5kdLHo:-MT7PL4VBI4aIb5kdLHp:b-oei32r) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L111)):*
> ```Markdown
> ~~~
> 
> ### Regional by row tables
> ```

I think its weird to break up regional tables and regional by row tables with global in between. I would suggest moving this up.
___
*[v21.1/multiregion-overview.md, line 198 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MT7Pnmf5oH1DQ5i4E0d:-MT7Pnmg4DmA88IfO-oq:bjpxf54) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L198)):*
> ```Markdown
> 
> 4. _Change both [survivability](#survivability-goals) and [table locality](#table-locality)_: In this configuration, you upgrade from zone to region survivability, and optimize for low-latency multi-region reads. Single-region writes can be made low-latency with the right settings, but multi-region writes are higher-latency because they have to move across the network. This is useful for multi-region apps that want a high level of survivability.
> ```

Probably worth having a reminder that different DBs can mix and match these various patterns and choices all within the same cluster


<!-- Sent from Reviewable.io -->

2021-02-09 23:07 UTC, rmloveland reviewed
Thanks for the reviews Nathan and Andy!  I think my latest update has addressed all of your feedback items (?).  PTAL  

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9723#-:-MT7bf16C-3honzcsV2v:bsm1nl6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @awoods187, and @nvanbenschoten)

___
*[v21.1/multiregion-overview.md, line 2 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MT7BEJ_0yyndCXSWCrZ:-MT7biho1ClcPs8UTK8b:bjoodlp) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L2)):*
<details><summary><i>Previously, awoods187 (Andy Woods) wrote…</i></summary><blockquote>

Do we want to be multiregion or multi-region moving forward? I have a slight preference for multi-region
</blockquote></details>

I am trying to push for "multiregion" to normalize the phrase, similar to how "e-mail" became "email" over time (good article on this: https://www-cs-faculty.stanford.edu/~knuth/email.html)

Another example is the use of "multigenerational" to describe living situations, e.g. https://www.google.com/search?q=multigenerational+homes

Having said that, I could also update to "multi-region", don't feel too strongly.  maybe we should poll the team
___
*[v21.1/multiregion-overview.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MT7BONY63KH-Ivh46Xh:-MT7tfy4B8tdP9KkTsev:b-fobyht) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L5)):*
<details><summary><i>Previously, awoods187 (Andy Woods) wrote…</i></summary><blockquote>

Do we need a note that's like "this functionality will be increasingly available in 21.1 Alphas."
</blockquote></details>

Yes!  Added a sentence to that effect, with a link to our testing releases page
___
*[v21.1/multiregion-overview.md, line 12 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MT7OA8g75t8D_V28zD1:-MT7sZenD5cniTgbgJeN:b-pbdbwu) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L12)):*
<details><summary><i>Previously, awoods187 (Andy Woods) wrote…</i></summary><blockquote>

Can we call this cluster & database regions?
</blockquote></details>

Yes!  Updated these to be separate sections
___
*[v21.1/multiregion-overview.md, line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSnqNiSEho9jUE0i2AL:-MT7dH4-D6rIxXYVr1Zt:baa5nl9) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L13)):*
<details><summary><i>Previously, awoods187 (Andy Woods) wrote…</i></summary><blockquote>

+1 
</blockquote></details>

Sounds good - updated to use that, but edited the language ever so slightly.

Also added another bullet for cluster regions (and another section below), based on some feedback in a different comment.  Although it's a bit longer, I hope separating them is clearer.
___
*[v21.1/multiregion-overview.md, line 14 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSnrF_BAL7uYIai-fCJ:-MT7dItSB5C_OUuinU1B:bkn3iyo) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L14)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is the word "underlying" needed here?
</blockquote></details>

Nope :-} Updated (here and elsewhere), not sure why i fell in love with that word here
___
*[v21.1/multiregion-overview.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MT7OFFzAlEeQx3n1jNR:-MT7uQkM2gjawfh_W1Dy:bl2wfqs) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L16)):*
<details><summary><i>Previously, awoods187 (Andy Woods) wrote…</i></summary><blockquote>

I still think survival goals should come after database regions and before patterns. They apply to the entire DB and their decision may dictate table choice in some cases and certainly, they are more closely aligned with regions.
</blockquote></details>

that makes sense - I have re-ordered this list of links, and the sections below to use that ordering
___
*[v21.1/multiregion-overview.md, line 22 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSnrVUFAWCtNaFI_r_a:-MT7dm9t8LPoCXgiy9KH:b-awtns8) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L22)):*
<details><summary><i>Previously, awoods187 (Andy Woods) wrote…</i></summary><blockquote>

+1 
</blockquote></details>

Updated to say the following - what do you think?

'Add one or more regions to a database, making it a "multiregion" database.  By default, the first region added is the _primary region_; this can be changed later.'
___
*[v21.1/multiregion-overview.md, line 22 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MT7Oai-BQEnh5dF56r2:-MT7e9e63KkXD8iSTomN:b-igbnno) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L22)):*
<details><summary><i>Previously, awoods187 (Andy Woods) wrote…</i></summary><blockquote>

Do we need to explain why primary region?
</blockquote></details>

I think this gets explained below
___
*[v21.1/multiregion-overview.md, line 26 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSnriuRCQ8VVHkfs3u9:-MT7eFNP4p8vHnu22wNP:b-3dlkhp) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L26)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> the best experience for many users
> ```

I think we talked about how this wording was a little off and that there's more nuance here about when a user will want to play with neither, one, or both of these knobs. Did we want to rephrase this?
</blockquote></details>

Ha, that one must have snuck through.  Removed that sentence entirely.
___
*[v21.1/multiregion-overview.md, line 38 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSns62m5B63wA3w73Si:-MT7hbFiEsPMrSMnGi4g:bifcxk5) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L38)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This would be a little easier to follow if we more clearly separated "cluster regions" (those shown with `SHOW REGIONS FROM CLUSTER`) from "database regions" (those added to the database from the list of available cluster regions). I'm imagining showing the `cockroach start --locality=` and the corresponding impact on `SHOW REGIONS FROM CLUSTER` in one step of the example. Then, in a separate step, we add regions to a database and show the impact on `SHOW REGIONS FROM DATABASE`.
</blockquote></details>

Updated this to add a separate 'Cluster Regions' section that I think addresses this, PTAL
___
*[v21.1/multiregion-overview.md, line 54 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MT7OvM139NsS-5YQFAz:-MT7iWfHCg2Dw6LJoTPl:bqmjwcm) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L54)):*
<details><summary><i>Previously, awoods187 (Andy Woods) wrote…</i></summary><blockquote>

we should show how to have additional regions with syntax here 
</blockquote></details>

Added!
___
*[v21.1/multiregion-overview.md, line 57 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSntFoF1Y-eub7Xy6ix:-MT7iOSVA_xvSIK2FUxS:b-jgrx4z) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L57)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We sh [...]

2021-02-09 23:14 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/

Edited pages:
- [v21.1/multiregion-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.html)

2021-02-10 13:43 UTC, ajstorm requested changes
Looks great Rich!  I think this will continue to be very valuable to our customers.  Sorry for being late to the party with my comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9723#-:-MTBAUFbEKxc1V9u4_2e:b-wocx7e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @nvanbenschoten, and @rmloveland)

___
*[v21.1/multiregion-overview.md, line 2 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MT7BEJ_0yyndCXSWCrZ:-MTAyDSZ1gc7_gOjshqb:b-gfv8rw) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L2)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

I am trying to push for "multiregion" to normalize the phrase, similar to how "e-mail" became "email" over time (good article on this: https://www-cs-faculty.stanford.edu/~knuth/email.html)

Another example is the use of "multigenerational" to describe living situations, e.g. https://www.google.com/search?q=multigenerational+homes

Having said that, I could also update to "multi-region", don't feel too strongly.  maybe we should poll the team
</blockquote></details>

FWIW, I'm also a fan of multi-region (and e-mail, TBH).  I'm also mildly amused that Knuth has become an authority for hyphenated grammatical rules.  Considering how far he goes to avoid keystrokes, I'm not surprised he'd take that approach.  
___
*[v21.1/multiregion-overview.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MT7BONY63KH-Ivh46Xh:-MTAyj0hE_yGW-ruzO86:bso67i) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L5)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Yes!  Added a sentence to that effect, with a link to our testing releases page
</blockquote></details>

Do we also need some mention of the fact that these are only supported under CCL? While it's not currently being enforced in the code, it will be shortly,
___
*[v21.1/multiregion-overview.md, line 22 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSnrVUFAWCtNaFI_r_a:-MTB-57N5t2xEc0P9OiJ:b-sxc795) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L22)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Updated to say the following - what do you think?

'Add one or more regions to a database, making it a "multiregion" database.  By default, the first region added is the _primary region_; this can be changed later.'
</blockquote></details>

The "By default" part isn't exactly correct.  The primary region must be added to a database explicitly, using the PRIMARY REGION clause.
___
*[v21.1/multiregion-overview.md, line 38 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSns62m5B63wA3w73Si:-MTB06pb78vyPE0H8Zel:bdjnm9) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L38)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Updated this to add a separate 'Cluster Regions' section that I think addresses this, PTAL
</blockquote></details>

Cluster level -> node level?
___
*[v21.1/multiregion-overview.md, line 88 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MT7P7_N49m3FY8B93Na:-MTB5xOnCwh9gUCOD9Lm:bxy1zib) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L88)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Do you mean show `ALTER DATABASE SET PRIMARY REGION <region>` again?  

If that is what you mean I'm not sure about it.  I'd rather not repeat stuff that is in another section.  This is not really supposed to be a functional "quickstart/tutorial" type thing where you only need to read the section you want and just type stuff in (but I agree we do need to write something like that next, per your suggestion to do a REGIONAL BY ROW tutorial ASAP)
</blockquote></details>

I think what he means is `ALTER TABLE SET LOCALITY REGIONAL BY TABLE IN PRIMARY REGION`
___
*[v21.1/multiregion-overview.md, line 13 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTAzAu_DrzZz82Z4De1:-MTAzAu_DrzZz82Z4De2:bmaz0r8) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L13)):*
> ```Markdown
> To take advantage of these improved capabilities, you will need to understand the following concepts:
> 
> - [_Cluster Regions_](#cluster-regions) are geographic regions that a user specifies at cluster start time.
> ```

Very much a nit, but cluster regions aren't necessarily specified at cluster start time, but rather, at node start time.
___
*[v21.1/multiregion-overview.md, line 22 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTAzlthAB_RT45A_Scm:-MTAzlthAB_RT45A_Scn:b-zgalq5) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L22)):*
> ```Markdown
> At a high level, the simplest process for running a multiregion cluster is:
> 
> 1. Set region information for the cluster at startup using [node startup locality options](cockroach-start.html#locality).
> ```

Nit: Set region information for _each node_  at startup using...?
___
*[v21.1/multiregion-overview.md, line 27 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTB-_3J1tybf_9gKz4c:-MTB-_3J1tybf_9gKz4d:b8fvpj5) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L27)):*
> ```Markdown
> 4. (*Optional*) Change the database's survivability goals (zone or region). This step is optional because by default multiregion databases will be configured to survive zone failures.
> 
> The steps above describe the simplest case, where you accept all of the default settings. If your application has performance or availability needs that are different than what the default settings provide, there are many customization options to explore.
> ```

Nit: Can we drop the "many" as I'm worried that it implies configuration complexity.  Maybe we go with "there are customization options to explore"?
___
*[v21.1/multiregion-overview.md, line 46 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTB0EQ8BcDHo5fUhMTK:-MTB0EQ8BcDHo5fUhMTL:b-nrm1md) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L46)):*
> ```Markdown
> {% include copy-clipboard.html %}
> ~~~ shell
> cockroach start --locality=region=us-east-2 # ... other required flags go here
> ```

Can we add a zone to this example?
___
*[v21.1/multiregion-overview.md, line 64 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTB0gJj7KgT-nAsCf7u:-MTB0gJj7KgT-nAsCf7v:bm2z3c8) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L64)):*
> ```Markdown
> {% include copy-clipboard.html %}
> ~~~ sql
> ALTER DATABASE <db> SET PRIMARY REGION 'us-east-2';
> ```

The "SET" is not currently part of the syntax right now.  We should remove it until it is.
___
*[v21.1/multiregion-overview.md, line 67 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTB0t-FBJslbdrimz0I:-MTB0t-FBJslbdrimz0J:brs9t5s) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L67)):*
> ```Markdown
> ~~~
> 
> Now that the database has a primary region assigned to it, it is a "multiregion database."  All data in that database is stored within its assigned regions, and CockroachDB optimizes access to the database's data from the primary region.
> ```

Nit: The wording here is stran [...]

2021-02-10 17:13 UTC, rmloveland reviewed
Thanks for the review Adam!  Made quite a few changes based on your comments, appreciate the detailed feedback.  PTAL and let me know what you think!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9723#-:-MTBvPMN7U8beTTeNmPU:b-vv9wi0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @awoods187, @nvanbenschoten, and @rmloveland)

___
*[v21.1/multiregion-overview.md, line 2 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MT7BEJ_0yyndCXSWCrZ:-MTBbyPhAH1lO4_BJsmT:btcuj8h) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L2)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

FWIW, I'm also a fan of multi-region (and e-mail, TBH).  I'm also mildly amused that Knuth has become an authority for hyphenated grammatical rules.  Considering how far he goes to avoid keystrokes, I'm not surprised he'd take that approach.  
</blockquote></details>

LOL it's not his fault Adam, he's an assembler guy

Updated to use "multi-region" everywhere
___
*[v21.1/multiregion-overview.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MT7BONY63KH-Ivh46Xh:-MTBf0XrDZkegok-EF9Y:b1au6mz) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L5)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Do we also need some mention of the fact that these are only supported under CCL? While it's not currently being enforced in the code, it will be shortly,
</blockquote></details>

I would like to tackle licensing in another PR that is more comprehensive on just that topic, this page is already getting pretty dense compared to the one-pager on the wiki and in the GDoc
___
*[v21.1/multiregion-overview.md, line 22 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSnrVUFAWCtNaFI_r_a:-MTBfloc9jaXrgPu7hxb:bnbzdoh) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L22)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

The "By default" part isn't exactly correct.  The primary region must be added to a database explicitly, using the PRIMARY REGION clause.
</blockquote></details>

Oooh thanks.  Updated to the following - better?

"The database must have a _primary region_; this can be changed later."
___
*[v21.1/multiregion-overview.md, line 38 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSns62m5B63wA3w73Si:-MTBgJwIDl4orG93IGgm:b-896fja) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L38)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Cluster level -> node level?
</blockquote></details>

Done!
___
*[v21.1/multiregion-overview.md, line 88 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MT7P7_N49m3FY8B93Na:-MTBov7AA3v__DoEE99t:bfr66cr) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L88)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

I think what he means is `ALTER TABLE SET LOCALITY REGIONAL BY TABLE IN PRIMARY REGION`
</blockquote></details>

Ah, ok that makes sense.  I slotted that in just above the one showing how to set it for a specific region.
___
*[v21.1/multiregion-overview.md, line 13 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTAzAu_DrzZz82Z4De1:-MTBfNxV7NzRDeqiKg6t:b-y8lwuz) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L13)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Very much a nit, but cluster regions aren't necessarily specified at cluster start time, but rather, at node start time.
</blockquote></details>

Correct!  Updated, thanks!
___
*[v21.1/multiregion-overview.md, line 22 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTAzlthAB_RT45A_Scm:-MTBfXm1ALdoYVXqxQNw:b-no2gef) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L22)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Set region information for _each node_  at startup using...?
</blockquote></details>

Went with "for each node in the cluster at startup ..."
___
*[v21.1/multiregion-overview.md, line 27 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTB-_3J1tybf_9gKz4c:-MTBg-S707jsDSm7kynS:b-5z2l1r) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L27)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Can we drop the "many" as I'm worried that it implies configuration complexity.  Maybe we go with "there are customization options to explore"?
</blockquote></details>

Yes - dropped here and in one other place where "many" was used

(also, searching for that led me to a place where I had erroneously copied over the "this is the best for most users" language, so I deleted it)
___
*[v21.1/multiregion-overview.md, line 46 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTB0EQ8BcDHo5fUhMTK:-MTBhWYr7SdTRcY64Z45:b6ud4xo) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L46)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Can we add a zone to this example?
</blockquote></details>

Updated to add a zone!
___
*[v21.1/multiregion-overview.md, line 64 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTB0gJj7KgT-nAsCf7u:-MTBi3Ss-VVid3iA3u8a:bss4a1y) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L64)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

The "SET" is not currently part of the syntax right now.  We should remove it until it is.
</blockquote></details>

Removed!
___
*[v21.1/multiregion-overview.md, line 84 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTB1bJ7B6TUDT1OXZit:-MTBiVx86kQOK-GNM_Mw:b1wzo1t) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L84)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: To avoid confusion, I think we should limit the amount of permutations we have on the region monikers.  To that effect, I'd change "primary database region" to "database's primary region".
</blockquote></details>

Completely agree.  Just changed this instance and looked for others just in case (weren't any)
___
*[v21.1/multiregion-overview.md, line 87 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTB1tYm5PrgGbYR44X9:-MTBibgC6Vm4nMBQk5KL:b7u23c0) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L87)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

While I personally like Survivability, there was some concern (from the weaker typists on the team :-P) that we should go with Survival Goals.  Was the switch back to Survivability intentional?  
</blockquote></details>

No intention on my part, i think i'm working on two levels of copypasta here :-}

This will make it easier to type and say for everyone, plus it's closer to what the SQL uses
___
*[v21.1/multiregion-overview.md, line 112 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTB2Whl3WbMzdam30LK:-MTBjZ-K3ui7xFIyclU2:b-2q8540) ([raw file](https://github.com/cockroachdb/docs/blob [...]

2021-02-10 17:18 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b5f71327ca1c36cfc80c0d08237c6653f8f9c963/

Edited pages:
- [v21.1/multiregion-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b5f71327ca1c36cfc80c0d08237c6653f8f9c963/v21.1/multiregion-overview.html)

2021-02-10 22:29 UTC, ajstorm reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9723)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @awoods187, @nvanbenschoten, and @rmloveland)

___
*[v21.1/multiregion-overview.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MT7BONY63KH-Ivh46Xh:-MTCku5IEMqpOF1dIe3j:b-ccdqpn) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L5)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

I would like to tackle licensing in another PR that is more comprehensive on just that topic, this page is already getting pretty dense compared to the one-pager on the wiki and in the GDoc
</blockquote></details>

I agree.  A follow doc seems like the right place for this.
___
*[v21.1/multiregion-overview.md, line 22 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSnrVUFAWCtNaFI_r_a:-MTClOakAPhCZBaUMD8o:bdlxhha) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L22)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Oooh thanks.  Updated to the following - better?

"The database must have a _primary region_; this can be changed later."
</blockquote></details>

What about "Add one or more regions to a database, making it a "multi-region" database. One of these regions must be the _primary region_."?
___
*[v21.1/multiregion-overview.md, line 116 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTB2md62sawVHgnr2_W:-MTD0Vgn2pSUWCq9r5v_:b2azhfp) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L116)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Do you mean "read performance will be unaffected"?

If so I will argue for keeping it in so less expert folks reading it don't have to think through the implications themselves, just see it written.
</blockquote></details>

Sorry, I meant "You do not need to change any settings to survive zone failures."
___
*[v21.1/multiregion-overview.md, line 140 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTB45nGEsMmoBrVQlm_:-MTD0w-Z0_OEkZxn8CHK:b-25momp) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L140)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Sorry, i probably have missed some discussions about where the team is landing on this

I guess i have been experimenting in my head with thinking about it a bit differently

From my point of view as a learner of this stuff the whole "regional by table" thing seems a bit weird, where `BY TABLE` seems like something our SQL parser needs so it can be context-free or something, but as a user I just think of it more as a funnel from big to small:

- global (top of funnel, least specific data placement)
- regional (middle of funnel, middling specificity)
- regional by row (bottom of funnel, most specific data placement)

I think it is easier to learn the high level concepts from this POV - obviously it's not changing how anything works or what you have to type at the SQL prompt

It feels like from the engineering team's POV `by table` is meaningful, but as a user from the outside I just wanna say "make mine regional".  I guess what I'm saying is that ever since the initial UX tests i have been a knee-jerk anti-BY-TABLE-ist :-}

are you ok with experimenting with this in the alpha docs for now and then changing it later if it creates a learning difficulty for users?

if the answer is "no I think this is really fundamental, people will make mistakes if they don't talk about the concepts this way' i defer to your expertise on this - let me know!
</blockquote></details>

I'm actually less concerned about the exact semantics (the `by table` part), but just that we try to group the two "regional" types together as logically they're more similar than different from a read/write performance perspective (just at a different granularity).  Presenting them back-to-back, with a single sentence trying to unify the concepts (at different granularities) solves my concern.  Does that work for you?  Or does that go against what you're hoping to test for?
___
*[v21.1/multiregion-overview.md, line 158 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTB5mfI68JOeCe-xfpO:-MTD1m0c5HwiWawzlLle:bi9tnr8) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L158)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Updated!  

FYI I also changed the region and zone to `us-east-1` and `us-east -1b` since those were easy to find online (but strangely, not easy to find in the AWS docs)
</blockquote></details>

Looks great.  Nit: we could probably drop "in a multi-region cluster" here, as that seems to be implied.
___
*[v21.1/multiregion-overview.md, line 171 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTB6AtS-98gl-Thsq_W:-MTD23GK0-r0vE3NkzZx:b-r3haqq) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L171)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Oh nice!  I added this at the end of the paragraph, let me know what you think
</blockquote></details>

Looks good.  Nit: "However, that region can be specified" -> "However, that region is specified".  There's no ability to not have the region specified at the row level for regional by row tables, although you may rely on the default `gateway_region()`.
___
*[v21.1/multiregion-overview.md, line 179 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTB7Paz7gS7K5MBh38K:-MTD2s3AAwtwCxGUmUTF:bpf92fu) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L179)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

This comment prompted me to basically re-order the steps here and revise a fair bit.  I think the presentation is more clear and sequential now (hopefully).  Please let me know what you think 
</blockquote></details>

Looks awesome.  More comments below.
___
*[v21.1/multiregion-overview.md, line 217 at r3](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTD2iVO61emGX8XycLs:-MTD2iVO61emGX8XycLt:b-fvz9wt) ([raw file](https://github.com/cockroachdb/docs/blob/b5f71327ca1c36cfc80c0d08237c6653f8f9c963/v21.1/multiregion-overview.md#L217)):*
> ```Markdown
>     ~~~
> 
> - Let CockroachDB set the row's home region automatically. It will use the region of the gateway node from which the row is inserted.
> ```

I love these changes!  Nit: I'd switch the order of the options here.  We're hoping that most customer will use the default.


<!-- Sent from Reviewable.io -->

2021-02-11 00:18 UTC, awoods187 commented
___
*[v21.1/multiregion-overview.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MT7BONY63KH-Ivh46Xh:-MTDS2nd4hMoKJuYBYkw:bb73djm) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L5)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

I agree.  A follow doc seems like the right place for this.
</blockquote></details>

SGTM


<!-- Sent from Reviewable.io -->

2021-02-11 00:21 UTC, awoods187 approved these changes
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9723)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @nvanbenschoten, and @rmloveland)

___
*[v21.1/multiregion-overview.md, line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSnqNiSEho9jUE0i2AL:-MTDSCz68IfOo6bVoQ7C:bb7k0qh) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L13)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Sounds good - updated to use that, but edited the language ever so slightly.

Also added another bullet for cluster regions (and another section below), based on some feedback in a different comment.  Although it's a bit longer, I hope separating them is clearer.
</blockquote></details>

lgtm
___
*[v21.1/multiregion-overview.md, line 22 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSnrVUFAWCtNaFI_r_a:-MTDSLKa78rRjFevhRYb:bb7k0qh) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L22)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

What about "Add one or more regions to a database, making it a "multi-region" database. One of these regions must be the _primary region_."?
</blockquote></details>

lgtm


<!-- Sent from Reviewable.io -->

2021-02-11 19:41 UTC, rmloveland reviewed
Adam I think this latest hits all the points you brought up - let me know!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9723#-:-MTHbE8T7tvQRuSpR9Cp:b-vigh74)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @nvanbenschoten)

___
*[v21.1/multiregion-overview.md, line 22 at r1](https://reviewable.io/reviews/cockroachdb/docs/9723#-MSnrVUFAWCtNaFI_r_a:-MTHUYQl2FPRDQsgN7eL:b-896fja) ([raw file](https://github.com/cockroachdb/docs/blob/65bb7bf5d35434a073167a560612c0a7da686a01/v21.1/multiregion-overview.md#L22)):*
<details><summary><i>Previously, awoods187 (Andy Woods) wrote…</i></summary><blockquote>

lgtm
</blockquote></details>

Done!
___
*[v21.1/multiregion-overview.md, line 67 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTB0t-FBJslbdrimz0I:-MTHXcq65Zrf9o5PBeV6:b3dk394) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L67)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: The wording here is strange, as the database clearly has only one region, yet it's considered a "multi-region" database.  I don't think that we should change the terminology, but we might want to acknowledge the strangeness above - "While the database has only one region assigned to it, it is considered a "multi-region databases".  This means that all data in that database is..."
</blockquote></details>

Updated to use that phrasing, thanks
___
*[v21.1/multiregion-overview.md, line 116 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTB2md62sawVHgnr2_W:-MTHUhy-0eueJruHEqk3:bss4a1y) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L116)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Sorry, I meant "You do not need to change any settings to survive zone failures."
</blockquote></details>

Removed!
___
*[v21.1/multiregion-overview.md, line 140 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTB45nGEsMmoBrVQlm_:-MTHUtDV7gmhnhiHesIb:b5k7rr0) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L140)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

I'm actually less concerned about the exact semantics (the `by table` part), but just that we try to group the two "regional" types together as logically they're more similar than different from a read/write performance perspective (just at a different granularity).  Presenting them back-to-back, with a single sentence trying to unify the concepts (at different granularities) solves my concern.  Does that work for you?  Or does that go against what you're hoping to test for?
</blockquote></details>

That makes total sense.  I have moved them to be presented in order, and added a short sentence about each of the localities that I think shows the compare/contrast.   PTAL
___
*[v21.1/multiregion-overview.md, line 154 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTB5VYB4wxhldByECx0:-MTHXkfd34s3luaJuqMe:bks5xcz) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L154)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Ahh, here we describe the performance tradeoffs.  Any way we can move this up so that the previous sentence makes more sense.?
</blockquote></details>

Moved it up!
___
*[v21.1/multiregion-overview.md, line 158 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTB5mfI68JOeCe-xfpO:-MTHXvjnEuXTOGLxqWfJ:b6k596n) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L158)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Looks great.  Nit: we could probably drop "in a multi-region cluster" here, as that seems to be implied.
</blockquote></details>

Sounds good - dropped it here and also found a couple other uses that were redundant, so I removed them as well.
___
*[v21.1/multiregion-overview.md, line 171 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTB6AtS-98gl-Thsq_W:-MTHY3g-2JIP1z83sW_x:bf7c82p) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L171)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Looks good.  Nit: "However, that region can be specified" -> "However, that region is specified".  There's no ability to not have the region specified at the row level for regional by row tables, although you may rely on the default `gateway_region()`.
</blockquote></details>

Updated to "is specified"
___
*[v21.1/multiregion-overview.md, line 179 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTB7Paz7gS7K5MBh38K:-MTHY6f58HM_gQi4MGnU:b-ucfknh) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L179)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Looks awesome.  More comments below.
</blockquote></details>

Thanks!
___
*[v21.1/multiregion-overview.md, line 217 at r3](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTD2iVO61emGX8XycLs:-MTHZ5NxCQH0uHeaOJnk:bnv1db8) ([raw file](https://github.com/cockroachdb/docs/blob/b5f71327ca1c36cfc80c0d08237c6653f8f9c963/v21.1/multiregion-overview.md#L217)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

I love these changes!  Nit: I'd switch the order of the options here.  We're hoping that most customer will use the default.
</blockquote></details>

Yay thanks!

I assume you mean it should be `SELECT crdb_region, id ..` ?

Looks like I found the right order in some tests but transposed them when typing it up


<!-- Sent from Reviewable.io -->

2021-02-11 19:46 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/2f8b0f9c75e1c2d9c561eafe65cd8aee1aaea3f2/

Edited pages:
- [v21.1/multiregion-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/2f8b0f9c75e1c2d9c561eafe65cd8aee1aaea3f2/v21.1/multiregion-overview.html)

2021-02-12 13:36 UTC, ajstorm approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

Only a couple of minor nits left.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9723#-:-MTLS8yX83vIU4LUw02g:b3lf7x5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @nvanbenschoten, and @rmloveland)

___
*[v21.1/multiregion-overview.md, line 191 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTB9FS77r2y12yYCXvt:-MTLRI_uBUm4V8IRfR2x:b-vs1pr4) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L191)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Agreed!  Ended up revising this section quite a bit - mentioned in a previous comment
</blockquote></details>

Looks good.
___
*[v21.1/multiregion-overview.md, line 217 at r3](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTD2iVO61emGX8XycLs:-MTLRwRH6yMKyMdZFgSY:b-e43hd3) ([raw file](https://github.com/cockroachdb/docs/blob/b5f71327ca1c36cfc80c0d08237c6653f8f9c963/v21.1/multiregion-overview.md#L217)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Yay thanks!

I assume you mean it should be `SELECT crdb_region, id ..` ?

Looks like I found the right order in some tests but transposed them when typing it up
</blockquote></details>

Sorry, I meant put the default option of using gateway_region() before INSERT with region specified.
___
*[v21.1/multiregion-overview.md, line 208 at r4](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTLRWhn8y2mW3k_4itj:-MTLRWhn8y2mW3k_4itk:bqd8zgx) ([raw file](https://github.com/cockroachdb/docs/blob/2f8b0f9c75e1c2d9c561eafe65cd8aee1aaea3f2/v21.1/multiregion-overview.md#L208)):*
> ```Markdown
> ~~~
> 
> To add a new row to a regional by row table, you must choose one of the following options. This is necessary because every row in a regional by row table must have a home region.
> ```

Ultra nit: For readability I'd move the "This is necessary..." part to after the options, but your call.


<!-- Sent from Reviewable.io -->

2021-02-17 02:21 UTC, lnhsingh approved these changes
This looks great! There are a few nits and some clean up (or maybe rewording?) that I suggested, but otherwise LGTM. 

One thought I did have as I read through this is should the different types of tables/databases be hyphenated? This thought might only be applicable to `region by row table`, which might be easier to read/understand if it's `regional-by-row table` instead. IMO, the hyphenated version is easier to understand that "regional-by-row" is a descriptor. However, I think this is prob a style choice, so I leave that to you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9723#-:-MThlOVa4nRmuTXWbWgT:b39m22z)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @nvanbenschoten, and @rmloveland)

___
*[v21.1/multiregion-overview.md, line 15 at r4](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTgpYkI9zD4A7InfNyS:-MTgpYkJ62WsTAarYkwG:bmudcbw) ([raw file](https://github.com/cockroachdb/docs/blob/2f8b0f9c75e1c2d9c561eafe65cd8aee1aaea3f2/v21.1/multiregion-overview.md#L15)):*
> ```Markdown
> - [_Cluster Regions_](#cluster-regions) are geographic regions that a user specifies at node start time.
> - [_Database Regions_](#database-regions) are geographic regions that a given database operates within. A database region must be chosen from the list of available cluster regions.
> - [_Survival Goals_](#survival-goals), which dictate the blast radius of failure(s) that a database can survive.
> ```

nit: "blast radius" seems like a colloquialism that we might want to avoid for clarity's sake. What about just `Survival goals, which dictate how many simultaneous disasters a database can survive` (could also link here to `disaster-recovery.html`)
___
*[v21.1/multiregion-overview.md, line 23 at r4](https://reviewable.io/reviews/cockroachdb/docs/9723#-MThIvmv5-dvbHdJGZ2Z:-MThIvmv5-dvbHdJGZ2_:bbwpd9e) ([raw file](https://github.com/cockroachdb/docs/blob/2f8b0f9c75e1c2d9c561eafe65cd8aee1aaea3f2/v21.1/multiregion-overview.md#L23)):*
> ```Markdown
> 
> 1. Set region information for each node in the cluster at startup using [node startup locality options](cockroach-start.html#locality).
> 2. Add one or more regions to a database, making it a "multi-region" database. One of these regions must be the _primary region_.
> ```

Do you have to do anything to set the primary region? Oh, I see that this info is given later. Maybe link primary region to the Database regions section? Or include a "For more info on setting the primary region, see..."
___
*[v21.1/multiregion-overview.md, line 32 at r4](https://reviewable.io/reviews/cockroachdb/docs/9723#-MThHyhi-aIL6-8CsCH5:-MThHyhi-aIL6-8CsCH6:b-neuls1) ([raw file](https://github.com/cockroachdb/docs/blob/2f8b0f9c75e1c2d9c561eafe65cd8aee1aaea3f2/v21.1/multiregion-overview.md#L32)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> The documentation for the new Multi-region features described below is still in development. More documentation on these features will be published in the run-up to the v21.1 release.
> ```

nit: I think `Multi-region` should be `multi-region` here
___
*[v21.1/multiregion-overview.md, line 49 at r4](https://reviewable.io/reviews/cockroachdb/docs/9723#-MThIb4PEblqxs3DwIuB:-MThIb4PEblqxs3DwIuC:b-slqtyr) ([raw file](https://github.com/cockroachdb/docs/blob/2f8b0f9c75e1c2d9c561eafe65cd8aee1aaea3f2/v21.1/multiregion-overview.md#L49)):*
> ```Markdown
> ~~~
> 
> To show all of a cluster's regions, execute the following SQL statement:
> ```

I assume the reference doc for `SHOW REGIONS` (and the other following SQL statements) will be added later?
___
*[v21.1/multiregion-overview.md, line 84 at r4](https://reviewable.io/reviews/cockroachdb/docs/9723#-MThJDrqCnFeYLrD4r_X:-MThJDrqCnFeYLrD4r_Y:b-bj38e9) ([raw file](https://github.com/cockroachdb/docs/blob/2f8b0f9c75e1c2d9c561eafe65cd8aee1aaea3f2/v21.1/multiregion-overview.md#L84)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> If you are happy to accept the default _Survival Goals_ and _Table Localities_ (both described below), there is nothing else you need to do once you have set a database's primary region.
> ```

nit: link to the Survival goals / Table localities sections instead of including the `(both described below)` parenthetical. IMO, this callout is too conversational and could be more concise, but I think that is a style call. I would suggest something like "If the default survival goals and table localities are sufficient for your setup, you only need to set the database's primary region." (but better, so maybe you can just leave what you have)
___
*[v21.1/multiregion-overview.md, line 110 at r4](https://reviewable.io/reviews/cockroachdb/docs/9723#-MThLUTz9DY_YJKAEcOA:-MThLUTz9DY_YJKAEcOB:b-29xyy7) ([raw file](https://github.com/cockroachdb/docs/blob/2f8b0f9c75e1c2d9c561eafe65cd8aee1aaea3f2/v21.1/multiregion-overview.md#L110)):*
> ```Markdown
> ### Surviving zone failures
> 
> The zone level survival goal has the following properties:
> ```

Should there be a list of properties here? I'm not quite sure what this is supposed to say (or maybe it should just be removed?)
___
*[v21.1/multiregion-overview.md, line 117 at r4](https://reviewable.io/reviews/cockroachdb/docs/9723#-MThf25F30O0bVkzdFYz:-MThf25F30O0bVkzdFZ-:buj6mm7) ([raw file](https://github.com/cockroachdb/docs/blob/2f8b0f9c75e1c2d9c561eafe65cd8aee1aaea3f2/v21.1/multiregion-overview.md#L117)):*
> ```Markdown
> Surviving zone failures is the default setting for multi-region databases.
> 
> If your application has performance or availability needs that are different than what the default settings provide, there are customization options to explore.
> ```

Is there somewhere you can link to for "customization options to explore"? Or maybe this should say something like "more info coming later"
___
*[v21.1/multiregion-overview.md, line 181 at r4](https://reviewable.io/reviews/cockroachdb/docs/9723#-MThi16D1LV7ENoQl5qY:-MThi16D1LV7ENoQl5qZ:b6iupwp) ([raw file](https://github.com/cockroachdb/docs/blob/2f8b0f9c75e1c2d9c561eafe65cd8aee1aaea3f2/v21.1/multiregion-overview.md#L181)):*
> ```Markdown
> ### Regional by row tables
> 
> In _regional by row_ tables, individual rows are optimized for access from different regions. This setting divides a table and all of its indexes into [partitions](https://www.cockroachlabs.com/docs/v21.1/partitioning.html), with each partition optimized for access from a different region. Like [regional tables](#regional-tables), _regional by row_ tables are optimized for access from a single region. However, that region is specified at the row level instead of applying to the whole table.
> ```

nit: this should be a relative link (`partitioning.html`)
___
*[v21.1/multiregion-overview.md, line 240 at r4](https://reviewable.io/reviews/cockroachdb/docs/9723#-MThkrYm8LD0m7VjHMe5:-MThkrYn09F9veTB0DMc:b-v07rec) ([raw file](https://github.com/cockroachdb/docs/blob/2f8b0f9c75e1c2d9c561eafe65cd8aee1aaea3f2/v21.1/multiregion-overview.md#L240)):*
> ```Markdown
> The options for changing your multi-region cluster's configuration include:
> 
> 1. _Change nothing_: Using the [default settings](#default-settings), you get zone survival, low-latency single-region writes, and multi-region stale reads.
> ```

nit: I think this should be a bulleted list instead of numbered since it's not a series of steps. 
___
*[v21.1/multiregion-overview.md, line 254 at r4](https://reviewable.io/reviews/cockroachdb/docs/9723#-MThbwB33RfqhWAUVXWb:-MThbwB33RfqhWAUVXWc:bitec5d) ([raw file](https://github.com/cockroachdb/docs/blob/2f8b0f9c75e1c2d9c561eafe65cd8aee1aaea3f2/v21.1/multiregion-overview.md#L254)):*
> ```Markdown
> - [Topology Patterns](topology-patterns.html)
> 
> <!-- EOF -->
> ```

Does this need to be removed?


<!-- Sent from Reviewable.io -->

2021-02-17 16:55 UTC, rmloveland reviewed
Thanks for the review Lauren!  I think I have addressed all your inline feedback 

I tend to agree with your regional-by-row comment.  I will probably revisit this soon, as we are still nailing down some naming stuff.  Adding hyphens does make them more distinct when discussed in prose.  We might rename some things in the next few weeks (?) but I will keep this in mind as we get more of these multi-region docs out

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9723#-:-MTksdk_2HCOdEWjiJkd:b6df54)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm, @lnhsingh, and @nvanbenschoten)

___
*[v21.1/multiregion-overview.md, line 191 at r2](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTB9FS77r2y12yYCXvt:-MTksb4y5EfHMA--7_yW:b-ucfknh) ([raw file](https://github.com/cockroachdb/docs/blob/e6c6f7ce9f628fa7c37f421413181c56f8f5f1fd/v21.1/multiregion-overview.md#L191)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Looks good.
</blockquote></details>

Thanks!
___
*[v21.1/multiregion-overview.md, line 217 at r3](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTD2iVO61emGX8XycLs:-MTkq2-C4WFXGXx3VbeS:bwt0gad) ([raw file](https://github.com/cockroachdb/docs/blob/b5f71327ca1c36cfc80c0d08237c6653f8f9c963/v21.1/multiregion-overview.md#L217)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Sorry, I meant put the default option of using gateway_region() before INSERT with region specified.
</blockquote></details>

Cool - reordered
___
*[v21.1/multiregion-overview.md, line 15 at r4](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTgpYkI9zD4A7InfNyS:-MTkquar4yfz6pBp6DGi:bv2qtcq) ([raw file](https://github.com/cockroachdb/docs/blob/2f8b0f9c75e1c2d9c561eafe65cd8aee1aaea3f2/v21.1/multiregion-overview.md#L15)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

nit: "blast radius" seems like a colloquialism that we might want to avoid for clarity's sake. What about just `Survival goals, which dictate how many simultaneous disasters a database can survive` (could also link here to `disaster-recovery.html`)
</blockquote></details>

Went with "dictate how many simultaneous failures", and added a link to the Disaster Recovery page in the See Also section
___
*[v21.1/multiregion-overview.md, line 23 at r4](https://reviewable.io/reviews/cockroachdb/docs/9723#-MThIvmv5-dvbHdJGZ2Z:-MTkr1Hh9np4q7-KC4Hb:b-sjjt9r) ([raw file](https://github.com/cockroachdb/docs/blob/2f8b0f9c75e1c2d9c561eafe65cd8aee1aaea3f2/v21.1/multiregion-overview.md#L23)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Do you have to do anything to set the primary region? Oh, I see that this info is given later. Maybe link primary region to the Database regions section? Or include a "For more info on setting the primary region, see..."
</blockquote></details>

Updated the language a bit.  I hesitated to add the "for more info" because I want folks to read this part fully before jumping to a "how to do it" (which we do give below)
___
*[v21.1/multiregion-overview.md, line 32 at r4](https://reviewable.io/reviews/cockroachdb/docs/9723#-MThHyhi-aIL6-8CsCH5:-MTkrO9Z3488k9nQaRgB:bgo2eje) ([raw file](https://github.com/cockroachdb/docs/blob/2f8b0f9c75e1c2d9c561eafe65cd8aee1aaea3f2/v21.1/multiregion-overview.md#L32)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

nit: I think `Multi-region` should be `multi-region` here
</blockquote></details>

fIxEd It :-} 
___
*[v21.1/multiregion-overview.md, line 49 at r4](https://reviewable.io/reviews/cockroachdb/docs/9723#-MThIb4PEblqxs3DwIuB:-MTkrTA24P7Cx8CwBfoy:b-bmay2r) ([raw file](https://github.com/cockroachdb/docs/blob/2f8b0f9c75e1c2d9c561eafe65cd8aee1aaea3f2/v21.1/multiregion-overview.md#L49)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

I assume the reference doc for `SHOW REGIONS` (and the other following SQL statements) will be added later?
</blockquote></details>

Yes!  none of that exists yet
___
*[v21.1/multiregion-overview.md, line 84 at r4](https://reviewable.io/reviews/cockroachdb/docs/9723#-MThJDrqCnFeYLrD4r_X:-MTkrosSDkNVX7j_SUCD:bozwydy) ([raw file](https://github.com/cockroachdb/docs/blob/2f8b0f9c75e1c2d9c561eafe65cd8aee1aaea3f2/v21.1/multiregion-overview.md#L84)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

nit: link to the Survival goals / Table localities sections instead of including the `(both described below)` parenthetical. IMO, this callout is too conversational and could be more concise, but I think that is a style call. I would suggest something like "If the default survival goals and table localities are sufficient for your setup, you only need to set the database's primary region." (but better, so maybe you can just leave what you have)
</blockquote></details>

Split the difference with "If the default .. meet your needs, there is nothing else you need to do ..."
___
*[v21.1/multiregion-overview.md, line 110 at r4](https://reviewable.io/reviews/cockroachdb/docs/9723#-MThLUTz9DY_YJKAEcOA:-MTks4Hr9-ptsezL0kkA:b-cj3kod) ([raw file](https://github.com/cockroachdb/docs/blob/2f8b0f9c75e1c2d9c561eafe65cd8aee1aaea3f2/v21.1/multiregion-overview.md#L110)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Should there be a list of properties here? I'm not quite sure what this is supposed to say (or maybe it should just be removed?)
</blockquote></details>

Ah must have crept in through edits

Updated to say "with the zone level survival goal, the database will ..."
___
*[v21.1/multiregion-overview.md, line 117 at r4](https://reviewable.io/reviews/cockroachdb/docs/9723#-MThf25F30O0bVkzdFYz:-MTksHkW4UNuywxp90Tx:be6k9py) ([raw file](https://github.com/cockroachdb/docs/blob/2f8b0f9c75e1c2d9c561eafe65cd8aee1aaea3f2/v21.1/multiregion-overview.md#L117)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Is there somewhere you can link to for "customization options to explore"? Or maybe this should say something like "more info coming later"
</blockquote></details>

Changed to say "..., you can explore the other customization options described on this page"
___
*[v21.1/multiregion-overview.md, line 181 at r4](https://reviewable.io/reviews/cockroachdb/docs/9723#-MThi16D1LV7ENoQl5qY:-MTksYFGDEjEGJ1dt4sd:b-1d095l) ([raw file](https://github.com/cockroachdb/docs/blob/2f8b0f9c75e1c2d9c561eafe65cd8aee1aaea3f2/v21.1/multiregion-overview.md#L181)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

nit: this should be a relative link (`partitioning.html`)
</blockquote></details>

Fixed! (here and in a couple other places where that happened)
___
*[v21.1/multiregion-overview.md, line 208 at r4](https://reviewable.io/reviews/cockroachdb/docs/9723#-MTLRWhn8y2mW3k_4itj:-MTkqIm42yCErVjr9542:b-yovi8s) ([raw file](https://github.com/cockroachdb/docs/blob/2f8b0f9c75e1c2d9c561eafe65cd8aee1aaea3f2/v21.1/multiregion-overview.md#L208)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Ultra nit: For readability I'd move the "This is necessary..." part to after the options, but your call.
</blockquote></details>

Moved it!
___
*[v21.1/multiregion-overview.md, line 240 at r4](https://reviewable.io/reviews/cockroachdb/docs/9723#-MThkrYm8LD0m7VjHMe5:-MTkqT8C63HX-5es47xG:by5b3ks) ([raw file](https://github.com/cockroachdb/docs/blob/2f8b0f9c75e1c2d9c561eafe65cd8aee1aaea3f2/v21.1/multiregion-overview.md#L240)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

nit: I think this should be a bulleted list instead of numbered since it's not a series of steps. 
</b [...]

2021-02-17 17:03 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/de5f774954ea4ae1e47e47c339ee757ec3951b4a/

Edited pages:
- [v21.1/multiregion-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/de5f774954ea4ae1e47e47c339ee757ec3951b4a/v21.1/multiregion-overview.html)

2021-02-17 18:39 UTC, merged