Developer Guide v2 (Phase 1)
cockroachdb/docs pull request #9724
Opened 2021-02-05 17:43 UTC by ericharmeling

This PR includes the "Phase 1" changes for the [Developer Guide v2 project](https://cockroachlabs.atlassian.net/wiki/spaces/PROD/pages/1076002864/Developer+Guide+v2).

See below for an overview of the changes.

### Organizational changes
(@ericharmeling) 

Files changed:

- `_includes/sidebar-data-v21.1.json`
- `v21.1/bulk-delete-data.md`
- `v21.1/delete.md`
- `v21.1/hash-sharded-indexes.md`
- `v21.1/indexes.md`
- `v21.1/limit-offset.md`
- `v21.1/order-by.md`
- `v21.1/pagination.md`
- `v21.1/performance-best-practices-overview.md`
- `v21.1/primary-key.md`
- `v21.1/query-data.md`
- `v21.1/selection-queries.md`

The changes include:

- A complete overhaul of the "Develop" ToC in the docs (see the [Content Plan](https://cockroachlabs.atlassian.net/wiki/spaces/PROD/pages/1076002864/Developer+Guide+v2#DeveloperGuidev2-Deliverables)).
- Some changes to the "Reference -> SQL" ToC.
- Some page sections trimmed, or moved to dedicated pages, to fit in the new "Develop" ToC changes.

### Develop: Overview 
(@ericharmeling)

Files changed:

- `v21.1/developer-guide-overview.md`

These changes include a rewritten Developer Guide overview that provides an introduction to CockroachDB, for developers.

### Develop: Connect
(@ianjevans)

Files changed:

- `_includes/cockroachcloud/connect_to_crc.md`
- `v21.1/connect-to-the-database-cockroachcloud.md`
- `v21.1/connect-to-the-database.md`
- `v21.1/connection-parameters.md`
- `v21.1/connection-pooling.md`
- `v21.1/install-client-drivers.md`
- `v21.1/secure-a-cluster.md`

These changes include:

- Connection guidance for CockroachCloud Free Tier users, in priority languages.
- Updated client driver and ORM connection guidance.
- A new page on connection pooling, with Hikari as reference example.

### Develop: Schema Design
(@ericharmeling)

Files changed:

- The `_includes/v21.1/sql/...` files in the PR.
- `v21.1/schema-design-database.md`
- `v21.1/schema-design-indexes.md`
- `v21.1/schema-design-overview.md`
- `v21.1/schema-design-schema.md`
- `v21.1/schema-design-table.md`
- `v21.1/schema-design-update.md`

These changes make up a new chapter that gives schema design guidance for developers.

### Other misc changes 

Any other changed files include minor updates for terminology consistency and reference updates.

2021-02-05 17:43 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/9724)
<!-- Reviewable:end -->

2021-02-05 17:50 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/

Edited pages:
- [v21.1/bulk-delete-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/bulk-delete-data.html)
- [v21.1/connect-to-the-database-cockroachcloud.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/connect-to-the-database-cockroachcloud.html)
- [v21.1/connect-to-the-database.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/connect-to-the-database.html)
- [v21.1/connection-parameters.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/connection-parameters.html)
- [v21.1/connection-pooling.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/connection-pooling.html)
- [v21.1/delete.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/delete.html)
- [v21.1/developer-guide-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/developer-guide-overview.html)
- [v21.1/hash-sharded-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/hash-sharded-indexes.html)
- [v21.1/indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/indexes.html)
- [v21.1/install-client-drivers.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/install-client-drivers.html)
- [v21.1/joins.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/joins.html)
- [v21.1/limit-offset.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/limit-offset.html)
- [v21.1/make-queries-fast.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/make-queries-fast.html)
- [v21.1/pagination.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/pagination.html)
- [v21.1/performance-best-practices-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/performance-best-practices-overview.html)
- [v21.1/primary-key.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/primary-key.html)
- [v21.1/query-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/query-data.html)
- [v21.1/schema-design-database.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/schema-design-database.html)
- [v21.1/schema-design-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/schema-design-indexes.html)
- [v21.1/schema-design-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/schema-design-overview.html)
- [v21.1/schema-design-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/schema-design-schema.html)
- [v21.1/schema-design-table.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/schema-design-table.html)
- [v21.1/schema-design-update.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/schema-design-update.html)
- [v21.1/secure-a-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/secure-a-cluster.html)
- [v21.1/select-clause.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/select-clause.html)
- [v21.1/selection-queries.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/selection-queries.html)
- [v21.1/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/sql-feature-support.html)
- [v21.1/start-a-local-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/start-a-local-cluster.html)
- [v21.1/table-expressions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cb775db0dcd58776858537eb9dfb565093040b27/v21.1/table-expressions.html)

2021-02-05 19:00 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/

Edited pages:
- [v21.1/alter-primary-key.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/alter-primary-key.html)
- [v21.1/build-a-java-app-with-cockroachdb-hibernate.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/build-a-java-app-with-cockroachdb-hibernate.html)
- [v21.1/build-a-java-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/build-a-java-app-with-cockroachdb.html)
- [v21.1/build-a-spring-app-with-cockroachdb-jdbc.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/build-a-spring-app-with-cockroachdb-jdbc.html)
- [v21.1/bulk-delete-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/bulk-delete-data.html)
- [v21.1/connect-to-the-database-cockroachcloud.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/connect-to-the-database-cockroachcloud.html)
- [v21.1/connect-to-the-database.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/connect-to-the-database.html)
- [v21.1/connection-parameters.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/connection-parameters.html)
- [v21.1/connection-pooling.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/connection-pooling.html)
- [v21.1/create-index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/create-index.html)
- [v21.1/create-table.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/create-table.html)
- [v21.1/delete-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/delete-data.html)
- [v21.1/delete.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/delete.html)
- [v21.1/developer-guide-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/developer-guide-overview.html)
- [v21.1/experimental-features.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/experimental-features.html)
- [v21.1/functions-and-operators.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/functions-and-operators.html)
- [v21.1/hash-sharded-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/hash-sharded-indexes.html)
- [v21.1/indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/indexes.html)
- [v21.1/insert.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/insert.html)
- [v21.1/install-client-drivers.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/install-client-drivers.html)
- [v21.1/interleave-in-parent.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/interleave-in-parent.html)
- [v21.1/joins.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/joins.html)
- [v21.1/jsonb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/jsonb.html)
- [v21.1/known-limitations.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/known-limitations.html)
- [v21.1/limit-offset.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/limit-offset.html)
- [v21.1/make-queries-fast.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/make-queries-fast.html)
- [v21.1/null-handling.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/null-handling.html)
- [v21.1/pagination.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/pagination.html)
- [v21.1/performance-best-practices-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/performance-best-practices-overview.html)
- [v21.1/primary-key.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/primary-key.html)
- [v21.1/query-behavior-troubleshooting.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/query-behavior-troubleshooting.html)
- [v21.1/query-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/query-data.html)
- [v21.1/run-multi-statement-transactions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/run-multi-statement-transactions.html)
- [v21.1/schema-design-database.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/schema-design-database.html)
- [v21.1/schema-design-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/schema-design-indexes.html)
- [v21.1/schema-design-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/schema-design-overview.html)
- [v21.1/schema-design-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/schema-design-schema.html)
- [v21.1/schema-design-table.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/schema-design-table.html)
- [v21.1/schema-design-update.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/schema-design-update.html)
- [v21.1/secure-a-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/secure-a-cluster.html)
- [v21.1/select-clause.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/select-clause.html)
- [v21.1/selection-queries.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/selection-queries.html)
- [v21.1/sql-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/sql-faqs.html)
- [v21.1/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/sql-feature-support.html)
- [v21.1/start-a-local-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/start-a-local-cluster.html)
- [v21.1/table-expressions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e3d575891633ed23e2f016b3418965609ece0755/v21.1/table-expressions.html)
- [v21.1/update.md](http://cockroach-docs-review.s3-website-u [...]

2021-02-05 19:39 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/

Edited pages:
- [v21.1/alter-primary-key.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/alter-primary-key.html)
- [v21.1/build-a-java-app-with-cockroachdb-hibernate.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/build-a-java-app-with-cockroachdb-hibernate.html)
- [v21.1/build-a-java-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/build-a-java-app-with-cockroachdb.html)
- [v21.1/build-a-spring-app-with-cockroachdb-jdbc.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/build-a-spring-app-with-cockroachdb-jdbc.html)
- [v21.1/bulk-delete-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/bulk-delete-data.html)
- [v21.1/connect-to-the-database-cockroachcloud.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/connect-to-the-database-cockroachcloud.html)
- [v21.1/connect-to-the-database.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/connect-to-the-database.html)
- [v21.1/connection-parameters.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/connection-parameters.html)
- [v21.1/connection-pooling.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/connection-pooling.html)
- [v21.1/create-index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/create-index.html)
- [v21.1/create-table.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/create-table.html)
- [v21.1/delete-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/delete-data.html)
- [v21.1/delete.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/delete.html)
- [v21.1/developer-guide-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/developer-guide-overview.html)
- [v21.1/experimental-features.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/experimental-features.html)
- [v21.1/functions-and-operators.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/functions-and-operators.html)
- [v21.1/hash-sharded-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/hash-sharded-indexes.html)
- [v21.1/indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/indexes.html)
- [v21.1/insert.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/insert.html)
- [v21.1/install-client-drivers.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/install-client-drivers.html)
- [v21.1/interleave-in-parent.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/interleave-in-parent.html)
- [v21.1/joins.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/joins.html)
- [v21.1/jsonb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/jsonb.html)
- [v21.1/known-limitations.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/known-limitations.html)
- [v21.1/limit-offset.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/limit-offset.html)
- [v21.1/make-queries-fast.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/make-queries-fast.html)
- [v21.1/null-handling.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/null-handling.html)
- [v21.1/pagination.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/pagination.html)
- [v21.1/performance-best-practices-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/performance-best-practices-overview.html)
- [v21.1/primary-key.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/primary-key.html)
- [v21.1/query-behavior-troubleshooting.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/query-behavior-troubleshooting.html)
- [v21.1/query-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/query-data.html)
- [v21.1/run-multi-statement-transactions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/run-multi-statement-transactions.html)
- [v21.1/schema-design-database.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/schema-design-database.html)
- [v21.1/schema-design-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/schema-design-indexes.html)
- [v21.1/schema-design-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/schema-design-overview.html)
- [v21.1/schema-design-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/schema-design-schema.html)
- [v21.1/schema-design-table.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/schema-design-table.html)
- [v21.1/schema-design-update.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/schema-design-update.html)
- [v21.1/secure-a-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/secure-a-cluster.html)
- [v21.1/select-clause.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/select-clause.html)
- [v21.1/selection-queries.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/selection-queries.html)
- [v21.1/sql-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/sql-faqs.html)
- [v21.1/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/sql-feature-support.html)
- [v21.1/start-a-local-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/start-a-local-cluster.html)
- [v21.1/table-expressions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4cccd8b2069648045d72724ce302452d47653276/v21.1/table-expressions.html)
- [v21.1/update.md](http://cockroach-docs-review.s3-website-u [...]

2021-02-05 21:12 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/

Edited pages:
- [v21.1/alter-primary-key.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/alter-primary-key.html)
- [v21.1/build-a-java-app-with-cockroachdb-hibernate.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/build-a-java-app-with-cockroachdb-hibernate.html)
- [v21.1/build-a-java-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/build-a-java-app-with-cockroachdb.html)
- [v21.1/build-a-spring-app-with-cockroachdb-jdbc.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/build-a-spring-app-with-cockroachdb-jdbc.html)
- [v21.1/bulk-delete-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/bulk-delete-data.html)
- [v21.1/connect-to-the-database-cockroachcloud.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/connect-to-the-database-cockroachcloud.html)
- [v21.1/connect-to-the-database.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/connect-to-the-database.html)
- [v21.1/connection-parameters.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/connection-parameters.html)
- [v21.1/connection-pooling.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/connection-pooling.html)
- [v21.1/create-index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/create-index.html)
- [v21.1/create-table.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/create-table.html)
- [v21.1/delete-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/delete-data.html)
- [v21.1/delete.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/delete.html)
- [v21.1/developer-guide-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/developer-guide-overview.html)
- [v21.1/experimental-features.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/experimental-features.html)
- [v21.1/functions-and-operators.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/functions-and-operators.html)
- [v21.1/hash-sharded-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/hash-sharded-indexes.html)
- [v21.1/indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/indexes.html)
- [v21.1/insert.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/insert.html)
- [v21.1/install-client-drivers.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/install-client-drivers.html)
- [v21.1/interleave-in-parent.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/interleave-in-parent.html)
- [v21.1/joins.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/joins.html)
- [v21.1/jsonb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/jsonb.html)
- [v21.1/known-limitations.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/known-limitations.html)
- [v21.1/limit-offset.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/limit-offset.html)
- [v21.1/make-queries-fast.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/make-queries-fast.html)
- [v21.1/null-handling.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/null-handling.html)
- [v21.1/pagination.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/pagination.html)
- [v21.1/performance-best-practices-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/performance-best-practices-overview.html)
- [v21.1/primary-key.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/primary-key.html)
- [v21.1/query-behavior-troubleshooting.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/query-behavior-troubleshooting.html)
- [v21.1/query-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/query-data.html)
- [v21.1/run-multi-statement-transactions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/run-multi-statement-transactions.html)
- [v21.1/schema-design-database.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/schema-design-database.html)
- [v21.1/schema-design-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/schema-design-indexes.html)
- [v21.1/schema-design-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/schema-design-overview.html)
- [v21.1/schema-design-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/schema-design-schema.html)
- [v21.1/schema-design-table.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/schema-design-table.html)
- [v21.1/schema-design-update.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/schema-design-update.html)
- [v21.1/secure-a-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/secure-a-cluster.html)
- [v21.1/select-clause.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/select-clause.html)
- [v21.1/selection-queries.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/selection-queries.html)
- [v21.1/sql-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/sql-faqs.html)
- [v21.1/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/sql-feature-support.html)
- [v21.1/start-a-local-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/start-a-local-cluster.html)
- [v21.1/table-expressions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/table-expressions.html)
- [v21.1/update.md](http://cockroach-docs-review.s3-website-u [...]

2021-02-10 02:13 UTC, rafiss commented on v21.1/developer-guide-overview.md
> +To guarantee that database operations are [atomic](https://en.wikipedia.org/wiki/Atomicity_(database_systems)) (the "A" of the [ACID properties](https://en.wikipedia.org/wiki/ACID)), CockroachDB exec
maybe i'd say something like "all data mutations are applied together simultaneously from the perspective of operations outside of the transaction"

2021-02-10 02:21 UTC, rafiss commented on v21.1/developer-guide-overview.md
> +CockroachDB guarantees [`SERIALIZABLE`](https://en.wikipedia.org/wiki/Serializability) transaction [isolation](https://en.wikipedia.org/wiki/Isolation_(database_systems) (the "I" of ACID semantics).
should it say "highest level of data consistency" ?

maybe mention that it protects from bugs as well as attacks ?

2021-02-10 02:21 UTC, rafiss commented on v21.1/developer-guide-overview.md
> +A growing number of popular third-party database tools offer full support for CockroachDB, but, CockroachDB uses the PostgreSQL wire protocol and supports PostgreSQL syntax, most PostgreSQL-compatibl
missing the word "since" in the first sentence, i think

2021-02-10 02:21 UTC, rafiss commented on v21.1/developer-guide-overview.md
> +
we never get to the "C" and "D" of ACID -- is it worth a mention that we satisfy C by enforcing database constraints like uniqueness and foreign keys, and never allowing data to violate this constraint?

and D would be something mentioning storage.

2021-02-16 17:25 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/

Edited pages:
- [v21.1/alter-primary-key.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/alter-primary-key.html)
- [v21.1/build-a-java-app-with-cockroachdb-hibernate.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/build-a-java-app-with-cockroachdb-hibernate.html)
- [v21.1/build-a-java-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/build-a-java-app-with-cockroachdb.html)
- [v21.1/build-a-spring-app-with-cockroachdb-jdbc.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/build-a-spring-app-with-cockroachdb-jdbc.html)
- [v21.1/bulk-delete-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/bulk-delete-data.html)
- [v21.1/connect-to-the-database-cockroachcloud.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/connect-to-the-database-cockroachcloud.html)
- [v21.1/connect-to-the-database.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/connect-to-the-database.html)
- [v21.1/connection-parameters.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/connection-parameters.html)
- [v21.1/connection-pooling.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/connection-pooling.html)
- [v21.1/create-index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/create-index.html)
- [v21.1/create-table.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/create-table.html)
- [v21.1/delete-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/delete-data.html)
- [v21.1/delete.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/delete.html)
- [v21.1/developer-guide-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/developer-guide-overview.html)
- [v21.1/experimental-features.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/experimental-features.html)
- [v21.1/functions-and-operators.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/functions-and-operators.html)
- [v21.1/hash-sharded-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/hash-sharded-indexes.html)
- [v21.1/indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/indexes.html)
- [v21.1/insert.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/insert.html)
- [v21.1/install-client-drivers.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/install-client-drivers.html)
- [v21.1/interleave-in-parent.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/interleave-in-parent.html)
- [v21.1/joins.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/joins.html)
- [v21.1/jsonb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/jsonb.html)
- [v21.1/known-limitations.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/known-limitations.html)
- [v21.1/limit-offset.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/limit-offset.html)
- [v21.1/make-queries-fast.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/make-queries-fast.html)
- [v21.1/null-handling.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/null-handling.html)
- [v21.1/pagination.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/pagination.html)
- [v21.1/performance-best-practices-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/performance-best-practices-overview.html)
- [v21.1/primary-key.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/primary-key.html)
- [v21.1/query-behavior-troubleshooting.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/query-behavior-troubleshooting.html)
- [v21.1/query-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/query-data.html)
- [v21.1/run-multi-statement-transactions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/run-multi-statement-transactions.html)
- [v21.1/schema-design-database.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/schema-design-database.html)
- [v21.1/schema-design-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/schema-design-indexes.html)
- [v21.1/schema-design-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/schema-design-overview.html)
- [v21.1/schema-design-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/schema-design-schema.html)
- [v21.1/schema-design-table.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/schema-design-table.html)
- [v21.1/schema-design-update.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/schema-design-update.html)
- [v21.1/secure-a-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/secure-a-cluster.html)
- [v21.1/select-clause.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/select-clause.html)
- [v21.1/selection-queries.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/selection-queries.html)
- [v21.1/sql-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/sql-faqs.html)
- [v21.1/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/sql-feature-support.html)
- [v21.1/start-a-local-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/start-a-local-cluster.html)
- [v21.1/table-expressions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/table-expressions.html)
- [v21.1/update.md](http://cockroach-docs-review.s3-website-u [...]

2021-02-18 15:54 UTC, jseldess requested changes
This is looking great, @ericharmeling and @ianjevans. I have just a handful of comments and suggestions. Let me know when to take another look. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9724#-:-MTpqH84DKN5z4Gnk8MT:b-5g96iy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @drewdeally, @ericharmeling, @hand-crdb, @solongordon, and @vy-ton)

___
*[_includes/sidebar-data-v21.1.json, line 129 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTppj-dBkTEKW0polAc:-MTppj-dBkTEKW0polAd:bpq9czm) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/_includes/sidebar-data-v21.1.json#L129)):*
> ```JSON
>         "items": [
>           {
>             "title": "Overview",
> ```

Maybe we should make this page load when the user selects "Develop"? Like we've done for "Third-Party Database Tools".
___
*[_includes/sidebar-data-v21.1.json, line 138 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTph0ul2qAyBlqz8Rwo:-MTph0um7_koUscU524D:bs3kd2m) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/_includes/sidebar-data-v21.1.json#L138)):*
> ```JSON
>             "items": [
>               {
>                 "title": "Start a Cluster",
> ```

I think we should remove this "Start a Cluster" section. It's duplicative of what we have elsewhere, and we list starting a cluster as something to do before beginning on most pages here anyway.
___
*[_includes/sidebar-data-v21.1.json, line 172 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTphMLt5D89F7bJvW5_:-MTphMLt5D89F7bJvW5a:bjgh6vb) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/_includes/sidebar-data-v21.1.json#L172)):*
> ```JSON
>                 "items": [
>                   {
>                     "title": "Connection Pooling",
> ```

Do we have other advanced topics we'll add in phase 2? If not, I'd suggest we just bump connection pooling up one level. It might be nice to give it a more active title as well, e.g., `Use Connection Pools`.
___
*[_includes/sidebar-data-v21.1.json, line 185 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTppXEW2kBqkXLPYd4k:-MTppXEW2kBqkXLPYd4l:beqc41m) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/_includes/sidebar-data-v21.1.json#L185)):*
> ```JSON
>             "items": [
>               {
>                 "title": "Overview",
> ```

Maybe we should make this page load when the user selects "Design a Database Schema"? Like we've done for "Third-Party Database Tools".
___
*[_includes/sidebar-data-v21.1.json, line 235 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTpo17g6gQ-ouwM2qYv:-MTpo17g6gQ-ouwM2qYw:bjmb3mi) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/_includes/sidebar-data-v21.1.json#L235)):*
> ```JSON
>                 "items": [
>                   {
>                     "title": "Create Computed Columns",
> ```

Should we rename this `Use Computed Columns"? What about the page heading?
___
*[_includes/sidebar-data-v21.1.json, line 302 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTpoWgkECDrcjyc2MTy:-MTpoWgkECDrcjyc2MTz:b2fs75n) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/_includes/sidebar-data-v21.1.json#L302)):*
> ```JSON
>               },
>               {
>                 "title": "Manage Transactions",
> ```

I would prefer to move this to the first level of the dev guide, following "Write Data" and "Read Data". 
___
*[_includes/sidebar-data-v21.1.json, line 367 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTpp3-s-RUdTVDp-Zky:-MTpp3-s-RUdTVDp-Zkz:btluu8p) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/_includes/sidebar-data-v21.1.json#L367)):*
> ```JSON
>           },
>           {
>             "title": "Debug Your Application",
> ```

I think this section is ok for now, but eventually, we should think about making the guidance a lot more focused on application development rather than broad logging and monitoring. 
___
*[_includes/sidebar-data-v21.1.json, line 395 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTpprGRBcQ-S5kn8GQu:-MTpprGRBcQ-S5kn8GQv:b-6ghtha) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/_includes/sidebar-data-v21.1.json#L395)):*
> ```JSON
>             [
>               {
>                 "title": "Overview",
> ```

Maybe we should make this page load when the user selects "Optimize Performance"? Like we've done for "Third-Party Database Tools".
___
*[_includes/sidebar-data-v21.1.json, line 421 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTpq39r3G9bUxJGUCRw:-MTpq39r3G9bUxJGUCRx:bhrhvwp) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/_includes/sidebar-data-v21.1.json#L421)):*
> ```JSON
>                 "items": [
>                   {
>                     "title": "Overview",
> ```

Maybe we should make this page load when the user selects "Hello World"? Like we've done for "Third-Party Database Tools".
___
*[_includes/sidebar-data-v21.1.json, line 520 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTpq9Pz682Rrgsb6Cls:-MTpq9Q0-rmuiCvu1sme:b-3vzm31) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/_includes/sidebar-data-v21.1.json#L520)):*
> ```JSON
>                 "items": [
>                   {
>                     "title": "Overview",
> ```

Maybe we should make this page load when the user selects "MovR"? Like we've done for "Third-Party Database Tools".
___
*[v21.1/connection-pooling.md, line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTpiDx3D0hxzamRXiyc:-MTpiDx53H7pqVydBPpL:b-22g26i) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/connection-pooling.md#L13)):*
> ```Markdown
> A typical database operation consists of several steps.
> 
> 1. The driver uses a configuration to start a connection the database server.
> ```

`start a connection the database server` > `start a connection to the database server`
___
*[v21.1/connection-pooling.md, line 17 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTpiQ64Ab-s8LdBU7rh:-MTpiQ64Ab-s8LdBU7ri:bq26wfq) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/connection-pooling.md#L17)):*
> ```Markdown
> 1. Data is read or written through the network socket.
> 1. The connection is closed down.
> 1. The network socket is closed down and its resources freed.
> ```

nit: `resources freed` > `resources are freed`
___
*[v21.1/connection-pooling.md, line 19 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTpiVJ44Fvm698oGYlv:-MTpiVJ44Fvm698oGYlw:b-gfexl8) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/connection-pooling.md#L19)):*
> ```Markdown
> 1. The network socket is closed down and its resources freed.
> 
> For simple database operations, these steps are not expensive, but as an application scales up the performance of the application will suffer as each connection is created and destroyed. One pattern for improving performance is a connection pool, a group of already configured and established network connections between the client and database that can be reused for data operations within an application.
> ```

nit: `but as an application scales up, `
___
*[v21.1/connection-pooling.md, line 35 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTpixJcEhhgZs-vIUg8:-MTpixJd2moN7UCOmmg7:b-jfzm20) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/connection-pooling.md#L35)):*
> ```Markdown
> Cockroach Labs performed lab testing of vari [...]

2021-02-18 17:29 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/

Edited pages:
- [v21.1/alter-primary-key.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/alter-primary-key.html)
- [v21.1/build-a-java-app-with-cockroachdb-hibernate.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/build-a-java-app-with-cockroachdb-hibernate.html)
- [v21.1/build-a-java-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/build-a-java-app-with-cockroachdb.html)
- [v21.1/build-a-spring-app-with-cockroachdb-jdbc.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/build-a-spring-app-with-cockroachdb-jdbc.html)
- [v21.1/bulk-delete-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/bulk-delete-data.html)
- [v21.1/computed-columns.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/computed-columns.html)
- [v21.1/connect-to-the-database-cockroachcloud.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/connect-to-the-database-cockroachcloud.html)
- [v21.1/connect-to-the-database.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/connect-to-the-database.html)
- [v21.1/connection-parameters.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/connection-parameters.html)
- [v21.1/connection-pooling.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/connection-pooling.html)
- [v21.1/create-index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/create-index.html)
- [v21.1/create-table.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/create-table.html)
- [v21.1/delete-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/delete-data.html)
- [v21.1/delete.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/delete.html)
- [v21.1/developer-guide-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/developer-guide-overview.html)
- [v21.1/experimental-features.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/experimental-features.html)
- [v21.1/functions-and-operators.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/functions-and-operators.html)
- [v21.1/hash-sharded-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/hash-sharded-indexes.html)
- [v21.1/indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/indexes.html)
- [v21.1/insert.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/insert.html)
- [v21.1/install-client-drivers.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/install-client-drivers.html)
- [v21.1/interleave-in-parent.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/interleave-in-parent.html)
- [v21.1/joins.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/joins.html)
- [v21.1/jsonb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/jsonb.html)
- [v21.1/known-limitations.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/known-limitations.html)
- [v21.1/limit-offset.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/limit-offset.html)
- [v21.1/make-queries-fast.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/make-queries-fast.html)
- [v21.1/null-handling.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/null-handling.html)
- [v21.1/pagination.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/pagination.html)
- [v21.1/performance-best-practices-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/performance-best-practices-overview.html)
- [v21.1/primary-key.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/primary-key.html)
- [v21.1/query-behavior-troubleshooting.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/query-behavior-troubleshooting.html)
- [v21.1/query-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/query-data.html)
- [v21.1/run-multi-statement-transactions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/run-multi-statement-transactions.html)
- [v21.1/schema-design-database.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/schema-design-database.html)
- [v21.1/schema-design-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/schema-design-indexes.html)
- [v21.1/schema-design-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/schema-design-overview.html)
- [v21.1/schema-design-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/schema-design-schema.html)
- [v21.1/schema-design-table.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/schema-design-table.html)
- [v21.1/schema-design-update.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/schema-design-update.html)
- [v21.1/secure-a-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/secure-a-cluster.html)
- [v21.1/select-clause.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/select-clause.html)
- [v21.1/selection-queries.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/selection-queries.html)
- [v21.1/sql-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/sql-faqs.html)
- [v21.1/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/sql-feature-support.html)
- [v21.1/start-a-local-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/start-a-local-cluster.html)
- [v21.1/table-expressions.md](http://cockroach-docs-review.s3- [...]

2021-02-18 17:35 UTC, ericharmeling reviewed
TFTR @jseldess and @rafiss !

I went through your feedback and accepted most of your suggestions. Please see the latest commit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9724#-:-MTq7Bxz1ISDZUV_VXgK:bah7a7i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @drewdeally, @hand-crdb, @jseldess, @rafiss, @solongordon, and @vy-ton)

___
*[_includes/sidebar-data-v21.1.json, line 129 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTppj-dBkTEKW0polAc:-MTpuJJq11ObxkvzDDx-:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/_includes/sidebar-data-v21.1.json#L129)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Maybe we should make this page load when the user selects "Develop"? Like we've done for "Third-Party Database Tools".
</blockquote></details>

Done.
___
*[_includes/sidebar-data-v21.1.json, line 138 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTph0ul2qAyBlqz8Rwo:-MTpuQaN-moz4lOb68JU:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/_includes/sidebar-data-v21.1.json#L138)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

I think we should remove this "Start a Cluster" section. It's duplicative of what we have elsewhere, and we list starting a cluster as something to do before beginning on most pages here anyway.
</blockquote></details>

Done.
___
*[_includes/sidebar-data-v21.1.json, line 172 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTphMLt5D89F7bJvW5_:-MTpuUKFEImDYPE3VI8L:b-gseust) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/_includes/sidebar-data-v21.1.json#L172)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Do we have other advanced topics we'll add in phase 2? If not, I'd suggest we just bump connection pooling up one level. It might be nice to give it a more active title as well, e.g., `Use Connection Pools`.
</blockquote></details>

Done.

Load balancing was a top-requested topic - but that would be phase 2 and beyond. 
___
*[_includes/sidebar-data-v21.1.json, line 185 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTppXEW2kBqkXLPYd4k:-MTpupqK0E7w0G9RJW0x:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/_includes/sidebar-data-v21.1.json#L185)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Maybe we should make this page load when the user selects "Design a Database Schema"? Like we've done for "Third-Party Database Tools".
</blockquote></details>

Done.
___
*[_includes/sidebar-data-v21.1.json, line 235 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTpo17g6gQ-ouwM2qYv:-MTpuzaq8NOKP6XNLSzp:bwvqbb0) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/_includes/sidebar-data-v21.1.json#L235)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Should we rename this `Use Computed Columns"? What about the page heading?
</blockquote></details>

Done.

And done.
___
*[_includes/sidebar-data-v21.1.json, line 302 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTpoWgkECDrcjyc2MTy:-MTpv2oe13dfAzryDg2p:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/_includes/sidebar-data-v21.1.json#L302)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

I would prefer to move this to the first level of the dev guide, following "Write Data" and "Read Data". 
</blockquote></details>

Done.
___
*[_includes/sidebar-data-v21.1.json, line 367 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTpp3-s-RUdTVDp-Zky:-MTpvCO18kHzWe1cpAPj:bwygxsx) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/_includes/sidebar-data-v21.1.json#L367)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

I think this section is ok for now, but eventually, we should think about making the guidance a lot more focused on application development rather than broad logging and monitoring. 
</blockquote></details>

Noted.
___
*[_includes/sidebar-data-v21.1.json, line 395 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTpprGRBcQ-S5kn8GQu:-MTpvGXl4khHrXJXxFUV:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/_includes/sidebar-data-v21.1.json#L395)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Maybe we should make this page load when the user selects "Optimize Performance"? Like we've done for "Third-Party Database Tools".
</blockquote></details>

Done.
___
*[_includes/sidebar-data-v21.1.json, line 421 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTpq39r3G9bUxJGUCRw:-MTpvLZs0-DmeWmZl95V:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/_includes/sidebar-data-v21.1.json#L421)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Maybe we should make this page load when the user selects "Hello World"? Like we've done for "Third-Party Database Tools".
</blockquote></details>

Done.
___
*[_includes/sidebar-data-v21.1.json, line 520 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTpq9Pz682Rrgsb6Cls:-MTpvPw9CUBJHY_zVY3G:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/_includes/sidebar-data-v21.1.json#L520)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Maybe we should make this page load when the user selects "MovR"? Like we've done for "Third-Party Database Tools".
</blockquote></details>

Done.
___
*[v21.1/connection-pooling.md, line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTpiDx3D0hxzamRXiyc:-MTpvdyjDceKypu6EO4X:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/connection-pooling.md#L13)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

`start a connection the database server` > `start a connection to the database server`
</blockquote></details>

Done.
___
*[v21.1/connection-pooling.md, line 17 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTpiQ64Ab-s8LdBU7rh:-MTpvh471QV0qcZK6aWE:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/connection-pooling.md#L17)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

nit: `resources freed` > `resources are freed`
</blockquote></details>

Done.
___
*[v21.1/connection-pooling.md, line 19 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTpiVJ44Fvm698oGYlv:-MTpvkSa7FNRINTt1bsL:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/connection-pooling.md#L19)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

nit: `but as an application scales up, `
</blockquote></details>

Done.
___
*[v21.1/connection-pooling.md, line 35 at r1](https://reviewable.io/reviews/cockroachdb/docs/9724#-MTpixJcEhhgZs-vIUg8:-MTpvpS05HO7dxsagRQi:baczo3e) ([raw file](https://github.com/cockroachdb/docs/blob/3a0ac5dea45db6753698223e8f622d15001b849e/v21.1/connection-pooling.md#L35)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

I might make this a code-block so it stands out more. Or bold.
</blockquote></details>

Made it bold.
___
*[v21.1/developer-guide-overview.md, line 32 at r1](https://rev [...]

2021-02-18 17:52 UTC, jseldess commented on v21.1/schema-design-database.md
> +- [Start a local cluster](secure-a-cluster.html), or [create a CockroachCloud cluster](../cockroachcloud/create-your-cluster.html).
Can you make this same change to all of the other before you begin sections in this guide?

2021-02-18 17:55 UTC, jseldess approved these changes
Thanks, @ericharmeling! LGTM now, with a few final asks:

- Will you port the changes to 20.2 as well?
- On that topic, I think Rich is planning to move Working with Spatial Data into the dev section. Can you sync with him on that?
- I just noticed an unintended consequence of getting rid of those overviews in the sidenav: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1e09dbc106c0b399e600c9a91a4948a83050dbf9/dev/developer-guide-overview.html. When we load the develop overview on clicking Develop, everything under it is active (purple). That’s a styling bug. I’m sorry for the churn, but do you think you could revert those particular changes and open a docs issue for us to solve the styling bug before we reimplement?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9724#-:-MTqGmQx0YEybMYCxMfk:bl6nq22)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @drewdeally, @ericharmeling, @hand-crdb, @jseldess, @rafiss, @solongordon, and @vy-ton)



<!-- Sent from Reviewable.io -->

2021-02-18 20:05 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/

Edited pages:
- [v21.1/alter-primary-key.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/alter-primary-key.html)
- [v21.1/build-a-java-app-with-cockroachdb-hibernate.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/build-a-java-app-with-cockroachdb-hibernate.html)
- [v21.1/build-a-java-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/build-a-java-app-with-cockroachdb.html)
- [v21.1/build-a-spring-app-with-cockroachdb-jdbc.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/build-a-spring-app-with-cockroachdb-jdbc.html)
- [v21.1/bulk-delete-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/bulk-delete-data.html)
- [v21.1/computed-columns.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/computed-columns.html)
- [v21.1/connect-to-the-database-cockroachcloud.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/connect-to-the-database-cockroachcloud.html)
- [v21.1/connect-to-the-database.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/connect-to-the-database.html)
- [v21.1/connection-parameters.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/connection-parameters.html)
- [v21.1/connection-pooling.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/connection-pooling.html)
- [v21.1/create-index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/create-index.html)
- [v21.1/create-table.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/create-table.html)
- [v21.1/delete-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/delete-data.html)
- [v21.1/delete.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/delete.html)
- [v21.1/developer-guide-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/developer-guide-overview.html)
- [v21.1/experimental-features.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/experimental-features.html)
- [v21.1/functions-and-operators.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/functions-and-operators.html)
- [v21.1/hash-sharded-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/hash-sharded-indexes.html)
- [v21.1/indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/indexes.html)
- [v21.1/insert-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/insert-data.html)
- [v21.1/insert.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/insert.html)
- [v21.1/install-client-drivers.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/install-client-drivers.html)
- [v21.1/interleave-in-parent.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/interleave-in-parent.html)
- [v21.1/joins.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/joins.html)
- [v21.1/jsonb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/jsonb.html)
- [v21.1/known-limitations.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/known-limitations.html)
- [v21.1/limit-offset.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/limit-offset.html)
- [v21.1/make-queries-fast.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/make-queries-fast.html)
- [v21.1/null-handling.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/null-handling.html)
- [v21.1/pagination.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/pagination.html)
- [v21.1/performance-best-practices-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/performance-best-practices-overview.html)
- [v21.1/primary-key.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/primary-key.html)
- [v21.1/query-behavior-troubleshooting.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/query-behavior-troubleshooting.html)
- [v21.1/query-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/query-data.html)
- [v21.1/run-multi-statement-transactions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/run-multi-statement-transactions.html)
- [v21.1/schema-design-database.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/schema-design-database.html)
- [v21.1/schema-design-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/schema-design-indexes.html)
- [v21.1/schema-design-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/schema-design-overview.html)
- [v21.1/schema-design-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/schema-design-schema.html)
- [v21.1/schema-design-table.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/schema-design-table.html)
- [v21.1/schema-design-update.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/schema-design-update.html)
- [v21.1/secure-a-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/secure-a-cluster.html)
- [v21.1/select-clause.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/select-clause.html)
- [v21.1/selection-queries.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/selection-queries.html)
- [v21.1/sql-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/sql-faqs.html)
- [v21.1/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a1fdbe0a61b90f7ce77f1b8a35eaf4c203395bab/v21.1/sql-feature-support.html)
- [v21.1/start-a-local-cluster.md](http://cockroach-docs-review.s3-website-us-east- [...]

2021-02-18 21:23 UTC, ericharmeling reviewed
Awesome. Thanks!

1. Done. See the latest commit.
2. I followed up with Rich about this. I personally think we bout agree that we should wait until after we merge this PR to make any further ToC changes to the "Develop" section of the docs.
3. Reverted those changes. Here's the styling bug issue: https://github.com/cockroachdb/docs/issues/9826.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9724#-:-MTqd5Yn5pfhbto-NGH9:bdaktam)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @drewdeally, @hand-crdb, @jseldess, @rafiss, @solongordon, and @vy-ton)

___
*[v21.1/schema-design-database.md, line 18 at r2](https://reviewable.io/reviews/cockroachdb/docs/9724#-MSnHjqPmSDijRf8hDo9-r2-18:-MTqgFQN56CKhlWbtVlD:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/1e09dbc106c0b399e600c9a91a4948a83050dbf9/v21.1/schema-design-database.md#L18)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Can you make this same change to all of the other before you begin sections in this guide?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-18 22:25 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/

Edited pages:
- [v20.2/alter-primary-key.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/alter-primary-key.html)
- [v20.2/build-a-java-app-with-cockroachdb-hibernate.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/build-a-java-app-with-cockroachdb-hibernate.html)
- [v20.2/build-a-java-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/build-a-java-app-with-cockroachdb.html)
- [v20.2/build-a-spring-app-with-cockroachdb-jdbc.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/build-a-spring-app-with-cockroachdb-jdbc.html)
- [v20.2/bulk-delete-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/bulk-delete-data.html)
- [v20.2/computed-columns.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/computed-columns.html)
- [v20.2/connect-to-the-database-cockroachcloud.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/connect-to-the-database-cockroachcloud.html)
- [v20.2/connect-to-the-database.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/connect-to-the-database.html)
- [v20.2/connection-parameters.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/connection-parameters.html)
- [v20.2/connection-pooling.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/connection-pooling.html)
- [v20.2/create-index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/create-index.html)
- [v20.2/create-table.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/create-table.html)
- [v20.2/delete-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/delete-data.html)
- [v20.2/delete.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/delete.html)
- [v20.2/developer-guide-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/developer-guide-overview.html)
- [v20.2/experimental-features.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/experimental-features.html)
- [v20.2/functions-and-operators.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/functions-and-operators.html)
- [v20.2/hash-sharded-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/hash-sharded-indexes.html)
- [v20.2/indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/indexes.html)
- [v20.2/insert-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/insert-data.html)
- [v20.2/insert.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/insert.html)
- [v20.2/install-client-drivers.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/install-client-drivers.html)
- [v20.2/interleave-in-parent.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/interleave-in-parent.html)
- [v20.2/joins.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/joins.html)
- [v20.2/jsonb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/jsonb.html)
- [v20.2/known-limitations.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/known-limitations.html)
- [v20.2/limit-offset.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/limit-offset.html)
- [v20.2/make-queries-fast.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/make-queries-fast.html)
- [v20.2/null-handling.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/null-handling.html)
- [v20.2/pagination.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/pagination.html)
- [v20.2/performance-best-practices-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/performance-best-practices-overview.html)
- [v20.2/primary-key.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/primary-key.html)
- [v20.2/query-behavior-troubleshooting.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/query-behavior-troubleshooting.html)
- [v20.2/query-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/query-data.html)
- [v20.2/run-multi-statement-transactions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/run-multi-statement-transactions.html)
- [v20.2/schema-design-database.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/schema-design-database.html)
- [v20.2/schema-design-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/schema-design-indexes.html)
- [v20.2/schema-design-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/schema-design-overview.html)
- [v20.2/schema-design-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/schema-design-schema.html)
- [v20.2/schema-design-table.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/schema-design-table.html)
- [v20.2/schema-design-update.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/schema-design-update.html)
- [v20.2/secure-a-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/secure-a-cluster.html)
- [v20.2/select-clause.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/select-clause.html)
- [v20.2/selection-queries.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/selection-queries.html)
- [v20.2/sql-faqs.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/sql-faqs.html)
- [v20.2/sql-feature-support.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/03608a77053a93a4320211b9293a2691674ef59f/v20.2/sql-feature-support.html)
- [v20.2/start-a-local-cluster.md](http://cockroach-docs-review.s3-website-us-east- [...]

2021-02-19 00:38 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/

Edited pages:
- [releases/v20.2.0-alpha.1.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/releases/v20.2.0-alpha.1.html)
- [releases/v20.2.0-alpha.3.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/releases/v20.2.0-alpha.3.html)
- [releases/v20.2.0.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/releases/v20.2.0.html)
- [releases/v20.2.2.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/releases/v20.2.2.html)
- [releases/v20.2.3.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/releases/v20.2.3.html)
- [v20.2/alter-primary-key.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/alter-primary-key.html)
- [v20.2/build-a-java-app-with-cockroachdb-hibernate.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/build-a-java-app-with-cockroachdb-hibernate.html)
- [v20.2/build-a-java-app-with-cockroachdb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/build-a-java-app-with-cockroachdb.html)
- [v20.2/build-a-spring-app-with-cockroachdb-jdbc.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/build-a-spring-app-with-cockroachdb-jdbc.html)
- [v20.2/bulk-delete-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/bulk-delete-data.html)
- [v20.2/computed-columns.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/computed-columns.html)
- [v20.2/connect-to-the-database-cockroachcloud.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/connect-to-the-database-cockroachcloud.html)
- [v20.2/connect-to-the-database.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/connect-to-the-database.html)
- [v20.2/connection-parameters.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/connection-parameters.html)
- [v20.2/connection-pooling.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/connection-pooling.html)
- [v20.2/create-index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/create-index.html)
- [v20.2/create-table.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/create-table.html)
- [v20.2/delete-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/delete-data.html)
- [v20.2/delete.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/delete.html)
- [v20.2/developer-guide-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/developer-guide-overview.html)
- [v20.2/experimental-features.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/experimental-features.html)
- [v20.2/functions-and-operators.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/functions-and-operators.html)
- [v20.2/hash-sharded-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/hash-sharded-indexes.html)
- [v20.2/indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/indexes.html)
- [v20.2/insert-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/insert-data.html)
- [v20.2/insert.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/insert.html)
- [v20.2/install-client-drivers.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/install-client-drivers.html)
- [v20.2/interleave-in-parent.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/interleave-in-parent.html)
- [v20.2/joins.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/joins.html)
- [v20.2/jsonb.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/jsonb.html)
- [v20.2/known-limitations.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/known-limitations.html)
- [v20.2/limit-offset.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/limit-offset.html)
- [v20.2/make-queries-fast.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/make-queries-fast.html)
- [v20.2/null-handling.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/null-handling.html)
- [v20.2/pagination.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/pagination.html)
- [v20.2/performance-best-practices-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/performance-best-practices-overview.html)
- [v20.2/primary-key.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/primary-key.html)
- [v20.2/query-behavior-troubleshooting.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/query-behavior-troubleshooting.html)
- [v20.2/query-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/query-data.html)
- [v20.2/run-multi-statement-transactions.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/run-multi-statement-transactions.html)
- [v20.2/schema-design-database.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/schema-design-database.html)
- [v20.2/schema-design-indexes.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/schema-design-indexes.html)
- [v20.2/schema-design-overview.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/schema-design-overview.html)
- [v20.2/schema-design-schema.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/schema-design-schema.html)
- [v20.2/schema-design-table.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/schema-design-table.html)
- [v20.2/schema-design-update.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f124a5ebd3eb478d08e44223b91f6beaea368a/v20.2/schema-design-update.html)
- [v20.2/secure-a-cluster.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/64f [...]

2021-02-19 00:42 UTC, merged