v20.2.5 release notes
cockroachdb/docs pull request #9730
Opened 2021-02-08 18:23 UTC by ericharmeling

Fixes https://github.com/cockroachdb/docs/issues/8928.

2021-02-08 18:23 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/9730)
<!-- Reviewable:end -->

2021-02-08 18:26 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cff7c62b8f9142d20def92d5a5e302083fde42ec/

Edited pages:
- [releases/v20.2.5.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/cff7c62b8f9142d20def92d5a5e302083fde42ec/releases/v20.2.5.html)

2021-02-10 18:59 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/38378a79095f0f991c277e0aa81a68f4a599f8dc/

Edited pages:
- [releases/v20.2.5.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/38378a79095f0f991c277e0aa81a68f4a599f8dc/releases/v20.2.5.html)

2021-02-16 15:33 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/9a4dc05ce7b2fd53389156a7fe688a9a2debdf72/

Edited pages:
- [releases/v20.2.5.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/9a4dc05ce7b2fd53389156a7fe688a9a2debdf72/releases/v20.2.5.html)

2021-02-16 16:14 UTC, jseldess requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9730)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @ericharmeling, and @ianjevans)

___
*[releases/v20.2.5.md, line 9 at r2](https://reviewable.io/reviews/cockroachdb/docs/9730#-MTfbSva-6WCIu6Hg0MO:-MTfbSva-6WCIu6Hg0MP:b-iq3f22) ([raw file](https://github.com/cockroachdb/docs/blob/9a4dc05ce7b2fd53389156a7fe688a9a2debdf72/releases/v20.2.5.md#L9)):*
> ```Markdown
> ## February 16, 2021
> 
> Get future release notes emailed to you:
> ```

@ericharmeling, I think you forgot to pass the `--prod-release` flag when generating these notes. So please manually change this intro to:

```
This page lists additions and changes in v20.2.4 since v20.2.3.

- For a comprehensive summary of features in v20.2, see the [v20.2 GA release notes](v20.2.0.html).
- To upgrade to v20.2, see [Upgrade to CockroachDB v20.2](../v20.2/upgrade-cockroach-version.html)

Get future release notes emailed to you:

{% include marketo.html %}
```
___
*[releases/v20.2.5.md, line 27 at r2](https://reviewable.io/reviews/cockroachdb/docs/9730#-MTfbetw92HEadZHHzQ5:-MTfbetw92HEadZHHzQ6:bm0up9a) ([raw file](https://github.com/cockroachdb/docs/blob/9a4dc05ce7b2fd53389156a7fe688a9a2debdf72/releases/v20.2.5.md#L27)):*
> ```Markdown
> {% include copy-clipboard.html %}
> ~~~shell
> $ docker pull cockroachdb/cockroach-unstable:v20.2.5
> ```

Please change `cockroach-unstable:v20.2.5` to `cockroach:v20.2.5`. That's another thing the `--prod-release` flag would've done differently


<!-- Sent from Reviewable.io -->

2021-02-16 16:26 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/2bbbbee2be8b2ab26ea589be8a2d5b41584185eb/

Edited pages:
- [releases/v20.2.5.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/2bbbbee2be8b2ab26ea589be8a2d5b41584185eb/releases/v20.2.5.html)

2021-02-16 16:35 UTC, ianjevans approved these changes

2021-02-16 16:38 UTC, merged