Peter fixes pri
cockroachdb/docs pull request #9766
Opened 2021-02-09 10:56 UTC by anagio

priority fixes

2021-02-09 10:56 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/9766)
<!-- Reviewable:end -->

2021-02-09 11:02 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7c6d12da69cd0b3982e38bf4ff2a74b16fa9a918/

Edited pages:
- [cockroachcloud/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7c6d12da69cd0b3982e38bf4ff2a74b16fa9a918/cockroachcloud/index.html)
- [v20.1/architecture/life-of-a-distributed-transaction.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7c6d12da69cd0b3982e38bf4ff2a74b16fa9a918/v20.1/architecture/life-of-a-distributed-transaction.html)
- [v20.2/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7c6d12da69cd0b3982e38bf4ff2a74b16fa9a918/v20.2/index.html)

2021-02-09 18:32 UTC, lnhsingh commented
These changes LGTM - @jseldess / @luciaaaaaaa can you take a look?

Closes #9656, #9559, #9437, #9560, #9667.

2021-02-09 19:08 UTC, jseldess requested changes
I don't think #9656 is fixed yet. All of the others LGTM.

2021-02-09 19:11 UTC, jseldess commented on v20.1/architecture/life-of-a-distributed-transaction.md
> +  	- If this push fails (which is the majority of the time), this transaction goes into the [`TxnWaitQueue`](/docs/stable/architecture/transaction-layer.html#txnwaitqueue) on this node. The incoming
This works, but I think we should just use `transaction-layer.html#txnwaitqueue`, as the target file is in the same directory. 

@anagio, we need to make this same change to other versions of this page.

2021-02-11 02:53 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/927a73f11217ebc33666b3e0f0da1deed8accf05/

Edited pages:
- [cockroachcloud/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/927a73f11217ebc33666b3e0f0da1deed8accf05/cockroachcloud/index.html)
- [v19.1/architecture/life-of-a-distributed-transaction.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/927a73f11217ebc33666b3e0f0da1deed8accf05/v19.1/architecture/life-of-a-distributed-transaction.html)
- [v19.2/architecture/life-of-a-distributed-transaction.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/927a73f11217ebc33666b3e0f0da1deed8accf05/v19.2/architecture/life-of-a-distributed-transaction.html)
- [v20.1/architecture/life-of-a-distributed-transaction.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/927a73f11217ebc33666b3e0f0da1deed8accf05/v20.1/architecture/life-of-a-distributed-transaction.html)
- [v20.2/architecture/life-of-a-distributed-transaction.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/927a73f11217ebc33666b3e0f0da1deed8accf05/v20.2/architecture/life-of-a-distributed-transaction.html)
- [v20.2/index.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/927a73f11217ebc33666b3e0f0da1deed8accf05/v20.2/index.html)
- [v21.1/architecture/life-of-a-distributed-transaction.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/927a73f11217ebc33666b3e0f0da1deed8accf05/v21.1/architecture/life-of-a-distributed-transaction.html)

2021-02-11 07:47 UTC, merged