Update deployment tutorial start nodes step for spatial
cockroachdb/docs pull request #9825
Opened 2021-02-18 18:30 UTC by jseldess

Fixes #9820.

2021-02-18 18:31 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/9825)
<!-- Reviewable:end -->

2021-02-18 18:38 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/fe1f98db2c245962f185cd3d67ee5ec5f4f98246/

2021-02-22 22:35 UTC, rmloveland requested changes
All good except there is an unrendered section that looks like it can be deleted from the v20.2 insecure page (see inline comment)

2021-02-22 22:35 UTC, rmloveland commented on _includes/v20.2/prod-deployment/insecure-start-nodes.md
> +echo 'Installing CockroachDB v20.2 and supporting spatial libraries...'
Looking at the [CI-built page](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/fe1f98db2c245962f185cd3d67ee5ec5f4f98246/stable/deploy-cockroachdb-on-premises-insecure.html) it looks like this section is not rendered in a code block.  But it seems like it's supposed to be.  Is that correct?

2021-02-22 22:35 UTC, rmloveland commented on _includes/v20.2/prod-deployment/insecure-start-nodes.md
> +wget -qO- https://binaries.cockroachdb.com/cockroach-v20.2.5.linux-amd64.tgz | tar  xvz
It looks like this unrendered section might not be necessary / can be deleted?  Since it appears to duplicate what is below.

2021-02-23 03:04 UTC, jseldess reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9825)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rmloveland)

___
*[_includes/v20.2/prod-deployment/insecure-start-nodes.md, line 27 at r1](https://reviewable.io/reviews/cockroachdb/docs/9825#-MTqPDDWTqLBMSRIsd81-r1-27:-MUBq-KQ3UStEehRhsdU:biyglu2) ([raw file](https://github.com/cockroachdb/docs/blob/fe1f98db2c245962f185cd3d67ee5ec5f4f98246/_includes/v20.2/prod-deployment/insecure-start-nodes.md#L27)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Looking at the [CI-built page](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/fe1f98db2c245962f185cd3d67ee5ec5f4f98246/stable/deploy-cockroachdb-on-premises-insecure.html) it looks like this section is not rendered in a code block.  But it seems like it's supposed to be.  Is that correct?
</blockquote></details>

Whoops. That's just copy-paste error. Thanks for catching it! Removed.
___
*[_includes/v20.2/prod-deployment/insecure-start-nodes.md, line 29 at r1](https://reviewable.io/reviews/cockroachdb/docs/9825#-MTqPDDWTqLBMSRIsd81-r1-29:-MUBq3x42538ZKsKSV9C:ba02hrp) ([raw file](https://github.com/cockroachdb/docs/blob/fe1f98db2c245962f185cd3d67ee5ec5f4f98246/_includes/v20.2/prod-deployment/insecure-start-nodes.md#L29)):*
> Whoops. That's just copy-paste error. Thanks for catching it! Removed.
Same as above. Removed. 


<!-- Sent from Reviewable.io -->

2021-02-23 03:08 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/5d7367a6a1b07092e7c9e31e0a3c69d5d87aa8bf/

2021-02-25 15:23 UTC, rmloveland approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9825#-:-MUOmMpO2WM1lRHZ-d47:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jseldess and @rmloveland)

___
*[_includes/v20.2/prod-deployment/insecure-start-nodes.md, line 27 at r1](https://reviewable.io/reviews/cockroachdb/docs/9825#-MTqPDDWTqLBMSRIsd81-r1-27:-MUOmHqABj_CvgrKFgTF:b2ni8oq) ([raw file](https://github.com/cockroachdb/docs/blob/fe1f98db2c245962f185cd3d67ee5ec5f4f98246/_includes/v20.2/prod-deployment/insecure-start-nodes.md#L27)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Whoops. That's just copy-paste error. Thanks for catching it! Removed.
</blockquote></details>

np!


<!-- Sent from Reviewable.io -->

2021-02-25 18:16 UTC, merged