Dg2 update data
cockroachdb/docs pull request #9993
Opened 2021-03-15 17:14 UTC by ericharmeling

Fixes https://github.com/cockroachdb/docs/issues/9862.

2021-03-15 17:14 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/9993)
<!-- Reviewable:end -->

2021-03-15 17:20 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1ef2eae1bb9dd10f90fef993cf819656636b0848/

Edited pages:
- [v21.1/update-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1ef2eae1bb9dd10f90fef993cf819656636b0848/v21.1/update-data.html)

2021-03-17 17:42 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/78e4ec3e40f56c8701497729c24e0b1d0ac5129f/

Edited pages:
- [v21.1/update-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/78e4ec3e40f56c8701497729c24e0b1d0ac5129f/v21.1/update-data.html)

2021-03-17 19:03 UTC, rafiss requested changes

2021-03-17 19:03 UTC, rafiss commented on v21.1/update-data.md
> +rulesOne := "{\"type\": \"percent_discount\", \"value\": \"15%\"}"
to avoid the need for `\` escaping, it could be 

```
rulesOne := `{"type": "percent_discount", "value": "15%"}`
```

2021-03-17 19:03 UTC, rafiss commented on v21.1/update-data.md
> +// tx is a *sql.Tx from "database/sql"
could be a `*sql.DB`

2021-03-17 19:03 UTC, rafiss commented on v21.1/update-data.md
> +    connection.createStatement().executeUpdate("INSERT INTO user_promo_codes VALUES ('" + city + "','" + userId
this should use `?` placeholders

2021-03-17 19:03 UTC, rafiss commented on v21.1/update-data.md
> +    conn.commit()
should the commit be outside of the `with` block? i'm actually not sure off the top of my head which is right, but this differs from the DELETE code sample

2021-03-17 19:03 UTC, rafiss commented on v21.1/update-data.md
> +    conn.commit()
make sure `commit` is in the right spot

2021-03-17 19:03 UTC, rafiss commented on v21.1/update-data.md
> +    conn.commit()
make sure `commit` is in the right spot

2021-03-18 17:56 UTC, ericharmeling reviewed
TFTR @rafiss !

I think I addressed all of your feedback in the latest commit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9993#-:-MW5TbuP7Yzo69aRzifb:ba5rnoh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[v21.1/update-data.md, line 92 at r2](https://reviewable.io/reviews/cockroachdb/docs/9993#-MVqsNVhMxvK3lMq3kIN-r2-92:-MW5QcQk8aZXo8bjbFqx:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/78e4ec3e40f56c8701497729c24e0b1d0ac5129f/v21.1/update-data.md#L92)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

we could use `*sql.DB` here if a txn is not desired
</blockquote></details>

Done.
___
*[v21.1/update-data.md, line 110 at r2](https://reviewable.io/reviews/cockroachdb/docs/9993#-MVqsNVhMxvK3lMq3kIN-r2-110:-MW5IMPoAOG9gwgr0KIs:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/78e4ec3e40f56c8701497729c24e0b1d0ac5129f/v21.1/update-data.md#L110)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

avoid string appending (similar to deletes)

```
PreparedStatement p = connection.prepareStatement("UPDATE vehicles SET status = 'unavailable' WHERE owner_id = ?");
p.setString(1, ownerID);
p.executeUpdate(); 
```
</blockquote></details>

Done.
___
*[v21.1/update-data.md, line 131 at r2](https://reviewable.io/reviews/cockroachdb/docs/9993#-MVqsNVhMxvK3lMq3kIN-r2-131:-MW5J8MF5kLP5PZjq1tb:bf81gxw) ([raw file](https://github.com/cockroachdb/docs/blob/78e4ec3e40f56c8701497729c24e0b1d0ac5129f/v21.1/update-data.md#L131)):*
I actually don't think you need `conn.commit()` at all, if you are using a `with` block.

From https://www.psycopg.org/docs/connection.html#connection.commit:

>  if the connection is used in a with statement, the method is automatically called if no exception is raised in the with block.

From https://www.psycopg.org/docs/usage.html#with-statement:

> Starting from version 2.5, psycopg2’s connections and cursors are context managers and can be used with the with statement:

> with psycopg2.connect(DSN) as conn:
    with conn.cursor() as curs:
        curs.execute(SQL)

> When a connection exits the with block, if no exception has been raised by the block, the transaction is committed. In case of exception the transaction is rolled back.

Removed it from all of the samples.
___
*[v21.1/update-data.md, line 192 at r2](https://reviewable.io/reviews/cockroachdb/docs/9993#-MVqsNVhMxvK3lMq3kIN-r2-192:-MW5Qdpe0GNoq5fLiAbs:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/78e4ec3e40f56c8701497729c24e0b1d0ac5129f/v21.1/update-data.md#L192)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could be a `*sql.DB`
</blockquote></details>

Done.
___
*[v21.1/update-data.md, line 196 at r2](https://reviewable.io/reviews/cockroachdb/docs/9993#-MVqsNVhMxvK3lMq3kIN-r2-196:-MW5KF1u7S3XbSO9_Dn1:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/78e4ec3e40f56c8701497729c24e0b1d0ac5129f/v21.1/update-data.md#L196)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

to avoid the need for `\` escaping, it could be 

```
rulesOne := `{"type": "percent_discount", "value": "15%"}`
```
</blockquote></details>

Done.
___
*[v21.1/update-data.md, line 234 at r2](https://reviewable.io/reviews/cockroachdb/docs/9993#-MVqsNVhMxvK3lMq3kIN-r2-234:-MW5JGss5vlRXEC64CzK:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/78e4ec3e40f56c8701497729c24e0b1d0ac5129f/v21.1/update-data.md#L234)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this should switch to using `?` placeholders

maybe using a loop over a hardcoded array would make it easier to set all the arguments
</blockquote></details>

Done.
___
*[v21.1/update-data.md, line 265 at r2](https://reviewable.io/reviews/cockroachdb/docs/9993#-MVqsNVhMxvK3lMq3kIN-r2-265:-MW5JHqjCCNv2WO-ZTvW:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/78e4ec3e40f56c8701497729c24e0b1d0ac5129f/v21.1/update-data.md#L265)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

make sure `commit` is in the right spot
</blockquote></details>

Done.
___
*[v21.1/update-data.md, line 335 at r2](https://reviewable.io/reviews/cockroachdb/docs/9993#-MVqsNVhMxvK3lMq3kIN-r2-335:-MW5Qf5N18JEfyF0FJO1:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/78e4ec3e40f56c8701497729c24e0b1d0ac5129f/v21.1/update-data.md#L335)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could be a `*sql.DB`
</blockquote></details>

Done.
___
*[v21.1/update-data.md, line 368 at r2](https://reviewable.io/reviews/cockroachdb/docs/9993#-MVqsNVhMxvK3lMq3kIN-r2-368:-MW5JIX0CH300cDUAfrE:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/78e4ec3e40f56c8701497729c24e0b1d0ac5129f/v21.1/update-data.md#L368)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this should use `?` placeholders
</blockquote></details>

Done.
___
*[v21.1/update-data.md, line 395 at r2](https://reviewable.io/reviews/cockroachdb/docs/9993#-MVqsNVhMxvK3lMq3kIN-r2-395:-MW5JJCNAQyC_K7NYuR-:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/78e4ec3e40f56c8701497729c24e0b1d0ac5129f/v21.1/update-data.md#L395)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

make sure `commit` is in the right spot
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-18 17:59 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1b9834af2ab531614b82c53436fa6c568f0ddc5/

Edited pages:
- [v21.1/update-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1b9834af2ab531614b82c53436fa6c568f0ddc5/v21.1/update-data.html)

2021-03-19 15:18 UTC, ianjevans approved these changes

2021-03-22 13:15 UTC, cockroach-teamcity commented
Online preview: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c7cb468faec84dc270f00c031df7f7af4b720cd8/

Edited pages:
- [v20.2/update-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c7cb468faec84dc270f00c031df7f7af4b720cd8/v20.2/update-data.html)
- [v21.1/update-data.md](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c7cb468faec84dc270f00c031df7f7af4b720cd8/v21.1/update-data.html)

2021-03-22 13:29 UTC, merged